--
-- DISTRIBUCION_MASIVA_LOG_TRG  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DISTRIBUCION_MASIVA_LOG (Table)
--   DISTRIBUCION_MASIVA_LOG_SEQ (Sequence)
--
CREATE OR REPLACE TRIGGER SICAS_OC.DISTRIBUCION_MASIVA_LOG_TRG
BEFORE INSERT
ON SICAS_OC.DISTRIBUCION_MASIVA_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column NUMSECUENCIA
  :new.NUMSECUENCIA := DISTRIBUCION_MASIVA_LOG_SEQ.nextval;
END DISTRIBUCION_MASIVA_LOG_TRG;
/
