
  CREATE OR REPLACE TRIGGER "SICAS_OC"."DISTRIBUCION_MASIVA_LOG_TRG" 
BEFORE INSERT
ON SICAS_OC.DISTRIBUCION_MASIVA_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column NUMSECUENCIA
  :new.NUMSECUENCIA := DISTRIBUCION_MASIVA_LOG_SEQ.nextval;
END DISTRIBUCION_MASIVA_LOG_TRG;

ALTER TRIGGER "SICAS_OC"."DISTRIBUCION_MASIVA_LOG_TRG" ENABLE
