
  CREATE OR REPLACE TRIGGER "SICAS_OC"."TEMP_REPORTES_THONA_TRG" 
BEFORE INSERT
ON SICAS_OC.TEMP_REPORTES_THONA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDSECUENCIA
  :new.IDSECUENCIA := SICAS_OC.TEMP_REPORTES_THONA_SEQ.nextval;
END TEMP_REPORTES_THONA_TRG;
ALTER TRIGGER "SICAS_OC"."TEMP_REPORTES_THONA_TRG" ENABLE
