--
-- TEMP_REPORTES_THONA_TRG  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   TEMP_REPORTES_THONA (Table)
--   TEMP_REPORTES_THONA_SEQ (Sequence)
--
CREATE OR REPLACE TRIGGER SICAS_OC.TEMP_REPORTES_THONA_TRG
BEFORE INSERT
ON SICAS_OC.TEMP_REPORTES_THONA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDSECUENCIA
  :new.IDSECUENCIA := SICAS_OC.TEMP_REPORTES_THONA_SEQ.nextval;
END TEMP_REPORTES_THONA_TRG;
/
