
  CREATE OR REPLACE TRIGGER "SICAS_OC"."TG_INSERT_PM" 
 BEFORE 
 INSERT
 ON PROCESOS_MASIVOS
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW 
DECLARE
BEGIN
 IF  :NEW.IdProcMasivo IS NULL THEN 
 :NEW.IdProcMasivo := OC_PROCESOS_MASIVOS.CREAR(:NEW.CodCia,:NEW.CodEmpresa);
END IF; 
END;






ALTER TRIGGER "SICAS_OC"."TG_INSERT_PM" ENABLE
