CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_PLANTILLAS_CAMPOS
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_PLANTILLAS_CAMPOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_PLANTILLAS_CAMPOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODPLANTILLA)||' - '||TO_CHAR(:OLD.NOMTABLA)||' - '||TO_CHAR(:OLD.ORDENPROCESO)||' - '||
                  TO_CHAR(:OLD.ORDENCAMPO)||' - '||TO_CHAR(:OLD.NOMCAMPO)||' - '||TO_CHAR(:OLD.INDCLAVEPRIMARIA)||' - '||TO_CHAR(:OLD.TIPOCAMPO)||' - '||TO_CHAR(:OLD.POSINICAMPO)||' - '||
                  TO_CHAR(:OLD.LONGITUDCAMPO)||' - '||TO_CHAR(:OLD.NUMDECIMALES)||' - '||TO_CHAR(:OLD.VALORDEFAULT)||' - '||TO_CHAR(:OLD.SQLVALIDACION)||' - '||TO_CHAR(:OLD.SQLVALORCAMPO)||' - '||
                  TO_CHAR(:OLD.INDDATOPART)||' - '||TO_CHAR(:OLD.ORDENDATOPART)||' - '||TO_CHAR(:OLD.INDASEG);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODPLANTILLA)||' - '||TO_CHAR(:NEW.NOMTABLA)||' - '||TO_CHAR(:NEW.ORDENPROCESO)||' - '||
                  TO_CHAR(:NEW.ORDENCAMPO)||' - '||TO_CHAR(:NEW.NOMCAMPO)||' - '||TO_CHAR(:NEW.INDCLAVEPRIMARIA)||' - '||TO_CHAR(:NEW.TIPOCAMPO)||' - '||TO_CHAR(:NEW.POSINICAMPO)||' - '||
                  TO_CHAR(:NEW.LONGITUDCAMPO)||' - '||TO_CHAR(:NEW.NUMDECIMALES)||' - '||TO_CHAR(:NEW.VALORDEFAULT)||' - '||TO_CHAR(:NEW.SQLVALIDACION)||' - '||TO_CHAR(:NEW.SQLVALORCAMPO)||' - '||
                  TO_CHAR(:NEW.INDDATOPART)||' - '||TO_CHAR(:NEW.ORDENDATOPART)||' - '||TO_CHAR(:NEW.INDASEG);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPLANTILLA <> :OLD.CODPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'CODPLANTILLA', TO_CHAR(:OLD.CODPLANTILLA), TO_CHAR(:NEW.CODPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NOMTABLA <> :OLD.NOMTABLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'NOMTABLA', TO_CHAR(:OLD.NOMTABLA), TO_CHAR(:NEW.NOMTABLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORDENPROCESO <> :OLD.ORDENPROCESO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'ORDENPROCESO', TO_CHAR(:OLD.ORDENPROCESO), TO_CHAR(:NEW.ORDENPROCESO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORDENCAMPO <> :OLD.ORDENCAMPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'ORDENCAMPO', TO_CHAR(:OLD.ORDENCAMPO), TO_CHAR(:NEW.ORDENCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NOMCAMPO <> :OLD.NOMCAMPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'NOMCAMPO', TO_CHAR(:OLD.NOMCAMPO), TO_CHAR(:NEW.NOMCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCLAVEPRIMARIA,-20000) <> NVL(:OLD.INDCLAVEPRIMARIA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'INDCLAVEPRIMARIA', TO_CHAR(:OLD.INDCLAVEPRIMARIA), TO_CHAR(:NEW.INDCLAVEPRIMARIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOCAMPO <> :OLD.TIPOCAMPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'TIPOCAMPO', TO_CHAR(:OLD.TIPOCAMPO), TO_CHAR(:NEW.TIPOCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.POSINICAMPO <> :OLD.POSINICAMPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'POSINICAMPO', TO_CHAR(:OLD.POSINICAMPO), TO_CHAR(:NEW.POSINICAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.LONGITUDCAMPO <> :OLD.LONGITUDCAMPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'LONGITUDCAMPO', TO_CHAR(:OLD.LONGITUDCAMPO), TO_CHAR(:NEW.LONGITUDCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUMDECIMALES <> :OLD.NUMDECIMALES) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'NUMDECIMALES', TO_CHAR(:OLD.NUMDECIMALES), TO_CHAR(:NEW.NUMDECIMALES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.VALORDEFAULT,-20000) <> NVL(:OLD.VALORDEFAULT,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'VALORDEFAULT', TO_CHAR(:OLD.VALORDEFAULT), TO_CHAR(:NEW.VALORDEFAULT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SQLVALIDACION,-20000) <> NVL(:OLD.SQLVALIDACION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'SQLVALIDACION', TO_CHAR(:OLD.SQLVALIDACION), TO_CHAR(:NEW.SQLVALIDACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SQLVALORCAMPO,-20000) <> NVL(:OLD.SQLVALORCAMPO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'SQLVALORCAMPO', TO_CHAR(:OLD.SQLVALORCAMPO), TO_CHAR(:NEW.SQLVALORCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDDATOPART,-20000) <> NVL(:OLD.INDDATOPART,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'INDDATOPART', TO_CHAR(:OLD.INDDATOPART), TO_CHAR(:NEW.INDDATOPART), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENDATOPART,-20000) <> NVL(:OLD.ORDENDATOPART,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'ORDENDATOPART', TO_CHAR(:OLD.ORDENDATOPART), TO_CHAR(:NEW.ORDENDATOPART), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDASEG,-20000) <> NVL(:OLD.INDASEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_CAMPOS', 'INDASEG', TO_CHAR(:OLD.INDASEG), TO_CHAR(:NEW.INDASEG), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_PLANTILLAS_CAMPOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_PLANTILLAS_CAMPOS FOR SICAS_OC.TRG_CONFIG_PLANTILLAS_CAMPOS;
