CREATE OR REPLACE TRIGGER SICAS_OC.TRG_FAI_TIPOS_FONDOS_PRODUCTOS
  BEFORE INSERT OR UPDATE OR DELETE ON FAI_TIPOS_FONDOS_PRODUCTOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA FAI_TIPOS_FONDOS_PRODUCTOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.TIPOFONDO)||' - '||TO_CHAR(:OLD.PORCFONDO)||' - '||
                  TO_CHAR(:OLD.INDFONDOOBLIG)||' - '||TO_CHAR(:OLD.ORDENFONDO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.TIPOFONDO)||' - '||TO_CHAR(:NEW.PORCFONDO)||' - '||
                  TO_CHAR(:NEW.INDFONDOOBLIG)||' - '||TO_CHAR(:NEW.ORDENFONDO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOFONDO <> :OLD.TIPOFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'TIPOFONDO', TO_CHAR(:OLD.TIPOFONDO), TO_CHAR(:NEW.TIPOFONDO),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PORCFONDO <> :OLD.PORCFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'PORCFONDO', TO_CHAR(:OLD.PORCFONDO), TO_CHAR(:NEW.PORCFONDO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDFONDOOBLIG,-20000) <> NVL(:OLD.INDFONDOOBLIG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'INDFONDOOBLIG', TO_CHAR(:OLD.INDFONDOOBLIG), TO_CHAR(:NEW.INDFONDOOBLIG),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENFONDO,-20000) <> NVL(:OLD.ORDENFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_FONDOS_PRODUCTOS', 'ORDENFONDO', TO_CHAR(:OLD.ORDENFONDO), TO_CHAR(:NEW.ORDENFONDO),'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de FAI_TIPOS_FONDOS_PRODUCTOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_FAI_TIPOS_FONDOS_PRODUCTOS FOR SICAS_OC.TRG_FAI_TIPOS_FONDOS_PRODUCTOS;
