CREATE OR REPLACE TRIGGER SICAS_OC.TRG_FAI_TIPOS_DE_FONDOS
  BEFORE INSERT OR UPDATE OR DELETE ON FAI_TIPOS_DE_FONDOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA FAI_TIPOS_DE_FONDOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.TIPOFONDO)||' - '||TO_CHAR(:OLD.DESCFONDO)||' - '||TO_CHAR(:OLD.CODMONEDA)||' - '||TO_CHAR(:OLD.PORCFONDO)||' - '||
                  TO_CHAR(:OLD.STSFONDO)||' - '||TO_CHAR(:OLD.FECSTATUS)||' - '||TO_CHAR(:OLD.EDADMIN)||' - '||TO_CHAR(:OLD.EDADMAX)||' - '||TO_CHAR(:OLD.EDADRETIRO)||' - '||TO_CHAR(:OLD.MTOAPORTEMIN)||' - '||
                  TO_CHAR(:OLD.MTOAPORTEMAX)||' - '||TO_CHAR(:OLD.MTOAPORTEINI)||' - '||TO_CHAR(:OLD.INDAPORTES)||' - '||TO_CHAR(:OLD.INDGENAPORTEINI)||' - '||TO_CHAR(:OLD.CODAPORTINI)||' - '||TO_CHAR(:OLD.INDRETPARCIALES)||' - '||
                  TO_CHAR(:OLD.INDRETTOTALES)||' - '||TO_CHAR(:OLD.INDAJUSTES)||' - '||TO_CHAR(:OLD.INDTRASPASO)||' - '||TO_CHAR(:OLD.INDPRESTAMOS)||' - '||TO_CHAR(:OLD.PORCPRESTAMOS)||' - '||TO_CHAR(:OLD.CALCINTPRESTAMOS)||' - '||
                  TO_CHAR(:OLD.TIPOINTPRESTAMOS)||' - '||TO_CHAR(:OLD.INDDESCINTFONDO)||' - '||TO_CHAR(:OLD.INDDESCPTMOFONDO)||' - '||TO_CHAR(:OLD.INDCOMISION)||' - '||TO_CHAR(:OLD.INDINCENTIVOS)||' - '||TO_CHAR(:OLD.TIPOINTERES)||' - '||
                  TO_CHAR(:OLD.TIEMPOMINIMO)||' - '||TO_CHAR(:OLD.NUMDIASANUL)||' - '||TO_CHAR(:OLD.ANOINDISPUT)||' - '||TO_CHAR(:OLD.INDAVM)||' - '||TO_CHAR(:OLD.NOMREPESTCTA)||' - '||TO_CHAR(:OLD.NOMREPCERTIF)||' - '||
                  TO_CHAR(:OLD.NOMREPFINIQUITO)||' - '||TO_CHAR(:OLD.TIPOINTERESGAR)||' - '||TO_CHAR(:OLD.INDRETANIOINI)||' - '||TO_CHAR(:OLD.TIPOINFLACION)||' - '||TO_CHAR(:OLD.MTOMINCONCENTRADORA)||' - '||TO_CHAR(:OLD.INDRESCATEAUTOMATICO)||' - '||
                  TO_CHAR(:OLD.NOMREPRESCAUTOMATICO)||' - '||TO_CHAR(:OLD.NOMREPCARTBIEN)||' - '||TO_CHAR(:OLD.NOMREPTABVAL)||' - '||TO_CHAR(:OLD.INDMANEJOMONEDALOC)||' - '||TO_CHAR(:OLD.INDGENINTERESES)||' - '||TO_CHAR(:OLD.CODRUTINACALCINT)||' - '||
                  TO_CHAR(:OLD.INDPLAZOOBLGCOMP)||' - '||TO_CHAR(:OLD.CLASEFONDO)||' - '||TO_CHAR(:OLD.TIPOFONDOASOC)||' - '||TO_CHAR(:OLD.CODTIPOINVERSION)||' - '||TO_CHAR(:OLD.INDBENEFICIARIOS)||' - '||TO_CHAR(:OLD.INDDCTOCOBFONDO)||' - '||
                  TO_CHAR(:OLD.CODRUTINAMINIMOS)||' - '||TO_CHAR(:OLD.INDUNIDADES)||' - '||TO_CHAR(:OLD.CODCPTORESAUTOM)||' - '||TO_CHAR(:OLD.TIPORANGOAPORTES)||' - '||TO_CHAR(:OLD.CODARTICULO)||' - '||TO_CHAR(:OLD.CODRUTINATOPES)||' - '||
                  TO_CHAR(:OLD.TASACAMBIOTOPES)||' - '||TO_CHAR(:OLD.NOMREPRECIBO)||' - '||TO_CHAR(:OLD.CODCOBERTPAF)||' - '||TO_CHAR(:OLD.MESESPREFERENCIAL)||' - '||TO_CHAR(:OLD.INDCONFAPORTES)||' - '||TO_CHAR(:OLD.PERIODOLIQUIDEZ)||' - '||
                  TO_CHAR(:OLD.INDCOBCOBERTOPCDIF)||' - '||TO_CHAR(:OLD.ANIOPERIODORETIRO)||' - '||TO_CHAR(:OLD.INDCOMFONDOPOL)||' - '||TO_CHAR(:OLD.INDAPLICAIR)||' - '||TO_CHAR(:OLD.INDINTERESESDIARIOS)||' - '||TO_CHAR(:OLD.INDCONSULTAWEB)||' - '||
                  TO_CHAR(:OLD.INDEXCLUSIVOPAGOPRIMA)||' - '||TO_CHAR(:OLD.INDFONDOCOLECTIVOS);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.TIPOFONDO)||' - '||TO_CHAR(:NEW.DESCFONDO)||' - '||TO_CHAR(:NEW.CODMONEDA)||' - '||TO_CHAR(:NEW.PORCFONDO)||' - '||
                  TO_CHAR(:NEW.STSFONDO)||' - '||TO_CHAR(:NEW.FECSTATUS)||' - '||TO_CHAR(:NEW.EDADMIN)||' - '||TO_CHAR(:NEW.EDADMAX)||' - '||TO_CHAR(:NEW.EDADRETIRO)||' - '||TO_CHAR(:NEW.MTOAPORTEMIN)||' - '||
                  TO_CHAR(:NEW.MTOAPORTEMAX)||' - '||TO_CHAR(:NEW.MTOAPORTEINI)||' - '||TO_CHAR(:NEW.INDAPORTES)||' - '||TO_CHAR(:NEW.INDGENAPORTEINI)||' - '||TO_CHAR(:NEW.CODAPORTINI)||' - '||TO_CHAR(:NEW.INDRETPARCIALES)||' - '||
                  TO_CHAR(:NEW.INDRETTOTALES)||' - '||TO_CHAR(:NEW.INDAJUSTES)||' - '||TO_CHAR(:NEW.INDTRASPASO)||' - '||TO_CHAR(:NEW.INDPRESTAMOS)||' - '||TO_CHAR(:NEW.PORCPRESTAMOS)||' - '||TO_CHAR(:NEW.CALCINTPRESTAMOS)||' - '||
                  TO_CHAR(:NEW.TIPOINTPRESTAMOS)||' - '||TO_CHAR(:NEW.INDDESCINTFONDO)||' - '||TO_CHAR(:NEW.INDDESCPTMOFONDO)||' - '||TO_CHAR(:NEW.INDCOMISION)||' - '||TO_CHAR(:NEW.INDINCENTIVOS)||' - '||TO_CHAR(:NEW.TIPOINTERES)||' - '||
                  TO_CHAR(:NEW.TIEMPOMINIMO)||' - '||TO_CHAR(:NEW.NUMDIASANUL)||' - '||TO_CHAR(:NEW.ANOINDISPUT)||' - '||TO_CHAR(:NEW.INDAVM)||' - '||TO_CHAR(:NEW.NOMREPESTCTA)||' - '||TO_CHAR(:NEW.NOMREPCERTIF)||' - '||
                  TO_CHAR(:NEW.NOMREPFINIQUITO)||' - '||TO_CHAR(:NEW.TIPOINTERESGAR)||' - '||TO_CHAR(:NEW.INDRETANIOINI)||' - '||TO_CHAR(:NEW.TIPOINFLACION)||' - '||TO_CHAR(:NEW.MTOMINCONCENTRADORA)||' - '||TO_CHAR(:NEW.INDRESCATEAUTOMATICO)||' - '||
                  TO_CHAR(:NEW.NOMREPRESCAUTOMATICO)||' - '||TO_CHAR(:NEW.NOMREPCARTBIEN)||' - '||TO_CHAR(:NEW.NOMREPTABVAL)||' - '||TO_CHAR(:NEW.INDMANEJOMONEDALOC)||' - '||TO_CHAR(:NEW.INDGENINTERESES)||' - '||TO_CHAR(:NEW.CODRUTINACALCINT)||' - '||
                  TO_CHAR(:NEW.INDPLAZOOBLGCOMP)||' - '||TO_CHAR(:NEW.CLASEFONDO)||' - '||TO_CHAR(:NEW.TIPOFONDOASOC)||' - '||TO_CHAR(:NEW.CODTIPOINVERSION)||' - '||TO_CHAR(:NEW.INDBENEFICIARIOS)||' - '||TO_CHAR(:NEW.INDDCTOCOBFONDO)||' - '||
                  TO_CHAR(:NEW.CODRUTINAMINIMOS)||' - '||TO_CHAR(:NEW.INDUNIDADES)||' - '||TO_CHAR(:NEW.CODCPTORESAUTOM)||' - '||TO_CHAR(:NEW.TIPORANGOAPORTES)||' - '||TO_CHAR(:NEW.CODARTICULO)||' - '||TO_CHAR(:NEW.CODRUTINATOPES)||' - '||
                  TO_CHAR(:NEW.TASACAMBIOTOPES)||' - '||TO_CHAR(:NEW.NOMREPRECIBO)||' - '||TO_CHAR(:NEW.CODCOBERTPAF)||' - '||TO_CHAR(:NEW.MESESPREFERENCIAL)||' - '||TO_CHAR(:NEW.INDCONFAPORTES)||' - '||TO_CHAR(:NEW.PERIODOLIQUIDEZ)||' - '||
                  TO_CHAR(:NEW.INDCOBCOBERTOPCDIF)||' - '||TO_CHAR(:NEW.ANIOPERIODORETIRO)||' - '||TO_CHAR(:NEW.INDCOMFONDOPOL)||' - '||TO_CHAR(:NEW.INDAPLICAIR)||' - '||TO_CHAR(:NEW.INDINTERESESDIARIOS)||' - '||TO_CHAR(:NEW.INDCONSULTAWEB)||' - '||
                  TO_CHAR(:NEW.INDEXCLUSIVOPAGOPRIMA)||' - '||TO_CHAR(:NEW.INDFONDOCOLECTIVOS);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' TIPOFONDO: '||:NEW.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOFONDO <> :OLD.TIPOFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOFONDO', TO_CHAR(:OLD.TIPOFONDO), TO_CHAR(:NEW.TIPOFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCFONDO <> :OLD.DESCFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'DESCFONDO', TO_CHAR(:OLD.DESCFONDO), TO_CHAR(:NEW.DESCFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODMONEDA <> :OLD.CODMONEDA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODMONEDA', TO_CHAR(:OLD.CODMONEDA), TO_CHAR(:NEW.CODMONEDA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PORCFONDO <> :OLD.PORCFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'PORCFONDO', TO_CHAR(:OLD.PORCFONDO), TO_CHAR(:NEW.PORCFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.STSFONDO <> :OLD.STSFONDO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'STSFONDO', TO_CHAR(:OLD.STSFONDO), TO_CHAR(:NEW.STSFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECSTATUS,SYSDATE) <> NVL(:OLD.FECSTATUS,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'FECSTATUS', TO_CHAR(:OLD.FECSTATUS), TO_CHAR(:NEW.FECSTATUS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDADMIN,-20000) <> NVL(:OLD.EDADMIN,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'EDADMIN', TO_CHAR(:OLD.EDADMIN), TO_CHAR(:NEW.EDADMIN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDADMAX,-20000) <> NVL(:OLD.EDADMAX,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'EDADMAX', TO_CHAR(:OLD.EDADMAX), TO_CHAR(:NEW.EDADMAX), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDADRETIRO,-20000) <> NVL(:OLD.EDADRETIRO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'EDADRETIRO', TO_CHAR(:OLD.EDADRETIRO), TO_CHAR(:NEW.EDADRETIRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOAPORTEMIN,-20000) <> NVL(:OLD.MTOAPORTEMIN,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'MTOAPORTEMIN', TO_CHAR(:OLD.MTOAPORTEMIN), TO_CHAR(:NEW.MTOAPORTEMIN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOAPORTEMAX,-20000) <> NVL(:OLD.MTOAPORTEMAX,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'MTOAPORTEMAX', TO_CHAR(:OLD.MTOAPORTEMAX), TO_CHAR(:NEW.MTOAPORTEMAX), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOAPORTEINI,-20000) <> NVL(:OLD.MTOAPORTEINI,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'MTOAPORTEINI', TO_CHAR(:OLD.MTOAPORTEINI), TO_CHAR(:NEW.MTOAPORTEINI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAPORTES,-20000) <> NVL(:OLD.INDAPORTES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDAPORTES', TO_CHAR(:OLD.INDAPORTES), TO_CHAR(:NEW.INDAPORTES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDGENAPORTEINI,-20000) <> NVL(:OLD.INDGENAPORTEINI,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDGENAPORTEINI', TO_CHAR(:OLD.INDGENAPORTEINI), TO_CHAR(:NEW.INDGENAPORTEINI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODAPORTINI,-20000) <> NVL(:OLD.CODAPORTINI,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODAPORTINI', TO_CHAR(:OLD.CODAPORTINI), TO_CHAR(:NEW.CODAPORTINI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRETPARCIALES,-20000) <> NVL(:OLD.INDRETPARCIALES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDGENAPORTEINI', TO_CHAR(:OLD.INDRETPARCIALES), TO_CHAR(:NEW.INDRETPARCIALES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRETTOTALES,-20000) <> NVL(:OLD.INDRETTOTALES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDRETTOTALES', TO_CHAR(:OLD.INDRETTOTALES), TO_CHAR(:NEW.INDRETTOTALES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAJUSTES,-20000) <> NVL(:OLD.INDAJUSTES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDAJUSTES', TO_CHAR(:OLD.INDAJUSTES), TO_CHAR(:NEW.INDAJUSTES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDTRASPASO,-20000) <> NVL(:OLD.INDTRASPASO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDTRASPASO', TO_CHAR(:OLD.INDTRASPASO), TO_CHAR(:NEW.INDTRASPASO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDPRESTAMOS,-20000) <> NVL(:OLD.INDPRESTAMOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDPRESTAMOS', TO_CHAR(:OLD.INDPRESTAMOS), TO_CHAR(:NEW.INDPRESTAMOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCPRESTAMOS,-20000) <> NVL(:OLD.PORCPRESTAMOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'PORCPRESTAMOS', TO_CHAR(:OLD.PORCPRESTAMOS), TO_CHAR(:NEW.PORCPRESTAMOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CALCINTPRESTAMOS,-20000) <> NVL(:OLD.CALCINTPRESTAMOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CALCINTPRESTAMOS', TO_CHAR(:OLD.CALCINTPRESTAMOS), TO_CHAR(:NEW.CALCINTPRESTAMOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOINTPRESTAMOS,-20000) <> NVL(:OLD.TIPOINTPRESTAMOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOINTPRESTAMOS', TO_CHAR(:OLD.TIPOINTPRESTAMOS), TO_CHAR(:NEW.TIPOINTPRESTAMOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDDESCINTFONDO,-20000) <> NVL(:OLD.INDDESCINTFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDDESCINTFONDO', TO_CHAR(:OLD.INDDESCINTFONDO), TO_CHAR(:NEW.INDDESCINTFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDDESCPTMOFONDO,-20000) <> NVL(:OLD.INDDESCPTMOFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDDESCPTMOFONDO', TO_CHAR(:OLD.INDDESCPTMOFONDO), TO_CHAR(:NEW.INDDESCPTMOFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCOMISION,-20000) <> NVL(:OLD.INDCOMISION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDCOMISION', TO_CHAR(:OLD.INDCOMISION), TO_CHAR(:NEW.INDCOMISION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDINCENTIVOS,-20000) <> NVL(:OLD.INDINCENTIVOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDINCENTIVOS', TO_CHAR(:OLD.INDINCENTIVOS), TO_CHAR(:NEW.INDINCENTIVOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOINTERES,-20000) <> NVL(:OLD.TIPOINTERES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOINTERES', TO_CHAR(:OLD.TIPOINTERES), TO_CHAR(:NEW.TIPOINTERES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIEMPOMINIMO,-20000) <> NVL(:OLD.TIEMPOMINIMO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIEMPOMINIMO', TO_CHAR(:OLD.TIEMPOMINIMO), TO_CHAR(:NEW.TIEMPOMINIMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMDIASANUL,-20000) <> NVL(:OLD.NUMDIASANUL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NUMDIASANUL', TO_CHAR(:OLD.NUMDIASANUL), TO_CHAR(:NEW.NUMDIASANUL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ANOINDISPUT,-20000) <> NVL(:OLD.ANOINDISPUT,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'ANOINDISPUT', TO_CHAR(:OLD.ANOINDISPUT), TO_CHAR(:NEW.ANOINDISPUT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAVM,-20000) <> NVL(:OLD.INDAVM,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDAVM', TO_CHAR(:OLD.INDAVM), TO_CHAR(:NEW.INDAVM), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPESTCTA,-20000) <> NVL(:OLD.NOMREPESTCTA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPESTCTA', TO_CHAR(:OLD.NOMREPESTCTA), TO_CHAR(:NEW.NOMREPESTCTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPCERTIF,-20000) <> NVL(:OLD.NOMREPCERTIF,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPCERTIF', TO_CHAR(:OLD.NOMREPCERTIF), TO_CHAR(:NEW.NOMREPCERTIF), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPFINIQUITO,-20000) <> NVL(:OLD.NOMREPFINIQUITO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPFINIQUITO', TO_CHAR(:OLD.NOMREPFINIQUITO), TO_CHAR(:NEW.NOMREPFINIQUITO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOINTERESGAR,-20000) <> NVL(:OLD.TIPOINTERESGAR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOINTERESGAR', TO_CHAR(:OLD.TIPOINTERESGAR), TO_CHAR(:NEW.TIPOINTERESGAR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRETANIOINI,-20000) <> NVL(:OLD.INDRETANIOINI,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDRETANIOINI', TO_CHAR(:OLD.INDRETANIOINI), TO_CHAR(:NEW.INDRETANIOINI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOINFLACION,-20000) <> NVL(:OLD.TIPOINFLACION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOINFLACION', TO_CHAR(:OLD.TIPOINFLACION), TO_CHAR(:NEW.TIPOINFLACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMINCONCENTRADORA,-20000) <> NVL(:OLD.MTOMINCONCENTRADORA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'MTOMINCONCENTRADORA', TO_CHAR(:OLD.MTOMINCONCENTRADORA), TO_CHAR(:NEW.MTOMINCONCENTRADORA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRESCATEAUTOMATICO,-20000) <> NVL(:OLD.INDRESCATEAUTOMATICO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDRESCATEAUTOMATICO', TO_CHAR(:OLD.INDRESCATEAUTOMATICO), TO_CHAR(:NEW.INDRESCATEAUTOMATICO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPRESCAUTOMATICO,-20000) <> NVL(:OLD.NOMREPRESCAUTOMATICO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPRESCAUTOMATICO', TO_CHAR(:OLD.NOMREPRESCAUTOMATICO), TO_CHAR(:NEW.NOMREPRESCAUTOMATICO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPCARTBIEN,-20000) <> NVL(:OLD.NOMREPCARTBIEN,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPCARTBIEN', TO_CHAR(:OLD.NOMREPCARTBIEN), TO_CHAR(:NEW.NOMREPCARTBIEN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPTABVAL,-20000) <> NVL(:OLD.NOMREPTABVAL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPTABVAL', TO_CHAR(:OLD.NOMREPTABVAL), TO_CHAR(:NEW.NOMREPTABVAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMANEJOMONEDALOC,-20000) <> NVL(:OLD.INDMANEJOMONEDALOC,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDMANEJOMONEDALOC', TO_CHAR(:OLD.INDMANEJOMONEDALOC), TO_CHAR(:NEW.INDMANEJOMONEDALOC), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDGENINTERESES,-20000) <> NVL(:OLD.INDGENINTERESES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDGENINTERESES', TO_CHAR(:OLD.INDGENINTERESES), TO_CHAR(:NEW.INDGENINTERESES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRUTINACALCINT,-20000) <> NVL(:OLD.CODRUTINACALCINT,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODRUTINACALCINT', TO_CHAR(:OLD.CODRUTINACALCINT), TO_CHAR(:NEW.CODRUTINACALCINT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDPLAZOOBLGCOMP,-20000) <> NVL(:OLD.INDPLAZOOBLGCOMP,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDPLAZOOBLGCOMP', TO_CHAR(:OLD.INDPLAZOOBLGCOMP), TO_CHAR(:NEW.INDPLAZOOBLGCOMP), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CLASEFONDO,-20000) <> NVL(:OLD.CLASEFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CLASEFONDO', TO_CHAR(:OLD.CLASEFONDO), TO_CHAR(:NEW.CLASEFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOFONDOASOC,-20000) <> NVL(:OLD.TIPOFONDOASOC,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPOFONDOASOC', TO_CHAR(:OLD.TIPOFONDOASOC), TO_CHAR(:NEW.TIPOFONDOASOC), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPOINVERSION,-20000) <> NVL(:OLD.CODTIPOINVERSION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODTIPOINVERSION', TO_CHAR(:OLD.CODTIPOINVERSION), TO_CHAR(:NEW.CODTIPOINVERSION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDBENEFICIARIOS,-20000) <> NVL(:OLD.INDBENEFICIARIOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDBENEFICIARIOS', TO_CHAR(:OLD.INDBENEFICIARIOS), TO_CHAR(:NEW.INDBENEFICIARIOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDDCTOCOBFONDO,-20000) <> NVL(:OLD.INDDCTOCOBFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDDCTOCOBFONDO', TO_CHAR(:OLD.INDDCTOCOBFONDO), TO_CHAR(:NEW.INDDCTOCOBFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRUTINAMINIMOS,-20000) <> NVL(:OLD.CODRUTINAMINIMOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODRUTINAMINIMOS', TO_CHAR(:OLD.CODRUTINAMINIMOS), TO_CHAR(:NEW.CODRUTINAMINIMOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDUNIDADES,-20000) <> NVL(:OLD.INDUNIDADES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDUNIDADES', TO_CHAR(:OLD.INDUNIDADES), TO_CHAR(:NEW.INDUNIDADES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCPTORESAUTOM,-20000) <> NVL(:OLD.CODCPTORESAUTOM,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODCPTORESAUTOM', TO_CHAR(:OLD.CODCPTORESAUTOM), TO_CHAR(:NEW.CODCPTORESAUTOM), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPORANGOAPORTES,-20000) <> NVL(:OLD.TIPORANGOAPORTES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TIPORANGOAPORTES', TO_CHAR(:OLD.TIPORANGOAPORTES), TO_CHAR(:NEW.TIPORANGOAPORTES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODARTICULO,-20000) <> NVL(:OLD.CODARTICULO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODARTICULO', TO_CHAR(:OLD.CODARTICULO), TO_CHAR(:NEW.CODARTICULO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRUTINATOPES,-20000) <> NVL(:OLD.CODRUTINATOPES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODRUTINATOPES', TO_CHAR(:OLD.CODRUTINATOPES), TO_CHAR(:NEW.CODRUTINATOPES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TASACAMBIOTOPES,-20000) <> NVL(:OLD.TASACAMBIOTOPES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'TASACAMBIOTOPES', TO_CHAR(:OLD.TASACAMBIOTOPES), TO_CHAR(:NEW.TASACAMBIOTOPES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREPRECIBO,-20000) <> NVL(:OLD.NOMREPRECIBO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'NOMREPRECIBO', TO_CHAR(:OLD.NOMREPRECIBO), TO_CHAR(:NEW.NOMREPRECIBO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCOBERTPAF,-20000) <> NVL(:OLD.CODCOBERTPAF,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'CODCOBERTPAF', TO_CHAR(:OLD.CODCOBERTPAF), TO_CHAR(:NEW.CODCOBERTPAF), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MESESPREFERENCIAL,-20000) <> NVL(:OLD.MESESPREFERENCIAL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'MESESPREFERENCIAL', TO_CHAR(:OLD.MESESPREFERENCIAL), TO_CHAR(:NEW.MESESPREFERENCIAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCONFAPORTES,-20000) <> NVL(:OLD.INDCONFAPORTES,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDCONFAPORTES', TO_CHAR(:OLD.INDCONFAPORTES), TO_CHAR(:NEW.INDCONFAPORTES), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PERIODOLIQUIDEZ,-20000) <> NVL(:OLD.PERIODOLIQUIDEZ,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'PERIODOLIQUIDEZ', TO_CHAR(:OLD.PERIODOLIQUIDEZ), TO_CHAR(:NEW.PERIODOLIQUIDEZ), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCOBCOBERTOPCDIF,-20000) <> NVL(:OLD.INDCOBCOBERTOPCDIF,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDCOBCOBERTOPCDIF', TO_CHAR(:OLD.INDCOBCOBERTOPCDIF), TO_CHAR(:NEW.INDCOBCOBERTOPCDIF), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ANIOPERIODORETIRO,-20000) <> NVL(:OLD.ANIOPERIODORETIRO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'ANIOPERIODORETIRO', TO_CHAR(:OLD.ANIOPERIODORETIRO), TO_CHAR(:NEW.ANIOPERIODORETIRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCOMFONDOPOL,-20000) <> NVL(:OLD.INDCOMFONDOPOL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDCOMFONDOPOL', TO_CHAR(:OLD.INDCOMFONDOPOL), TO_CHAR(:NEW.INDCOMFONDOPOL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAPLICAIR,-20000) <> NVL(:OLD.INDAPLICAIR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDAPLICAIR', TO_CHAR(:OLD.INDAPLICAIR), TO_CHAR(:NEW.INDAPLICAIR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDINTERESESDIARIOS,-20000) <> NVL(:OLD.INDINTERESESDIARIOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDINTERESESDIARIOS', TO_CHAR(:OLD.INDINTERESESDIARIOS), TO_CHAR(:NEW.INDINTERESESDIARIOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCONSULTAWEB,-20000) <> NVL(:OLD.INDCONSULTAWEB,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDCONSULTAWEB', TO_CHAR(:OLD.INDCONSULTAWEB), TO_CHAR(:NEW.INDCONSULTAWEB), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDEXCLUSIVOPAGOPRIMA,-20000) <> NVL(:OLD.INDEXCLUSIVOPAGOPRIMA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDEXCLUSIVOPAGOPRIMA', TO_CHAR(:OLD.INDEXCLUSIVOPAGOPRIMA), TO_CHAR(:NEW.INDEXCLUSIVOPAGOPRIMA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDFONDOCOLECTIVOS,-20000) <> NVL(:OLD.INDFONDOCOLECTIVOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' TIPOFONDO: '||:OLD.TIPOFONDO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FAI_TIPOS_DE_FONDOS', 'INDFONDOCOLECTIVOS', TO_CHAR(:OLD.INDFONDOCOLECTIVOS), TO_CHAR(:NEW.INDFONDOCOLECTIVOS), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de FAI_TIPOS_DE_FONDOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_FAI_TIPOS_DE_FONDOS FOR SICAS_OC.TRG_FAI_TIPOS_DE_FONDOS;
