CREATE OR REPLACE TRIGGER SICAS_OC.TRG_COBERT_ACT_ASEG
  BEFORE DELETE ON COBERT_ACT_ASEG
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA COBERT_ACT_ASEG
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.IDPOLIZA)||' - '||TO_CHAR(:OLD.IDETPOL)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.TIPOREF)||' - '||TO_CHAR(:OLD.NUMREF)||' - '||
                  TO_CHAR(:OLD.CODCOBERT)||' - '||TO_CHAR(:OLD.COD_ASEGURADO)||' - '||TO_CHAR(:OLD.SUMAASEG_LOCAL)||' - '||TO_CHAR(:OLD.SUMAASEG_MONEDA)||' - '||TO_CHAR(:OLD.TASA)||' - '||TO_CHAR(:OLD.PRIMA_MONEDA)||' - '||
                  TO_CHAR(:OLD.PRIMA_LOCAL)||' - '||TO_CHAR(:OLD.IDENDOSO)||' - '||TO_CHAR(:OLD.STSCOBERTURA)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.COD_MONEDA)||' - '||TO_CHAR(:OLD.DEDUCIBLE_LOCAL)||' - '||
                  TO_CHAR(:OLD.DEDUCIBLE_MONEDA)||' - '||TO_CHAR(:OLD.INDCAMBIOSAMI)||' - '||TO_CHAR(:OLD.SUMAASEGORIGEN)||' - '||TO_CHAR(:OLD.SALARIOMENSUAL)||' - '||TO_CHAR(:OLD.VECESSALARIO)||' - '||TO_CHAR(:OLD.SUMAASEGCALCULADA)||' - '||
                  TO_CHAR(:OLD.EDAD_MINIMA)||' - '||TO_CHAR(:OLD.EDAD_MAXIMA)||' - '||TO_CHAR(:OLD.EDAD_EXCLUSION)||' - '||TO_CHAR(:OLD.SUMAASEG_MINIMA)||' - '||TO_CHAR(:OLD.SUMAASEG_MAXIMA)||' - '||TO_CHAR(:OLD.PORCEXTRAPRIMADET)||' - '||  
                  TO_CHAR(:OLD.MONTOEXTRAPRIMADET)||' - '||TO_CHAR(:OLD.SUMAINGRESADA)||' - '||TO_CHAR(:OLD.PRIMANIVMONEDA)||' - '||TO_CHAR(:OLD.SUMAASEG_MINIMA)||' - '||TO_CHAR(:OLD.IDRAMOREAL); 
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDPOLIZA: '||:OLD.IDPOLIZA||' IDETPOL: '||:OLD.IDETPOL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERT_ACT_ASEG', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de COBERT_ACT_ASEG, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_COBERT_ACT_ASEG FOR SICAS_OC.TRG_COBERT_ACT_ASEG;
