CREATE OR REPLACE TRIGGER TRG_UP_FACT_ELECT_MOTIVO_CANCELA
BEFORE UPDATE
ON FACT_ELECT_MOTIVO_CANCELA
FOR EACH ROW

 BEGIN

  IF :NEW.CVEMOTIVCANCFACT != :OLD.CVEMOTIVCANCFACT THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_MOTIVO_CANCELA', 'CVEMOTIVCANCFACT', :OLD.CVEMOTIVCANCFACT, :NEW.CVEMOTIVCANCFACT, 'UPDATE');

  END IF;

  IF :NEW.DESCMOTIVOCANC != :OLD.DESCMOTIVOCANC THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_MOTIVO_CANCELA', 'DESCMOTIVOCANC', :OLD.DESCMOTIVOCANC, :NEW.DESCMOTIVOCANC, 'UPDATE');

  END IF;

  IF :NEW.STSMOTIVCANC != :OLD.STSMOTIVCANC THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_MOTIVO_CANCELA', 'STSMOTIVCANC', :OLD.STSMOTIVCANC, :NEW.STSMOTIVCANC, 'UPDATE');

  END IF;

  IF :NEW.FECSTSMOTIVCANC != :OLD.FECSTSMOTIVCANC THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_MOTIVO_CANCELA', 'FECSTSMOTIVCANC', TO_CHAR(:OLD.FECSTSMOTIVCANC), TO_CHAR(:NEW.FECSTSMOTIVCANC), 'UPDATE');

  END IF;

  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_MOTIVO_CANCELA', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');

  END IF;

 END TRG_UP_FACT_ELECT_MOTIVO_CANCELA;