CREATE OR REPLACE TRIGGER TRG_U_FACT_ELECT_USO_CFDI
BEFORE UPDATE
ON FACT_ELECT_USO_CFDI
FOR EACH ROW

 BEGIN

  IF :NEW.CODUSOCFDI != :OLD.CODUSOCFDI THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'CODUSOCFDI', :OLD.CODUSOCFDI, :NEW.CODUSOCFDI, 'UPDATE');

  END IF;

  IF :NEW.DESCUSOCFDI != :OLD.DESCUSOCFDI THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'DESCUSOCFDI', :OLD.DESCUSOCFDI, :NEW.DESCUSOCFDI, 'UPDATE');

  END IF;

  IF :NEW.INDPERSFISICA != :OLD.INDPERSFISICA THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'INDPERSFISICA', :OLD.INDPERSFISICA, :NEW.INDPERSFISICA, 'UPDATE');

  END IF;

  IF :NEW.INDPERSMORAL != :OLD.INDPERSMORAL THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'INDPERSMORAL', :OLD.INDPERSMORAL, :NEW.INDPERSMORAL, 'UPDATE');

  END IF;

  IF :NEW.FECINIVIG != :OLD.FECINIVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'FECINIVIG', TO_CHAR(:OLD.FECINIVIG), TO_CHAR(:NEW.FECINIVIG), 'UPDATE');

  END IF;

  IF :NEW.FECFINVIG != :OLD.FECFINVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'FECFINVIG', TO_CHAR(:OLD.FECFINVIG), TO_CHAR(:NEW.FECFINVIG), 'UPDATE');

  END IF;

  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');

  END IF;

  IF :NEW.FECMOD != :OLD.FECMOD THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'FECMOD', TO_CHAR(:OLD.FECMOD), TO_CHAR(:NEW.FECMOD), 'UPDATE');

  END IF;

 END TRG_U_FACT_ELECT_USO_CFDI;