CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_SESAS_TIPO_SEGURO
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_SESAS_TIPO_SEGURO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_SESAS_TIPO_SEGURO
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CLASESEGURO)||' - '||TO_CHAR(:OLD.TIPOSEGURO)||' - '||
                  TO_CHAR(:OLD.PERIODOESPERA)||' - '||TO_CHAR(:OLD.INICIOCOBERTURA)||' - '||TO_CHAR(:OLD.MAXDIASBENEF3)||' - '||TO_CHAR(:OLD.SUBTIPOSEG)||' - '||TO_CHAR(:OLD.TIPORIESGO)||' - '||
                  TO_CHAR(:OLD.TIPORIESGOASOC)||' - '||TO_CHAR(:OLD.COBERTAFECTADA)||' - '||TO_CHAR(:OLD.MODALSUMAASEG)||' - '||TO_CHAR(:OLD.MODALPOLIZA)||' - '||TO_CHAR(:OLD.MTODEDUCIBLE)||' - '||
                  TO_CHAR(:OLD.MTOCOASEGURO)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CLASESEGURO)||' - '||TO_CHAR(:NEW.TIPOSEGURO)||' - '||
                  TO_CHAR(:NEW.PERIODOESPERA)||' - '||TO_CHAR(:NEW.INICIOCOBERTURA)||' - '||TO_CHAR(:NEW.MAXDIASBENEF3)||' - '||TO_CHAR(:NEW.SUBTIPOSEG)||' - '||TO_CHAR(:NEW.TIPORIESGO)||' - '||
                  TO_CHAR(:NEW.TIPORIESGOASOC)||' - '||TO_CHAR(:NEW.COBERTAFECTADA)||' - '||TO_CHAR(:NEW.MODALSUMAASEG)||' - '||TO_CHAR(:NEW.MODALPOLIZA)||' - '||TO_CHAR(:NEW.MTODEDUCIBLE)||' - '||
                  TO_CHAR(:NEW.MTOCOASEGURO)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CLASESEGURO,-20000) <> NVL(:OLD.CLASESEGURO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'CLASESEGURO', TO_CHAR(:OLD.CLASESEGURO), TO_CHAR(:NEW.CLASESEGURO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOSEGURO,-20000) <> NVL(:OLD.TIPOSEGURO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'TIPOSEGURO', TO_CHAR(:OLD.TIPOSEGURO), TO_CHAR(:NEW.TIPOSEGURO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PERIODOESPERA,-20000) <> NVL(:OLD.PERIODOESPERA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'PERIODOESPERA', TO_CHAR(:OLD.PERIODOESPERA), TO_CHAR(:NEW.PERIODOESPERA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INICIOCOBERTURA,-20000) <> NVL(:OLD.INICIOCOBERTURA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'INICIOCOBERTURA', TO_CHAR(:OLD.INICIOCOBERTURA), TO_CHAR(:NEW.INICIOCOBERTURA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MAXDIASBENEF3,-20000) <> NVL(:OLD.MAXDIASBENEF3,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'MAXDIASBENEF3', TO_CHAR(:OLD.MAXDIASBENEF3), TO_CHAR(:NEW.MAXDIASBENEF3),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUBTIPOSEG,-20000) <> NVL(:OLD.SUBTIPOSEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'SUBTIPOSEG', TO_CHAR(:OLD.SUBTIPOSEG), TO_CHAR(:NEW.SUBTIPOSEG),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPORIESGO,-20000) <> NVL(:OLD.TIPORIESGO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'TIPORIESGO', TO_CHAR(:OLD.TIPORIESGO), TO_CHAR(:NEW.TIPORIESGO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPORIESGOASOC,-20000) <> NVL(:OLD.TIPORIESGOASOC,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'TIPORIESGOASOC', TO_CHAR(:OLD.TIPORIESGO), TO_CHAR(:NEW.TIPORIESGOASOC),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COBERTAFECTADA,-20000) <> NVL(:OLD.COBERTAFECTADA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'COBERTAFECTADA', TO_CHAR(:OLD.COBERTAFECTADA), TO_CHAR(:NEW.COBERTAFECTADA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MODALSUMAASEG,-20000) <> NVL(:OLD.MODALSUMAASEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'MODALSUMAASEG', TO_CHAR(:OLD.MODALSUMAASEG), TO_CHAR(:NEW.MODALSUMAASEG),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MODALPOLIZA,-20000) <> NVL(:OLD.MODALPOLIZA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'MODALPOLIZA', TO_CHAR(:OLD.MODALPOLIZA), TO_CHAR(:NEW.MODALPOLIZA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTODEDUCIBLE,-20000) <> NVL(:OLD.MTODEDUCIBLE,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'MTODEDUCIBLE', TO_CHAR(:OLD.MTODEDUCIBLE), TO_CHAR(:NEW.MTODEDUCIBLE),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOCOASEGURO,-20000) <> NVL(:OLD.MTOCOASEGURO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'MTOCOASEGURO', TO_CHAR(:OLD.MTOCOASEGURO), TO_CHAR(:NEW.MTOCOASEGURO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_SESAS_TIPO_SEGURO', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO),'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_SESAS_TIPO_SEGURO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_SESAS_TIPO_SEGURO FOR SICAS_OC.TRG_CONFIG_SESAS_TIPO_SEGURO;
