CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PAQUETE_COMERCIAL
  BEFORE INSERT OR UPDATE OR DELETE ON PAQUETE_COMERCIAL
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PAQUETE_COMERCIAL
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODPAQUETE)||' - '||
                  TO_CHAR(:OLD.DESCPAQUETE)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECHAMODIF)||' - '||TO_CHAR('BLOB');
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODPAQUETE)||' - '||
                  TO_CHAR(:NEW.DESCPAQUETE)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECHAMODIF)||' - '||TO_CHAR('BLOB');
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' DESCPAQUETE: '||:NEW.DESCPAQUETE;           
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PAQUETE_COMERCIAL', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDTIPOSEG,-20000) <> NVL(:OLD.IDTIPOSEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PLANCOB,-20000) <> NVL(:OLD.PLANCOB,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPAQUETE,-20000) <> NVL(:OLD.CODPAQUETE,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'CODPAQUETE', TO_CHAR(:OLD.CODPAQUETE), TO_CHAR(:NEW.CODPAQUETE), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCPAQUETE <> :OLD.DESCPAQUETE) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'DESCPAQUETE', TO_CHAR(:OLD.DESCPAQUETE), TO_CHAR(:NEW.DESCPAQUETE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAMODIF,SYSDATE) <> NVL(:OLD.FECHAMODIF,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'FECHAMODIF', TO_CHAR(:OLD.FECHAMODIF), TO_CHAR(:NEW.FECHAMODIF), 'UPDATE',vl_Primary);
    END IF;
    IF dbms_lob.getlength(:NEW.DOCUMENTO) <> dbms_lob.getlength(:OLD.DOCUMENTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' DESCPAQUETE: '||:OLD.DESCPAQUETE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PAQUETE_COMERCIAL', 'DOCUMENTO', TO_CHAR('BLOB'), TO_CHAR('BLOB'), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PAQUETE_COMERCIAL, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PAQUETE_COMERCIAL FOR SICAS_OC.TRG_PAQUETE_COMERCIAL;
