CREATE OR REPLACE TRIGGER SICAS_OC.TRG_VALORES_DE_LISTAS
  BEFORE INSERT OR UPDATE OR DELETE ON VALORES_DE_LISTAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA VALORES_DE_LISTAS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODLISTA)||' - '||TO_CHAR(:OLD.CODVALOR)||' - '||TO_CHAR(:OLD.DESCVALLST)||' - '||TO_CHAR(:OLD.CVE_CNSF)||' - '||TO_CHAR(:OLD.DESC_CNSF);
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODLISTA)||' - '||TO_CHAR(:NEW.CODVALOR)||' - '||TO_CHAR(:NEW.DESCVALLST)||' - '||TO_CHAR(:NEW.CVE_CNSF)||' - '||TO_CHAR(:NEW.DESC_CNSF);
      vl_Primary := 'CODLISTA: '||:NEW.CODLISTA ||' CODVALOR: '||:NEW.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODLISTA <> :OLD.CODLISTA) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'CODLISTA', TO_CHAR(:OLD.CODLISTA), TO_CHAR(:NEW.CODLISTA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODVALOR <> :OLD.CODVALOR) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'CODVALOR', TO_CHAR(:OLD.CODVALOR), TO_CHAR(:NEW.CODVALOR), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCVALLST <> :OLD.DESCVALLST) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'DESCVALLST', TO_CHAR(:OLD.DESCVALLST), TO_CHAR(:NEW.DESCVALLST), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CVE_CNSF,-20000) <> NVL(:OLD.CVE_CNSF,-20000)) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'CVE_CNSF', TO_CHAR(:OLD.CVE_CNSF), TO_CHAR(:NEW.CVE_CNSF), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESC_CNSF,-20000) <> NVL(:OLD.DESC_CNSF,-20000)) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA ||' CODVALOR: '||:OLD.CODVALOR;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'VALORES_DE_LISTAS', 'DESC_CNSF', TO_CHAR(:OLD.DESC_CNSF), TO_CHAR(:NEW.DESC_CNSF), 'UPDATE',vl_Primary);
    END IF;

  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de VALORES_DE_LISTAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_VALORES_DE_LISTAS FOR SICAS_OC.TRG_VALORES_DE_LISTAS;
