CREATE OR REPLACE TRIGGER SICAS_OC.TRG_AGENTES_DETALLES_POLIZAS
  BEFORE DELETE ON AGENTES_DETALLES_POLIZAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA AGENTES_DETALLES_POLIZAS
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 

      vl_Texto := TO_CHAR(:OLD.IDPOLIZA)||' - '||TO_CHAR(:OLD.IDETPOL)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.PORC_COMISION)||' - '||TO_CHAR(:OLD.IND_PRINCIPAL)||' - '||
                  TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.ORIGEN);  
      vl_Primary := 'IDPOLIZA: '||:OLD.IDPOLIZA||' IDETPOL: '||:OLD.IDETPOL||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_DETALLES_POLIZAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de AGENTES_DETALLES_POLIZAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_AGENTES_DETALLES_POLIZAS FOR SICAS_OC.TRG_AGENTES_DETALLES_POLIZAS;
