CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TIPOS_DE_SEGUROS
  BEFORE INSERT OR UPDATE OR DELETE ON TIPOS_DE_SEGUROS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000) := NULL;
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TIPOS_DE_SEGUROS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    Indice Unico: IDTIPOSEG - CODEMPRESA - CODCIA
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.DESCRIPCION)||' - '||TO_CHAR(:OLD.STSTIPSEG)||' - '||
        TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.TIPOSEG)||' - '||TO_CHAR(:OLD.IDPLANTILLA)||' - '||TO_CHAR(:OLD.CODTIPOPLAN)||' - '||TO_CHAR(:OLD.CODPLANPAGO)||' - '||
        TO_CHAR(:OLD.INDRENOVAUT)||' - '||TO_CHAR(:OLD.TIPOCONTABILIDAD)||' - '||TO_CHAR(:OLD.DIASCANCELACION)||' - '||TO_CHAR(:OLD.CLAVEFACTELECT)||' - '||TO_CHAR(:OLD.INDMANEJAFONDOS)||' - '||
        TO_CHAR(:OLD.TIPO_RIESGO)||' - '||TO_CHAR(:OLD.ID_LARGO_PLAZO)||' - '||TO_CHAR(:OLD.ID_PREPAGO)||' - '||TO_CHAR(utl_raw.cast_to_raw('BLOB'))||' - '||TO_CHAR(:OLD.INDMULTIRAMO);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'SE ELIMINA EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE');
  END IF;

  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.DESCRIPCION)||' - '||TO_CHAR(:NEW.STSTIPSEG)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.TIPOSEG)||' - '||TO_CHAR(:NEW.IDPLANTILLA)||' - '||TO_CHAR(:NEW.CODTIPOPLAN)
              ||' - '||TO_CHAR(:NEW.CODPLANPAGO)||' - '||TO_CHAR(:NEW.INDRENOVAUT)||' - '||TO_CHAR(:NEW.TIPOCONTABILIDAD)||' - '||TO_CHAR(:NEW.DIASCANCELACION)||' - '||TO_CHAR(:NEW.CLAVEFACTELECT)||' - '||TO_CHAR(:NEW.INDMANEJAFONDOS)||' - '||TO_CHAR(:NEW.TIPO_RIESGO)
              ||' - '||TO_CHAR(:NEW.ID_LARGO_PLAZO)||' - '||TO_CHAR(:NEW.ID_PREPAGO)||' - '||TO_CHAR(utl_raw.cast_to_raw('BLOB'))||' - '||TO_CHAR(:NEW.INDMULTIRAMO);

    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TIPOS_DE_SEGUROS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT');
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE');
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE');
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE');
    END IF;
    IF (:NEW.DESCRIPCION <> :OLD.DESCRIPCION) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'DESCRIPCION', TO_CHAR(:OLD.DESCRIPCION), TO_CHAR(:NEW.DESCRIPCION), 'UPDATE');
    END IF;
    IF (:NEW.STSTIPSEG <> :OLD.STSTIPSEG) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'STSTIPSEG', TO_CHAR(:OLD.STSTIPSEG), TO_CHAR(:NEW.STSTIPSEG), 'UPDATE');
    END IF;
    IF (:NEW.FECSTS <> :OLD.FECSTS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE');
    END IF;
    IF (:NEW.TIPOSEG <> :OLD.TIPOSEG) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPOSEG', TO_CHAR(:OLD.TIPOSEG), TO_CHAR(:NEW.TIPOSEG), 'UPDATE');
    END IF;
    IF (:NEW.IDPLANTILLA <> :OLD.IDPLANTILLA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'IDPLANTILLA', TO_CHAR(:OLD.IDPLANTILLA), TO_CHAR(:NEW.IDPLANTILLA), 'UPDATE');
    END IF;
    IF (:NEW.CODTIPOPLAN <> :OLD.CODTIPOPLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE');
    END IF;
    IF (:NEW.CODPLANPAGO <> :OLD.CODPLANPAGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE');
    END IF;
    IF (:NEW.INDRENOVAUT <> :OLD.INDRENOVAUT) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDRENOVAUT', TO_CHAR(:OLD.INDRENOVAUT), TO_CHAR(:NEW.INDRENOVAUT), 'UPDATE');
    END IF;
    IF (:NEW.TIPOCONTABILIDAD <> :OLD.TIPOCONTABILIDAD) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPOCONTABILIDAD', TO_CHAR(:OLD.TIPOCONTABILIDAD), TO_CHAR(:NEW.TIPOCONTABILIDAD), 'UPDATE');
    END IF;
    IF (:NEW.DIASCANCELACION <> :OLD.DIASCANCELACION) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'DIASCANCELACION', TO_CHAR(:OLD.DIASCANCELACION), TO_CHAR(:NEW.DIASCANCELACION), 'UPDATE');
    END IF;
    IF (:NEW.CLAVEFACTELECT <> :OLD.CLAVEFACTELECT) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CLAVEFACTELECT', TO_CHAR(:OLD.CLAVEFACTELECT), TO_CHAR(:NEW.CLAVEFACTELECT), 'UPDATE');
    END IF;
    IF (:NEW.INDMANEJAFONDOS <> :OLD.INDMANEJAFONDOS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDMANEJAFONDOS', TO_CHAR(:OLD.INDMANEJAFONDOS), TO_CHAR(:NEW.INDMANEJAFONDOS), 'UPDATE');
    END IF;
    IF (:NEW.TIPO_RIESGO <> :OLD.TIPO_RIESGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPO_RIESGO', TO_CHAR(:OLD.TIPO_RIESGO), TO_CHAR(:NEW.TIPO_RIESGO), 'UPDATE');
    END IF;
    IF (:NEW.ID_LARGO_PLAZO <> :OLD.ID_LARGO_PLAZO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'ID_LARGO_PLAZO', TO_CHAR(:OLD.ID_LARGO_PLAZO), TO_CHAR(:NEW.ID_LARGO_PLAZO), 'UPDATE');
    END IF;
    IF (:NEW.ID_PREPAGO <> :OLD.ID_PREPAGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'ID_PREPAGO', TO_CHAR(:OLD.ID_PREPAGO), TO_CHAR(:NEW.ID_PREPAGO), 'UPDATE');
    END IF;
    IF (dbms_lob.compare(:OLD.QUEHACERSINIESTROS, :NEW.QUEHACERSINIESTROS) <> 0) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'QUEHACERSINIESTROS', TO_CHAR(utl_raw.cast_to_raw('BLOB')), TO_CHAR(TO_BLOB('BLOB')), 'UPDATE');
    END IF;
    IF (:NEW.INDMULTIRAMO <> :OLD.INDMULTIRAMO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDMULTIRAMO', TO_CHAR(:OLD.INDMULTIRAMO), TO_CHAR(:NEW.INDMULTIRAMO), 'UPDATE');
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TIPOS_DE_SEGUROS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TIPOS_DE_SEGUROS FOR SICAS_OC.TRG_TIPOS_DE_SEGUROS;
