CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TIPO_AGENTE
  BEFORE INSERT OR UPDATE OR DELETE ON TIPO_AGENTE
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TIPO_AGENTE
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODTIPO)||' - '||TO_CHAR(:OLD.DESCRIPCION)||' - '||TO_CHAR(:OLD.FECHAESTADO)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.ESTADO);  
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODTIPO)||' - '||TO_CHAR(:NEW.DESCRIPCION)||' - '||TO_CHAR(:NEW.FECHAESTADO)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.ESTADO);  
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODTIPO: '||:NEW.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TIPO_AGENTE', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODTIPO <> :OLD.CODTIPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'CODTIPO', TO_CHAR(:OLD.CODTIPO), TO_CHAR(:NEW.CODTIPO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCRIPCION,-20000) <> NVL(:OLD.DESCRIPCION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'DESCRIPCION', TO_CHAR(:OLD.DESCRIPCION), TO_CHAR(:NEW.DESCRIPCION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAESTADO,SYSDATE) <> NVL(:OLD.FECHAESTADO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'FECHAESTADO', TO_CHAR(:OLD.FECHAESTADO), TO_CHAR(:NEW.FECHAESTADO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ESTADO,-20000) <> NVL(:OLD.ESTADO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODTIPO: '||:OLD.CODTIPO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPO_AGENTE', 'ESTADO', TO_CHAR(:OLD.ESTADO), TO_CHAR(:NEW.ESTADO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TIPO_AGENTE, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TIPO_AGENTE FOR SICAS_OC.TRG_TIPO_AGENTE;
