CREATE OR REPLACE TRIGGER SICAS_OC.TRG_VALGAR_COB_SEX_EDAD_RIESG
  BEFORE INSERT OR UPDATE OR DELETE ON VALGAR_COB_SEX_EDAD_RIESG
  FOR EACH ROW 
DECLARE
    vl_Primary  VARCHAR2(2000);
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA VALGAR_COB_SEX_EDAD_RIESG
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: UNICOS CAMPOS QUE NO SON PK 	"FACTORSEGUROSALDADO" - "PRORRANIOS" - "PRORRDIAS" - "IDTARIFA"
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                  TO_CHAR(:OLD.EDADINITARIFA)||' - '||TO_CHAR(:OLD.EDADFINTARIFA)||' - '||TO_CHAR(:OLD.ANIOPOL)||' - '||TO_CHAR(:OLD.SEXOTARIFA)||' - '||TO_CHAR(:OLD.RIESGOTARIFA)||' - '||
                  TO_CHAR(:OLD.FACTORRESCATE)||' - '||TO_CHAR(:OLD.FACTORSEGUROSALDADO)||' - '||TO_CHAR(:OLD.PRORRANIOS)||' - '||TO_CHAR(:OLD.PRORRDIAS)||' - '||TO_CHAR(:OLD.IDTARIFA);
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
  
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                  TO_CHAR(:NEW.EDADINITARIFA)||' - '||TO_CHAR(:NEW.EDADFINTARIFA)||' - '||TO_CHAR(:NEW.ANIOPOL)||' - '||TO_CHAR(:NEW.SEXOTARIFA)||' - '||TO_CHAR(:NEW.RIESGOTARIFA)||' - '||
                  TO_CHAR(:NEW.FACTORRESCATE)||' - '||TO_CHAR(:NEW.FACTORSEGUROSALDADO)||' - '||TO_CHAR(:NEW.PRORRANIOS)||' - '||TO_CHAR(:NEW.PRORRDIAS)||' - '||TO_CHAR(:NEW.IDTARIFA);
      vl_Primary  := 'CODCIA: '||:NEW.CODCIA ||' CODEMPRESA: '||:NEW.CODEMPRESA || ' IDTIPOSEG: '||:NEW.IDTIPOSEG ||' PLANCOB: '||:NEW.PLANCOB ||' CODCOBERT: '||:NEW.CODCOBERT ||' EDADINITARIFA: '||
                  :NEW.EDADINITARIFA ||' EDADFINTARIFA: '||:NEW.EDADFINTARIFA ||' ANIOPOL: '||:NEW.ANIOPOL ||' SEXOTARIFA: '||:NEW.SEXOTARIFA ||' RIESGOTARIFA: '||:NEW.RIESGOTARIFA ||' FACTORRESCATE: '||:NEW.FACTORRESCATE ;

      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;
  
  IF UPDATING THEN 
    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODCOBERT <> :OLD.CODCOBERT THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.EDADINITARIFA <> :OLD.EDADINITARIFA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'EDADINITARIFA', TO_CHAR(:OLD.EDADINITARIFA), TO_CHAR(:NEW.EDADINITARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.EDADFINTARIFA <> :OLD.EDADFINTARIFA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'EDADFINTARIFA', TO_CHAR(:OLD.EDADFINTARIFA), TO_CHAR(:NEW.EDADFINTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.ANIOPOL <> :OLD.ANIOPOL THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'ANIOPOL', TO_CHAR(:OLD.ANIOPOL), TO_CHAR(:NEW.ANIOPOL), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.SEXOTARIFA <> :OLD.SEXOTARIFA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SEXOTARIFA', TO_CHAR(:OLD.SEXOTARIFA), TO_CHAR(:NEW.SEXOTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.RIESGOTARIFA <> :OLD.RIESGOTARIFA THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'RIESGOTARIFA', TO_CHAR(:OLD.RIESGOTARIFA), TO_CHAR(:NEW.RIESGOTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.FACTORRESCATE <> :OLD.FACTORRESCATE THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'FACTORRESCATE', TO_CHAR(:OLD.FACTORRESCATE), TO_CHAR(:NEW.FACTORRESCATE), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.FACTORSEGUROSALDADO <> :OLD.FACTORSEGUROSALDADO THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'FACTORSEGUROSALDADO', TO_CHAR(:OLD.FACTORSEGUROSALDADO), TO_CHAR(:NEW.FACTORSEGUROSALDADO), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PRORRANIOS <> :OLD.PRORRANIOS THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PRORRANIOS', TO_CHAR(:OLD.PRORRANIOS), TO_CHAR(:NEW.PRORRANIOS), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PRORRDIAS <> :OLD.PRORRDIAS THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PRORRDIAS', TO_CHAR(:OLD.PRORRDIAS), TO_CHAR(:NEW.PRORRDIAS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDTARIFA,-20000) <> NVL(:OLD.IDTARIFA,-20000)) THEN
      vl_Primary  := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA || ' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT ||' EDADINITARIFA: '||
                  :OLD.EDADINITARIFA ||' EDADFINTARIFA: '||:OLD.EDADFINTARIFA ||' ANIOPOL: '||:OLD.ANIOPOL ||' SEXOTARIFA: '||:OLD.SEXOTARIFA ||' RIESGOTARIFA: '||:OLD.RIESGOTARIFA ||' FACTORRESCATE: '||:OLD.FACTORRESCATE ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de VALGAR_COB_SEX_EDAD_RIESG, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_VALGAR_COB_SEX_EDAD_RIESG FOR SICAS_OC.TRG_VALGAR_COB_SEX_EDAD_RIESG;
