CREATE OR REPLACE TRIGGER SICAS_OC.TRG_DETALLE_FACT_ELECT_CONF_DOCTO
  BEFORE INSERT OR UPDATE OR DELETE ON DETALLE_FACT_ELECT_CONF_DOCTO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA DETALLE_FACT_ELECT_CONF_DOCTO
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.IDIDENTIFICADOR)||' - '||TO_CHAR(:OLD.CODIDENTIFICADOR)||' - '||TO_CHAR(:OLD.CODATRIBUTO)||' - '||TO_CHAR(:OLD.ORDENATRIB)||' - '||TO_CHAR(:OLD.CONDICIONATRIBUTO)||' - '||
                  TO_CHAR(:OLD.TIPOVALORATRIBUTO)||' - '||TO_CHAR(:OLD.VALORATRIBUTO)||' - '||TO_CHAR('CLOB')||' - '||TO_CHAR(:OLD.INDENVIACIA)||' - '||TO_CHAR(:NEW.CODRUTINACALC);  
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.IDIDENTIFICADOR)||' - '||TO_CHAR(:NEW.CODIDENTIFICADOR)||' - '||TO_CHAR(:NEW.CODATRIBUTO)||' - '||TO_CHAR(:NEW.ORDENATRIB)||' - '||TO_CHAR(:NEW.CONDICIONATRIBUTO)||' - '||
                  TO_CHAR(:NEW.TIPOVALORATRIBUTO)||' - '||TO_CHAR(:NEW.VALORATRIBUTO)||' - '||TO_CHAR('CLOB')||' - '||TO_CHAR(:NEW.INDENVIACIA)||' - '||TO_CHAR(:NEW.CODRUTINACALC);  
      vl_Primary := 'IDIDENTIFICADOR: '||:NEW.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:NEW.CODIDENTIFICADOR||' CODATRIBUTO: '||:NEW.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDIDENTIFICADOR <> :OLD.IDIDENTIFICADOR) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'IDIDENTIFICADOR', TO_CHAR(:OLD.IDIDENTIFICADOR), TO_CHAR(:NEW.IDIDENTIFICADOR), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODIDENTIFICADOR <> :OLD.CODIDENTIFICADOR) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODIDENTIFICADOR', TO_CHAR(:OLD.CODIDENTIFICADOR), TO_CHAR(:NEW.CODIDENTIFICADOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODATRIBUTO,-20000) <> NVL(:OLD.CODATRIBUTO,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODATRIBUTO', TO_CHAR(:OLD.CODATRIBUTO), TO_CHAR(:NEW.CODATRIBUTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENATRIB,-20000) <> NVL(:OLD.ORDENATRIB,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'ORDENATRIB', TO_CHAR(:OLD.ORDENATRIB), TO_CHAR(:NEW.ORDENATRIB), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CONDICIONATRIBUTO,-20000) <> NVL(:OLD.CONDICIONATRIBUTO,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CONDICIONATRIBUTO', TO_CHAR(:OLD.CONDICIONATRIBUTO), TO_CHAR(:NEW.CONDICIONATRIBUTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOVALORATRIBUTO <> :OLD.TIPOVALORATRIBUTO) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'TIPOVALORATRIBUTO', TO_CHAR(:OLD.TIPOVALORATRIBUTO), TO_CHAR(:NEW.TIPOVALORATRIBUTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.VALORATRIBUTO,-20000) <> NVL(:OLD.VALORATRIBUTO,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'VALORATRIBUTO', TO_CHAR(:OLD.VALORATRIBUTO), TO_CHAR(:NEW.VALORATRIBUTO), 'UPDATE',vl_Primary);
    END IF;
    IF (dbms_lob.getlength(:NEW.CONSULTA) <> dbms_lob.getlength(:OLD.CONSULTA)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CONSULTA', TO_CHAR('CLOB'), TO_CHAR('CLOB'), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDENVIACIA,-20000) <> NVL(:OLD.INDENVIACIA,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'INDENVIACIA', TO_CHAR(:OLD.INDENVIACIA), TO_CHAR(:NEW.INDENVIACIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRUTINACALC,-20000) <> NVL(:OLD.CODRUTINACALC,-20000)) THEN
      vl_Primary := 'IDIDENTIFICADOR: '||:OLD.IDIDENTIFICADOR||' CODIDENTIFICADOR: '||:OLD.CODIDENTIFICADOR||' CODATRIBUTO: '||:OLD.CODATRIBUTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODRUTINACALC', TO_CHAR(:OLD.CODRUTINACALC), TO_CHAR(:NEW.CODRUTINACALC), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de DETALLE_FACT_ELECT_CONF_DOCTO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_DETALLE_FACT_ELECT_CONF_DOCTO FOR SICAS_OC.TRG_DETALLE_FACT_ELECT_CONF_DOCTO;
