CREATE OR REPLACE TRIGGER TRG_D_FACT_ELECT_USO_CFDI
BEFORE DELETE
ON FACT_ELECT_USO_CFDI
FOR EACH ROW
  DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := TO_CHAR(:OLD.CODCIA)||' - '||:OLD.CODUSOCFDI||' - '||:OLD.DESCUSOCFDI||' - '||:OLD.INDPERSFISICA||' - '||:OLD.INDPERSMORAL||' - '||TO_CHAR(:OLD.FECINIVIG)||' - '||TO_CHAR(:OLD.FECFINVIG)||' - '||:OLD.CODUSUARIO||' - '||TO_CHAR(:OLD.FECMOD);
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
	
END TRG_D_FACT_ELECT_USO_CFDI;