CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONCEPTO_COMISION
  BEFORE INSERT OR UPDATE OR DELETE ON CONCEPTO_COMISION
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONCEPTO_COMISION
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCONCEPTO)||' - '||TO_CHAR(:OLD.CODTIPO)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PORCCPTO)||' - '||TO_CHAR(:OLD.MTOCPTO)||' - '||TO_CHAR(:OLD.INDMODIF)||' - '||TO_CHAR(:OLD.MTOMINAJUSTE)||' - '||
                  TO_CHAR(:OLD.MTOMAXAJUSTE)||' - '||TO_CHAR(:OLD.MTOMAXIMO)||' - '||TO_CHAR(:OLD.MTOMINIMO)||' - '||TO_CHAR(:NEW.PRIORIDAD)||' - '||TO_CHAR(:NEW.ESTADO)||' - '||TO_CHAR(:NEW.ORIGEN);  
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCONCEPTO)||' - '||TO_CHAR(:NEW.CODTIPO)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PORCCPTO)||' - '||TO_CHAR(:NEW.MTOCPTO)||' - '||TO_CHAR(:NEW.INDMODIF)||' - '||TO_CHAR(:NEW.MTOMINAJUSTE)||' - '||
                  TO_CHAR(:NEW.MTOMAXAJUSTE)||' - '||TO_CHAR(:NEW.MTOMAXIMO)||' - '||TO_CHAR(:NEW.MTOMINIMO)||' - '||TO_CHAR(:NEW.PRIORIDAD)||' - '||TO_CHAR(:NEW.ESTADO)||' - '||TO_CHAR(:NEW.ORIGEN);  
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODCONCEPTO: '||:NEW.CODCONCEPTO||' CODTIPO: '||:NEW.CODTIPO||' ORIGEN: '||:NEW.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONCEPTO_COMISION', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCONCEPTO <> :OLD.CODCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'CODCONCEPTO', TO_CHAR(:OLD.CODCONCEPTO), TO_CHAR(:NEW.CODCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODTIPO <> :OLD.CODTIPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'CODTIPO', TO_CHAR(:OLD.CODTIPO), TO_CHAR(:NEW.CODTIPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCCPTO,-20000) <> NVL(:OLD.PORCCPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'PORCCPTO', TO_CHAR(:OLD.PORCCPTO), TO_CHAR(:NEW.PORCCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOCPTO,-20000) <> NVL(:OLD.MTOCPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'MTOCPTO', TO_CHAR(:OLD.MTOCPTO), TO_CHAR(:NEW.MTOCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMODIF,-20000) <> NVL(:OLD.INDMODIF,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'INDMODIF', TO_CHAR(:OLD.INDMODIF), TO_CHAR(:NEW.INDMODIF), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.MTOMINAJUSTE <> :OLD.MTOMINAJUSTE) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'MTOMINAJUSTE', TO_CHAR(:OLD.MTOMINAJUSTE), TO_CHAR(:NEW.MTOMINAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMAXAJUSTE,-20000) <> NVL(:OLD.MTOMAXAJUSTE,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'MTOMAXAJUSTE', TO_CHAR(:OLD.MTOMAXAJUSTE), TO_CHAR(:NEW.MTOMAXAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMAXIMO,-20000) <> NVL(:OLD.MTOMAXIMO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'MTOMAXIMO', TO_CHAR(:OLD.MTOMAXIMO), TO_CHAR(:NEW.MTOMAXIMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMINIMO,-20000) <> NVL(:OLD.MTOMINIMO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'MTOMINIMO', TO_CHAR(:OLD.MTOMINIMO), TO_CHAR(:NEW.MTOMINIMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PRIORIDAD,-20000) <> NVL(:OLD.PRIORIDAD,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'PRIORIDAD', TO_CHAR(:OLD.PRIORIDAD), TO_CHAR(:NEW.PRIORIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ESTADO,-20000) <> NVL(:OLD.ESTADO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'ESTADO', TO_CHAR(:OLD.ESTADO), TO_CHAR(:NEW.ESTADO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORIGEN <> :OLD.ORIGEN) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' ORIGEN: '||:OLD.ORIGEN;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTO_COMISION', 'ORIGEN', TO_CHAR(:OLD.ORIGEN), TO_CHAR(:NEW.ORIGEN), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONCEPTO_COMISION, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONCEPTO_COMISION FOR SICAS_OC.TRG_CONCEPTO_COMISION;
