CREATE OR REPLACE TRIGGER SICAS_OC.TRG_RAMOS_CONCEPTOS_PLAN
  BEFORE INSERT OR UPDATE OR DELETE ON RAMOS_CONCEPTOS_PLAN
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA RAMOS_CONCEPTOS_PLAN
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODPLANPAGO)||' - '||TO_CHAR(:OLD.CODCPTO)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODTIPOPLAN);
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODPLANPAGO)||' - '||TO_CHAR(:NEW.CODCPTO)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODTIPOPLAN);
      vl_Primary := 'CODPLANPAGO: '||:NEW.CODPLANPAGO ||'CODCPTO: '||:NEW.CODCPTO ||'IDTIPOSEG: '||:NEW.IDTIPOSEG||'CODEMPRESA: '||:NEW.CODEMPRESA||'CODCIA: '||:NEW.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODPLANPAGO <> :OLD.CODPLANPAGO) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCPTO <> :OLD.CODCPTO) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'CODCPTO', TO_CHAR(:OLD.CODCPTO), TO_CHAR(:NEW.CODCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPOPLAN,-20000) <> NVL(:OLD.CODTIPOPLAN,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO ||'CODCPTO: '||:OLD.CODCPTO ||'IDTIPOSEG: '||:OLD.IDTIPOSEG||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMOS_CONCEPTOS_PLAN', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de RAMOS_CONCEPTOS_PLAN, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_RAMOS_CONCEPTOS_PLAN FOR SICAS_OC.TRG_RAMOS_CONCEPTOS_PLAN;
