--
-- TRG_ACTUALIZA_APROBACIONES  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   POLIZAS (Table)
--   APROBACIONES (Table)
--   LOG_TRANSACCION (Table)
--   SQ_LOGTRANSACC (Sequence)
--
CREATE OR REPLACE TRIGGER SICAS_OC.TRG_ACTUALIZA_APROBACIONES 
 BEFORE UPDATE ON SICAS_OC.APROBACIONES
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
nMaxTransaccion   LOG_TRANSACCION.Id_Transaccion%TYPE;
cCodCia           POLIZAS.CodCia%TYPE;
cIP               VARCHAR2(20);
cUsuario          VARCHAR2(30);
cTexto            VARCHAR2(4000) := 'DATOS MODIFICADOS: ';
BEGIN
  --
  SELECT SQ_LOGTRANSACC.NEXTVAL
    INTO nMaxTransaccion
    FROM DUAL;
  --
  SELECT USER
    INTO cUsuario
    FROM DUAL;
  --
  SELECT SYS_CONTEXT ('USERENV', 'IP_ADDRESS')
    INTO cIP
    FROM DUAL;
  --
  IF :NEW.NUM_APROBACION != :OLD.NUM_APROBACION THEN
     cTexto := cTexto||' - '|| 'NUM_APROBACION: '||:NEW.NUM_APROBACION;
  END IF;
  IF :NEW.IDSINIESTRO != :OLD.IDSINIESTRO THEN
     cTexto := cTexto||' - '|| 'IDSINIESTRO: '||:NEW.IDSINIESTRO;
  END IF;
  IF :NEW.IDPOLIZA != :OLD.IDPOLIZA THEN
     cTexto := cTexto||' - '|| 'IDPOLIZA: '||:NEW.IDPOLIZA;
  END IF;
  IF :NEW.IDDETSIN != :OLD.IDDETSIN THEN
     cTexto := cTexto||' - '|| 'IDDETSIN: '||:NEW.IDDETSIN;
  END IF;
  IF :NEW.TIPO_APROBACION != :OLD.TIPO_APROBACION THEN
     cTexto := cTexto||' - '|| 'TIPO_APROBACION: '||:NEW.TIPO_APROBACION;
  END IF;
  IF :NEW.MONTO_LOCAL != :OLD.MONTO_LOCAL THEN
     cTexto := cTexto||' - '|| 'MONTO_LOCAL: '||:NEW.MONTO_LOCAL;
  END IF;
  IF :NEW.MONTO_MONEDA != :OLD.MONTO_MONEDA THEN
     cTexto := cTexto||' - '|| 'MONTO_MONEDA: '||:NEW.MONTO_MONEDA;
  END IF;
  IF :NEW.STSAPROBACION != :OLD.STSAPROBACION THEN
     cTexto := cTexto||' - '|| 'STSAPROBACION: '||:NEW.STSAPROBACION;
  END IF;
  IF :NEW.TIPO_DE_APROBACION != :OLD.TIPO_DE_APROBACION THEN
     cTexto := cTexto||' - '|| 'TIPO_DE_APROBACION: '||:NEW.TIPO_DE_APROBACION;
  END IF;
  IF :NEW.IDTRANSACCION != :OLD.IDTRANSACCION THEN
     cTexto := cTexto||' - '|| 'IDTRANSACCION: '||:NEW.IDTRANSACCION;
  END IF;
  IF :NEW.INDDISPERSION != :OLD.INDDISPERSION THEN
     cTexto := cTexto||' - '|| 'INDDISPERSION: '||:NEW.INDDISPERSION;
  END IF;
  IF :NEW.CTALIQUIDADORA != :OLD.CTALIQUIDADORA THEN
     cTexto := cTexto||' - '|| 'CTALIQUIDADORA: '||:NEW.CTALIQUIDADORA;
  END IF;
  IF :NEW.IDEFACTEXT != :OLD.IDEFACTEXT THEN
     cTexto := cTexto||' - '|| 'IDEFACTEXT: '||:NEW.IDEFACTEXT;
  END IF;
  IF :NEW.BENEF != :OLD.BENEF THEN
     cTexto := cTexto||' - '|| 'BENEF: '||:NEW.BENEF;
  END IF;
  IF :NEW.IDTRANSACCIONANUL != :OLD.IDTRANSACCIONANUL THEN
     cTexto := cTexto||' - '|| 'IDTRANSACCIONANUL: '||:NEW.IDTRANSACCIONANUL;
  END IF;
--  IF :NEW.TIPOBENEF != :OLD.TIPOBENEF THEN
--     cTexto := cTexto||' - '|| 'TIPOBENEF: '||:NEW.TIPOBENEF;
--  END IF;
  --
  INSERT INTO LOG_TRANSACCION
        (Id_Transaccion, CodCia, Id_Referencia, Fecha_Transaccion, Direccion_IP,
         Num_Referencia, Origen_Transaccion, Desc_Movimiento, CodUsuario)
  VALUES(nMaxtransaccion, 1, 'APROBACIONES ' || :NEW.IdSiniestro, SYSDATE, cIP,
         :NEW.Num_Aprobacion||'-'||:NEW.IdSiniestro||'-'||:NEW.Tipo_Aprobacion, 'MODIFICA APROBACIONES', SUBSTR(cTexto,1,1000), cUsuario);
END;
/
