CREATE OR REPLACE TRIGGER SICAS_OC.TRG_DIRECCIONES_PNJ
  BEFORE INSERT OR UPDATE OR DELETE ON DIRECCIONES_PNJ
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA DIRECCIONES_PNJ
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.TIPO_DIRECCION)||' - '||TO_CHAR(:OLD.CORRELATIVO_DIRECCION)||' - '||TO_CHAR(:OLD.DIRECCION)||' - '||
                  TO_CHAR(:OLD.CODPAIS)||' - '||TO_CHAR(:OLD.CODESTADO)||' - '||TO_CHAR(:OLD.CODCIUDAD)||' - '||TO_CHAR(:OLD.CODMUNICIPIO)||' - '||TO_CHAR(:OLD.CODIGO_POSTAL)||' - '||
                  TO_CHAR(:OLD.CODASENTAMIENTO)||' - '||TO_CHAR(:OLD.CODIGO_ZIP)||' - '||TO_CHAR(:OLD.DIRECCION_PRINCIPAL)||' - '||TO_CHAR(:OLD.NUMINTERIOR)||' - '||TO_CHAR(:OLD.NUMEXTERIOR);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.TIPO_DIRECCION)||' - '||TO_CHAR(:NEW.CORRELATIVO_DIRECCION)||' - '||TO_CHAR(:NEW.DIRECCION)||' - '||
                  TO_CHAR(:NEW.CODPAIS)||' - '||TO_CHAR(:NEW.CODESTADO)||' - '||TO_CHAR(:NEW.CODCIUDAD)||' - '||TO_CHAR(:NEW.CODMUNICIPIO)||' - '||TO_CHAR(:NEW.CODIGO_POSTAL)||' - '||
                  TO_CHAR(:NEW.CODASENTAMIENTO)||' - '||TO_CHAR(:NEW.CODIGO_ZIP)||' - '||TO_CHAR(:NEW.DIRECCION_PRINCIPAL)||' - '||TO_CHAR(:NEW.NUMINTERIOR)||' - '||TO_CHAR(:NEW.NUMEXTERIOR);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:NEW.CORRELATIVO_DIRECCION;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPO_DIRECCION <> :OLD.TIPO_DIRECCION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'TIPO_DIRECCION', TO_CHAR(:OLD.TIPO_DIRECCION), TO_CHAR(:NEW.TIPO_DIRECCION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CORRELATIVO_DIRECCION <> :OLD.CORRELATIVO_DIRECCION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CORRELATIVO_DIRECCION', TO_CHAR(:OLD.CORRELATIVO_DIRECCION), TO_CHAR(:NEW.CORRELATIVO_DIRECCION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIRECCION,-20000) <> NVL(:OLD.DIRECCION,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'DIRECCION', TO_CHAR(:OLD.DIRECCION), TO_CHAR(:NEW.DIRECCION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPAIS <> :OLD.CODPAIS) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODPAIS', TO_CHAR(:OLD.CODPAIS), TO_CHAR(:NEW.CODPAIS), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODESTADO <> :OLD.CODESTADO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODESTADO', TO_CHAR(:OLD.CODESTADO), TO_CHAR(:NEW.CODESTADO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIUDAD <> :OLD.CODCIUDAD) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODCIUDAD', TO_CHAR(:OLD.CODCIUDAD), TO_CHAR(:NEW.CODCIUDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODMUNICIPIO <> :OLD.CODMUNICIPIO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODMUNICIPIO', TO_CHAR(:OLD.CODMUNICIPIO), TO_CHAR(:NEW.CODMUNICIPIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODIGO_POSTAL <> :OLD.CODIGO_POSTAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODIGO_POSTAL', TO_CHAR(:OLD.CODIGO_POSTAL), TO_CHAR(:NEW.CODIGO_POSTAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODASENTAMIENTO <> :OLD.CODASENTAMIENTO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODASENTAMIENTO', TO_CHAR(:OLD.CODASENTAMIENTO), TO_CHAR(:NEW.CODASENTAMIENTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODIGO_ZIP,-20000) <> NVL(:OLD.CODIGO_ZIP,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'CODIGO_ZIP', TO_CHAR(:OLD.CODIGO_ZIP), TO_CHAR(:NEW.CODIGO_ZIP), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DIRECCION_PRINCIPAL <> :OLD.DIRECCION_PRINCIPAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'DIRECCION_PRINCIPAL', TO_CHAR(:OLD.DIRECCION_PRINCIPAL), TO_CHAR(:NEW.DIRECCION_PRINCIPAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMINTERIOR,-20000) <> NVL(:OLD.NUMINTERIOR,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'NUMINTERIOR', TO_CHAR(:OLD.NUMINTERIOR), TO_CHAR(:NEW.NUMINTERIOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMEXTERIOR,-20000) <> NVL(:OLD.NUMEXTERIOR,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_DIRECCION: '||:OLD.CORRELATIVO_DIRECCION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'DIRECCIONES_PNJ', 'NUMEXTERIOR', TO_CHAR(:OLD.NUMEXTERIOR), TO_CHAR(:NEW.NUMEXTERIOR), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de DIRECCIONES_PNJ, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_DIRECCIONES_PNJ FOR SICAS_OC.TRG_DIRECCIONES_PNJ;
