CREATE OR REPLACE TRIGGER SICAS_OC.TRG_REQUISITOS
  BEFORE INSERT OR UPDATE OR DELETE ON REQUISITOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA REQUISITOS
    FECHA CREACIÓN: 29/02/2024
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    INDICE UNICO: CODREQUISITO - INDOBLIG
*/

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODREQUISITO)||' - '||TO_CHAR(:OLD.INDOBLIG)||' - '||TO_CHAR(:OLD.DESCREQUISITO)||' - '||TO_CHAR(:OLD.STSREQUISITO)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||
                  TO_CHAR(:OLD.USOREQUISITO)||' - '||TO_CHAR(:OLD.INDCOBERT)||' - '||TO_CHAR(:OLD.INDPLANCOB)||' - '||TO_CHAR(:OLD.TAMANIOBYTES)||' - '||TO_CHAR(:OLD.FORMATOS)||' - '||
                  TO_CHAR(:OLD.CLAVEOCR)||' - '||TO_CHAR(:OLD.TOOLTIP)||' - '||TO_CHAR(:OLD.NOMARCHIVO);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',TO_CHAR(:OLD.CODREQUISITO));
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODREQUISITO)||' - '||TO_CHAR(:NEW.INDOBLIG)||' - '||TO_CHAR(:NEW.DESCREQUISITO)||' - '||TO_CHAR(:NEW.STSREQUISITO)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||
                  TO_CHAR(:NEW.USOREQUISITO)||' - '||TO_CHAR(:NEW.INDCOBERT)||' - '||TO_CHAR(:NEW.INDPLANCOB)||' - '||TO_CHAR(:NEW.TAMANIOBYTES)||' - '||TO_CHAR(:NEW.FORMATOS)||' - '||
                  TO_CHAR(:NEW.CLAVEOCR)||' - '||TO_CHAR(:NEW.TOOLTIP)||' - '||TO_CHAR(:NEW.NOMARCHIVO);

    OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',TO_CHAR(:NEW.CODREQUISITO));
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODREQUISITO <> :OLD.CODREQUISITO) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'CODREQUISITO',  TO_CHAR(:OLD.CODREQUISITO),  TO_CHAR(:NEW.CODREQUISITO), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.INDOBLIG <> :OLD.INDOBLIG) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'INDOBLIG',  TO_CHAR(:OLD.INDOBLIG),  TO_CHAR(:NEW.INDOBLIG), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.DESCREQUISITO <> :OLD.DESCREQUISITO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'DESCREQUISITO', TO_CHAR(:OLD.DESCREQUISITO), TO_CHAR(:NEW.DESCREQUISITO), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.STSREQUISITO <> :OLD.STSREQUISITO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'STSREQUISITO', TO_CHAR(:OLD.STSREQUISITO), TO_CHAR(:NEW.STSREQUISITO), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.FECSTS <> :OLD.FECSTS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'FECSTS',  TO_CHAR(:OLD.FECSTS),  TO_CHAR(:NEW.FECSTS), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.USOREQUISITO <> :OLD.USOREQUISITO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'USOREQUISITO',  TO_CHAR(:OLD.USOREQUISITO),  TO_CHAR(:NEW.USOREQUISITO), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.INDCOBERT <> :OLD.INDCOBERT) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'INDCOBERT', TO_CHAR(:OLD.INDCOBERT), TO_CHAR(:NEW.INDCOBERT), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.INDPLANCOB <> :OLD.INDPLANCOB) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'INDPLANCOB', TO_CHAR(:OLD.INDPLANCOB), TO_CHAR(:NEW.INDPLANCOB), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.TAMANIOBYTES <> :OLD.TAMANIOBYTES) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'TAMANIOBYTES', TO_CHAR(:OLD.TAMANIOBYTES), TO_CHAR(:NEW.TAMANIOBYTES), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.FORMATOS <> :OLD.FORMATOS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'FORMATOS', TO_CHAR(:OLD.FORMATOS), TO_CHAR(:NEW.FORMATOS), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.CLAVEOCR <> :OLD.CLAVEOCR) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'CLAVEOCR', TO_CHAR(:OLD.CLAVEOCR), TO_CHAR(:NEW.CLAVEOCR), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.TOOLTIP <> :OLD.TOOLTIP) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'TOOLTIP', TO_CHAR(:OLD.TOOLTIP), TO_CHAR(:NEW.TOOLTIP), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
    IF (:NEW.NOMARCHIVO <> :OLD.NOMARCHIVO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REQUISITOS', 'NOMARCHIVO', TO_CHAR(:OLD.NOMARCHIVO), TO_CHAR(:NEW.NOMARCHIVO), 'UPDATE',TO_CHAR(:OLD.CODREQUISITO));
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de REQUISITOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_REQUISITOS FOR SICAS_OC.TRG_REQUISITOS;
/