CREATE OR REPLACE TRIGGER TRG_DELT_FACT_ELECT_CAT_GPO_LINEA
BEFORE DELETE
ON FACT_ELECT_CAT_GPO_LINEA
FOR EACH ROW
  DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := TO_CHAR(:OLD.CODCIA)||' - '||:OLD.CODIDENTIFICADOR||' - '||:OLD.DESCIDENTIFICADOR||' - '||:OLD.VERSIONCFDI||' - '||:OLD.CODUSUARIO||' - '||TO_CHAR(:OLD.FECHALINEA);
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
			
END TRG_DELT_FACT_ELECT_CAT_GPO_LINEA;