--
-- TRG_ACTUALIZA_SINIESTRO  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   LOG_TRANSACCION (Table)
--   SQ_LOGTRANSACC (Sequence)
--   SINIESTRO (Table)
--   POLIZAS (Table)
--
CREATE OR REPLACE TRIGGER SICAS_OC.TRG_ACTUALIZA_SINIESTRO 
 BEFORE UPDATE ON SICAS_OC.SINIESTRO
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
nMaxTransaccion   LOG_TRANSACCION.Id_Transaccion%TYPE;
cCodCia           POLIZAS.CodCia%TYPE;
cIP               VARCHAR2(20);
cUsuario          VARCHAR2(30);
cTexto            VARCHAR2(4000) := 'DATOS MODIFICADOS: ';
BEGIN
   --  
   SELECT SQ_LOGTRANSACC.NEXTVAL
     INTO nMaxTransaccion
     FROM DUAL;
   --           
  SELECT USER
    INTO cUsuario
    FROM DUAL;

  SELECT SYS_CONTEXT ('USERENV', 'IP_ADDRESS')
    INTO cIP
    FROM DUAL;
	
  IF :NEW.IDSINIESTRO != :OLD.IDSINIESTRO THEN
     cTexto := cTexto||' - '|| 'IDSINIESTRO: '||:NEW.IDSINIESTRO;
  END IF;
  IF :NEW.IDPOLIZA != :OLD.IDPOLIZA THEN
     cTexto := cTexto||' - '|| 'IDPOLIZA: '||:NEW.IDPOLIZA;
  END IF;
  IF :NEW.NUMSINIREF != :OLD.NUMSINIREF THEN
     cTexto := cTexto||' - '|| 'NUMSINIREF: '||:NEW.NUMSINIREF;
  END IF;
  IF :NEW.TIPO_SINIESTRO != :OLD.TIPO_SINIESTRO THEN
     cTexto := cTexto||' - '|| 'TIPO_SINIESTRO: '||:NEW.TIPO_SINIESTRO;
  END IF;
  IF :NEW.FEC_OCURRENCIA != :OLD.FEC_OCURRENCIA THEN
     cTexto := cTexto||' - '|| 'FEC_OCURRENCIA: '||:NEW.FEC_OCURRENCIA;
  END IF;
  IF :NEW.FEC_NOTIFICACION != :OLD.FEC_NOTIFICACION THEN
     cTexto := cTexto||' - '|| 'FEC_NOTIFICACION: '||:NEW.FEC_NOTIFICACION;
  END IF;
  IF :NEW.STS_SINIESTRO != :OLD.STS_SINIESTRO THEN
     cTexto := cTexto||' - '|| 'STS_SINIESTRO: '||:NEW.STS_SINIESTRO;
  END IF;
  IF :NEW.FECSTS != :OLD.FECSTS THEN
     cTexto := cTexto||' - '|| 'FECSTS: '||:NEW.FECSTS;
  END IF;
  IF :NEW.FECANUL != :OLD.FECANUL THEN
     cTexto := cTexto||' - '|| 'FECANUL: '||:NEW.FECANUL;
  END IF;
  IF :NEW.MOTIV_ANUL != :OLD.MOTIV_ANUL THEN
     cTexto := cTexto||' - '|| 'MOTIV_ANUL: '||:NEW.MOTIV_ANUL;
  END IF;
  IF :NEW.DESC_SINIESTRO != :OLD.DESC_SINIESTRO THEN
     cTexto := cTexto||' - '|| 'DESC_SINIESTRO: '||:NEW.DESC_SINIESTRO;
  END IF;
  IF :NEW.MONTO_RESERVA_LOCAL != :OLD.MONTO_RESERVA_LOCAL THEN
     cTexto := cTexto||' - '|| 'MONTO_RESERVA_LOCAL: '||:NEW.MONTO_RESERVA_LOCAL;
  END IF;
  IF :NEW.MONTO_RESERVA_MONEDA != :OLD.MONTO_RESERVA_MONEDA THEN
     cTexto := cTexto||' - '|| 'MONTO_RESERVA_MONEDA: '||:NEW.MONTO_RESERVA_MONEDA;
  END IF;
  IF :NEW.MONTO_PAGO_LOCAL != :OLD.MONTO_PAGO_LOCAL THEN
     cTexto := cTexto||' - '|| 'MONTO_PAGO_LOCAL: '||:NEW.MONTO_PAGO_LOCAL;
  END IF;
  IF :NEW.MONTO_PAGO_MONEDA != :OLD.MONTO_PAGO_MONEDA THEN
     cTexto := cTexto||' - '|| 'MONTO_PAGO_MONEDA: '||:NEW.MONTO_PAGO_MONEDA;
  END IF;
  IF :NEW.COD_MONEDA != :OLD.COD_MONEDA THEN
     cTexto := cTexto||' - '|| 'COD_MONEDA: '||:NEW.COD_MONEDA;
  END IF;
  IF :NEW.IDETPOL != :OLD.IDETPOL THEN
     cTexto := cTexto||' - '|| 'IDETPOL: '||:NEW.IDETPOL;
  END IF;
  IF :NEW.NUM_BIEN != :OLD.NUM_BIEN THEN
     cTexto := cTexto||' - '|| 'NUM_BIEN: '||:NEW.NUM_BIEN;
  END IF;
  IF :NEW.MONTO_INDEMINZACION != :OLD.MONTO_INDEMINZACION THEN
     cTexto := cTexto||' - '|| 'MONTO_INDEMINZACION: '||:NEW.MONTO_INDEMINZACION;
  END IF;
  IF :NEW.DEDUCIBLE != :OLD.DEDUCIBLE THEN
     cTexto := cTexto||' - '|| 'DEDUCIBLE: '||:NEW.DEDUCIBLE;
  END IF;
  IF :NEW.TIPO_INDEMNIZACION != :OLD.TIPO_INDEMNIZACION THEN
     cTexto := cTexto ||' - '|| 'TIPO_INDEMNIZACION: '||:NEW.TIPO_INDEMNIZACION;
  END IF;
  IF :NEW.AJUSTADOR != :OLD.AJUSTADOR THEN
     cTexto := cTexto||' - '|| 'AJUSTADOR: '||:NEW.AJUSTADOR;
  END IF;
  IF :NEW.CODCIA != :OLD.CODCIA THEN
     cTexto := cTexto||' - '|| 'CODCIA: '||:NEW.CODCIA;
  END IF;
  IF :NEW.MOTIVO_DE_SINIESTRO != :OLD.MOTIVO_DE_SINIESTRO THEN
     cTexto := cTexto||' - '|| 'MOTIVO_DE_SINIESTRO: '||:NEW.MOTIVO_DE_SINIESTRO;
  END IF;
  IF :NEW.CODEMPRESA != :OLD.CODEMPRESA THEN
     cTexto := cTexto||' - '|| 'CODEMPRESA: '||:NEW.CODEMPRESA;
  END IF;
  IF :NEW.NUMSINNOM != :OLD.NUMSINNOM THEN
     cTexto := cTexto||' - '|| 'NUMSINNOM:'|| :NEW.NUMSINNOM;
  END IF;
  IF :NEW.NUMSEMANA != :OLD.NUMSEMANA THEN
     cTexto := cTexto||' - '||'NUMSEMANA: '||:NEW.NUMSEMANA;
  END IF;
  IF :NEW.CODPAISOCURR != :OLD.CODPAISOCURR THEN
     cTexto := cTexto||' - '|| 'CODPAISOCURR: '||:NEW.CODPAISOCURR;
  END IF;
  IF :NEW.CODPROVOCURR != :OLD.CODPROVOCURR THEN
     cTexto := cTexto||' - '||'CODPROVOCURR: '||:NEW.CODPROVOCURR;
  END IF;
  IF :NEW.CODPROVEEDOR != :OLD.CODPROVEEDOR THEN
     cTexto := cTexto||' - '||'CODPROVEEDOR: '||:NEW.CODPROVEEDOR;
  END IF;
  IF :NEW.COD_ASEGURADO != :OLD.COD_ASEGURADO THEN
     cTexto := cTexto||' - '||'COD_ASEGURADO: '||:NEW.COD_ASEGURADO;
  END IF;
--  IF :NEW.IDENTIFICADOR != :OLD.IDENTIFICADOR THEN
--     cTexto := cTexto||' - '||'IDENTIFICADOR: '||:NEW.IDENTIFICADOR;
--  END IF;
  --
  INSERT INTO LOG_TRANSACCION
        (Id_Transaccion, CodCia, Id_Referencia, Fecha_Transaccion, Direccion_IP,
         Num_Referencia, Origen_Transaccion, Desc_Movimiento, CodUsuario)
  VALUES(nMaxtransaccion, :NEW.CodCia, 'SINIESTRO ' ||:NEW.IdSiniestro, SYSDATE, cIP,
         :NEW.IdSiniestro, 'MODIFICA SINIESTRO', SUBSTR(cTexto,1,1000), cUsuario);
END;
/
