CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_NOMSIN
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_NOMSIN
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_NOMSIN
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODIGO)||' - '||TO_CHAR(:OLD.NOMENCLATURA)||' - '||
                  TO_CHAR(:OLD.ANIO)||' - '||TO_CHAR(:OLD.ULTSINASIG)||' - '||TO_CHAR(:OLD.DESCIPCION);
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODIGO)||' - '||TO_CHAR(:NEW.NOMENCLATURA)||' - '||
                  TO_CHAR(:NEW.ANIO)||' - '||TO_CHAR(:NEW.ULTSINASIG)||' - '||TO_CHAR(:NEW.DESCIPCION);
      vl_Primary := 'PLANCOB: '||:NEW.PLANCOB ||' IDTIPOSEG: '||:NEW.IDTIPOSEG ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' CODCIA: '||:NEW.CODCIA;            
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_NOMSIN', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODIGO <> :OLD.CODIGO) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'CODIGO', TO_CHAR(:OLD.CODIGO), TO_CHAR(:NEW.CODIGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMENCLATURA,-20000) <> NVL(:OLD.NOMENCLATURA,-20000)) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'NOMENCLATURA', TO_CHAR(:OLD.NOMENCLATURA), TO_CHAR(:NEW.NOMENCLATURA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ANIO,-20000) <> NVL(:OLD.ANIO,-20000)) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'ANIO', TO_CHAR(:OLD.ANIO), TO_CHAR(:NEW.ANIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ULTSINASIG,-20000) <> NVL(:OLD.ULTSINASIG,-20000)) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'ULTSINASIG', TO_CHAR(:OLD.ULTSINASIG), TO_CHAR(:NEW.ULTSINASIG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCIPCION,-20000) <> NVL(:OLD.DESCIPCION,-20000)) THEN
      vl_Primary := 'PLANCOB: '||:OLD.PLANCOB ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_NOMSIN', 'DESCIPCION', TO_CHAR(:OLD.DESCIPCION), TO_CHAR(:NEW.DESCIPCION), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_NOMSIN, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_NOMSIN FOR SICAS_OC.TRG_CONFIG_NOMSIN;
