CREATE OR REPLACE TRIGGER SICAS_OC.TRG_AGENTES_CEDULA_AUTORIZADA
  BEFORE INSERT OR UPDATE OR DELETE ON AGENTES_CEDULA_AUTORIZADA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA AGENTES_CEDULA_AUTORIZADA
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.TIPOCEDULA)||' - '||TO_CHAR(:OLD.NUMCEDULA)||' - '||TO_CHAR(:OLD.FECEXPEDICION)||' - '||TO_CHAR(:OLD.FECVENCIMIENTO)||' - '||  
                  TO_CHAR(:OLD.NUMPOLRC)||' - '||TO_CHAR(:OLD.NOMASEGPOLRC)||' - '||TO_CHAR(:OLD.FECVENCPOLRC);
                  
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.TIPOCEDULA)||' - '||TO_CHAR(:NEW.NUMCEDULA)||' - '||TO_CHAR(:NEW.FECEXPEDICION)||' - '||TO_CHAR(:NEW.FECVENCIMIENTO)||' - '||  
                  TO_CHAR(:NEW.NUMPOLRC)||' - '||TO_CHAR(:NEW.NOMASEGPOLRC)||' - '||TO_CHAR(:NEW.FECVENCPOLRC);
      vl_Primary := 'COD_AGENTE: '||:NEW.COD_AGENTE ||' CODCIA: '||:NEW.CODCIA ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' TIPOCEDULA: '||:NEW.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.COD_AGENTE <> :OLD.COD_AGENTE) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOCEDULA <> :OLD.TIPOCEDULA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'TIPOCEDULA', TO_CHAR(:OLD.TIPOCEDULA), TO_CHAR(:NEW.TIPOCEDULA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUMCEDULA <> :OLD.NUMCEDULA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'NUMCEDULA', TO_CHAR(:OLD.NUMCEDULA), TO_CHAR(:NEW.NUMCEDULA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECEXPEDICION <> :OLD.FECEXPEDICION) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'FECEXPEDICION', TO_CHAR(:OLD.FECEXPEDICION), TO_CHAR(:NEW.FECEXPEDICION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECVENCIMIENTO <> :OLD.FECVENCIMIENTO) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'FECVENCIMIENTO', TO_CHAR(:OLD.FECVENCIMIENTO), TO_CHAR(:NEW.FECVENCIMIENTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMPOLRC,-20000) <> NVL(:OLD.NUMPOLRC,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'NUMPOLRC', TO_CHAR(:OLD.NUMPOLRC), TO_CHAR(:NEW.NUMPOLRC), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMASEGPOLRC,-20000) <> NVL(:OLD.NOMASEGPOLRC,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'NOMASEGPOLRC', TO_CHAR(:OLD.NOMASEGPOLRC), TO_CHAR(:NEW.NOMASEGPOLRC), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECVENCPOLRC,SYSDATE) <> NVL(:OLD.FECVENCPOLRC,SYSDATE)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE ||' CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' TIPOCEDULA: '||:OLD.TIPOCEDULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_CEDULA_AUTORIZADA', 'FECVENCPOLRC', TO_CHAR(:OLD.FECVENCPOLRC), TO_CHAR(:NEW.FECVENCPOLRC), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de AGENTES_CEDULA_AUTORIZADA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_AGENTES_CEDULA_AUTORIZADA FOR SICAS_OC.TRG_AGENTES_CEDULA_AUTORIZADA;
