-- =============================
-- Crear script TRIGGERS
-- =============================

-- =============================
--  TRIGGERS ACTUALIZA FACT_ELECT_CONF_DOCTO
-- =============================
CREATE OR REPLACE TRIGGER TRG_U_FACT_ELECT_CONF_DOCTO
BEFORE UPDATE
ON FACT_ELECT_CONF_DOCTO
FOR EACH ROW

 BEGIN
    
  IF :NEW.VERSIONCFDI != :OLD.VERSIONCFDI THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'VERSIONCFDI', :OLD.VERSIONCFDI, :NEW.VERSIONCFDI, 'UPDATE');
  
  END IF;
  
  IF :NEW.CODIDENTIFICADOR != :OLD.CODIDENTIFICADOR THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'CODIDENTIFICADOR', :OLD.CODIDENTIFICADOR, :NEW.CODIDENTIFICADOR, 'UPDATE');
  
  END IF;
  
  IF :NEW.PROCESO != :OLD.PROCESO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'PROCESO', :OLD.PROCESO, :NEW.PROCESO, 'UPDATE');
  
  END IF;
  
  IF :NEW.ORDENIDENT != :OLD.ORDENIDENT THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'ORDENIDENT', TO_CHAR(:OLD.ORDENIDENT), TO_CHAR(:NEW.ORDENIDENT), 'UPDATE');
  
  END IF;
  
  IF :NEW.INDRECURSIVO != :OLD.INDRECURSIVO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'INDRECURSIVO', :OLD.INDRECURSIVO, :NEW.INDRECURSIVO, 'UPDATE');
  
  END IF;
  
  IF :NEW.INDIMPUESTO != :OLD.INDIMPUESTO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'INDIMPUESTO', :OLD.INDIMPUESTO, :NEW.INDIMPUESTO, 'UPDATE');
  
  END IF;
  
  IF :NEW.IMPTOTRARET != :OLD.IMPTOTRARET THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'IMPTOTRARET', :OLD.IMPTOTRARET, :NEW.IMPTOTRARET, 'UPDATE');
  
  END IF;
  
  IF :NEW.CODCPTOIMPTO != :OLD.CODCPTOIMPTO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'CODCPTOIMPTO', :OLD.CODCPTOIMPTO, :NEW.CODCPTOIMPTO, 'UPDATE');
  
  END IF;
  
  IF :NEW.INDRELACION != :OLD.INDRELACION THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'INDRELACION', :OLD.INDRELACION, :NEW.INDRELACION, 'UPDATE');
  
  END IF;
  
  IF :NEW.INDVENTAPUBLICOGENERAL != :OLD.INDVENTAPUBLICOGENERAL THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'INDVENTAPUBLICOGENERAL', :OLD.INDVENTAPUBLICOGENERAL, :NEW.INDVENTAPUBLICOGENERAL, 'UPDATE');
  
  END IF;
  
 END TRG_U_FACT_ELECT_CONF_DOCTO;
