CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TIPOS_DE_SEGUROS
  BEFORE INSERT OR UPDATE OR DELETE ON TIPOS_DE_SEGUROS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000) := NULL;
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TIPOS_DE_SEGUROS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    Indice Unico: IDTIPOSEG - CODEMPRESA - CODCIA
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.DESCRIPCION)||' - '||TO_CHAR(:OLD.STSTIPSEG)||' - '||
        TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.TIPOSEG)||' - '||TO_CHAR(:OLD.IDPLANTILLA)||' - '||TO_CHAR(:OLD.CODTIPOPLAN)||' - '||TO_CHAR(:OLD.CODPLANPAGO)||' - '||
        TO_CHAR(:OLD.INDRENOVAUT)||' - '||TO_CHAR(:OLD.TIPOCONTABILIDAD)||' - '||TO_CHAR(:OLD.DIASCANCELACION)||' - '||TO_CHAR(:OLD.CLAVEFACTELECT)||' - '||TO_CHAR(:OLD.INDMANEJAFONDOS)||' - '||
        TO_CHAR(:OLD.TIPO_RIESGO)||' - '||TO_CHAR(:OLD.ID_LARGO_PLAZO)||' - '||TO_CHAR(:OLD.ID_PREPAGO)||' - '||TO_CHAR(utl_raw.cast_to_raw('BLOB'))||' - '||TO_CHAR(:OLD.INDMULTIRAMO);
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'SE ELIMINA EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.DESCRIPCION)||' - '||TO_CHAR(:NEW.STSTIPSEG)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.TIPOSEG)||' - '||TO_CHAR(:NEW.IDPLANTILLA)||' - '||TO_CHAR(:NEW.CODTIPOPLAN)
              ||' - '||TO_CHAR(:NEW.CODPLANPAGO)||' - '||TO_CHAR(:NEW.INDRENOVAUT)||' - '||TO_CHAR(:NEW.TIPOCONTABILIDAD)||' - '||TO_CHAR(:NEW.DIASCANCELACION)||' - '||TO_CHAR(:NEW.CLAVEFACTELECT)||' - '||TO_CHAR(:NEW.INDMANEJAFONDOS)||' - '||TO_CHAR(:NEW.TIPO_RIESGO)
              ||' - '||TO_CHAR(:NEW.ID_LARGO_PLAZO)||' - '||TO_CHAR(:NEW.ID_PREPAGO)||' - '||TO_CHAR(utl_raw.cast_to_raw('BLOB'))||' - '||TO_CHAR(:NEW.INDMULTIRAMO);
    vl_Primary := 'IDTIPOSEG: '||:NEW.IDTIPOSEG ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' CODCIA: '||:NEW.CODCIA ;
    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TIPOS_DE_SEGUROS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCRIPCION <> :OLD.DESCRIPCION) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'DESCRIPCION', TO_CHAR(:OLD.DESCRIPCION), TO_CHAR(:NEW.DESCRIPCION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STSTIPSEG,-20000) <> NVL(:OLD.STSTIPSEG,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'STSTIPSEG', TO_CHAR(:OLD.STSTIPSEG), TO_CHAR(:NEW.STSTIPSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECSTS,SYSDATE) <> NVL(:OLD.FECSTS,SYSDATE)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOSEG,-20000) <> NVL(:OLD.TIPOSEG,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPOSEG', TO_CHAR(:OLD.TIPOSEG), TO_CHAR(:NEW.TIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDPLANTILLA,-20000) <> NVL(:OLD.IDPLANTILLA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'IDPLANTILLA', TO_CHAR(:OLD.IDPLANTILLA), TO_CHAR(:NEW.IDPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPOPLAN,-20000) <> NVL(:OLD.CODTIPOPLAN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPLANPAGO,-20000) <> NVL(:OLD.CODPLANPAGO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRENOVAUT,-20000) <> NVL(:OLD.INDRENOVAUT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDRENOVAUT', TO_CHAR(:OLD.INDRENOVAUT), TO_CHAR(:NEW.INDRENOVAUT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOCONTABILIDAD,-20000) <> NVL(:OLD.TIPOCONTABILIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPOCONTABILIDAD', TO_CHAR(:OLD.TIPOCONTABILIDAD), TO_CHAR(:NEW.TIPOCONTABILIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIASCANCELACION,-20000) <> NVL(:OLD.DIASCANCELACION,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'DIASCANCELACION', TO_CHAR(:OLD.DIASCANCELACION), TO_CHAR(:NEW.DIASCANCELACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CLAVEFACTELECT,-20000) <> NVL(:OLD.CLAVEFACTELECT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'CLAVEFACTELECT', TO_CHAR(:OLD.CLAVEFACTELECT), TO_CHAR(:NEW.CLAVEFACTELECT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMANEJAFONDOS,-20000) <> NVL(:OLD.INDMANEJAFONDOS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDMANEJAFONDOS', TO_CHAR(:OLD.INDMANEJAFONDOS), TO_CHAR(:NEW.INDMANEJAFONDOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_RIESGO,-20000) <> NVL(:OLD.TIPO_RIESGO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'TIPO_RIESGO', TO_CHAR(:OLD.TIPO_RIESGO), TO_CHAR(:NEW.TIPO_RIESGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ID_LARGO_PLAZO,-20000) <> NVL(:OLD.ID_LARGO_PLAZO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'ID_LARGO_PLAZO', TO_CHAR(:OLD.ID_LARGO_PLAZO), TO_CHAR(:NEW.ID_LARGO_PLAZO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ID_PREPAGO,-20000) <> NVL(:OLD.ID_PREPAGO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'ID_PREPAGO', TO_CHAR(:OLD.ID_PREPAGO), TO_CHAR(:NEW.ID_PREPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (dbms_lob.compare(:OLD.QUEHACERSINIESTROS, :NEW.QUEHACERSINIESTROS) <> 0) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'QUEHACERSINIESTROS', TO_CHAR(utl_raw.cast_to_raw('BLOB')), TO_CHAR(TO_BLOB('BLOB')), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMULTIRAMO,-20000) <> NVL(:OLD.INDMULTIRAMO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TIPOS_DE_SEGUROS', 'INDMULTIRAMO', TO_CHAR(:OLD.INDMULTIRAMO), TO_CHAR(:NEW.INDMULTIRAMO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TIPOS_DE_SEGUROS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TIPOS_DE_SEGUROS FOR SICAS_OC.TRG_TIPOS_DE_SEGUROS;
