CREATE OR REPLACE TRIGGER TRG_DELT_FACT_ELECT_PROD_SERV
BEFORE DELETE
ON FACT_ELECT_PROD_SERV
FOR EACH ROW
  DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := TO_CHAR(:OLD.CODCIA)||' - '||:OLD.CLAVEPRODSERV||' - '||:OLD.DESCCLAVEPRODSERV||' - '||:OLD.INDAPLICANEGOCIO||' - '||:OLD.CLAVEUNIDAD||' - '||:OLD.CODUSUARIO||' - '||TO_CHAR(:OLD.FECULTMODIF);
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
	
END TRG_DELT_FACT_ELECT_PROD_SERV;