CREATE OR REPLACE TRIGGER TRG_UP_FACT_ELECT_CAT_CAMPOS_CFDI
BEFORE UPDATE
ON FACT_ELECT_CAT_CAMPOS_CFDI
FOR EACH ROW
  
 BEGIN
   
  IF :NEW.CODIDENTIFICADOR != :OLD.CODIDENTIFICADOR THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_CAMPOS_CFDI', 'CODIDENTIFICADOR', :OLD.CODIDENTIFICADOR, :NEW.CODIDENTIFICADOR, 'UPDATE');
 
  END IF;
  
  IF :NEW.CODATRIBUTO != :OLD.CODATRIBUTO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_CAMPOS_CFDI', 'CODATRIBUTO', :OLD.CODATRIBUTO, :NEW.CODATRIBUTO, 'UPDATE');
  
  END IF;
  
  IF :NEW.DESCATRIBUTO != :OLD.DESCATRIBUTO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_CAMPOS_CFDI', 'DESCATRIBUTO', :OLD.DESCATRIBUTO, :NEW.DESCATRIBUTO, 'UPDATE');
  
  END IF;
  
  IF :NEW.CODRUTINACALC != :OLD.CODRUTINACALC THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_CAMPOS_CFDI', 'CODRUTINACALC', :OLD.CODRUTINACALC, :NEW.CODRUTINACALC, 'UPDATE');
  
  END IF;
  
 END TRG_UP_FACT_ELECT_CAT_CAMPOS_CFDI;