CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CORREOS_ELECTRONICOS_PNJ
  BEFORE INSERT OR UPDATE OR DELETE ON CORREOS_ELECTRONICOS_PNJ
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CORREOS_ELECTRONICOS_PNJ
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.CORRELATIVO_EMAIL)||' - '||TO_CHAR(:OLD.EMAIL)||' - '||TO_CHAR(:OLD.EMAIL_PRINCIPAL);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.CORRELATIVO_EMAIL)||' - '||TO_CHAR(:NEW.EMAIL)||' - '||TO_CHAR(:NEW.EMAIL_PRINCIPAL);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:NEW.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CORRELATIVO_EMAIL <> :OLD.CORRELATIVO_EMAIL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'CORRELATIVO_EMAIL', TO_CHAR(:OLD.CORRELATIVO_EMAIL), TO_CHAR(:NEW.CORRELATIVO_EMAIL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EMAIL,-20000) <> NVL(:OLD.EMAIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'EMAIL', TO_CHAR(:OLD.EMAIL), TO_CHAR(:NEW.EMAIL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.EMAIL_PRINCIPAL <> :OLD.EMAIL_PRINCIPAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION||' CORRELATIVO_EMAIL: '||:OLD.CORRELATIVO_EMAIL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CORREOS_ELECTRONICOS_PNJ', 'EMAIL_PRINCIPAL', TO_CHAR(:OLD.EMAIL_PRINCIPAL), TO_CHAR(:NEW.EMAIL_PRINCIPAL), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CORREOS_ELECTRONICOS_PNJ, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CORREOS_ELECTRONICOS_PNJ FOR SICAS_OC.TRG_CORREOS_ELECTRONICOS_PNJ;
