CREATE OR REPLACE TRIGGER SICAS_OC.TRG_REGISTRO_TIPSEG_AUTORIDAD
  BEFORE INSERT OR UPDATE OR DELETE ON REGISTRO_TIPSEG_AUTORIDAD
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA REGISTRO_TIPSEG_AUTORIDAD
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.NUMREGISTRO)||' - '||TO_CHAR(:OLD.FECREGISTRO)||' - '||TO_CHAR(:OLD.NUMAUTORTIPSEG)||' - '||
                  TO_CHAR(:OLD.FECINGRESO)||' - '||TO_CHAR(:OLD.OBSERVACIONES)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.DS_ARCH_CONGEN)||' - '||TO_CHAR(:NEW.STREGISTRO)||' - '||TO_CHAR(:NEW.FEC_SUSPENCION)||' - '||TO_CHAR('BLOB');
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;       
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.NUMREGISTRO)||' - '||TO_CHAR(:NEW.FECREGISTRO)||' - '||TO_CHAR(:NEW.NUMAUTORTIPSEG)||' - '||
                  TO_CHAR(:NEW.FECINGRESO)||' - '||TO_CHAR(:NEW.OBSERVACIONES)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.DS_ARCH_CONGEN)||' - '||TO_CHAR(:NEW.STREGISTRO)||' - '||TO_CHAR(:NEW.FEC_SUSPENCION)||' - '||TO_CHAR('BLOB');
      vl_Primary := 'IDTIPOSEG: '||:NEW.IDTIPOSEG ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' CODCIA: '||:NEW.CODCIA ||' NUMREGISTRO: '||:NEW.NUMREGISTRO ;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUMREGISTRO <> :OLD.NUMREGISTRO) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'NUMREGISTRO', TO_CHAR(:OLD.NUMREGISTRO), TO_CHAR(:NEW.NUMREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECREGISTRO,SYSDATE) <> NVL(:OLD.FECREGISTRO,SYSDATE)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'FECREGISTRO', TO_CHAR(:OLD.FECREGISTRO), TO_CHAR(:NEW.FECREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMAUTORTIPSEG,-20000) <> NVL(:OLD.NUMAUTORTIPSEG,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'NUMAUTORTIPSEG', TO_CHAR(:OLD.NUMAUTORTIPSEG), TO_CHAR(:NEW.NUMAUTORTIPSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECINGRESO,SYSDATE) <> NVL(:OLD.FECINGRESO,SYSDATE)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'FECINGRESO', TO_CHAR(:OLD.FECINGRESO), TO_CHAR(:NEW.FECINGRESO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.OBSERVACIONES,-20000) <> NVL(:OLD.OBSERVACIONES,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'OBSERVACIONES', TO_CHAR(:OLD.OBSERVACIONES), TO_CHAR(:NEW.OBSERVACIONES), 'UPDATE',vl_Primary);
    END IF;
    IF dbms_lob.getlength(:NEW.CONDICIONESGENERALES) <> dbms_lob.getlength(:OLD.CONDICIONESGENERALES) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'CODUSUARIO', TO_CHAR('BLOB'), TO_CHAR('BLOB'), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DS_ARCH_CONGEN,-20000) <> NVL(:OLD.DS_ARCH_CONGEN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'DS_ARCH_CONGEN', TO_CHAR(:OLD.DS_ARCH_CONGEN), TO_CHAR(:NEW.DS_ARCH_CONGEN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STREGISTRO,-20000) <> NVL(:OLD.STREGISTRO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'STREGISTRO', TO_CHAR(:OLD.STREGISTRO), TO_CHAR(:NEW.STREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FEC_SUSPENCION,SYSDATE) <> NVL(:OLD.FEC_SUSPENCION,SYSDATE)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCIA: '||:OLD.CODCIA ||' NUMREGISTRO: '||:OLD.NUMREGISTRO ;  
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'REGISTRO_TIPSEG_AUTORIDAD', 'FEC_SUSPENCION', TO_CHAR(:OLD.FEC_SUSPENCION), TO_CHAR(:NEW.FEC_SUSPENCION), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de REGISTRO_TIPSEG_AUTORIDAD, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_REGISTRO_TIPSEG_AUTORIDAD FOR SICAS_OC.TRG_REGISTRO_TIPSEG_AUTORIDAD;
