CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PLAN_DE_PAGOS
  BEFORE INSERT OR UPDATE OR DELETE ON PLAN_DE_PAGOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PLAN_DE_PAGOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODPLANPAGO)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.DESCPLAN)||' - '||TO_CHAR(:OLD.NUMPAGOS)||' - '||TO_CHAR(:OLD.FRECPAGOS)||' - '||TO_CHAR(:OLD.PORCINICIAL)||' - '||
                  TO_CHAR(:OLD.STSPLAN)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.TIPOPAGO)||' - '||TO_CHAR(:OLD.INDPORCINIDINAMICO);
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODPLANPAGO)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.DESCPLAN)||' - '||TO_CHAR(:NEW.NUMPAGOS)||' - '||TO_CHAR(:NEW.FRECPAGOS)||' - '||TO_CHAR(:NEW.PORCINICIAL)||' - '||
                  TO_CHAR(:NEW.STSPLAN)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.TIPOPAGO)||' - '||TO_CHAR(:NEW.INDPORCINIDINAMICO);
      vl_Primary := 'CODPLANPAGO: '||:NEW.CODPLANPAGO||'CODEMPRESA: '||:NEW.CODEMPRESA||'CODCIA: '||:NEW.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PLAN_DE_PAGOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODPLANPAGO <> :OLD.CODPLANPAGO) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCPLAN,-20000) <> NVL(:OLD.DESCPLAN,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'DESCPLAN', TO_CHAR(:OLD.DESCPLAN), TO_CHAR(:NEW.DESCPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUMPAGOS <> :OLD.NUMPAGOS) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'NUMPAGOS', TO_CHAR(:OLD.NUMPAGOS), TO_CHAR(:NEW.NUMPAGOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FRECPAGOS,-20000) <> NVL(:OLD.FRECPAGOS,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'FRECPAGOS', TO_CHAR(:OLD.FRECPAGOS), TO_CHAR(:NEW.FRECPAGOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCINICIAL,-20000) <> NVL(:OLD.PORCINICIAL,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'PORCINICIAL', TO_CHAR(:OLD.PORCINICIAL), TO_CHAR(:NEW.PORCINICIAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STSPLAN,-20000) <> NVL(:OLD.STSPLAN,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'STSPLAN', TO_CHAR(:OLD.STSPLAN), TO_CHAR(:NEW.STSPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECSTS,SYSDATE) <> NVL(:OLD.FECSTS,SYSDATE)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOPAGO,-20000) <> NVL(:OLD.TIPOPAGO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'TIPOPAGO', TO_CHAR(:OLD.TIPOPAGO), TO_CHAR(:NEW.TIPOPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDPORCINIDINAMICO,-20000) <> NVL(:OLD.INDPORCINIDINAMICO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||'CODEMPRESA: '||:OLD.CODEMPRESA||'CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_DE_PAGOS', 'INDPORCINIDINAMICO', TO_CHAR(:OLD.INDPORCINIDINAMICO), TO_CHAR(:NEW.INDPORCINIDINAMICO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PLAN_DE_PAGOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PLAN_DE_PAGOS FOR SICAS_OC.TRG_PLAN_DE_PAGOS;
