CREATE OR REPLACE TRIGGER TRG_U_FACT_ELECT_USO_CFDI_REG
BEFORE UPDATE
ON FACT_ELECT_USO_CFDI_REG
FOR EACH ROW

 BEGIN

  IF :NEW.CODUSOCFDI != :OLD.CODUSOCFDI THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI_REG', 'CODUSOCFDI', :OLD.CODUSOCFDI, :NEW.CODUSOCFDI, 'UPDATE');

  END IF;

  IF :NEW.IDREGFISSAT != :OLD.IDREGFISSAT THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_USO_CFDI_REG', 'IDREGFISSAT', TO_CHAR(:OLD.IDREGFISSAT), TO_CHAR(:NEW.IDREGFISSAT), 'UPDATE');

  END IF;

 END TRG_U_FACT_ELECT_USO_CFDI_REG;

 03200