CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TARIFA_CONTROL_VIGENCIAS
  BEFORE INSERT OR UPDATE OR DELETE ON TARIFA_CONTROL_VIGENCIAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TARIFA_CONTROL_VIGENCIAS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: IDTARIFA
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTARIFA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||
                  TO_CHAR(:OLD.FECINITARIFA)||' - '||TO_CHAR(:OLD.FECFINTARIFA)||' - '||TO_CHAR(:OLD.OBSERVTARIFA)||' - '||TO_CHAR(:OLD.STSTARIFA)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.CODUSUARIO);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE');
  END IF;
  
  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.IDTARIFA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||
                TO_CHAR(:NEW.FECINITARIFA)||' - '||TO_CHAR(:NEW.FECFINTARIFA)||' - '||TO_CHAR(:NEW.OBSERVTARIFA)||' - '||TO_CHAR(:NEW.STSTARIFA)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.CODUSUARIO);

    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT');
  END IF;
  
  IF UPDATING THEN  
    IF :NEW.IDTARIFA <> :OLD.IDTARIFA THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE');
    END IF;
    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE');
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE');
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE');
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE');
    END IF;
    IF :NEW.FECINITARIFA <> :OLD.FECINITARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECINITARIFA', TO_CHAR(:OLD.FECINITARIFA), TO_CHAR(:NEW.FECINITARIFA), 'UPDATE');
    END IF;
    IF :NEW.FECFINTARIFA <> :OLD.FECFINTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECFINTARIFA', TO_CHAR(:OLD.FECFINTARIFA), TO_CHAR(:NEW.FECFINTARIFA), 'UPDATE');
    END IF;
    IF :NEW.OBSERVTARIFA <> :OLD.OBSERVTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODTIPOPLAN', TO_CHAR(:OLD.OBSERVTARIFA), TO_CHAR(:NEW.OBSERVTARIFA), 'UPDATE');
    END IF;
    IF :NEW.STSTARIFA <> :OLD.STSTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'STSTARIFA', TO_CHAR(:OLD.STSTARIFA), TO_CHAR(:NEW.STSTARIFA), 'UPDATE');
    END IF;
    IF :NEW.FECSTS <> :OLD.FECSTS THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE');
    END IF;
    IF :NEW.CODUSUARIO <> :OLD.CODUSUARIO THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE');
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TARIFA_CONTROL_VIGENCIAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TARIFA_CONTROL_VIGENCIAS FOR SICAS_OC.TRG_TARIFA_CONTROL_VIGENCIAS;
