CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_PLANTILLAS
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_PLANTILLAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_PLANTILLAS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODPLANTILLA)||' - '||TO_CHAR(:OLD.DESCPLANTILLA)||' - '||TO_CHAR(:OLD.TIPOPLANTILLA)||' - '||
                  TO_CHAR(:OLD.STSPLANTILLA)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.NOMARCHIVO)||' - '||TO_CHAR(:OLD.PATHARCHIVO)||' - '||TO_CHAR(:OLD.INDSEPARADOR)||' - '||
                  TO_CHAR(:OLD.TIPOSEPARADOR)||' - '||TO_CHAR(:OLD.ACCIONPLANTILLA)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO)||' - '||TO_CHAR(:OLD.CODENTIDAD);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODPLANTILLA)||' - '||TO_CHAR(:NEW.DESCPLANTILLA)||' - '||TO_CHAR(:NEW.TIPOPLANTILLA)||' - '||
                  TO_CHAR(:NEW.STSPLANTILLA)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.NOMARCHIVO)||' - '||TO_CHAR(:NEW.PATHARCHIVO)||' - '||TO_CHAR(:NEW.INDSEPARADOR)||' - '||
                  TO_CHAR(:NEW.TIPOSEPARADOR)||' - '||TO_CHAR(:NEW.ACCIONPLANTILLA)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO)||' - '||TO_CHAR(:NEW.CODENTIDAD);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' CODEMPRESA: '||:NEW.CODEMPRESA||' CODPLANTILLA: '||:NEW.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_PLANTILLAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPLANTILLA <> :OLD.CODPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'CODPLANTILLA', TO_CHAR(:OLD.CODPLANTILLA), TO_CHAR(:NEW.CODPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCPLANTILLA <> :OLD.DESCPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'DESCPLANTILLA', TO_CHAR(:OLD.DESCPLANTILLA), TO_CHAR(:NEW.DESCPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOPLANTILLA <> :OLD.TIPOPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'TIPOPLANTILLA', TO_CHAR(:OLD.TIPOPLANTILLA), TO_CHAR(:NEW.TIPOPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.STSPLANTILLA <> :OLD.STSPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'STSPLANTILLA', TO_CHAR(:OLD.STSPLANTILLA), TO_CHAR(:NEW.STSPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECSTS <> :OLD.FECSTS) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMARCHIVO,-20000) <> NVL(:OLD.NOMARCHIVO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'NOMARCHIVO', TO_CHAR(:OLD.NOMARCHIVO), TO_CHAR(:NEW.NOMARCHIVO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PATHARCHIVO,-20000) <> NVL(:OLD.PATHARCHIVO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'PATHARCHIVO', TO_CHAR(:OLD.PATHARCHIVO), TO_CHAR(:NEW.PATHARCHIVO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDSEPARADOR,-20000) <> NVL(:OLD.INDSEPARADOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'INDSEPARADOR', TO_CHAR(:OLD.INDSEPARADOR), TO_CHAR(:NEW.INDSEPARADOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOSEPARADOR,-20000) <> NVL(:OLD.TIPOSEPARADOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'TIPOSEPARADOR', TO_CHAR(:OLD.TIPOSEPARADOR), TO_CHAR(:NEW.TIPOSEPARADOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACCIONPLANTILLA,-20000) <> NVL(:OLD.ACCIONPLANTILLA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'ACCIONPLANTILLA', TO_CHAR(:OLD.ACCIONPLANTILLA), TO_CHAR(:NEW.ACCIONPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODENTIDAD,-20000) <> NVL(:OLD.CODENTIDAD,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS', 'CODENTIDAD', TO_CHAR(:OLD.CODENTIDAD), TO_CHAR(:NEW.CODENTIDAD), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_PLANTILLAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_PLANTILLAS FOR SICAS_OC.TRG_CONFIG_PLANTILLAS;
