CREATE OR REPLACE TRIGGER SICAS_OC.TRG_REP_LEGAL_PNJ
  BEFORE INSERT OR UPDATE OR DELETE ON REP_LEGAL_PNJ
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA REP_LEGAL_PNJ
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.TIPO_DOC_REP_LEGAL)||' - '||TO_CHAR(:OLD.NUM_DOC_REP_LEGAL)||' - '||TO_CHAR(:OLD.CORRELATIVO)||' - '||
                  TO_CHAR(:OLD.FECHAINICIO)||' - '||TO_CHAR(:OLD.FECHAFINAL)||' - '||TO_CHAR(:OLD.ESTADO)||' - '||TO_CHAR(:OLD.CODUSUARIO_ALTA)||' - '||TO_CHAR(:OLD.FEC_ALTA);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.TIPO_DOC_REP_LEGAL)||' - '||TO_CHAR(:NEW.NUM_DOC_REP_LEGAL)||' - '||TO_CHAR(:NEW.CORRELATIVO)||' - '||
                  TO_CHAR(:NEW.FECHAINICIO)||' - '||TO_CHAR(:NEW.FECHAFINAL)||' - '||TO_CHAR(:NEW.ESTADO)||' - '||TO_CHAR(:NEW.CODUSUARIO_ALTA)||' - '||TO_CHAR(:NEW.FEC_ALTA);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:NEW.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:NEW.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:NEW.CORRELATIVO;            
    OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPO_DOC_REP_LEGAL <> :OLD.TIPO_DOC_REP_LEGAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'TIPO_DOC_REP_LEGAL', TO_CHAR(:OLD.TIPO_DOC_REP_LEGAL), TO_CHAR(:NEW.TIPO_DOC_REP_LEGAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_REP_LEGAL <> :OLD.NUM_DOC_REP_LEGAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'NUM_DOC_REP_LEGAL', TO_CHAR(:OLD.NUM_DOC_REP_LEGAL), TO_CHAR(:NEW.NUM_DOC_REP_LEGAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CORRELATIVO <> :OLD.CORRELATIVO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'CORRELATIVO', TO_CHAR(:OLD.CORRELATIVO), TO_CHAR(:NEW.CORRELATIVO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAINICIO,SYSDATE) <> NVL(:OLD.FECHAINICIO,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'FECHAINICIO', TO_CHAR(:OLD.FECHAINICIO), TO_CHAR(:NEW.FECHAINICIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAFINAL,SYSDATE) <> NVL(:OLD.FECHAFINAL,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'FECHAFINAL', TO_CHAR(:OLD.FECHAFINAL), TO_CHAR(:NEW.FECHAFINAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ESTADO,-20000) <> NVL(:OLD.ESTADO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'ESTADO', TO_CHAR(:OLD.ESTADO), TO_CHAR(:NEW.ESTADO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO_ALTA,-20000) <> NVL(:OLD.CODUSUARIO_ALTA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'CODUSUARIO_ALTA', TO_CHAR(:OLD.CODUSUARIO_ALTA), TO_CHAR(:NEW.CODUSUARIO_ALTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FEC_ALTA,SYSDATE) <> NVL(:OLD.FEC_ALTA,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' TIPO_DOC_REP_LEGAL: '||:OLD.TIPO_DOC_REP_LEGAL ||' NUM_DOC_REP_LEGAL: '||:OLD.NUM_DOC_REP_LEGAL ||' CORRELATIVO: '||:OLD.CORRELATIVO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'REP_LEGAL_PNJ', 'FEC_ALTA', TO_CHAR(:OLD.FEC_ALTA), TO_CHAR(:NEW.FEC_ALTA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de REP_LEGAL_PNJ, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_REP_LEGAL_PNJ FOR SICAS_OC.TRG_REP_LEGAL_PNJ;
