CREATE OR REPLACE TRIGGER SICAS_OC.TRG_VALGAR_COB_SEX_EDAD_RIESG
  BEFORE INSERT OR UPDATE OR DELETE ON VALGAR_COB_SEX_EDAD_RIESG
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA VALGAR_COB_SEX_EDAD_RIESG
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: UNICOS CAMPOS QUE NO SON PK 	"FACTORSEGUROSALDADO" - "PRORRANIOS" - "PRORRDIAS" - "IDTARIFA"
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                  TO_CHAR(:OLD.EDADINITARIFA)||' - '||TO_CHAR(:OLD.EDADFINTARIFA)||' - '||TO_CHAR(:OLD.ANIOPOL)||' - '||TO_CHAR(:OLD.SEXOTARIFA)||' - '||TO_CHAR(:OLD.RIESGOTARIFA)||' - '||
                  TO_CHAR(:OLD.FACTORRESCATE)||' - '||TO_CHAR(:OLD.FACTORSEGUROSALDADO)||' - '||TO_CHAR(:OLD.PRORRANIOS)||' - '||TO_CHAR(:OLD.PRORRDIAS)||' - '||TO_CHAR(:OLD.IDTARIFA);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE');
  END IF;
  
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                  TO_CHAR(:NEW.EDADINITARIFA)||' - '||TO_CHAR(:NEW.EDADFINTARIFA)||' - '||TO_CHAR(:NEW.ANIOPOL)||' - '||TO_CHAR(:NEW.SEXOTARIFA)||' - '||TO_CHAR(:NEW.RIESGOTARIFA)||' - '||
                  TO_CHAR(:NEW.FACTORRESCATE)||' - '||TO_CHAR(:NEW.FACTORSEGUROSALDADO)||' - '||TO_CHAR(:NEW.PRORRANIOS)||' - '||TO_CHAR(:NEW.PRORRDIAS)||' - '||TO_CHAR(:NEW.IDTARIFA);

    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT');
  END IF;
  
  IF UPDATING THEN 
    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE');
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE');
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE');
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE');
    END IF;
    IF :NEW.CODCOBERT <> :OLD.CODCOBERT THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE');
    END IF;
    IF :NEW.EDADINITARIFA <> :OLD.EDADINITARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'EDADINITARIFA', TO_CHAR(:OLD.EDADINITARIFA), TO_CHAR(:NEW.EDADINITARIFA), 'UPDATE');
    END IF;
    IF :NEW.EDADFINTARIFA <> :OLD.EDADFINTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'EDADFINTARIFA', TO_CHAR(:OLD.EDADFINTARIFA), TO_CHAR(:NEW.EDADFINTARIFA), 'UPDATE');
    END IF;
    IF :NEW.ANIOPOL <> :OLD.ANIOPOL THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'ANIOPOL', TO_CHAR(:OLD.ANIOPOL), TO_CHAR(:NEW.ANIOPOL), 'UPDATE');
    END IF;
    IF :NEW.SEXOTARIFA <> :OLD.SEXOTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'SEXOTARIFA', TO_CHAR(:OLD.SEXOTARIFA), TO_CHAR(:NEW.SEXOTARIFA), 'UPDATE');
    END IF;
    IF :NEW.RIESGOTARIFA <> :OLD.RIESGOTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'RIESGOTARIFA', TO_CHAR(:OLD.RIESGOTARIFA), TO_CHAR(:NEW.RIESGOTARIFA), 'UPDATE');
    END IF;
    IF :NEW.FACTORRESCATE <> :OLD.FACTORRESCATE THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'FACTORRESCATE', TO_CHAR(:OLD.FACTORRESCATE), TO_CHAR(:NEW.FACTORRESCATE), 'UPDATE');
    END IF;
    IF :NEW.FACTORSEGUROSALDADO <> :OLD.FACTORSEGUROSALDADO THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'FACTORSEGUROSALDADO', TO_CHAR(:OLD.FACTORSEGUROSALDADO), TO_CHAR(:NEW.FACTORSEGUROSALDADO), 'UPDATE');
    END IF;
    IF :NEW.PRORRANIOS <> :OLD.PRORRANIOS THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PRORRANIOS', TO_CHAR(:OLD.PRORRANIOS), TO_CHAR(:NEW.PRORRANIOS), 'UPDATE');
    END IF;
    IF :NEW.PRORRDIAS <> :OLD.PRORRDIAS THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'PRORRDIAS', TO_CHAR(:OLD.PRORRDIAS), TO_CHAR(:NEW.PRORRDIAS), 'UPDATE');
    END IF;
    IF :NEW.IDTARIFA <> :OLD.IDTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'VALGAR_COB_SEX_EDAD_RIESG', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE');
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de VALGAR_COB_SEX_EDAD_RIESG, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_VALGAR_COB_SEX_EDAD_RIESG FOR SICAS_OC.TRG_VALGAR_COB_SEX_EDAD_RIESG;
