CREATE OR REPLACE TRIGGER SICAS_OC.TRG_RELACION_AGENTE
  BEFORE INSERT OR UPDATE OR DELETE ON RELACION_AGENTE
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA RELACION_AGENTE
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.ID_RELACION)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.TIPO_RELACION)||' - '||
                  TO_CHAR(:OLD.FECHA_HORA)||' - '||TO_CHAR(:OLD.CONTACTO)||' - '||TO_CHAR(:OLD.MOTIVO)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR('LOB');  
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.ID_RELACION)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.TIPO_RELACION)||' - '||
                  TO_CHAR(:NEW.FECHA_HORA)||' - '||TO_CHAR(:NEW.CONTACTO)||' - '||TO_CHAR(:NEW.MOTIVO)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR('LOB');  
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' COD_AGENTE: '||:NEW.COD_AGENTE||' ID_RELACION: '||:NEW.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'RELACION_AGENTE', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.COD_AGENTE <> :OLD.COD_AGENTE) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ID_RELACION <> :OLD.ID_RELACION) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'ID_RELACION', TO_CHAR(:OLD.ID_RELACION), TO_CHAR(:NEW.ID_RELACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_RELACION,-20000) <> NVL(:OLD.TIPO_RELACION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'TIPO_RELACION', TO_CHAR(:OLD.TIPO_RELACION), TO_CHAR(:NEW.TIPO_RELACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHA_HORA,SYSDATE) <> NVL(:OLD.FECHA_HORA,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'FECHA_HORA', TO_CHAR(:OLD.FECHA_HORA), TO_CHAR(:NEW.FECHA_HORA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CONTACTO,-20000) <> NVL(:OLD.CONTACTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'CONTACTO', TO_CHAR(:OLD.CONTACTO), TO_CHAR(:NEW.CONTACTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MOTIVO,-20000) <> NVL(:OLD.MOTIVO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'MOTIVO', TO_CHAR(:OLD.MOTIVO), TO_CHAR(:NEW.MOTIVO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDTIPOSEG,-20000) <> NVL(:OLD.IDTIPOSEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE||' ID_RELACION: '||:OLD.ID_RELACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RELACION_AGENTE', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de RELACION_AGENTE, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_RELACION_AGENTE FOR SICAS_OC.TRG_RELACION_AGENTE;
