CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CLAUSULAS_FACTORES
  BEFORE INSERT OR UPDATE OR DELETE ON CLAUSULAS_FACTORES
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CLAUSULAS_FACTORES
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPOFACTOR)||' - '||TO_CHAR(:OLD.CODFACTOR)||' - '||TO_CHAR(:OLD.CODCLAUSULA)||' - '||TO_CHAR(:OLD.INDPRINCIPAL)||' - '||TO_CHAR(:OLD.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:OLD.ACTUALIZO_FECHA);
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPOFACTOR)||' - '||TO_CHAR(:NEW.CODFACTOR)||' - '||TO_CHAR(:NEW.CODCLAUSULA)||' - '||TO_CHAR(:NEW.INDPRINCIPAL)||' - '||TO_CHAR(:NEW.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:NEW.ACTUALIZO_FECHA);
      vl_Primary := 'TIPOFACTOR: '||:NEW.TIPOFACTOR ||' CODFACTOR: '||:NEW.CODFACTOR ||' CODCLAUSULA: '||:NEW.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPOFACTOR <> :OLD.TIPOFACTOR) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'TIPOFACTOR', TO_CHAR(:OLD.TIPOFACTOR), TO_CHAR(:NEW.TIPOFACTOR), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODFACTOR <> :OLD.CODFACTOR) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'CODFACTOR', TO_CHAR(:OLD.CODFACTOR), TO_CHAR(:NEW.CODFACTOR), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCLAUSULA <> :OLD.CODCLAUSULA) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'CODCLAUSULA', TO_CHAR(:OLD.CODCLAUSULA), TO_CHAR(:NEW.CODCLAUSULA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDPRINCIPAL <> :OLD.INDPRINCIPAL) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'INDPRINCIPAL', TO_CHAR(:OLD.INDPRINCIPAL), TO_CHAR(:NEW.INDPRINCIPAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_USUARIO,-20000) <> NVL(:OLD.ACTUALIZO_USUARIO,-20000)) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'ACTUALIZO_USUARIO', TO_CHAR(:OLD.ACTUALIZO_USUARIO), TO_CHAR(:NEW.ACTUALIZO_USUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_FECHA,SYSDATE) <> NVL(:OLD.ACTUALIZO_FECHA,SYSDATE)) THEN
      vl_Primary := 'TIPOFACTOR: '||:OLD.TIPOFACTOR ||' CODFACTOR: '||:OLD.CODFACTOR ||' CODCLAUSULA: '||:OLD.CODCLAUSULA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CLAUSULAS_FACTORES', 'ACTUALIZO_FECHA', TO_CHAR(:OLD.ACTUALIZO_FECHA), TO_CHAR(:NEW.ACTUALIZO_FECHA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CLAUSULAS_FACTORES, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CLAUSULAS_FACTORES FOR SICAS_OC.TRG_CLAUSULAS_FACTORES;
