-- =============================
--  TRIGGERS ELIMINAR
-- =============================
CREATE OR REPLACE TRIGGER TRG_D_FACT_ELECT_CONF_DOCTO
BEFORE DELETE 
ON FACT_ELECT_CONF_DOCTO
FOR EACH ROW
DECLARE
	 cTexto     VARCHAR2(4000);
	 
 BEGIN
 
	cTexto := TO_CHAR(:OLD.IDIDENTIFICADOR)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||:OLD.VERSIONCFDI||' - '||:OLD.CODIDENTIFICADOR||' - '||:OLD.PROCESO||' - '||TO_CHAR(:OLD.ORDENIDENT)||' - '||:OLD.INDRECURSIVO||' - '||:OLD.INDIMPUESTO;
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CONF_DOCTO', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
   
END TRG_D_FACT_ELECT_CONF_DOCTO;
 
