CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PERDIDAS_ORGANICAS
  BEFORE INSERT OR UPDATE OR DELETE ON PERDIDAS_ORGANICAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PERDIDAS_ORGANICAS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                  TO_CHAR(:OLD.CODPERDORGANICA)||' - '||TO_CHAR(:OLD.FECINIINDEM)||' - '||TO_CHAR(:OLD.FECFININDEM)||' - '||TO_CHAR(:OLD.PORCENINDEMNIZACION);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                  TO_CHAR(:NEW.CODPERDORGANICA)||' - '||TO_CHAR(:NEW.FECINIINDEM)||' - '||TO_CHAR(:NEW.FECFININDEM)||' - '||TO_CHAR(:NEW.PORCENINDEMNIZACION);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG||' PLANCOB: '||:NEW.PLANCOB||' CODCOBERT: '||:NEW.CODCOBERT||' CODPERDORGANICA: '||:NEW.CODPERDORGANICA||' FECINIINDEM: '||:NEW.FECINIINDEM||' FECFININDEM: '||:NEW.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PERDIDAS_ORGANICAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCOBERT <> :OLD.CODCOBERT) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPERDORGANICA <> :OLD.CODPERDORGANICA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'CODPERDORGANICA', TO_CHAR(:OLD.CODPERDORGANICA), TO_CHAR(:NEW.CODPERDORGANICA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECINIINDEM <> :OLD.FECINIINDEM) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'FECINIINDEM', TO_CHAR(:OLD.FECINIINDEM), TO_CHAR(:NEW.FECINIINDEM), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECFININDEM <> :OLD.FECFININDEM) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'FECFININDEM', TO_CHAR(:OLD.FECFININDEM), TO_CHAR(:NEW.FECFININDEM), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PORCENINDEMNIZACION <> :OLD.PORCENINDEMNIZACION) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB||' CODCOBERT: '||:OLD.CODCOBERT||' CODPERDORGANICA: '||:OLD.CODPERDORGANICA||' FECINIINDEM: '||:OLD.FECINIINDEM||' FECFININDEM: '||:OLD.FECFININDEM;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PERDIDAS_ORGANICAS', 'PORCENINDEMNIZACION', TO_CHAR(:OLD.PORCENINDEMNIZACION), TO_CHAR(:NEW.PORCENINDEMNIZACION), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PERDIDAS_ORGANICAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PERDIDAS_ORGANICAS FOR SICAS_OC.TRG_PERDIDAS_ORGANICAS;
