CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PLANTILLAS_CONTABLES
  BEFORE INSERT OR UPDATE OR DELETE ON PLANTILLAS_CONTABLES
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PLANTILLAS_CONTABLES
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODPROCESO)||' - '||TO_CHAR(:OLD.IDREGPLANTILLA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODCPTO)||' - '||
                  TO_CHAR(:OLD.NIVELCTA1)||' - '||TO_CHAR(:OLD.NIVELCTA2)||' - '||TO_CHAR(:OLD.NIVELCTA3)||' - '||TO_CHAR(:OLD.NIVELCTA4)||' - '||TO_CHAR(:OLD.NIVELCTA5)||' - '||TO_CHAR(:OLD.NIVELCTA6)||' - '||
                  TO_CHAR(:OLD.NIVELCTA7)||' - '||TO_CHAR(:OLD.NIVELAUX)||' - '||TO_CHAR(:OLD.REGDEBCRED)||' - '||TO_CHAR(:OLD.TIPOREGISTRO)||' - '||TO_CHAR(:OLD.CODCENTROCOSTO)||' - '||TO_CHAR(:OLD.CODUNIDADNEGOCIO)||' - '||
                  TO_CHAR(:OLD.TIPOPERSONA)||' - '||TO_CHAR(:OLD.CANALCOMISVENTA)||' - '||TO_CHAR(:OLD.DESCCPTOGENERAL)||' - '||TO_CHAR(:OLD.TIPOAGENTE)||' - '||TO_CHAR(:OLD.CODMONEDA);
                  
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODPROCESO)||' - '||TO_CHAR(:NEW.IDREGPLANTILLA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODCPTO)||' - '||
                  TO_CHAR(:NEW.NIVELCTA1)||' - '||TO_CHAR(:NEW.NIVELCTA2)||' - '||TO_CHAR(:NEW.NIVELCTA3)||' - '||TO_CHAR(:NEW.NIVELCTA4)||' - '||TO_CHAR(:NEW.NIVELCTA5)||' - '||TO_CHAR(:NEW.NIVELCTA6)||' - '||
                  TO_CHAR(:NEW.NIVELCTA7)||' - '||TO_CHAR(:NEW.NIVELAUX)||' - '||TO_CHAR(:NEW.REGDEBCRED)||' - '||TO_CHAR(:NEW.TIPOREGISTRO)||' - '||TO_CHAR(:NEW.CODCENTROCOSTO)||' - '||TO_CHAR(:NEW.CODUNIDADNEGOCIO)||' - '||
                  TO_CHAR(:NEW.TIPOPERSONA)||' - '||TO_CHAR(:NEW.CANALCOMISVENTA)||' - '||TO_CHAR(:NEW.DESCCPTOGENERAL)||' - '||TO_CHAR(:NEW.TIPOAGENTE)||' - '||TO_CHAR(:NEW.CODMONEDA);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODPROCESO: '||:NEW.CODPROCESO||' IDREGPLANTILLA: '||:NEW.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PLANTILLAS_CONTABLES', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPROCESO <> :OLD.CODPROCESO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODPROCESO', TO_CHAR(:OLD.CODPROCESO), TO_CHAR(:NEW.CODPROCESO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDREGPLANTILLA <> :OLD.IDREGPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'IDREGPLANTILLA', TO_CHAR(:OLD.IDREGPLANTILLA), TO_CHAR(:NEW.IDREGPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCPTO <> :OLD.CODCPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODCPTO', TO_CHAR(:OLD.CODCPTO), TO_CHAR(:NEW.CODCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA1,-20000) <> NVL(:OLD.NIVELCTA1,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA1', TO_CHAR(:OLD.NIVELCTA1), TO_CHAR(:NEW.NIVELCTA1), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA2,-20000) <> NVL(:OLD.NIVELCTA2,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA2', TO_CHAR(:OLD.NIVELCTA2), TO_CHAR(:NEW.NIVELCTA2), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA3,-20000) <> NVL(:OLD.NIVELCTA3,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA3', TO_CHAR(:OLD.NIVELCTA3), TO_CHAR(:NEW.NIVELCTA3), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA4,-20000) <> NVL(:OLD.NIVELCTA4,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA4', TO_CHAR(:OLD.NIVELCTA4), TO_CHAR(:NEW.NIVELCTA4), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA5,-20000) <> NVL(:OLD.NIVELCTA5,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA5', TO_CHAR(:OLD.NIVELCTA5), TO_CHAR(:NEW.NIVELCTA5), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA6,-20000) <> NVL(:OLD.NIVELCTA6,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA6', TO_CHAR(:OLD.NIVELCTA6), TO_CHAR(:NEW.NIVELCTA6), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELCTA7,-20000) <> NVL(:OLD.NIVELCTA7,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELCTA7', TO_CHAR(:OLD.NIVELCTA7), TO_CHAR(:NEW.NIVELCTA7), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELAUX,-20000) <> NVL(:OLD.NIVELAUX,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'NIVELAUX', TO_CHAR(:OLD.NIVELAUX), TO_CHAR(:NEW.NIVELAUX), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.REGDEBCRED,-20000) <> NVL(:OLD.REGDEBCRED,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'REGDEBCRED', TO_CHAR(:OLD.REGDEBCRED), TO_CHAR(:NEW.REGDEBCRED), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOREGISTRO,-20000) <> NVL(:OLD.TIPOREGISTRO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'TIPOREGISTRO', TO_CHAR(:OLD.TIPOREGISTRO), TO_CHAR(:NEW.TIPOREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCENTROCOSTO,-20000) <> NVL(:OLD.CODCENTROCOSTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODCENTROCOSTO', TO_CHAR(:OLD.CODCENTROCOSTO), TO_CHAR(:NEW.CODCENTROCOSTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUNIDADNEGOCIO,-20000) <> NVL(:OLD.CODUNIDADNEGOCIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODUNIDADNEGOCIO', TO_CHAR(:OLD.CODUNIDADNEGOCIO), TO_CHAR(:NEW.CODUNIDADNEGOCIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOPERSONA,-20000) <> NVL(:OLD.TIPOPERSONA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'TIPOPERSONA', TO_CHAR(:OLD.TIPOPERSONA), TO_CHAR(:NEW.TIPOPERSONA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CANALCOMISVENTA,-20000) <> NVL(:OLD.CANALCOMISVENTA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CANALCOMISVENTA', TO_CHAR(:OLD.CANALCOMISVENTA), TO_CHAR(:NEW.CANALCOMISVENTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCCPTOGENERAL,-20000) <> NVL(:OLD.DESCCPTOGENERAL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'DESCCPTOGENERAL', TO_CHAR(:OLD.DESCCPTOGENERAL), TO_CHAR(:NEW.DESCCPTOGENERAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOAGENTE,-20000) <> NVL(:OLD.TIPOAGENTE,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'TIPOAGENTE', TO_CHAR(:OLD.TIPOAGENTE), TO_CHAR(:NEW.TIPOAGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODMONEDA,-20000) <> NVL(:OLD.CODMONEDA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODPROCESO: '||:OLD.CODPROCESO||' IDREGPLANTILLA: '||:OLD.IDREGPLANTILLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLANTILLAS_CONTABLES', 'CODMONEDA', TO_CHAR(:OLD.CODMONEDA), TO_CHAR(:NEW.CODMONEDA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PLANTILLAS_CONTABLES, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PLANTILLAS_CONTABLES FOR SICAS_OC.TRG_PLANTILLAS_CONTABLES;
