CREATE OR REPLACE TRIGGER SICAS_OC.TRG_POLIZAS_TEXTO_COTIZACION_PIPE
  BEFORE INSERT OR UPDATE OR DELETE ON POLIZAS_TEXTO_COTIZACION
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA POLIZAS_TEXTO_COTIZACION
    FECHA CREACIÓN: 21/01/2026
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  
  vl_Texto := :NEW.DESCGIRONEGOCIO;
  IF INSERTING THEN 
  
    IF REGEXP_LIKE(:NEW.DESCGIRONEGOCIO, '[^a-zA-Z0-9 ]') THEN
        :NEW.DESCGIRONEGOCIO := REGEXP_REPLACE(:NEW.DESCGIRONEGOCIO, '[¿?!¡|@$%/()=\]', '');
      END IF;
      
      IF (INSTR(:NEW.DESCGIRONEGOCIO,CHR(13))>0) THEN
        :NEW.DESCGIRONEGOCIO := REPLACE(:NEW.DESCGIRONEGOCIO, CHR(13), ' ');
      END IF;

  END IF;

  IF UPDATING THEN 
    IF (:NEW.DESCGIRONEGOCIO <> :OLD.DESCGIRONEGOCIO) THEN
      IF REGEXP_LIKE(:NEW.DESCGIRONEGOCIO, '[^a-zA-Z0-9 ]') THEN
        :NEW.DESCGIRONEGOCIO := REGEXP_REPLACE(:NEW.DESCGIRONEGOCIO, '[¿?!¡|@$%/()=\]', '');
      END IF;
      
      IF (INSTR(:NEW.DESCGIRONEGOCIO, CHR(13)) > 0) THEN
        :NEW.DESCGIRONEGOCIO := REPLACE(:NEW.DESCGIRONEGOCIO,CHR(13),' ');
      END IF;
      
    END IF;

  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de POLIZAS_TEXTO_COTIZACION, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_POLIZAS_TEXTO_COTIZACION_PIPE FOR SICAS_OC.TRG_POLIZAS_TEXTO_COTIZACION_PIPE;
