CREATE OR REPLACE TRIGGER SICAS_OC.TRG_MEDIOS_DE_COBRO
  BEFORE INSERT OR UPDATE OR DELETE ON MEDIOS_DE_COBRO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA MEDIOS_DE_COBRO
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.IDFORMACOBRO)||' - '||TO_CHAR(:OLD.INDMEDIOPRINCIPAL)||' - '||TO_CHAR(:OLD.CODFORMACOBRO)||' - '||
                  TO_CHAR(:OLD.CODENTIDADFINAN)||' - '||TO_CHAR(:OLD.NUMCUENTABANCARIA)||' - '||TO_CHAR(:OLD.NUMCUENTACLABE)||' - '||TO_CHAR(:OLD.NUMTARJETA)||' - '||TO_CHAR(:OLD.FECHAVENCTARJETA)||' - '||TO_CHAR(:OLD.NOMBRETITULAR);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.IDFORMACOBRO)||' - '||TO_CHAR(:NEW.INDMEDIOPRINCIPAL)||' - '||TO_CHAR(:NEW.CODFORMACOBRO)||' - '||
                  TO_CHAR(:NEW.CODENTIDADFINAN)||' - '||TO_CHAR(:NEW.NUMCUENTABANCARIA)||' - '||TO_CHAR(:NEW.NUMCUENTACLABE)||' - '||TO_CHAR(:NEW.NUMTARJETA)||' - '||TO_CHAR(:NEW.FECHAVENCTARJETA)||' - '||TO_CHAR(:NEW.NOMBRETITULAR);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:NEW.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDFORMACOBRO <> :OLD.IDFORMACOBRO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'IDFORMACOBRO', TO_CHAR(:OLD.IDFORMACOBRO), TO_CHAR(:NEW.IDFORMACOBRO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDMEDIOPRINCIPAL <> :OLD.INDMEDIOPRINCIPAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'INDMEDIOPRINCIPAL', TO_CHAR(:OLD.INDMEDIOPRINCIPAL), TO_CHAR(:NEW.INDMEDIOPRINCIPAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODFORMACOBRO <> :OLD.CODFORMACOBRO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'CODFORMACOBRO', TO_CHAR(:OLD.CODFORMACOBRO), TO_CHAR(:NEW.CODFORMACOBRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODENTIDADFINAN,-20000) <> NVL(:OLD.CODENTIDADFINAN,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'CODENTIDADFINAN', TO_CHAR(:OLD.CODENTIDADFINAN), TO_CHAR(:NEW.CODENTIDADFINAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMCUENTABANCARIA,-20000) <> NVL(:OLD.NUMCUENTABANCARIA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'NUMCUENTABANCARIA', TO_CHAR(:OLD.NUMCUENTABANCARIA), TO_CHAR(:NEW.NUMCUENTABANCARIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMCUENTACLABE,-20000) <> NVL(:OLD.NUMCUENTACLABE,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'NUMCUENTACLABE', TO_CHAR(:OLD.NUMCUENTACLABE), TO_CHAR(:NEW.NUMCUENTACLABE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMTARJETA,-20000) <> NVL(:OLD.NUMTARJETA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'NUMTARJETA', TO_CHAR(:OLD.NUMTARJETA), TO_CHAR(:NEW.NUMTARJETA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAVENCTARJETA,SYSDATE) <> NVL(:OLD.FECHAVENCTARJETA,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'FECHAVENCTARJETA', TO_CHAR(:OLD.FECHAVENCTARJETA), TO_CHAR(:NEW.FECHAVENCTARJETA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMBRETITULAR,-20000) <> NVL(:OLD.NOMBRETITULAR,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMACOBRO: '||:OLD.IDFORMACOBRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_COBRO', 'NOMBRETITULAR', TO_CHAR(:OLD.NOMBRETITULAR), TO_CHAR(:NEW.NOMBRETITULAR), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de MEDIOS_DE_COBRO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_MEDIOS_DE_COBRO FOR SICAS_OC.TRG_MEDIOS_DE_COBRO;
