 CREATE OR REPLACE TRIGGER SICAS_OC.TRG_DATOS_PART_SINIESTROS_PIPE
  BEFORE INSERT OR UPDATE OR DELETE ON DATOS_PART_SINIESTROS
  FOR EACH ROW 

DECLARE
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA DATOS_PART_SINIESTROS
    FECHA CREACIÓN: 21/01/2026
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF INSERTING THEN 
  
      IF REGEXP_LIKE(:NEW.CAMPO4, '[^a-zA-Z0-9 ]') THEN
        :NEW.CAMPO4 := REGEXP_REPLACE(:NEW.CAMPO4, '[|]', '');
      END IF;
      
      IF (INSTR(:NEW.CAMPO4,CHR(13))>0) THEN
        :NEW.CAMPO4 := REPLACE(:NEW.CAMPO4, CHR(13), ' ');
      END IF;
      
      IF REGEXP_LIKE(:NEW.CAMPO1, '[^a-zA-Z0-9 ]') THEN
        :NEW.CAMPO1 := REGEXP_REPLACE(:NEW.CAMPO1, '[¿?!¡|@#$%&/()=\]', '');
      END IF;
      
  END IF;

  IF UPDATING THEN 
  
    IF (:NEW.CAMPO4 <> :OLD.CAMPO4) THEN
      IF (INSTR(:NEW.CAMPO4, CHR(13)) > 0) THEN
        :NEW.CAMPO4 := REPLACE(:NEW.CAMPO4,CHR(13),' ');
      END IF;
    END IF;
    
    IF (:NEW.CAMPO4 <> :OLD.CAMPO4) THEN
      IF REGEXP_LIKE(:NEW.CAMPO4, '[^a-zA-Z0-9 ]') THEN
        :NEW.CAMPO4 := REGEXP_REPLACE(:NEW.CAMPO4, '[|]', '');
      END IF;
    END IF;
    
    IF ((:NEW.CAMPO1 <> :OLD.CAMPO1)) THEN
      IF REGEXP_LIKE(:NEW.CAMPO1, '[^a-zA-Z0-9 ]') THEN
        :NEW.CAMPO1 := REGEXP_REPLACE(:NEW.CAMPO1, '[¡|@#$%&\!=/?¿]', '');
      END IF;
    END IF;
    
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de DATOS_PART_SINIESTROS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_DATOS_PART_SINIESTROS_PIPE FOR SICAS_OC.TRG_DATOS_PART_SINIESTROS_PIPE;
