CREATE OR REPLACE TRIGGER SICAS_OC.TRG_POLIZAS_PIPE
  BEFORE INSERT OR UPDATE OR DELETE ON POLIZAS
  FOR EACH ROW 
  

DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Fuente   VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA POLIZAS
    FECHA CREACIÓN: 21/01/2026
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  
  IF INSERTING THEN 
      IF (INSTR(:NEW.CODPAQCOMERCIAL, '|') > 0) THEN
        :NEW.CODPAQCOMERCIAL := REPLACE(:NEW.CODPAQCOMERCIAL,'|','');
      END IF;
      
      IF (INSTR(:NEW.FUENTERECURSOSPRIMA, '|') > 0) THEN
        :NEW.FUENTERECURSOSPRIMA := REPLACE(:NEW.FUENTERECURSOSPRIMA,'|','');
      END IF;
      
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODPAQCOMERCIAL <> :OLD.CODPAQCOMERCIAL) THEN
      IF (INSTR(:NEW.CODPAQCOMERCIAL, '|') > 0) THEN
        :NEW.CODPAQCOMERCIAL := REPLACE(:NEW.CODPAQCOMERCIAL,'|','');
      END IF;
    END IF;
    
    IF (:NEW.FUENTERECURSOSPRIMA <> :OLD.FUENTERECURSOSPRIMA) THEN
        IF (INSTR(:NEW.FUENTERECURSOSPRIMA, '|') > 0) THEN
            :NEW.FUENTERECURSOSPRIMA := REPLACE(:NEW.FUENTERECURSOSPRIMA,'|','');
        END IF;
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de POLIZAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_POLIZAS_PIPE FOR SICAS_OC.TRG_POLIZAS_PIPE;
