CREATE OR REPLACE TRIGGER TRG_D_FACT_ELECT_CAT_CAMP_CFDI
BEFORE DELETE
ON FACT_ELECT_CAT_CAMPOS_CFDI
FOR EACH ROW
  DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := TO_CHAR(:OLD.CODCIA)||' - '||:OLD.CODIDENTIFICADOR||' - '||:OLD.CODATRIBUTO||' - '||:OLD.DESCATRIBUTO||' - '||:OLD.CODRUTINACALC;
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_CAMPOS_CFDI', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
			
END TRG_D_FACT_ELECT_CAT_CAMP_CFDI;