CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TARIFA_CONTROL_VIGENCIAS
  BEFORE INSERT OR UPDATE OR DELETE ON TARIFA_CONTROL_VIGENCIAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TARIFA_CONTROL_VIGENCIAS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: IDTARIFA
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTARIFA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||
                  TO_CHAR(:OLD.FECINITARIFA)||' - '||TO_CHAR(:OLD.FECFINTARIFA)||' - '||TO_CHAR(:OLD.OBSERVTARIFA)||' - '||TO_CHAR(:OLD.STSTARIFA)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO);
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.IDTARIFA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||
                TO_CHAR(:NEW.FECINITARIFA)||' - '||TO_CHAR(:NEW.FECFINTARIFA)||' - '||TO_CHAR(:NEW.OBSERVTARIFA)||' - '||TO_CHAR(:NEW.STSTARIFA)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO);
    vl_Primary := 'IDTARIFA: '||:NEW.IDTARIFA;
    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN  
    IF :NEW.IDTARIFA <> :OLD.IDTARIFA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.FECINITARIFA <> :OLD.FECINITARIFA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECINITARIFA', TO_CHAR(:OLD.FECINITARIFA), TO_CHAR(:NEW.FECINITARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.FECFINTARIFA <> :OLD.FECFINTARIFA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECFINTARIFA', TO_CHAR(:OLD.FECFINTARIFA), TO_CHAR(:NEW.FECFINTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF NVL(:NEW.OBSERVTARIFA,-20000) <> NVL(:OLD.OBSERVTARIFA,-20000) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODTIPOPLAN', TO_CHAR(:OLD.OBSERVTARIFA), TO_CHAR(:NEW.OBSERVTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.STSTARIFA <> :OLD.STSTARIFA THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'STSTARIFA', TO_CHAR(:OLD.STSTARIFA), TO_CHAR(:NEW.STSTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.FECSTS <> :OLD.FECSTS THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODUSUARIO <> :OLD.CODUSUARIO THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_CONTROL_VIGENCIAS', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TARIFA_CONTROL_VIGENCIAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TARIFA_CONTROL_VIGENCIAS FOR SICAS_OC.TRG_TARIFA_CONTROL_VIGENCIAS;
