CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONCEPTOS_PLAN_DE_PAGOS
  BEFORE INSERT OR UPDATE OR DELETE ON CONCEPTOS_PLAN_DE_PAGOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONCEPTOS_PLAN_DE_PAGOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODPLANPAGO)||' - '||TO_CHAR(:OLD.CODCPTO)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PORCCPTO)||' - '||TO_CHAR(:OLD.APLICA)||' - '||
                  TO_CHAR(:OLD.MTOCPTO)||' - '||TO_CHAR(:OLD.INDMODIF)||' - '||TO_CHAR(:OLD.MTOMINAJUSTE)||' - '||TO_CHAR(:OLD.MTOMAXAJUSTE)||' - '||TO_CHAR(:OLD.MTOMAXIMO)||' - '||TO_CHAR(:OLD.MTOMINIMO)||' - '||
                  TO_CHAR(:OLD.PRIORIDAD)||' - '||TO_CHAR(:OLD.RUTINACALCULO);
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODPLANPAGO)||' - '||TO_CHAR(:NEW.CODCPTO)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PORCCPTO)||' - '||TO_CHAR(:NEW.APLICA)||' - '||
                  TO_CHAR(:NEW.MTOCPTO)||' - '||TO_CHAR(:NEW.INDMODIF)||' - '||TO_CHAR(:NEW.MTOMINAJUSTE)||' - '||TO_CHAR(:NEW.MTOMAXAJUSTE)||' - '||TO_CHAR(:NEW.MTOMAXIMO)||' - '||TO_CHAR(:NEW.MTOMINIMO)||' - '||
                  TO_CHAR(:NEW.PRIORIDAD)||' - '||TO_CHAR(:NEW.RUTINACALCULO);
      vl_Primary := 'CODPLANPAGO: '||:NEW.CODPLANPAGO||' CODCPTO: '||:NEW.CODCPTO||' CODEMPRESA: '||:NEW.CODEMPRESA||' CODCIA: '||:NEW.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODPLANPAGO <> :OLD.CODPLANPAGO) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCPTO <> :OLD.CODCPTO) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'CODCPTO', TO_CHAR(:OLD.CODCPTO), TO_CHAR(:NEW.CODCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCCPTO,-20000) <> NVL(:OLD.PORCCPTO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'PORCCPTO', TO_CHAR(:OLD.PORCCPTO), TO_CHAR(:NEW.PORCCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.APLICA,-20000) <> NVL(:OLD.APLICA,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'APLICA', TO_CHAR(:OLD.APLICA), TO_CHAR(:NEW.APLICA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOCPTO,-20000) <> NVL(:OLD.MTOCPTO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'MTOCPTO', TO_CHAR(:OLD.MTOCPTO), TO_CHAR(:NEW.MTOCPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMODIF,-20000) <> NVL(:OLD.INDMODIF,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'INDMODIF', TO_CHAR(:OLD.INDMODIF), TO_CHAR(:NEW.INDMODIF), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMINAJUSTE,-20000) <> NVL(:OLD.MTOMINAJUSTE,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'MTOMINAJUSTE', TO_CHAR(:OLD.MTOMINAJUSTE), TO_CHAR(:NEW.MTOMINAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMAXAJUSTE,-20000) <> NVL(:OLD.MTOMAXAJUSTE,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'MTOMAXAJUSTE', TO_CHAR(:OLD.MTOMAXAJUSTE), TO_CHAR(:NEW.MTOMAXAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMAXIMO,-20000) <> NVL(:OLD.MTOMAXIMO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'MTOMAXIMO', TO_CHAR(:OLD.MTOMAXIMO), TO_CHAR(:NEW.MTOMAXIMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MTOMINIMO,-20000) <> NVL(:OLD.MTOMINIMO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'MTOMINIMO', TO_CHAR(:OLD.MTOMINIMO), TO_CHAR(:NEW.MTOMINIMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PRIORIDAD,-20000) <> NVL(:OLD.PRIORIDAD,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'PRIORIDAD', TO_CHAR(:OLD.PRIORIDAD), TO_CHAR(:NEW.PRIORIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.RUTINACALCULO,-20000) <> NVL(:OLD.RUTINACALCULO,-20000)) THEN
      vl_Primary := 'CODPLANPAGO: '||:OLD.CODPLANPAGO||' CODCPTO: '||:OLD.CODCPTO||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONCEPTOS_PLAN_DE_PAGOS', 'RUTINACALCULO', TO_CHAR(:OLD.RUTINACALCULO), TO_CHAR(:NEW.RUTINACALCULO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONCEPTOS_PLAN_DE_PAGOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONCEPTOS_PLAN_DE_PAGOS FOR SICAS_OC.TRG_CONCEPTOS_PLAN_DE_PAGOS;
