CREATE OR REPLACE TRIGGER SICAS_OC.TRG_AGENTES
  BEFORE INSERT OR UPDATE OR DELETE ON AGENTES
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA AGENTES
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.EST_AGENTE)||' - '||TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.TIPO_AGENTE)||' - '||
                  TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CANALCOMISVENTA)||' - '||TO_CHAR(:OLD.COD_AGENTE_JEFE)||' - '||TO_CHAR(:OLD.CODTIPO)||' - '||TO_CHAR(:OLD.CODNIVEL)||' - '||  
                  TO_CHAR(:OLD.INDPAGOSAUTOM)||' - '||TO_CHAR(:OLD.CODEJECUTIVO)||' - '||TO_CHAR(:OLD.IDFORMAPAGO)||' - '||TO_CHAR(:OLD.IDCUENTACORREO)||' - '||TO_CHAR(:OLD.INDSUJETOSUSP)||' - '||
                  TO_CHAR(:OLD.FECALTA)||' - '||TO_CHAR(:OLD.INDEXCLUIRHONORARIO)||' - '||TO_CHAR(:OLD.CLAVE_PORTAL)||' - '||TO_CHAR(:OLD.PASSWORD_PORTAL)||' - '||TO_CHAR(:OLD.INDALTAPLATAFORMA);  
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.EST_AGENTE)||' - '||TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.TIPO_AGENTE)||' - '||
                  TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CANALCOMISVENTA)||' - '||TO_CHAR(:NEW.COD_AGENTE_JEFE)||' - '||TO_CHAR(:NEW.CODTIPO)||' - '||TO_CHAR(:NEW.CODNIVEL)||' - '||  
                  TO_CHAR(:NEW.INDPAGOSAUTOM)||' - '||TO_CHAR(:NEW.CODEJECUTIVO)||' - '||TO_CHAR(:NEW.IDFORMAPAGO)||' - '||TO_CHAR(:NEW.IDCUENTACORREO)||' - '||TO_CHAR(:NEW.INDSUJETOSUSP)||' - '||
                  TO_CHAR(:NEW.FECALTA)||' - '||TO_CHAR(:NEW.INDEXCLUIRHONORARIO)||' - '||TO_CHAR(:NEW.CLAVE_PORTAL)||' - '||TO_CHAR(:NEW.PASSWORD_PORTAL)||' - '||TO_CHAR(:NEW.INDALTAPLATAFORMA);  
      vl_Primary := 'COD_AGENTE: '||:NEW.COD_AGENTE||' CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'AGENTES', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.COD_AGENTE <> :OLD.COD_AGENTE) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EST_AGENTE,-20000) <> NVL(:OLD.EST_AGENTE,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'EST_AGENTE', TO_CHAR(:OLD.EST_AGENTE), TO_CHAR(:NEW.EST_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_DOC_IDENTIFICACION,-20000) <> NVL(:OLD.TIPO_DOC_IDENTIFICACION,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUM_DOC_IDENTIFICACION,-20000) <> NVL(:OLD.NUM_DOC_IDENTIFICACION,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_AGENTE,-20000) <> NVL(:OLD.TIPO_AGENTE,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'TIPO_AGENTE', TO_CHAR(:OLD.TIPO_AGENTE), TO_CHAR(:NEW.TIPO_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CANALCOMISVENTA,-20000) <> NVL(:OLD.CANALCOMISVENTA,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CANALCOMISVENTA', TO_CHAR(:OLD.CANALCOMISVENTA), TO_CHAR(:NEW.CANALCOMISVENTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COD_AGENTE_JEFE,-20000) <> NVL(:OLD.COD_AGENTE_JEFE,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'COD_AGENTE_JEFE', TO_CHAR(:OLD.COD_AGENTE_JEFE), TO_CHAR(:NEW.COD_AGENTE_JEFE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPO,-20000) <> NVL(:OLD.CODTIPO,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CODTIPO', TO_CHAR(:OLD.CODTIPO), TO_CHAR(:NEW.CODTIPO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODNIVEL,-20000) <> NVL(:OLD.CODNIVEL,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CODNIVEL', TO_CHAR(:OLD.CODNIVEL), TO_CHAR(:NEW.CODNIVEL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDPAGOSAUTOM,-20000) <> NVL(:OLD.INDPAGOSAUTOM,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'INDPAGOSAUTOM', TO_CHAR(:OLD.INDPAGOSAUTOM), TO_CHAR(:NEW.INDPAGOSAUTOM), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODEJECUTIVO,-20000) <> NVL(:OLD.CODEJECUTIVO,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CODEJECUTIVO', TO_CHAR(:OLD.CODEJECUTIVO), TO_CHAR(:NEW.CODEJECUTIVO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDFORMAPAGO,-20000) <> NVL(:OLD.IDFORMAPAGO,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'IDFORMAPAGO', TO_CHAR(:OLD.IDFORMAPAGO), TO_CHAR(:NEW.IDFORMAPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDCUENTACORREO,-20000) <> NVL(:OLD.IDCUENTACORREO,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'IDCUENTACORREO', TO_CHAR(:OLD.IDCUENTACORREO), TO_CHAR(:NEW.IDCUENTACORREO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDSUJETOSUSP,-20000) <> NVL(:OLD.INDSUJETOSUSP,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'INDSUJETOSUSP', TO_CHAR(:OLD.INDSUJETOSUSP), TO_CHAR(:NEW.INDSUJETOSUSP), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECALTA,SYSDATE) <> NVL(:OLD.FECALTA,SYSDATE)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'FECALTA', TO_CHAR(:OLD.FECALTA), TO_CHAR(:NEW.FECALTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDEXCLUIRHONORARIO,-20000) <> NVL(:OLD.INDEXCLUIRHONORARIO,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'INDEXCLUIRHONORARIO', TO_CHAR(:OLD.INDEXCLUIRHONORARIO), TO_CHAR(:NEW.INDEXCLUIRHONORARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CLAVE_PORTAL,-20000) <> NVL(:OLD.CLAVE_PORTAL,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'CLAVE_PORTAL', TO_CHAR(:OLD.CLAVE_PORTAL), TO_CHAR(:NEW.CLAVE_PORTAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PASSWORD_PORTAL,-20000) <> NVL(:OLD.PASSWORD_PORTAL,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'PASSWORD_PORTAL', TO_CHAR(:OLD.PASSWORD_PORTAL), TO_CHAR(:NEW.PASSWORD_PORTAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDALTAPLATAFORMA,-20000) <> NVL(:OLD.INDALTAPLATAFORMA,-20000)) THEN
      vl_Primary := 'COD_AGENTE: '||:OLD.COD_AGENTE||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES', 'INDALTAPLATAFORMA', TO_CHAR(:OLD.INDALTAPLATAFORMA), TO_CHAR(:NEW.INDALTAPLATAFORMA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de AGENTES, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_AGENTES FOR SICAS_OC.TRG_AGENTES;
