CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TARIFA_DINAMICA_DET
  BEFORE INSERT OR UPDATE OR DELETE ON TARIFA_DINAMICA_DET
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TARIFA_DINAMICA_DET
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTARIFA)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||TO_CHAR(:OLD.TIPOTARIFA)||' - '||TO_CHAR(:OLD.IDCAMPO)||' - '||TO_CHAR(:OLD.INDAPLICFORMULA)||' - '||TO_CHAR(:OLD.CODCAMPO)||' - '||
                  TO_CHAR(:OLD.ORDENPROCCAMPO)||' - '||TO_CHAR(:OLD.CODCONDICION)||' - '||TO_CHAR(:OLD.VALORINICOND)||' - '||TO_CHAR(:OLD.VALORFINCOND)||' - '||TO_CHAR(:OLD.VALORTARIFA)||' - '||
                  TO_CHAR(:OLD.CAMPOVALOR)||' - '||TO_CHAR(:OLD.ORDENPROCCAMPOVAL)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO)||' - '||TO_CHAR(:OLD.ORDENCAMPO)||' - '||TO_CHAR(:OLD.TIPOPROCESO);
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTARIFA)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||TO_CHAR(:NEW.TIPOTARIFA)||' - '||TO_CHAR(:NEW.IDCAMPO)||' - '||TO_CHAR(:NEW.INDAPLICFORMULA)||' - '||TO_CHAR(:NEW.CODCAMPO)||' - '||
                  TO_CHAR(:NEW.ORDENPROCCAMPO)||' - '||TO_CHAR(:NEW.CODCONDICION)||' - '||TO_CHAR(:NEW.VALORINICOND)||' - '||TO_CHAR(:NEW.VALORFINCOND)||' - '||TO_CHAR(:NEW.VALORTARIFA)||' - '||
                  TO_CHAR(:NEW.CAMPOVALOR)||' - '||TO_CHAR(:NEW.ORDENPROCCAMPOVAL)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO)||' - '||TO_CHAR(:NEW.ORDENCAMPO)||' - '||TO_CHAR(:NEW.TIPOPROCESO);
      vl_Primary := 'IDTARIFA: '||:NEW.IDTARIFA|| ' CODCOBERT: '||:NEW.CODCOBERT || ' TIPOTARIFA: '||:NEW.TIPOTARIFA || ' IDCAMPO: '||:NEW.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTARIFA <> :OLD.IDTARIFA) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCOBERT <> :OLD.CODCOBERT) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOTARIFA <> :OLD.TIPOTARIFA) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'TIPOTARIFA', TO_CHAR(:OLD.TIPOTARIFA), TO_CHAR(:NEW.TIPOTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDCAMPO <> :OLD.IDCAMPO) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'IDCAMPO', TO_CHAR(:OLD.IDCAMPO), TO_CHAR(:NEW.IDCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDAPLICFORMULA <> :OLD.INDAPLICFORMULA) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'INDAPLICFORMULA', TO_CHAR(:OLD.INDAPLICFORMULA), TO_CHAR(:NEW.INDAPLICFORMULA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCAMPO <> :OLD.CODCAMPO) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'CODCAMPO', TO_CHAR(:OLD.CODCAMPO), TO_CHAR(:NEW.CODCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORDENPROCCAMPO <> :OLD.ORDENPROCCAMPO) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'ORDENPROCCAMPO', TO_CHAR(:OLD.ORDENPROCCAMPO), TO_CHAR(:NEW.ORDENPROCCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCONDICION <> :OLD.CODCONDICION) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'CODCONDICION', TO_CHAR(:OLD.CODCONDICION), TO_CHAR(:NEW.CODCONDICION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.VALORINICOND <> :OLD.VALORINICOND) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'VALORINICOND', TO_CHAR(:OLD.VALORINICOND), TO_CHAR(:NEW.VALORINICOND), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.VALORFINCOND,-20000) <> NVL(:OLD.VALORFINCOND,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'VALORFINCOND', TO_CHAR(:OLD.VALORFINCOND), TO_CHAR(:NEW.VALORFINCOND), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.VALORTARIFA,-20000) <> NVL(:OLD.VALORTARIFA,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'VALORTARIFA', TO_CHAR(:OLD.VALORTARIFA), TO_CHAR(:NEW.VALORTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CAMPOVALOR,-20000) <> NVL(:OLD.CAMPOVALOR,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'CAMPOVALOR', TO_CHAR(:OLD.CAMPOVALOR), TO_CHAR(:NEW.CAMPOVALOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENPROCCAMPOVAL,-20000) <> NVL(:OLD.ORDENPROCCAMPOVAL,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'ORDENPROCCAMPOVAL', TO_CHAR(:OLD.ORDENPROCCAMPOVAL), TO_CHAR(:NEW.ORDENPROCCAMPOVAL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENCAMPO,-20000) <> NVL(:OLD.ORDENCAMPO,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'ORDENCAMPO', TO_CHAR(:OLD.ORDENCAMPO), TO_CHAR(:NEW.ORDENCAMPO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOPROCESO,-20000) <> NVL(:OLD.TIPOPROCESO,-20000)) THEN
      vl_Primary := 'IDTARIFA: '||:OLD.IDTARIFA|| ' CODCOBERT: '||:OLD.CODCOBERT || ' TIPOTARIFA: '||:OLD.TIPOTARIFA || ' IDCAMPO: '||:OLD.IDCAMPO; 
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TARIFA_DINAMICA_DET', 'TIPOPROCESO', TO_CHAR(:OLD.TIPOPROCESO), TO_CHAR(:NEW.TIPOPROCESO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TARIFA_DINAMICA_DET, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TARIFA_DINAMICA_DET FOR SICAS_OC.TRG_TARIFA_DINAMICA_DET;
