CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PLAN_COBERTURAS
  BEFORE INSERT OR UPDATE OR DELETE ON PLAN_COBERTURAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PLAN_COBERTURAS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    INDICE UNICO: IDTIPOSEG - CODEMPRESA - CODCIA - PLANCOB
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.DESC_PLAN)||' - '||
                  TO_CHAR(:OLD.ULTMODPLAN)||' - '||TO_CHAR(:OLD.ESTADO_PLAN)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.TIPPLANCOB)||' - '||TO_CHAR(:OLD.CODMONEDA)||' - '||
                  TO_CHAR(:OLD.CODTIPOPLAN)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.DIASRETROACTIVOS)||' - '||TO_CHAR(:OLD.MODALIDAD)||' - '||TO_CHAR(:OLD.PLANPOLIZA)||' - '||
                  TO_CHAR(:OLD.INDISPUTABILIDAD)||' - '||TO_CHAR(:OLD.CODTEMPORALIDAD)||' - '||TO_CHAR(:OLD.INDAPLICASAMI)||' - '||TO_CHAR(:OLD.COMMINIMA)||' - '||TO_CHAR(:OLD.COMMAXIMA)||' - '||
                  TO_CHAR(:OLD.PORCGTOADMIN)||' - '||TO_CHAR(:OLD.PORCGTOADQUI)||' - '||TO_CHAR(:OLD.PORCUTILIDAD)||' - '||TO_CHAR(:OLD.DIASRETROREN)||' - '||TO_CHAR(:OLD.DURACIONPLAN)||' - '||
                  TO_CHAR(:OLD.PORCDESCUENTO)||' - '||TO_CHAR(:OLD.PORCEXTRAPRIMA)||' - '||TO_CHAR(:OLD.MONTOEXTRAPRIMA)||' - '||TO_CHAR(:OLD.FACTORAJUSTE)||' - '||TO_CHAR(:OLD.MONTODEDUCIBLE)||' - '||
                  TO_CHAR(:OLD.FACTFORMULADEDUC)||' - '||TO_CHAR(:OLD.PREFIJOPOL)||' - '||TO_CHAR(:OLD.DIASEXTRASCANCEL)||' - '||TO_CHAR(:OLD.DIASSINPAGOFONDOS)||' - '||TO_CHAR(:OLD.ID_LARGO_PLAZO)||' - '||TO_CHAR(:OLD.SUMA_ASEG_MAX);
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.DESC_PLAN)||' - '||
                  TO_CHAR(:NEW.ULTMODPLAN)||' - '||TO_CHAR(:NEW.ESTADO_PLAN)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.TIPPLANCOB)||' - '||TO_CHAR(:NEW.CODMONEDA)||' - '||
                  TO_CHAR(:NEW.CODTIPOPLAN)||' - '||TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.DIASRETROACTIVOS)||' - '||TO_CHAR(:NEW.MODALIDAD)||' - '||TO_CHAR(:NEW.PLANPOLIZA)||' - '||
                  TO_CHAR(:NEW.INDISPUTABILIDAD)||' - '||TO_CHAR(:NEW.CODTEMPORALIDAD)||' - '||TO_CHAR(:NEW.INDAPLICASAMI)||' - '||TO_CHAR(:NEW.COMMINIMA)||' - '||TO_CHAR(:NEW.COMMAXIMA)||' - '||
                  TO_CHAR(:NEW.PORCGTOADMIN)||' - '||TO_CHAR(:NEW.PORCGTOADQUI)||' - '||TO_CHAR(:NEW.PORCUTILIDAD)||' - '||TO_CHAR(:NEW.DIASRETROREN)||' - '||TO_CHAR(:NEW.DURACIONPLAN)||' - '||
                  TO_CHAR(:NEW.PORCDESCUENTO)||' - '||TO_CHAR(:NEW.PORCEXTRAPRIMA)||' - '||TO_CHAR(:NEW.MONTOEXTRAPRIMA)||' - '||TO_CHAR(:NEW.FACTORAJUSTE)||' - '||TO_CHAR(:NEW.MONTODEDUCIBLE)||' - '||
                  TO_CHAR(:NEW.FACTFORMULADEDUC)||' - '||TO_CHAR(:NEW.PREFIJOPOL)||' - '||TO_CHAR(:NEW.DIASEXTRASCANCEL)||' - '||TO_CHAR(:NEW.DIASSINPAGOFONDOS)||' - '||TO_CHAR(:NEW.ID_LARGO_PLAZO)||' - '||TO_CHAR(:NEW.SUMA_ASEG_MAX);
      vl_Primary := 'IDTIPOSEG: '||:NEW.IDTIPOSEG ||'CODEMPRESA: '||:NEW.CODEMPRESA ||'CODCIA: '||:NEW.CODCIA||'PLANCOB: '||:NEW.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PLAN_COBERTURAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'IDTIPOSEG',  TO_CHAR(:OLD.IDTIPOSEG),  TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODEMPRESA',  TO_CHAR(:OLD.CODEMPRESA),  TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESC_PLAN <> :OLD.DESC_PLAN) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DESC_PLAN',  TO_CHAR(:OLD.DESC_PLAN),  TO_CHAR(:NEW.DESC_PLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ULTMODPLAN,SYSDATE) <> NVL(:OLD.ULTMODPLAN,SYSDATE)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ULTMODPLAN',  TO_CHAR(:OLD.ULTMODPLAN),  TO_CHAR(:NEW.ULTMODPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ESTADO_PLAN,-20000) <> NVL(:OLD.ESTADO_PLAN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ESTADO_PLAN', TO_CHAR(:OLD.ESTADO_PLAN), TO_CHAR(:NEW.ESTADO_PLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPPLANCOB,-20000) <> NVL(:OLD.TIPPLANCOB,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'TIPPLANCOB', TO_CHAR(:OLD.TIPPLANCOB), TO_CHAR(:NEW.TIPPLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODMONEDA,-20000) <> NVL(:OLD.CODMONEDA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODMONEDA', TO_CHAR(:OLD.CODMONEDA), TO_CHAR(:NEW.CODMONEDA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPOPLAN,-20000) <> NVL(:OLD.CODTIPOPLAN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COD_AGENTE,-20000) <> NVL(:OLD.COD_AGENTE,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIASRETROACTIVOS,-20000) <> NVL(:OLD.DIASRETROACTIVOS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASRETROACTIVOS', TO_CHAR(:OLD.DIASRETROACTIVOS), TO_CHAR(:NEW.DIASRETROACTIVOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MODALIDAD,-20000) <> NVL(:OLD.MODALIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MODALIDAD', TO_CHAR(:OLD.MODALIDAD), TO_CHAR(:NEW.MODALIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PLANPOLIZA,-20000) <> NVL(:OLD.PLANPOLIZA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PLANPOLIZA', TO_CHAR(:OLD.PLANPOLIZA), TO_CHAR(:NEW.PLANPOLIZA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDISPUTABILIDAD,-20000) <> NVL(:OLD.INDISPUTABILIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'INDISPUTABILIDAD', TO_CHAR(:OLD.INDISPUTABILIDAD), TO_CHAR(:NEW.INDISPUTABILIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTEMPORALIDAD,-20000) <> NVL(:OLD.CODTEMPORALIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODTEMPORALIDAD', TO_CHAR(:OLD.CODTEMPORALIDAD), TO_CHAR(:NEW.CODTEMPORALIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAPLICASAMI,-20000) <> NVL(:OLD.INDAPLICASAMI,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'INDAPLICASAMI', TO_CHAR(:OLD.INDAPLICASAMI), TO_CHAR(:NEW.INDAPLICASAMI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COMMINIMA,-20000) <> NVL(:OLD.COMMINIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COMMINIMA', TO_CHAR(:OLD.COMMINIMA), TO_CHAR(:NEW.COMMINIMA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COMMAXIMA,-20000) <> NVL(:OLD.COMMAXIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COMMAXIMA', TO_CHAR(:OLD.COMMAXIMA), TO_CHAR(:NEW.COMMAXIMA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCGTOADMIN,-20000) <> NVL(:OLD.PORCGTOADMIN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCGTOADMIN', TO_CHAR(:OLD.PORCGTOADMIN), TO_CHAR(:NEW.PORCGTOADMIN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCGTOADQUI,-20000) <> NVL(:OLD.PORCGTOADQUI,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCGTOADQUI', TO_CHAR(:OLD.PORCGTOADQUI), TO_CHAR(:NEW.PORCGTOADQUI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCUTILIDAD,-20000) <> NVL(:OLD.PORCUTILIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCUTILIDAD', TO_CHAR(:OLD.PORCUTILIDAD), TO_CHAR(:NEW.PORCUTILIDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIASRETROREN,-20000) <> NVL(:OLD.DIASRETROREN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASRETROREN', TO_CHAR(:OLD.DIASRETROREN), TO_CHAR(:NEW.DIASRETROREN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DURACIONPLAN,-20000) <> NVL(:OLD.DURACIONPLAN,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DURACIONPLAN', TO_CHAR(:OLD.DURACIONPLAN), TO_CHAR(:NEW.DURACIONPLAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCDESCUENTO,-20000) <> NVL(:OLD.PORCDESCUENTO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCDESCUENTO', TO_CHAR(:OLD.PORCDESCUENTO), TO_CHAR(:NEW.PORCDESCUENTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCEXTRAPRIMA,-20000) <> NVL(:OLD.PORCEXTRAPRIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCEXTRAPRIMA', TO_CHAR(:OLD.PORCEXTRAPRIMA), TO_CHAR(:NEW.PORCEXTRAPRIMA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTOEXTRAPRIMA,-20000) <> NVL(:OLD.MONTOEXTRAPRIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MONTOEXTRAPRIMA', TO_CHAR(:OLD.MONTOEXTRAPRIMA), TO_CHAR(:NEW.MONTOEXTRAPRIMA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FACTORAJUSTE,-20000) <> NVL(:OLD.FACTORAJUSTE,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'FACTORAJUSTE', TO_CHAR(:OLD.FACTORAJUSTE), TO_CHAR(:NEW.FACTORAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTODEDUCIBLE,-20000) <> NVL(:OLD.MONTODEDUCIBLE,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MONTODEDUCIBLE', TO_CHAR(:OLD.MONTODEDUCIBLE), TO_CHAR(:NEW.MONTODEDUCIBLE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FACTFORMULADEDUC,-20000) <> NVL(:OLD.FACTFORMULADEDUC,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'FACTFORMULADEDUC', TO_CHAR(:OLD.FACTFORMULADEDUC), TO_CHAR(:NEW.FACTFORMULADEDUC), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PREFIJOPOL,-20000) <> NVL(:OLD.PREFIJOPOL,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PREFIJOPOL', TO_CHAR(:OLD.PREFIJOPOL), TO_CHAR(:NEW.PREFIJOPOL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIASEXTRASCANCEL,-20000) <> NVL(:OLD.DIASEXTRASCANCEL,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASEXTRASCANCEL', TO_CHAR(:OLD.DIASEXTRASCANCEL), TO_CHAR(:NEW.DIASEXTRASCANCEL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIASSINPAGOFONDOS,-20000) <> NVL(:OLD.DIASSINPAGOFONDOS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASSINPAGOFONDOS', TO_CHAR(:OLD.DIASSINPAGOFONDOS), TO_CHAR(:NEW.DIASSINPAGOFONDOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ID_LARGO_PLAZO,-20000) <> NVL(:OLD.ID_LARGO_PLAZO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ID_LARGO_PLAZO', TO_CHAR(:OLD.ID_LARGO_PLAZO), TO_CHAR(:NEW.ID_LARGO_PLAZO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUMA_ASEG_MAX,-20000) <> NVL(:OLD.SUMA_ASEG_MAX,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG ||'CODEMPRESA: '||:OLD.CODEMPRESA ||'CODCIA: '||:OLD.CODCIA||'PLANCOB: '||:OLD.PLANCOB;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'SUMA_ASEG_MAX', TO_CHAR(:OLD.SUMA_ASEG_MAX), TO_CHAR(:NEW.SUMA_ASEG_MAX), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PLAN_COBERTURAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PLAN_COBERTURAS FOR SICAS_OC.TRG_PLAN_COBERTURAS;
