CREATE OR REPLACE TRIGGER TRG_DELT_FACT_ELECT_SERIES_FOLIOS
BEFORE DELETE
ON FACT_ELECT_SERIES_FOLIOS
FOR EACH ROW
  DECLARE
     cTexto     VARCHAR2(4000);
	 
 BEGIN
 
    cTexto := :OLD.TIPOCFDI||' - '||:OLD.TIPODOCUMENTO||' - '||:OLD.SERIE||' - '||TO_CHAR(:OLD.FOLIO)||' - '||TO_CHAR(:OLD.FECINIVIG)||' - '||TO_CHAR(:OLD.FECFINVIG)||' - '||:OLD.CODUSUARIO||' - '||TO_CHAR(:OLD.FECCONFIG);
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_SERIES_FOLIOS', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
	
END TRG_DELT_FACT_ELECT_SERIES_FOLIOS;