CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TARIFA_SEXO_EDAD_RIESGO
  BEFORE INSERT OR UPDATE OR DELETE ON TARIFA_SEXO_EDAD_RIESGO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TARIFA_SEXO_EDAD_RIESGO
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: UNICOS CAMPOS QUE NO SON PK "PRIMATARIFA" - "TASATARIFA" - "TASANIVELADA" - "PORCGTOADMIN" 
  */
  
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                TO_CHAR(:OLD.EDADINITARIFA)||' - '||TO_CHAR(:OLD.EDADFINTARIFA)||' - '||TO_CHAR(:OLD.SEXOTARIFA)||' - '||TO_CHAR(:OLD.RIESGOTARIFA)||' - '||TO_CHAR(:OLD.SUMAASEGTARIFA)||' - '||
                TO_CHAR(:OLD.PRIMATARIFA)||' - '||TO_CHAR(:OLD.TASATARIFA)||' - '||TO_CHAR(:OLD.TASANIVELADA)||' - '||TO_CHAR(:OLD.IDTARIFA)||' - '||TO_CHAR(:OLD.PORCGTOADMIN)||' - '||TO_CHAR(:OLD.HABITOTARIFA);
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
  
  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                TO_CHAR(:NEW.EDADINITARIFA)||' - '||TO_CHAR(:NEW.EDADFINTARIFA)||' - '||TO_CHAR(:NEW.SEXOTARIFA)||' - '||TO_CHAR(:NEW.RIESGOTARIFA)||' - '||TO_CHAR(:NEW.SUMAASEGTARIFA)||' - '||
                TO_CHAR(:NEW.PRIMATARIFA)||' - '||TO_CHAR(:NEW.TASATARIFA)||' - '||TO_CHAR(:NEW.TASANIVELADA)||' - '||TO_CHAR(:NEW.IDTARIFA)||' - '||TO_CHAR(:NEW.PORCGTOADMIN)||' - '||TO_CHAR(:NEW.HABITOTARIFA);
    
      vl_Primary := 'RIESGOTARIFA: '||:NEW.RIESGOTARIFA || ' SEXOTARIFA: '||:NEW.SEXOTARIFA || ' EDADINITARIFA: '||:NEW.EDADINITARIFA || ' EDADFINTARIFA: '||:NEW.EDADFINTARIFA || ' CODCOBERT: '||:NEW.CODCOBERT || 
                ' PLANCOB: '|| :NEW.PLANCOB|| ' IDTIPOSEG: '||:NEW.IDTIPOSEG || ' CODEMPRESA: '||:NEW.CODEMPRESA || ' CODCIA: '||:NEW.CODCIA || ' HABITOTARIFA: '||:NEW.HABITOTARIFA || ' SUMAASEGTARIFA: '||:NEW.SUMAASEGTARIFA || ' IDTARIFA: '||:NEW.IDTARIFA;
    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;
  
  IF UPDATING THEN 

    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.CODCOBERT <> :OLD.CODCOBERT THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.EDADINITARIFA <> :OLD.EDADINITARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'EDADINITARIFA', TO_CHAR(:OLD.EDADINITARIFA), TO_CHAR(:NEW.EDADINITARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.EDADFINTARIFA <> :OLD.EDADFINTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'EDADFINTARIFA', TO_CHAR(:OLD.EDADFINTARIFA), TO_CHAR(:NEW.EDADFINTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.SEXOTARIFA <> :OLD.SEXOTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SEXOTARIFA', TO_CHAR(:OLD.SEXOTARIFA), TO_CHAR(:NEW.SEXOTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.RIESGOTARIFA <> :OLD.RIESGOTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'RIESGOTARIFA', TO_CHAR(:OLD.RIESGOTARIFA), TO_CHAR(:NEW.RIESGOTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.SUMAASEGTARIFA <> :OLD.SUMAASEGTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SUMAASEGTARIFA', TO_CHAR(:OLD.SUMAASEGTARIFA), TO_CHAR(:NEW.SUMAASEGTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.PRIMATARIFA <> :OLD.PRIMATARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PRIMATARIFA', TO_CHAR(:OLD.PRIMATARIFA), TO_CHAR(:NEW.PRIMATARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF NVL(:NEW.TASATARIFA,-20000) <> NVL(:OLD.TASATARIFA,-20000) THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'TASATARIFA', TO_CHAR(:OLD.TASATARIFA), TO_CHAR(:NEW.TASATARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF NVL(:NEW.TASANIVELADA,-20000) <> NVL(:OLD.TASANIVELADA,-20000) THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'TASANIVELADA', TO_CHAR(:OLD.TASANIVELADA), TO_CHAR(:NEW.TASANIVELADA), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.IDTARIFA <> :OLD.IDTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE',vl_Primary);
    END IF;
    IF NVL(:NEW.PORCGTOADMIN,-20000) <> NVL(:OLD.PORCGTOADMIN,-20000) THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PORCGTOADMIN', TO_CHAR(:OLD.PORCGTOADMIN), TO_CHAR(:NEW.PORCGTOADMIN), 'UPDATE',vl_Primary);
    END IF;
    IF :NEW.HABITOTARIFA <> :OLD.HABITOTARIFA THEN
      vl_Primary := 'RIESGOTARIFA: '||:OLD.RIESGOTARIFA || ' SEXOTARIFA: '||:OLD.SEXOTARIFA || ' EDADINITARIFA: '||:OLD.EDADINITARIFA || ' EDADFINTARIFA: '||:OLD.EDADFINTARIFA || ' CODCOBERT: '||:OLD.CODCOBERT || 
                ' PLANCOB: '|| :OLD.PLANCOB|| ' IDTIPOSEG: '||:OLD.IDTIPOSEG || ' CODEMPRESA: '||:OLD.CODEMPRESA || ' CODCIA: '||:OLD.CODCIA || ' HABITOTARIFA: '||:OLD.HABITOTARIFA || ' SUMAASEGTARIFA: '||:OLD.SUMAASEGTARIFA || ' IDTARIFA: '||:OLD.IDTARIFA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'HABITOTARIFA', TO_CHAR(:OLD.HABITOTARIFA), TO_CHAR(:NEW.HABITOTARIFA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TARIFA_SEXO_EDAD_RIESGO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TARIFA_SEXO_EDAD_RIESGO FOR SICAS_OC.TRG_TARIFA_SEXO_EDAD_RIESGO;
