CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TARIFA_SEXO_EDAD_RIESGO
  BEFORE INSERT OR UPDATE OR DELETE ON TARIFA_SEXO_EDAD_RIESGO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TARIFA_SEXO_EDAD_RIESGO
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    PRIMARY KEY: UNICOS CAMPOS QUE NO SON PK "PRIMATARIFA" - "TASATARIFA" - "TASANIVELADA" - "PORCGTOADMIN" 
  */
  
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                TO_CHAR(:OLD.EDADINITARIFA)||' - '||TO_CHAR(:OLD.EDADFINTARIFA)||' - '||TO_CHAR(:OLD.SEXOTARIFA)||' - '||TO_CHAR(:OLD.RIESGOTARIFA)||' - '||TO_CHAR(:OLD.SUMAASEGTARIFA)||' - '||
                TO_CHAR(:OLD.PRIMATARIFA)||' - '||TO_CHAR(:OLD.TASATARIFA)||' - '||TO_CHAR(:OLD.TASANIVELADA)||' - '||TO_CHAR(:OLD.IDTARIFA)||' - '||TO_CHAR(:OLD.PORCGTOADMIN)||' - '||TO_CHAR(:OLD.HABITOTARIFA);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE');
  END IF;
  
  IF INSERTING THEN 
    vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                TO_CHAR(:NEW.EDADINITARIFA)||' - '||TO_CHAR(:NEW.EDADFINTARIFA)||' - '||TO_CHAR(:NEW.SEXOTARIFA)||' - '||TO_CHAR(:NEW.RIESGOTARIFA)||' - '||TO_CHAR(:NEW.SUMAASEGTARIFA)||' - '||
                TO_CHAR(:NEW.PRIMATARIFA)||' - '||TO_CHAR(:NEW.TASATARIFA)||' - '||TO_CHAR(:NEW.TASANIVELADA)||' - '||TO_CHAR(:NEW.IDTARIFA)||' - '||TO_CHAR(:NEW.PORCGTOADMIN)||' - '||TO_CHAR(:NEW.HABITOTARIFA);

    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT');
  END IF;
  
  IF UPDATING THEN 
  
    IF :NEW.CODCIA <> :OLD.CODCIA THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE');
    END IF;
    IF :NEW.CODEMPRESA <> :OLD.CODEMPRESA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE');
    END IF;
    IF :NEW.IDTIPOSEG <> :OLD.IDTIPOSEG THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE');
    END IF;
    IF :NEW.PLANCOB <> :OLD.PLANCOB THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE');
    END IF;
    IF :NEW.CODCOBERT <> :OLD.CODCOBERT THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE');
    END IF;
    IF :NEW.EDADINITARIFA <> :OLD.EDADINITARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'EDADINITARIFA', TO_CHAR(:OLD.EDADINITARIFA), TO_CHAR(:NEW.EDADINITARIFA), 'UPDATE');
    END IF;
    IF :NEW.EDADFINTARIFA <> :OLD.EDADFINTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'EDADFINTARIFA', TO_CHAR(:OLD.EDADFINTARIFA), TO_CHAR(:NEW.EDADFINTARIFA), 'UPDATE');
    END IF;
    IF :NEW.SEXOTARIFA <> :OLD.SEXOTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SEXOTARIFA', TO_CHAR(:OLD.SEXOTARIFA), TO_CHAR(:NEW.SEXOTARIFA), 'UPDATE');
    END IF;
    IF :NEW.RIESGOTARIFA <> :OLD.RIESGOTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'RIESGOTARIFA', TO_CHAR(:OLD.RIESGOTARIFA), TO_CHAR(:NEW.RIESGOTARIFA), 'UPDATE');
    END IF;
    IF :NEW.SUMAASEGTARIFA <> :OLD.SUMAASEGTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'SUMAASEGTARIFA', TO_CHAR(:OLD.SUMAASEGTARIFA), TO_CHAR(:NEW.SUMAASEGTARIFA), 'UPDATE');
    END IF;
    IF :NEW.PRIMATARIFA <> :OLD.PRIMATARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PRIMATARIFA', TO_CHAR(:OLD.PRIMATARIFA), TO_CHAR(:NEW.PRIMATARIFA), 'UPDATE');
    END IF;
    IF :NEW.TASATARIFA <> :OLD.TASATARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'TASATARIFA', TO_CHAR(:OLD.TASATARIFA), TO_CHAR(:NEW.TASATARIFA), 'UPDATE');
    END IF;
    IF :NEW.TASANIVELADA <> :OLD.TASANIVELADA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'TASANIVELADA', TO_CHAR(:OLD.TASANIVELADA), TO_CHAR(:NEW.TASANIVELADA), 'UPDATE');
    END IF;
    IF :NEW.IDTARIFA <> :OLD.IDTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'IDTARIFA', TO_CHAR(:OLD.IDTARIFA), TO_CHAR(:NEW.IDTARIFA), 'UPDATE');
    END IF;
    IF :NEW.PORCGTOADMIN <> :OLD.PORCGTOADMIN THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'PORCGTOADMIN', TO_CHAR(:OLD.PORCGTOADMIN), TO_CHAR(:NEW.PORCGTOADMIN), 'UPDATE');
    END IF;
    IF :NEW.HABITOTARIFA <> :OLD.HABITOTARIFA THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'TARIFA_SEXO_EDAD_RIESGO', 'HABITOTARIFA', TO_CHAR(:OLD.HABITOTARIFA), TO_CHAR(:NEW.HABITOTARIFA), 'UPDATE');
    END IF;
  END IF;    
  
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TARIFA_SEXO_EDAD_RIESGO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TARIFA_SEXO_EDAD_RIESGO FOR SICAS_OC.TRG_TARIFA_SEXO_EDAD_RIESGO;
