CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_ASISTENCIAS_PLANCOB
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_ASISTENCIAS_PLANCOB
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_ASISTENCIAS_PLANCOB
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODASISTENCIA)||' - '||
                  TO_CHAR(:OLD.INDASISTOBLIG)||' - '||TO_CHAR(:OLD.STSPLANCOBASIST)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODASISTENCIA)||' - '||
                  TO_CHAR(:NEW.INDASISTOBLIG)||' - '||TO_CHAR(:NEW.STSPLANCOBASIST)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' IDTIPOSEG: '||:NEW.IDTIPOSEG||' PLANCOB: '||:NEW.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODASISTENCIA <> :OLD.CODASISTENCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'CODASISTENCIA', TO_CHAR(:OLD.CODASISTENCIA), TO_CHAR(:NEW.CODASISTENCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDASISTOBLIG,-20000) <> NVL(:OLD.INDASISTOBLIG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'INDASISTOBLIG', TO_CHAR(:OLD.INDASISTOBLIG), TO_CHAR(:NEW.INDASISTOBLIG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STSPLANCOBASIST,-20000) <> NVL(:OLD.STSPLANCOBASIST,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'STSPLANCOBASIST', TO_CHAR(:OLD.STSPLANCOBASIST), TO_CHAR(:NEW.STSPLANCOBASIST), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECSTS,SYSDATE) <> NVL(:OLD.FECSTS,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_ASISTENCIAS_PLANCOB', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
    
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_ASISTENCIAS_PLANCOB, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_ASISTENCIAS_PLANCOB FOR SICAS_OC.TRG_CONFIG_ASISTENCIAS_PLANCOB;
