CREATE OR REPLACE TRIGGER SICAS_OC.TRG_MEDIOS_DE_PAGO
  BEFORE INSERT OR UPDATE OR DELETE ON MEDIOS_DE_PAGO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA MEDIOS_DE_PAGO
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.IDFORMAPAGO)||' - '||TO_CHAR(:OLD.INDMEDIOPRINCIPAL)||' - '||TO_CHAR(:OLD.CODFORMAPAGO)||' - '||
                  TO_CHAR(:OLD.CODENTIDADFINAN)||' - '||TO_CHAR(:OLD.NUMCUENTABANCARIA)||' - '||TO_CHAR(:OLD.NUMCUENTACLABE)||' - '||TO_CHAR(:OLD.NUMTARJETA)||' - '||TO_CHAR(:OLD.FECHAVENCTARJETA)||' - '||TO_CHAR(:OLD.ABA_SWIFT)||' - '||
                  TO_CHAR(:OLD.NOMBREBANCOINTERMEDIARIO)||' - '||TO_CHAR(:OLD.CUENTABANCOINTERMEDIARIO);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.IDFORMAPAGO)||' - '||TO_CHAR(:NEW.INDMEDIOPRINCIPAL)||' - '||TO_CHAR(:NEW.CODFORMAPAGO)||' - '||
                  TO_CHAR(:NEW.CODENTIDADFINAN)||' - '||TO_CHAR(:NEW.NUMCUENTABANCARIA)||' - '||TO_CHAR(:NEW.NUMCUENTACLABE)||' - '||TO_CHAR(:NEW.NUMTARJETA)||' - '||TO_CHAR(:NEW.FECHAVENCTARJETA)||' - '||TO_CHAR(:NEW.ABA_SWIFT)||' - '||
                  TO_CHAR(:NEW.NOMBREBANCOINTERMEDIARIO)||' - '||TO_CHAR(:NEW.CUENTABANCOINTERMEDIARIO);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:NEW.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDFORMAPAGO <> :OLD.IDFORMAPAGO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'IDFORMAPAGO', TO_CHAR(:OLD.IDFORMAPAGO), TO_CHAR(:NEW.IDFORMAPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDMEDIOPRINCIPAL <> :OLD.INDMEDIOPRINCIPAL) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'INDMEDIOPRINCIPAL', TO_CHAR(:OLD.INDMEDIOPRINCIPAL), TO_CHAR(:NEW.INDMEDIOPRINCIPAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODFORMAPAGO <> :OLD.CODFORMAPAGO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'CODFORMAPAGO', TO_CHAR(:OLD.CODFORMAPAGO), TO_CHAR(:NEW.CODFORMAPAGO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODENTIDADFINAN,-20000) <> NVL(:OLD.CODENTIDADFINAN,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'CODENTIDADFINAN', TO_CHAR(:OLD.CODENTIDADFINAN), TO_CHAR(:NEW.CODENTIDADFINAN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMCUENTABANCARIA,-20000) <> NVL(:OLD.NUMCUENTABANCARIA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'NUMCUENTABANCARIA', TO_CHAR(:OLD.NUMCUENTABANCARIA), TO_CHAR(:NEW.NUMCUENTABANCARIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMCUENTACLABE,-20000) <> NVL(:OLD.NUMCUENTACLABE,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'NUMCUENTACLABE', TO_CHAR(:OLD.NUMCUENTACLABE), TO_CHAR(:NEW.NUMCUENTACLABE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMTARJETA,-20000) <> NVL(:OLD.NUMTARJETA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'NUMTARJETA', TO_CHAR(:OLD.NUMTARJETA), TO_CHAR(:NEW.NUMTARJETA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECHAVENCTARJETA,SYSDATE) <> NVL(:OLD.FECHAVENCTARJETA,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'FECHAVENCTARJETA', TO_CHAR(:OLD.FECHAVENCTARJETA), TO_CHAR(:NEW.FECHAVENCTARJETA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ABA_SWIFT,-20000) <> NVL(:OLD.ABA_SWIFT,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'ABA_SWIFT', TO_CHAR(:OLD.ABA_SWIFT), TO_CHAR(:NEW.ABA_SWIFT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMBREBANCOINTERMEDIARIO,-20000) <> NVL(:OLD.NOMBREBANCOINTERMEDIARIO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'NOMBREBANCOINTERMEDIARIO', TO_CHAR(:OLD.NOMBREBANCOINTERMEDIARIO), TO_CHAR(:NEW.NOMBREBANCOINTERMEDIARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CUENTABANCOINTERMEDIARIO,-20000) <> NVL(:OLD.CUENTABANCOINTERMEDIARIO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'CUENTABANCOINTERMEDIARIO', TO_CHAR(:OLD.CUENTABANCOINTERMEDIARIO), TO_CHAR(:NEW.CUENTABANCOINTERMEDIARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ABA_SWIFT_INTERMEDIARIO,-20000) <> NVL(:OLD.ABA_SWIFT_INTERMEDIARIO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' IDFORMAPAGO: '||:OLD.IDFORMAPAGO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'MEDIOS_DE_PAGO', 'ABA_SWIFT_INTERMEDIARIO', TO_CHAR(:OLD.ABA_SWIFT_INTERMEDIARIO), TO_CHAR(:NEW.ABA_SWIFT_INTERMEDIARIO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de MEDIOS_DE_PAGO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_MEDIOS_DE_PAGO FOR SICAS_OC.TRG_MEDIOS_DE_PAGO;
