CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CATALOGO_CONCEPTOS_RANGOS
  BEFORE INSERT OR UPDATE OR DELETE ON CATALOGO_CONCEPTOS_RANGOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CATALOGO_CONCEPTOS_RANGOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCONCEPTO)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODTIPORANGO)||' - '||TO_CHAR(:OLD.CODMONEDA)||' - '||
      TO_CHAR(:OLD.RANGOINICIAL)||' - '||TO_CHAR(:OLD.RANGOFINAL)||' - '||TO_CHAR(:OLD.INDTIPOCONCEPTO)||' - '||TO_CHAR(:OLD.PORCCONCEPTO)||' - '||TO_CHAR(:OLD.MONTOCONCEPTO)||' - '||TO_CHAR(:OLD.RUTINACALCULO)||' - '||
      TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO)||' - '||TO_CHAR(:OLD.ID_AÑO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCONCEPTO)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODTIPORANGO)||' - '||TO_CHAR(:NEW.CODMONEDA)||' - '||
                  TO_CHAR(:NEW.RANGOINICIAL)||' - '||TO_CHAR(:NEW.RANGOFINAL)||' - '||TO_CHAR(:NEW.INDTIPOCONCEPTO)||' - '||TO_CHAR(:NEW.PORCCONCEPTO)||' - '||TO_CHAR(:NEW.MONTOCONCEPTO)||' - '||TO_CHAR(:NEW.RUTINACALCULO)||' - '||
                  TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO)||' - '||TO_CHAR(:NEW.ID_AÑO);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA ||' CODCONCEPTO: '||:NEW.CODCONCEPTO||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCONCEPTO <> :OLD.CODCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODCONCEPTO', TO_CHAR(:OLD.CODCONCEPTO), TO_CHAR(:NEW.CODCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODTIPORANGO <> :OLD.CODTIPORANGO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODTIPORANGO', TO_CHAR(:OLD.CODTIPORANGO), TO_CHAR(:NEW.CODTIPORANGO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODMONEDA <> :OLD.CODMONEDA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODMONEDA', TO_CHAR(:OLD.CODMONEDA), TO_CHAR(:NEW.CODMONEDA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.RANGOINICIAL <> :OLD.RANGOINICIAL) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'RANGOINICIAL', TO_CHAR(:OLD.RANGOINICIAL), TO_CHAR(:NEW.RANGOINICIAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.RANGOFINAL <> :OLD.RANGOFINAL) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'RANGOFINAL', TO_CHAR(:OLD.RANGOFINAL), TO_CHAR(:NEW.RANGOFINAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDTIPOCONCEPTO <> :OLD.INDTIPOCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'INDTIPOCONCEPTO', TO_CHAR(:OLD.INDTIPOCONCEPTO), TO_CHAR(:NEW.INDTIPOCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCCONCEPTO,-20000) <> NVL(:OLD.PORCCONCEPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'PORCCONCEPTO', TO_CHAR(:OLD.PORCCONCEPTO), TO_CHAR(:NEW.PORCCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTOCONCEPTO,-20000) <> NVL(:OLD.MONTOCONCEPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'MONTOCONCEPTO', TO_CHAR(:OLD.MONTOCONCEPTO), TO_CHAR(:NEW.MONTOCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.RUTINACALCULO,-20000) <> NVL(:OLD.RUTINACALCULO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'RUTINACALCULO', TO_CHAR(:OLD.RUTINACALCULO), TO_CHAR(:NEW.RUTINACALCULO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ID_AÑO <> :OLD.ID_AÑO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA ||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_CONCEPTOS_RANGOS', 'ID_AÑO', TO_CHAR(:OLD.ID_AÑO), TO_CHAR(:NEW.ID_AÑO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CATALOGO_CONCEPTOS_RANGOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CATALOGO_CONCEPTOS_RANGOS FOR SICAS_OC.TRG_CATALOGO_CONCEPTOS_RANGOS;
