CREATE OR REPLACE TRIGGER TRG_D_DET_FACT_ELECT_CONF_DOCT
BEFORE DELETE
ON DETALLE_FACT_ELECT_CONF_DOCTO
FOR EACH ROW
DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := :OLD.CODCIA||' - '||TO_CHAR(:OLD.IDIDENTIFICADOR)||' - '||:OLD.CODIDENTIFICADOR||' - '||:OLD.CODATRIBUTO||' - '||TO_CHAR(:OLD.ORDENATRIB)||' - '||:OLD.CONDICIONATRIBUTO||' - '||:OLD.TIPOVALORATRIBUTO||' - '||:OLD.VALORATRIBUTO||' - '||:OLD.CONSULTA||' - '||:OLD.INDENVIACIA||' - '||:OLD.CODRUTINACALC;
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');

END TRG_D_DET_FACT_ELECT_CONF_DOCT;