CREATE OR REPLACE TRIGGER SICAS_OC.TRG_NIVEL_PLAN_COBERTURA
  BEFORE INSERT OR UPDATE OR DELETE ON NIVEL_PLAN_COBERTURA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA NIVEL_PLAN_COBERTURA
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODNIVEL)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.COMAGENIVEL)||' - '||TO_CHAR(:OLD.ORIGEN);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' PLANCOB: '||:OLD.PLANCOB ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODNIVEL)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.COMAGENIVEL)||' - '||TO_CHAR(:NEW.ORIGEN);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'NIVEL_PLAN_COBERTURA', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODNIVEL <> :OLD.CODNIVEL) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'CODNIVEL', TO_CHAR(:OLD.CODNIVEL), TO_CHAR(:NEW.CODNIVEL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COMAGENIVEL,-20000) <> NVL(:OLD.COMAGENIVEL,-20000)) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'COMAGENIVEL', TO_CHAR(:OLD.COMAGENIVEL), TO_CHAR(:NEW.COMAGENIVEL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORIGEN,-20000) <> NVL(:OLD.ORIGEN,-20000)) THEN
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' PLANCOB: '||:NEW.PLANCOB ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'NIVEL_PLAN_COBERTURA', 'ORIGEN', TO_CHAR(:OLD.ORIGEN), TO_CHAR(:NEW.ORIGEN), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de NIVEL_PLAN_COBERTURA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_NIVEL_PLAN_COBERTURA FOR SICAS_OC.TRG_NIVEL_PLAN_COBERTURA;
