CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PLAN_COBERTURAS
  BEFORE INSERT OR UPDATE OR DELETE ON PLAN_COBERTURAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PLAN_COBERTURAS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    INDICE UNICO: IDTIPOSEG - CODEMPRESA - CODCIA - PLANCOB
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.DESC_PLAN)||' - '||
                  TO_CHAR(:OLD.ULTMODPLAN)||' - '||TO_CHAR(:OLD.ESTADO_PLAN)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.TIPPLANCOB)||' - '||TO_CHAR(:OLD.CODMONEDA)||' - '||
                  TO_CHAR(:OLD.CODTIPOPLAN)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.DIASRETROACTIVOS)||' - '||TO_CHAR(:OLD.MODALIDAD)||' - '||TO_CHAR(:OLD.PLANPOLIZA)||' - '||
                  TO_CHAR(:OLD.INDISPUTABILIDAD)||' - '||TO_CHAR(:OLD.CODTEMPORALIDAD)||' - '||TO_CHAR(:OLD.INDAPLICASAMI)||' - '||TO_CHAR(:OLD.COMMINIMA)||' - '||TO_CHAR(:OLD.COMMAXIMA)||' - '||
                  TO_CHAR(:OLD.PORCGTOADMIN)||' - '||TO_CHAR(:OLD.PORCGTOADQUI)||' - '||TO_CHAR(:OLD.PORCUTILIDAD)||' - '||TO_CHAR(:OLD.DIASRETROREN)||' - '||TO_CHAR(:OLD.DURACIONPLAN)||' - '||
                  TO_CHAR(:OLD.PORCDESCUENTO)||' - '||TO_CHAR(:OLD.PORCEXTRAPRIMA)||' - '||TO_CHAR(:OLD.MONTOEXTRAPRIMA)||' - '||TO_CHAR(:OLD.FACTORAJUSTE)||' - '||TO_CHAR(:OLD.MONTODEDUCIBLE)||' - '||
                  TO_CHAR(:OLD.FACTFORMULADEDUC)||' - '||TO_CHAR(:OLD.PREFIJOPOL)||' - '||TO_CHAR(:OLD.DIASEXTRASCANCEL)||' - '||TO_CHAR(:OLD.DIASSINPAGOFONDOS)||' - '||TO_CHAR(:OLD.ID_LARGO_PLAZO)||' - '||TO_CHAR(:OLD.SUMA_ASEG_MAX);
      
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE');
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.DESC_PLAN)||' - '||
                  TO_CHAR(:NEW.ULTMODPLAN)||' - '||TO_CHAR(:NEW.ESTADO_PLAN)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.TIPPLANCOB)||' - '||TO_CHAR(:NEW.CODMONEDA)||' - '||
                  TO_CHAR(:NEW.CODTIPOPLAN)||' - '||TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.DIASRETROACTIVOS)||' - '||TO_CHAR(:NEW.MODALIDAD)||' - '||TO_CHAR(:NEW.PLANPOLIZA)||' - '||
                  TO_CHAR(:NEW.INDISPUTABILIDAD)||' - '||TO_CHAR(:NEW.CODTEMPORALIDAD)||' - '||TO_CHAR(:NEW.INDAPLICASAMI)||' - '||TO_CHAR(:NEW.COMMINIMA)||' - '||TO_CHAR(:NEW.COMMAXIMA)||' - '||
                  TO_CHAR(:NEW.PORCGTOADMIN)||' - '||TO_CHAR(:NEW.PORCGTOADQUI)||' - '||TO_CHAR(:NEW.PORCUTILIDAD)||' - '||TO_CHAR(:NEW.DIASRETROREN)||' - '||TO_CHAR(:NEW.DURACIONPLAN)||' - '||
                  TO_CHAR(:NEW.PORCDESCUENTO)||' - '||TO_CHAR(:NEW.PORCEXTRAPRIMA)||' - '||TO_CHAR(:NEW.MONTOEXTRAPRIMA)||' - '||TO_CHAR(:NEW.FACTORAJUSTE)||' - '||TO_CHAR(:NEW.MONTODEDUCIBLE)||' - '||
                  TO_CHAR(:NEW.FACTFORMULADEDUC)||' - '||TO_CHAR(:NEW.PREFIJOPOL)||' - '||TO_CHAR(:NEW.DIASEXTRASCANCEL)||' - '||TO_CHAR(:NEW.DIASSINPAGOFONDOS)||' - '||TO_CHAR(:NEW.ID_LARGO_PLAZO)||' - '||TO_CHAR(:NEW.SUMA_ASEG_MAX);

    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'PLAN_COBERTURAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT');
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'IDTIPOSEG',  TO_CHAR(:OLD.IDTIPOSEG),  TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE');
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODEMPRESA',  TO_CHAR(:OLD.CODEMPRESA),  TO_CHAR(:NEW.CODEMPRESA), 'UPDATE');
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE');
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE');
    END IF;
    IF (:NEW.DESC_PLAN <> :OLD.DESC_PLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DESC_PLAN',  TO_CHAR(:OLD.DESC_PLAN),  TO_CHAR(:NEW.DESC_PLAN), 'UPDATE');
    END IF;
    IF (:NEW.ULTMODPLAN <> :OLD.ULTMODPLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ULTMODPLAN',  TO_CHAR(:OLD.ULTMODPLAN),  TO_CHAR(:NEW.ULTMODPLAN), 'UPDATE');
    END IF;
    IF (:NEW.ESTADO_PLAN <> :OLD.ESTADO_PLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ESTADO_PLAN', TO_CHAR(:OLD.ESTADO_PLAN), TO_CHAR(:NEW.ESTADO_PLAN), 'UPDATE');
    END IF;
    IF (:NEW.CODUSUARIO <> :OLD.CODUSUARIO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE');
    END IF;
    IF (:NEW.TIPPLANCOB <> :OLD.TIPPLANCOB) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'TIPPLANCOB', TO_CHAR(:OLD.TIPPLANCOB), TO_CHAR(:NEW.TIPPLANCOB), 'UPDATE');
    END IF;
    IF (:NEW.CODMONEDA <> :OLD.CODMONEDA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODMONEDA', TO_CHAR(:OLD.CODMONEDA), TO_CHAR(:NEW.CODMONEDA), 'UPDATE');
    END IF;
    IF (:NEW.CODTIPOPLAN <> :OLD.CODTIPOPLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE');
    END IF;
    IF (:NEW.COD_AGENTE <> :OLD.COD_AGENTE) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE');
    END IF;
    IF (:NEW.DIASRETROACTIVOS <> :OLD.DIASRETROACTIVOS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASRETROACTIVOS', TO_CHAR(:OLD.DIASRETROACTIVOS), TO_CHAR(:NEW.DIASRETROACTIVOS), 'UPDATE');
    END IF;
    IF (:NEW.MODALIDAD <> :OLD.MODALIDAD) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MODALIDAD', TO_CHAR(:OLD.MODALIDAD), TO_CHAR(:NEW.MODALIDAD), 'UPDATE');
    END IF;
    IF (:NEW.PLANPOLIZA <> :OLD.PLANPOLIZA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PLANPOLIZA', TO_CHAR(:OLD.PLANPOLIZA), TO_CHAR(:NEW.PLANPOLIZA), 'UPDATE');
    END IF;
    IF (:NEW.INDISPUTABILIDAD <> :OLD.INDISPUTABILIDAD) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'INDISPUTABILIDAD', TO_CHAR(:OLD.INDISPUTABILIDAD), TO_CHAR(:NEW.INDISPUTABILIDAD), 'UPDATE');
    END IF;
    IF (:NEW.CODTEMPORALIDAD <> :OLD.CODTEMPORALIDAD) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'CODTEMPORALIDAD', TO_CHAR(:OLD.CODTEMPORALIDAD), TO_CHAR(:NEW.CODTEMPORALIDAD), 'UPDATE');
    END IF;
    IF (:NEW.INDAPLICASAMI <> :OLD.INDAPLICASAMI) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'INDAPLICASAMI', TO_CHAR(:OLD.INDAPLICASAMI), TO_CHAR(:NEW.INDAPLICASAMI), 'UPDATE');
    END IF;
    IF (:NEW.COMMINIMA <> :OLD.COMMINIMA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COMMINIMA', TO_CHAR(:OLD.COMMINIMA), TO_CHAR(:NEW.COMMINIMA), 'UPDATE');
    END IF;
    IF (:NEW.COMMAXIMA <> :OLD.COMMAXIMA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'COMMAXIMA', TO_CHAR(:OLD.COMMAXIMA), TO_CHAR(:NEW.COMMAXIMA), 'UPDATE');
    END IF;
    IF (:NEW.PORCGTOADMIN <> :OLD.PORCGTOADMIN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCGTOADMIN', TO_CHAR(:OLD.PORCGTOADMIN), TO_CHAR(:NEW.PORCGTOADMIN), 'UPDATE');
    END IF;
    IF (:NEW.PORCGTOADQUI <> :OLD.PORCGTOADQUI) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCGTOADQUI', TO_CHAR(:OLD.PORCGTOADQUI), TO_CHAR(:NEW.PORCGTOADQUI), 'UPDATE');
    END IF;
    IF (:NEW.PORCUTILIDAD <> :OLD.PORCUTILIDAD) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCUTILIDAD', TO_CHAR(:OLD.PORCUTILIDAD), TO_CHAR(:NEW.PORCUTILIDAD), 'UPDATE');
    END IF;
    IF (:NEW.DIASRETROREN <> :OLD.DIASRETROREN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASRETROREN', TO_CHAR(:OLD.DIASRETROREN), TO_CHAR(:NEW.DIASRETROREN), 'UPDATE');
    END IF;
    IF (:NEW.DURACIONPLAN <> :OLD.DURACIONPLAN) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DURACIONPLAN', TO_CHAR(:OLD.DURACIONPLAN), TO_CHAR(:NEW.DURACIONPLAN), 'UPDATE');
    END IF;
    IF (:NEW.PORCDESCUENTO <> :OLD.PORCDESCUENTO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCDESCUENTO', TO_CHAR(:OLD.PORCDESCUENTO), TO_CHAR(:NEW.PORCDESCUENTO), 'UPDATE');
    END IF;
    IF (:NEW.PORCEXTRAPRIMA <> :OLD.PORCEXTRAPRIMA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PORCEXTRAPRIMA', TO_CHAR(:OLD.PORCEXTRAPRIMA), TO_CHAR(:NEW.PORCEXTRAPRIMA), 'UPDATE');
    END IF;
    IF (:NEW.MONTOEXTRAPRIMA <> :OLD.MONTOEXTRAPRIMA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MONTOEXTRAPRIMA', TO_CHAR(:OLD.MONTOEXTRAPRIMA), TO_CHAR(:NEW.MONTOEXTRAPRIMA), 'UPDATE');
    END IF;
    IF (:NEW.FACTORAJUSTE <> :OLD.FACTORAJUSTE) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'FACTORAJUSTE', TO_CHAR(:OLD.FACTORAJUSTE), TO_CHAR(:NEW.FACTORAJUSTE), 'UPDATE');
    END IF;
    IF (:NEW.MONTODEDUCIBLE <> :OLD.MONTODEDUCIBLE) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'MONTODEDUCIBLE', TO_CHAR(:OLD.MONTODEDUCIBLE), TO_CHAR(:NEW.MONTODEDUCIBLE), 'UPDATE');
    END IF;
    IF (:NEW.FACTFORMULADEDUC <> :OLD.FACTFORMULADEDUC) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'FACTFORMULADEDUC', TO_CHAR(:OLD.FACTFORMULADEDUC), TO_CHAR(:NEW.FACTFORMULADEDUC), 'UPDATE');
    END IF;
    IF (:NEW.PREFIJOPOL <> :OLD.PREFIJOPOL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'PREFIJOPOL', TO_CHAR(:OLD.PREFIJOPOL), TO_CHAR(:NEW.PREFIJOPOL), 'UPDATE');
    END IF;
    IF (:NEW.DIASEXTRASCANCEL <> :OLD.DIASEXTRASCANCEL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASEXTRASCANCEL', TO_CHAR(:OLD.DIASEXTRASCANCEL), TO_CHAR(:NEW.DIASEXTRASCANCEL), 'UPDATE');
    END IF;
    IF (:NEW.DIASSINPAGOFONDOS <> :OLD.DIASSINPAGOFONDOS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'DIASSINPAGOFONDOS', TO_CHAR(:OLD.DIASSINPAGOFONDOS), TO_CHAR(:NEW.DIASSINPAGOFONDOS), 'UPDATE');
    END IF;
    IF (:NEW.ID_LARGO_PLAZO <> :OLD.ID_LARGO_PLAZO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'ID_LARGO_PLAZO', TO_CHAR(:OLD.ID_LARGO_PLAZO), TO_CHAR(:NEW.ID_LARGO_PLAZO), 'UPDATE');
    END IF;
    IF (:NEW.SUMA_ASEG_MAX <> :OLD.SUMA_ASEG_MAX) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'PLAN_COBERTURAS', 'SUMA_ASEG_MAX', TO_CHAR(:OLD.SUMA_ASEG_MAX), TO_CHAR(:NEW.SUMA_ASEG_MAX), 'UPDATE');
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PLAN_COBERTURAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PLAN_COBERTURAS FOR SICAS_OC.TRG_PLAN_COBERTURAS;
