CREATE OR REPLACE TRIGGER SICAS_OC.TRG_AGENTES_TIPOS_SEGUROS
  BEFORE INSERT OR UPDATE OR DELETE ON AGENTES_TIPOS_SEGUROS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA AGENTES_TIPOS_SEGUROS
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.PORC_COMISION)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.TIPO_COMISION);  
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.COD_AGENTE)||' - '||TO_CHAR(:NEW.PORC_COMISION)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.TIPO_COMISION);  
      vl_Primary := 'IDTIPOSEG: '||:NEW.IDTIPOSEG||' CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' COD_AGENTE: '||:NEW.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.COD_AGENTE <> :OLD.COD_AGENTE) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'COD_AGENTE', TO_CHAR(:OLD.COD_AGENTE), TO_CHAR(:NEW.COD_AGENTE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORC_COMISION,-20000) <> NVL(:OLD.PORC_COMISION,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'PORC_COMISION', TO_CHAR(:OLD.PORC_COMISION), TO_CHAR(:NEW.PORC_COMISION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_COMISION,-20000) <> NVL(:OLD.TIPO_COMISION,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' COD_AGENTE: '||:OLD.COD_AGENTE;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_TIPOS_SEGUROS', 'TIPO_COMISION', TO_CHAR(:OLD.TIPO_COMISION), TO_CHAR(:NEW.TIPO_COMISION), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de AGENTES_TIPOS_SEGUROS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_AGENTES_TIPOS_SEGUROS FOR SICAS_OC.TRG_AGENTES_TIPOS_SEGUROS;
