CREATE OR REPLACE TRIGGER SICAS_OC.TRG_FACTURAS
  BEFORE UPDATE ON FACTURAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA FACTURAS
    FECHA CREACIÓN: 07/09/2026
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    INDICE UNICO: IDFACTURA 
  */

  IF UPDATING THEN 
    IF (:NEW.IDFACTURA <> :OLD.IDFACTURA) THEN
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDFACTURA',  TO_CHAR(:OLD.IDFACTURA),  TO_CHAR(:NEW.IDFACTURA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.IDPOLIZA <> :OLD.IDPOLIZA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDPOLIZA',  TO_CHAR(:OLD.IDPOLIZA),  TO_CHAR(:NEW.IDPOLIZA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.IDETPOL <> :OLD.IDETPOL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDETPOL', TO_CHAR(:OLD.IDETPOL), TO_CHAR(:NEW.IDETPOL), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.STSFACT <> :OLD.STSFACT) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'STSFACT', TO_CHAR(:OLD.STSFACT), TO_CHAR(:NEW.STSFACT), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.CODCLIENTE <> :OLD.CODCLIENTE) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'CODCLIENTE',  TO_CHAR(:OLD.CODCLIENTE),  TO_CHAR(:NEW.CODCLIENTE), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.MONTO_FACT_LOCAL <> :OLD.MONTO_FACT_LOCAL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'MONTO_FACT_LOCAL',  TO_CHAR(:OLD.MONTO_FACT_LOCAL),  TO_CHAR(:NEW.MONTO_FACT_LOCAL), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.MONTO_FACT_MONEDA <> :OLD.MONTO_FACT_MONEDA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'MONTO_FACT_MONEDA', TO_CHAR(:OLD.MONTO_FACT_MONEDA), TO_CHAR(:NEW.MONTO_FACT_MONEDA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.FECSTS = :OLD.FECSTS) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.CODUSUARIOENVFACT <> :OLD.CODUSUARIOENVFACT) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'CODUSUARIOENVFACT', TO_CHAR(:OLD.CODUSUARIOENVFACT), TO_CHAR(:NEW.CODUSUARIOENVFACT), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.FECANUL <> :OLD.FECANUL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'FECANUL', TO_CHAR(:OLD.FECANUL), TO_CHAR(:NEW.FECANUL), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.MOTIVANUL <> :OLD.MOTIVANUL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'MOTIVANUL', TO_CHAR(:OLD.MOTIVANUL), TO_CHAR(:NEW.MOTIVANUL), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.CODUSUARIOENVFACTANU <> :OLD.CODUSUARIOENVFACTANU) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'CODUSUARIOENVFACTANU', TO_CHAR(:OLD.CODUSUARIOENVFACTANU), TO_CHAR(:NEW.CODUSUARIOENVFACTANU), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.RECIBOPAGO <> :OLD.RECIBOPAGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'RECIBOPAGO', TO_CHAR(:OLD.RECIBOPAGO), TO_CHAR(:NEW.RECIBOPAGO), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.MTOCOMISI_LOCAL <> :OLD.MTOCOMISI_LOCAL) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'MTOCOMISI_LOCAL', TO_CHAR(:OLD.MTOCOMISI_LOCAL), TO_CHAR(:NEW.MTOCOMISI_LOCAL), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.MTOCOMISI_MONEDA <> :OLD.MTOCOMISI_MONEDA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'MTOCOMISI_MONEDA', TO_CHAR(:OLD.MTOCOMISI_MONEDA), TO_CHAR(:NEW.MTOCOMISI_MONEDA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.CODPLANPAGO <> :OLD.CODPLANPAGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'CODPLANPAGO', TO_CHAR(:OLD.CODPLANPAGO), TO_CHAR(:NEW.CODPLANPAGO), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.NUMCUOTA <> :OLD.NUMCUOTA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'NUMCUOTA', TO_CHAR(:OLD.NUMCUOTA), TO_CHAR(:NEW.NUMCUOTA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.SALDO_MONEDA <> :OLD.SALDO_MONEDA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'SALDO_MONEDA', TO_CHAR(:OLD.SALDO_MONEDA), TO_CHAR(:NEW.SALDO_MONEDA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.IDTRANSACCION <> :OLD.IDTRANSACCION) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDTRANSACCION', TO_CHAR(:OLD.IDTRANSACCION), TO_CHAR(:NEW.IDTRANSACCION), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.IDTRANSACCIONANU <> :OLD.IDTRANSACCIONANU) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDTRANSACCIONANU', TO_CHAR(:OLD.IDTRANSACCIONANU), TO_CHAR(:NEW.IDTRANSACCIONANU), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.FECPAGO <> :OLD.FECPAGO) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'FECPAGO', TO_CHAR(:OLD.FECPAGO), TO_CHAR(:NEW.FECPAGO), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.FECCONTABILIZADA <> :OLD.FECCONTABILIZADA) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'FECCONTABILIZADA', TO_CHAR(:OLD.FECCONTABILIZADA), TO_CHAR(:NEW.FECCONTABILIZADA), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.IDTRANSACCONTAB <> :OLD.IDTRANSACCONTAB) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'IDTRANSACCONTAB', TO_CHAR(:OLD.IDTRANSACCONTAB), TO_CHAR(:NEW.IDTRANSACCONTAB), 'UPDATE',:OLD.IDFACTURA);
    END IF;
    IF (:NEW.FOLIOFACTELEC <> :OLD.FOLIOFACTELEC) THEN
       OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'FACTURAS', 'FOLIOFACTELEC', TO_CHAR(:OLD.FOLIOFACTELEC), TO_CHAR(:NEW.FOLIOFACTELEC), 'UPDATE',:OLD.IDFACTURA);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de FACTURAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_FACTURAS FOR SICAS_OC.TRG_FACTURAS;
/