CREATE OR REPLACE TRIGGER SICAS_OC.TRG_SINIESTRO_PIPE
  BEFORE INSERT OR UPDATE OR DELETE ON SINIESTRO
  FOR EACH ROW 

DECLARE
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA SINIESTRO
    FECHA CREACIÓN: 21/01/2026
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    */

  IF INSERTING THEN 

      IF (INSTR(:NEW.NUMSINIREF, '|') > 0) THEN
        :NEW.NUMSINIREF := REPLACE(:NEW.NUMSINIREF,'|','');
      END IF;

      IF (INSTR(:NEW.EMPRESA_LABORA, '|') > 0) THEN
        :NEW.EMPRESA_LABORA := REPLACE(:NEW.EMPRESA_LABORA,'|','');
      END IF;

      IF (INSTR(:NEW.IDCREDITO, '|') > 0) THEN
        :NEW.IDCREDITO := REPLACE(:NEW.IDCREDITO,'|','');
      END IF;

      IF REGEXP_LIKE(:NEW.NOM_MEDICO_CERTIFICA, '[^a-zA-Z0-9 ]') THEN
        :NEW.NOM_MEDICO_CERTIFICA := REGEXP_REPLACE(:NEW.NOM_MEDICO_CERTIFICA, '[¿?!¡|@#$%&/()=\]', '');
      END IF;

      IF REGEXP_LIKE(:NEW.ID_CEDULA_MEDICA, '[^a-zA-Z0-9 ]') THEN
        :NEW.ID_CEDULA_MEDICA := REGEXP_REPLACE(:NEW.ID_CEDULA_MEDICA, '[¿?!¡|@#$%&/()=\]', '');
      END IF;
        
      IF REGEXP_LIKE(:NEW.DESC_SINIESTRO, '[^a-zA-Z0-9 ]') THEN
        :NEW.DESC_SINIESTRO := REGEXP_REPLACE(:NEW.DESC_SINIESTRO, '[|]', '');
      END IF;
      
      IF (INSTR(:NEW.DESC_SINIESTRO,CHR(13))>0) THEN
        :NEW.DESC_SINIESTRO := REPLACE(:NEW.DESC_SINIESTRO, CHR(13), ' ');
      END IF;
      
  END IF;

  IF UPDATING THEN 
    IF (:NEW.NUMSINIREF <> :OLD.NUMSINIREF) THEN
      IF (INSTR(:NEW.NUMSINIREF, '|') > 0) THEN
        :NEW.NUMSINIREF := REPLACE(:NEW.NUMSINIREF,'|','');
      END IF;
    END IF;

    IF (:NEW.EMPRESA_LABORA <> :OLD.EMPRESA_LABORA) THEN
      IF (INSTR(:NEW.EMPRESA_LABORA, '|') > 0) THEN
        :NEW.EMPRESA_LABORA := REPLACE(:NEW.EMPRESA_LABORA,'|','');
      END IF;
    END IF;

    IF (:NEW.IDCREDITO <> :OLD.IDCREDITO) THEN
      IF (INSTR(:NEW.IDCREDITO, '|') > 0) THEN
        :NEW.IDCREDITO := REPLACE(:NEW.IDCREDITO,'|','');
      END IF;
    END IF;

    IF ((:NEW.NOM_MEDICO_CERTIFICA <> :OLD.NOM_MEDICO_CERTIFICA)) THEN
      IF REGEXP_LIKE(:NEW.NOM_MEDICO_CERTIFICA, '[^a-zA-Z0-9 ]') THEN
        :NEW.NOM_MEDICO_CERTIFICA := REGEXP_REPLACE(:NEW.NOM_MEDICO_CERTIFICA, '[¡|@#$%&\!=/?¿]', '');
      END IF;
    END IF;

    IF (:NEW.ID_CEDULA_MEDICA <> :OLD.ID_CEDULA_MEDICA) THEN
      IF REGEXP_LIKE(:NEW.ID_CEDULA_MEDICA, '[^a-zA-Z0-9 ]') THEN
        :NEW.ID_CEDULA_MEDICA := REGEXP_REPLACE(:NEW.ID_CEDULA_MEDICA, '[¡|@#$%&\!=/?¿]', '');
      END IF;
    END IF;

    IF (:NEW.DESC_SINIESTRO <> :OLD.DESC_SINIESTRO) THEN
      IF REGEXP_LIKE(:NEW.DESC_SINIESTRO, '[^a-zA-Z0-9 ]') THEN
        :NEW.DESC_SINIESTRO := REGEXP_REPLACE(:NEW.DESC_SINIESTRO, '[|]', '');
      END IF;
    END IF;
    
    IF (:NEW.DESC_SINIESTRO <> :OLD.DESC_SINIESTRO) THEN
      IF (INSTR(:NEW.DESC_SINIESTRO, CHR(13)) > 0) THEN
        :NEW.DESC_SINIESTRO := REPLACE(:NEW.DESC_SINIESTRO,CHR(13),' ');
      END IF;
    END IF;

  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de SINIESTRO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_SINIESTRO_PIPE FOR SICAS_OC.TRG_SINIESTRO_PIPE;
