CREATE OR REPLACE TRIGGER SICAS_OC.TRG_COBERTURAS_DE_SEGUROS
  BEFORE INSERT OR UPDATE OR DELETE ON COBERTURAS_DE_SEGUROS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA COBERTURAS_DE_SEGUROS
    FECHA CREACIÓN: 05/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
    INDICE UNICO: IDTIPOSEG - PLANCOB - CODCOBERT - CODEMPRESA - CODCIA
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||
                  TO_CHAR(:OLD.DESCCOBERT)||' - '||TO_CHAR(:OLD.TIPOTASA)||' - '||TO_CHAR(:OLD.PORC_TASA)||' - '||TO_CHAR(:OLD.PRIMA_COBERT)||' - '||TO_CHAR(:OLD.STSCOBERTURA)||' - '||
                  TO_CHAR(:OLD.SUMAASEGURADA)||' - '||TO_CHAR(:OLD.COD_MONEDA)||' - '||TO_CHAR(:OLD.ACUMULAASUMA)||' - '||TO_CHAR(:OLD.INDBASICA)||' - '||TO_CHAR(:OLD.COBERTURA_BASICA)||' - '||
                  TO_CHAR(:OLD.CALCULA_PRORRATA)||' - '||TO_CHAR(:OLD.DEVUELVE_PRIMA)||' - '||TO_CHAR(:OLD.EDAD_MINIMA)||' - '||TO_CHAR(:OLD.EDAD_MAXIMA)||' - '||TO_CHAR(:OLD.EDAD_EXCLUSION)||' - '||
                  TO_CHAR(:OLD.NOMREP)||' - '||TO_CHAR(:OLD.CODCPTO)||' - '||TO_CHAR(:OLD.CODTARIFA)||' - '||TO_CHAR(:OLD.CLAVESESAS)||' - '||TO_CHAR(:OLD.CODRIESGOREA)||' - '||
                  TO_CHAR(:OLD.INDACUMULASUMAREA)||' - '||TO_CHAR(:OLD.INDACUMULAPRIMAREA)||' - '||TO_CHAR(:OLD.SUMAASEGMINIMA)||' - '||TO_CHAR(:OLD.SUMAASEGMAXIMA)||' - '||TO_CHAR(:OLD.SUMAASEGMAXINDIV)||' - '||
                  TO_CHAR(:OLD.INDPERDORGANICAS)||' - '||TO_CHAR(:OLD.INDMANEJAANTICIPOS)||' - '||TO_CHAR(:OLD.PORCENANTICIPO)||' - '||TO_CHAR(:OLD.MONTOANTICIPO)||' - '||TO_CHAR(:OLD.PORCENDEDUCIBLE)||' - '||
                  TO_CHAR(:OLD.MONTODEDUCIBLE)||' - '||TO_CHAR(:OLD.PERIODOESPERAANIOS)||' - '||TO_CHAR(:OLD.PERIODOESPERAMESES)||' - '||TO_CHAR(:OLD.INDSUMASAMI)||' - '||TO_CHAR(:OLD.ORDENIMPRESION)||' - '||
                  TO_CHAR(:OLD.TABMORTALIDAD)||' - '||TO_CHAR(:OLD.ORDENSESAS)||' - '||TO_CHAR(:OLD.CODGRUPOCOBERT)||' - '||TO_CHAR(:OLD.INDREASINIESTRO)||' - '||TO_CHAR(:OLD.INDCANCPOLSINI)||' - '||
                  TO_CHAR(:OLD.CODMOTIVCANCELPOL)||' - '||TO_CHAR(:OLD.PORC_DEVOL_PRIMA)||' - '||TO_CHAR(:OLD.INDVALORGARANT)||' - '||TO_CHAR(:OLD.IDRAMOREAL);
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||
                  TO_CHAR(:NEW.DESCCOBERT)||' - '||TO_CHAR(:NEW.TIPOTASA)||' - '||TO_CHAR(:NEW.PORC_TASA)||' - '||TO_CHAR(:NEW.PRIMA_COBERT)||' - '||TO_CHAR(:NEW.STSCOBERTURA)||' - '||
                  TO_CHAR(:NEW.SUMAASEGURADA)||' - '||TO_CHAR(:NEW.COD_MONEDA)||' - '||TO_CHAR(:NEW.ACUMULAASUMA)||' - '||TO_CHAR(:NEW.INDBASICA)||' - '||TO_CHAR(:NEW.COBERTURA_BASICA)||' - '||
                  TO_CHAR(:NEW.CALCULA_PRORRATA)||' - '||TO_CHAR(:NEW.DEVUELVE_PRIMA)||' - '||TO_CHAR(:NEW.EDAD_MINIMA)||' - '||TO_CHAR(:NEW.EDAD_MAXIMA)||' - '||TO_CHAR(:NEW.EDAD_EXCLUSION)||' - '||
                  TO_CHAR(:NEW.NOMREP)||' - '||TO_CHAR(:NEW.CODCPTO)||' - '||TO_CHAR(:NEW.CODTARIFA)||' - '||TO_CHAR(:NEW.CLAVESESAS)||' - '||TO_CHAR(:NEW.CODRIESGOREA)||' - '||
                  TO_CHAR(:NEW.INDACUMULASUMAREA)||' - '||TO_CHAR(:NEW.INDACUMULAPRIMAREA)||' - '||TO_CHAR(:NEW.SUMAASEGMINIMA)||' - '||TO_CHAR(:NEW.SUMAASEGMAXIMA)||' - '||TO_CHAR(:NEW.SUMAASEGMAXINDIV)||' - '||
                  TO_CHAR(:NEW.INDPERDORGANICAS)||' - '||TO_CHAR(:NEW.INDMANEJAANTICIPOS)||' - '||TO_CHAR(:NEW.PORCENANTICIPO)||' - '||TO_CHAR(:NEW.MONTOANTICIPO)||' - '||TO_CHAR(:NEW.PORCENDEDUCIBLE)||' - '||
                  TO_CHAR(:NEW.MONTODEDUCIBLE)||' - '||TO_CHAR(:NEW.PERIODOESPERAANIOS)||' - '||TO_CHAR(:NEW.PERIODOESPERAMESES)||' - '||TO_CHAR(:NEW.INDSUMASAMI)||' - '||TO_CHAR(:NEW.ORDENIMPRESION)||' - '||
                  TO_CHAR(:NEW.TABMORTALIDAD)||' - '||TO_CHAR(:NEW.ORDENSESAS)||' - '||TO_CHAR(:NEW.CODGRUPOCOBERT)||' - '||TO_CHAR(:NEW.INDREASINIESTRO)||' - '||TO_CHAR(:NEW.INDCANCPOLSINI)||' - '||
                  TO_CHAR(:NEW.CODMOTIVCANCELPOL)||' - '||TO_CHAR(:NEW.PORC_DEVOL_PRIMA)||' - '||TO_CHAR(:NEW.INDVALORGARANT)||' - '||TO_CHAR(:NEW.IDRAMOREAL);

      vl_Primary := 'IDTIPOSEG: '||:NEW.IDTIPOSEG||' PLANCOB: '||:NEW.PLANCOB ||' CODCOBERT: '||:NEW.CODCOBERT||' CODEMPRESA: '||:NEW.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCOBERT <> :OLD.CODCOBERT) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCCOBERT,-20000) <> NVL(:OLD.DESCCOBERT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'DESCCOBERT', TO_CHAR(:OLD.DESCCOBERT), TO_CHAR(:NEW.DESCCOBERT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPOTASA,-20000) <> NVL(:OLD.TIPOTASA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'TIPOTASA', TO_CHAR(:OLD.TIPOTASA), TO_CHAR(:NEW.TIPOTASA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORC_TASA,-20000) <> NVL(:OLD.PORC_TASA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PORC_TASA', TO_CHAR(:OLD.PORC_TASA), TO_CHAR(:NEW.PORC_TASA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PRIMA_COBERT,-20000) <> NVL(:OLD.PRIMA_COBERT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PRIMA_COBERT', TO_CHAR(:OLD.PRIMA_COBERT), TO_CHAR(:NEW.PRIMA_COBERT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STSCOBERTURA,-20000) <> NVL(:OLD.STSCOBERTURA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'STSCOBERTURA', TO_CHAR(:OLD.STSCOBERTURA), TO_CHAR(:NEW.STSCOBERTURA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUMAASEGURADA,-20000) <> NVL(:OLD.SUMAASEGURADA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SUMAASEGURADA', TO_CHAR(:OLD.SUMAASEGURADA), TO_CHAR(:NEW.SUMAASEGURADA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COD_MONEDA,-20000) <> NVL(:OLD.COD_MONEDA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'COD_MONEDA', TO_CHAR(:OLD.COD_MONEDA), TO_CHAR(:NEW.COD_MONEDA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACUMULAASUMA,-20000) <> NVL(:OLD.ACUMULAASUMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'ACUMULAASUMA', TO_CHAR(:OLD.ACUMULAASUMA), TO_CHAR(:NEW.ACUMULAASUMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDBASICA,-20000) <> NVL(:OLD.INDBASICA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDBASICA', TO_CHAR(:OLD.INDBASICA), TO_CHAR(:NEW.INDBASICA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.COBERTURA_BASICA,-20000) <> NVL(:OLD.COBERTURA_BASICA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'COBERTURA_BASICA', TO_CHAR(:OLD.COBERTURA_BASICA), TO_CHAR(:NEW.COBERTURA_BASICA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CALCULA_PRORRATA,-20000) <> NVL(:OLD.CALCULA_PRORRATA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CALCULA_PRORRATA', TO_CHAR(:OLD.CALCULA_PRORRATA), TO_CHAR(:NEW.CALCULA_PRORRATA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DEVUELVE_PRIMA,-20000) <> NVL(:OLD.DEVUELVE_PRIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'DEVUELVE_PRIMA', TO_CHAR(:OLD.DEVUELVE_PRIMA), TO_CHAR(:NEW.DEVUELVE_PRIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDAD_MINIMA,-20000) <> NVL(:OLD.EDAD_MINIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'EDAD_MINIMA', TO_CHAR(:OLD.EDAD_MINIMA), TO_CHAR(:NEW.EDAD_MINIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDAD_MAXIMA,-20000) <> NVL(:OLD.EDAD_MAXIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'EDAD_MAXIMA', TO_CHAR(:OLD.EDAD_MAXIMA), TO_CHAR(:NEW.EDAD_MAXIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EDAD_EXCLUSION,-20000) <> NVL(:OLD.EDAD_EXCLUSION,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'EDAD_EXCLUSION', TO_CHAR(:OLD.EDAD_EXCLUSION), TO_CHAR(:NEW.EDAD_EXCLUSION),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMREP,-20000) <> NVL(:OLD.NOMREP,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'NOMREP', TO_CHAR(:OLD.NOMREP), TO_CHAR(:NEW.NOMREP),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCPTO,-20000) <> NVL(:OLD.CODCPTO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODCPTO', TO_CHAR(:OLD.CODCPTO), TO_CHAR(:NEW.CODCPTO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTARIFA,-20000) <> NVL(:OLD.CODTARIFA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODTARIFA', TO_CHAR(:OLD.CODTARIFA), TO_CHAR(:NEW.CODTARIFA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CLAVESESAS,-20000) <> NVL(:OLD.CLAVESESAS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CLAVESESAS', TO_CHAR(:OLD.CLAVESESAS), TO_CHAR(:NEW.CLAVESESAS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRIESGOREA,-20000) <> NVL(:OLD.CODRIESGOREA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODRIESGOREA', TO_CHAR(:OLD.CODRIESGOREA), TO_CHAR(:NEW.CODRIESGOREA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDACUMULASUMAREA,-20000) <> NVL(:OLD.INDACUMULASUMAREA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDACUMULASUMAREA', TO_CHAR(:OLD.INDACUMULASUMAREA), TO_CHAR(:NEW.INDACUMULASUMAREA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDACUMULAPRIMAREA,-20000) <> NVL(:OLD.INDACUMULAPRIMAREA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDACUMULAPRIMAREA', TO_CHAR(:OLD.INDACUMULAPRIMAREA), TO_CHAR(:NEW.INDACUMULAPRIMAREA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUMAASEGMINIMA,-20000) <> NVL(:OLD.SUMAASEGMINIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SUMAASEGMINIMA', TO_CHAR(:OLD.SUMAASEGMINIMA), TO_CHAR(:NEW.SUMAASEGMINIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUMAASEGMAXIMA,-20000) <> NVL(:OLD.SUMAASEGMAXIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SUMAASEGMAXIMA', TO_CHAR(:OLD.SUMAASEGMAXIMA), TO_CHAR(:NEW.SUMAASEGMAXIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SUMAASEGMAXINDIV,-20000) <> NVL(:OLD.SUMAASEGMAXINDIV,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'SUMAASEGMAXINDIV', TO_CHAR(:OLD.SUMAASEGMAXINDIV), TO_CHAR(:NEW.SUMAASEGMAXINDIV),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDPERDORGANICAS,-20000) <> NVL(:OLD.INDPERDORGANICAS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDPERDORGANICAS', TO_CHAR(:OLD.INDPERDORGANICAS), TO_CHAR(:NEW.INDPERDORGANICAS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDMANEJAANTICIPOS,-20000) <> NVL(:OLD.INDMANEJAANTICIPOS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDMANEJAANTICIPOS', TO_CHAR(:OLD.INDMANEJAANTICIPOS), TO_CHAR(:NEW.INDMANEJAANTICIPOS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCENANTICIPO,-20000) <> NVL(:OLD.PORCENANTICIPO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PORCENANTICIPO', TO_CHAR(:OLD.PORCENANTICIPO), TO_CHAR(:NEW.PORCENANTICIPO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTOANTICIPO,-20000) <> NVL(:OLD.MONTOANTICIPO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'MONTOANTICIPO', TO_CHAR(:OLD.MONTOANTICIPO), TO_CHAR(:NEW.MONTOANTICIPO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCENDEDUCIBLE,-20000) <> NVL(:OLD.PORCENDEDUCIBLE,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PORCENDEDUCIBLE', TO_CHAR(:OLD.PORCENDEDUCIBLE), TO_CHAR(:NEW.PORCENDEDUCIBLE),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTODEDUCIBLE,-20000) <> NVL(:OLD.MONTODEDUCIBLE,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'MONTODEDUCIBLE', TO_CHAR(:OLD.MONTODEDUCIBLE), TO_CHAR(:NEW.MONTODEDUCIBLE),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PERIODOESPERAANIOS,-20000) <> NVL(:OLD.PERIODOESPERAANIOS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PERIODOESPERAANIOS', TO_CHAR(:OLD.PERIODOESPERAANIOS), TO_CHAR(:NEW.PERIODOESPERAANIOS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PERIODOESPERAMESES ,-20000)<> NVL(:OLD.PERIODOESPERAMESES,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PERIODOESPERAMESES', TO_CHAR(:OLD.PERIODOESPERAMESES), TO_CHAR(:NEW.PERIODOESPERAMESES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDSUMASAMI,-20000) <> NVL(:OLD.INDSUMASAMI,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDSUMASAMI', TO_CHAR(:OLD.INDSUMASAMI), TO_CHAR(:NEW.INDSUMASAMI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENIMPRESION,-20000) <> NVL(:OLD.ORDENIMPRESION,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'ORDENIMPRESION', TO_CHAR(:OLD.ORDENIMPRESION), TO_CHAR(:NEW.ORDENIMPRESION),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TABMORTALIDAD,-20000) <> NVL(:OLD.TABMORTALIDAD,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'TABMORTALIDAD', TO_CHAR(:OLD.TABMORTALIDAD), TO_CHAR(:NEW.TABMORTALIDAD),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENSESAS,-20000) <> NVL(:OLD.ORDENSESAS,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'ORDENSESAS', TO_CHAR(:OLD.ORDENSESAS), TO_CHAR(:NEW.ORDENSESAS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODGRUPOCOBERT,-20000) <> NVL(:OLD.CODGRUPOCOBERT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODGRUPOCOBERT', TO_CHAR(:OLD.CODGRUPOCOBERT), TO_CHAR(:NEW.CODGRUPOCOBERT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDREASINIESTRO,-20000) <> NVL(:OLD.INDREASINIESTRO,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDREASINIESTRO', TO_CHAR(:OLD.INDREASINIESTRO), TO_CHAR(:NEW.INDREASINIESTRO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCANCPOLSINI,-20000) <> NVL(:OLD.INDCANCPOLSINI,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDCANCPOLSINI', TO_CHAR(:OLD.INDCANCPOLSINI), TO_CHAR(:NEW.INDCANCPOLSINI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODMOTIVCANCELPOL,-20000) <> NVL(:OLD.CODMOTIVCANCELPOL,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'CODMOTIVCANCELPOL', TO_CHAR(:OLD.CODMOTIVCANCELPOL), TO_CHAR(:NEW.CODMOTIVCANCELPOL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORC_DEVOL_PRIMA,-20000) <> NVL(:OLD.PORC_DEVOL_PRIMA,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'PORC_DEVOL_PRIMA', TO_CHAR(:OLD.PORC_DEVOL_PRIMA), TO_CHAR(:NEW.PORC_DEVOL_PRIMA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDVALORGARANT,-20000) <> NVL(:OLD.INDVALORGARANT,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'INDVALORGARANT', TO_CHAR(:OLD.INDVALORGARANT), TO_CHAR(:NEW.INDVALORGARANT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDRAMOREAL,-20000) <> NVL(:OLD.IDRAMOREAL,-20000)) THEN
      vl_Primary := 'IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB ||' CODCOBERT: '||:OLD.CODCOBERT||' CODEMPRESA: '||:OLD.CODEMPRESA;
       OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COBERTURAS_DE_SEGUROS', 'IDRAMOREAL', TO_CHAR(:OLD.IDRAMOREAL), TO_CHAR(:NEW.IDRAMOREAL),'UPDATE',vl_Primary);
    END IF;
  END IF;    
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de COBERTURAS_DE_SEGUROS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_COBERTURAS_DE_SEGUROS FOR SICAS_OC.TRG_COBERTURAS_DE_SEGUROS;
