CREATE OR REPLACE TRIGGER SICAS_OC.TRG_AGENTES_DISTRIBUCION_POLIZA
  BEFORE DELETE ON AGENTES_DISTRIBUCION_POLIZA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA AGENTES_DISTRIBUCION_POLIZA
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.IDPOLIZA)||' - '||TO_CHAR(:OLD.COD_AGENTE)||' - '||TO_CHAR(:OLD.CODNIVEL)||' - '||TO_CHAR(:OLD.COD_AGENTE_DISTR)||' - '||TO_CHAR(:OLD.PORC_COMISION_AGENTE) ||' - '||
                  TO_CHAR(:OLD.PORC_COM_DISTRIBUIDA)||' - '||TO_CHAR(:OLD.PORC_COMISION_PLAN)||' - '||TO_CHAR(:OLD.PORC_COM_PROPORCIONAL)||' - '||TO_CHAR(:OLD.COD_AGENTE_JEFE) ||' - '||TO_CHAR(:OLD.PORC_COM_POLIZA)||' - '||
                  TO_CHAR(:OLD.ORIGEN);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' IDPOLIZA: '||:OLD.IDPOLIZA||' COD_AGENTE: '||:OLD.COD_AGENTE||' CODNIVEL: '||:OLD.CODNIVEL;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'AGENTES_DISTRIBUCION_POLIZA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de AGENTES_DISTRIBUCION_POLIZA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_AGENTES_DISTRIBUCION_POLIZA FOR SICAS_OC.TRG_AGENTES_DISTRIBUCION_POLIZA;
