CREATE OR REPLACE TRIGGER TRG_D_FACT_ELECT_CLAVE_UNIDAD
BEFORE DELETE
ON FACT_ELECT_CLAVE_UNIDAD
FOR EACH ROW
DECLARE
    cTexto     VARCHAR2(4000);

 BEGIN

    cTexto := TO_CHAR(:OLD.CODCIA)||' - '||:OLD.CLAVEUNIDAD||' - '||TO_CHAR(:OLD.FECINIVIG)||' - '||TO_CHAR(:OLD.FECFINVIG)||' - '||:OLD.NOMBRECLAVEUNIDAD||' - '||:OLD.DESCCLAVEUNIDAD||' - '||:OLD.NOTACLAVEUNIDAD||' - '||:OLD.INDAPLICANEGOCIO||' - '||:OLD.CODUSUARIO||' - '||TO_CHAR(:OLD.FECULTMODIF);
 
    OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'TODOS LOS CAMPOS', cTexto, 'Null', 'DELETE');
	
END TRG_D_FACT_ELECT_CLAVE_UNIDAD;