CREATE OR REPLACE TRIGGER TRG_UP_FACT_ELECT_PROD_SERV
BEFORE UPDATE
ON FACT_ELECT_PROD_SERV
FOR EACH ROW

 BEGIN

  IF :NEW.CLAVEPRODSERV != :OLD.CLAVEPRODSERV THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'CLAVEPRODSERV', :OLD.CLAVEPRODSERV, :NEW.CLAVEPRODSERV, 'UPDATE');

  END IF;

  IF :NEW.DESCCLAVEPRODSERV != :OLD.DESCCLAVEPRODSERV THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'DESCCLAVEPRODSERV', :OLD.DESCCLAVEPRODSERV, :NEW.DESCCLAVEPRODSERV, 'UPDATE');

  END IF;

  IF :NEW.INDAPLICANEGOCIO != :OLD.INDAPLICANEGOCIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'INDAPLICANEGOCIO', :OLD.INDAPLICANEGOCIO, :NEW.INDAPLICANEGOCIO, 'UPDATE');

  END IF;

  IF :NEW.CLAVEUNIDAD != :OLD.CLAVEUNIDAD THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'CLAVEUNIDAD', :OLD.CLAVEUNIDAD, :NEW.CLAVEUNIDAD, 'UPDATE');

  END IF;

  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');

  END IF;

  IF :NEW.FECULTMODIF != :OLD.FECULTMODIF THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_PROD_SERV', 'FECULTMODIF', TO_CHAR(:OLD.FECULTMODIF), TO_CHAR(:NEW.FECULTMODIF), 'UPDATE');

  END IF;

 END TRG_UP_FACT_ELECT_PROD_SERV;