CREATE OR REPLACE TRIGGER SICAS_OC.TRG_COND_GEN_AUTORIDAD
  BEFORE INSERT OR UPDATE OR DELETE ON COND_GEN_AUTORIDAD
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA COND_GEN_AUTORIDAD
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.NUMREGISTRO)||' - '||TO_CHAR(:OLD.DS_ARCH_CONGEN)||' - '||
                  TO_CHAR(:OLD.STREGISTRO)||' - '||TO_CHAR(:OLD.FE_INIVIG)||' - '||TO_CHAR(:OLD.FE_FINVIG)||' - '||TO_CHAR(:OLD.NUMAUTORTIPSEG)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||
                  TO_CHAR(:OLD.FE_ALTA)||' - '||TO_CHAR(:OLD.OBSERVACIONES);
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.NUMREGISTRO)||' - '||TO_CHAR(:NEW.DS_ARCH_CONGEN)||' - '||
                  TO_CHAR(:NEW.STREGISTRO)||' - '||TO_CHAR(:NEW.FE_INIVIG)||' - '||TO_CHAR(:NEW.FE_FINVIG)||' - '||TO_CHAR(:NEW.NUMAUTORTIPSEG)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||
                  TO_CHAR(:NEW.FE_ALTA)||' - '||TO_CHAR(:NEW.OBSERVACIONES);
      vl_Primary := 'CODEMPRESA: '||:NEW.CODEMPRESA||' CODCIA: '||:NEW.CODCIA||' IDTIPOSEG: '||:NEW.IDTIPOSEG||' NUMREGISTRO: '||:NEW.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'COND_GEN_AUTORIDAD', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUMREGISTRO <> :OLD.NUMREGISTRO) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'NUMREGISTRO', TO_CHAR(:OLD.NUMREGISTRO), TO_CHAR(:NEW.NUMREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DS_ARCH_CONGEN,-20000) <> NVL(:OLD.DS_ARCH_CONGEN,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'DS_ARCH_CONGEN', TO_CHAR(:OLD.DS_ARCH_CONGEN), TO_CHAR(:NEW.DS_ARCH_CONGEN), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.STREGISTRO,-20000) <> NVL(:OLD.STREGISTRO,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'STREGISTRO', TO_CHAR(:OLD.STREGISTRO), TO_CHAR(:NEW.STREGISTRO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FE_INIVIG,SYSDATE) <> NVL(:OLD.FE_INIVIG,SYSDATE)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'FE_INIVIG', TO_CHAR(:OLD.FE_INIVIG), TO_CHAR(:NEW.FE_INIVIG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FE_FINVIG,SYSDATE) <> NVL(:OLD.FE_FINVIG,SYSDATE)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'FE_FINVIG', TO_CHAR(:OLD.FE_FINVIG), TO_CHAR(:NEW.FE_FINVIG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMAUTORTIPSEG,-20000) <> NVL(:OLD.NUMAUTORTIPSEG,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'NUMAUTORTIPSEG', TO_CHAR(:OLD.NUMAUTORTIPSEG), TO_CHAR(:NEW.NUMAUTORTIPSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FE_ALTA,SYSDATE) <> NVL(:OLD.FE_ALTA,SYSDATE)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'FE_ALTA', TO_CHAR(:OLD.FE_ALTA), TO_CHAR(:NEW.FE_ALTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.OBSERVACIONES,-20000) <> NVL(:OLD.OBSERVACIONES,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' CODCIA: '||:OLD.CODCIA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' NUMREGISTRO: '||:OLD.NUMREGISTRO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'COND_GEN_AUTORIDAD', 'OBSERVACIONES', TO_CHAR(:OLD.OBSERVACIONES), TO_CHAR(:NEW.OBSERVACIONES), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de COND_GEN_AUTORIDAD, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_COND_GEN_AUTORIDAD FOR SICAS_OC.TRG_COND_GEN_AUTORIDAD;
