CREATE OR REPLACE TRIGGER TRG_UP_FACT_ELECT_CAT_GPO_LINEA
BEFORE UPDATE
ON FACT_ELECT_CAT_GPO_LINEA
FOR EACH ROW
 
 BEGIN
    
  IF :NEW.CODIDENTIFICADOR != :OLD.CODIDENTIFICADOR THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'CODIDENTIFICADOR', :OLD.CODIDENTIFICADOR, :NEW.CODIDENTIFICADOR, 'UPDATE');
  
  END IF;
  
  IF :NEW.DESCIDENTIFICADOR != :OLD.DESCIDENTIFICADOR THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'DESCIDENTIFICADOR', :OLD.DESCIDENTIFICADOR, :NEW.DESCIDENTIFICADOR, 'UPDATE');
  
  END IF;
  
  IF :NEW.VERSIONCFDI != :OLD.VERSIONCFDI THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'VERSIONCFDI', :OLD.VERSIONCFDI, :NEW.VERSIONCFDI, 'UPDATE');
 
  END IF;
  
  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');
  
  END IF;
  
  IF :NEW.FECHALINEA != :OLD.FECHALINEA THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CAT_GPO_LINEA', 'FECHALINEA', TO_CHAR(:OLD.FECHALINEA), TO_CHAR(:NEW.FECHALINEA), 'UPDATE');
  
  END IF;
  
 END TRG_UP_FACT_ELECT_CAT_GPO_LINEA;
 