CREATE OR REPLACE TRIGGER TRG_U_DET_FACT_ELECT_CONFDOCT
AFTER UPDATE
ON DETALLE_FACT_ELECT_CONF_DOCTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

  IF :NEW.CODIDENTIFICADOR != :OLD.CODIDENTIFICADOR THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODIDENTIFICADOR', :OLD.CODIDENTIFICADOR, :NEW.CODIDENTIFICADOR, 'UPDATE');
     
  END IF;
  --
  IF :NEW.CODATRIBUTO != :OLD.CODATRIBUTO THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODATRIBUTO', :OLD.CODATRIBUTO, :NEW.CODATRIBUTO, 'UPDATE' );
    
  END IF;
  --
  IF :NEW.ORDENATRIB != :OLD.ORDENATRIB THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'ORDENATRIB', TO_CHAR(:OLD.ORDENATRIB), TO_CHAR(:NEW.ORDENATRIB), 'UPDATE');
  
  END IF;
  --
  IF :NEW.CONDICIONATRIBUTO != :OLD.CONDICIONATRIBUTO THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CONDICIONATRIBUTO', :OLD.CONDICIONATRIBUTO, :NEW.CONDICIONATRIBUTO,'UPDATE' );

  END IF;
  --
  IF :NEW.TIPOVALORATRIBUTO != :OLD.TIPOVALORATRIBUTO THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'TIPOVALORATRIBUTO', :OLD.TIPOVALORATRIBUTO, :NEW.TIPOVALORATRIBUTO, 'UPDATE');

  END IF;
  --
  IF  :NEW.VALORATRIBUTO != :OLD.VALORATRIBUTO THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'VALORATRIBUTO', :OLD.VALORATRIBUTO, :NEW.VALORATRIBUTO, 'UPDATE');

  END IF;
  --
  IF :NEW.INDENVIACIA != :OLD.INDENVIACIA THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'INDENVIACIA', :OLD.INDENVIACIA, :NEW.INDENVIACIA, 'UPDATE');

  END IF;
  --
  IF :NEW.CODRUTINACALC != :OLD.CODRUTINACALC THEN
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CODRUTINACALC', :OLD.CODRUTINACALC, :NEW.CODRUTINACALC, 'UPDATE');

  END IF;
  
  --IF :BK_DETDCTOCFDI.CONSULTA != :OLD.CONSULTA THEN
     --OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'DETALLE_FACT_ELECT_CONF_DOCTO', 'CONSULTA', :OLD.CONSULTA, TO_CLOB(:NEW.CONSULTA), 'UPDATE');
  --END IF;
  --
END TRG_U_DET_FACT_ELECT_CONFDOCT;
