CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_COMISIONES
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_COMISIONES
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_COMISIONES
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.PORCCOMISION)||' - '||TO_CHAR(:OLD.MONTOCOMISION);
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.PORCCOMISION)||' - '||TO_CHAR(:NEW.MONTOCOMISION);
      vl_Primary := 'CODEMPRESA: '||:NEW.CODEMPRESA||' IDTIPOSEG: '||:NEW.IDTIPOSEG||' CODCIA: '||:NEW.CODCIA;
    OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_COMISIONES', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCCOMISION,-20000) <> NVL(:OLD.PORCCOMISION,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'PORCCOMISION', TO_CHAR(:OLD.PORCCOMISION), TO_CHAR(:NEW.PORCCOMISION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTOCOMISION,-20000) <> NVL(:OLD.MONTOCOMISION,-20000)) THEN
      vl_Primary := 'CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' CODCIA: '||:OLD.CODCIA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_COMISIONES', 'MONTOCOMISION', TO_CHAR(:OLD.MONTOCOMISION), TO_CHAR(:NEW.MONTOCOMISION), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_COMISIONES, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_COMISIONES FOR SICAS_OC.TRG_CONFIG_COMISIONES;
