CREATE OR REPLACE TRIGGER SICAS_OC.TRG_FACTOR_GUA
  BEFORE INSERT OR UPDATE OR DELETE ON FACTOR_GUA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA FACTOR_GUA
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODCOBERT)||' - '||
                  TO_CHAR(:OLD.NIVEL)||' - '||TO_CHAR(:OLD.FACTOR)||' - '||TO_CHAR(:OLD.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:OLD.ACTUALIZO_FECHA);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODCOBERT)||' - '||
                  TO_CHAR(:NEW.NIVEL)||' - '||TO_CHAR(:NEW.FACTOR)||' - '||TO_CHAR(:NEW.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:NEW.ACTUALIZO_FECHA);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA ||' CODEMPRESA: '||:NEW.CODEMPRESA ||' IDTIPOSEG: '||:NEW.IDTIPOSEG ||' PLANCOB: '||:NEW.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'FACTOR_GUA', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCOBERT <> :OLD.CODCOBERT) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'CODCOBERT', TO_CHAR(:OLD.CODCOBERT), TO_CHAR(:NEW.CODCOBERT), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NIVEL <> :OLD.NIVEL) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'NIVEL', TO_CHAR(:OLD.NIVEL), TO_CHAR(:NEW.NIVEL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FACTOR,-20000) <> NVL(:OLD.FACTOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'FACTOR', TO_CHAR(:OLD.FACTOR), TO_CHAR(:NEW.FACTOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_USUARIO,-20000) <> NVL(:OLD.ACTUALIZO_USUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'ACTUALIZO_USUARIO', TO_CHAR(:OLD.ACTUALIZO_USUARIO), TO_CHAR(:NEW.ACTUALIZO_USUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_FECHA,SYSDATE) <> NVL(:OLD.ACTUALIZO_FECHA,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA ||' CODEMPRESA: '||:OLD.CODEMPRESA ||' IDTIPOSEG: '||:OLD.IDTIPOSEG ||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_GUA', 'ACTUALIZO_FECHA', TO_CHAR(:OLD.ACTUALIZO_FECHA), TO_CHAR(:NEW.ACTUALIZO_FECHA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de FACTOR_GUA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_FACTOR_GUA FOR SICAS_OC.TRG_FACTOR_GUA;
