CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONTACTOS_PNJ
  BEFORE INSERT OR UPDATE OR DELETE ON CONTACTOS_PNJ
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONTACTOS_PNJ
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.CORRELATIVO_CONTACTO)||' - '||TO_CHAR(:OLD.NOMBRE)||' - '||TO_CHAR(:OLD.PUESTO)||' - '||
                  TO_CHAR(:OLD.TELEFONOS)||' - '||TO_CHAR(:OLD.EMAIL)||' - '||TO_CHAR(:OLD.PRIORIDAD_CONTACTO)||' - '||TO_CHAR(:OLD.TIPO_TELEFONO);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:NEW.CORRELATIVO_CONTACTO)||' - '||TO_CHAR(:NEW.NOMBRE)||' - '||TO_CHAR(:NEW.PUESTO)||' - '||
                  TO_CHAR(:NEW.TELEFONOS)||' - '||TO_CHAR(:NEW.EMAIL)||' - '||TO_CHAR(:NEW.PRIORIDAD_CONTACTO)||' - '||TO_CHAR(:NEW.TIPO_TELEFONO);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:NEW.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:NEW.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:NEW.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CORRELATIVO_CONTACTO <> :OLD.CORRELATIVO_CONTACTO) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'CORRELATIVO_CONTACTO', TO_CHAR(:OLD.CORRELATIVO_CONTACTO), TO_CHAR(:NEW.CORRELATIVO_CONTACTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NOMBRE <> :OLD.NOMBRE) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'NOMBRE', TO_CHAR(:OLD.NOMBRE), TO_CHAR(:NEW.NOMBRE), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PUESTO,-20000) <> NVL(:OLD.PUESTO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'PUESTO', TO_CHAR(:OLD.PUESTO), TO_CHAR(:NEW.PUESTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TELEFONOS,-20000) <> NVL(:OLD.TELEFONOS,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'TELEFONOS', TO_CHAR(:OLD.TELEFONOS), TO_CHAR(:NEW.TELEFONOS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EMAIL,-20000) <> NVL(:OLD.EMAIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'EMAIL', TO_CHAR(:OLD.EMAIL), TO_CHAR(:NEW.EMAIL), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PRIORIDAD_CONTACTO,-20000) <> NVL(:OLD.PRIORIDAD_CONTACTO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'PRIORIDAD_CONTACTO', TO_CHAR(:OLD.PRIORIDAD_CONTACTO), TO_CHAR(:NEW.PRIORIDAD_CONTACTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_TELEFONO,-20000) <> NVL(:OLD.TIPO_TELEFONO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION ||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION ||' CORRELATIVO_CONTACTO: '||:OLD.CORRELATIVO_CONTACTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'CONTACTOS_PNJ', 'TIPO_TELEFONO', TO_CHAR(:OLD.TIPO_TELEFONO), TO_CHAR(:NEW.TIPO_TELEFONO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONTACTOS_PNJ, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONTACTOS_PNJ FOR SICAS_OC.TRG_CONTACTOS_PNJ;
