CREATE OR REPLACE TRIGGER SICAS_OC.TRG_TIPO_DE_LISTA
  BEFORE INSERT OR UPDATE OR DELETE ON TIPO_DE_LISTA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA TIPO_DE_LISTA
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODLISTA)||' - '||TO_CHAR(:OLD.DESCLISTA)||' - '||TO_CHAR(:OLD.TIPO_LISTA);
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TIPO_DE_LISTA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODLISTA)||' - '||TO_CHAR(:NEW.DESCLISTA)||' - '||TO_CHAR(:NEW.TIPO_LISTA);
      vl_Primary := 'CODLISTA: '||:NEW.CODLISTA;
    OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TIPO_DE_LISTA', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODLISTA <> :OLD.CODLISTA) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TIPO_DE_LISTA', 'CODLISTA', TO_CHAR(:OLD.CODLISTA), TO_CHAR(:NEW.CODLISTA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCLISTA <> :OLD.DESCLISTA) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TIPO_DE_LISTA', 'DESCLISTA', TO_CHAR(:OLD.DESCLISTA), TO_CHAR(:NEW.DESCLISTA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_LISTA,-20000) <> NVL(:OLD.TIPO_LISTA,-20000)) THEN
      vl_Primary := 'CODLISTA: '||:OLD.CODLISTA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'TIPO_DE_LISTA', 'TIPO_LISTA', TO_CHAR(:OLD.TIPO_LISTA), TO_CHAR(:NEW.TIPO_LISTA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de TIPO_DE_LISTA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_TIPO_DE_LISTA FOR SICAS_OC.TRG_TIPO_DE_LISTA;
