CREATE OR REPLACE TRIGGER TRG_U_FACT_ELECT_CLAVE_UNIDAD
BEFORE UPDATE
ON FACT_ELECT_CLAVE_UNIDAD
FOR EACH ROW
  
 BEGIN
    
  IF :NEW.FECINIVIG != :OLD.FECINIVIG THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'FECINIVIG', TO_CHAR(:OLD.FECINIVIG), TO_CHAR(:NEW.FECINIVIG), 'UPDATE');
  
  END IF;
  
  IF :NEW.FECFINVIG != :OLD.FECFINVIG THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'FECFINVIG', TO_CHAR(:OLD.FECFINVIG), TO_CHAR(:NEW.FECFINVIG), 'UPDATE');
  
  END IF;
  
  IF :NEW.NOMBRECLAVEUNIDAD != :OLD.NOMBRECLAVEUNIDAD THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'NOMBRECLAVEUNIDAD', :OLD.NOMBRECLAVEUNIDAD, :NEW.NOMBRECLAVEUNIDAD, 'UPDATE');
  
  END IF;
  
  IF :NEW.DESCCLAVEUNIDAD != :OLD.DESCCLAVEUNIDAD THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'DESCCLAVEUNIDAD', :OLD.DESCCLAVEUNIDAD, :NEW.DESCCLAVEUNIDAD, 'UPDATE');
  
  END IF;
  
  IF :NEW.NOTACLAVEUNIDAD != :OLD.NOTACLAVEUNIDAD THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'NOTACLAVEUNIDAD', :OLD.NOTACLAVEUNIDAD, :NEW.NOTACLAVEUNIDAD, 'UPDATE');
  
  END IF;
  
  IF :NEW.INDAPLICANEGOCIO != :OLD.INDAPLICANEGOCIO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'INDAPLICANEGOCIO', :OLD.INDAPLICANEGOCIO, :NEW.INDAPLICANEGOCIO, 'UPDATE');
  
  END IF;
  
  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');
  
  END IF;
  
  IF :NEW.FECULTMODIF != :OLD.FECULTMODIF THEN
  
     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_CLAVE_UNIDAD', 'FECULTMODIF', TO_CHAR(:OLD.FECULTMODIF), TO_CHAR(:NEW.FECULTMODIF), 'UPDATE');
  
  END IF;
  
 END TRG_U_FACT_ELECT_CLAVE_UNIDAD;
