CREATE OR REPLACE TRIGGER TRG_U_FACT_ELECT_OBJ_IMPUESTO
BEFORE UPDATE
ON FACT_ELECT_OBJETO_IMPUESTO
FOR EACH ROW

 BEGIN

  IF :NEW.CODOBJETOIMP != :OLD.CODOBJETOIMP THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'CODOBJETOIMP', :OLD.CODOBJETOIMP, :NEW.CODOBJETOIMP, 'UPDATE');

  END IF;

  IF :NEW.DESCOBJETOIMP != :OLD.DESCOBJETOIMP THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'DESCOBJETOIMP', :OLD.DESCOBJETOIMP, :NEW.DESCOBJETOIMP, 'UPDATE');

  END IF;

  IF :NEW.FECINIVIG != :OLD.FECINIVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'FECINIVIG', TO_CHAR(:OLD.FECINIVIG), TO_CHAR(:NEW.FECINIVIG), 'UPDATE');

  END IF;

  IF :NEW.FECFINVIG != :OLD.FECFINVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'FECFINVIG', TO_CHAR(:OLD.FECFINVIG), TO_CHAR(:NEW.FECFINVIG), 'UPDATE');

  END IF;

  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');

  END IF;

  IF :NEW.FECMOD != :OLD.FECMOD THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_OBJETO_IMPUESTO', 'FECMOD', TO_CHAR(:OLD.FECMOD), TO_CHAR(:NEW.FECMOD), 'UPDATE');

  END IF;

 END TRG_U_FACT_ELECT_OBJ_IMPUESTO;