CREATE OR REPLACE TRIGGER SICAS_OC.TRG_PERSONA_NATURAL_JURIDICA
  BEFORE UPDATE OR DELETE ON PERSONA_NATURAL_JURIDICA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA PERSONA_NATURAL_JURIDICA
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION)||' - '||TO_CHAR(:OLD.NOMBRE)||' - '||TO_CHAR(:OLD.APELLIDO)||' - '||TO_CHAR(:OLD.APECASADA)||' - '||TO_CHAR(:OLD.SEXO)||' - '||
                  TO_CHAR(:OLD.ESTADOCIVIL)||' - '||TO_CHAR(:OLD.FECNACIMIENTO)||' - '||TO_CHAR(:OLD.DIRECRES)||' - '||TO_CHAR(:OLD.CODPAISRES)||' - '||TO_CHAR(:OLD.CODPROVRES)||' - '||TO_CHAR(:OLD.CODDISTRES)||' - '||
                  TO_CHAR(:OLD.CODCORRRES)||' - '||TO_CHAR(:OLD.ZIPRES)||' - '||TO_CHAR(:OLD.TELRES)||' - '||TO_CHAR(:OLD.EMPRESATRAB)||' - '||TO_CHAR(:OLD.DIRECOFI)||' - '||TO_CHAR(:OLD.CODPAISOFI)||' - '||
                  TO_CHAR(:OLD.CODPROVOFI)||' - '||TO_CHAR(:OLD.CODDISTOFI)||' - '||TO_CHAR(:OLD.CODCORROFI)||' - '||TO_CHAR(:OLD.ZIPOFI)||' - '||TO_CHAR(:OLD.TELOFI)||' - '||TO_CHAR(:OLD.FAXOFI)||' - '||
                  TO_CHAR(:OLD.EMAIL)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.FECINGRESO)||' - '||TO_CHAR(:OLD.CEDULA)||' - '||TO_CHAR(:OLD.TIPO_ID_TRIBUTARIA)||' - '||TO_CHAR(:OLD.NUM_TRIBUTARIO)||' - '||
                  TO_CHAR(:OLD.CODIGOZIP)||' - '||TO_CHAR(:OLD.CODPOSRES)||' - '||TO_CHAR(:OLD.CODASENRES)||' - '||TO_CHAR(:OLD.CODPOSOFI)||' - '||TO_CHAR(:OLD.CODASENOFI)||' - '||TO_CHAR(:OLD.TIPO_PERSONA)||' - '||
                  TO_CHAR(:OLD.TIP_DOCIDE_MATRIZ)||' - '||TO_CHAR(:OLD.NUM_DOCIDE_MATRIZ)||' - '||TO_CHAR(:OLD.TELMOVIL)||' - '||TO_CHAR(:OLD.APELLIDO_MATERNO)||' - '||TO_CHAR(:OLD.APELLIDO_PATERNO)||' - '||TO_CHAR(:OLD.CODCOLRES)||' - '||
                  TO_CHAR(:OLD.LADATELRES)||' - '||TO_CHAR(:OLD.LADATELOFI)||' - '||TO_CHAR(:OLD.LADAFAXOFI)||' - '||TO_CHAR(:OLD.LADATELMOVIL)||' - '||TO_CHAR(:OLD.CODACTIVIDAD)||' - '||TO_CHAR(:OLD.NUMINTERIOR)||' - '||
                  TO_CHAR(:OLD.NUMEXTERIOR)||' - '||TO_CHAR(:OLD.AUXCONTABLE)||' - '||TO_CHAR(:OLD.NOMBRECOMERCIAL)||' - '||TO_CHAR(:OLD.CURP)||' - '||TO_CHAR(:OLD.CODLISTAREF)||' - '||TO_CHAR(:OLD.FECLISTAREF)||' - '||
                  TO_CHAR(:OLD.NACIONALIDAD)||' - '||TO_CHAR(:OLD.IDCLIENTEUNICO)||' - '||TO_CHAR(:OLD.IDREGFISSAT)||' - '||TO_CHAR(:OLD.RAZONSOCIALFACT)||' - '||TO_CHAR(:OLD.FECMOVTOSICAS)||' - '||TO_CHAR(:OLD.FECAPLICASAT);
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
  
  IF UPDATING THEN 
    IF (:NEW.TIPO_DOC_IDENTIFICACION <> :OLD.TIPO_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TIPO_DOC_IDENTIFICACION', TO_CHAR(:OLD.TIPO_DOC_IDENTIFICACION), TO_CHAR(:NEW.TIPO_DOC_IDENTIFICACION),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NUM_DOC_IDENTIFICACION <> :OLD.NUM_DOC_IDENTIFICACION) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NUM_DOC_IDENTIFICACION', TO_CHAR(:OLD.NUM_DOC_IDENTIFICACION), TO_CHAR(:NEW.NUM_DOC_IDENTIFICACION),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMBRE,-20000) <> NVL(:OLD.NOMBRE,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NOMBRE', TO_CHAR(:OLD.NOMBRE), TO_CHAR(:NEW.NOMBRE),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.APELLIDO,-20000) <> NVL(:OLD.APELLIDO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'APELLIDO', TO_CHAR(:OLD.APELLIDO), TO_CHAR(:NEW.APELLIDO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.APECASADA,-20000) <> NVL(:OLD.APECASADA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'APECASADA', TO_CHAR(:OLD.APECASADA), TO_CHAR(:NEW.APECASADA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SEXO,-20000) <> NVL(:OLD.SEXO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'SEXO', TO_CHAR(:OLD.SEXO), TO_CHAR(:NEW.SEXO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ESTADOCIVIL,-20000) <> NVL(:OLD.ESTADOCIVIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'ESTADOCIVIL', TO_CHAR(:OLD.ESTADOCIVIL), TO_CHAR(:NEW.ESTADOCIVIL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECNACIMIENTO,SYSDATE) <> NVL(:OLD.FECNACIMIENTO,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECNACIMIENTO', TO_CHAR(:OLD.FECNACIMIENTO), TO_CHAR(:NEW.FECNACIMIENTO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIRECRES,-20000) <> NVL(:OLD.DIRECRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'DIRECRES', TO_CHAR(:OLD.DIRECRES), TO_CHAR(:NEW.DIRECRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPAISRES,-20000) <> NVL(:OLD.CODPAISRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODPAISRES', TO_CHAR(:OLD.CODPAISRES), TO_CHAR(:NEW.CODPAISRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPROVRES,-20000) <> NVL(:OLD.CODPROVRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODPROVRES', TO_CHAR(:OLD.CODPROVRES), TO_CHAR(:NEW.CODPROVRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODDISTRES,-20000) <> NVL(:OLD.CODDISTRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODDISTRES', TO_CHAR(:OLD.CODDISTRES), TO_CHAR(:NEW.CODDISTRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCORRRES,-20000) <> NVL(:OLD.CODCORRRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODCORRRES', TO_CHAR(:OLD.CODCORRRES), TO_CHAR(:NEW.CODCORRRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ZIPRES,-20000) <> NVL(:OLD.ZIPRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'ZIPRES', TO_CHAR(:OLD.ZIPRES), TO_CHAR(:NEW.ZIPRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TELRES,-20000) <> NVL(:OLD.TELRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TELRES', TO_CHAR(:OLD.TELRES), TO_CHAR(:NEW.TELRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EMPRESATRAB,-20000) <> NVL(:OLD.EMPRESATRAB,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'EMPRESATRAB', TO_CHAR(:OLD.EMPRESATRAB), TO_CHAR(:NEW.EMPRESATRAB),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DIRECOFI,-20000) <> NVL(:OLD.DIRECOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'DIRECOFI', TO_CHAR(:OLD.DIRECOFI), TO_CHAR(:NEW.DIRECOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPAISOFI,-20000) <> NVL(:OLD.CODPAISOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'EMPRESATRAB', TO_CHAR(:OLD.CODPAISOFI), TO_CHAR(:NEW.CODPAISOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPROVOFI,-20000) <> NVL(:OLD.CODPROVOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODPROVOFI', TO_CHAR(:OLD.CODPROVOFI), TO_CHAR(:NEW.CODPROVOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODDISTOFI,-20000) <> NVL(:OLD.CODDISTOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODDISTOFI', TO_CHAR(:OLD.CODDISTOFI), TO_CHAR(:NEW.CODDISTOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCORROFI,-20000) <> NVL(:OLD.CODCORROFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODCORROFI', TO_CHAR(:OLD.CODCORROFI), TO_CHAR(:NEW.CODCORROFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ZIPOFI,-20000) <> NVL(:OLD.ZIPOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'ZIPOFI', TO_CHAR(:OLD.ZIPOFI), TO_CHAR(:NEW.ZIPOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TELOFI,-20000) <> NVL(:OLD.TELOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TELOFI', TO_CHAR(:OLD.TELOFI), TO_CHAR(:NEW.TELOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FAXOFI,-20000) <> NVL(:OLD.FAXOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FAXOFI', TO_CHAR(:OLD.FAXOFI), TO_CHAR(:NEW.FAXOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.EMAIL,-20000) <> NVL(:OLD.EMAIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'EMAIL', TO_CHAR(:OLD.EMAIL), TO_CHAR(:NEW.EMAIL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECSTS,SYSDATE) <> NVL(:OLD.FECSTS,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECINGRESO,SYSDATE) <> NVL(:OLD.FECINGRESO,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECINGRESO', TO_CHAR(:OLD.FECINGRESO), TO_CHAR(:NEW.FECINGRESO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CEDULA,-20000) <> NVL(:OLD.CEDULA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CEDULA', TO_CHAR(:OLD.CEDULA), TO_CHAR(:NEW.CEDULA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_ID_TRIBUTARIA,-20000) <> NVL(:OLD.TIPO_ID_TRIBUTARIA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TIPO_ID_TRIBUTARIA', TO_CHAR(:OLD.TIPO_ID_TRIBUTARIA), TO_CHAR(:NEW.TIPO_ID_TRIBUTARIA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUM_TRIBUTARIO,-20000) <> NVL(:OLD.NUM_TRIBUTARIO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NUM_TRIBUTARIO', TO_CHAR(:OLD.NUM_TRIBUTARIO), TO_CHAR(:NEW.NUM_TRIBUTARIO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODIGOZIP,-20000) <> NVL(:OLD.CODIGOZIP,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODIGOZIP', TO_CHAR(:OLD.CODIGOZIP), TO_CHAR(:NEW.CODIGOZIP),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPOSRES,-20000) <> NVL(:OLD.CODPOSRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODPOSRES', TO_CHAR(:OLD.CODPOSRES), TO_CHAR(:NEW.CODPOSRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODASENRES,-20000) <> NVL(:OLD.CODASENRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODASENRES', TO_CHAR(:OLD.CODASENRES), TO_CHAR(:NEW.CODASENRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODPOSOFI,-20000) <> NVL(:OLD.CODPOSOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODPOSOFI', TO_CHAR(:OLD.CODPOSOFI), TO_CHAR(:NEW.CODPOSOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODASENOFI,-20000) <> NVL(:OLD.CODASENOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODASENOFI', TO_CHAR(:OLD.CODASENOFI), TO_CHAR(:NEW.CODASENOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIPO_PERSONA,-20000) <> NVL(:OLD.TIPO_PERSONA,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TIPO_PERSONA', TO_CHAR(:OLD.TIPO_PERSONA), TO_CHAR(:NEW.TIPO_PERSONA),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TIP_DOCIDE_MATRIZ,-20000) <> NVL(:OLD.TIP_DOCIDE_MATRIZ,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TIP_DOCIDE_MATRIZ', TO_CHAR(:OLD.TIP_DOCIDE_MATRIZ), TO_CHAR(:NEW.TIP_DOCIDE_MATRIZ),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUM_DOCIDE_MATRIZ,-20000) <> NVL(:OLD.NUM_DOCIDE_MATRIZ,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NUM_DOCIDE_MATRIZ', TO_CHAR(:OLD.NUM_DOCIDE_MATRIZ), TO_CHAR(:NEW.NUM_DOCIDE_MATRIZ),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TELMOVIL,-20000) <> NVL(:OLD.TELMOVIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'TELMOVIL', TO_CHAR(:OLD.TELMOVIL), TO_CHAR(:NEW.TELMOVIL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.APELLIDO_MATERNO,-20000) <> NVL(:OLD.APELLIDO_MATERNO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'APELLIDO_MATERNO', TO_CHAR(:OLD.APELLIDO_MATERNO), TO_CHAR(:NEW.APELLIDO_MATERNO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.APELLIDO_PATERNO,-20000) <> NVL(:OLD.APELLIDO_PATERNO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'APELLIDO_PATERNO', TO_CHAR(:OLD.APELLIDO_PATERNO), TO_CHAR(:NEW.APELLIDO_PATERNO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCOLRES,-20000) <> NVL(:OLD.CODCOLRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODCOLRES', TO_CHAR(:OLD.CODCOLRES), TO_CHAR(:NEW.CODCOLRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.LADATELRES,-20000) <> NVL(:OLD.LADATELRES,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'LADATELRES', TO_CHAR(:OLD.LADATELRES), TO_CHAR(:NEW.LADATELRES),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.LADATELOFI,-20000) <> NVL(:OLD.LADATELOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'LADATELOFI', TO_CHAR(:OLD.LADATELOFI), TO_CHAR(:NEW.LADATELOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.LADAFAXOFI,-20000) <> NVL(:OLD.LADAFAXOFI,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'LADAFAXOFI', TO_CHAR(:OLD.LADAFAXOFI), TO_CHAR(:NEW.LADAFAXOFI),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.LADATELMOVIL,-20000) <> NVL(:OLD.LADATELMOVIL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'LADATELMOVIL', TO_CHAR(:OLD.LADATELMOVIL), TO_CHAR(:NEW.LADATELMOVIL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODACTIVIDAD,-20000) <> NVL(:OLD.CODACTIVIDAD,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODACTIVIDAD', TO_CHAR(:OLD.CODACTIVIDAD), TO_CHAR(:NEW.CODACTIVIDAD),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMINTERIOR,-20000) <> NVL(:OLD.NUMINTERIOR,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NUMINTERIOR', TO_CHAR(:OLD.NUMINTERIOR), TO_CHAR(:NEW.NUMINTERIOR),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NUMEXTERIOR,-20000) <> NVL(:OLD.NUMEXTERIOR,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NUMEXTERIOR', TO_CHAR(:OLD.NUMEXTERIOR), TO_CHAR(:NEW.NUMEXTERIOR),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.AUXCONTABLE,-20000) <> NVL(:OLD.AUXCONTABLE,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'AUXCONTABLE', TO_CHAR(:OLD.AUXCONTABLE), TO_CHAR(:NEW.AUXCONTABLE),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NOMBRECOMERCIAL,-20000) <> NVL(:OLD.NOMBRECOMERCIAL,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NOMBRECOMERCIAL', TO_CHAR(:OLD.NOMBRECOMERCIAL), TO_CHAR(:NEW.NOMBRECOMERCIAL),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CURP,-20000) <> NVL(:OLD.CURP,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CURP', TO_CHAR(:OLD.CURP), TO_CHAR(:NEW.CURP),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODLISTAREF,-20000) <> NVL(:OLD.CODLISTAREF,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'CODLISTAREF', TO_CHAR(:OLD.CODLISTAREF), TO_CHAR(:NEW.CODLISTAREF),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECLISTAREF,SYSDATE) <> NVL(:OLD.FECLISTAREF,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECLISTAREF', TO_CHAR(:OLD.FECLISTAREF), TO_CHAR(:NEW.FECLISTAREF),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NACIONALIDAD,-20000) <> NVL(:OLD.NACIONALIDAD,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'NACIONALIDAD', TO_CHAR(:OLD.NACIONALIDAD), TO_CHAR(:NEW.NACIONALIDAD),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDCLIENTEUNICO,-20000) <> NVL(:OLD.IDCLIENTEUNICO,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'IDCLIENTEUNICO', TO_CHAR(:OLD.IDCLIENTEUNICO), TO_CHAR(:NEW.IDCLIENTEUNICO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.IDREGFISSAT,-20000) <> NVL(:OLD.IDREGFISSAT,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'IDREGFISSAT', TO_CHAR(:OLD.IDREGFISSAT), TO_CHAR(:NEW.IDREGFISSAT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.RAZONSOCIALFACT,-20000) <> NVL(:OLD.RAZONSOCIALFACT,-20000)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'RAZONSOCIALFACT', TO_CHAR(:OLD.RAZONSOCIALFACT), TO_CHAR(:NEW.RAZONSOCIALFACT),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECMOVTOSICAS,SYSDATE) <> NVL(:OLD.FECMOVTOSICAS,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECMOVTOSICAS', TO_CHAR(:OLD.FECMOVTOSICAS), TO_CHAR(:NEW.FECMOVTOSICAS),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECAPLICASAT,SYSDATE) <> NVL(:OLD.FECAPLICASAT,SYSDATE)) THEN
      vl_Primary := 'TIPO_DOC_IDENTIFICACION: '||:OLD.TIPO_DOC_IDENTIFICACION||' NUM_DOC_IDENTIFICACION: '||:OLD.NUM_DOC_IDENTIFICACION;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'PERSONA_NATURAL_JURIDICA', 'FECAPLICASAT', TO_CHAR(:OLD.FECAPLICASAT), TO_CHAR(:NEW.FECAPLICASAT),'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de PERSONA_NATURAL_JURIDICA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_PERSONA_NATURAL_JURIDICA FOR SICAS_OC.TRG_PERSONA_NATURAL_JURIDICA;
