CREATE OR REPLACE TRIGGER SICAS_OC.TRG_RAMO_CONCEPTO_COMISION
  BEFORE INSERT OR UPDATE OR DELETE ON RAMO_CONCEPTO_COMISION
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA RAMO_CONCEPTO_COMISION
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCONCEPTO)||' - '||TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODTIPO)||' - '||TO_CHAR(:OLD.ORIGEN)||' - '||TO_CHAR(:OLD.CODTIPOPLAN);  
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCONCEPTO)||' - '||TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODTIPO)||' - '||TO_CHAR(:NEW.ORIGEN)||' - '||TO_CHAR(:NEW.CODTIPOPLAN); 
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODCONCEPTO: '||:NEW.CODCONCEPTO||' CODTIPO: '||:NEW.CODTIPO||' IDTIPOSEG: '||:NEW.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'RAMO_CONCEPTO_COMISION', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCONCEPTO <> :OLD.CODCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'CODCONCEPTO', TO_CHAR(:OLD.CODCONCEPTO), TO_CHAR(:NEW.CODCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODTIPO <> :OLD.CODTIPO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'CODTIPO', TO_CHAR(:OLD.CODTIPO), TO_CHAR(:NEW.CODTIPO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORIGEN <> :OLD.ORIGEN) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'ORIGEN', TO_CHAR(:OLD.ORIGEN), TO_CHAR(:NEW.ORIGEN), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODTIPOPLAN <> :OLD.CODTIPOPLAN) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO||' CODTIPO: '||:OLD.CODTIPO||' IDTIPOSEG: '||:OLD.IDTIPOSEG;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'RAMO_CONCEPTO_COMISION', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de RAMO_CONCEPTO_COMISION, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_RAMO_CONCEPTO_COMISION FOR SICAS_OC.TRG_RAMO_CONCEPTO_COMISION;
