CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CONFIG_PLANTILLAS_TABLAS
  BEFORE INSERT OR UPDATE OR DELETE ON CONFIG_PLANTILLAS_TABLAS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CONFIG_PLANTILLAS_TABLAS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODPLANTILLA)||' - '||TO_CHAR(:OLD.NOMTABLA)||' - '||TO_CHAR(:OLD.ORDENPROCESO)||' - '||
                  TO_CHAR(:OLD.TIPOTABLA)||' - '||TO_CHAR(:OLD.WHERETABLA)||' - '||TO_CHAR(:OLD.ORDENCAMPOS)||' - '||TO_CHAR(:OLD.TIPOACCION)||' - '||TO_CHAR(:OLD.CODRUTINA);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODPLANTILLA)||' - '||TO_CHAR(:NEW.NOMTABLA)||' - '||TO_CHAR(:NEW.ORDENPROCESO)||' - '||
                  TO_CHAR(:NEW.TIPOTABLA)||' - '||TO_CHAR(:NEW.WHERETABLA)||' - '||TO_CHAR(:NEW.ORDENCAMPOS)||' - '||TO_CHAR(:NEW.TIPOACCION)||' - '||TO_CHAR(:NEW.CODRUTINA);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPLANTILLA <> :OLD.CODPLANTILLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'CODPLANTILLA', TO_CHAR(:OLD.CODPLANTILLA), TO_CHAR(:NEW.CODPLANTILLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.NOMTABLA <> :OLD.NOMTABLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'NOMTABLA', TO_CHAR(:OLD.NOMTABLA), TO_CHAR(:NEW.NOMTABLA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.ORDENPROCESO <> :OLD.ORDENPROCESO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'ORDENPROCESO', TO_CHAR(:OLD.ORDENPROCESO), TO_CHAR(:NEW.ORDENPROCESO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOTABLA <> :OLD.TIPOTABLA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'TIPOTABLA', TO_CHAR(:OLD.TIPOTABLA), TO_CHAR(:NEW.TIPOTABLA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.WHERETABLA,-20000) <> NVL(:OLD.WHERETABLA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'WHERETABLA', TO_CHAR(:OLD.WHERETABLA), TO_CHAR(:NEW.WHERETABLA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDENCAMPOS,-20000) <> NVL(:OLD.ORDENCAMPOS,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'ORDENCAMPOS', TO_CHAR(:OLD.ORDENCAMPOS), TO_CHAR(:NEW.ORDENCAMPOS), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.TIPOACCION <> :OLD.TIPOACCION) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'TIPOACCION', TO_CHAR(:OLD.TIPOACCION), TO_CHAR(:NEW.TIPOACCION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODRUTINA,-20000) <> NVL(:OLD.CODRUTINA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODPLANTILLA: '||:OLD.CODPLANTILLA||' NOMTABLA: '||:OLD.NOMTABLA;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CONFIG_PLANTILLAS_TABLAS', 'CODRUTINA', TO_CHAR(:OLD.CODRUTINA), TO_CHAR(:NEW.CODRUTINA), 'UPDATE',vl_Primary);
    END IF;
    
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CONFIG_PLANTILLAS_TABLAS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CONFIG_PLANTILLAS_TABLAS FOR SICAS_OC.TRG_CONFIG_PLANTILLAS_TABLAS;
