CREATE OR REPLACE TRIGGER SICAS_OC.TRG_COLONIA
  BEFORE INSERT OR UPDATE OR DELETE ON COLONIA
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA COLONIA
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODPAIS)||' - '||TO_CHAR(:OLD.CODESTADO)||' - '||TO_CHAR(:OLD.CODCIUDAD)||' - '||TO_CHAR(:OLD.CODMUNICIPIO)||' - '||TO_CHAR(:OLD.CODIGO_POSTAL)||' - '||TO_CHAR(:OLD.CODIGO_COLONIA)||' - '||TO_CHAR(:OLD.DESCRIPCION_COLONIA);
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODPAIS)||' - '||TO_CHAR(:NEW.CODESTADO)||' - '||TO_CHAR(:NEW.CODCIUDAD)||' - '||TO_CHAR(:NEW.CODMUNICIPIO)||' - '||TO_CHAR(:NEW.CODIGO_POSTAL)||' - '||TO_CHAR(:NEW.CODIGO_COLONIA)||' - '||TO_CHAR(:OLD.DESCRIPCION_COLONIA);
      vl_Primary := 'CODPAIS: '||:NEW.CODPAIS ||' CODESTADO: '||:NEW.CODESTADO||' CODCIUDAD: '||:NEW.CODCIUDAD ||' CODMUNICIPIO: '||:NEW.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODPAIS <> :OLD.CODPAIS) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODPAIS', TO_CHAR(:OLD.CODPAIS), TO_CHAR(:NEW.CODPAIS), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODESTADO <> :OLD.CODESTADO) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODESTADO', TO_CHAR(:OLD.CODESTADO), TO_CHAR(:NEW.CODESTADO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCIUDAD <> :OLD.CODCIUDAD) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODCIUDAD', TO_CHAR(:OLD.CODCIUDAD), TO_CHAR(:NEW.CODCIUDAD), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODMUNICIPIO <> :OLD.CODMUNICIPIO) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODMUNICIPIO', TO_CHAR(:OLD.CODMUNICIPIO), TO_CHAR(:NEW.CODMUNICIPIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODIGO_POSTAL <> :OLD.CODIGO_POSTAL) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODIGO_POSTAL', TO_CHAR(:OLD.CODIGO_POSTAL), TO_CHAR(:NEW.CODIGO_POSTAL), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODIGO_COLONIA <> :OLD.CODIGO_COLONIA) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'CODMUNICIPIO', TO_CHAR(:OLD.CODMUNICIPIO), TO_CHAR(:NEW.CODIGO_COLONIA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.DESCRIPCION_COLONIA,-20000) <> NVL(:OLD.DESCRIPCION_COLONIA,-20000)) THEN
      vl_Primary := 'CODPAIS: '||:OLD.CODPAIS ||' CODESTADO: '||:OLD.CODESTADO||' CODCIUDAD: '||:OLD.CODCIUDAD ||' CODMUNICIPIO: '||:OLD.CODMUNICIPIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(1, 'COLONIA', 'DESCRIPCION_COLONIA', TO_CHAR(:OLD.DESCRIPCION_COLONIA), TO_CHAR(:NEW.DESCRIPCION_COLONIA), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de COLONIA, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_COLONIA FOR SICAS_OC.TRG_COLONIA;
