CREATE OR REPLACE TRIGGER SICAS_OC.TRG_CATALOGO_DE_CONCEPTOS
  BEFORE INSERT OR UPDATE OR DELETE ON CATALOGO_DE_CONCEPTOS
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA CATALOGO_DE_CONCEPTOS
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODCONCEPTO)||' - '||TO_CHAR(:OLD.DESCRIPCONCEPTO)||' - '||TO_CHAR(:OLD.INDTIPOCONCEPTO)||' - '||TO_CHAR(:OLD.PORCCONCEPTO)||' - '||TO_CHAR(:OLD.MONTOCONCEPTO)||' - '||
                  TO_CHAR(:OLD.RUTINACALCULO)||' - '||TO_CHAR(:OLD.INDCPTOPRIMAS)||' - '||TO_CHAR(:OLD.INDCPTOAJUSTE)||' - '||TO_CHAR(:OLD.INDREDONDEO)||' - '||TO_CHAR(:OLD.INDCONTABREDONDEO)||' - '||TO_CHAR(:OLD.CODCPTODEUDOR)||' - '||
                  TO_CHAR(:OLD.CODCPTOACREEDOR)||' - '||TO_CHAR(:OLD.CODUSUARIO)||' - '||TO_CHAR(:OLD.FECULTCAMBIO)||' - '||TO_CHAR(:OLD.INDCPTOSERVICIO)||' - '||TO_CHAR(:OLD.INDCALCRESERVA)||' - '||TO_CHAR(:OLD.INDCPTOREASEG)||' - '||
                  TO_CHAR(:OLD.INDRANGOSTIPSEG)||' - '||TO_CHAR(:OLD.INDAPLICACOMISION)||' - '||TO_CHAR(:OLD.INDCPTOSINI)||' - '||TO_CHAR(:OLD.ORDEN_IMPRESION)||' - '||TO_CHAR(:OLD.SIGNO_CONCEPTO)||' - '||TO_CHAR(:OLD.INDESIMPUESTO)||' - '||
                  TO_CHAR(:OLD.CODCPTOPRIMASFACTELECT)||' - '||TO_CHAR(:OLD.INDCPTOFONDO)||' - '||TO_CHAR(:OLD.INDCPTOPRESTAMO)||' - '||TO_CHAR(:OLD.INDGENERAIVA)||' - '||TO_CHAR(:OLD.CODTIPOPLAN);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODCONCEPTO)||' - '||TO_CHAR(:NEW.DESCRIPCONCEPTO)||' - '||TO_CHAR(:NEW.INDTIPOCONCEPTO)||' - '||TO_CHAR(:NEW.PORCCONCEPTO)||' - '||TO_CHAR(:NEW.MONTOCONCEPTO)||' - '||
                  TO_CHAR(:NEW.RUTINACALCULO)||' - '||TO_CHAR(:NEW.INDCPTOPRIMAS)||' - '||TO_CHAR(:NEW.INDCPTOAJUSTE)||' - '||TO_CHAR(:NEW.INDREDONDEO)||' - '||TO_CHAR(:NEW.INDCONTABREDONDEO)||' - '||TO_CHAR(:NEW.CODCPTODEUDOR)||' - '||
                  TO_CHAR(:NEW.CODCPTOACREEDOR)||' - '||TO_CHAR(:NEW.CODUSUARIO)||' - '||TO_CHAR(:NEW.FECULTCAMBIO)||' - '||TO_CHAR(:NEW.INDCPTOSERVICIO)||' - '||TO_CHAR(:NEW.INDCALCRESERVA)||' - '||TO_CHAR(:NEW.INDCPTOREASEG)||' - '||
                  TO_CHAR(:NEW.INDRANGOSTIPSEG)||' - '||TO_CHAR(:NEW.INDAPLICACOMISION)||' - '||TO_CHAR(:NEW.INDCPTOSINI)||' - '||TO_CHAR(:NEW.ORDEN_IMPRESION)||' - '||TO_CHAR(:NEW.SIGNO_CONCEPTO)||' - '||TO_CHAR(:NEW.INDESIMPUESTO)||' - '||
                  TO_CHAR(:NEW.CODCPTOPRIMASFACTELECT)||' - '||TO_CHAR(:NEW.INDCPTOFONDO)||' - '||TO_CHAR(:NEW.INDCPTOPRESTAMO)||' - '||TO_CHAR(:NEW.INDGENERAIVA)||' - '||TO_CHAR(:NEW.CODTIPOPLAN);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODCONCEPTO: '||:NEW.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODCONCEPTO <> :OLD.CODCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODCONCEPTO', TO_CHAR(:OLD.CODCONCEPTO), TO_CHAR(:NEW.CODCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCRIPCONCEPTO <> :OLD.DESCRIPCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'DESCRIPCONCEPTO', TO_CHAR(:OLD.DESCRIPCONCEPTO), TO_CHAR(:NEW.DESCRIPCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDTIPOCONCEPTO <> :OLD.INDTIPOCONCEPTO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDTIPOCONCEPTO', TO_CHAR(:OLD.INDTIPOCONCEPTO), TO_CHAR(:NEW.INDTIPOCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.PORCCONCEPTO,-20000) <> NVL(:OLD.PORCCONCEPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'PORCCONCEPTO', TO_CHAR(:OLD.PORCCONCEPTO), TO_CHAR(:NEW.PORCCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.MONTOCONCEPTO,-20000) <> NVL(:OLD.MONTOCONCEPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'MONTOCONCEPTO', TO_CHAR(:OLD.MONTOCONCEPTO), TO_CHAR(:NEW.MONTOCONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.RUTINACALCULO,-20000) <> NVL(:OLD.RUTINACALCULO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'RUTINACALCULO', TO_CHAR(:OLD.RUTINACALCULO), TO_CHAR(:NEW.RUTINACALCULO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDCPTOPRIMAS <> :OLD.INDCPTOPRIMAS) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOPRIMAS', TO_CHAR(:OLD.INDCPTOPRIMAS), TO_CHAR(:NEW.INDCPTOPRIMAS), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDCPTOAJUSTE <> :OLD.INDCPTOAJUSTE) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOAJUSTE', TO_CHAR(:OLD.INDCPTOAJUSTE), TO_CHAR(:NEW.INDCPTOAJUSTE), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDREDONDEO <> :OLD.INDREDONDEO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDREDONDEO', TO_CHAR(:OLD.INDREDONDEO), TO_CHAR(:NEW.INDREDONDEO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.INDCONTABREDONDEO <> :OLD.INDCONTABREDONDEO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCONTABREDONDEO', TO_CHAR(:OLD.INDCONTABREDONDEO), TO_CHAR(:NEW.INDCONTABREDONDEO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCPTODEUDOR,-20000) <> NVL(:OLD.CODCPTODEUDOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODCPTODEUDOR', TO_CHAR(:OLD.CODCPTODEUDOR), TO_CHAR(:NEW.CODCPTODEUDOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCPTOACREEDOR,-20000) <> NVL(:OLD.CODCPTOACREEDOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODCPTOACREEDOR', TO_CHAR(:OLD.CODCPTOACREEDOR), TO_CHAR(:NEW.CODCPTOACREEDOR), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,-20000) <> NVL(:OLD.CODUSUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FECULTCAMBIO,SYSDATE) <> NVL(:OLD.FECULTCAMBIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'FECULTCAMBIO', TO_CHAR(:OLD.FECULTCAMBIO), TO_CHAR(:NEW.FECULTCAMBIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCPTOSERVICIO,-20000) <> NVL(:OLD.INDCPTOSERVICIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOSERVICIO', TO_CHAR(:OLD.INDCPTOSERVICIO), TO_CHAR(:NEW.INDCPTOSERVICIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCALCRESERVA,-20000) <> NVL(:OLD.INDCALCRESERVA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCALCRESERVA', TO_CHAR(:OLD.INDCALCRESERVA), TO_CHAR(:NEW.INDCALCRESERVA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCPTOREASEG,-20000) <> NVL(:OLD.INDCPTOREASEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOSERVICIO', TO_CHAR(:OLD.INDCPTOREASEG), TO_CHAR(:NEW.INDCPTOREASEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDRANGOSTIPSEG,-20000) <> NVL(:OLD.INDRANGOSTIPSEG,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDRANGOSTIPSEG', TO_CHAR(:OLD.INDRANGOSTIPSEG), TO_CHAR(:NEW.INDRANGOSTIPSEG), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDAPLICACOMISION,-20000) <> NVL(:OLD.INDAPLICACOMISION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDAPLICACOMISION', TO_CHAR(:OLD.INDAPLICACOMISION), TO_CHAR(:NEW.INDAPLICACOMISION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCPTOSINI,-20000) <> NVL(:OLD.INDCPTOSINI,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOSINI', TO_CHAR(:OLD.INDCPTOSINI), TO_CHAR(:NEW.INDCPTOSINI), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ORDEN_IMPRESION,-20000) <> NVL(:OLD.ORDEN_IMPRESION,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'ORDEN_IMPRESION', TO_CHAR(:OLD.ORDEN_IMPRESION), TO_CHAR(:NEW.ORDEN_IMPRESION), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.SIGNO_CONCEPTO,-20000) <> NVL(:OLD.SIGNO_CONCEPTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'SIGNO_CONCEPTO', TO_CHAR(:OLD.SIGNO_CONCEPTO), TO_CHAR(:NEW.SIGNO_CONCEPTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDESIMPUESTO,-20000) <> NVL(:OLD.INDESIMPUESTO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDESIMPUESTO', TO_CHAR(:OLD.INDESIMPUESTO), TO_CHAR(:NEW.INDESIMPUESTO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODCPTOPRIMASFACTELECT,-20000) <> NVL(:OLD.CODCPTOPRIMASFACTELECT,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODCPTOPRIMASFACTELECT', TO_CHAR(:OLD.CODCPTOPRIMASFACTELECT), TO_CHAR(:NEW.CODCPTOPRIMASFACTELECT), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCPTOFONDO,-20000) <> NVL(:OLD.INDCPTOFONDO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOFONDO', TO_CHAR(:OLD.INDCPTOFONDO), TO_CHAR(:NEW.INDCPTOFONDO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDCPTOPRESTAMO,-20000) <> NVL(:OLD.INDCPTOPRESTAMO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDCPTOPRESTAMO', TO_CHAR(:OLD.INDCPTOPRESTAMO), TO_CHAR(:NEW.INDCPTOPRESTAMO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.INDGENERAIVA,-20000) <> NVL(:OLD.INDGENERAIVA,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'INDGENERAIVA', TO_CHAR(:OLD.INDGENERAIVA), TO_CHAR(:NEW.INDGENERAIVA), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODTIPOPLAN,-20000) <> NVL(:OLD.CODTIPOPLAN,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODCONCEPTO: '||:OLD.CODCONCEPTO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'CATALOGO_DE_CONCEPTOS', 'CODTIPOPLAN', TO_CHAR(:OLD.CODTIPOPLAN), TO_CHAR(:NEW.CODTIPOPLAN), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de CATALOGO_DE_CONCEPTOS, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_CATALOGO_DE_CONCEPTOS FOR SICAS_OC.TRG_CATALOGO_DE_CONCEPTOS;
