CREATE OR REPLACE TRIGGER SICAS_OC.TRG_UNIDADES_DE_NEGOCIO
  BEFORE INSERT OR UPDATE OR DELETE ON UNIDADES_DE_NEGOCIO
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA UNIDADES_DE_NEGOCIO
    FECHA CREACIÓN: 22/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */

  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.CODUNIDADNEGOCIO)||' - '||TO_CHAR(:OLD.DESCUNIDADNEGOCIO)||' - '||TO_CHAR(:OLD.NIVELUNIDADNEGOCIO)||' - '||
                  TO_CHAR(:OLD.STSUNIDADNEGOCIO)||' - '||TO_CHAR(:OLD.FECSTS)||' - '||TO_CHAR(:OLD.CODUSUARIO);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;

  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.CODUNIDADNEGOCIO)||' - '||TO_CHAR(:NEW.DESCUNIDADNEGOCIO)||' - '||TO_CHAR(:NEW.NIVELUNIDADNEGOCIO)||' - '||
                  TO_CHAR(:NEW.STSUNIDADNEGOCIO)||' - '||TO_CHAR(:NEW.FECSTS)||' - '||TO_CHAR(:NEW.CODUSUARIO); 
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' CODUNIDADNEGOCIO: '||:NEW.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'UNIDADES_DE_NEGOCIO', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODUNIDADNEGOCIO <> :OLD.CODUNIDADNEGOCIO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'CODUNIDADNEGOCIO', TO_CHAR(:OLD.CODUNIDADNEGOCIO), TO_CHAR(:NEW.CODUNIDADNEGOCIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.DESCUNIDADNEGOCIO <> :OLD.DESCUNIDADNEGOCIO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'DESCUNIDADNEGOCIO', TO_CHAR(:OLD.DESCUNIDADNEGOCIO), TO_CHAR(:NEW.DESCUNIDADNEGOCIO), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.NIVELUNIDADNEGOCIO,-20000) <> NVL(:OLD.NIVELUNIDADNEGOCIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'NIVELUNIDADNEGOCIO', TO_CHAR(:OLD.NIVELUNIDADNEGOCIO), TO_CHAR(:NEW.NIVELUNIDADNEGOCIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.STSUNIDADNEGOCIO <> :OLD.STSUNIDADNEGOCIO) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'STSUNIDADNEGOCIO', TO_CHAR(:OLD.STSUNIDADNEGOCIO), TO_CHAR(:NEW.STSUNIDADNEGOCIO), 'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.FECSTS <> :OLD.FECSTS) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.CODUSUARIO,SYSDATE) <> NVL(:OLD.CODUSUARIO,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' CODUNIDADNEGOCIO: '||:OLD.CODUNIDADNEGOCIO;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'UNIDADES_DE_NEGOCIO', 'CODUSUARIO', TO_CHAR(:OLD.CODUSUARIO), TO_CHAR(:NEW.CODUSUARIO), 'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de UNIDADES_DE_NEGOCIO, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_UNIDADES_DE_NEGOCIO FOR SICAS_OC.TRG_UNIDADES_DE_NEGOCIO;
