CREATE OR REPLACE TRIGGER SICAS_OC.TRG_FACTOR_REGION
  BEFORE INSERT OR UPDATE OR DELETE ON FACTOR_REGION
  FOR EACH ROW 
DECLARE
    vl_Texto    VARCHAR2(4000);
    vl_Primary  VARCHAR2(2000);
    vl_ErrorN   NUMBER;
    vl_ErrorC   VARCHAR2(4000);
BEGIN
  /*TRIGGER PARA MONITOREO DE LA TABLA FACTOR_REGION
    FECHA CREACIÓN: 12/06/2023
    MODIFICO: LUIS ARGENIS REYNOSO ALVAREZ
  */
  IF DELETING THEN 
      vl_Texto := TO_CHAR(:OLD.CODCIA)||' - '||TO_CHAR(:OLD.CODEMPRESA)||' - '||TO_CHAR(:OLD.IDTIPOSEG)||' - '||TO_CHAR(:OLD.PLANCOB)||' - '||TO_CHAR(:OLD.CODPAQUETE)||' - '||
                  TO_CHAR(:OLD.CODREGION)||' - '||TO_CHAR(:OLD.FACTOR)||' - '||TO_CHAR(:OLD.TEXTOFACTOR)||' - '||TO_CHAR(:OLD.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:OLD.ACTUALIZO_FECHA);
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'SE ELIMINA TODO EL REGISTRO', vl_Texto, 'REGISTRO ELIMINADO', 'DELETE',vl_Primary);
  END IF;
 
  IF INSERTING THEN 
      vl_Texto := TO_CHAR(:NEW.CODCIA)||' - '||TO_CHAR(:NEW.CODEMPRESA)||' - '||TO_CHAR(:NEW.IDTIPOSEG)||' - '||TO_CHAR(:NEW.PLANCOB)||' - '||TO_CHAR(:NEW.CODPAQUETE)||' - '||
                  TO_CHAR(:NEW.CODREGION)||' - '||TO_CHAR(:NEW.FACTOR)||' - '||TO_CHAR(:NEW.TEXTOFACTOR)||' - '||TO_CHAR(:NEW.ACTUALIZO_USUARIO)||' - '||TO_CHAR(:new.ACTUALIZO_FECHA);
      vl_Primary := 'CODCIA: '||:NEW.CODCIA||' CODEMPRESA: '||:NEW.CODEMPRESA||' IDTIPOSEG: '||:NEW.IDTIPOSEG||' PLANCOB: '||:NEW.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:NEW.CODCIA, 'FACTOR_REGION', 'SE AGREGA NUEVO REGISTRO', vl_Texto, 'NUEVO REGISTRO', 'INSERT',vl_Primary);
  END IF;

  IF UPDATING THEN 
    IF (:NEW.CODCIA <> :OLD.CODCIA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'CODCIA', TO_CHAR(:OLD.CODCIA), TO_CHAR(:NEW.CODCIA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODEMPRESA <> :OLD.CODEMPRESA) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'CODEMPRESA', TO_CHAR(:OLD.CODEMPRESA), TO_CHAR(:NEW.CODEMPRESA),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.IDTIPOSEG <> :OLD.IDTIPOSEG) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'IDTIPOSEG', TO_CHAR(:OLD.IDTIPOSEG), TO_CHAR(:NEW.IDTIPOSEG),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.PLANCOB <> :OLD.PLANCOB) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'PLANCOB', TO_CHAR(:OLD.PLANCOB), TO_CHAR(:NEW.PLANCOB),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODPAQUETE <> :OLD.CODPAQUETE) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'CODPAQUETE', TO_CHAR(:OLD.CODPAQUETE), TO_CHAR(:NEW.CODPAQUETE),'UPDATE',vl_Primary);
    END IF;
    IF (:NEW.CODREGION <> :OLD.CODREGION) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'CODREGION', TO_CHAR(:OLD.CODREGION), TO_CHAR(:NEW.CODREGION),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.FACTOR,-20000) <> NVL(:OLD.FACTOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'FACTOR', TO_CHAR(:OLD.FACTOR), TO_CHAR(:NEW.FACTOR),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.TEXTOFACTOR,-20000) <> NVL(:OLD.TEXTOFACTOR,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'TEXTOFACTOR', TO_CHAR(:OLD.TEXTOFACTOR), TO_CHAR(:NEW.TEXTOFACTOR),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_USUARIO,-20000) <> NVL(:OLD.ACTUALIZO_USUARIO,-20000)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'ACTUALIZO_USUARIO', TO_CHAR(:OLD.ACTUALIZO_USUARIO), TO_CHAR(:NEW.ACTUALIZO_USUARIO),'UPDATE',vl_Primary);
    END IF;
    IF (NVL(:NEW.ACTUALIZO_FECHA,SYSDATE) <> NVL(:OLD.ACTUALIZO_FECHA,SYSDATE)) THEN
      vl_Primary := 'CODCIA: '||:OLD.CODCIA||' CODEMPRESA: '||:OLD.CODEMPRESA||' IDTIPOSEG: '||:OLD.IDTIPOSEG||' PLANCOB: '||:OLD.PLANCOB;
      OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.CODCIA, 'FACTOR_REGION', 'ACTUALIZO_FECHA', TO_CHAR(:OLD.ACTUALIZO_FECHA), TO_CHAR(:NEW.ACTUALIZO_FECHA),'UPDATE',vl_Primary);
    END IF;
  END IF;    

EXCEPTION
    WHEN OTHERS THEN 
      vl_ErrorN := SQLCODE;
      vl_ErrorC := 'Error con el disparador de FACTOR_REGION, Contacte al administrador. '||SQLERRM;
      raise_application_error( -20000,vl_ErrorC);
END;
/

CREATE OR REPLACE PUBLIC SYNONYM TRG_FACTOR_REGION FOR SICAS_OC.TRG_FACTOR_REGION;
