--
-- TRG_ACTUALIZA_COBERT_SINI_ASEG  (Trigger) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DUAL (Synonym)
--   LOG_TRANSACCION (Table)
--   SQ_LOGTRANSACC (Sequence)
--   POLIZAS (Table)
--   COBERTURA_SINIESTRO_ASEG (Table)
--
CREATE OR REPLACE TRIGGER SICAS_OC.TRG_ACTUALIZA_COBERT_SINI_ASEG 
 BEFORE UPDATE ON SICAS_OC.COBERTURA_SINIESTRO_ASEG
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
nMaxTransaccion   LOG_TRANSACCION.Id_Transaccion%TYPE;
cCodCia           POLIZAS.CodCia%TYPE;
cIP               VARCHAR2(20);
cUsuario          VARCHAR2(30);
cTexto            VARCHAR2(4000) := 'DATOS MODIFICADOS: ';
BEGIN
  --
  SELECT SQ_LOGTRANSACC.NEXTVAL
    INTO nMaxTransaccion
    FROM DUAL;
  --
  SELECT USER
    INTO cUsuario
    FROM DUAL;
  --
  SELECT SYS_CONTEXT ('USERENV', 'IP_ADDRESS')
    INTO cIP
    FROM DUAL;
  --
  IF :NEW.IDDETSIN != :OLD.IDDETSIN THEN
     cTexto := cTexto||' - '|| 'IDDETSIN: '||:NEW.IDDETSIN;
  END IF;
  IF :NEW.CODCOBERT != :OLD.CODCOBERT THEN
     cTexto := cTexto||' - '|| 'CODCOBERT: '||:NEW.CODCOBERT;
  END IF;
  IF :NEW.IDSINIESTRO != :OLD.IDSINIESTRO THEN
     cTexto := cTexto||' - '|| 'IDSINIESTRO: '||:NEW.IDSINIESTRO;
  END IF;
  IF :NEW.IDPOLIZA != :OLD.IDPOLIZA THEN
     cTexto := cTexto||' - '|| 'IDPOLIZA: '||:NEW.IDPOLIZA;
  END IF;
  IF :NEW.COD_ASEGURADO != :OLD.COD_ASEGURADO THEN
     cTexto := cTexto||' - '|| 'COD_ASEGURADO: '||:NEW.COD_ASEGURADO;
  END IF;
  IF :NEW.DOC_REF_PAGO != :OLD.DOC_REF_PAGO THEN
     cTexto := cTexto||' - '|| 'DOC_REF_PAGO: '||:NEW.DOC_REF_PAGO;
  END IF;
  IF :NEW.MONTO_PAGADO_MONEDA != :OLD.MONTO_PAGADO_MONEDA THEN
     cTexto := cTexto||' - '|| 'MONTO_PAGADO_MONEDA: '||:NEW.MONTO_PAGADO_MONEDA;
  END IF;
  IF :NEW.MONTO_PAGADO_LOCAL != :OLD.MONTO_PAGADO_LOCAL THEN
     cTexto := cTexto||' - '|| 'MONTO_PAGADO_LOCAL: '||:NEW.MONTO_PAGADO_LOCAL;
  END IF;
  IF :NEW.MONTO_RESERVADO_MONEDA != :OLD.MONTO_RESERVADO_MONEDA THEN
     cTexto := cTexto||' - '|| 'MONTO_RESERVADO_MONEDA: '||:NEW.MONTO_RESERVADO_MONEDA;
  END IF;
  IF :NEW.MONTO_RESERVADO_LOCAL != :OLD.MONTO_RESERVADO_LOCAL THEN
     cTexto := cTexto||' - '|| 'MONTO_RESERVADO_LOCAL: '||:NEW.MONTO_RESERVADO_LOCAL;
  END IF;
  IF :NEW.STSCOBERTURA != :OLD.STSCOBERTURA THEN
     cTexto := cTexto||' - '|| 'STSCOBERTURA: '||:NEW.STSCOBERTURA;
  END IF;
  IF :NEW.NUMMOD != :OLD.NUMMOD THEN
     cTexto := cTexto||' - '|| 'NUMMOD: '||:NEW.NUMMOD;
  END IF;
  IF :NEW.CODTRANSAC != :OLD.CODTRANSAC THEN
     cTexto := cTexto||' - '|| 'CODTRANSAC: '||:NEW.CODTRANSAC;
  END IF;
  IF :NEW.CODCPTOTRANSAC != :OLD.CODCPTOTRANSAC THEN
     cTexto := cTexto||' - '|| 'CODCPTOTRANSAC: '||:NEW.CODCPTOTRANSAC;
  END IF;
  IF :NEW.IDTRANSACCION != :OLD.IDTRANSACCION THEN
     cTexto := cTexto||' - '|| 'IDTRANSACCION: '||:NEW.IDTRANSACCION;
  END IF;
  IF :NEW.SALDO_RESERVA != :OLD.SALDO_RESERVA THEN
     cTexto := cTexto||' - '|| 'SALDO_RESERVA: '||:NEW.SALDO_RESERVA;
  END IF;
  IF :NEW.INDORIGEN != :OLD.INDORIGEN THEN
     cTexto := cTexto||' - '|| 'INDORIGEN: '||:NEW.INDORIGEN;
  END IF;
  IF :NEW.FECRES != :OLD.FECRES THEN
     cTexto := cTexto||' - '|| 'FECRES: '||:NEW.FECRES;
  END IF;
  IF :NEW.SALDO_RESERVA_LOCAL != :OLD.SALDO_RESERVA_LOCAL THEN
     cTexto := cTexto||' - '|| 'SALDO_RESERVA_LOCAL: '||:NEW.SALDO_RESERVA_LOCAL;
  END IF;
  IF :NEW.IDTRANSACCIONANUL != :OLD.IDTRANSACCIONANUL THEN
     cTexto := cTexto||' - '|| 'IDTRANSACCIONANUL: '||:NEW.IDTRANSACCIONANUL;
  END IF;
  --
  INSERT INTO LOG_TRANSACCION
        (Id_Transaccion, CodCia, Id_Referencia, Fecha_Transaccion, Direccion_IP,
         Num_Referencia, Origen_Transaccion, Desc_Movimiento, CodUsuario)
  VALUES(nMaxtransaccion, 1, 'COBERTURA_SINIESTRO_ASEG ' || :NEW.IdSiniestro, SYSDATE, cIP,
         :NEW.IdSiniestro||'-'||:NEW.CodCobert||'-'||:NEW.NumMod, 'MODIFICA COBERTURA_SINIESTRO_ASEG', SUBSTR(cTexto,1,1000), cUsuario);
END;
/
