CREATE OR REPLACE TRIGGER TRG_UP_FACT_ELECT_FORMA_PAGO
BEFORE UPDATE
ON FACT_ELECT_FORMA_PAGO
FOR EACH ROW

 BEGIN

  IF :NEW.IDFORMAPAGO != :OLD.IDFORMAPAGO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'IDFORMAPAGO', TO_CHAR(:OLD.IDFORMAPAGO), TO_CHAR(:NEW.IDFORMAPAGO), 'UPDATE');

  END IF;

  IF :NEW.CODFORMAPAGO != :OLD.CODFORMAPAGO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'CODFORMAPAGO', :OLD.CODFORMAPAGO, :NEW.CODFORMAPAGO, 'UPDATE');

  END IF;

  IF :NEW.CODFORMAPAGOFE != :OLD.CODFORMAPAGOFE THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'CODFORMAPAGOFE', :OLD.CODFORMAPAGOFE, :NEW.CODFORMAPAGOFE, 'UPDATE');

  END IF;

  IF :NEW.FECINIVIG != :OLD.FECINIVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'FECINIVIG', TO_CHAR(:OLD.FECINIVIG), TO_CHAR(:NEW.FECINIVIG), 'UPDATE');

  END IF;

  IF :NEW.FECFINVIG != :OLD.FECFINVIG THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'FECFINVIG', TO_CHAR(:OLD.FECFINVIG), TO_CHAR(:NEW.FECFINVIG), 'UPDATE');

  END IF;

  IF :NEW.CODUSUARIO != :OLD.CODUSUARIO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'CODUSUARIO', :OLD.CODUSUARIO, :NEW.CODUSUARIO, 'UPDATE');

  END IF;

  IF :NEW.STSFORMAPAGO != :OLD.STSFORMAPAGO THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'STSFORMAPAGO', :OLD.STSFORMAPAGO, :NEW.STSFORMAPAGO, 'UPDATE');

  END IF;

  IF :NEW.FECSTS != :OLD.FECSTS THEN

     OC_LOG_CONF_FACT_ELECT.INSERTA(:OLD.codcia, 'FACT_ELECT_FORMA_PAGO', 'FECSTS', TO_CHAR(:OLD.FECSTS), TO_CHAR(:NEW.FECSTS), 'UPDATE');

  END IF;

 END TRG_UP_FACT_ELECT_FORMA_PAGO;