Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '03', '04', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES AGENTES P.FISICAS', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '05', '04', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES AGENTES P.MORALES', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '09', '39', 
    '10', '8606', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'HONORARIOS', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8614', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIADI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIADI', '6', '1', '01', '02', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'MADI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'MADI', '6', '1', '01', '02', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'DEREMI', '6', '5', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'DERECHOS POL. PMAS X COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'DEREMI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'RECFIN', '2', '7', '04', '00', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS X COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'RECFIN', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '09', '39', 
    '10', '8607', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '02', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES X DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '01', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES X DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '100', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'100'), 1, 'VIFLEX', 
    'PRIBAS', '6', '1', '01', '02', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '5', '3', '09', '39', 
    '10', '8607', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '2', '1', '33', '02', 
    '10', 'D', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '02', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES POR DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '22', '01', 
    '10', 'C', 'CO', '5.1300-02-001', '002', 
    'FISICA', 'AGENTES CUENTA CORRIENTE', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '22', '02', 
    '10', 'C', 'CO', '5.1300-02-001', '002', 
    'MORAL', 'AGENTES CUENTA CORRIENTE', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '01', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES POR DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8617', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR PAG PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8616', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR PAG PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8614', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '6', '1', '01', '02', 
    '10', '2345', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '02', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES X DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '01', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES X DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '05', '04', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES AGENTES P.MORALES', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '03', '04', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES AGENTES P.FISICAS', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '6', '1', '01', '02', 
    '10', '1234', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '09', '39', 
    '10', '8606', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'HONORARIOS', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8614', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '09', '39', 
    '10', '8607', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOINI', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '2', '1', '33', '02', 
    '10', 'D', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '5', '3', '09', '39', 
    '10', '8607', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '6', '1', '01', '02', 
    '10', '2345', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'PMACOM', '2', '1', '33', '02', 
    '10', 'D', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1000', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1000'), 1, 'VIFLEX', 
    'APOADI', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '6', '1', '01', '02', 
    '10', '2345', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '5', '3', '09', '39', 
    '10', '8607', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '2', '1', '33', '02', 
    '10', 'C', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOADI', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '6', '1', '01', '02', 
    '10', '2345', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '5', '3', '09', '39', 
    '10', '8607', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '2', '1', '33', '02', 
    '10', 'C', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'APOINI', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '1', '33', '02', 
    '10', 'C', 'MO', '5.1300-02-001', '01111011008001001', 
    'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '09', '39', 
    '10', '8607', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8614', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '09', '39', 
    '10', '8606', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'HONORARIOS', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '6', '1', '01', '02', 
    '10', '1234', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '03', '04', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES AGENTES P.FISICAS', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '5', '3', '05', '04', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES AGENTES P.MORALES', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '01', '01', 
    '10', 'C', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '01', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES X DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '02', 
    '10', 'D', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES X DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '01', '01', 
    '10', 'D', 'MO', '5.1300-02-001', '001', 
    'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '02', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'MORAL', 'COMISIONES POR DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '22', '01', 
    '10', 'D', 'CO', '5.1300-02-001', '002', 
    'FISICA', 'AGENTES CUENTA CORRIENTE', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '1', '6', '22', '02', 
    '10', 'D', 'CO', '5.1300-02-001', '002', 
    'MORAL', 'AGENTES CUENTA CORRIENTE', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, CODUNIDADNEGOCIO, 
    TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '3', '03', '01', 
    '10', 'C', 'CO', '5.1300-02-001', '01111011008001001', 
    'FISICA', 'COMISIONES POR DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8617', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR PAG PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8616', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR PAG PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '1010', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'1010'), 1, 'VIFLEX', 
    'PMACOM', '2', '4', '08', '01', 
    '10', '8614', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'RECFIN', '2', '7', '04', '00', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS X COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'RECFIN', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '02', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES X DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '01', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES X DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '05', '04', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES AGENTES P.MORALES', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '03', '04', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES AGENTES P.FISICAS', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '6', '1', '01', '02', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '09', '39', 
    '10', '8606', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'HONORARIOS', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8614', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIBAS', '5', '3', '09', '39', 
    '10', '8607', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'HONORARIOS', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIADI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'PRIADI', '6', '1', '01', '02', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'MADI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'MADI', '6', '1', '01', '02', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'PRIMAS DEL SEGURO DIRECTO', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'DEREMI', '6', '5', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'DERECHOS POL. PMAS X COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '200', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'200'), 1, 'VIFLEX', 
    'DEREMI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'RECFIN', '6', '6', '20', '00', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'DEREMI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'RECFIN', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8614', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8616', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR PAG PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8615', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8617', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR PAG PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '01', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES POR DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '22', '02', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '002', 'MORAL', 'AGENTES CUENTA CORRIENTE', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '22', '01', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '002', 'FISICA', 'AGENTES CUENTA CORRIENTE', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '02', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES POR DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PRIADI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'PAGREC', '2', '1', '33', '02', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'MADI', '1', '6', '01', '01', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '300', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'300'), 1, 'VIFLEX', 
    'RECFIN', '2', '7', '04', '00', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS POR COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'RECFIN', '2', '7', '04', '00', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS POR COBRAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'RECFIN', '6', '6', '20', '00', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '01111011008001001', 'RECARGOS SOBRE PRIMAS', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'DEREMI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'MADI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PAGREC', '2', '1', '33', '02', 
    '10', '0', 'C', 'MO', '5.1300-02-001', 
    '01111011008001001', 'REMESAS POR APLICAR', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIADI', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '02', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'MORAL', 'COMISIONES POR DEVENGAR', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '22', '01', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '002', 'FISICA', 'AGENTES CUENTA CORRIENTE', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '22', '02', 
    '10', '0', 'D', 'CO', '5.1300-02-001', 
    '002', 'MORAL', 'AGENTES CUENTA CORRIENTE', 'AGTEPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '3', '03', '01', 
    '10', '0', 'C', 'CO', '5.1300-02-001', 
    '01111011008001001', 'FISICA', 'COMISIONES POR DEVENGAR', 'AGTEPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8617', 'D', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR PAG PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8615', 'C', 'CO', '5', 
    '000', 'MORAL', 'COMPENSACIONES POR DEV PM', 'HONPM', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8616', 'D', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR PAG PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, TIPOPERSONA, DESCCPTOGENERAL, TIPOAGENTE, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'PRIBAS', '2', '4', '08', '01', 
    '10', '8614', 'C', 'CO', '5', 
    '000', 'FISICA', 'COMPENSACIONES POR DEV PF', 'HONPF', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '310', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'310'), 1, 'VIFLEX', 
    'RECFIN', '1', '6', '01', '01', 
    '10', '0', 'D', 'MO', '5.1300-02-001', 
    '001', 'DEUDORES X PRIMAS DE A.P.', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '800', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'800'), 1, 'VIFLEX', 
    'PRIMDE', '2', '4', '08', '01', 
    '10', '8600', 'D', 'MO', '5', 
    'ACREEDORES DIVERSOS-LIQUIDADORA DE PAGOS', 'PS');
Insert into SICAS_OC.PLANTILLAS_CONTABLES
   (CODCIA, CODPROCESO, IDREGPLANTILLA, CODEMPRESA, IDTIPOSEG, 
    CODCPTO, NIVELCTA1, NIVELCTA2, NIVELCTA3, NIVELCTA4, 
    NIVELCTA5, NIVELAUX, REGDEBCRED, TIPOREGISTRO, CODCENTROCOSTO, 
    CODUNIDADNEGOCIO, DESCCPTOGENERAL, CODMONEDA)
 Values
   (1, '800', OC_PLANTILLAS_CONTABLES.NUMERO_REG_PLANTILLA(1,'800'), 1, 'VIFLEX', 
    'PRIMDE', '2', '1', '33', '02', 
    '10', '0', 'C', 'MO', '5', 
    '01111011008001001', 'PRIMAS EN DEPOSITO PENDIENTES DE APLICACION', 'PS');
