--
-- CONTABILIZA_FACTURAS_VIDA  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   OC_FACTURAS (Package)
--   EMPRESAS (Table)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.CONTABILIZA_FACTURAS_VIDA IS
CURSOR EMP_Q IS
   SELECT CodCia
     FROM EMPRESAS
    WHERE StsCia = 'ACT';
BEGIN
   FOR W IN EMP_Q LOOP
      OC_FACTURAS.CONTABILIZAR_FACTURAS(W.CodCia, TRUNC(SYSDATE));
      COMMIT;
   END LOOP;
END;
/

--
-- CONTABILIZA_FACTURAS_VIDA  (Synonym) 
--
--  Dependencies: 
--   CONTABILIZA_FACTURAS_VIDA (Procedure)
--
CREATE OR REPLACE PUBLIC SYNONYM CONTABILIZA_FACTURAS_VIDA FOR SICAS_OC.CONTABILIZA_FACTURAS_VIDA
/


GRANT EXECUTE ON SICAS_OC.CONTABILIZA_FACTURAS_VIDA TO PUBLIC
/
