PROCEDURE CONTABILIZA_FACTURAS_VIDA IS
CURSOR EMP_Q IS
   SELECT CodCia
     FROM EMPRESAS
    WHERE StsCia = 'ACT';
BEGIN
   FOR W IN EMP_Q LOOP
      OC_FACTURAS.CONTABILIZAR_FACTURAS(W.CodCia, TRUNC(SYSDATE));
      COMMIT;
   END LOOP;
END;
