--
-- DERIVACION_CONTABLE  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   GT_TABLERO_CONTROL_DERIVA (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.DERIVACION_CONTABLE IS
BEGIN
   GT_TABLERO_CONTROL_DERIVA.EJECUTA_PROCESO_WS_DERIVA(1, 1, NULL);
   COMMIT;
END;
/
