--
-- DERIVACION_CONTABLE  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   GT_TABLERO_CONTROL_DERIVA (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.DERIVACION_CONTABLE IS
BEGIN
   GT_TABLERO_CONTROL_DERIVA.EJECUTA_PROCESO_WS_DERIVA(1, 1, NULL);
   COMMIT;
END;
/

--
-- DERIVACION_CONTABLE  (Synonym) 
--
--  Dependencies: 
--   DERIVACION_CONTABLE (Procedure)
--
CREATE OR REPLACE PUBLIC SYNONYM DERIVACION_CONTABLE FOR SICAS_OC.DERIVACION_CONTABLE
/


GRANT EXECUTE ON SICAS_OC.DERIVACION_CONTABLE TO PUBLIC
/
