CREATE OR REPLACE PROCEDURE DEVENGAMIENTOAUTO AS
nCodCia     NUMBER := 1;
nCodEmpresa NUMBER := 1;
cSQL        VARCHAR2(200) := 'TRUNCATE TABLE POLIZA_PRIMA_DEVENGADA';
BEGIN
   EXECUTE IMMEDIATE cSQL;
   DBMS_OUTPUT.PUT_LINE('Inicio de Carga Inicial: '|| TO_CHAR(LOCALTIMESTAMP, 'DD/MM/RRRR HH:MI:SS AM'));
   OC_POLIZA_PRIMA_DEVENGADA.CARGA_PRIMA_DEVENGADA (nCodCia, nCodEmpresa, NULL);
    --DBMS_OUTPUT.PUT_LINE('Termine Carga Inicial y ahora Verifico tipo de Devengo: '|| TO_CHAR(LOCALTIMESTAMP, 'DD/MM/RRRR HH:MI:SS AM')); -->> No aplica para PROD
      --  OC_POLIZA_PRIMA_DEVENGADA.VERIFICA_TIPO_DEVENGO ('I', 1, 1, NULL);                                                                 -->> No aplica para PROD
   DBMS_OUTPUT.PUT_LINE('Termine: '|| TO_CHAR(LOCALTIMESTAMP, 'DD/MM/RRRR HH:MI:SS AM'));
   --COMMIT;
END DEVENGAMIENTOAUTO;
/
CREATE OR REPLACE PUBLIC SYNONYM DEVENGAMIENTOAUTO FOR SICAS_OC.DEVENGAMIENTOAUTO;
/
GRANT EXECUTE ON DEVENGAMIENTOAUTO TO PUBLIC