CREATE OR REPLACE PROCEDURE ENVIO_PLD IS
  nIdPoliza   NUMBER;
  cMensaje    VARCHAR2(300);
  
  CURSOR POLIZA_Q IS
      SELECT IDPOLIZA 
      FROM POLIZAS
      WHERE FECEMISION = TRUNC(SYSDATE) 
      AND STSPOLIZA = 'EMI';

BEGIN
  FOR X  IN POLIZA_Q LOOP
     nIdPoliza := X.Idpoliza;
     IF nIdPoliza != 0 THEN
        OC_ADMON_RIESGO.VALIDA_PERSONAS_POLIZA(nIdPoliza,cMensaje);
     END IF;
  END LOOP;
END ENVIO_PLD;