--
-- GTREAALERTAS  (Procedure) 
--
--  Dependencies: 
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   GT_REA_ALERTA_VENCIMIENTO (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.GTREAALERTAS
AS
BEGIN
GT_REA_ALERTA_VENCIMIENTO.PRINCIPAL;
END ;
/

GRANT EXECUTE, DEBUG ON SICAS_OC.GTREAALERTAS TO PUBLIC
/
