CREATE OR REPLACE PACKAGE OC_DETALLE_COMISION IS
----- SE INCLUYE TRATAMIENTO DE COMISIONES PARA POLIZAS PAQUETE (MULTIRAMO VIFLEX)      JMMD20220114
-- HOMOLOGACION VIFLEX                                                       2022/03/01  JMMD
-- SE AGREGA EN EL CURSOR OC_DETALLE_COM_IMP CONSULTA IVA DE HONORARIOS PROVEEDORES 09/01/2024 MLJS

PROCEDURE INSERTA_DETALLE_COMISION(cCodCia VARCHAR2, nIdPoliza Number, nIdComision Number,
                                   cOrigen VARCHAR2,cIdTipoSeg VARCHAR2) ;
END;
/
CREATE OR REPLACE PACKAGE BODY OC_DETALLE_COMISION IS

----- SE INCLUYE TRATAMIENTO DE COMISIONES PARA POLIZAS PAQUETE (MULTIRAMO VIFLEX)      JMMD20220114
-- HOMOLOGACION VIFLEX                                                       2022/03/01  JMMD

PROCEDURE INSERTA_DETALLE_COMISION(cCodCia VARCHAR2, nIdPoliza Number, nIdComision Number,
                                   cOrigen VARCHAR2, cIdTipoSeg VARCHAR2) IS
nExiste                 NUMBER(2);
nMonto_Mon_Local        COMISIONES.Comision_Local%TYPE;
nMonto_Mon_Extranjera   COMISIONES.Comision_Moneda%TYPE;
-----
cEsmultiramo            VARCHAR2(1)  := 'N';
cCodTipoPlan            TIPOS_DE_SEGUROS.CODTIPOPLAN%TYPE;
nPrimaLocal             DETALLE_POLIZA.PRIMA_LOCAL%TYPE;
nPrimaMoneda            DETALLE_POLIZA.PRIMA_MONEDA%TYPE;
nComision_Local         COMISIONES.COMISION_LOCAL%TYPE;
nComision_Moneda        COMISIONES.COMISION_MONEDA%TYPE;
nIdetpol                DETALLE_POLIZA.IDETPOL%TYPE;
nFactorComision     NUMBER;
nFactorComisionAP       NUMBER;
cTiporamo               VARCHAR2(6);

-----
CURSOR  Oc_Detalle_Com IS
   SELECT CO.CodCia CodCia, CO.IdComision IdComision, CC.CodConcepto CodConcepto, CO.IdFactura, CO.IdNcr,
          DECODE(CDC.Signo_Concepto,'+',((CO.Comision_Local*CC.PorcCpto)/100)*1,((CO.Comision_Local*CC.PorcCpto)/100)*-1) Monto_Mon_Local,
          DECODE(CDC.Signo_Concepto,'+',((CO.Comision_Moneda*CC.PorcCpto)/100)*1,((CO.Comision_Moneda*CC.PorcCpto)/100)*-1) Monto_Mon_Extranjera
     FROM COMISIONES CO, AGENTES AG, CONCEPTO_COMISION CC,
          RAMO_CONCEPTO_COMISION RMC, CATALOGO_DE_CONCEPTOS CDC
    WHERE CO.CodCia      = AG.CodCia
      AND CO.Cod_Agente  = AG.Cod_Agente
      AND AG.CodCia      = CC.CodCia
      AND AG.CodTipo     = CC.CodTipo
      AND CC.CodCia      = RMC.CodCia
      AND CC.CodTipo     = RMC.CodTipo
      AND CC.CODCONCEPTO = RMC.CODCONCEPTO
      AND CC.ORIGEN      = RMC.ORIGEN
      AND CC.CodCia      = CDC.CodCia
      AND CC.CodConcepto = CDC.CodConcepto
      AND CC.Origen      = cOrigen
      AND RMC.IdTipoSeg  = cIdTipoSeg
      AND CO.CodCia      = cCodCia
      AND CO.IdPoliza    = nIdPoliza
      AND CO.IdComision  = nIdComision;

----- JMMD20220107

CURSOR OC_DETALLE_COM_IMP IS
SELECT DISTINCT X.CodCia CodCia, X.IdComision IdComision, CC.CodConcepto CodConcepto, X.IdFactura, X.IdNcr,
          DECODE(CDC.Signo_Concepto,'+',((MONTO_LOCAL*CC.PorcCpto)/100)*1,((MONTO_LOCAL*CC.PorcCpto)/100)*-1) Monto_Mon_Local,
          DECODE(CDC.Signo_Concepto,'+',((MONTO_EXTRANJERA*CC.PorcCpto)/100)*1,((MONTO_EXTRANJERA*CC.PorcCpto)/100)*-1) Monto_Mon_Extranjera
--          , C.COMISION_MONEDA
          FROM
(
----- IVA AGENTES
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto
FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('COMACC')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('AGTEPF','AGTEPM')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'IVASIN'
AND RCC.CODTIPO LIKE 'AGTE%'
AND RCC.CODTIPOPLAN = '099'
GROUP BY C.CodCia, C.IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
RCC.CodConcepto
UNION
----- IVA HONORARIOS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto
FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('HONACC', 'HONVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('HONPF','HONPM')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'IVASIN'
AND RCC.CODTIPO IN('HONPF','HONPM')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 RCC.CodConcepto
----- MLJS 09/01/2024 SE AGREGA IVA HONORARIOS PROVEEDORES 
UNION
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto
FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('HONACC', 'HONVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('HONORM','HONORF')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO IN ('IVASIN','IVAHON')
AND RCC.CODTIPO = A.CODTIPO 
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 RCC.CodConcepto
----- MLJS 09/01/2024 SE AGREGA IVA HONORARIOS PROVEEDORES 
UNION
----- RETISR AGENTES Y HONORARIOS PERSONAS FISICAS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto

FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('HONACC', 'HONVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'RETISR'
AND RCC.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 RCC.CodConcepto
UNION
----- RETISR AGENTES Y HONORARIOS PERSONAS FISICAS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto

FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('HONACC', 'HONVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'RETISR'
AND RCC.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 RCC.CodConcepto
UNION
----- RETISR AGENTES PERSONAS FISICAS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto

FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('COMACC', 'COMVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('AGTEPF')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'RETISR'
AND RCC.CODTIPO IN('AGTEPF')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 RCC.CodConcepto

UNION
----- RETIVA AGENTES Y HONORARIOS PERSONAS FISICAS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto
FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('HONACC', 'HONVDA')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'RETIVA'
AND RCC.CODTIPO IN('HONPF') --,'HONPM')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO , --DC.CODCONCEPTO,
 RCC.CodConcepto
UNION
----- RETIVA AGENTES Y HONORARIOS PERSONAS FISICAS
SELECT  C.CodCia CodCia, C.IdComision IdComision, C.IDFACTURA, C.IDNCR, C.ORIGEN,
 C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO,
 SUM(NVL(DC.MONTO_MON_LOCAL,0)) MONTO_LOCAL, SUM(NVL(DC.MONTO_MON_EXTRANJERA,0)) MONTO_EXTRANJERA, RCC.CodConcepto CodConcepto
FROM COMISIONES C, DETALLE_COMISION DC, AGENTES A, RAMO_CONCEPTO_COMISION RCC
WHERE DC.CODCIA = cCodCia
AND DC.IDCOMISION = nIdComision
AND DC.ORIGEN = cOrigen
AND DC.CODCONCEPTO IN('COMACC')
AND C.CODCIA = DC.CODCIA
AND C.IDCOMISION = DC.IDCOMISION
AND C.IDPOLIZA = nIdPoliza
AND C.ORIGEN = DC.ORIGEN
AND A.COD_AGENTE = C.COD_AGENTE
AND A.CODCIA = C.CODCIA
AND A.CODEMPRESA = C.CODEMPRESA
AND A.CODTIPO IN('AGTEPF')
AND RCC.CODCIA = C.CODCIA
AND RCC.CODEMPRESA = C.CODEMPRESA
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO = 'RETIVA'
AND RCC.CODTIPO IN('AGTEPF')
AND RCC.ORIGEN = C.ORIGEN
AND RCC.CODTIPOPLAN = '099'
GROUP BY  C.CodCia , C.IdComision , C.IDFACTURA, C.IDNCR, C.ORIGEN, C.COD_MONEDA, C.COD_AGENTE, A.CODTIPO , --DC.CODCONCEPTO,
 RCC.CodConcepto

 ) X,
 concepto_comision cc , catalogo_de_conceptos cDc
 WHERE CC.CODCONCEPTO   = X.CODCONCEPTO
AND CC.ORIGEN        = X.Origen
AND CDC.CODCIA       = cCodCia
AND CDC.CODCONCEPTO  = CC.CODCONCEPTO;
--------------------
CURSOR OC_DETALLE_COMISION_CONCEPTOS IS
SELECT  RCC.CODCONCEPTO, RCC.CODTIPOPLAN, C.COMISION_LOCAL, C.COMISION_MONEDA, C.CODCIA, C.IDCOMISION,
C.IDFACTURA, C.IDNCR, C.COD_MONEDA, C.COD_AGENTE
FROM RAMO_CONCEPTO_COMISION RCC, AGENTES A, COMISIONES C
WHERE C.CODCIA = cCodCia
AND C.IDPOLIZA = nIdPoliza
AND C.IDCOMISION = nIdComision
AND A.CODCIA = C.CODCIA
AND A.COD_AGENTE = C.COD_AGENTE
AND RCC.IDTIPOSEG = cIdTipoSeg
AND RCC.CODCONCEPTO IN('COMVDA','COMACC','HONACC','HONVDA')
AND RCC.CODTIPO = A.CODTIPO
AND RCC.ORIGEN = cOrigen
AND RCC.CODTIPOPLAN = cCodTipoPlan;

CURSOR P_COB_RAMOS IS
SELECT DISTINCT C.IDRAMOREAL
  FROM   COBERT_ACT C
  WHERE  C.StsCobertura IN ('EMI','SOL','XRE')
    AND  C.IDetPol       = nIdetPol
    AND  C.IdPoliza      = nIdPoliza
    AND  C.CodCia        = cCodCia
  UNION ALL
  SELECT DISTINCT C.IDRAMOREAL
  FROM   COBERT_ACT_ASEG C
  WHERE  C.StsCobertura IN ('EMI','SOL','XRE')
    AND  C.IDetPol       = nIdetPol
    AND  C.IdPoliza      = nIdPoliza
    AND  C.CodCia        = cCodCia     ;

BEGIN
   BEGIN
      SELECT 1
        INTO nExiste
        FROM DETALLE_COMISION
       WHERE CodCia     = cCodCia
         AND IdComision = nIdComision;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         nExiste:= 0;
      WHEN TOO_MANY_ROWS THEN
         nExiste:= 1;
   END;
----- JMMD20220107
   SELECT NVL(INDMULTIRAMO,'N'), CODTIPOPLAN
     INTO cEsmultiramo, cCodTipoPlan
     FROM TIPOS_DE_SEGUROS TS
    WHERE TS.CODCIA = cCodCia
      AND TS.IDTIPOSEG = cIdTipoSeg;
----- JMMD20220107
   IF nExiste = 0 THEN
----- JMMD20220107
--         dbms_output.put_line('jmmd en oc_detalle_comision cEsmultiramo  '||cEsmultiramo);
     IF cEsmultiramo = 'N' THEN
----- JMMD20220107
      FOR I IN Oc_Detalle_Com LOOP
--         dbms_output.put_line('jmmd en oc_detalle_comision I.CODCONCEPTO  '||I.CODCONCEPTO||' nIdComision  '||nIdComision||'  I.Monto_Mon_Extranjera  '||I.Monto_Mon_Extranjera );
         nMonto_Mon_Local      := I.Monto_Mon_Local;
         nMonto_Mon_Extranjera := I.Monto_Mon_Extranjera;
         BEGIN
            INSERT INTO DETALLE_COMISION
                  (CodCia, IdComision, CodConcepto, Monto_Mon_Local,
                   Monto_Mon_Extranjera, Estado, Origen)
            VALUES(I.CodCia, I.IdComision, I.CodConcepto, nMonto_Mon_Local,
                   nMonto_Mon_Extranjera, 'ACT', cOrigen);
         EXCEPTION
            WHEN OTHERS THEN
               RAISE_APPLICATION_ERROR(-20100, 'Error'||i.CodCia||'-'||i.IdComision||'-'||i.CodConcepto||'-'|| cOrigen ||sqlerrm);
         END;
      END LOOP;
----- JMMD20220107
    ELSE

----- JMMD20220113
         SELECT IDETPOL
           INTO nIdetpol
           FROM COMISIONES
          WHERE IdPoliza  = nIdPoliza
            AND CodCia    = cCodCia
            AND IdCOMISION = nIdComision;

         SELECT NVL(Prima_Local,0), NVL(Prima_Moneda,0)
           INTO nPrimaLocal, nPrimaMoneda
           FROM DETALLE_POLIZA
          WHERE IdPoliza  = nIdPoliza
            AND IDETPOL   = nIdetpol
            AND CodCia    = cCodCia
            AND IdTipoSeg = cIdTipoSeg;

        FOR PCR IN P_COB_RAMOS LOOP
        nFactorComision := OC_FACTURAR.FACTOR_PRORRATEO_RAMO( cCodCia, nIdPoliza, nIDetPol, PCR.IdRamoReal , nPrimaMoneda );
        cCodTipoPlan := PCR.IDRAMOREAL;

           FOR I IN OC_DETALLE_COMISION_CONCEPTOS LOOP
    ----- JMMD 20220113  MULTIRAMO
              SELECT SUBSTR(i.CodConcepto,4,3)
                INTO ctiporamo
                from dual;

             dbms_output.put_line('jmmd en oc_detalle_comision ctiporamo  '||ctiporamo||' nIdComision  '||nIdComision||'  nPrimaMoneda  '||nPrimaMoneda );
             BEGIN
               SELECT ODCV.COMISION_LOCAL, ODCV.COMISION_MONEDA
                INTO nComision_Local, nComision_Moneda
                FROM T_OC_DETALLE_COMISION_VIFLEX ODCV
                WHERE ODCV.COD_AGENTE = I.COD_AGENTE
                AND ODCV.IDPOLIZA = nIdPoliza
                AND ODCV.NUMDOCTO = I.IDFACTURA
                AND ODCV.IDETPOL  = nIdetpol
                AND ODCV.COD_MONEDA = I.COD_MONEDA
                AND ODCV.TIPORAMO = ctiporamo
                ;
             EXCEPTION
                WHEN NO_DATA_FOUND THEN
                   nComision_Local := 0;
                   nComision_Moneda:= 0;
             END;
                nMonto_Mon_Local := nComision_Local; -- * nFactorComision;
                nMonto_Mon_Extranjera := nComision_Moneda ; --* nFactorComision;

--             dbms_output.put_line('jmmd en oc_detalle_comision ctiporamo  '||ctiporamo||' nMonto_Mon_Extranjera  '||nMonto_Mon_Extranjera );
             BEGIN
                INSERT INTO DETALLE_COMISION
                      (CodCia, IdComision, CodConcepto, Monto_Mon_Local,
                       Monto_Mon_Extranjera, Estado, Origen)
                VALUES(I.CodCia, I.IdComision, I.CodConcepto, nMonto_Mon_Local,
                       nMonto_Mon_Extranjera, 'ACT', cOrigen);
             EXCEPTION
                WHEN OTHERS THEN
                   RAISE_APPLICATION_ERROR(-20100, 'Error'||i.CodCia||'-'||i.IdComision||'-'||i.CodConcepto||'-'|| cOrigen ||sqlerrm);
             END;
          END LOOP;

        END LOOP;

-----------------
      FOR J IN Oc_Detalle_Com_IMP LOOP
         nMonto_Mon_Local      := J.Monto_Mon_Local;
         nMonto_Mon_Extranjera := J.Monto_Mon_Extranjera;
--         dbms_output.put_line('jmmd en oc_detalle_comision IdComision  '||J.IdComision||' CodConcepto  '||J.CodConcepto||'  Monto_Mon_Local  '||nMonto_Mon_Local||' Origen  '||cOrigen);
         BEGIN
            INSERT INTO DETALLE_COMISION
                  (CodCia, IdComision, CodConcepto, Monto_Mon_Local,
                   Monto_Mon_Extranjera, Estado, Origen)
            VALUES(J.CodCia, J.IdComision, J.CodConcepto, nMonto_Mon_Local,
                   nMonto_Mon_Extranjera, 'ACT', cOrigen);
         EXCEPTION
            WHEN OTHERS THEN
               RAISE_APPLICATION_ERROR(-20100, 'Error'||J.CodCia||'-'||J.IdComision||'-'||J.CodConcepto||'-'|| cOrigen ||sqlerrm);
         END;
      END LOOP;
    END IF;
----- JMMD20220107
   ELSE
      RAISE_APPLICATION_ERROR(-20100, 'Intenta Crear de Forma Automática un Nuevo Detalle de Comisión, pero ya Existen Registros');
   END IF;
END INSERTA_DETALLE_COMISION;

end oc_detalle_comision;
/
