--
-- PROC_EMITAR  (Procedure) 
--
--  Dependencies: 
--   STANDARD (Package)
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   PROCESOS_MASIVOS (Table)
--   OC_PROCESOS_MASIVOS (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC."PROC_EMITAR" IS

CURSOR REG_Q IS
   SELECT IdProcMasivo, TipoProceso
     FROM PROCESOS_MASIVOS
    WHERE StsRegProceso IN ('XPROC','ERROR')
      AND TipoProceso = 'EMITAR'
    ORDER BY IdProcMasivo;
BEGIN
    FOR X IN REG_Q LOOP
      OC_PROCESOS_MASIVOS.PROCESO_REGISTRO(X.IdProcMasivo, X.TipoProceso);
      COMMIT;
    END LOOP;
END;
/

--
-- PROC_EMITAR  (Synonym) 
--
--  Dependencies: 
--   PROC_EMITAR (Procedure)
--
CREATE OR REPLACE PUBLIC SYNONYM PROC_EMITAR FOR SICAS_OC.PROC_EMITAR
/


GRANT EXECUTE ON SICAS_OC.PROC_EMITAR TO PUBLIC
/
