--
-- TIPO_CAMBIO_DIARIO  (Procedure) 
--
--  Dependencies: 
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   GT_TASAS_CAMBIO (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.TIPO_CAMBIO_DIARIO IS
BEGIN
   GT_TASAS_CAMBIO.EJECUTA_PROCESO_WS_TASA_CAMBIO;
   COMMIT;
END;
/
