--
-- TIPO_CAMBIO_DIARIO  (Procedure) 
--
--  Dependencies: 
--   SYS_STUB_FOR_PURITY_ANALYSIS (Package)
--   GT_TASAS_CAMBIO (Package)
--
CREATE OR REPLACE PROCEDURE SICAS_OC.TIPO_CAMBIO_DIARIO IS
BEGIN
   GT_TASAS_CAMBIO.EJECUTA_PROCESO_WS_TASA_CAMBIO;
   COMMIT;
END;
/

--
-- TIPO_CAMBIO_DIARIO  (Synonym) 
--
--  Dependencies: 
--   TIPO_CAMBIO_DIARIO (Procedure)
--
CREATE OR REPLACE PUBLIC SYNONYM TIPO_CAMBIO_DIARIO FOR SICAS_OC.TIPO_CAMBIO_DIARIO
/


GRANT EXECUTE ON SICAS_OC.TIPO_CAMBIO_DIARIO TO PUBLIC
/
