CREATE OR REPLACE PROCEDURE SICAS_OC.UTF8 IS

    BEGIN
        UPDATE SICAS_OC.REQUISITOS
        SET TOOLTIP = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TOOLTIP,'Ã³','ó'),'Ã¼','ü'),'Ã±','ñ'),'Ã©','é'),'Ã­','í'),'Ã¡','í'),'Ãº','ú');
        
        UPDATE SICAS_OC.REQUISITOS
        SET NOMARCHIVO = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(NOMARCHIVO,'Ã³','ó'),'Ã¼','ü'),'Ã±','ñ'),'Ã©','é'),'Ã­','í'),'Ã¡','í'),'Ãº','ú');
        
        COMMIT;
    END;
/

CREATE OR REPLACE PUBLIC SYNONYM UTF8 FOR SICAS_OC.UTF8;
/

GRANT EXECUTE ON SICAS_OC.UTF8 TO PUBLIC;
/
