create or replace PROCEDURE SICAS_OC.WS_MODIFICA_ASEGURADO (
    --p_cod_asegurado           IN ASEGURADO.COD_ASEGURADO%TYPE,
    p_tipo_doc_identificacion IN PERSONA_NATURAL_JURIDICA.TIPO_DOC_IDENTIFICACION%TYPE,
    p_num_doc_identificacion  IN PERSONA_NATURAL_JURIDICA.NUM_DOC_IDENTIFICACION%TYPE,
    p_nombre           IN PERSONA_NATURAL_JURIDICA.NOMBRE%TYPE DEFAULT NULL,
    p_apellido_paterno IN PERSONA_NATURAL_JURIDICA.APELLIDO_PATERNO%TYPE DEFAULT NULL,
    p_apellido_materno IN PERSONA_NATURAL_JURIDICA.APELLIDO_MATERNO%TYPE DEFAULT NULL,
    p_tipo_persona     IN PERSONA_NATURAL_JURIDICA.TIPO_PERSONA%TYPE DEFAULT NULL,
    p_fec_nacimiento   IN PERSONA_NATURAL_JURIDICA.FECNACIMIENTO%TYPE DEFAULT NULL,
    p_direcres         IN PERSONA_NATURAL_JURIDICA.DIRECRES%TYPE DEFAULT NULL,
    p_num_interior     IN PERSONA_NATURAL_JURIDICA.NUMINTERIOR%TYPE DEFAULT NULL,
    p_num_exterior     IN PERSONA_NATURAL_JURIDICA.NUMEXTERIOR%TYPE DEFAULT NULL,
    p_codcolonia       IN PERSONA_NATURAL_JURIDICA.CODCOLRES%TYPE DEFAULT NULL,
    p_codcorrres       IN PERSONA_NATURAL_JURIDICA.CODCORRRES%TYPE DEFAULT NULL,
    p_codprovres       IN PERSONA_NATURAL_JURIDICA.CODPROVRES%TYPE DEFAULT NULL,
    p_codpaisres       IN PERSONA_NATURAL_JURIDICA.CODPAISRES%TYPE DEFAULT NULL,
    p_codposres        IN PERSONA_NATURAL_JURIDICA.CODPOSRES%TYPE DEFAULT NULL,
    p_email            IN PERSONA_NATURAL_JURIDICA.EMAIL%TYPE DEFAULT NULL,
    p_telefono         IN PERSONA_NATURAL_JURIDICA.TELRES%TYPE DEFAULT NULL
) AS
BEGIN
    UPDATE PERSONA_NATURAL_JURIDICA
    SET
        NOMBRE           = NVL(p_nombre,           NOMBRE),
        APELLIDO_PATERNO = NVL(p_apellido_paterno, APELLIDO_PATERNO),
        APELLIDO_MATERNO = NVL(p_apellido_materno, APELLIDO_MATERNO),
        TIPO_PERSONA     = NVL(p_tipo_persona,     TIPO_PERSONA),
        FECNACIMIENTO    = NVL(p_fec_nacimiento,   FECNACIMIENTO),
        DIRECRES         = NVL(p_direcres,         DIRECRES),
        NUMINTERIOR      = NVL(p_num_interior,     NUMINTERIOR),
        NUMEXTERIOR      = NVL(p_num_exterior,     NUMEXTERIOR),
        CODCOLRES        = NVL(p_codcolonia,       CODCOLRES),
        CODCORRRES       = NVL(p_codcorrres,       CODCORRRES),
        CODPROVRES       = NVL(p_codprovres,       CODPROVRES),
        CODPAISRES       = NVL(p_codpaisres,       CODPAISRES),
        CODPOSRES        = NVL(p_codposres,        CODPOSRES),
        EMAIL            = NVL(p_email,            EMAIL),
        TELRES           = NVL(p_telefono,         TELRES)
    WHERE TIPO_DOC_IDENTIFICACION = p_tipo_doc_identificacion
      AND NUM_DOC_IDENTIFICACION = p_num_doc_identificacion;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se encontró la persona para actualizar.');
    END IF;
    COMMIT;
END WS_MODIFICA_ASEGURADO;
/

CREATE OR REPLACE PUBLIC SYNONYM WS_MODIFICA_ASEGURADO FOR SICAS_OC.WS_MODIFICA_ASEGURADO
/

GRANT EXECUTE ON SICAS_OC.WS_MODIFICA_ASEGURADO TO PUBLIC
/