create or replace PROCEDURE SICAS_OC.WS_OBTIENE_RECIBOS (    
    p_IdPoliza    IN NUMBER DEFAULT NULL,
    p_CodCia      IN NUMBER DEFAULT NULL,
    p_CodEmpresa  IN NUMBER DEFAULT NULL,  
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
        SELECT IDFACTURA, STSFACT, NUMCUOTA, COD_MONEDA, MONTO_FACT_MONEDA, MTOCOMISI_MONEDA, NUMFACT,
               MONTO_FACT_LOCAL, FECSTS, RECIBOPAGO, FECANUL, FORMPAGO, SALDO_MONEDA, FECPAGO, FOLIOFACTELEC
          FROM FACTURAS
         WHERE (p_CodCia IS NULL OR CodCia = p_CodCia)
           AND (p_IdPoliza IS NULL OR IdPoliza = p_IdPoliza)
         ORDER BY IDFACTURA DESC;
END WS_OBTIENE_RECIBOS;
/

CREATE OR REPLACE PUBLIC SYNONYM WS_OBTIENE_RECIBOS FOR SICAS_OC.WS_OBTIENE_RECIBOS
/

GRANT EXECUTE ON SICAS_OC.WS_OBTIENE_RECIBOS TO PUBLIC
/