create or replace PROCEDURE SICAS_OC.WS_OBTENER_REGIMEN_FISCAL (
    p_IDREGFISSAT      IN NUMBER DEFAULT NULL,
    p_DESCTIPOREGIMEN  IN VARCHAR2 DEFAULT NULL,
    p_resultado        OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
        SELECT IDREGFISSAT,
               TIPOPERSONA,
               DESCTIPOREGIMEN
          FROM CAT_REGIMEN_FISCAL
         WHERE (p_IDREGFISSAT IS NULL OR IDREGFISSAT = p_IDREGFISSAT)
           AND (p_DESCTIPOREGIMEN IS NULL OR UPPER(TIPOPERSONA) LIKE '%' || UPPER(p_DESCTIPOREGIMEN) || '%')
         ORDER BY IDREGFISSAT;
END WS_OBTENER_REGIMEN_FISCAL;
/

CREATE OR REPLACE PUBLIC SYNONYM WS_OBTENER_REGIMEN_FISCAL FOR SICAS_OC.WS_OBTENER_REGIMEN_FISCAL
/

GRANT EXECUTE ON SICAS_OC.WS_OBTENER_REGIMEN_FISCAL TO PUBLIC
/