create or replace PROCEDURE SICAS_OC.WS_REGISTRAR_OBSERVACION_SINIESTRO (
    P_IDSINIESTRO      IN NUMBER,
    P_IDPOLIZA         IN NUMBER,
    P_FECOBSERV        IN DATE,
    P_CODUSUARIO       IN VARCHAR2,
    P_DESCRIPCION      IN VARCHAR2,
    P_IDTPOPAGOSIN     IN VARCHAR2,  
    P_CODCIA           IN NUMBER,
    P_CODEMPRESA       IN NUMBER,
    P_MENSAJE          OUT VARCHAR2
) AS
    V_IDOBSERVA        NUMBER;
    V_EXISTE_SINIESTRO  NUMBER;  -- Cambio: Se usa un número en lugar de BOOLEAN
BEGIN
    -- Validación de que el siniestro existe (filtro por IDSINIESTRO y IDPOLIZA)
    SELECT COUNT(*)
    INTO V_EXISTE_SINIESTRO
    FROM SINIESTRO
    WHERE IDSINIESTRO = P_IDSINIESTRO
      AND IDPOLIZA = P_IDPOLIZA;
    IF V_EXISTE_SINIESTRO = 0 THEN
        P_MENSAJE := 'El siniestro con esa póliza no existe.';
        RAISE_APPLICATION_ERROR(-20001, P_MENSAJE);
    END IF;
    -- Calcular el ID de la observación (IDOBSERVA) automáticamente
    BEGIN
        SELECT NVL(MAX(IDOBSERVA), 0) + 1
        INTO V_IDOBSERVA
        FROM OBSERVACION_SINIESTRO
        WHERE IDSINIESTRO = P_IDSINIESTRO
          AND IDPOLIZA = P_IDPOLIZA;
    EXCEPTION
        WHEN OTHERS THEN
            V_IDOBSERVA := 1;  -- Si no existen observaciones, comenzamos con 1
    END;
    -- Insertar en la tabla OBSERVACION_SINIESTRO
    INSERT INTO OBSERVACION_SINIESTRO (
        IDSINIESTRO, IDPOLIZA, IDOBSERVA, FECOBSERV, CODUSUARIO, 
        DESCRIPCION, IDTPOPAGOSIN, CODCIA, CODEMPRESA
    ) VALUES (
        P_IDSINIESTRO, P_IDPOLIZA, V_IDOBSERVA, P_FECOBSERV, P_CODUSUARIO, 
        P_DESCRIPCION, P_IDTPOPAGOSIN, P_CODCIA, P_CODEMPRESA
    );
    -- Confirmación del éxito de la operación
    COMMIT;
    P_MENSAJE := 'Registro de observación realizado correctamente.';
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        P_MENSAJE := 'Error al registrar la observación: ' || SQLERRM;
        RAISE_APPLICATION_ERROR(-20002, P_MENSAJE);
END WS_REGISTRAR_OBSERVACION_SINIESTRO;
/

CREATE OR REPLACE PUBLIC SYNONYM WS_REGISTRAR_OBSERVACION_SINIESTRO FOR SICAS_OC.WS_REGISTRAR_OBSERVACION_SINIESTRO
/

GRANT EXECUTE ON SICAS_OC.WS_REGISTRAR_OBSERVACION_SINIESTRO TO PUBLIC
/