--
-- CAMBIA_ACENTOS  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION SICAS_OC."CAMBIA_ACENTOS" 
      (CADENA_ENTRADA VARCHAR2) RETURN VARCHAR2 IS
--
-- CREADA 10/05/2016  JICO
--      
 CADENA_SALIDA VARCHAR2(500);
 ENTRADA       VARCHAR2(100) := 'ЯАИМСЗюабцдехийклмнорстужызшэя';
 SALIDA        VARCHAR2(100) := 'naeiouAAAAAAEEEEIIIIOOOOOUUUUN';
BEGIN
  --
  CADENA_SALIDA :=  UPPER(TRANSLATE(LTRIM(CADENA_ENTRADA),ENTRADA,SALIDA));
  --
  RETURN(CADENA_SALIDA);
END;
/

--
-- CAMBIA_ACENTOS  (Synonym) 
--
--  Dependencies: 
--   CAMBIA_ACENTOS (Function)
--
CREATE OR REPLACE PUBLIC SYNONYM CAMBIA_ACENTOS FOR SICAS_OC.CAMBIA_ACENTOS
/


GRANT EXECUTE ON SICAS_OC.CAMBIA_ACENTOS TO PUBLIC
/
