FUNCTION          OBTIENE_REFERENCIA
  (P_IDPOLIZA  NUMBER,
   P_IDFACTURA NUMBER)  RETURN VARCHAR2 IS
 --
 P_IDCLIENTE      CLIENTES.CODCLIENTE%TYPE;
 P_NUM_TRIBUTARIO PERSONA_NATURAL_JURIDICA.NUM_TRIBUTARIO%TYPE;
 --  
 CREFERENCIA   VARCHAR2(20);
 CIDTIPOSEG    VARCHAR2(5);
 CCORRELATIVO  VARCHAR2(6);
 CCLIENTE_VIP  VARCHAR2(2);  -- JICO 20190118
 CDIGITO       VARCHAR2(2);
 NCONSECUTIVO  NUMBER;
BEGIN
  --
  CIDTIPOSEG   := '';
  CCORRELATIVO := '';
  NCONSECUTIVO := '0';
  P_IDCLIENTE  := 0;
  CCLIENTE_VIP := 'N';
  CDIGITO      := '';
  --
  SELECT RPAD(SUBSTR(MAX(IDTIPOSEG),1,5) ,5,'0'),
         P.CODCLIENTE
    INTO CIDTIPOSEG,
         P_IDCLIENTE
    FROM DETALLE_POLIZA DP,
         POLIZAS        P    
   WHERE DP.IDPOLIZA = P_IDPOLIZA
     --
     AND P.IDPOLIZA = DP.IDPOLIZA
   GROUP BY P.CODCLIENTE;
  --
  BEGIN
   SELECT NVL(CLIENTE_ESPECIAL,'N')
     INTO CCLIENTE_VIP
     FROM CLIENTES C
    WHERE C.CODCLIENTE = P_IDCLIENTE;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
         CCLIENTE_VIP := 'N';
    WHEN TOO_MANY_ROWS THEN
         CCLIENTE_VIP := 'S';
    WHEN OTHERS THEN
         CCLIENTE_VIP := 'N';
  END;
  --
  IF CCLIENTE_VIP = 'N' THEN
     BEGIN 
       SELECT RPAD(MAX(CORRELATIVO),6,'0'),
              CORRELATIVO
         INTO CCORRELATIVO,
              NCONSECUTIVO
         FROM COBRO_REFER_CLI_POL   
        WHERE IDPOLIZA   = P_IDPOLIZA
          AND CODCLIENTE = P_IDCLIENTE
        GROUP BY CORRELATIVO;
     EXCEPTION
        WHEN NO_DATA_FOUND THEN
             CCORRELATIVO := '0';
             NCONSECUTIVO := 0;
     END;
     --
     IF NCONSECUTIVO = 0 THEN 
        CREFERENCIA := CIDTIPOSEG||lpad(P_IDPOLIZA,7,'0')||lpad(P_IDFACTURA,7,'0');
        CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));
     ELSE
        P_NUM_TRIBUTARIO := OC_CLIENTES.IDENTIFICACION_TRIBUTARIA(P_IDCLIENTE);
        CREFERENCIA := P_NUM_TRIBUTARIO||CCORRELATIVO;
        CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));     
     END IF;
     -- 
  ELSE
     CDIGITO     := DIGITO_VERIFICADOR('2543683'||LPAD(P_IDCLIENTE,12,0));
     CREFERENCIA := '2543683'||LPAD(P_IDCLIENTE,12,0)||CDIGITO;
  END IF;
  --
  RETURN (CREFERENCIA);
  --
END;
