--
-- REFERENCIA_FONDOS_COLECTIVO  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--   DIGITO_VERIFICADOR (Function)
--
CREATE OR REPLACE FUNCTION SICAS_OC.REFERENCIA_FONDOS_COLECTIVO
  (P_IDPOLIZA        NUMBER,
   P_TIPOAPORTACION  VARCHAR2,
   P_IDETPOL         NUMBER,
   P_COD_ASEGURADO   NUMBER
   )  RETURN VARCHAR2 IS
 --
 CREFERENCIA   VARCHAR2(20);
BEGIN
  --
  IF P_TIPOAPORTACION = 'E' THEN
     CREFERENCIA := LPAD(P_IDPOLIZA,7,'0')||LPAD(P_IDETPOL,3,'0')||LPAD(P_COD_ASEGURADO,8,'0')||'E';
     CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));
  ELSE
     CREFERENCIA := LPAD(P_IDPOLIZA,7,'0')||LPAD(P_IDETPOL,3,'0')||LPAD(P_COD_ASEGURADO,8,'0')||'R';
     CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));
  END IF;
  --
  RETURN (CREFERENCIA) ;
END;
/

--
-- REFERENCIA_FONDOS_COLECTIVO  (Synonym) 
--
--  Dependencies: 
--   REFERENCIA_FONDOS_COLECTIVO (Function)
--
CREATE OR REPLACE PUBLIC SYNONYM REFERENCIA_FONDOS_COLECTIVO FOR SICAS_OC.REFERENCIA_FONDOS_COLECTIVO
/


GRANT EXECUTE ON SICAS_OC.REFERENCIA_FONDOS_COLECTIVO TO PUBLIC
/
