FUNCTION REFERENCIA_FONDOS_COLECTIVO
  (P_IDPOLIZA        NUMBER,
   P_TIPOAPORTACION  VARCHAR2,
   P_IDETPOL         NUMBER,
   P_COD_ASEGURADO   NUMBER
   )  RETURN VARCHAR2 IS
 --
 CREFERENCIA   VARCHAR2(20);
BEGIN
  --
  IF P_TIPOAPORTACION = 'E' THEN
     CREFERENCIA := LPAD(P_IDPOLIZA,7,'0')||LPAD(P_IDETPOL,3,'0')||LPAD(P_COD_ASEGURADO,8,'0')||'E';
     CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));
  ELSE
     CREFERENCIA := LPAD(P_IDPOLIZA,7,'0')||LPAD(P_IDETPOL,3,'0')||LPAD(P_COD_ASEGURADO,8,'0')||'R';
     CREFERENCIA := CREFERENCIA||TO_CHAR(DIGITO_VERIFICADOR(CREFERENCIA));
  END IF;
  --
  RETURN (CREFERENCIA) ;
END;
