
-- Generated by ORDS REST Data Services 22.3.0.r2781755
-- Schema: SICAS_OC  Date: Thu Feb 19 09:55:58 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SICAS_OC',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'sicas',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'emisiones_SIGO',
      p_base_path      => '/emisiones_SIGO/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_informacion_fiscal',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_informacion_fiscal',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado  VARCHAR2(2) := ''OK'';
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información fiscal
    cResultado := THONAPI.FLUJO_EMISION_SIGO.ACTUALIZAR_INFORMACION_FISCAL( :nCodCia
                                                                          , :nCodEmpresa
          ' || '                                                                , :nIdPoliza
                                                                          , :cCodUsoCFDI
                                                                          , :cCodObjetoImp
                                                                          , :nIdRegFisSAT
                                                                          , :cRazonSocialFact
                                                                          , :cTipo_Doc_Identificacion
                                                                          , :cNum_Doc_Identificacion
                                                                          , :cTipo_Direccion
                                                                          , :cDireccion
                                                                          , :cCodPais
                                                                          , :cC' || 'odEstado
                                                                          , :cCodCiudad
                                                                          , :cCodMunicipio
                                                                          , :cCodigo_Postal
                                                                          , :cCodAsentamiento
                                                                          , :cCodigo_ZIP
                                                                          , :cDireccion_Principal
                                                                          , :cNumInterior
                                                                          , :cNumExterior );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje' || '": "Información actualizada correctamente.",
        "data": { "cResultado": '' || NVL(TO_CHAR(cResultado), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'recalcular_poliza',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'recalcular_poliza',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :nIDetPol IS NULL THEN
       cMensaje := ''Debe indicar el Detalle de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información de la póliza
    THONAPI.API_MASIVOS_PLATAFORMA.RECALCULAR_POLIZA( nCodCia => :nCodCia
                                                 ' || '   , nCodEmpresa => :nCodEmpresa
                                                    , nIdPoliza => :nIdPoliza
                                                    , nIDetPol => :nIDetPol );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información actualizada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '',
                  "nIDetPol": '' || NVL(TO_CHAR(nIDetPol), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'cargar_asegurados',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'cargar_asegurados',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    --Parámetros principales del servicio
    cMensaje  VARCHAR2(500);
    nTotAseg  NUMBER:
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :nIDetPol IS NULL THEN
       cMensaje := ''Debe indicar el Detalle de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para eliminar a los asegurados
    nTotAseg := THONAPI.FLUJO_EMISION_SIGO.ELIMINAR_ASEGURADOS( :nCodCia
' || '                                                              , :nCodEmpresa
                                                              , :nIdPoliza
                                                              , :nIDetPol );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información eliminada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '',
                  "nIDetPol": '' || NVL(TO_CHAR(:nIDetPol), ''NULL'') || '',
                  "nTotAseg": '' || NVL(TO_CHAR(nTotAseg), ''NULL'') || '' }
    }'');
    --
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQL' || 'ERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'solicitar_pol_colectiva',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'solicitar_pol_colectiva',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    --Parámetros principales del servicio
    nIdPoliza       POLIZAS.IdPoliza%TYPE;
    cMensaje        VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdCotizacion IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Cotización'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para insertar la información y regresar la póliza generada
    nIdPoliza := THONAPI.FLUJO_EMISION_SIGO.SOLICITAR_POL_COLECTIVA( :nCodCia
                          ' || '                                         , :nCodEmpresa
                                                                   , :nIdCotizacion
                                                                   , :cTipoDocIdentificacion
                                                                   , :cNumDocIdentificacion
                                                                   , :cNombreCliente
                                                                   , :cApellidoPaternoCliente
                                                                   , :cApellidoMaternoCliente
                                                                   , :cSexo
                                                                   , :dFecNacimiento
                                                                   , :cTipoPersona
                                                                   , :cTipoIdTributario
                                                           ' || '        , :cNumTributario
                                                                   , :cDirecRes
                                                                   , :cNumInterior
                                                                   , :cNumExterior
                                                                   , :cCodColonia
                                                                   , :cCodProvRes
                                                                   , :cCodPosRes
                                                                   , :cTelRes
                                                                   , :cEmail
                                                                   , :cNacionalidad
                                                                   , :cCodFormaCobro
                                                                   , :cCodEntidadFinan
                                                            ' || '       , :cNumCuentaBancaria
                                                                   , :cNumCuentaClabe
                                                                   , :cNumTarjeta
                                                                   , :dFechaVencTarjeta
                                                                   , :cNombreTitular
                                                                   , :dFecIniVig
                                                                   , :dFecFinVig
                                                                   , :cCodPlanPago
                                                                   , :cIndAsegModelo
                                                                   , :cCodActividad );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{' || '
        "success": true,
        "mensaje": "Póliza generada correctamente.",
        "data": { "IdPoliza": '' || NVL(TO_CHAR(nIdPoliza), ''NULL'') || '' }
    }'');
    --
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_riesgo_tarifa',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_riesgo_tarifa',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información de la póliza
    THONAPI.API_MASIVOS_PLATAFORMA.ACTUALIZAR_RIESGO_TARIFA( nCodCia => :nCodCia
                                                           , nCodEmpresa => :nCodEmpresa
                                              ' || '             , nIdPoliza => :nIdPoliza );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información actualizada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_agrupador_pol',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_agrupador_pol',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    nRowAffect  NUMBER;
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :cCodAgrupador IS NULL THEN
       cMensaje := ''Debe indicar el Código del Agrupador'';
    ELSIF :cNumFolioPortal IS NULL THEN
       cMensaje := ''Debe indicar el Número de Folio del Portal'';
    ELSIF :cCodCatego IS NULL THEN
       cMensaje := ''Debe indicar el Código de Categoría'';
    ELSIF :cIndCalcDerechoEmis IS NULL THEN
       cMensaje := ''Debe indicar el Indicador de Derechos de Emisión'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "succe' || 'ss": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información de la póliza
    THONAPI.API_MASIVOS_PLATAFORMA.ACTUALIZAR_INFO_POLIZA( nCodCia => :nCodCia
                                                         , nCodEmpresa => :nCodEmpresa
                                                         , nIdPoliza => :nIdPoliza
                                                         , cCodAgrupador => :cCodAgrupador
                                                         , cNumFolioPortal => :cNumFolioPortal
                                                         , cCodCatego => :cCodCatego
                                                         , cIndCalcDerechoEmis => :cIndCalcDerechoEmis );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- R' || 'esponder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información actualizada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_numpolunico',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_numpolunico',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :cNumPolUnico IS NULL THEN
       cMensaje := ''Debe indicar el Número de Póliza Único'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información de la póliza
    THONAPI.API_MASIVOS_PLATAFORMA.ACTUALIZAR_NUMPOLUNICO( nCodCia => :nCodCia
                                      ' || '                   , nCodEmpresa => :nCodEmpresa
                                                         , nIdPoliza => :nIdPoliza
                                                         , cNumPolUnico => :cNumPolUnico );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información actualizada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_indicador_web',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'actualizar_indicador_web',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cMensaje    VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdCotizacion IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Cotización'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información de la póliza
    THONAPI.API_MASIVOS_PLATAFORMA.ACTUALIZAR_INDICADOR_WEB( nCodCia => :nCodCia
                                                           , nCodEmpresa => :nCodEmpresa
                                      ' || '                     , nIdCotizacion => :nIdCotizacion );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información actualizada correctamente.",
        "data": { "nIdCotizacion": '' || NVL(TO_CHAR(:nIdCotizacion), ''NULL'') || '' }
    }'');
    --                
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'insertar_asistencias_aseg',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'insertar_asistencias_aseg',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    --Parámetros principales del servicio
    cMensaje       VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :nIDetPol IS NULL THEN
       cMensaje := ''Debe indicar el Detalle de la Póliza'';
    ELSIF :nIdEndoso IS NULL THEN
       cMensaje := ''Debe indicar el Id. del Endoso'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para insertar el detalle de la coti' || 'zación
    THONAPI.FLUJO_EMISION_SIGO.INSERTAR_ASISTENCIAS_ASEG( :nCodCia
                                                        , :nCodEmpresa
                                                        , :nIdPoliza
                                                        , :nIDetPol
                                                        , :nIdEndoso
                                                        , :cCodAsistencia
                                                        , :cCodMoneda
                                                        , :nMontoAsistLocal
                                                        , :nMontoAsistMoneda );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información insertada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(' || ':nIdPoliza), ''NULL'') || '',
                  "nIDetPol": '' || NVL(TO_CHAR(:nIDetPol), ''NULL'') || '' }
    }'');
    --
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'insertar_asegurados',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'insertar_asegurados',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    --Parámetros principales del servicio
    cMensaje  VARCHAR2(500);
    nIdAseg   NUMBER:
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :nIDetPol IS NULL THEN
       cMensaje := ''Debe indicar el Detalle de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para insertar al asegurado
    nIdAseg := THONAPI.FLUJO_EMISION_SIGO.INSERTAR_ASEGURADOS( :nCodCia
     ' || '                                                        , :nCodEmpresa
                                                             , :nIdPoliza
                                                             , :nIDetPol
                                                             , :cNombre
                                                             , :cApellidoPaterno
                                                             , :cApellidoMaterno
                                                             , :cGenero
                                                             , :dFecNacimiento
                                                             , :nSalarioMensual
                                                             , :nVecesSalario
                                                             , :nSumAsegFija
                                                             , :cRFC );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''applicati' || 'on/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información insertada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '',
                  "nIDetPol": '' || NVL(TO_CHAR(:nIDetPol), ''NULL'') || '',
                  "nIdAseg": '' || NVL(TO_CHAR(nIdAseg), ''NULL'') || '' }
    }'');
    --
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQLERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'eliminar_asegurados',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'eliminar_asegurados',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    --Parámetros principales del servicio
    cMensaje  VARCHAR2(500);
    nTotAseg  NUMBER:
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
       cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
       cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :nIDetPol IS NULL THEN
       cMensaje := ''Debe indicar el Detalle de la Póliza'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para eliminar a los asegurados
    nTotAseg := THONAPI.FLUJO_EMISION_SIGO.ELIMINAR_ASEGURADOS( :nCodCia
' || '                                                              , :nCodEmpresa
                                                              , :nIdPoliza
                                                              , :nIDetPol );
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "Información eliminada correctamente.",
        "data": { "nIdPoliza": '' || NVL(TO_CHAR(:nIdPoliza), ''NULL'') || '',
                  "nIDetPol": '' || NVL(TO_CHAR(:nIDetPol), ''NULL'') || '',
                  "nTotAseg": '' || NVL(TO_CHAR(nTotAseg), ''NULL'') || '' }
    }'');
    --
    COMMIT;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
                "success": false,
                "mensaje": "'' || SQL' || 'ERRM || ''",
                "data": []
            }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'pre_emitir_poliza',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'emisiones_SIGO',
      p_pattern        => 'pre_emitir_poliza',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un Código de Empresa'';
    ELSIF :nIdPoliza IS NULL THEN
        cMensaje := ''Debe indicar el Id. de la Póliza'';
    ELSIF :cIndRequierePago IS NULL THEN
        cMensaje := ''Debe indicar si Requiere Pago'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
  ' || '  --
    cResultado := THONAPI.FLUJO_EMISION_SIGO.PRE_EMITE_POLIZA( nCodCia => :nCodCia
                                                             , nCodEmpresa => :nCodEmpresa
                                                             , nIdPoliza => :nIdPoliza
                                                             , cIndRequierePago => :cIndRequierePago );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se puede Pre-Emitir la Póliza con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": tru' || 'e,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

    
        
COMMIT;

END;