
-- Generated by ORDS REST Data Services 22.3.0.r2781755
-- Schema: SICAS_OC  Date: Thu Feb 19 09:56:08 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SICAS_OC',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'sicas',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'thona-api',
      p_base_path      => '/siniestros/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_poliza',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_poliza',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado_texto VARCHAR2(32767);
    v_resultado CLOB;
BEGIN
    v_resultado := FN_OBTIENE_POLIZAS_POR_ASEGURADO2(
        p_codasegurado => :p_codasegurado,
        p_codcia      => :p_codcia,
        p_codempresa  => :p_codempresa
    );

 -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    -- Enviar el JSON resultante
    --HTP.PRN(v_resultado);
     IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron polizas con este codigo de asegurado",
            "data": []
        }'');
    ELSE
    ' || '    -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;
    
    
EXCEPTION
    WHEN OTHERS THEN
          -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

        --HTP.PRN(''{ "error": "'' || SQLERRM || ''" }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_recibos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_recibos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_output    VARCHAR2(32767);
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTIENE_RECIBOS(
        p_IdPoliza => :p_idpoliza,
        p_CodCia   => :p_codcia,
        p_CodEmpresa   => :p_codempresa        
    );

    -- Extrae hasta 32,767 caracteres para evitar error con HTP.PRN
    v_output := DBMS_LOB.SUBSTR(v_resultado, 32767, 1);
  -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;


    -- Configurar e' || 'l encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron recibos con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
     OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
     OWA_UTIL.HTTP_HEADER_CLOSE;

        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'valida_cuenta',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'valida_cuenta',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_clabe_valida BOOLEAN;
BEGIN
    -- Validar el token de seguridad
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Validar el parámetro obligatorio p_clabe
    IF :p_clabe IS NULL OR LENGTH(TRIM(:p_clabe)) = 0 THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "El parámetro p_clabe es obligatorio y no puede estar vacío.",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamar a la función de validación de CLABE
    v_clabe_valida := OC_GENERALES.valida_clabe(:p_clabe);

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', F' || 'ALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Responder en formato JSON según el resultado de la validación
    IF v_clabe_valida THEN
        HTP.PRN(''{
            "success": true,
            "mensaje": "La cuenta CLABE '' || :p_clabe || '' es VÁLIDA.",
            "data": {
                "clabe_valida": true
            }
        }'');
    ELSE
        HTP.PRN(''{
            "success": false,
            "mensaje": "La cuenta CLABE '' || :p_clabe || '' es INVÁLIDA.",
            "data": {
                "clabe_valida": false
            }
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON en caso de error
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "Se produjo un error inesperado: '' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",' || '
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_poliza_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_poliza_id',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Validar que al menos uno de los dos parámetros clave fue recibido
    IF (:p_id_poliza IS NULL OR :p_id_poliza = 0)
       AND (NVL(TRIM(:p_num_pol_unico), '' '') = '' '') THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el ID de póliza o el número de póliza único",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamada a la función que genera el JSON en un CLOB
    v_resultado := FN_OBTIENE_POLIZAS_POR_ID(
        p_id_poliza     => :p_id_poliza,
        p_num_pol_unico => ' || ':p_num_pol_unico,
        p_codcia        => :p_codcia,
        p_codempresa    => :p_codempresa
    );

    -- Configurar encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Validar si el CLOB tiene contenido
    IF v_resultado IS NULL OR DBMS_LOB.GETLENGTH(v_resultado) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron polizas con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Imprimir el CLOB en partes para evitar desbordamientos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '');

        FOR i IN 0 .. FLOOR((DBMS_LOB.GETLENGTH(v_resultado) - 1) / 30000) LOOP
            HTP.PRN(DBMS_LOB.SUBSTR(v_resultado, 30000, i * 30000 + 1));
        END LOOP;

        HTP.PRN(''}'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application' || '/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_pais',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_pais',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTENER_PAIS(
        p_codigo_pais      => :p_codigo_pais, 
        p_descripcion_pais => :p_descripcion_pais
    );

    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := '''';
    END;

    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron países con los parámetros indicado' || 's",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'activa_siniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'activa_siniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_Mensaje VARCHAR2(2000);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    WS_ACTIVA_SINIESTRO(
        p_CodCia      => :p_codcia,
        p_CodEmpresa  => :p_codempresa,
        p_IdPoliza    => :p_idpoliza,
        p_IdetPol     => :p_idetpol,
        p_IdSiniestro => :p_idsiniestro,
        p_Mensaje     => v_Mensaje
    );

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Responder en formato JSON con control de nulos
    IF v_Mensaje IS NOT NULL THEN       
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(NVL(v_Mensaje, ''""''), ''"'', ''\"'') || ''",
            "data": {}' || '
        }'');
    ELSE       
         HTP.PRN(''{
            "success": true,
            "mensaje": "'' || REPLACE(NVL(v_Mensaje, ''Operación realizada correctamente.''), ''"'', ''\"'') || ''",
            "data": {}
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;

        -- Responder con error en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_asegurado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_asegurado',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_COD_ASEGURADO  NUMBER;
    v_Mensaje VARCHAR2(2000);  
    v_FECNAC DATE;
    v_FEC_POL_FINVIG DATE;
BEGIN
     IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Validar parámetros obligatorios
    IF :p_pol_consecutivo IS NULL OR :p_nombre IS NULL OR :p_fecnac IS NULL OR :p_fec_pol_finvig IS NULL THEN
        HTP.PRN(''{
                "success": false,
                "mensaje": "Parámetros obligatorios faltantes o inválidos.",
                "data": {}
            }'');
        RETURN;
    END IF;

    -- Intentar convertir fechas para validar formato
    BEGIN
        v_FECNAC := TO_DATE(:p_fecnac, ''YYYY-MM-DD'');
        v_FEC_POL_FINVIG := TO_DATE(:p_fec_pol_finvig, ''YYYY-MM-DD'');
    EXCEPTION
' || '        WHEN OTHERS THEN            
             HTP.PRN(''{
                "success": false,
                "mensaje": "Formato de fecha inválido.",
                "data": {}
            }'');
            RETURN;
    END;

    -- Llamar al procedimiento WS_ALTA_ASEGURADO con fechas ya validadas
    WS_ALTA_ASEGURADO(
        p_POL_CONSECUTIVO => :p_pol_consecutivo,
        p_EMAIL           => :p_email,       
        p_TIPO_IDTRIBUTARIO => :p_tipo_idtributario,
        p_NOMBRE          => :p_nombre,
        p_APEPAT          => :p_apepat,
        p_APEMAT          => :p_apemat,
        p_FECNAC          => v_FECNAC,
        p_SEXO            => :p_sexo,
        p_TELEFONO        => :p_telefono,
        p_FEC_POL_FINVIG  => v_FEC_POL_FINVIG,
        p_FECSOLICITUD    => SYSDATE,
        p_FECEMISION      => SYSDATE,
        p_TIPO_ENDOSO     => :p_tipo_endoso,
        p_STS_ENDOSO      => :p_sts_endoso,
        p_DESC_ENDOSO     => :p_desc_endoso,
        ' || 'p_MOTIVO_ENDOSO   => :p_motivo_endoso,
        p_IDETPOL         => :p_idetpol,
        p_CODCIA          => :p_codcia,
        p_CODEMPRESA      => :p_codempresa,
        p_COD_ASEGURADO   => v_COD_ASEGURADO
    );

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Responder en formato JSON con control de nulos
    HTP.PRN(''{
        "success": true,
        "mensaje": "mensaje": "Asegurado dado de alta correctamente.",
        "data": { "naseg": '' || NVL(TO_CHAR(v_COD_ASEGURADO), ''null'') || '' }
    }'');

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
     ' || '   }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_beneficiario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_beneficiario',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
	V_NBENEF  NUMBER;
    V_MENSAJE VARCHAR2(2000);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

     -- Llamar al procedimiento WS_CAPTURA_BENEFICIARIO
    WS_CAPTURA_BENEFICIARIO(
        P_IDSINIESTRO        => :p_idsiniestro,
        P_IDPOLIZA           => :p_idpoliza,
        P_COD_ASEGURADO      => :p_codasegurado,
        P_NOMBRE             => :p_nombre,
        P_APELLIDO_PATERNO   => :p_apellidopaterno,
        P_APELLIDO_MATERNO   => :p_apellidomaterno,
        P_FECNAC             => TO_DATE(:p_fecnac, ''YYYY-MM-DD''),
        P_TIPO_ID_TRIBUTARIO => :p_tipoidtributario,
        P_NUM_DOC_TRIBUTARIO => :p_numdoctributario,
        P_SEXO               => :p_sexo,
        P_DIRECCION          =>' || ' :p_direccion,
        P_EMAIL              => :p_email,
        P_ENT_FINANCIERA     => :p_entfinanciera,
        P_NUM_CUENTA_BANCARIA => :p_numcuentabancaria,
        P_CUENTA_CLAVE       => :p_cuentaclave,
        P_TELEFONO_LOCAL     => :p_telefonolocal,
        P_TELEFONO           => :p_telefono,
        P_INDAPLICAISR       => :p_indappliaisr,
        p_CodCia             => :p_codcia,
        p_CodEmpresa         => :p_codempresa,
        P_NBENEF             => V_NBENEF,
        P_MENSAJE            => V_MENSAJE
    );

	-- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
	
    -- Responder en formato JSON
    IF v_Mensaje IS NOT NULL AND v_Mensaje <> '''' THEN        
    HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_Mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
       ' || '     "mensaje": "'' || REPLACE(NVL(v_Mensaje, ''Operación realizada correctamente.''), ''"'', ''\"'') || ''",
            "data": { "nbenef": '' || NVL(TO_CHAR(V_NBENEF), ''null'') || '' }
        }'');
    END IF;
   
EXCEPTION
    WHEN OTHERS THEN
	
		-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_obs_siniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'alta_obs_siniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_mensaje VARCHAR2(2000);
BEGIN
    -- Validación del TOKEN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    WS_REGISTRAR_OBSERVACION_SINIESTRO(
        P_IDSINIESTRO => :p_idsiniestro,
        P_IDPOLIZA    => :p_idpoliza,
        P_FECOBSERV   => TO_DATE(:p_fecobserv, ''YYYY-MM-DD''),
        P_CODUSUARIO  => :p_codusuario,
        P_DESCRIPCION => :p_descripcion,
        P_IDTPOPAGOSIN => :p_idtpopagosin,  
        P_CODCIA      => :p_codcia,
        P_CODEMPRESA  => :p_codempresa,
        P_MENSAJE     => v_mensaje
    );

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    -- Responder en formato JSON
    IF v_' || 'mensaje IS NOT NULL AND v_mensaje <> '''' THEN        
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "'' || REPLACE(NVL(v_mensaje, ''Operación realizada correctamente.''), ''"'', ''\"'') || ''",
            "data": {}
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_asegurado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_asegurado',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_fecha_nac DATE;
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Validar y convertir fecha de nacimiento si viene
    BEGIN
        IF :p_fec_nacimiento IS NOT NULL THEN
            v_fecha_nac := TO_DATE(:p_fec_nacimiento, ''YYYY-MM-DD'');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            OWA_UTIL.HTTP_HEADER_CLOSE;
            HTP.PRN(''{
                "success": false,
                "mensaje": "Formato de fecha inválido.",
                "data": {}
            }'');
            RETURN;
    END;

    
    WS_MODIFICA_ASEGURADO(
        --p_cod_asegurado         => :p_cod_asegurado,
    ' || '    p_tipo_doc_identificacion => :p_tipo_doc_identificacion,
        p_num_doc_identificacion  => :p_num_doc_identificacion,
        p_nombre           => :p_nombre,
        p_apellido_paterno => :p_apellido_paterno,
        p_apellido_materno => :p_apellido_materno,
        p_tipo_persona     => :p_tipo_persona,
        p_fec_nacimiento   => v_fecha_nac,
        p_direcres         => :p_direcres,
        p_num_interior     => :p_num_interior,
        p_num_exterior     => :p_num_exterior,
        p_codcolonia       => :p_codcolonia,
        p_codcorrres       => :p_codcorrres,
        p_codprovres       => :p_codprovres,
        p_codpaisres       => :p_codpaisres,
        p_codposres        => :p_codposres,
        p_email            => :p_email,
        p_telefono         => :p_telefono
    );

    -- Respuesta exitosa
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    HTP.PRN(''{
        "success": true,
        "mensaje"' || ': "Registro modificado correctamente.",
        "data": { }
    }'');

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_beneficiario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_beneficiario',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_mensaje VARCHAR2(2000);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    WS_MODIFICA_BENEFICIARIO(
        p_benef               => :p_benef,
        p_idsiniestro         => :p_idsiniestro,
        p_idpoliza            => :p_idpoliza,
        p_certificado         => :p_certificado,
        p_codasegurado       => :p_codasegurado,        
        p_nombre              => :p_nombre,
        p_apellidopaterno    => :p_apellidopaterno,
        p_apellidomaterno    => :p_apellidomaterno,
        p_fecnac              => TO_DATE(:p_fecnac, ''YYYY-MM-DD''),
        p_tipoidtributario  => :p_tipoidtributario,
        p_numdoctributario  => :p_numdoctributario,
        p_sexo                => :p_sexo,
  ' || '      p_direccion           => :p_direccion,
        p_email               => :p_email,
        p_entfinanciera      => :p_entfinanciera,
        p_numcuentabancaria => :p_numcuentabancaria,
        p_cuentaclave        => :p_cuentaclave,
        p_telefonolocal      => :p_telefonolocal,
        p_telefono            => :p_telefono,
        p_indaplicaisr        => :p_indaplicaisr,
        p_indirrevocable      => :p_indirrevocable,
        p_mensaje             => v_mensaje
    );

    -- Configurar el encabezado JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Responder en formato JSON
    IF v_mensaje IS NOT NULL AND v_mensaje <> '''' THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "Beneficiario modificado correctamente.",' || '
            "data": {}
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_datos_bancarios',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_datos_bancarios',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_mensaje VARCHAR2(2000);
BEGIN
    -- Validación del TOKEN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    WS_MODIFICA_DATOS_BANCARIOS(
        P_BENEF => :p_benef,
        P_IDSINIESTRO => :p_idsiniestro,
        P_IDPOLIZA    => :p_idpoliza,
        P_COD_ASEGURADO => :p_codasegurado,
        P_NUM_CUENTA_BANCARIA => :p_numcuentabancaria,
        P_CUENTA_CLAVE => :p_cuentaclabe,
        P_ENT_FINANCIERA => :p_entfinanciera,
        P_MENSAJE => v_mensaje
    );

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    -- Responder en formato JSON
    IF v_mensaje IS NOT NULL AND v_mensaje <> '''' THEN        
      ' || '  HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "'' || REPLACE(NVL(v_mensaje, ''Operación realizada correctamente.''), ''"'', ''\"'') || ''",
            "data": {}
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_siniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'modifica_siniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_mensaje VARCHAR2(2000);
BEGIN
     -- Validar si el token es nulo o vacío
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;
    
    WS_MODIFICA_SINIESTRO(
        p_idsiniestro        => :p_idsiniestro,
        p_refsiniestro       => :p_refsiniestro,
        p_tiposiniestro      => :p_tiposiniestro,
        p_fechaocurrencia  => TO_DATE(:p_fechaocurrencia, ''YYYY-MM-DD''),
        p_fechanotificacion => TO_DATE(:p_fechanotificacion, ''YYYY-MM-DD''),
        p_descsiniestro      => :p_descsiniestro,
        p_montoreserva       => :p_montoreserva,
        p_montopago          => :p_montopago,
        p_codmoneda          => :p_codmoneda,
        p_codasegurado       => :p_codasegurado,
        p_codusuario       ' || '  => :p_codusuario,
        p_submotivo          => :p_submotivo,
        p_codriesgorea       => :p_codriesgorea,
        p_idcontributorio    => :p_idcontributorio,
        p_numtributario      => :p_numtributario,
        p_codmunicipio       => :p_codmunicipio,
        p_empresalabora      => :p_empresalabora,
        p_motivosiniestro    => :p_motivosiniestro,
        p_codproveedor       => :p_codproveedor,
        p_nommedicocertifica => :p_nommedicocertifica,
        p_idcedulamedica     => :p_idcedulamedica,
        p_tipoasegurado      => :p_tipoasegurado,
        p_idcredito          => :p_idcredito
    );

    v_mensaje := ''Siniestro modificado con éxito.'';
    -- Responder con mensaje en JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --HTP.PRN(''{ "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''" }'');
    HTP.PRN(''{
            "success": true,
            "mensaje": "'' || REPLACE(NVL(v_mensaje, ''Operac' || 'ión realizada correctamente.''), ''"'', ''\"'') || ''",
            "data": {}
        }'');
EXCEPTION
    WHEN OTHERS THEN
        v_mensaje := ''Error al modificar siniestro: '' || SQLERRM;
        -- Responder con error en formato JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        --HTP.PRN(''{ "error": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''" }'');
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_asegurado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_asegurado',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamada a la función con los parámetros de búsqueda
    v_resultado := FN_BUSCAR_ASEGURADOS(
        p_tipo_doc_identificacion => :p_tipo_doc_identificacion,
        p_num_doc_identificacion => :p_num_doc_identificacion,
        p_nombre => :p_nombre,
        p_apellido_paterno => :p_apellido_paterno,
        p_apellido_materno => :p_apellido_materno,
        p_fec_nacimiento => TO_DATE(:p_fec_nacimiento, ''YYYY-MM-DD''),
        p_CodCia      => :P_CODCIA,
        p_CodEmpresa  => :P_CODEMPRESA
    );

  -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := ' || 'DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;

    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Verificar si v_resultado está vacío o es nulo
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron asegurados con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON en caso de error
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
     ' || '   OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{ "error": "'' || SQLERRM || ''" }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_beneficiario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_beneficiario',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTENER_BENEFICIARIO(
        p_idpoliza      => :p_id_poliza,
        p_cod_asegurado => :p_cod_asegurado
    );

    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := '''';
    END;

    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron beneficiarios para el asegurado indica' || 'do",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_causasiniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_causasiniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    l_offset    INTEGER := 1;
    l_chunk     VARCHAR2(32767);
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamar a la función para obtener las causas de siniestro
    v_resultado := FN_OBTENER_CAUSAS_SINIESTRO(
        p_codvalor => :p_codvalor,
        p_descval  => :p_descval
    );

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Evaluar contenido del CLOB
    IF v_resultado IS NULL OR DBMS_LOB.GETLENGTH(v_resultado) < 3 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron causas de siniestro con los parámetros indicados o hubo' || ' un problema.",
            "data": []
        }'');
    ELSIF DBMS_LOB.INSTR(v_resultado, ''{ "error"'') > 0 THEN
        -- Extraer mensaje de error dentro del JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "Error de la base de datos",
            "data": []
        }'');
    ELSE
        -- Construir JSON correctamente fragmentado
        HTP.PRN(''{ "success": true, "mensaje": "", "data": '');
        WHILE l_offset <= DBMS_LOB.GETLENGTH(v_resultado) LOOP
            l_chunk := DBMS_LOB.SUBSTR(v_resultado, 32767, l_offset);
            HTP.PRN(l_chunk);
            l_offset := l_offset + LENGTH(l_chunk);
        END LOOP;
        HTP.PRN('' }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Manejo de errores general
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', '''''''') || ''",
   ' || '         "data": []
        }'');
END;
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_coberturas',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_coberturas',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_output    VARCHAR2(32767);
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;
    
    v_resultado := FN_OBTENER_COBERTURAS(:p_idpoliza, :p_codsubgrupo, :p_codasegurado, :p_codcia, :p_codempresa);
    v_output := DBMS_LOB.SUBSTR(v_resultado, 32767, 1);

    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;

    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --HTP.PRN(v_output);
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN' || '
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron coberturas con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_output, ''{}'') || ''
        }'');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

        HTP.PRN(''{
            "success": false,
            "mensaje": '' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_diagnosticos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_diagnosticos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    l_offset    INTEGER := 1;
    l_chunk     VARCHAR2(32767);
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamar a la función para obtener los diagnósticos
    v_resultado := FN_OBTENER_DIAGNOSTICO(
        p_nombre_concepto => :p_codvalor,
        p_valor_largo     => :p_descval
    );

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir respuesta JSON de forma segura
    IF v_resultado IS NULL OR DBMS_LOB.GETLENGTH(v_resultado) < 10 THEN 
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron diagnósticos con los parámetros indica' || 'dos",
            "data": []
        }'');
    ELSIF DBMS_LOB.INSTR(v_resultado, ''{ "error"'') > 0 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "Error de la base de datos",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{ "success": true, "mensaje": "", "data": '');
        WHILE l_offset <= DBMS_LOB.GETLENGTH(v_resultado) LOOP
            l_chunk := DBMS_LOB.SUBSTR(v_resultado, 32767, l_offset);
            HTP.PRN(l_chunk);
            l_offset := l_offset + LENGTH(l_chunk);
        END LOOP;
        HTP.PRN('' }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', '''''''') || ''",
            "data": []
        }'');
END;
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_domicilio',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_domicilio',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTENER_COLONIA(
        p_codigo_postal        => :p_codigo_postal, 
        p_descripcion_colonia  => :p_descripcion_colonia, 
        p_descripcion_municipio => :p_descripcion_municipio
    );
    
      -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;


    	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        O' || 'WA_UTIL.HTTP_HEADER_CLOSE;

    --HTP.PRN(v_resultado);
     -- Verificar si v_resultado está vacío o es nulo
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron domicilios con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_entidadf',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_entidadf',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTENER_ENTIDADF(        
        p_codentidad  => :p_codentidad,
        p_descentidad => :p_descentidad,
        p_codcia      => :p_codcia,
        p_codempresa  => :p_codempresa
    );
    
       -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;


    	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UT' || 'IL.HTTP_HEADER_CLOSE;

    -- Enviar el JSON resultante
    --HTP.PRN(v_resultado);
     IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron entidades financieras con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN

        	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_estado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_estado',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    IF NVL(:p_codigo_pais, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el codigo de pais",
            "data": {}
        }'');
        RETURN;
    END IF;

    v_resultado := FN_OBTENER_ESTADO(
        p_codigo_pais        => :p_codigo_pais,
        p_codigo_estado      => :p_codigo_estado, 
        p_descripcion_estado => :p_descripcion_estado
    );

    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION' || '
        WHEN OTHERS THEN
            v_resultado_texto := '''';
    END;

    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;

    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron estados con los parámetros indicados",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_hospitales',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_hospitales',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    l_offset    INTEGER := 1;
    l_chunk     VARCHAR2(32767);
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Validar que al menos se indique p_codproveedor o p_nombre_hospital (mínimo 3 caracteres)
    /*IF :p_codvalor IS NULL AND (NVL(:p_descval, '' '') = '' '' OR LENGTH(TRIM(:p_descval)) < 3) THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el código del proveedor o un nombre de hospital de al menos 3 caracteres",
            "data": []
        }'');
        RETURN;
    END IF;*/

    -- Llamar a la función para obtener los' || ' hospitales
    v_resultado := FN_OBTENER_HOSPITALES(
        p_codproveedor    => :p_codvalor,
        p_nombre_hospital => :p_descval
    );

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir respuesta JSON de forma segura
    IF v_resultado IS NULL OR DBMS_LOB.GETLENGTH(v_resultado) < 10 THEN 
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron hospitales con los parámetros indicados",
            "data": []
        }'');
    ELSIF DBMS_LOB.INSTR(v_resultado, ''{ "error"'') > 0 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "Error de la base de datos",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{ "success": true, "mensaje": "", "data": '');
        WHILE l_offset <= DBMS_LOB.GETLENGTH(v_resultado) LOOP
            l_chunk := DBMS_LOB.SUBSTR(v_resultado, 32767, l_offset);
            HTP.PRN(' || 'l_chunk);
            l_offset := l_offset + LENGTH(l_chunk);
        END LOOP;
        HTP.PRN('' }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', '''''''') || ''",
            "data": []
        }'');
END;
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_municipios',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_municipios',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

        IF NVL(:p_codigo_pais, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el codigo de pais",
            "data": {}
        }'');
        RETURN;
    END IF;


        IF NVL(:p_codigo_estado, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el codigo de estado",
            "data": {}
        }'');
        RETURN;
 ' || '   END IF;

    -- Validar que al menos se indique p_codmunicipio o p_descmunicipio (con mínimo 3 caracteres para la descripción)
   /* IF :p_codmunicipio IS NULL AND (NVL(:p_descmunicipio, '' '') = '' '' OR LENGTH(TRIM(:p_descmunicipio)) < 3) THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el código del municipio o una descripción de al menos 3 caracteres",
            "data": {}
        }'');
        RETURN;
    END IF;*/

    -- Llamar a la función para obtener los municipios
    v_resultado := FN_OBTENER_MUNICIPIOS(
        p_codigo_pais   => :p_codigo_pais,
        p_codigo_estado => :p_codigo_estado,
        p_codmunicipio  => :p_codmunicipio,
        p_descmunicipio => :p_descmunicipio
    );

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir' || ' respuesta JSON
    IF v_resultado IS NULL OR DBMS_LOB.GETLENGTH(v_resultado) < 10 THEN 
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron municipios con los parámetros indicados",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Manejo de errores general
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_regimen',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_regimen',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_auth_header VARCHAR2(32767);
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Obtener el encabezado Authorization
    --v_auth_header := OWA_UTIL.GET_CGI_ENV(''HTTP_AUTHORIZATION'');
     v_resultado := FN_OBTENER_REGIMEN_FISCAL(
        p_IDREGFISSAT      => :p_id,
        p_DESCTIPOREGIMEN  => :p_desc
    );

    -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;


    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HE' || 'ADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir el valor del encabezado Authorization en formato JSON
    --HTP.PRN(''{ "v_auth_header": "'' || NVL(v_auth_header, ''NULL'') || ''" }'');
    
    --HTP.PRN(v_resultado);
     -- Verificar si v_resultado está vacío o es nulo
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontro regimen con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
         HTP.PRN(''{
            "success": fal' || 'se,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_requistos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_requistos',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_auth_header VARCHAR2(32767);
    v_resultado_texto VARCHAR2(32767);
    v_output    VARCHAR2(32767);
BEGIN
   IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;


    v_resultado := FN_OBTIENE_REQUISITOS_COB(
        P_IDPOLIZA     => :p_idpoliza,
        P_CODASEGURADO => :p_codasegurado,
        P_CODSUBGRUPO  => :p_codsubgrupo,
        P_CODCIA       => :p_codcia,
        P_CODEMPRESA   => :p_codempresa
    );


    -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;

    v_output' || ' := DBMS_LOB.SUBSTR(v_resultado, 32767, 1);


    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontro requisitos con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_output, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        	-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_siniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_siniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamada a la función con los parámetros
    v_resultado := FN_OBTIENE_SINIESTROS(
        p_id_poliza     => :p_idpoliza,
        p_cod_asegurado => :p_codasegurado,
        p_cod_subgrupo  => :p_codsubgrupo,
        p_cod_cia       => :p_codcia,
        p_cod_empresa   => :p_codempresa
    );


  -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;

    -- Configurar el encabezado para' || ' JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    -- Enviar el JSON resultante 
     -- Verificar si v_resultado está vacío o es nulo
    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron siniestros con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_tipoasegurado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_tipoasegurado',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamar a la función para obtener los tipos de asegurado
    v_resultado := FN_OBTENER_TIPOS_ASEGURADO(
        p_codvalor => :p_codvalor,
        p_descval  => :p_descval
    );

    -- Convertir CLOB a VARCHAR2 para validación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1);
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := '''';
    END;

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir respuesta JSON
    IF v_resultado_texto IS ' || 'NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron tipos de asegurado con los parámetros indicados",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Manejo de errores general
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_tiposiniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_tiposiniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
BEGIN
    -- Validar token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Llamar a la función para obtener los tipos de siniestro
    v_resultado := FN_OBTENER_TIPO_SINIESTROS(
        p_codvalor => :p_codvalor,
        p_descval  => :p_descval
    );

    -- Convertir CLOB a VARCHAR2 para validación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1);
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := '''';
    END;

    -- Establecer cabecera HTTP
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Imprimir respuesta JSON
    IF v_resultado_texto IS ' || 'NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron tipos de siniestro con los parámetros indicados",
            "data": []
        }'');
    ELSE
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Manejo de errores general
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'registra_siniestro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'registra_siniestro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_Mensaje VARCHAR2(2000);
    v_IdSiniestro  NUMBER;
BEGIN
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    WS_INSERTAR_SINIESTRO(
    p_IdPoliza         => :p_idpoliza,
    p_IdetPol          => :p_idetpol,
    p_CodCia           => :p_codcia,
    p_CodEmpresa       => :p_codempresa,
    p_TipoSiniestro    => :p_tiposiniestro,
    p_RefSiniestro     => :p_refsiniestro,
    p_FecOcurrencia    => TO_DATE(:p_fechaocurrencia, ''YYYY-MM-DD''),
    p_FecNotificacion  => TO_DATE(:p_fechanotificacion, ''YYYY-MM-DD''),
    p_DescSiniestro    => :p_descsiniestro,
    p_MontoReserva     => :p_montoreserva,
    p_MontoPago        => :p_montopago,
    p_CodMoneda        => :p_codmoneda,
    p_CodAsegurado     => :p_coda' || 'segurado,
    p_CodUsuario       => :p_codusuario,
    p_Submotivo        => :p_submotivo,
    p_CodRiesgoRea     => :p_codriesgorea,
    p_IdContribuyente  => :p_idcontributorio,
    p_NumTributario    => :p_numtributario,
    p_Curp             => :p_curp,
    p_CodPais          => :p_codpais,
    p_CodProv          => :p_codprov,
    p_CodMunicipio     => :p_codmunicipio,
    p_EmpresaLabora    => :p_empresalabora,
    p_MotivoSiniestro  => :p_motivosiniestro,
    p_CodProveedor     => :p_codproveedor,
    p_NomMedico        => :p_nommedicocertifica,
    p_IdCedulaMedica   => :p_idcedulamedica,
    p_TipoAsegurado    => :p_tipoasegurado,
    p_IdCredito        => :p_idcredito,
    p_IdSiniestro      => v_IdSiniestro,
    p_Mensaje          => :p_mensaje
);


		-- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

    -- Responder en formato JSON con control de nulos
    IF v_' || 'Mensaje IS NOT NULL THEN
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(v_mensaje, ''"'', ''\"'') || ''",
            "data": {}
        }'');
    ELSE
         HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": {
                "IdSiniestro": '' || v_IdSiniestro || ''
            }
        }'');
        
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_token',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_token',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_mensaje VARCHAR2(2000);
BEGIN
    
    IF NVL(:p_usuario, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el usuario",
            "data": {}
        }'');
        RETURN;
    END IF;

     IF NVL(:p_password, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el password",
            "data": {}
        }'');
        RETURN;
    END IF;

    
    -- Configurar el encabezado para JSON
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    
    -- Responder en formato JSON
   HTP.PRN(''{
            "success": true,
            "mensaje": "Token generado correctamente.",
            "data": {
                "token": ' || '"Vkc5clpXNVFjblZsWW1Ga1pWUm9iMjVoWDFWVFJWSTZVRUZUVXc9PQ=="
            }
        }'');

EXCEPTION
    WHEN OTHERS THEN
        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
        -- Manejar errores y devolver mensaje en JSON
        HTP.PRN(''{
            "success": false,
            "mensaje": "'' || REPLACE(SQLERRM, ''"'', ''\"'') || ''",
            "data": {}
        }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_parentesco',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'thona-api',
      p_pattern        => 'obtiene_parentesco',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_resultado CLOB;
    v_resultado_texto VARCHAR2(32767);
    v_token_valido NUMBER;
BEGIN
   
    -- Validar si se proporcionó un token
    IF NVL(:p_token, '' '') = '' '' THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "Debe indicar el TOKEN",
            "data": {}
        }'');
        RETURN;
    END IF;

    -- Verificar si el token es válido
    /*v_token_valido := FN_VALIDAR_TOKEN(:p_token);

    IF v_token_valido = 0 THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
            "success": false,
            "mensaje": "El TOKEN es inválido o ha expirado",
            "data": {}
        }'');
        RETURN;
    END IF;*/

    v_resultado := FN_OBTENER_PARENTESCO(
        p_CodParentesco => :p_codparentesco,
        p_DescParentesco => :p_descparentesco' || '
    );
    
       -- Convertir el CLOB a VARCHAR2 para comparación
    BEGIN
        v_resultado_texto := DBMS_LOB.SUBSTR(v_resultado, 32767, 1); 
    EXCEPTION
        WHEN OTHERS THEN
            v_resultado_texto := ''''; -- Si no se puede convertir, dejamos vacío
    END;


        -- Configurar el encabezado para JSON
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;

    IF v_resultado_texto IS NULL OR LENGTH(TRIM(v_resultado_texto)) < 10 THEN
        HTP.PRN(''{
            "success": false,
            "mensaje": "No se encontraron parentescos con los parametros indicados",
            "data": []
        }'');
    ELSE
        -- Mostrar el resultado si hay datos
        HTP.PRN(''{
            "success": true,
            "mensaje": "",
            "data": '' || NVL(v_resultado, ''{}'') || ''
        }'');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        	-- Configurar el encabezado para JSON
        OW' || 'A_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        
         HTP.PRN(''{
            "success": false,
            "mensaje": "'' || SQLERRM || ''",
            "data": []
        }'');

END;
');

    
        
COMMIT;

END;