
-- Generated by ORDS REST Data Services 22.3.0.r2781755
-- Schema: SICAS_OC  Date: Thu Feb 19 09:55:45 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SICAS_OC',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'sicas',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'catalogos_SIGO',
      p_base_path      => '/catalogos_SIGO/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'endosos_producto',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'endosos_producto',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un codigo de compañia'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un codigo de empresa'';
    ELSIF :cIdTipoSeg IS NULL THEN
        cMensaje := ''Debe indicar un tipo de seguro'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para la consulta del catálogo
    cResultado := THONAPI.CATALOGOS_SIGO' || '.ENDOSOS_PRODUCTO( nCodCia     => :nCodCia
                                                         , nCodEmpresa => :nCodEmpresa
                                                         , cIdTipoSeg  => :cIdTipoSeg );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron endosos con los parámetros indicados",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
         ' || '       DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'planes_coberturas',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'planes_coberturas',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cIdTipoSeg IS NULL THEN
        cMensaje := ''Debe indicar un tipo de seguro'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CA' || 'TALOGOS_SIGO.PLANES_COBERTURAS( nCodCia     => :nCodCia
                                                          , nCodEmpresa => :nCodEmpresa
                                                          , cIdTipoSeg  => :cIdTipoSeg );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron planes de cobertura con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
  ' || '          BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'cotizadores_plancob',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'cotizadores_plancob',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cCodCotizador IS NULL THEN
        cMensaje := ''Debe indicar un código de cotizador'';
    ELSIF :cIdTipoSeg IS NULL THEN
        cMensaje := ''Debe indicar un tipo de seguro'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
' || '    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.COTIZADORES_PLANCOB( nCodCia       => :nCodCia
                                                            , nCodEmpresa   => :nCodEmpresa
                                                            , cCodCotizador => :cCodCotizador
                                                            , cIdTipoSeg    => :cIdTipoSeg );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron planes de cobertura con los parámetros indicados",
                    "data": []
            ' || '    }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'categorias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'categorias',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cCodTipoNegocio IS NULL THEN
        cMensaje := ''Debe indicar un tipo de negocio'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THON' || 'API.CATALOGOS_SIGO.CATEGORIA( nCodCia         => :nCodCia
                                                  , nCodEmpresa     => :nCodEmpresa
                                                  , cCodTipoNegocio => :cCodTipoNegocio );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron categorías con los parámetros indicados",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
           ' || ' BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'listas_de_valores',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'listas_de_valores',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Validar parámetros obligatorios
    IF :cCodLista IS NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "Debe indicar un código de lista",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.LISTAS_DE_VALORES( cCodLista => :cCodLista );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOS' || 'E;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron listas de valores con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
  ' || '                  "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'planes_de_pagos',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'planes_de_pagos',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.PLANES_DE_PAGOS( nCodCia     => :nCodCia
                                    ' || '                    , nCodEmpresa => :nCodEmpresa );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron planes de pagos con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);' || '
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'codigos_postales',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'codigos_postales',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.CODIGOS_POSTALES( cCodPostal    => :cCodPostal
                                                         , cCodPais      => :cCodPais
                                                         , cCodEstado    => :cCodEstado
                                                         , cCodCiudad    => :cCodCiudad
                                                         , cCodMunicipio => :cCodMunicipio
                                                         , cCodColonia   => :cCodColonia );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32760, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '' '';
    END;
    --
    OWA_UTIL' || '.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron códigos postales con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                    "success": true,
                   "mensaje": "",
                    "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/jso' || 'n'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'notas_aclaratorias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'notas_aclaratorias',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.NOTAS_ACLARATORIAS( nCodCia     => :nCodCia
                                 ' || '                          , nCodEmpresa => :nCodEmpresa );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron clausulas de notas aclaratorias con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
            ' || '    HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'paquetes_comerciales',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'paquetes_comerciales',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cIdTipoSeg IS NULL THEN
        cMensaje := ''Debe indicar un tipo de seguro'';
    ELSIF :cPlanCob IS NULL THEN
        cMensaje := ''Debe indicar un plan de coberturas'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    --' || ' Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.PAQUETES_COMERCIALES( nCodCia     => :nCodCia
                                                             , nCodEmpresa => :nCodEmpresa
                                                             , cIdTipoSeg  => :cIdTipoSeg
                                                             , cPlanCob    => :cPlanCob );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron paquetes comerciales con los parámetros indicados",
                    "data": []
                }'');
    ' || 'ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'tipos_de_seguros',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'tipos_de_seguros',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cCodProducto IS NULL THEN
        cMensaje := ''Debe indicar un código de producto'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THON' || 'API.CATALOGOS_SIGO.TIPOS_DE_SEGURO( nCodCia      => :nCodCia
                                                        , nCodEmpresa  => :nCodEmpresa
                                                        , cCodProducto => :cCodProducto );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron tipos de seguros con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
' || '            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'cotizadores_tiposeg',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'cotizadores_tiposeg',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :cCodCotizador IS NULL THEN
        cMensaje := ''Debe indicar un código de cotizador'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := TH' || 'ONAPI.CATALOGOS_SIGO.COTIZADORES_TIPOSEG( nCodCia       => :nCodCia
                                                            , nCodEmpresa   => :nCodEmpresa
                                                            , cCodCotizador => :cCodCotizador );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron tipos de seguros con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}''' || ');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'tipos_reaseguros',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'tipos_reaseguros',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "Debe indicar un código de compañía",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.TIPOS_REASEGURO( nCodCia => :nCodCia );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
 ' || '   --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron tipos de reaseguros con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
     ' || '               "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'estados_pais',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'estados_pais',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Validar parámetros obligatorios
    IF :cCodPais IS NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "Debe indicar el País del cual requiere consultar sus Estados",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio que devuelve el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.ESTADOS_PAIS( cCodPais => :cCodPais );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UT' || 'IL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron Estados para el País Indicado",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{' || '
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'regimen_fiscal',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'regimen_fiscal',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Ejecuto el servicio que devuelve el catálogo correspondiente
    cResultado := THONAPI.CATALOGOS_SIGO.REGIMEN_FISCAL;
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron Regímenes Fiscales",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
' || '        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'uso_cfdi',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'uso_cfdi',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
       cMensaje := ''Debe indicar un Código de Compañía'';
    ELSIF :nIdRegFisSat IS NULL THEN
       cMensaje := ''Debe indicar el Régimen Fiscal'';
    ELSIF :cTipoPersona IS NULL THEN
       cMensaje := ''Debe indicar el Tipo de Persona'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio de actualización de información del asegurado
    cResultado := THONAPI.' || 'CATALOGOS_SIGO.USO_CFDI( nCodCia      => :nCodCia
                                                 , nIdRegFisSat => :nIdRegFisSat
                                                 , cTipoPersona => :cTipoPersona );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron Uso de CFDI con los parámetros indicados",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
         ' || '       DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'objeto_impuesto',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'objeto_impuesto',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "Debe indicar un código de compañía",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecutar el servicio para la consulta del catálogo
    cResultado := THONAPI.CATALOGOS_SIGO.OBJETO_IMPUESTO( nCodCia => :nCodCia );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    I' || 'F cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontraron Objetos de Impuesto con los parámetros indicados",
                    "data": []
                }'');
    ELSE
         HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                ' || '    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'estructura_agentes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'catalogos_SIGO',
      p_pattern        => 'estructura_agentes',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    cResultado        CLOB;
    cResultado_texto  VARCHAR2(32767);
    nIncrementar      INTEGER := 4000;
    nPosicion         INTEGER := 1;
    cBuffer           VARCHAR2(4000);
    cMensaje          VARCHAR2(500);
BEGIN
    -- Validar parámetros obligatorios
    IF :nCodCia IS NULL THEN
        cMensaje := ''Debe indicar un código de compañía'';
    ELSIF :nCodEmpresa IS NULL THEN
        cMensaje := ''Debe indicar un código de empresa'';
    ELSIF :nCodAgente IS NULL THEN
        cMensaje := ''Debe indicar una clave de agente'';
    END IF;
    --
    IF cMensaje IS NOT NULL THEN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || cMensaje || ''",
                    "data": {}
                }'');
        RETURN;
    END IF;
    -- Ejecuto el servicio para recuperar el catálogo correspondiente
    cResultado := THONAPI.' || 'CATALOGOS_SIGO.ESTRUCTURA_AGENTES( nCodCia     => :nCodCia
                                                           , nCodEmpresa => :nCodEmpresa
                                                           , nCodAgente  => :nCodAgente );
    --
    BEGIN
        cResultado_texto := DBMS_LOB.SUBSTR(cResultado, 32767, 1); 
    EXCEPTION
    WHEN OTHERS THEN
        cResultado_texto := '''';
    END;
    --
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
    OWA_UTIL.HTTP_HEADER_CLOSE;
    --
    IF cResultado_texto IS NULL OR LENGTH(TRIM(cResultado_texto)) < 10 THEN
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "No se encontró una estructura de agentes con los parámetros indicados",
                    "data": []
                }'');
    ELSE
        HTP.PRN(''{
                   "success": true,
                   "mensaje": "",
                   "data": '');
        cResultado := NVL(cResultado, ''{}'');
        ' || 'LOOP
            BEGIN
                DBMS_LOB.READ( cResultado, nIncrementar, nPosicion, cbuffer );
                nPosicion := nPosicion + nIncrementar;
                HTP.PRN(cbuffer);
            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                EXIT;
            END;
        END LOOP;
        --
        HTP.PRN(''}'');
    END IF;
EXCEPTION
WHEN OTHERS THEN
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);    
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.PRN(''{
                    "success": false,
                    "mensaje": "'' || SQLERRM || ''",
                    "data": []
                }'');
END;');

    
        
COMMIT;

END;