--<TABLA QUE SE UTILIZA EN MIGRACION SICAS - APEX>
--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM TMP_AGENTES_SUSP;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.TMP_AGENTES_SUSP;

/

--CREACION DE TABLA CONF_ASISTENCIA_APPL PARA LA CONFIGURACION DE LOS COLORES POR AREA Y DIAS ESPECIALES.
CREATE TABLE SICAS_OC.TMP_AGENTES_SUSP(
                                COD_AGENTE		NUMBER          NOT NULL
                                ,CODUSR       	VARCHAR2(50)    NOT NULL
                                ) TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.TMP_AGENTES_SUSP_IDX1 ON SICAS_OC.TMP_AGENTES_SUSP (COD_AGENTE,CODUSR) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.TMP_AGENTES_SUSP ADD CONSTRAINT PK_TMP_AGENTES_SUSP PRIMARY KEY (COD_AGENTE,CODUSR) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.TMP_AGENTES_SUSP TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.TMP_AGENTES_SUSP TO ROL_CONSULTA_SICAS;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.TMP_AGENTES_SUSP.COD_AGENTE	IS 'CODIGO DEL AGENTE';
COMMENT ON COLUMN SICAS_OC.TMP_AGENTES_SUSP.CODUSR		IS 'CODIGO DEL USUARIO';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM TMP_AGENTES_SUSP FOR SICAS_OC.TMP_AGENTES_SUSP;
