--<TABLA QUE SE UTILIZA EN MIGRACION SICAS - APEX>
--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM REPORTES_PDF;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.REPORTES_PDF;

/

--CREACION DE TABLA CONF_ASISTENCIA_APPL PARA LA CONFIGURACION DE LOS COLORES POR AREA Y DIAS ESPECIALES.
CREATE TABLE SICAS_OC.REPORTES_PDF(
                                ID			NUMBER          NOT NULL
                                ,NOMBRE     VARCHAR2(100) 	NOT NULL
								,ARCHIVO	BLOB
								,CODUSUARIO	VARCHAR2(100)	NOT NULL
								,FECHA		DATE
                                ) SEGMENT CREATION IMMEDIATE TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.REPORTES_PDF_IDX1 ON SICAS_OC.REPORTES_PDF (ID,CODUSUARIO) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.REPORTES_PDF ADD CONSTRAINT PK_REPORTES_PDF PRIMARY KEY (ID,CODUSUARIO) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.REPORTES_PDF TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.REPORTES_PDF TO ROL_CONSULTA_SICAS;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.REPORTES_PDF.ID			IS 'COLUMAN DE IDENTIFICADOR UNICO DE LA TABLA';
COMMENT ON COLUMN SICAS_OC.REPORTES_PDF.NOMBRE		IS 'NOMBRE DEL DOCUMENTO QUE SE GENERA';
COMMENT ON COLUMN SICAS_OC.REPORTES_PDF.ARCHIVO		IS 'CONTENIDO DEL DOCUEMTNO QUE SE GENERA';
COMMENT ON COLUMN SICAS_OC.REPORTES_PDF.CODUSUARIO	IS 'CODIGO DEL USUARIO QUE GENERA EL ARCHIVO';
COMMENT ON COLUMN SICAS_OC.REPORTES_PDF.FECHA		IS 'FECHA DE CREACION DEL DCUEMTNO QUE SE GENERA';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM REPORTES_PDF FOR SICAS_OC.REPORTES_PDF;
