--<TABLA QUE SE UTILIZA EN MIGRACION SICAS - APEX>
--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM EXTRACCION_DE_REPORTES;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.EXTRACCION_DE_REPORTES;

/

--CREACION DE TABLA CONF_ASISTENCIA_APPL PARA LA CONFIGURACION DE LOS COLORES POR AREA Y DIAS ESPECIALES.
CREATE TABLE SICAS_OC.EXTRACCION_DE_REPORTES(
                                IDEXTRACCION 	NUMBER          NOT NULL
                                ,TIPO_REPORTE	VARCHAR2(100) 	NOT NULL
								,CODUSR			VARCHAR2(100) 	NOT NULL
								,FECREPORTE		DATE
								,STATUS			VARCHAR2(100)
								,REPORTE		BLOB
								,FILE_NAME		VARCHAR2(250)
                                ) SEGMENT CREATION IMMEDIATE TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.EXTRACCION_DE_REPORTES_IDX1 ON SICAS_OC.EXTRACCION_DE_REPORTES (IDEXTRACCION,CODUSR) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.EXTRACCION_DE_REPORTES ADD CONSTRAINT PK_EXTRACCION_DE_REPORTES PRIMARY KEY (IDEXTRACCION,CODUSR) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.EXTRACCION_DE_REPORTES TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.EXTRACCION_DE_REPORTES TO ROL_CONSULTA_SICAS;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.IDEXTRACCION	IS 'COLUMAN DE IDENTIFICADOR UNICO DE LA TABLA';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.TIPO_REPORTE	IS 'TIPO DE REPORTE QUE SE EJECUTA';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.CODUSR		IS 'CODIGO DE USUARIO QUE GENERO EL REPORTE';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.FECREPORTE	IS 'FECHA DEL REPORTE';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.STATUS		IS 'ESTATUS DE CONTROL DEL REPORTE GENERADO';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.REPORTE		IS 'CONTENIDO DEL REPORTE GENERADO';
COMMENT ON COLUMN SICAS_OC.EXTRACCION_DE_REPORTES.FILE_NAME		IS 'NOMBRE DEL ARCHIVO DEL REPORTE GENERADO';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM EXTRACCION_DE_REPORTES FOR SICAS_OC.EXTRACCION_DE_REPORTES;
