--<TABLA QUE SE UTILIZA EN MIGRACION SICAS - APEX>
--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM T_SALDOS_COMISIONES_ANIOMES;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.T_SALDOS_COMISIONES_ANIOMES;

/

--CREACION DE TABLA CONF_ASISTENCIA_APPL PARA LA CONFIGURACION DE LOS COLORES POR AREA Y DIAS ESPECIALES.
CREATE TABLE SICAS_OC.T_SALDOS_COMISIONES_ANIOMES(
                                CODCIA 				NUMBER          NOT NULL
                                ,COD_AGENTE			NUMBER 			NOT NULL
								,FE_INI_SALDO		DATE 			NOT NULL
								,COD_MONEDA			VARCHAR2(2)		NOT NULL
								,MONTO_SALDO_FINAL	NUMBER
                                ) SEGMENT CREATION IMMEDIATE TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.T_SALDOS_COMISIONES_ANIOMES_IDX1 ON SICAS_OC.T_SALDOS_COMISIONES_ANIOMES (CODCIA,COD_AGENTE,COD_MONEDA,FE_INI_SALDO) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.T_SALDOS_COMISIONES_ANIOMES ADD CONSTRAINT PK_T_SALDOS_COMISIONES_ANIOMES PRIMARY KEY (CODCIA,COD_AGENTE,COD_MONEDA,FE_INI_SALDO) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.T_SALDOS_COMISIONES_ANIOMES TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.T_SALDOS_COMISIONES_ANIOMES TO ROL_CONSULTA_SICAS;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.T_SALDOS_COMISIONES_ANIOMES.CODCIA				IS 'COLUMNA DE LA COMPANIA';
COMMENT ON COLUMN SICAS_OC.T_SALDOS_COMISIONES_ANIOMES.COD_AGENTE			IS 'COLUMNA DEL CODIGO DEL AGENTE';
COMMENT ON COLUMN SICAS_OC.T_SALDOS_COMISIONES_ANIOMES.FE_INI_SALDO			IS 'FECHA DE INICIO DEL SALDO';
COMMENT ON COLUMN SICAS_OC.T_SALDOS_COMISIONES_ANIOMES.COD_MONEDA			IS 'CODIGO DE LA MONEDA';
COMMENT ON COLUMN SICAS_OC.T_SALDOS_COMISIONES_ANIOMES.MONTO_SALDO_FINAL	IS 'MONTO DEL SALDO A FINAL DEL MES';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM T_SALDOS_COMISIONES_ANIOMES FOR SICAS_OC.T_SALDOS_COMISIONES_ANIOMES;
