--<TABLA QUE SE UTILIZA EN MIGRACION SICAS - APEX>
--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM TMP_SINI;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.TMP_SINI;

--CREACION DE TABLA CONF_ASISTENCIA_APPL PARA LA CONFIGURACION DE LOS COLORES POR AREA Y DIAS ESPECIALES.
  CREATE TABLE SICAS_OC.TMP_SINI (IDPOLIZA NUMBER(14,0)
								,IDREPORTE NUMBER(14,0)
								,NUMPOLUNICO VARCHAR2(30 BYTE)
								,COD_AGENTE VARCHAR2(10 BYTE)
								,NOMBREAGENTE VARCHAR2(1000 BYTE)
								,CODPROMOTOR VARCHAR2(10 BYTE)
								,NOMPROMOTOR VARCHAR2(1000 BYTE)
								,CODDIRECCION VARCHAR2(20 BYTE)
								,NOMDIRECCION VARCHAR2(1000 BYTE)
								,NOMBRE_CLIENTE VARCHAR2(1000 BYTE)
								,RAMO VARCHAR2(50 BYTE)
								,FECINIVIG DATE
								,FECFINVIG DATE
								,CANTSINIESTROS NUMBER(5,0)
								,FECHACOBHASTA DATE
								,PORCSINI NUMBER(10,4)
								,MONTOPRIMAPAGADA NUMBER(14,2)
								,IDTIPOSEG VARCHAR2(6 BYTE)
								,DESCIDTIPOSEG VARCHAR2(1000 BYTE)
								,PLANCOB VARCHAR2(15 BYTE)
								,DESCPLANCOB VARCHAR2(1000 BYTE)
								,MONTOPRIMATOTAL NUMBER(14,2)
								,PRIMAANULADA NUMBER(14,2)
								,MTOSINIPAGADOS NUMBER(14,2)
								,MONTOSINIESTROS NUMBER(14,2)
								,USUARIO VARCHAR2(50 BYTE)
								,MTOSINIPENDIENTES NUMBER(14,2)
   ) TABLESPACE TS_SICASOC ;

/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.TMP_SINI_IDX1 ON SICAS_OC.TMP_SINI (IDPOLIZA,IDREPORTE) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.TMP_SINI ADD CONSTRAINT PK_TMP_SINI PRIMARY KEY (IDPOLIZA,IDREPORTE) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.TMP_SINI TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.TMP_SINI TO ROL_CONSULTA_SICAS;

/
--##COMENTARIOS DESCRIPTIVOS
--COMMENT ON COLUMN SICAS_OC.TMP_SINI.CODCIA				IS 'COLUMNA DE LA COMPANIA';
--COMMENT ON COLUMN SICAS_OC.TMP_SINI.COD_AGENTE			IS 'COLUMNA DEL CODIGO DEL AGENTE';
--COMMENT ON COLUMN SICAS_OC.TMP_SINI.FE_INI_SALDO			IS 'FECHA DE INICIO DEL SALDO';
--COMMENT ON COLUMN SICAS_OC.TMP_SINI.COD_MONEDA			IS 'CODIGO DE LA MONEDA';
--COMMENT ON COLUMN SICAS_OC.TMP_SINI.MONTO_SALDO_FINAL	IS 'MONTO DEL SALDO A FINAL DEL MES';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM TMP_SINI FOR SICAS_OC.TMP_SINI;