
  CREATE TABLE "SICAS_OC"."ACCESOS_AUTORIZADOS" 
   (	"CODGRUPO" VARCHAR2(8) CONSTRAINT "SYS_C006952" NOT NULL ENABLE, 
	"CODAPLICA" VARCHAR2(8) CONSTRAINT "SYS_C006953" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C006954" NOT NULL ENABLE, 
	 PRIMARY KEY ("CODGRUPO", "CODAPLICA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODGRUPO", "CODCIA")
	  REFERENCES "SICAS_OC"."GRUPOS_DE_USUARIOS" ("CODGRUPO", "CODCIA") ENABLE, 
	 FOREIGN KEY ("CODAPLICA")
	  REFERENCES "SICAS_OC"."APLICACIONES" ("CODAPLICA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
