
  CREATE TABLE "SICAS_OC"."ACTIVIDADES_ECONOMICAS" 
   (	"CODACTIVIDAD" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCACTIVIDAD" VARCHAR2(100) NOT NULL ENABLE, 
	"RIESGOACTIVIDAD" VARCHAR2(2) NOT NULL ENABLE, 
	"TIPORIESGO" VARCHAR2(6), 
	"CVE_CNSF" VARCHAR2(15), 
	"DESC_CNSF" VARCHAR2(300), 
	 CONSTRAINT "PK_ACTIVIDADES_ECONOMICAS" PRIMARY KEY ("CODACTIVIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
