
  CREATE TABLE "SICAS_OC"."ADMON_RIESGO_H" 
   (	"CODEMPRESA" NUMBER(14,0), 
	"CODCIA" NUMBER(14,0), 
	"ID_PROCESO" NUMBER(5,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"CODCLIENTE" NUMBER(14,0), 
	"CODASEGURADO" NUMBER(14,0), 
	"ORIGEN" VARCHAR2(10), 
	"ST_RESOLUCION" VARCHAR2(4), 
	"FE_ESTATUS" DATE, 
	"TP_RESOLUCION" VARCHAR2(10), 
	"FECHA_PROCESO" DATE, 
	"USUARIO" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
