
  CREATE TABLE "SICAS_OC"."ADMON_ACTIVI" 
   (	"CODCIA" NUMBER(14,0), 
	"ID_PROCESO" NUMBER(5,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"TP_PERSONA" VARCHAR2(10), 
	"ORIGEN" VARCHAR2(10), 
	"CODCLIENTE" NUMBER(14,0), 
	"CODASEGURADO" NUMBER(14,0), 
	"IDFACTURA" NUMBER(14,0), 
	"IDTIPOSEG" VARCHAR2(6), 
	"COD_MONEDA" VARCHAR2(5), 
	"FORMPAGO" VARCHAR2(6), 
	"TIPO_PERSONA" VARCHAR2(6), 
	"CODACTIVIDAD" VARCHAR2(10), 
	"ASEGURADOS_EMI" NUMBER(10,0), 
	"ASEGURADOS_END" NUMBER(10,0), 
	"SUMAASEG_EMI" NUMBER(10,0), 
	"SUMAASEG_END" NUMBER(10,0), 
	"ST_RIESGO" VARCHAR2(10), 
	"OBSERVACIONES" VARCHAR2(300), 
	"FE_PROCESO" DATE, 
	"FE_HORA_PROCESO" DATE, 
	"FE_ACTUALIZACION" DATE, 
	"USUARIO_ACTUA" VARCHAR2(20), 
	"IMPTE_MOVTO_REG" NUMBER(14,0), 
	"FE_ALTA_REG" DATE, 
	"HISTORICO_MOVTOS_REG" VARCHAR2(200), 
	"IDENDOSO" NUMBER(14,0), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
