
  CREATE TABLE "SICAS_OC"."AGENTES_DISTRIBUCION_POLIZA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CODNIVEL" NUMBER(10,0) NOT NULL ENABLE, 
	"COD_AGENTE_DISTR" NUMBER(18,0) NOT NULL ENABLE, 
	"PORC_COMISION_AGENTE" NUMBER(9,6) NOT NULL ENABLE, 
	"PORC_COM_DISTRIBUIDA" NUMBER(9,6) NOT NULL ENABLE, 
	"PORC_COMISION_PLAN" NUMBER(9,6) NOT NULL ENABLE, 
	"PORC_COM_PROPORCIONAL" NUMBER(9,6) NOT NULL ENABLE, 
	"COD_AGENTE_JEFE" NUMBER(18,0), 
	"PORC_COM_POLIZA" NUMBER(9,6), 
	"ORIGEN" VARCHAR2(1), 
	 CONSTRAINT "PK_AGENTES_DISTRIBUCION_POLIZA" PRIMARY KEY ("CODCIA", "IDPOLIZA", "COD_AGENTE", "CODNIVEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
