
  CREATE TABLE "SICAS_OC"."AGENTES" 
   (	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"EST_AGENTE" VARCHAR2(6), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPO_AGENTE" VARCHAR2(6), 
	"CODEMPRESA" NUMBER(14,0), 
	"CANALCOMISVENTA" VARCHAR2(6), 
	"COD_AGENTE_JEFE" NUMBER(18,0), 
	"CODTIPO" VARCHAR2(6), 
	"CODNIVEL" NUMBER(10,0), 
	"INDPAGOSAUTOM" VARCHAR2(1) DEFAULT 'S', 
	"CODEJECUTIVO" NUMBER(10,0), 
	"IDFORMAPAGO" NUMBER(10,0), 
	"IDCUENTACORREO" NUMBER(10,0), 
	"INDSUJETOSUSP" VARCHAR2(1), 
	"FECALTA" DATE, 
	"INDEXCLUIRHONORARIO" VARCHAR2(1) DEFAULT 'N', 
	"CLAVE_PORTAL" VARCHAR2(10), 
	"PASSWORD_PORTAL" VARCHAR2(25), 
	"INDALTAPLATAFORMA" VARCHAR2(1), 
	 CONSTRAINT "PK_AGENTES" PRIMARY KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
