ALTER TABLE SICAS_OC.ADMON_RIESGO ADD NUMSINIESTRO  NUMBER;
ALTER TABLE SICAS_OC.ADMON_RIESGO_SINIESTROS ADD NUMSINIESTRO  NUMBER;
/

ALTER PACKAGE SICAS_OC.OC_RIESGOS_PLD COMPILE;
ALTER PACKAGE SICAS_OC.PKG_PLD_ADMONRIESGO COMPILE;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO COMPILE;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO_SINIESTROS COMPILE;
ALTER PACKAGE SICAS_OC.OC_CAT_QEQ COMPILE;
ALTER PACKAGE SICAS_OC.OC_PLD_LISTAS_CNSF COMPILE;

ALTER PACKAGE SICAS_OC.PKG_PLD_ADMONRIESGO COMPILE;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MASIVOS COMPILE;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS COMPILE;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO_SINIESTROS COMPILE;


ALTER PACKAGE SICAS_OC.OC_RIESGOS_PLD COMPILE BODY;
ALTER PACKAGE SICAS_OC.PKG_PLD_ADMONRIESGO COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO_SINIESTROS COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_CAT_QEQ COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_PLD_LISTAS_CNSF COMPILE BODY;

ALTER PACKAGE SICAS_OC.PKG_PLD_ADMONRIESGO COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MASIVOS COMPILE BODY;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_ADMON_RIESGO_SINIESTROS COMPILE BODY;
/