ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD NOM_LISTA_ORIGEN  VARCHAR2(500);
ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD NOM_TIPO_PERS_CNSF  VARCHAR2(500);
ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD CVE_PAIS_CNSF  VARCHAR2(50);
ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD NOM_PAIS_PROCEDENCIA  VARCHAR2(50);
ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD CVE_NACIONALIDAD_CNSF  VARCHAR2(50);
ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF ADD NOM_NACIONALIDAD  VARCHAR2(100);
/

ALTER PACKAGE SICAS_OC.OC_PLD_LISTAS_CNSF COMPILE;
ALTER PACKAGE SICAS_OC.OC_PLD_LISTAS_CNSF COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_PLD_REP_OPERACIONES COMPILE;
ALTER PACKAGE SICAS_OC.OC_PLD_REP_OPERACIONES COMPILE BODY;
/
