ALTER TABLE SICAS_OC.PLD_REP_OPERACIONES ADD FEC_DETECCION DATE;

ALTER TABLE SICAS_OC.PLD_LISTAS_CNSF MODIFY FEC_ALTA DATE DEFAULT SYSDATE;

ALTER PACKAGE SICAS_OC.OC_PLD_REP_OPERACIONES COMPILE;
ALTER PACKAGE SICAS_OC.OC_PLD_REP_OPERACIONES COMPILE BODY;
/
