ALTER TABLE SICAS_OC.BENEF_SIN ADD TIPO_PERSONA VARCHAR2(6);

ALTER TABLE SICAS_OC.BENEF_SIN ADD CURP VARCHAR2(20);
ALTER TABLE SICAS_OC.BENEF_SIN ADD CODIGOZIP NUMBER;

ALTER PROCEDURE	SICAS_OC.APROBACIONES_PAGADAS COMPILE;
ALTER PROCEDURE	SICAS_OC.OC_INTEGRADO_CONTABLE COMPILE;
ALTER PROCEDURE	SICAS_OC.ENVIA_CORREO_REPORTE_PLD COMPILE;
ALTER PROCEDURE	SICAS_OC.APROBACIONES_ANULADAS COMPILE;
ALTER PACKAGE SICAS_OC.OC_SINIESTRO COMPILE;
ALTER PACKAGE SICAS_OC.OC_SINIESTRO COMPILE BODY;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS_CONT COMPILE;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS_CONT COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MASIVOS COMPILE;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MASIVOS COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_BENEF_SIN COMPILE;
ALTER PACKAGE SICAS_OC.OC_BENEF_SIN COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_APROBACION_ASEG COMPILE;
ALTER PACKAGE SICAS_OC.OC_APROBACION_ASEG COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MAS_SINI COMPILE;
ALTER PACKAGE SICAS_OC.OC_PROCESOS_MAS_SINI COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_APROBACIONES COMPILE;
ALTER PACKAGE SICAS_OC.OC_APROBACIONES COMPILE BODY;
ALTER PACKAGE SICAS_OC.OC_COMPROBANTES_CONTABLES COMPILE;
ALTER PACKAGE SICAS_OC.OC_COMPROBANTES_CONTABLES COMPILE BODY;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS COMPILE;
ALTER PACKAGE SICAS_OC.REPORTE_SINIESTROS COMPILE BODY;
ALTER PACKAGE SICAS_OC.GT_TABLERO_CTRL_PAGO COMPILE;
ALTER PACKAGE SICAS_OC.GT_TABLERO_CTRL_PAGO COMPILE BODY;
ALTER PACKAGE SICAS_OC.SICAS_APEX COMPILE;
ALTER PACKAGE SICAS_OC.SICAS_APEX COMPILE BODY;
/