
  CREATE TABLE "SICAS_OC"."APARTADO_POSTAL" 
   (	"CODIGO_POSTAL" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCRIPCION_POSTAL" VARCHAR2(100), 
	"CODPAIS" VARCHAR2(3) NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODIGO_POSTAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO")
	  REFERENCES "SICAS_OC"."CORREGIMIENTO" ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
