
  CREATE TABLE "SICAS_OC"."APLICACIONES_AYUDA" 
   (	"CODAPLICA" VARCHAR2(8) NOT NULL ENABLE, 
	"IDDOCVIDEOAYUDA" NUMBER(5,0) NOT NULL ENABLE, 
	"NOMBREDOCUMVIDEO" VARCHAR2(400), 
	"FORMATO" VARCHAR2(10), 
	 CONSTRAINT "PK_APLICACIONES_AYUDA" PRIMARY KEY ("CODAPLICA", "IDDOCVIDEOAYUDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODAPLICA")
	  REFERENCES "SICAS_OC"."APLICACIONES" ("CODAPLICA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
