
  CREATE TABLE "SICAS_OC"."APROBACIONES" 
   (	"NUM_APROBACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPO_APROBACION" VARCHAR2(6), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(14,2), 
	"STSAPROBACION" VARCHAR2(3), 
	"TIPO_DE_APROBACION" VARCHAR2(1), 
	"IDTRANSACCION" NUMBER(18,0), 
	"INDDISPERSION" VARCHAR2(1), 
	"CTALIQUIDADORA" VARCHAR2(6), 
	"IDEFACTEXT" NUMBER(14,0), 
	"BENEF" NUMBER(5,0), 
	"IDTRANSACCIONANUL" VARCHAR2(18), 
	"FECHFONDOSINI" DATE, 
	"CODUSUARIO" VARCHAR2(50), 
	"TERMINAL" VARCHAR2(50), 
	"INDFONDOSINI" VARCHAR2(1) DEFAULT 'N', 
	"FECPAGO" DATE DEFAULT sysdate, 
	"NUMPAGREF" VARCHAR2(30), 
	"IDAUTORIZACION" NUMBER(14,0), 
	"CODCIA" NUMBER(14,0) DEFAULT 1, 
	"CODEMPRESA" NUMBER(14,0) DEFAULT 1, 
	"COD_MONEDA" VARCHAR2(5) DEFAULT 'PS', 
	"CODCOBERT" VARCHAR2(6), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"CODUSUARIO_ALTA" VARCHAR2(30) DEFAULT USER, 
	"FECREGISTRO" DATE DEFAULT TRUNC(SYSDATE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
