
  CREATE TABLE "SICAS_OC"."APROBACIONES_SIN1" 
   (	"NUM_APROBACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPO_APROBACION" VARCHAR2(6), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(14,2), 
	"STSAPROBACION" VARCHAR2(3), 
	"TIPO_DE_APROBACION" VARCHAR2(1), 
	"IDTRANSACCION" NUMBER(18,0), 
	"INDDISPERSION" VARCHAR2(1), 
	"CTALIQUIDADORA" VARCHAR2(6), 
	"IDEFACTEXT" NUMBER(14,0), 
	"BENEF" NUMBER(5,0), 
	"IDTRANSACCIONANUL" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
