
  CREATE TABLE "SICAS_OC"."ASISTENCIAS_ASEGURADO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_ASEGURADO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODASISTENCIA" VARCHAR2(10) NOT NULL ENABLE, 
	"CODMONEDA" VARCHAR2(5), 
	"MONTOASISTLOCAL" NUMBER(28,2), 
	"MONTOASISTMONEDA" NUMBER(28,2), 
	"STSASISTENCIA" VARCHAR2(6), 
	"FECSTS" DATE NOT NULL ENABLE, 
	"IDENDOSO" NUMBER(14,0), 
	 CONSTRAINT "PK_ASISTENCIAS_ASEGURADO" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "COD_ASEGURADO", "CODASISTENCIA", "IDENDOSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCIA", "IDPOLIZA", "IDETPOL", "COD_ASEGURADO")
	  REFERENCES "SICAS_OC"."ASEGURADO_CERTIFICADO" ("CODCIA", "IDPOLIZA", "IDETPOL", "COD_ASEGURADO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
