
  CREATE TABLE "SICAS_OC"."AUDITORIA" 
   (	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"SINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"INDV_COLECT" VARCHAR2(10), 
	"MNTO_RESERVA_COBERTURAS" NUMBER(18,2), 
	"MNTO_RESERVA_TRANSACC" NUMBER(18,2), 
	"DIFERENCIAS_RESERVAS" VARCHAR2(50), 
	"MNTO_PAGOS_COBERTURAS" NUMBER(18,2), 
	"MNTO_PAGOS_TRANSACC" NUMBER(18,2), 
	"MNTO_PAGOS_COMPROBANTE" NUMBER(18,2), 
	"MNTO_APROBACIONES_DE_PAGO" NUMBER(18,2), 
	"IMPUESTOS" VARCHAR2(20), 
	"DIFERENCIAS_PAGOS" VARCHAR2(50), 
	"OBSERVACIONES" VARCHAR2(50), 
	"ESTATUS_SINIESTRO" VARCHAR2(15), 
	 CONSTRAINT "AUDITORIA_PK" PRIMARY KEY ("SINIESTRO", "IDPOLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
