
  CREATE TABLE "SICAS_OC"."AUTORIZA_PROCESOS_REGRESO" 
   (	"CODCIA" NUMBER NOT NULL ENABLE, 
	"IDAUTORIZACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDREGRESO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDEMPLEADOREGRESA" NUMBER(14,0), 
	"FECHAREGRESA" DATE, 
	"HORAREGRESA" VARCHAR2(10), 
	"IDEMPLEADOREGRESADO" NUMBER(14,0), 
	"STSREGRESO" VARCHAR2(10), 
	"FECHASTATUS" DATE, 
	"OBSERVACIONES" VARCHAR2(4000), 
	 CONSTRAINT "PK_AUTORIZA_PROCESOS_REGRESO" PRIMARY KEY ("CODCIA", "IDAUTORIZACION", "IDREGRESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
