
  CREATE TABLE "SICAS_OC"."AVALUO" 
   (	"NUM_AVALUO" NUMBER(18,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(18,2) NOT NULL ENABLE, 
	"NUM_BIEN" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPAIS" VARCHAR2(3) NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"ESTADO_AVALUO" VARCHAR2(3), 
	"TIPO_AVALUO" VARCHAR2(6), 
	"TIPO_PROPIEDAD" VARCHAR2(6), 
	"FECHA_AVALUO" DATE, 
	"TIPO_CONTRUCCION" VARCHAR2(6), 
	"METROS_CUADRADOS" NUMBER(18,0), 
	"OBSERVACIONES_ADICIONALES" LONG, 
	"CODIGO_POSTAL" VARCHAR2(30), 
	"CODASENTAMIENTO" NUMBER(5,0), 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM_AVALUO", "IDPOLIZA", "IDETPOL", "NUM_BIEN", "CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
