
  CREATE TABLE "SICAS_OC"."BENEF_SIN_PAGOS_SIN1" 
   (	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"BENEF" NUMBER(5,0) NOT NULL ENABLE, 
	"NUM_APROBACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPO_DE_PAGO" VARCHAR2(6), 
	"ENTIDAD_FINANCIERA" VARCHAR2(6), 
	"NRO_CTA_BANCARIA_CLABE" VARCHAR2(20), 
	"NRO_CHEQUE" VARCHAR2(20), 
	"NRO_ORDEN_PAGO" VARCHAR2(20), 
	"STSPAGO" VARCHAR2(6), 
	"FECSTS" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
