
  CREATE TABLE "SICAS_OC"."BENEF_SIN_ESP" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDNEGOCIO" VARCHAR2(6), 
	"IDBENEFICIARIO" NUMBER(14,0), 
	"NOMBRE" VARCHAR2(300), 
	"APELLIDO_PATERNO" VARCHAR2(50), 
	"APELLIDO_MATERNO" VARCHAR2(50), 
	"CODPARENT" VARCHAR2(6), 
	"PORCEPART" NUMBER(9,6), 
	"FECNAC" DATE, 
	"TIPO_ID_TRIBUTARIO" VARCHAR2(6), 
	"NUM_DOC_TRIBUTARIO" VARCHAR2(20), 
	"SEXO" VARCHAR2(6), 
	"ENT_FINANCIERA" VARCHAR2(6), 
	"NUMCUENTABANCARIA" VARCHAR2(20), 
	"CUENTA_CLABE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
