
  CREATE TABLE "SICAS_OC"."BONOS_AGENTES_NEGOCIOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDBONOVENTAS" NUMBER(14,0) NOT NULL ENABLE, 
	"CODTIPONEGOCIO" VARCHAR2(6) NOT NULL ENABLE, 
	"PORCENNEGOCIO" NUMBER(12,6) NOT NULL ENABLE, 
	"CANTNEGOCIOS" NUMBER(5,0), 
	 CONSTRAINT "PK_BONOS_AGENTES_NEGOCIOS" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDBONOVENTAS", "CODTIPONEGOCIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
