
  CREATE TABLE "SICAS_OC"."BONO_DETPOLIZA" 
   (	"IDBONODETPOLIZA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOLIZA" NUMBER(14,0), 
	"COD_MONEDA" VARCHAR2(5), 
	"COD_AGENTE" NUMBER(18,0), 
	"TIPBONO" VARCHAR2(6), 
	"MTOLOCAL" NUMBER(22,4), 
	"MTOMONEDA" NUMBER(22,4), 
	"STSBONO" VARCHAR2(3), 
	"FECSTS" DATE, 
	"FECLIQ" DATE, 
	"FECCREACION" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "PK_BONODETPOLIZA" PRIMARY KEY ("IDBONODETPOLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
