
  CREATE TABLE "SICAS_OC"."CALENDARIO_SEMANAL" 
   (	"IDSEMANA" NUMBER(6,0) NOT NULL ENABLE, 
	"FECINISEMANA" DATE NOT NULL ENABLE, 
	"FECFINSEMANA" DATE NOT NULL ENABLE, 
	"ANIOSEMANA" NUMBER(4,0) NOT NULL ENABLE, 
	"NUMSEMANA" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CALENDARIO_SEMANAL" PRIMARY KEY ("IDSEMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
