
  CREATE TABLE "SICAS_OC"."CAMBIA_BENEF_LOGEM" 
   (	"CODCIA" NUMBER, 
	"CODEMPRESA" NUMBER, 
	"IDSINIESTRO" NUMBER, 
	"IDPOLIZA" VARCHAR2(12), 
	"COD_ASEGURADO" VARCHAR2(200), 
	"IDTRANSACCION" NUMBER, 
	"TIPO_ID_TRIBUTARIO_LOG" VARCHAR2(20), 
	"NUM_DOC_TRIBUTARIO_LOG" VARCHAR2(20), 
	"NOMBRE" VARCHAR2(300), 
	"APELLIDO_PATERNO" VARCHAR2(50), 
	"APELLIDO_MATERNO" VARCHAR2(50), 
	"TIPO_ID_TRIBUTARIO" VARCHAR2(20), 
	"NUM_DOC_TRIBUTARIO" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	"CUENTA_CLAVE" VARCHAR2(50), 
	"ENT_FINANCIERA" VARCHAR2(6), 
	"NUMCUENTABANCARIA" VARCHAR2(20), 
	"INDAPLICAISR" VARCHAR2(1), 
	"PORCENTISR" NUMBER(9,6), 
	"COLUMNA1" NUMBER, 
	"COLUMNA2" VARCHAR2(200), 
	"COLUMNA3" DATE, 
	"COLUMNA4" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
