
  CREATE TABLE "SICAS_OC"."CAMBIOS_NIVEL" 
   (	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C0028106" NOT NULL ENABLE, 
	"CODNIVEL" NUMBER(10,0) CONSTRAINT "SYS_C0028107" NOT NULL ENABLE, 
	"NUMCAMBIO" NUMBER(3,0) CONSTRAINT "SYS_C0028108" NOT NULL ENABLE, 
	"FECINICIOVIG" DATE, 
	"FECFINVIG" DATE, 
	"COMMINIMA" NUMBER(14,2), 
	"COMMAXIMA" NUMBER(14,2), 
	"ESTADO" VARCHAR2(6), 
	 PRIMARY KEY ("CODCIA", "CODNIVEL", "NUMCAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCIA", "CODNIVEL")
	  REFERENCES "SICAS_OC"."NIVEL" ("CODCIA", "CODNIVEL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
