
  CREATE TABLE "SICAS_OC"."CAMBIOS_POLIZAS" 
   (	"CODCIA" NUMBER(4,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(18,0) NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(18,0), 
	"CERTIFICADO" NUMBER(18,0), 
	"ASEGURADO" NUMBER(18,0), 
	"CDUSER" VARCHAR2(40), 
	"CDTERMINAL" VARCHAR2(40), 
	"FEMODIFI" DATE DEFAULT SYSDATE, 
	"TIPO_CAMBIO" VARCHAR2(30) NOT NULL ENABLE, 
	"DSORIGEN" VARCHAR2(100) NOT NULL ENABLE, 
	"DATO_ORIGINAL" VARCHAR2(3000) NOT NULL ENABLE, 
	"DATO_ALTERADO" VARCHAR2(3000) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
