
  CREATE TABLE "SICAS_OC"."CAMCAR_POLIZA" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"COD_AGENTE_ANT" NUMBER(18,0), 
	"COD_AGENTE_ACT" NUMBER(18,0), 
	"COD_PROMOTOR_ANT" NUMBER(18,0), 
	"COD_PROMOTOR_ACT" NUMBER(18,0), 
	"CODTIPO_AGE_ANT" VARCHAR2(6), 
	"CODTIPO_AGE_ACT" VARCHAR2(6), 
	"CODTIPO_PRO_ANT" VARCHAR2(6), 
	"CODTIPO_PRO_ACT" VARCHAR2(6), 
	"CODUSUARIO" VARCHAR2(30), 
	"ST_ACTUALIZADA" VARCHAR2(6), 
	"ID_TP_AGENTES" VARCHAR2(3), 
	"IDTRANSACCION_FACT" NUMBER(18,0), 
	"IDTRANSACCIONANU_FACT" NUMBER(18,0), 
	"IDTRANSACCION_NCR" NUMBER(18,0), 
	"IDTRANSACCIONANU_NCR" NUMBER(18,0), 
	"FE_CAMBIO" DATE, 
	"HR_CAMBIO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
