
  CREATE TABLE "SICAS_OC"."CARGA_REFERENCIADO" 
   (	"FECHAOPERA" VARCHAR2(10), 
	"CONCEPTO" VARCHAR2(50), 
	"REFERENCIA" VARCHAR2(50), 
	"REFERENCIAMPLI" VARCHAR2(50), 
	"IMPORTE" VARCHAR2(14)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
