
  CREATE TABLE "SICAS_OC"."CARGA_INFOFISCAL_EXT" 
   (	"IDPOLIZA" NUMBER(14,0), 
	"CODCLIENTE" NUMBER(14,0), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"RAZONSOCIALFACT" VARCHAR2(300), 
	"IDREGFISSAT" NUMBER(5,0), 
	"DESCRIPCION_REGFIS" VARCHAR2(500), 
	"TIPO_DIRECCION" VARCHAR2(6), 
	"CORRELATIVO_DIRECCION" NUMBER(5,0), 
	"DIRECCION" VARCHAR2(250), 
	"CODPAIS" VARCHAR2(3), 
	"CODESTADO" VARCHAR2(3), 
	"CODCIUDAD" VARCHAR2(3), 
	"CODMUNICIPIO" VARCHAR2(3), 
	"CODIGO_POSTAL" VARCHAR2(30), 
	"CODCOLONIA" VARCHAR2(6), 
	"NUMINTERIOR" VARCHAR2(20), 
	"NUMEXTERIOR" VARCHAR2(20), 
	"CODUSOCFDI" VARCHAR2(10), 
	"CODOBJETOIMP" VARCHAR2(10), 
	"TIPO_PERSONA" VARCHAR2(6), 
	"NUM_CARGA" NUMBER(2,0)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DIR_TMP"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
           BADFILE DIR_TMP:'carga_infofiscal.bad'
           LOGFILE DIR_TMP:'carga_infofiscal.log'
           FIELDS TERMINATED BY '|' 
           MISSING FIELD VALUES ARE NULL
              ( IDPOLIZA
              , CODCLIENTE
              , TIPO_DOC_IDENTIFICACION
              , NUM_DOC_IDENTIFICACION
              , RAZONSOCIALFACT
              , IDREGFISSAT
              , DESCRIPCION_REGFIS
              , TIPO_DIRECCION
              , CORRELATIVO_DIRECCION
              , DIRECCION
              , CODPAIS
              , CODESTADO
              , CODCIUDAD
              , CODMUNICIPIO
              , CODIGO_POSTAL
              , CODCOLONIA
              , NUMINTERIOR
              , NUMEXTERIOR
              , CODUSOCFDI
              , CODOBJETOIMP
              , TIPO_PERSONA
              , NUM_CARGA
            )
             )
      LOCATION
       ( 'carga_infofiscal.txt'
       )
    )
   REJECT LIMIT UNLIMITED 
