
  CREATE TABLE "SICAS_OC"."CARGA_ASEGURADOS_LOG" 
   (	"NOMARCHIVOCARGA" VARCHAR2(50) NOT NULL ENABLE, 
	"IDREGISTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"CAMPOFLEXIBLE1" VARCHAR2(4000), 
	"CAMPOFLEXIBLE2" VARCHAR2(4000), 
	"CAMPOFLEXIBLE3" VARCHAR2(4000), 
	 CONSTRAINT "CARGA_ASEGURADOS_LOG_PK" PRIMARY KEY ("NOMARCHIVOCARGA", "IDREGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
