DROP TABLE SICAS_OC.CARGA_ASEGURADOS_LOG
/
--
-- CARGA_ASEGURADOS_LOG  (Table) 
--
CREATE TABLE SICAS_OC.CARGA_ASEGURADOS_LOG
( 
  NOMARCHIVOCARGA  VARCHAR2(50)  NOT NULL,
  IDREGISTRO       NUMBER(14)    NOT NULL,
  CAMPOFLEXIBLE1   VARCHAR2(4000),
  CAMPOFLEXIBLE2   VARCHAR2(4000), 
  CAMPOFLEXIBLE3   VARCHAR2(4000)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.CARGA_ASEGURADOS_LOG IS 'Resultado de la Carga de Archivos'
/

COMMENT ON COLUMN SICAS_OC.CARGA_ASEGURADOS_LOG.NOMARCHIVOCARGA IS 'Nombre del Archivo de Carga'
/

COMMENT ON COLUMN SICAS_OC.CARGA_ASEGURADOS_LOG.IDREGISTRO IS 'Identificador del Registro'
/

COMMENT ON COLUMN SICAS_OC.CARGA_ASEGURADOS_LOG.CAMPOFLEXIBLE1 IS 'Campo Flexible 1 para la descripción del resultado'
/

COMMENT ON COLUMN SICAS_OC.CARGA_ASEGURADOS_LOG.CAMPOFLEXIBLE2 IS 'Campo Flexible 2 para la descripción del resultado'
/

COMMENT ON COLUMN SICAS_OC.CARGA_ASEGURADOS_LOG.CAMPOFLEXIBLE3 IS 'Campo Flexible 3 para la descripción del resultado'
/

--
-- CARGA_ASEGURADOS_LOG_PK  (Index) 
--
--  Dependencies: 
--   CARGA_ASEGURADOS_LOG (Table)
--
CREATE UNIQUE INDEX SICAS_OC.CARGA_ASEGURADOS_LOG_PK ON SICAS_OC.CARGA_ASEGURADOS_LOG
( NOMARCHIVOCARGA, IDREGISTRO )
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- CARGA_ASEGURADOS_LOG  (Synonym) 
--
--  Dependencies: 
--   CARGA_ASEGURADOS_LOG (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM CARGA_ASEGURADOS_LOG FOR SICAS_OC.CARGA_ASEGURADOS_LOG
/

-- 
-- Non Foreign Key Constraints for Table CARGA_ASEGURADOS_LOG
-- 
ALTER TABLE SICAS_OC.CARGA_ASEGURADOS_LOG ADD (
  CONSTRAINT CARGA_ASEGURADOS_LOG_PK
  PRIMARY KEY
  ( NOMARCHIVOCARGA, IDREGISTRO )
  USING INDEX SICAS_OC.CARGA_ASEGURADOS_LOG_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.CARGA_ASEGURADOS_LOG TO PUBLIC
/