DROP TABLE SICAS_OC.CARGA_COBERTURAS_MASIVA
/
--
-- CARGA_COBERTURAS_MASIVA  (Table) 
--
CREATE TABLE SICAS_OC.CARGA_COBERTURAS_MASIVA
(
  CODCIA             NUMBER(14)    NOT NULL,
  CODEMPRESA         NUMBER(14)    NOT NULL,
  IDTIPOSEG          VARCHAR2(6)   NOT NULL, 
  PLANCOB            VARCHAR2(15)  NOT NULL, 
  NUMPOLUNICO        VARCHAR2(30)  NOT NULL,
  IDETPOL            NUMBER(14)    NOT NULL,
  CODCOBERT          VARCHAR2(6)   NOT NULL, 
  SALARIOMENSUAL     NUMBER(18,2), 
  VECESSALARIO       NUMBER(18,2), 
  SUMAASEGMANUAL     NUMBER(18,2), 
  SUMAASEGINGRESADA  NUMBER(18,2), 
  PRIMA_COBERT       NUMBER(18,2), 
  PORC_TASA          NUMBER(28,6),
  PRIMAPROMEDIO      NUMBER(18,2)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.CARGA_COBERTURAS_MASIVA IS 'Coberturas a Cargar de Forma Masiva'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.CODCIA IS 'Código de la Compañía'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.IDTIPOSEG IS 'Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.PLANCOB IS 'Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.NUMPOLUNICO IS 'Número de Poliza Único'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.IDETPOL IS 'Número de Detalle de Poliza'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.SALARIOMENSUAL IS 'Salario Mensual'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.VECESSALARIO IS 'Veces Salario'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.SUMAASEGMANUAL IS 'Suma Asegurada Fija Manual de la Cobertura'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.SUMAASEGINGRESADA IS 'Suma Asegurada Ingresada de la Cobertura'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.PRIMA_COBERT IS 'Prima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.PORC_TASA IS 'Tasa de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.CARGA_COBERTURAS_MASIVA.PRIMAPROMEDIO IS 'Prima Promedio o Fija'
/

--
-- CARGA_COBERTURAS_MASIVA_PK  (Index) 
--
--  Dependencies: 
--   CARGA_COBERTURAS_MASIVA (Table)
--
CREATE UNIQUE INDEX SICAS_OC.CARGA_COBERTURAS_MASIVA_PK ON SICAS_OC.CARGA_COBERTURAS_MASIVA
( CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, NUMPOLUNICO, IDETPOL, CODCOBERT )
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- CARGA_COBERTURAS_MASIVA  (Synonym) 
--
--  Dependencies: 
--   CARGA_COBERTURAS_MASIVA (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM CARGA_COBERTURAS_MASIVA FOR SICAS_OC.CARGA_COBERTURAS_MASIVA
/

-- 
-- Non Foreign Key Constraints for Table CARGA_COBERTURAS_MASIVA
-- 
ALTER TABLE SICAS_OC.CARGA_COBERTURAS_MASIVA ADD (
  CONSTRAINT CARGA_COBERTURAS_MASIVA_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, NUMPOLUNICO, IDETPOL, CODCOBERT )
  USING INDEX SICAS_OC.CARGA_COBERTURAS_MASIVA_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.CARGA_COBERTURAS_MASIVA TO PUBLIC
/