
  CREATE TABLE "SICAS_OC"."CARGA_ASEG_DETALLE" 
   (	"CODCIA" NUMBER(5,0), 
	"PROCESO" NUMBER(5,0), 
	"USUARIO_REGISTRO" VARCHAR2(30), 
	"FECHA_REGISTRO" DATE, 
	"NUTRA" VARCHAR2(30), 
	"NOMBRE" VARCHAR2(300), 
	"SEXO" VARCHAR2(2), 
	"FECHA_NAC" DATE, 
	"SUMA_ASEG" NUMBER(20,0), 
	"FOLIO" VARCHAR2(30), 
	"MES" VARCHAR2(2), 
	"PERIODO" VARCHAR2(4), 
	"IDPOLIZA" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
