
  CREATE TABLE "SICAS_OC"."CATEGORIAS" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"CODTIPONEGOCIO" VARCHAR2(100), 
	"CODCATEGO" VARCHAR2(14 CHAR), 
	"DESCCATEGO" VARCHAR2(200 CHAR), 
	"CODUSUARIO" VARCHAR2(30 CHAR) DEFAULT USER, 
	"FECHAMODIF" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "CATEGORIAS_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "CODTIPONEGOCIO", "CODCATEGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
