--
-- CLAUSULAS_FACTORES  (Table) 
--
CREATE TABLE SICAS_OC.CLAUSULAS_FACTORES
(
  TIPOFACTOR    VARCHAR2(6 BYTE)                NOT NULL,
  CODFACTOR     VARCHAR2(8 BYTE)                NOT NULL,
  CODCLAUSULA   VARCHAR2(6 BYTE)                NOT NULL,
  INDPRINCIPAL  VARCHAR2(1 BYTE)                NOT NULL
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.CLAUSULAS_FACTORES IS 'Clausulas para los diferentes Tipos de Factores'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.TIPOFACTOR IS 'Tipo de Factor'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.CODFACTOR IS 'Código del Factor'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.CODCLAUSULA IS 'Código de la Clausula'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.INDPRINCIPAL IS 'Indicador de si es Clausula Principal'
/



--
-- CLAUSULAS_FACTORES_PK  (Index) 
--
--  Dependencies: 
--   CLAUSULAS_FACTORES (Table)
--
CREATE UNIQUE INDEX SICAS_OC.CLAUSULAS_FACTORES_PK ON SICAS_OC.CLAUSULAS_FACTORES
(TIPOFACTOR, CODFACTOR, CODCLAUSULA)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- CLAUSULAS_FACTORES  (Synonym) 
--
--  Dependencies: 
--   CLAUSULAS_FACTORES (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM CLAUSULAS_FACTORES FOR SICAS_OC.CLAUSULAS_FACTORES
/


-- 
-- Non Foreign Key Constraints for Table CLAUSULAS_FACTORES 
-- 
ALTER TABLE SICAS_OC.CLAUSULAS_FACTORES ADD (
  CONSTRAINT CLAUSULAS_FACTORES_PK
  PRIMARY KEY
  (TIPOFACTOR, CODFACTOR, CODCLAUSULA)
  USING INDEX SICAS_OC.CLAUSULAS_FACTORES_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.CLAUSULAS_FACTORES TO PUBLIC
/