
  CREATE TABLE "SICAS_OC"."CLAUSULAS_COBERT_ACT" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6) NOT NULL ENABLE, 
	"COD_CLAUSULA" NUMBER(15,0) NOT NULL ENABLE, 
	"TIPO_CLAUSULA" VARCHAR2(6), 
	"TEXTO" LONG, 
	"INICIO_VIGENCIA" DATE, 
	"FIN_VIGENCIA" DATE, 
	"ESTADO" VARCHAR2(6), 
	 CONSTRAINT "PK_CLAUSULAS_COBERT_ACT" PRIMARY KEY ("CODCIA", "IDPOLIZA", "IDETPOL", "CODCOBERT", "COD_CLAUSULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
