
  CREATE TABLE "SICAS_OC"."CLAUSULAS_FACTORES" 
   (	"TIPOFACTOR" VARCHAR2(6) NOT NULL ENABLE, 
	"CODFACTOR" VARCHAR2(8) NOT NULL ENABLE, 
	"CODCLAUSULA" VARCHAR2(6) NOT NULL ENABLE, 
	"INDPRINCIPAL" VARCHAR2(1) NOT NULL ENABLE, 
	"ACTUALIZO_USUARIO" VARCHAR2(30 CHAR) DEFAULT USER, 
	"ACTUALIZO_FECHA" DATE DEFAULT sysdate, 
	 CONSTRAINT "CLAUSULAS_FACTORES_PK" PRIMARY KEY ("TIPOFACTOR", "CODFACTOR", "CODCLAUSULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
