
  CREATE TABLE "SICAS_OC"."COBERTURAS" 
   (	"IDPOLIZA" NUMBER(14,0) CONSTRAINT "SYS_C0033737" NOT NULL ENABLE, 
	"IDETPOL" NUMBER(18,2) CONSTRAINT "SYS_C0033738" NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) CONSTRAINT "SYS_C0033739" NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) CONSTRAINT "SYS_C0033740" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C0033741" NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6) CONSTRAINT "SYS_C0033742" NOT NULL ENABLE, 
	"IDENDOSO" VARCHAR2(14) NOT NULL ENABLE, 
	"STSCOBERTURA" VARCHAR2(3), 
	"SUMA_ASEGURADA_LOCAL" NUMBER(18,2), 
	"SUMA_ASEGURADA_MONEDA" NUMBER(18,2), 
	"PRIMA_LOCAL" NUMBER(18,2), 
	"PRIMA_MONEDA" NUMBER(18,2), 
	"TASA" NUMBER(18,6), 
	"PLANCOB" VARCHAR2(15), 
	"MODIFICACION" NUMBER(3,0), 
	"DEDUCIBLE_LOCAL" NUMBER(14,2), 
	"DEDUCIBLE_MONEDA" NUMBER(14,2), 
	"SALARIOMENSUAL" NUMBER(28,2), 
	"VECESSALARIO" NUMBER(10,0), 
	"SUMAASEGCALCULADA" NUMBER(28,2), 
	"EDAD_MINIMA" NUMBER(3,0), 
	"EDAD_MAXIMA" NUMBER(3,0), 
	"EDAD_EXCLUSION" NUMBER(3,0), 
	"SUMAASEG_MINIMA" NUMBER(28,2), 
	"SUMAASEG_MAXIMA" NUMBER(28,2), 
	"PORCEXTRAPRIMADET" NUMBER(9,6), 
	"MONTOEXTRAPRIMADET" NUMBER(18,2), 
	"SUMAINGRESADA" NUMBER(28,2), 
	"PRIMANIVMONEDA" NUMBER(18,2) DEFAULT 0, 
	"PRIMANIVLOCAL" NUMBER(18,2) DEFAULT 0, 
	"IDRAMOREAL" VARCHAR2(6 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
