
  CREATE TABLE "SICAS_OC"."COBERTURA_SINIESTRO" 
   (	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6) NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"DOC_REF_PAGO" VARCHAR2(50), 
	"MONTO_PAGADO_MONEDA" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL" NUMBER(18,2), 
	"STSCOBERTURA" VARCHAR2(3), 
	"NUMMOD" NUMBER(2,0), 
	"CODTRANSAC" VARCHAR2(6), 
	"CODCPTOTRANSAC" VARCHAR2(6), 
	"IDTRANSACCION" NUMBER(18,0), 
	"SALDO_RESERVA" NUMBER(18,2), 
	"INDORIGEN" VARCHAR2(1), 
	"FECRES" DATE, 
	"SALDO_RESERVA_LOCAL" NUMBER(18,2), 
	"IDTRANSACCIONANUL" VARCHAR2(18), 
	"IDAUTORIZACION" NUMBER(14,0), 
	"CODCIA" NUMBER(14,0) DEFAULT 1, 
	"CODEMPRESA" NUMBER(14,0) DEFAULT 1, 
	"COD_MONEDA" VARCHAR2(5) DEFAULT 'PS', 
	"COD_ASEGURADO" NUMBER(14,0), 
	"COD_TPRESERVA" VARCHAR2(6), 
	"IDTPRESERVA" NUMBER(5,0) DEFAULT 1, 
	"CODUSUARIO" VARCHAR2(30) DEFAULT USER, 
	"FECREGISTRO" DATE DEFAULT TRUNC(SYSDATE), 
	"TP_SERVICIO" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
