
  CREATE TABLE "SICAS_OC"."COBRO_REFER_CLI_POL" 
   (	"CODEMPRESA" NUMBER(14,0), 
	"CODCIA" NUMBER(14,0), 
	"CODCLIENTE" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"CORRELATIVO" NUMBER(10,0), 
	"NUMPOLUNICO" VARCHAR2(30), 
	"USUARIO_ALTA" VARCHAR2(15), 
	"FECHA_ALTA" DATE, 
	 CONSTRAINT "COBRO_REFER_CLI_POL_PK" PRIMARY KEY ("CODEMPRESA", "CODCIA", "CODCLIENTE", "IDPOLIZA", "CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
