
  CREATE TABLE "SICAS_OC"."COLONIA" 
   (	"CODPAIS" VARCHAR2(3) NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODIGO_POSTAL" VARCHAR2(30) NOT NULL ENABLE, 
	"CODIGO_COLONIA" VARCHAR2(6) NOT NULL ENABLE, 
	"DESCRIPCION_COLONIA" VARCHAR2(100), 
	 CONSTRAINT "PK_COLONIA" PRIMARY KEY ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO", "CODIGO_POSTAL", "CODIGO_COLONIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
