CREATE SEQUENCE SICAS_OC.SEQ_COMITECOMCTRL
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
ORDER 
;

CREATE TABLE SICAS_OC.COMITECOMCTRL (
    CODCIA          NUMBER  DEFAULT 1,
    CODEMPRESA      NUMBER  DEFAULT 1,
    IDCONSEC        NUMBER DEFAULT SICAS_OC.SEQ_COMITECOMCTRL.NEXTVAL,
    NOMBRE          VARCHAR2(4000)  NOT NULL,
    RFC             VARCHAR2(13),
    FECNACIMIENTO   DATE,
    POLIZA          VARCHAR2(20),
    CONTRATANTE     VARCHAR2(4000),
    MES             VARCHAR2(20),
    LISTA           VARCHAR2(5),
    OPERACION       VARCHAR2(500),
    COMENTARIO      VARCHAR2(4000),
    FECHAINSERT     DATE DEFAULT SYSDATE,
    FECUPDATE       DATE,
    USRINSERT       VARCHAR2(20) DEFAULT USER,
    USRUPDATE       VARCHAR2(20)
);

CREATE UNIQUE INDEX SICAS_OC.IX_COMITECOMCTRL 
    ON SICAS_OC.COMITECOMCTRL (CODCIA,CODEMPRESA,IDCONSEC);
/

ALTER TABLE SICAS_OC.COMITECOMCTRL ADD 
    CONSTRAINT PK_COMITECOMCTRL
    PRIMARY KEY (CODCIA,CODEMPRESA,IDCONSEC)
    USING INDEX SICAS_OC.IX_COMITECOMCTRL;
/

GRANT SELECT,INSERT,DELETE,UPDATE ON SICAS_OC.COMITECOMCTRL TO ROL_MODIFICA_SICAS,ROL_CONSULTA_SICAS;
/

CREATE OR REPLACE PUBLIC SYNONYM SEQ_COMITECOMCTRL FOR SEQ_COMITECOMCTRL;
CREATE OR REPLACE PUBLIC SYNONYM COMITECOMCTRL FOR COMITECOMCTRL;
/
