
  CREATE TABLE "SICAS_OC"."COMISION_COBRADOR" 
   (	"IDCOMISION" NUMBER(10,0) NOT NULL ENABLE, 
	"CODCOBRADOR" NUMBER(5,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"FECHA_PAGO" DATE, 
	"RECIBO_PAGO" VARCHAR2(20), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"FECHA_LIQUIDADO" DATE, 
	"STSCOMISION" VARCHAR2(3), 
	 PRIMARY KEY ("IDCOMISION", "CODCOBRADOR", "IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("IDFACTURA")
	  REFERENCES "SICAS_OC"."FACTURAS" ("IDFACTURA") ENABLE, 
	 FOREIGN KEY ("CODCOBRADOR")
	  REFERENCES "SICAS_OC"."COBRADORES" ("CODCOBRADOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
