
  CREATE TABLE "SICAS_OC"."COMISIONES" 
   (	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0), 
	"IDNCR" NUMBER(14,0), 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0), 
	"IDCOMISION" NUMBER(14,0) NOT NULL ENABLE, 
	"COMISION_LOCAL" NUMBER(18,2), 
	"COMISION_MONEDA" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6), 
	"NUM_RECIBO" VARCHAR2(20), 
	"ESTADO" VARCHAR2(6), 
	"FEC_PAGO" DATE, 
	"FEC_GENERACION" DATE, 
	"FEC_LIQUIDACION" DATE, 
	"USUARIO_GENERO" VARCHAR2(30), 
	"IDENDOSO" VARCHAR2(14), 
	"NOMINA_PAGO" VARCHAR2(20), 
	"IDRECIBO" NUMBER(18,0), 
	"FEC_ESTADO" DATE, 
	"COM_SALDO_LOCAL" NUMBER(18,2), 
	"COM_SALDO_MONEDA" NUMBER(18,2), 
	"IDNOMINA" NUMBER(14,0), 
	"COMISION_MONEDA_ANT" NUMBER(18,2), 
	"COMISION_LOCAL_ANT" NUMBER(18,2), 
	"FECMOD" DATE, 
	"USRMOD" VARCHAR2(20), 
	"ORIGEN" VARCHAR2(1), 
	"IDLIQUIDACION" VARCHAR2(20), 
	"PRIMA_COMISINABLE_LOCAL" NUMBER(16,2), 
	"PRIMA_COMISIONABLE_EXT" NUMBER(16,2), 
	"OBSERVACION" CLOB DEFAULT EMPTY_CLOB(), 
	 CONSTRAINT "PK_COMISIONES" PRIMARY KEY ("CODCIA", "IDCOMISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("OBSERVACION") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
