
  CREATE TABLE "SICAS_OC"."COMPONENTES_SINIESTRO" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"ID_CONSECUTIVO" NUMBER(6,0), 
	"ID_COMPONENTE" VARCHAR2(6), 
	"MONTO_COMPONENTE" NUMBER(18,2), 
	"FEC_REGISTRO" DATE, 
	"USUARIO_REGISTRO" VARCHAR2(30), 
	 CONSTRAINT "COMPONENTES_SINIESTRO_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDSINIESTRO", "IDPOLIZA", "ID_CONSECUTIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
