
  CREATE TABLE "SICAS_OC"."CONCEPTOS_REPORTE_FONDOS" 
   (	"CODCIA" NUMBER, 
	"CODEMPRESA" NUMBER, 
	"ORDEN" NUMBER, 
	"CODCONCEPTO" VARCHAR2(12), 
	"DESCRICONCEPTO" VARCHAR2(200), 
	"SIGNO" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
