
  CREATE TABLE "SICAS_OC"."COND_GEN_AUTORIDAD" 
   (	"CODEMPRESA" NUMBER(14,0), 
	"CODCIA" NUMBER(14,0), 
	"IDTIPOSEG" VARCHAR2(6), 
	"NUMREGISTRO" NUMBER(6,0), 
	"DS_ARCH_CONGEN" VARCHAR2(100), 
	"STREGISTRO" VARCHAR2(6), 
	"FE_INIVIG" DATE, 
	"FE_FINVIG" DATE, 
	"NUMAUTORTIPSEG" VARCHAR2(40), 
	"CODUSUARIO" VARCHAR2(30), 
	"FE_ALTA" DATE, 
	"OBSERVACIONES" VARCHAR2(100), 
	 CONSTRAINT "COND_GEN_AUTORIDAD_PK" PRIMARY KEY ("CODEMPRESA", "CODCIA", "IDTIPOSEG", "NUMREGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
