
  CREATE TABLE "SICAS_OC"."CONFIG_COMISIONES" 
   (	"CODEMPRESA" NUMBER(14,0) CONSTRAINT "SYS_C007018" NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) CONSTRAINT "SYS_C007019" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C007020" NOT NULL ENABLE, 
	"PORCCOMISION" NUMBER(9,6), 
	"MONTOCOMISION" NUMBER(28,2), 
	 PRIMARY KEY ("CODEMPRESA", "IDTIPOSEG", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."TIPOS_DE_SEGUROS" ("IDTIPOSEG", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
