
  CREATE TABLE "SICAS_OC"."CONFIG_SOBRECOMISIONES" 
   (	"CODEMPRESA" NUMBER(14,0) CONSTRAINT "SYS_C007022" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C007024" NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) CONSTRAINT "SYS_C007023" NOT NULL ENABLE, 
	"RANGOINICIAL" NUMBER(18,2), 
	"RANGOFINAL" NUMBER(18,2), 
	"PORCSOBCOMIS" NUMBER(9,6), 
	"MONTOSOBCOMIS" NUMBER(28,2), 
	 FOREIGN KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."TIPOS_DE_SEGUROS" ("IDTIPOSEG", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
