
  CREATE TABLE "SICAS_OC"."CONFIG_RESERVAS_FACTOR_EDAD" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODRESERVA" VARCHAR2(10) NOT NULL ENABLE, 
	"EDAD" NUMBER(3,0) NOT NULL ENABLE, 
	"FACTORBASICA" NUMBER(14,9) NOT NULL ENABLE, 
	"FACTORADIC" NUMBER(14,9) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CONFIG_RESERVAS_FACTOR_EDAD" PRIMARY KEY ("CODCIA", "CODRESERVA", "EDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_CONFIG_RVAS_FACT_EDAD" FOREIGN KEY ("CODCIA", "CODRESERVA")
	  REFERENCES "SICAS_OC"."CONFIG_RESERVAS" ("CODCIA", "CODRESERVA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
