
  CREATE TABLE "SICAS_OC"."CONTROL_CAMBIO_DATOS" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDCAMPO" VARCHAR2(50), 
	"IDTABLA" VARCHAR2(50), 
	"VALORANTERIOR" VARCHAR2(100), 
	"VALORNUEVO" VARCHAR2(100), 
	"USUARIO_SOLICITANTE" VARCHAR2(30), 
	"USUARIO_REGISTRO" VARCHAR2(30), 
	"FECHAREGISTRO" DATE, 
	"MOTIVO" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
