--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM CONTROL_PAGOS_CHEQUES;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.CONTROL_PAGOS_CHEQUES;

/
--CREACION DE TABLA CONTROL_PAGOS_CHEQUES PARA LLEVAR EL REGISTRO DE LOS CHEQUES. SE CARGA DESDE EL ARCHIVO .XLSX
CREATE TABLE SICAS_OC.CONTROL_PAGOS_CHEQUES(
                                ID_CONTROL          VARCHAR2(100)   NOT NULL
                                ,CODCIA             NUMBER          NOT NULL
                                ,TIPO_PROCESO       VARCHAR2(100)   NOT NULL
                                ,NOMBRE_ARCHIVO     VARCHAR2(100)   NOT NULL
                                ,FECHA_PROCESO      DATE            NOT NULL
                                ,CONCEPTO           VARCHAR2(50)  
                                ,CHEQUE             NUMBER          NOT NULL
                                ,REFERENCIA_APLIADA VARCHAR2(200)   
                                ,RFC                VARCHAR2(15)
                                ,CARGO              FLOAT
                                ,ABONO              FLOAT
                                ,REFERENCIA         VARCHAR2(100)
                                ,USUARIO_ALTA		VARCHAR2(50)	NOT NULL
								,FECHA_ALTA			DATE			NOT NULL
								,USUARIO_MOD		VARCHAR2(50)	NOT NULL
								,FECHA_MOD			DATE			NOT NULL
                                ) TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.CONTROL_PAGOS__CHEQUES_IDX_1 ON SICAS_OC.CONTROL_PAGOS_CHEQUES (ID_CONTROL, CODCIA, TIPO_PROCESO, NOMBRE_ARCHIVO) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.CONTROL_PAGOS_CHEQUES ADD CONSTRAINT PK_CONTROL_PAGOS_CHEQUES PRIMARY KEY (ID_CONTROL, CODCIA, TIPO_PROCESO, NOMBRE_ARCHIVO) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX ON SICAS_OC.CONTROL_PAGOS_CHEQUES TO PUBLIC;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.ID_CONTROL         IS 'CONSECUTIVO QUE FORMA PARTE DE LA LLAVE PRIMARIA';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.CODCIA             IS 'CODIGO DE COMPAÑIA THONA SEGUROS';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.TIPO_PROCESO       IS 'IDENTIFICADOR DEL TIPO DE PROCESO QUE EXTRAE INFORMACIÓN';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.NOMBRE_ARCHIVO 	IS 'NOMBRE DEL ARCHIVO QUE SE PROCESO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.FECHA_PROCESO 	    IS 'FECHA QUE CONTIENE EL DOCUMENTO QUE SE ESTA CARGANDO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.CONCEPTO 			IS 'CONCEPTO ASOCIADO A LA OPERACIÓN';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.CHEQUE 			IS 'NUMERO DE CHEQUE';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.REFERENCIA_APLIADA IS 'REFERENCIA AMPLIADA QUE SE TIENE';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.RFC                IS 'RFC ASOCIADO AL CHEQUE';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.CARGO 		        IS 'MONTO DEL CARGO ASOCIADO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.ABONO 		        IS 'MONTO DEL ABONO ASOCIADO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.REFERENCIA 		IS 'NUMERO DE REFERENCIA ASOCIADO AL CHEQUE';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.USUARIO_ALTA       IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.FECHA_ALTA         IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.USUARIO_MOD        IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS_CHEQUES.FECHA_MOD          IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE ACTUALIZA EL REGISTRO';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM CONTROL_PAGOS_CHEQUES FOR SICAS_OC.CONTROL_PAGOS_CHEQUES;