--SINONIMO SE ELIMINA
DROP PUBLIC SYNONYM CONTROL_PAGOS;

--TABLA SE ELIMINA
DROP TABLE SICAS_OC.CONTROL_PAGOS;

/
--CREACION DE TABLA CONTROL_PAGOS PARA LLEVAR EL REGISTRO DE LOS PAGOS OBTENIDOS. SE CARGA DESDE EL ARCHIVO .TXT
CREATE TABLE SICAS_OC.CONTROL_PAGOS(
                                ID_CONTROL          VARCHAR2(100)   NOT NULL
                                ,CODCIA             NUMBER          NOT NULL
                                ,TIPO_PROCESO       VARCHAR2(100)   NOT NULL
                                ,NOMBRE_ARCHIVO     VARCHAR2(100)   NOT NULL
                                ,FECHA_PROCESO      DATE            NOT NULL
                                ,CUENTA             VARCHAR2(20)  
                                ,IMPORTE            FLOAT    
                                ,BENEFICIARIO       VARCHAR2(50)    
                                ,SINIESTRO          VARCHAR2(30)
                                ,USUARIO_ALTA		VARCHAR2(50)	NOT NULL
								,FECHA_ALTA			DATE			NOT NULL
								,USUARIO_MOD		VARCHAR2(50)	NOT NULL
								,FECHA_MOD			DATE			NOT NULL
                                ) TABLESPACE TS_SICASOC;


/
--INDICES
CREATE UNIQUE INDEX SICAS_OC.CONTROL_PAGOS_IDX_1 ON SICAS_OC.CONTROL_PAGOS (ID_CONTROL, CODCIA, TIPO_PROCESO, NOMBRE_ARCHIVO) TABLESPACE IDX_SICASOC;	

/
--PRIMARY Y FOREIGN KEY
ALTER TABLE SICAS_OC.CONTROL_PAGOS ADD CONSTRAINT PK_CONTROL_PAGOS PRIMARY KEY (ID_CONTROL, CODCIA, TIPO_PROCESO, NOMBRE_ARCHIVO) USING INDEX;

/
--##GRANTs
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX ON SICAS_OC.CONTROL_PAGOS TO PUBLIC;

/
--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.ID_CONTROL         IS 'CONSECUTIVO QUE FORMA PARTE DE LA LLAVE PRIMARIA';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.CODCIA             IS 'CODIGO DE COMPAÑIA THONA SEGUROS';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.TIPO_PROCESO       IS 'IDENTIFICADOR DEL TIPO DE PROCESO QUE EXTRAE INFORMACIÓN';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.NOMBRE_ARCHIVO 	IS 'NOMBRE DEL ARCHIVO QUE SE PROCESO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.FECHA_PROCESO 	    IS 'FECHA QUE CONTIENE EL DOCUMENTO QUE SE ESTA CARGANDO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.CUENTA 			IS 'CUENTA CLABE O CUENTA BBVB DEL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.IMPORTE 			IS 'IMPORTE DE LA TRANSFERENCIA';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.BENEFICIARIO 		IS 'NOMBRE DEL BENEFICIARIO ASOCIADO AL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.SINIESTRO 		    IS 'NUMERO DE SINIESTRO ASOCIADO AL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.USUARIO_ALTA       IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.FECHA_ALTA         IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.USUARIO_MOD        IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.CONTROL_PAGOS.FECHA_MOD          IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE ACTUALIZA EL REGISTRO';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM CONTROL_PAGOS FOR SICAS_OC.CONTROL_PAGOS;