
  CREATE TABLE "SICAS_OC"."CONTROL_PROCESOS_AUTOMATICOS" 
   (	"NOMBREPROCESO" VARCHAR2(30), 
	"FECHAEJECUCION" DATE, 
	"ID_ENVIO" VARCHAR2(100), 
	"ID_USER" VARCHAR2(20), 
	"ID_TERMINAL" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
