
  CREATE TABLE "SICAS_OC"."CORREGIMIENTO" 
   (	"CODPAIS" VARCHAR2(3) CONSTRAINT "SYS_C007027" NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) CONSTRAINT "SYS_C007028" NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) CONSTRAINT "SYS_C007029" NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) CONSTRAINT "SYS_C007030" NOT NULL ENABLE, 
	"DESCMUNICIPIO" VARCHAR2(50) CONSTRAINT "SYS_C007031" NOT NULL ENABLE, 
	"CODCORREGALTERNO" VARCHAR2(3), 
	 PRIMARY KEY ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODPAIS", "CODESTADO", "CODCIUDAD")
	  REFERENCES "SICAS_OC"."DISTRITO" ("CODPAIS", "CODESTADO", "CODCIUDAD") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
