
  CREATE TABLE "SICAS_OC"."CORREOS_ELECTRONICOS_CONTACTOS" 
   (	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CORR_CONTACTO" NUMBER(14,0) NOT NULL ENABLE, 
	"CORRELATIVO_EMAIL" NUMBER(5,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(150) NOT NULL ENABLE, 
	"EMAIL_PRINCIPAL" VARCHAR2(1) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODEMPRESA", "CODCIA", "CORR_CONTACTO", "CORRELATIVO_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
