
  CREATE TABLE "SICAS_OC"."COSTO_VEHICULO" 
   (	"ANIO_VEHICULO" NUMBER(4,0) CONSTRAINT "SYS_C007033" NOT NULL ENABLE, 
	"COD_MARCA" VARCHAR2(10) CONSTRAINT "SYS_C007034" NOT NULL ENABLE, 
	"COD_VERSION" VARCHAR2(10) CONSTRAINT "SYS_C007035" NOT NULL ENABLE, 
	"COD_MODELO" VARCHAR2(10) CONSTRAINT "SYS_C007036" NOT NULL ENABLE, 
	"COSTO_VEHICULO" NUMBER(18,2), 
	"FECHA_COSTO" DATE, 
	"CIF" NUMBER(18,2), 
	 PRIMARY KEY ("ANIO_VEHICULO", "COD_MARCA", "COD_VERSION", "COD_MODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("COD_MARCA", "COD_VERSION", "COD_MODELO")
	  REFERENCES "SICAS_OC"."VERSION" ("COD_MARCA", "COD_VERSION", "COD_MODELO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
