
  CREATE TABLE "SICAS_OC"."COTIZACION" 
   (	"NUM_COTIZACION" NUMBER(14,0) CONSTRAINT "SYS_C007038" NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"CODPLANPAGO" VARCHAR2(4) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"PLAN_COBERTURAS" VARCHAR2(6) NOT NULL ENABLE, 
	"PRIMER_NOMBRE" VARCHAR2(100), 
	"SEGUNDO_NOMBRE" VARCHAR2(100), 
	"PRIMER_APELLIDO" VARCHAR2(100), 
	"SEGUNDO_APELLIDO" VARCHAR2(100), 
	"APELLIDO_CASADA" VARCHAR2(100), 
	"SEXO" VARCHAR2(3), 
	"TELEFONOS" VARCHAR2(100), 
	"DIRECCION" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"CODUSUARIO" VARCHAR2(30), 
	"COD_MONEDA" VARCHAR2(5), 
	"FECHA" DATE, 
	"STSCOTIZACION" VARCHAR2(3), 
	"FECHA_NAC" DATE, 
	"MOTIVO_ANULA" VARCHAR2(6), 
	"FECHA_ANULA" DATE, 
	"DESCRIPCION" VARCHAR2(200), 
	"SUMAASEGURADA" NUMBER(14,2), 
	"INDTARIFA" VARCHAR2(1), 
	 PRIMARY KEY ("NUM_COTIZACION", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
