--
-- COTIZACIONES_DETALLE_FACTOR  (Table) 
--
CREATE TABLE SICAS_OC.COTIZACIONES_DETALLE_FACTOR
(
  CODCIA               NUMBER(14)               NOT NULL,
  CODEMPRESA           NUMBER(14)               NOT NULL,
  IDCOTIZACION         NUMBER(14)               NOT NULL,
  IDETCOTIZACION       NUMBER(14)               NOT NULL,
  TIPOFACTOR           VARCHAR2(6 BYTE)         NOT NULL,
  CODFACTOR            VARCHAR2(10 BYTE)        NOT NULL,
  FACTOR               NUMBER(9,6)              DEFAULT 1
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.COTIZACIONES_DETALLE_FACTOR IS 'Registro de los Factores de Ajuste por Detalle o SubGrupos de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.CODCIA IS 'Código de Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.CODEMPRESA IS 'Código de Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.IDCOTIZACION IS 'No. de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.IDETCOTIZACION IS 'No. de Detalle de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.TIPOFACTOR IS 'Tipo de Factor'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.CODFACTOR IS 'Código del Factor'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_DETALLE_FACTOR.FACTOR IS 'Factor a Aplicar'
/

--
-- PK_COTIZACIONES_DETALLE_FACTOR  (Index) 
--
--  Dependencies: 
--   COTIZACIONES_DETALLE_FACTOR (Table)
--
CREATE UNIQUE INDEX SICAS_OC.PK_COTIZACIONES_DETALLE_FACTOR ON SICAS_OC.COTIZACIONES_DETALLE_FACTOR
(CODCIA, CODEMPRESA, IDCOTIZACION, IDETCOTIZACION, TIPOFACTOR, CODFACTOR)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- COTIZACIONES_DETALLE_FACTOR  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZACIONES_DETALLE_FACTOR FOR SICAS_OC.COTIZACIONES_DETALLE_FACTOR
/

-- 
-- Non Foreign Key Constraints for Table COTIZACIONES_DETALLE_FACTOR 
-- 
ALTER TABLE SICAS_OC.COTIZACIONES_DETALLE_FACTOR ADD (
  CONSTRAINT PK_COTIZACIONES_DETALLE_FACTOR
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDCOTIZACION, IDETCOTIZACION, TIPOFACTOR, CODFACTOR)
  USING INDEX SICAS_OC.PK_COTIZACIONES_DETALLE_FACTOR
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZACIONES_DETALLE_FACTOR TO PUBLIC
/