CREATE TABLE SICAS_OC.COTIZADOR_NOTIFICA
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  CODCOTIZADOR        VARCHAR2(30 BYTE)         NOT NULL,
  CODUSUARIO          VARCHAR2(30 BYTE)         NOT NULL,
  STSUSUARIO          VARCHAR2(6 BYTE)          NOT NULL,
  USUARIO_ASIGNO      VARCHAR2(30 BYTE)         NOT NULL,
  FECHA_ASIGNACION    DATE                      NOT NULL,
  USUARIO_MODIFICO    VARCHAR2(30 BYTE),
  FECHA_MODIFICACION  DATE
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.COTIZADOR_NOTIFICA IS 'Configuración de Usuarios para Notificar Cotizaciones'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.CODCOTIZADOR IS 'Código del Cotizador'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.CODUSUARIO IS 'Usuario Asignado'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.STSUSUARIO IS 'Estatus del Usuario Asignado'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.USUARIO_ASIGNO IS 'Usuario que Asignó'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.FECHA_ASIGNACION IS 'Fecha de Asignación'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.USUARIO_MODIFICO IS 'Usuario que Modificó la Asignación'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_NOTIFICA.FECHA_MODIFICACION IS 'Fecha de Modificación de Asignación'
/

CREATE UNIQUE INDEX SICAS_OC.PK_COTIZADOR_NOTIFICA ON SICAS_OC.COTIZADOR_NOTIFICA
(CODCIA, CODEMPRESA, CODCOTIZADOR, CODUSUARIO)
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

-- 
-- Non Foreign Key Constraints for Table COTIZADOR_NOTIFICA 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_NOTIFICA ADD (
  CONSTRAINT PK_COTIZADOR_NOTIFICA
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODCOTIZADOR, CODUSUARIO)
  USING INDEX SICAS_OC.PK_COTIZADOR_NOTIFICA
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table COTIZADOR_NOTIFICA 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_NOTIFICA ADD (
  CONSTRAINT FK_COT_NOTIFICA_CODCOTIZADOR
  FOREIGN KEY (CODCIA, CODEMPRESA, CODCOTIZADOR)
  REFERENCES SICAS_OC.COTIZADOR_CONFIG (CODCIA, CODEMPRESA, CODCOTIZADOR)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
