
  CREATE TABLE "SICAS_OC"."COTIZACION_SEGUIMIENTO" 
   (	"CODCIA" NUMBER(14,0), 
	"NUM_COTIZACION" NUMBER(14,0), 
	"CODUSUARIO" VARCHAR2(30), 
	"FECHA" DATE, 
	"OBSERVACION" VARCHAR2(4000), 
	"NUMLINEA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
