
  CREATE TABLE "SICAS_OC"."COTIZACIONES_CLAUSULAS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDCOTIZACION" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCLAUSULA" VARCHAR2(6) NOT NULL ENABLE, 
	"TEXTOCLAUSULA" LONG, 
	 CONSTRAINT "PK_COTIZACIONES_CLAUSULAS" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDCOTIZACION", "CODCLAUSULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_COTIZACIONES_CLAUSULAS_COT" FOREIGN KEY ("CODCIA", "CODEMPRESA", "IDCOTIZACION")
	  REFERENCES "SICAS_OC"."COTIZACIONES" ("CODCIA", "CODEMPRESA", "IDCOTIZACION") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
