
  CREATE TABLE "SICAS_OC"."COTIZADOR_NOTIFICA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCOTIZADOR" VARCHAR2(30) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"STSUSUARIO" VARCHAR2(6) NOT NULL ENABLE, 
	"USUARIO_ASIGNO" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHA_ASIGNACION" DATE NOT NULL ENABLE, 
	"USUARIO_MODIFICO" VARCHAR2(30), 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "PK_COTIZADOR_NOTIFICA" PRIMARY KEY ("CODCIA", "CODEMPRESA", "CODCOTIZADOR", "CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_COT_NOTIFICA_CODCOTIZADOR" FOREIGN KEY ("CODCIA", "CODEMPRESA", "CODCOTIZADOR")
	  REFERENCES "SICAS_OC"."COTIZADOR_CONFIG" ("CODCIA", "CODEMPRESA", "CODCOTIZADOR") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
