DROP TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB
/
--
-- COTIZADOR_GPO_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB
(
  CODCIA            NUMBER(14)                  NOT NULL,
  CODEMPRESA        NUMBER(14)                  NOT NULL,
  CODCOTIZADOR      VARCHAR2(30 BYTE)           NOT NULL,
  IDTIPOSEG         VARCHAR2(6 BYTE)            NOT NULL,
  PLANCOB           VARCHAR2(15 BYTE)           NOT NULL,
  CODGPOCOBERTWEB   VARCHAR2(6 BYTE)            NOT NULL
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB IS 'Cotizador Grupo Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODCOTIZADOR IS 'Código del Cotizador'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/


--
-- COTIZADOR_GPO_COBERT_WEB_PK  (Index) 
--
--  Dependencies: 
--   COTIZADOR_GPO_COBERT_WEB (Table)
--
CREATE UNIQUE INDEX SICAS_OC.COTIZADOR_GPO_COBERT_WEB_PK ON SICAS_OC.COTIZADOR_GPO_COBERT_WEB
(CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, 
CODGPOCOBERTWEB)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- COTIZADOR_GPO_COBERT_WEB  (Synonym) 
--
--  Dependencies: 
--   COTIZADOR_GPO_COBERT_WEB (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZADOR_GPO_COBERT_WEB FOR SICAS_OC.COTIZADOR_GPO_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZADOR_GPO_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB ADD (
  CONSTRAINT COTIZADOR_GPO_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, CODGPOCOBERTWEB)
  USING INDEX SICAS_OC.COTIZADOR_GPO_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZADOR_GPO_COBERT_WEB TO PUBLIC
/