DROP TABLE SICAS_OC.COTIZADOR_COBERT_WEB
/
--
-- COTIZADOR_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZADOR_COBERT_WEB
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  CODCOTIZADOR        VARCHAR2(30 BYTE)         NOT NULL,
  IDTIPOSEG           VARCHAR2(6 BYTE)          NOT NULL,
  PLANCOB             VARCHAR2(15 BYTE)         NOT NULL,
  CODGPOCOBERTWEB     VARCHAR2(6 BYTE)          NOT NULL,
  CODCOBERTWEB        VARCHAR2(6 BYTE)          NOT NULL,
  IDCOTIZACION        NUMBER(14)                NOT NULL,
  IDETCOTIZACION      NUMBER(14)                NOT NULL,
  SUMAASEGCOBLOCAL    NUMBER(28,2),
  SUMAASEGCOBMONEDA   NUMBER(28,2),
  TASA                NUMBER(18,6),
  PRIMACOBLOCAL       NUMBER(28,2),
  PRIMACOBMONEDA      NUMBER(28,2),
  DEDUCIBLECOBLOCAL   NUMBER(28,2),
  DEDUCIBLECOBMONEDA  NUMBER(28,2),
  SALARIOMENSUAL      NUMBER(28,2),
  VECESSALARIO        NUMBER(10),
  SUMAASEGCALCULADA   NUMBER(28,2),
  EDAD_MINIMA         NUMBER(3),
  EDAD_MAXIMA         NUMBER(3),
  EDAD_EXCLUSION      NUMBER(3),
  SUMAASEG_MINIMA     NUMBER(28,2),
  SUMAASEG_MAXIMA     NUMBER(28,2),
  PORCEXTRAPRIMADET   NUMBER(9,6),
  MONTOEXTRAPRIMADET  NUMBER(18,2),
  SUMAINGRESADA       NUMBER(28,2),
  ORDENIMPRESION      NUMBER(4),
  DEDUCIBLEINGRESADO  NUMBER(28,2),
  CUOTAPROMEDIO       NUMBER(18,6),
  PRIMAPROMEDIO       NUMBER(28,2)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.COTIZADOR_COBERT_WEB IS 'Cotizador Grupo Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCOTIZADOR IS 'Código del Cotizador'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCOBERTWEB IS 'Código de Cobertura Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDCOTIZACION IS 'No. de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDETCOTIZACION IS 'No. de Detalle de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCOBLOCAL IS 'Suma Asegurada Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCOBMONEDA IS 'Suma Asegurada Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.TASA IS 'Tasa de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMACOBLOCAL IS 'Prima Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMACOBMONEDA IS 'Prima Moneta de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLECOBLOCAL IS 'Deducible Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLECOBMONEDA IS 'Deducible Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SALARIOMENSUAL IS 'Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.VECESSALARIO IS 'Veces de Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCALCULADA IS 'Suma Asegurada Calculada'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_MINIMA IS 'Edad Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_MAXIMA IS 'Edad Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_EXCLUSION IS 'Edad Exclusion de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEG_MINIMA IS 'Suma Asegurada Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEG_MAXIMA IS 'Suma Asegurada Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PORCEXTRAPRIMADET IS 'Porcentaje de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.MONTOEXTRAPRIMADET IS 'Monto de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAINGRESADA IS 'Suma Asegurada Ingresada por Usuario'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.ORDENIMPRESION IS 'Orden de Impresión de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLEINGRESADO IS 'Deducible Ingresado para Tarifa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CUOTAPROMEDIO IS 'Cuota Promedio de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMAPROMEDIO IS 'Prima Promedio de Cobertura'
/



--
-- COTIZADOR_COBERT_WEB_PK  (Index) 
--
--  Dependencies: 
--   COTIZADOR_COBERT_WEB (Table)
--
CREATE UNIQUE INDEX SICAS_OC.COTIZADOR_COBERT_WEB_PK ON SICAS_OC.COTIZADOR_COBERT_WEB
(CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, 
CODGPOCOBERTWEB, CODCOBERTWEB, IDCOTIZACION, IDETCOTIZACION)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- COTIZADOR_COBERT_WEB  (Synonym) 
--
--  Dependencies: 
--   COTIZADOR_COBERT_WEB (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZADOR_COBERT_WEB FOR SICAS_OC.COTIZADOR_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZADOR_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_COBERT_WEB ADD (
  CONSTRAINT COTIZADOR_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, CODGPOCOBERTWEB, CODCOBERTWEB, IDCOTIZACION, IDETCOTIZACION)
  USING INDEX SICAS_OC.COTIZADOR_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZADOR_COBERT_WEB TO PUBLIC
/