
  CREATE TABLE "SICAS_OC"."COTIZACIONES_GPO_COBERT_WEB" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDCOTIZACION" NUMBER(14,0) NOT NULL ENABLE, 
	"CODGPOCOBERTWEB" VARCHAR2(6) NOT NULL ENABLE, 
	"ACTUALIZO_USUARIO" VARCHAR2(30 CHAR) DEFAULT USER, 
	"ACTUALIZO_FECHA" DATE DEFAULT sysdate, 
	 CONSTRAINT "COTIZACIONES_GPO_COBERT_WEB_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDCOTIZACION", "CODGPOCOBERTWEB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
