
  CREATE TABLE "SICAS_OC"."COTIZADOR_TIPOSEG" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCOTIZADOR" VARCHAR2(30) NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"FECALTA" DATE, 
	"STSTIPOSEGCOT" VARCHAR2(6), 
	"FECSTATUS" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "PK_COTIZADOR_TIPOSEG" PRIMARY KEY ("CODCIA", "CODEMPRESA", "CODCOTIZADOR", "IDTIPOSEG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_COTIZADOR_TIPOSEG_CONFIG" FOREIGN KEY ("CODCIA", "CODEMPRESA", "CODCOTIZADOR")
	  REFERENCES "SICAS_OC"."COTIZADOR_CONFIG" ("CODCIA", "CODEMPRESA", "CODCOTIZADOR") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
