
  CREATE TABLE "SICAS_OC"."CPTOS_TRANSAC_SINIESTROS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODTRANSAC" VARCHAR2(6) NOT NULL ENABLE, 
	"INDTIPOCOBERT" VARCHAR2(2) NOT NULL ENABLE, 
	"CODCPTOTRANSAC" VARCHAR2(6) NOT NULL ENABLE, 
	"INDDISMINRVA" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE, 
	 CONSTRAINT "PK_CPTOS_TRANSAC_SINIESTROS" PRIMARY KEY ("CODCIA", "CODTRANSAC", "INDTIPOCOBERT", "CODCPTOTRANSAC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_CPTOS_TRANSAC_SINIESTROS" FOREIGN KEY ("CODCIA", "CODTRANSAC")
	  REFERENCES "SICAS_OC"."CONFIG_TRANSAC_SINIESTROS" ("CODCIA", "CODTRANSAC") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
