
--ELIMINACION SINONIMO TABLA
DROP PUBLIC SYNONYM SESAS_SIN_APC;
/

--ELIMINACION SINONIMO SECUENCIA 
DROP PUBLIC SYNONYM SESAS_SIN_APC_SEQ; 
/

---ELIMINACION DE SECUENCIA SICAS_OC.SESAS_HIST_SEQ
DROP SEQUENCE SICAS_OC.SESAS_SIN_APC_SEQ;
/
----ELIMINACION DE TABLA SICAS_OC.SESAS_SIN_APC

DROP TABLE SICAS_OC.SESAS_SIN_APC; 
/
----SCRIPT SECUENCIA SICAS_OC.SESAS_SIN_APC_SEQ

  CREATE SEQUENCE SICAS_OC.SESAS_SIN_APC_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  MINVALUE 1
  ORDER;
 /
 ---CREACION DE TABLA SICAS_OC.SESAS_SIN_APC
 CREATE TABLE SICAS_OC.SESAS_SIN_APC(
ID_SESAS_SIN_APC NUMBER  DEFAULT SICAS_OC.SESAS_SIN_APC_SEQ.NEXTVAL
,CODCIA NUMBER DEFAULT 1
,CODEMPRESA NUMBER DEFAULT 1
,IDPOLIZA NUMBER
,IDSINIESTRO NUMBER NOT NULL
,NPOLIZA VARCHAR2(50)
,FEC_OCU DATE
,FEC_EST DATE
,MONTO NUMBER
,COBERTURA VARCHAR2(20)
,MAXIMO NUMBER
,RECL NUMBER
,R2 NUMBER
,NREC_OK NUMBER
,CREATION_BY VARCHAR2(30) DEFAULT USER
,CREATION_DATE DATE DEFAULT SYSDATE
,LAST_UPDATE_BY VARCHAR2(30) DEFAULT USER
,LAST_UPDATE_DATE DATE DEFAULT SYSDATE

)TABLESPACE TS_SICASOC;
/
---CREACION DE INDEX

CREATE UNIQUE INDEX SICAS_OC.SESAS_SIN_APC_IDX ON SICAS_OC.SESAS_SIN_APC(CODCIA,CODEMPRESA,ID_SESAS_SIN_APC) TABLESPACE IDX_SICASOC;

--CREACION DE INDEX SOLO PARA IDSINIESTRO

CREATE  INDEX SICAS_OC.SIN_SESAS_SIN_APC_IDSINIESTRO_IDX ON SICAS_OC.SESAS_SIN_APC(IDSINIESTRO) TABLESPACE IDX_SICASOC;

 --CREACION DE PK PARA COLUMNAS
  ALTER TABLE SICAS_OC.SESAS_SIN_APC ADD CONSTRAINT PK_SESAS_SIN_APC PRIMARY KEY (CODCIA,CODEMPRESA,ID_SESAS_SIN_APC) USING INDEX SESAS_SIN_APC_IDX;
  
  --##GRANTs

GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.SESAS_SIN_APC TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.SESAS_SIN_APC TO ROL_CONSULTA_SICAS;
  
  --SINONIMO
  CREATE OR REPLACE PUBLIC SYNONYM SESAS_SIN_APC FOR SICAS_OC.SESAS_SIN_APC;

    
  --PERMISOS SECUENCIA SICAS_OC.SESAS_SIN_APC_SEQ
  GRANT SELECT ON SICAS_OC.SESAS_SIN_APC_SEQ  TO PUBLIC ;
  /
  CREATE OR REPLACE PUBLIC SYNONYM SESAS_SIN_APC_SEQ FOR SICAS_OC.SESAS_SIN_APC_SEQ;
  /

----COMENTARIO TABLA
  COMMENT ON TABLE SICAS_OC.SESAS_SIN_APC IS 'Información DE SINIESTROS HACIENDO AGRUPACION POR MONTO,FECHA_OCU,FECHA_EST YA UNIFICADOS';

  --##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.IDSINIESTRO             IS 'NUMERO DE SINIESTRO DE LA TABLA SESAS_SIN_APC';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.NPOLIZA 		        IS 'NUMERO DE POLIZA';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.FEC_EST 			    IS 'FECHA DE REPORTE';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.FEC_OCU 			IS 'FECHA OCURRENCIA';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.MONTO 			    IS 'MONTO SUMADO DE SINIESTRO AGRUPADO POR MONTO,FECHA_OCU,FECHA_EST YA UNIFICADOS';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.MAXIMO 			    IS 'NUMERO MAXIMO DE NUM RECLAMACION DE SESAS_HISTORICO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.RECL 			    IS 'NUMERO MAXIMO DE NREC + 1';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.R2			    IS 'VALOR DE NREC VALIDANDO MONTOS';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.NREC_OK			    IS 'NUMERO DE RECLAMACION FINAL';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.CREATION_BY 			    IS 'REGISTRO CREADO POR';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.CREATION_DATE             IS 'FECHA DE CREACION DE REGISTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.LAST_UPDATE_BY               IS 'FECHA DE ULTIMA ACTUALIZACION POR';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC.LAST_UPDATE_DATE              IS 'FECHA DE ULTIMA ACTUALIZACION';