
--ELIMINACION SINONIMO TABLA
DROP PUBLIC SYNONYM SESAS_SIN_ATECNICA_EXT;
/

--ELIMINACION TABLA
DROP table SICAS_OC.SESAS_SIN_ATECNICA_EXT;
/

--
CREATE TABLE SICAS_OC.SESAS_SIN_ATECNICA_EXT(


LLAVE VARCHAR2(100),	
CUENTA VARCHAR2(30),
SUBRAMO VARCHAR2(30),
CONSECUTIVO NUMBER NOT NULL,
NPOLIZA VARCHAR2(50),
SINIESTRO NUMBER NOT NULL,
CVCOB VARCHAR2(50),
TIPOADIC VARCHAR2(50),
ADOMES VARCHAR2(50),
FEC_BZA DATE,
NUM_ASIST VARCHAR2(50),
INIVIGPOL DATE,	
FINVIGPOL DATE,
FEC_EST DATE,
FEC_OCU DATE,
FEC_REP DATE,
FEC_NAC DATE,
CVESTIMADO VARCHAR2(50),
DESC_CIE10 VARCHAR2(100),
NOM_ASEG VARCHAR2(100),
CAUSA VARCHAR2(200),
TIPOSEGURO VARCHAR2(10),
MONTO NUMBER,
ND_5401_05 NUMBER,
SISTEMA VARCHAR2(10),
RAMSUBRAMO VARCHAR2(10),
RAMO VARCHAR2(20),
CTA_5411 NUMBER,
CTA_5411_2 NUMBER,
MES_STATUS DATE,
N_CONTRATO VARCHAR2(20),
REASEG VARCHAR2(20),
MONTO_AP NUMBER,
VIGENCIA DATE,
CONTRATANT VARCHAR2(200),
VAL1 NUMBER,
VAL2 NUMBER,
C_5401_03 NUMBER

)
ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DIR_CARGA_ASEG"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE DIR_CARGA_ASEG:'siniestros_1222.bad'
    LOGFILE DIR_CARGA_ASEG:'siniestros_1222.log'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    ( 

LLAVE 	
,CUENTA 
,SUBRAMO 
,CONSECUTIVO
,NPOLIZA 
,SINIESTRO 
,CVCOB 
,TIPOADIC 
,ADOMES 
,FEC_BZA  CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,NUM_ASIST 
,INIVIGPOL CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FINVIGPOL CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FEC_EST  CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FEC_OCU CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FEC_REP CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FEC_NAC CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,CVESTIMADO 
,DESC_CIE10 
,NOM_ASEG 
,CAUSA 
,TIPOSEGURO
,MONTO 
,ND_5401_05 
,SISTEMA 
,RAMSUBRAMO 
,RAMO 
,CTA_5411 
,CTA_5411_2 
,MES_STATUS CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,N_CONTRATO 
,REASEG 
,MONTO_AP 
,VIGENCIA CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,CONTRATANT
,VAL1 
,VAL2 
,C_5401_03 
    )
  )
      LOCATION
       ( "DIR_CARGA_ASEG":'siniestros_1222.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;


  GRANT SELECT ON "SICAS_OC"."SESAS_SIN_ATECNICA_EXT" TO PUBLIC;
 /
  -- =============================
-- Crea el Sinónimo
-- =============================
CREATE OR REPLACE PUBLIC SYNONYM SESAS_SIN_ATECNICA_EXT FOR SICAS_OC.SESAS_SIN_ATECNICA_EXT;
/

