
DROP TABLE SICAS_OC.SESAS_SIN_APC_FECM;
/

CREATE TABLE "SICAS_OC"."SESAS_SIN_APC_FECM" 
   (	"ID_SESAS_SIN_APC" NUMBER, 
	"CODCIA" NUMBER, 
	"CODEMPRESA" NUMBER, 
	"IDSINIESTRO" NUMBER NOT NULL ENABLE, 
	"FEC_OCU" DATE, 
	"FEC_EST" DATE, 
	"MONTO" NUMBER, 
	"MAXIMO" NUMBER, 
	"RECL" NUMBER, 
	"R2" NUMBER, 
	"NREC_OK" NUMBER
   ) TABLESPACE TS_SICASOC;
/
   --INDICES
CREATE UNIQUE INDEX SICAS_OC.SESAS_SIN_APC_FECM_IDX1 ON SICAS_OC.SESAS_SIN_APC_FECM (CODCIA,CODEMPRESA,IDSINIESTRO,ID_SESAS_SIN_APC) TABLESPACE IDX_SICASOC;	
 
/
--PRIMARY KEY
ALTER TABLE SICAS_OC.SESAS_SIN_APC_FECM ADD CONSTRAINT PK_SESAS_SIN_APC_FECM PRIMARY KEY (CODCIA,CODEMPRESA,IDSINIESTRO,ID_SESAS_SIN_APC) USING INDEX;
/
--SINONIMO TABLA 
CREATE OR REPLACE PUBLIC SYNONYM SESAS_SIN_APC_FECM FOR SICAS_OC.SESAS_SIN_APC_FECM;
/
--GRANTS
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.SESAS_SIN_APC_FECM TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.SESAS_SIN_APC_FECM TO ROL_CONSULTA_SICAS;
/
--COMENTARIO TABLA
  COMMENT ON TABLE SICAS_OC.SESAS_SIN_APC_FECM IS 'Registrso con fecha de ocurrencia menor al año de reporte NREC_OK';

--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.ID_SESAS_SIN_APC          IS 'NUMERO UNICO DE SINIESTRO DE LA TABLA SESAS_SIN_APC';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.CODCIA		        IS 'CODIGO COMPAÑIA';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.CODEMPRESA 			    IS 'CODIGO EMPRESA';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.IDSINIESTRO			IS 'ID SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.FEC_OCU			    IS 'FECHA OCURRENCIA SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.FEC_EST			    IS 'FECHA AÑO DE REPORTE';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.MONTO 			    IS 'MONTO SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.MAXIMO			    IS 'VALOR MAXIMO DE HISTORICO';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.RECL		    IS 'CLACULO RMAXIMO +1';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.R2			    IS 'CALCULO R2';
COMMENT ON COLUMN SICAS_OC.SESAS_SIN_APC_FECM.NREC_OK          IS 'CALCULO NREC_OK';
