-- Create table
DROP PUBLIC SYNONYM INCLU_ASEGURADOS_EXT;
DROP table SICAS_OC.INCLU_ASEGURADOS_EXT;
/
CREATE TABLE "SICAS_OC"."INCLU_ASEGURADOS_EXT" 
   ("CODEMPRESA" NUMBER(14,0), 
    "IDTIPOSEG" VARCHAR2(6 BYTE),
    "PLANCOB" VARCHAR2(15 BYTE),
    "NUMPOLUNICO" VARCHAR2(30 BYTE),
    "IDETPOL" NUMBER(14,0),
    "TIPO_DOC_IDENTIFICACION" VARCHAR2(6 BYTE),
    "NUM_DOC_IDENTIFICACION" VARCHAR2(20 BYTE),
    "NOMBRE" VARCHAR2(200 BYTE),
    "APELLIDO_PATERNO" VARCHAR2(50 BYTE),
    "APELLIDO_MATERNO" VARCHAR2(50 BYTE),
    "SEXO" VARCHAR2(1 BYTE),
    "FECNACIMIENTO" DATE,
    "TIPO_ID_TRIBUTARIA" VARCHAR2(5 BYTE),
    "NUM_TRIBUTARIO" VARCHAR2(20 BYTE),
    "FECINGRESO" DATE, 
    "FECSTATUS" DATE,
    "DIRECRES" VARCHAR2(250 BYTE),
    "CODPOSRES" VARCHAR2(30 BYTE),
    "CODCLIENTE" NUMBER(14,0),
    "FECINIVIG" DATE,
    "FECFINVIG" DATE,
    "FECINIVIGCERT" DATE,
    "FECFINVIGCERT" DATE,
    "SUMAASEG" NUMBER(14,0),
    "SUELDO" NUMBER(18,2),
    "NUTRA" VARCHAR2(500 BYTE),
    "CODCOBERT1" VARCHAR2(6 BYTE),
    "SUMAASEG_1" NUMBER(18,2),
    "CODCOBERT2" VARCHAR2(6 BYTE),
    "SUMAASEG_2" NUMBER(18,2),
    "CODCOBERT3" VARCHAR2(6 BYTE),
    "SUMAASEG_3" NUMBER(18,2),
    "CODCOBERT4" VARCHAR2(6 BYTE),
    "SUMAASEG_4" NUMBER(18,2),
    "CODCOBERT5" VARCHAR2(6 BYTE),
    "SUMAASEG_5" NUMBER(18,2),
    "CODCOBERT6" VARCHAR2(6 BYTE),
    "SUMAASEG_6" NUMBER(18,2),
    "CODCOBERT7" VARCHAR2(6 BYTE),
    "SUMAASEG_7" NUMBER(18,2),
    "CODCOBERT8" VARCHAR2(6 BYTE),
    "SUMAASEG_8" NUMBER(18,2)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DIR_CARGA_ASEG"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE DIR_CARGA_ASEG:'carga_inclusionasegurado.bad'
    LOGFILE DIR_CARGA_ASEG:'carga_inclusionasegurado.log'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    ( CODEMPRESA
    , IDTIPOSEG
    , PLANCOB
    , NUMPOLUNICO
    , IDETPOL
    , TIPO_DOC_IDENTIFICACION
    , NUM_DOC_IDENTIFICACION
    , NOMBRE
    , APELLIDO_PATERNO
    , APELLIDO_MATERNO
    , SEXO
    , FECNACIMIENTO     CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , TIPO_ID_TRIBUTARIA
    , NUM_TRIBUTARIO
    , FECINGRESO        CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , FECSTATUS         CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , DIRECRES
    , CODPOSRES
    , CODCLIENTE
    , FECINIVIG         CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , FECFINVIG         CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , FECINIVIGCERT     CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , FECFINVIGCERT     CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
    , SUMAASEG
    , SUELDO
    , NUTRA
    , CODCOBERT1
    , SUMAASEG_1
    , CODCOBERT2
    , SUMAASEG_2
    , CODCOBERT3
    , SUMAASEG_3
    , CODCOBERT4
    , SUMAASEG_4
    , CODCOBERT5
    , SUMAASEG_5
    , CODCOBERT6
    , SUMAASEG_6
    , CODCOBERT7
    , SUMAASEG_7
    , CODCOBERT8
    , SUMAASEG_8
    )
  )
      LOCATION
       ( "DIR_CARGA_ASEG":'carga_inclusionasegurado.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;


  GRANT SELECT ON "SICAS_OC"."INCLU_ASEGURADOS_EXT" TO PUBLIC;
 /
  -- =============================
-- Crea el Sinónimo
-- =============================
CREATE OR REPLACE PUBLIC SYNONYM INCLU_ASEGURADOS_EXT FOR SICAS_OC.INCLU_ASEGURADOS_EXT;
/