---ELIMINACION SINONIMO TABLA
DROP PUBLIC SYNONYM SESAS_HISTORICO_EXT;
/
--ELIMINACION TABLA
DROP table SICAS_OC.SESAS_HISTORICO_EXT;
/
CREATE TABLE SICAS_OC.SESAS_HISTORICO_EXT(

 ID_SESAS_HIST	NUMBER
,NPOLIZA	VARCHAR2(30)
,CERTIFICADO	VARCHAR2(30)
,IDSINIESTRO	NUMBER
,NUM_REC	NUMBER
,FECOCU	DATE
,FECREP	DATE
,FECCON	VARCHAR2(30)
,FECPAG	VARCHAR2(30)
,EST_REC	VARCHAR2(30)
,ENTIDAD_OC	VARCHAR2(30)
,COB_AFEC	VARCHAR2(30)
,FNACIM	VARCHAR2(30)
,SEXO	VARCHAR2(30)
,CAUSA	VARCHAR2(30 )
,TIP_MOV	VARCHAR2(30)
,MONTO	NUMBER
,MTO_DED	NUMBER
,MTO_COA	NUMBER
,MTO_PAG	NUMBER
,MTO_CED	NUMBER
,PC	VARCHAR2(30)
,ANOREP	VARCHAR2(30)
,IDPOLIZA NUMBER

)
ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "DIR_CARGA_ASEG"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE DIR_CARGA_ASEG:'SesasHistorico.bad'
    LOGFILE DIR_CARGA_ASEG:'SesasHistorico.log'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
    MISSING FIELD VALUES ARE NULL
    ( 
ID_SESAS_HIST 
,NPOLIZA 	
,CERTIFICADO	
,IDSINIESTRO	
,NUM_REC
,FECOCU	CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"	
,FECREP		CHAR DATE_FORMAT DATE MASK "DD/MM/YYYY"
,FECCON		
,FECPAG		
,EST_REC	
,ENTIDAD_OC	
,COB_AFEC	
,FNACIM	
,SEXO	
,CAUSA	
,TIP_MOV	
,MONTO	
,MTO_DED	
,MTO_COA	
,MTO_PAG	
,MTO_CED	
,PC	
,ANOREP	
,IDPOLIZA 
    )
  )
      LOCATION
       ( "DIR_CARGA_ASEG":'SesasHistorico.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;


  GRANT SELECT ON "SICAS_OC"."SESAS_HISTORICO_EXT" TO PUBLIC;
 /
  -- =============================
-- Crea el Sinónimo
-- =============================
CREATE OR REPLACE PUBLIC SYNONYM SESAS_HISTORICO_EXT FOR SICAS_OC.SESAS_HISTORICO_EXT;
/

