CREATE TABLE SOLICITUD_REGLA_SA(
CodCia         NUMBER(14) NOT NULL, 
CodEmpresa     NUMBER(14) NOT NULL,
IdSolicitud    NUMBER(14) NOT NULL,
IDetSol        NUMBER(14) NOT NULL,
CodCobert      VARCHAR2(6) NOT NULL,
ReglaSumaAseg  VARCHAR2(200) NOT NULL
)
TABLESPACE TS_SICASOC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/
COMMENT ON TABLE SOLICITUD_REGLA_SA IS 'Tabla para registrar la regla de SA en Emi Facil'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.CodCia IS 'Codigo de compañia'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.CodEmpresa IS 'Codigo de empresa'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.IdSolicitud IS 'Id Solicitud'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.IDetSol IS 'Sub Grupo de la Solicitud'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.CodCobert IS 'Cobertura de la Regla'
/
COMMENT ON COLUMN SOLICITUD_REGLA_SA.ReglaSumaAseg IS 'Texto de la Regla'
/
ALTER TABLE SICAS_OC.SOLICITUD_REGLA_SA ADD (
  CONSTRAINT PK_SOLICITUD_REGLA_SA
  PRIMARY KEY
  (CodCia, CodEmpresa, IdSolicitud, IDetSol, CodCobert)
  USING INDEX
    TABLESPACE TS_SICASOC
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

CREATE OR REPLACE PUBLIC SYNONYM SOLICITUD_REGLA_SA FOR SICAS_OC.SOLICITUD_REGLA_SA;
/
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SOLICITUD_REGLA_SA TO ROL_MODIFICA_SICAS;
/
GRANT SELECT ON SICAS_OC.SOLICITUD_REGLA_SA TO ROL_CONSULTA_SICAS;
--/
--GRANT SELECT, INSERT, UPDATE, DELETE ON SOLICITUD_REGLA_SA TO PUBLIC;
