

--ELIMINACION SINONIMO TABLA

DROP PUBLIC SYNONYM SESAS_SINIESTROS_ATECNICA;
/

--ELIMINACION SINONIMO SECUENCIA
DROP PUBLIC SYNONYM SESAS_SINIESTROS_ATECNICA_SEQ;
/
--ELIMINACION SECUENCIA
DROP SEQUENCE SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ;
/

--ELIMINACION TABLA
DROP TABLE SICAS_OC.SESAS_SINIESTROS_ATECNICA;

-----SCRIPT SECUENCIA SESAS_SINIESTROS_ATECNICA_SEQ
/

  CREATE SEQUENCE SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  MINVALUE 1
  ORDER;
/
--------SCRIPT CREACION DE TABLA

CREATE TABLE SICAS_OC.SESAS_SINIESTROS_ATECNICA(
ID_SESAS_SINIESTRO  NUMBER  DEFAULT SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ.NEXTVAL,
CODCIA NUMBER DEFAULT 1,
CODEMPRESA NUMBER DEFAULT 1,
LLAVE VARCHAR2(100),	
CUENTA VARCHAR2(30),
SUBRAMO VARCHAR2(30),
IDPOLIZA NUMBER NOT NULL,
NPOLIZA VARCHAR2(50),
IDSINIESTRO NUMBER NOT NULL,
CVCOB VARCHAR2(50),
TIPOADIC VARCHAR2(50),
ADOMES VARCHAR2(50),
FEC_BZA DATE,
NUM_ASIST VARCHAR2(50),
INIVIGPOL DATE,	
FINVIGPOL DATE,
FEC_EST DATE,
FEC_OCU DATE,
FEC_REP DATE,
FEC_NAC DATE,
CVESTIMADO VARCHAR2(50),
DESC_CIE10 VARCHAR2(100),
NOM_ASEG VARCHAR2(100),
CAUSA VARCHAR2(200),
TIPOSEGURO VARCHAR2(10),
MONTO NUMBER,
ND_5401_05 NUMBER,
SISTEMA VARCHAR2(10),
RAMSUBRAMO VARCHAR2(10),
RAMO VARCHAR2(20),
CTA_5411 NUMBER,
CTA_5411_2 NUMBER,
MES_STATUS DATE,
N_CONTRATO VARCHAR2(20),
REASEG VARCHAR2(20),
MONTO_AP NUMBER,
VIGENCIA DATE,
CONTRATANT VARCHAR2(200),
VAL1 NUMBER,
VAL2 NUMBER,
C_5401_03 NUMBER,
CREATION_BY VARCHAR2(30) DEFAULT USER,
CREATION_DATE DATE DEFAULT SYSDATE,
LAST_UPDATE_BY VARCHAR2(30) DEFAULT USER,
LAST_UPDATE_DATE DATE DEFAULT SYSDATE
)TABLESPACE TS_SICASOC;
/
 CREATE UNIQUE INDEX SICAS_OC.SIN_SESAS_SINIESTROS_AT_IDX ON SICAS_OC.SESAS_SINIESTROS_ATECNICA(CODCIA,CODEMPRESA,ID_SESAS_SINIESTRO) TABLESPACE IDX_SICASOC ;

 --CREACION DE INDEX PARA CAMPO ID_SINIESTRO,NPOLIZA,ID_POLIZA
 CREATE  INDEX SICAS_OC.SIN_SESAS_SINIESTROS_AT_IDPOLIZA_IDX ON SICAS_OC.SESAS_SINIESTROS_ATECNICA(IDPOLIZA) TABLESPACE IDX_SICASOC ;
 CREATE  INDEX SICAS_OC.SIN_SESAS_SINIESTROS_AT_IDSINIESTO_IDX ON SICAS_OC.SESAS_SINIESTROS_ATECNICA(IDSINIESTRO) TABLESPACE IDX_SICASOC ;
 --CREATE  INDEX SICAS_OC.SIN_SESAS_SINIESTROS_AT_NPOLIZA_IDX ON SICAS_OC.SESAS_SINIESTROS_ATECNICA(NPOLIZA) TABLESPACE IDX_SICASOC ;

 --CREAR PK PARA CAMPOS 

  ALTER TABLE SICAS_OC.SESAS_SINIESTROS_ATECNICA ADD CONSTRAINT PK_SESAS_SINIESTROS_AT PRIMARY KEY (CODCIA,CODEMPRESA,ID_SESAS_SINIESTRO) USING INDEX SIN_SESAS_SINIESTROS_AT_IDX;
  
  --##GRANTs


GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.SESAS_SINIESTROS_ATECNICA TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.SESAS_SINIESTROS_ATECNICA TO ROL_CONSULTA_SICAS;

--SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM SESAS_SINIESTROS_ATECNICA FOR SICAS_OC.SESAS_SINIESTROS_ATECNICA;


 --PERMISOS SECUENCIA SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ
  GRANT SELECT ON SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ  TO PUBLIC ;
  /
  CREATE OR REPLACE PUBLIC SYNONYM SESAS_SINIESTROS_ATECNICA_SEQ FOR SICAS_OC.SESAS_SINIESTROS_ATECNICA_SEQ;
  /

---COMENTARIO TABLA 

COMMENT ON TABLE SICAS_OC.SESAS_SINIESTROS_ATECNICA IS 'Informacion de tabla siniestros_1222 del área técnica';

--##COMENTARIOS DESCRIPTIVOS
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.IDSINIESTRO             IS 'NUMERO DE SINIESTRO DE LA TABLA SINIESTROS AREA TECNICA';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.NPOLIZA 		        IS 'NUMERO DE POLIZA';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.IDPOLIZA                    IS 'POLIZA ID';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.FEC_EST 			    IS 'FECHA DE REPORTE DE SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.FEC_OCU 			IS 'FECHA DE OCURRENCIA DE SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.MONTO 			    IS 'MONTO DE SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.ND_5401_05 			IS 'MONTO QUE SE SUMA CON EL MONTO DE SINIESTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.CREATION_BY 			    IS 'NUM USUARIO QUE CREO REGISTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.CREATION_DATE             IS 'FECHA CREACION DE REGISTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.LAST_UPDATE_BY               IS 'USUARIO QUE MODIFICO REGISTRO';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS_ATECNICA.LAST_UPDATE_DATE              IS 'FECHA DE ULTIMA MODIFICACION';