
  CREATE TABLE "SICAS_OC"."CT_DET_COT_AUTO" 
   (	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDCOTIZACION" NUMBER(5,0) NOT NULL ENABLE, 
	"DET_COT_AUTO" NUMBER(2,0), 
	"CODCOBERTURA" VARCHAR2(6) NOT NULL ENABLE, 
	"TIPCOBERT" VARCHAR2(3) NOT NULL ENABLE, 
	"SUMAASEGLOCL" NUMBER(14,2), 
	"SUMAASEGMON" NUMBER(14,2), 
	"PRIMALOCAL" NUMBER(14,2), 
	"PRIMAMONEDA" NUMBER(14,2), 
	"ESTADO" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("CODEMPRESA", "CODCIA", "IDCOTIZACION", "DET_COT_AUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CHECK ("DET_COT_AUTO" IS NOT NULL) ENABLE, 
	 FOREIGN KEY ("IDCOTIZACION", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."CT_COTIZACION_AUTO" ("IDCOTIZACION", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
