
  CREATE TABLE "SICAS_OC"."CTES_CERTIF_INDIV" 
   (	"IDCERTCTE" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"STSCERTCTE" VARCHAR2(10), 
	"FECREGISTRO" DATE, 
	"USERREGISTRO" VARCHAR2(30), 
	"FECULTACTUALIZA" DATE, 
	"USERULTACTUALIZA" VARCHAR2(30), 
	 CONSTRAINT "PK_CTE_CERTIF_IND" PRIMARY KEY ("IDCERTCTE", "CODCIA", "CODEMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
