
  CREATE TABLE "SICAS_OC"."CTROL_PROCESOS" 
   (	"ID_TP_SOLICITUD" NUMBER(5,0), 
	"ID_CONSECUTIVO" NUMBER(14,0), 
	"ID_APLICATIVO" VARCHAR2(6), 
	"ID_AREA" VARCHAR2(6), 
	"CODUSUARIO" VARCHAR2(15), 
	"DESC_SOLICITUD" VARCHAR2(4000), 
	"ID_POLIZA" VARCHAR2(100), 
	"ID_SINIESTRO" VARCHAR2(100), 
	"ID_RECIBO_O_NCRED" VARCHAR2(100), 
	"ID_ASEG_O_ENDOSOS" VARCHAR2(100), 
	"ID_COMPLEJIDAD" VARCHAR2(6), 
	"ID_ESTATUS" VARCHAR2(6), 
	"FE_RECIBIDO" DATE, 
	"FE_ASIGNADO" DATE, 
	"FE_ATENDIDO" DATE, 
	"FE_ENTREGADO" DATE, 
	"FE_TERMINADO" DATE, 
	"ID_CAUSA_INCIDENCIA" VARCHAR2(6), 
	"CODUSUARIO_ATIENDE" VARCHAR2(15), 
	"OBSERVACIONES" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
