
  CREATE TABLE "SICAS_OC"."DATOS_PARTICULARES_PERSONAS" 
   (	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"ESTATURA" NUMBER(3,0), 
	"PESO" NUMBER(6,3), 
	"CAVIDAD_TORAXICA_MIN" NUMBER(6,3), 
	"CAVIDAD_TORAXICA_MAX" NUMBER(6,3), 
	"CAPACIDAD_ABDOMINAL" NUMBER(6,3), 
	"PRESION_ARTERIAL_MIN" NUMBER(6,3), 
	"PRESION_ARTERIAL_MAX" NUMBER(6,3), 
	"PULSO" NUMBER(3,0), 
	"MORTALIDAD" NUMBER(6,3), 
	"SUMA_ASEG_MONEDA" NUMBER(18,2), 
	"SUMA_ASEG_LOCAL" NUMBER(18,2), 
	"EXTRA_PRIMA_MONEDA" NUMBER(18,2), 
	"EXTRA_PRIMA_LOCAL" NUMBER(18,2), 
	"ID_FUMADOR" VARCHAR2(1) NOT NULL ENABLE, 
	"OBSERVACIONES" VARCHAR2(3000), 
	"PORC_SUBNORMAL" NUMBER(18,6), 
	"PRIMA_LOCAL" NUMBER(18,2), 
	"PRIMA_MONEDA" NUMBER(18,2), 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0), 
	 CONSTRAINT "FK_PERSONAS_DETALLE" FOREIGN KEY ("IDPOLIZA", "IDETPOL", "CODCIA")
	  REFERENCES "SICAS_OC"."DETALLE_POLIZA" ("IDPOLIZA", "IDETPOL", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
