
  CREATE TABLE "SICAS_OC"."DATOS_SINIESTRO_NEGOCIO" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"CODAGRUPADOR" VARCHAR2(6), 
	"CODPLANTEL" VARCHAR2(6), 
	"ST_SINIESTRO_DOCTO" VARCHAR2(6), 
	"ID_MOTIVO_RECHAZO" VARCHAR2(6), 
	"MONTO_RECHAZO_NOCUM" NUMBER(18,2), 
	"FECHA_REGISTRO" DATE, 
	"USUARIO_REGISTRO" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
