
  CREATE TABLE "SICAS_OC"."DATOS_PARTICULARES_BIENES" 
   (	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_BIEN" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPAIS" VARCHAR2(3) NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) NOT NULL ENABLE, 
	"UBICACION_BIEN" VARCHAR2(250), 
	"TIPO_BIEN" VARCHAR2(6), 
	"SUMA_ASEG_LOCAL_BIEN" NUMBER(18,2), 
	"SUMA_ASEG_MONEDA_BIEN" NUMBER(18,2), 
	"PRIMA_NETA_LOCAL_BIEN" NUMBER(18,2), 
	"PRIMA_NETA_MONEDA_BIEN" NUMBER(18,2), 
	"INICIO_VIGENCIA" DATE, 
	"FIN_VIGENCIA" DATE, 
	"CODIGO_POSTAL" VARCHAR2(30), 
	"CODASENTAMIENTO" NUMBER(5,0), 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("IDPOLIZA", "IDETPOL", "NUM_BIEN", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_BIENES_DETALLE" FOREIGN KEY ("IDPOLIZA", "IDETPOL", "CODCIA")
	  REFERENCES "SICAS_OC"."DETALLE_POLIZA" ("IDPOLIZA", "IDETPOL", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
