
  CREATE TABLE "SICAS_OC"."DATOS_ADICIONALES_PNJ" 
   (	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"CARGO_FEDERAL_ULTIMOS_ANIOS" VARCHAR2(1 CHAR), 
	"CARGO_FEDERAL_DESEMPENADO" VARCHAR2(100 CHAR), 
	"ORIGEN_REC_SALARIO" VARCHAR2(1 CHAR), 
	"ORIGEN_REC_COMISIONES" VARCHAR2(1 CHAR), 
	"ORIGEN_REC_NEG_PROPIO" VARCHAR2(1 CHAR), 
	"ORIGEN_REC_HONORARIOS" VARCHAR2(1 CHAR), 
	"ORIGEN_REC_REGALIAS" VARCHAR2(1 CHAR), 
	"ORIGEN_REC_OTROS" VARCHAR2(1 CHAR), 
	"OTRO_ORIGEN_SALARIO" VARCHAR2(100 CHAR), 
	"MONEDA_INGRESO" VARCHAR2(6 CHAR), 
	"INGRESO_MENSUAL" NUMBER(14,2), 
	"PAIS_NACIMIENTO" VARCHAR2(3 CHAR), 
	"ENTIDAD_FEDERATIVA" VARCHAR2(6), 
	"FOLIO_MERCANTIL" VARCHAR2(15 CHAR), 
	"OCUPACION" VARCHAR2(6 CHAR), 
	"FIRMA_ELECTRONICA" VARCHAR2(100 CHAR), 
	"ADMINISTRACION_SOCIEDAD" VARCHAR2(1 CHAR), 
	"SOCIOS" VARCHAR2(4000), 
	 CONSTRAINT "PK_DATOS_ADICIONALES_PNJ" PRIMARY KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_DATOS_ADICIONALES_PNJ" FOREIGN KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE, 
	 CONSTRAINT "RF_DATOS_ADICIONALES_PNJ_01" FOREIGN KEY ("MONEDA_INGRESO")
	  REFERENCES "SICAS_OC"."MONEDA" ("COD_MONEDA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
