
  CREATE TABLE "SICAS_OC"."DATOS_PARTICULARES_VEHICULO" 
   (	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_VEHI" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_MARCA" VARCHAR2(10) NOT NULL ENABLE, 
	"COD_VERSION" VARCHAR2(10) NOT NULL ENABLE, 
	"COD_MODELO" VARCHAR2(10) NOT NULL ENABLE, 
	"ANIO_VEHICULO" NUMBER(4,0) NOT NULL ENABLE, 
	"PLACA" VARCHAR2(25) NOT NULL ENABLE, 
	"CANTIDAD_PASAJEROS" NUMBER(3,0), 
	"TARJETA_CIRCULACION" VARCHAR2(50), 
	"COLOR" VARCHAR2(100), 
	"NUMERO_CHASIS" VARCHAR2(50), 
	"NUMERO_MOTOR" VARCHAR2(50), 
	"SUMAASEG_LOCAL" NUMBER(18,2) NOT NULL ENABLE, 
	"SUMAASEG_MONEDA" NUMBER(14,2) NOT NULL ENABLE, 
	"PRIMANETA_LOCAL" NUMBER(18,2) NOT NULL ENABLE, 
	"PRIMANETA_MONEDA" NUMBER(14,2) NOT NULL ENABLE, 
	 PRIMARY KEY ("IDETPOL", "NUM_VEHI", "IDPOLIZA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
