--
-- PAQUETE_COMERCIAL  (Table) 
--


CREATE TABLE SICAS_OC.PAQUETE_COMERCIAL
(
  CODCIA       NUMBER(14),
  CODEMPRESA   NUMBER(14),
  IDTIPOSEG    VARCHAR2(6 CHAR),
  PLANCOB      VARCHAR2(15 CHAR),
  CODPAQUETE   NUMBER(14)                       DEFAULT 0,
  DESCPAQUETE  VARCHAR2(250 CHAR),
  CODUSUARIO   VARCHAR2(30 CHAR)                DEFAULT USER,
  FECHAMODIF   DATE                             DEFAULT SYSDATE,
  DOCUMENTO    BLOB                             DEFAULT EMPTY_BLOB()
)
LOB (DOCUMENTO) STORE AS (
  TABLESPACE  TS_SICASOC
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
/

COMMENT ON TABLE SICAS_OC.PAQUETE_COMERCIAL IS 'Catálogo de los paquetes comerciales de la compañia'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.CODCIA IS 'Código de la compañia'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.CODEMPRESA IS 'Código de la empresa'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.IDTIPOSEG IS 'Identifica el tipo de seguro'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.PLANCOB IS 'El plan de cobertura'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.CODPAQUETE IS 'Código del paquete comercial'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.DESCPAQUETE IS 'Descripción del paquete comercial'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.CODUSUARIO IS 'Usuario que modifica el registro'
/

COMMENT ON COLUMN SICAS_OC.PAQUETE_COMERCIAL.FECHAMODIF IS 'Fecha en que se modifica el registro'
/



--
-- IDX_PAQUETE_COMERCIAL_IDPAQUE  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.IDX_PAQUETE_COMERCIAL_IDPAQUE ON SICAS_OC.PAQUETE_COMERCIAL
(CODPAQUETE)
/


--
-- PAQUETE_COMERCIAL_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.PAQUETE_COMERCIAL_PK ON SICAS_OC.PAQUETE_COMERCIAL
(CODCIA, CODEMPRESA, DESCPAQUETE)
/


--
-- PAQUETE_COMERCIAL  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM PAQUETE_COMERCIAL FOR SICAS_OC.PAQUETE_COMERCIAL
/


-- 
-- Non Foreign Key Constraints for Table PAQUETE_COMERCIAL 
-- 
ALTER TABLE SICAS_OC.PAQUETE_COMERCIAL ADD (
  CONSTRAINT PAQUETE_COMERCIAL_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, DESCPAQUETE)
  USING INDEX SICAS_OC.PAQUETE_COMERCIAL_PK
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table PAQUETE_COMERCIAL 
-- 
ALTER TABLE SICAS_OC.PAQUETE_COMERCIAL ADD (
  CONSTRAINT PAQUETE_COMERCIAL_R01 
  FOREIGN KEY (IDTIPOSEG, CODEMPRESA, CODCIA, PLANCOB) 
  REFERENCES SICAS_OC.PLAN_COBERTURAS (IDTIPOSEG,CODEMPRESA,CODCIA,PLANCOB)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON SICAS_OC.PAQUETE_COMERCIAL TO PUBLIC
/
