CREATE TABLE SICAS_OC.OFICINAS
(
  CODOFICINA     VARCHAR2(8 CHAR),
  DESCOFICINA    VARCHAR2(500 CHAR)             NOT NULL,
  DIRECCION      VARCHAR2(1000 CHAR),
  TELEFONO       VARCHAR2(30 CHAR),
  STSOFICINA     VARCHAR2(10 CHAR)              DEFAULT 'ACTIVO',
  CODUSUARIO     VARCHAR2(30 CHAR)              DEFAULT USER,
  FECALTA        DATE                           DEFAULT SYSDATE,
  CODUSUARIOMOD  VARCHAR2(30 CHAR)              DEFAULT USER,
  FECMODIF       DATE                           DEFAULT SYSDATE
)
RESULT_CACHE (MODE DEFAULT)
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING
/

COMMENT ON TABLE SICAS_OC.OFICINAS IS 'Catálogo de oficinas'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.CODOFICINA IS 'Código de la oficina'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.DESCOFICINA IS 'Nombre de la oficina'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.DIRECCION IS 'Dirección de la ubicación de la oficina'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.TELEFONO IS 'Numero teléfonico'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.CODUSUARIO IS 'Usuario que da de alta el registro'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.FECALTA IS 'Fecha de alta del registro'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.CODUSUARIOMOD IS 'Usuario que modifica el registro'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.FECMODIF IS 'Fecha de la modificación del registro'
/

COMMENT ON COLUMN SICAS_OC.OFICINAS.STSOFICINA IS 'Estatus de la oficina (Suspendido, Activo)'
/
ALTER TABLE SICAS_OC.OFICINAS ADD (
  CONSTRAINT OFICINAS_PK
  PRIMARY KEY
  (CODOFICINA)
  ENABLE VALIDATE)
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SICAS_OC.OFICINAS TO "PUBLIC";
/
CREATE OR REPLACE PUBLIC SYNONYM OFICINAS FOR SICAS_OC.OFICINAS;
/
