ALTER TABLE SICAS_OC.DETALLE_DOMICI_REFERE ADD (FECHATASACAMBIO DATE);
/
ALTER TABLE SICAS_OC.DETALLE_DOMICI_REFERE ADD (CAMBIO_MONEDA_ENVIO NUMBER(18,2));
/
COMMENT ON COLUMN SICAS_OC.DETALLE_DOMICI_REFERE.FECHATASACAMBIO IS 'Cambio moneda enviada al banco';
/
COMMENT ON COLUMN SICAS_OC.DETALLE_DOMICI_REFERE.FECHATASACAMBIO IS 'Fecha de la Tasa de cambio para envío de cobranza al banco en moneda local';
/
