
  CREATE TABLE "SICAS_OC"."DEP_TRANSAC" 
   (	"ID_PROCESO" NUMBER(5,0), 
	"SUB_PROCESO" NUMBER(5,0), 
	"IDTRANSACCION" NUMBER(18,0), 
	"FECHATRANSACCION" DATE, 
	"USUARIOGENERO" VARCHAR2(30), 
	"ORIGEN_TRANSACC" NUMBER(3,0), 
	"CORRELATIVO" NUMBER(10,0), 
	"CODSUBPROCESO" VARCHAR2(6), 
	"OBJETO" VARCHAR2(35), 
	"IDSINIESTRO" VARCHAR2(20), 
	"IDPOLIZA" VARCHAR2(20), 
	"CODCOBERT" VARCHAR2(20), 
	"NUMMOD" VARCHAR2(20), 
	"MTOLOCAL" NUMBER(18,6), 
	"MTOEXTRANERO" NUMBER(18,6), 
	"MTOLOCAL_C" NUMBER(18,6), 
	"MTOEXTRANERO_C" NUMBER(18,6), 
	"ST_APROBACION" VARCHAR2(5), 
	"ID_ACCION" NUMBER(3,0), 
	"OBSERVACIONES" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
