
  CREATE TABLE "SICAS_OC"."DEP_COBER" 
   (	"ID_PROCESO" NUMBER(5,0), 
	"SUB_PROCESO" NUMBER(5,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDDETSIN" NUMBER(14,0), 
	"CODCOBERT" VARCHAR2(6), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"MONTO_PAGADO_MONEDA" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL" NUMBER(18,2), 
	"MONTO_PAGADO_MONEDA_C" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL_C" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA_C" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL_C" NUMBER(18,2), 
	"STSCOBERTURA" VARCHAR2(3), 
	"NUMMOD" NUMBER(2,0), 
	"CODTRANSAC" VARCHAR2(6), 
	"CODCPTOTRANSAC" VARCHAR2(6), 
	"IDTRANSACCION" NUMBER(18,0), 
	"SALDO_RESERVA" NUMBER(18,2), 
	"FECRES" DATE, 
	"SALDO_RESERVA_LOCAL" NUMBER(18,2), 
	"IDTRANSACCIONANUL" VARCHAR2(18), 
	"ST_COBERTURA" VARCHAR2(5), 
	"ID_ACCION" NUMBER(3,0), 
	"OBSERVACIONES" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
