
  CREATE TABLE "SICAS_OC"."DEP_APROB" 
   (	"ID_PROCESO" NUMBER(5,0), 
	"SUB_PROCESO" NUMBER(5,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDDETSIN" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"NUM_APROBACION" NUMBER(14,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(14,2), 
	"MONTO_LOCAL_A" NUMBER(18,2), 
	"MONTO_MONEDA_A" NUMBER(14,2), 
	"STSAPROBACION" VARCHAR2(3), 
	"TIPO_DE_APROBACION" VARCHAR2(1), 
	"IDTRANSACCION" NUMBER(18,0), 
	"BENEF" NUMBER(5,0), 
	"IDTRANSACCIONANUL" VARCHAR2(18), 
	"IDSINIESTRO_DA" NUMBER(14,0), 
	"NUM_APROBACION_DA" NUMBER(14,0), 
	"IDDETAPROB_DA" NUMBER(14,0), 
	"COD_PAGO_DA" VARCHAR2(6), 
	"MONTO_LOCAL_DA" NUMBER(18,2), 
	"MONTO_MONEDA_DA" NUMBER(18,2), 
	"MONTO_LOCAL_DA_C" NUMBER(18,2), 
	"MONTO_MONEDA_DA_C" NUMBER(18,2), 
	"CODTRANSAC_DA" VARCHAR2(6), 
	"CODCPTOTRANSAC_DA" VARCHAR2(6), 
	"ST_APROBACION" VARCHAR2(5), 
	"ID_ACCION" NUMBER(3,0), 
	"OBSERVACIONES" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
