
  CREATE TABLE "SICAS_OC"."DEP_SINIE" 
   (	"ID_PROCESO" NUMBER(5,0), 
	"SUB_PROCESO" NUMBER(5,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"ID_COL_INDI" VARCHAR2(1), 
	"ID_COL_INDI_POL" VARCHAR2(1), 
	"FEC_OCURRENCIA" DATE, 
	"FEC_NOTIFICACION" DATE, 
	"STS_SINIESTRO" VARCHAR2(3), 
	"FECSTS" DATE, 
	"FECANUL" DATE, 
	"MONTO_RESERVA_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVA_MONEDA" NUMBER(18,2), 
	"MONTO_PAGO_LOCAL" NUMBER(18,2), 
	"MONTO_PAGO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVA_LOCAL_C" NUMBER(18,2), 
	"MONTO_RESERVA_MONEDA_C" NUMBER(18,2), 
	"MONTO_PAGO_LOCAL_C" NUMBER(18,2), 
	"MONTO_PAGO_MONEDA_C" NUMBER(18,2), 
	"IDDETSIN" NUMBER(14,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"MONTO_PAGADO_MONEDA" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL" NUMBER(18,2), 
	"MONTO_PAGADO_MONEDA_C" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL_C" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA_C" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL_C" NUMBER(18,2), 
	"ST_SINIESTRO" VARCHAR2(5), 
	"ID_ACCION" NUMBER(3,0), 
	"OBSERVACIONES" VARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
