
  CREATE TABLE "SICAS_OC"."DERIVACION_AUTO_CONFIG" 
   (	"CODCIA" NUMBER NOT NULL ENABLE, 
	"IDCONFDER" NUMBER NOT NULL ENABLE, 
	"TIPOCOMPROB" VARCHAR2(6) NOT NULL ENABLE, 
	"INDDERIVAAUTO" VARCHAR2(1), 
	"CODTIPODERIVACION" VARCHAR2(6), 
	"EMAILNOTIFICADEST" VARCHAR2(1000), 
	"EMAILNOTIFICACC" VARCHAR2(1000), 
	"STSCONFIG" VARCHAR2(10), 
	"CODUSUARIO" VARCHAR2(30), 
	"FECHACONFIG" DATE, 
	 CONSTRAINT "DERIVACION_AUTO_CONFIG_PK" PRIMARY KEY ("CODCIA", "IDCONFDER", "TIPOCOMPROB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
