
  CREATE TABLE "SICAS_OC"."DESCUENTOS" 
   (	"CODDESC" VARCHAR2(6) NOT NULL ENABLE, 
	"PORC_DESC" NUMBER(18,6), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"INI_VIGENCIA" DATE, 
	"FIN_VIGENCIA" DATE, 
	"OBSERVACIONES" LONG, 
	"ESTADO" VARCHAR2(6), 
	"FECHA_ESTADO" DATE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0), 
	 PRIMARY KEY ("CODDESC", "IDPOLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
