
  CREATE TABLE "SICAS_OC"."DET_DOMICI_REC" 
   (	"INDICADOR_DETALLE" VARCHAR2(1), 
	"TIPO_TRANSACCION" VARCHAR2(1), 
	"NUMEROCUENTA" NUMBER(18,0), 
	"IMPORTE" NUMBER(18,2), 
	"MONEDA" NUMBER(3,0), 
	"NUMREFCONTRATO" VARCHAR2(19), 
	"CODRESULTADO" VARCHAR2(2), 
	"TIPAUTORIZACION" NUMBER(1,0), 
	"NUMAUTORIZACION" VARCHAR2(6), 
	"FILLER" VARCHAR2(3), 
	"FERCHARECEPCION" DATE, 
	"PROCESADOPOR" VARCHAR2(30), 
	"CONCILIADO" VARCHAR2(1), 
	"RESPDOMICILIACION" VARCHAR2(100), 
	"DESCRESPDOMICILIACION" VARCHAR2(1000), 
	"TIPO_CONFIGURACION" VARCHAR2(6), 
	"IDPROCESO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
