
  CREATE TABLE "SICAS_OC"."DETALLE_SINIESTRO" 
   (	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"MONTO_PAGADO_MONEDA" NUMBER(18,2), 
	"MONTO_PAGADO_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL" NUMBER(18,2), 
	"IDTIPOSEG" VARCHAR2(6), 
	"CODCIA" NUMBER(14,0) DEFAULT 1, 
	"CODEMPRESA" NUMBER(14,0) DEFAULT 1, 
	"COD_MONEDA" VARCHAR2(5) DEFAULT 'PS', 
	"COD_ASEGURADO" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
