
  CREATE TABLE "SICAS_OC"."DETALLE_PAPELERIA" 
   (	"CODIGO" NUMBER(5,0) NOT NULL ENABLE, 
	"CORRELATIVO" NUMBER(5,0) NOT NULL ENABLE, 
	"PARENTRADA" VARCHAR2(50), 
	"NOMPARAMETRO" VARCHAR2(50), 
	"TIPOPARAMETRO" VARCHAR2(1), 
	 PRIMARY KEY ("CODIGO", "CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODIGO")
	  REFERENCES "SICAS_OC"."PAPELERIA" ("CODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
