
  CREATE TABLE "SICAS_OC"."DETALLE_NOTAS_DE_CREDITO" 
   (	"IDNCR" NUMBER(14,0) CONSTRAINT "SYS_C0033745" NOT NULL ENABLE, 
	"CODCPTO" VARCHAR2(6) CONSTRAINT "SYS_C0033746" NOT NULL ENABLE, 
	"MONTO_DET_LOCAL" NUMBER(18,2) CONSTRAINT "SYS_C0033747" NOT NULL ENABLE, 
	"MONTO_DET_MONEDA" NUMBER(18,2), 
	"INDCPTOPRIMA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MTOORIGDETLOCAL" NUMBER(18,2) DEFAULT 0, 
	"MTOORIGDETMONEDA" NUMBER(18,2) DEFAULT 0, 
	"MTOIMPTOFACTELECT" NUMBER(18,2) DEFAULT 0, 
	 PRIMARY KEY ("IDNCR", "CODCPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
