
  CREATE TABLE "SICAS_OC"."DETALLE_COTIZACION" 
   (	"NUM_COTIZACION" NUMBER(14,0) NOT NULL ENABLE, 
	"LINEA_COTIZACION" NUMBER(5,0) CONSTRAINT "SYS_C007056" NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6) NOT NULL ENABLE, 
	"SUMA_ASEGURADA_LOCAL" NUMBER(18,2), 
	"SUMA_ASEGURADA_MONEDA" NUMBER(18,2), 
	"PRIMA_NETA_LOCAL" NUMBER(18,2), 
	"PRIMA_NETA_MONEDA" NUMBER(18,2), 
	"OBSERVACIONES" LONG, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"TASA" NUMBER(28,6), 
	"INDTARIFA" VARCHAR2(1), 
	"TIPOTASA" VARCHAR2(1), 
	 PRIMARY KEY ("NUM_COTIZACION", "LINEA_COTIZACION", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("NUM_COTIZACION", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."COTIZACION" ("NUM_COTIZACION", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
