
  CREATE TABLE "SICAS_OC"."DETALLE_PRIMAS_DEPOSITO" 
   (	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"IDRECIBO" NUMBER(18,0) NOT NULL ENABLE, 
	"IDPRIMADEPOSITO" NUMBER(14,0) NOT NULL ENABLE, 
	"CORRELATIVO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"TIP_MOV" VARCHAR2(6), 
	"MONTO_APLICADO_MONEDA" NUMBER(18,2), 
	"ESTADO" VARCHAR2(6), 
	 CONSTRAINT "PK_DETALLE_PRIMAS_DEPOSITO" PRIMARY KEY ("IDPRIMADEPOSITO", "CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_PRIMDEP_DETPRIMDEP" FOREIGN KEY ("IDPRIMADEPOSITO")
	  REFERENCES "SICAS_OC"."PRIMAS_DEPOSITO" ("IDPRIMADEPOSITO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
