
  CREATE TABLE "SICAS_OC"."DETALLE_APROBACION_ASEG" 
   (	"NUM_APROBACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETAPROB" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_PAGO" VARCHAR2(6) NOT NULL ENABLE, 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"IDSINIESTRO" NUMBER(14,0), 
	"CODTRANSAC" VARCHAR2(6), 
	"CODCPTOTRANSAC" VARCHAR2(6), 
	"CODCIA" NUMBER(14,0) DEFAULT 1, 
	"CODEMPRESA" NUMBER(14,0) DEFAULT 1, 
	"COD_MONEDA" VARCHAR2(5) DEFAULT 'PS'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
