
  CREATE TABLE "SICAS_OC"."DETALLE_FACTURAS_PAG" 
   (	"MONTO_DET_LOCAL" NUMBER(18,2) NOT NULL ENABLE, 
	"MONTO_DET_MONEDA" NUMBER(18,2), 
	"IDRECIBO" NUMBER(18,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCPTO" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
