
  CREATE TABLE "SICAS_OC"."DETALLE_FACT_ELECT_CONF_DOCTO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDIDENTIFICADOR" NUMBER NOT NULL ENABLE, 
	"CODIDENTIFICADOR" VARCHAR2(10) NOT NULL ENABLE, 
	"CODATRIBUTO" VARCHAR2(30) NOT NULL ENABLE, 
	"ORDENATRIB" NUMBER NOT NULL ENABLE, 
	"CONDICIONATRIBUTO" VARCHAR2(1) NOT NULL ENABLE, 
	"TIPOVALORATRIBUTO" VARCHAR2(1) NOT NULL ENABLE, 
	"VALORATRIBUTO" VARCHAR2(3000), 
	"CONSULTA" CLOB DEFAULT EMPTY_CLOB(), 
	"INDENVIACIA" VARCHAR2(1), 
	"CODRUTINACALC" VARCHAR2(20), 
	 CONSTRAINT "P_IDENT_ATRIB" PRIMARY KEY ("IDIDENTIFICADOR", "CODIDENTIFICADOR", "CODATRIBUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("IDIDENTIFICADOR")
	  REFERENCES "SICAS_OC"."FACT_ELECT_CONF_DOCTO" ("IDIDENTIFICADOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("CONSULTA") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
