
  CREATE TABLE "SICAS_OC"."DETALLES_PAGOS" 
   (	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_PAGO" NUMBER(18,0) NOT NULL ENABLE, 
	"NUM_FACTURA" VARCHAR2(30), 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,8), 
	"REFERENCIA_FACTURA" VARCHAR2(100), 
	"CAMPO1" VARCHAR2(30), 
	"CAMPO2" VARCHAR2(30), 
	"CAMPO3" VARCHAR2(30), 
	 PRIMARY KEY ("IDFACTURA", "NUM_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("NUM_PAGO")
	  REFERENCES "SICAS_OC"."PAGOS_FACTURA" ("NUM_PAGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
