
  CREATE TABLE "SICAS_OC"."DETALLE_NOMINA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDNOMINA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"MONTONETOLOCAL" NUMBER(14,2), 
	"MONTONETOMONEDA" NUMBER(14,2), 
	"CODMONEDA" VARCHAR2(3), 
	"IDCOMISION" NUMBER(14,0), 
	"IDBONO" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
