
  CREATE TABLE "SICAS_OC"."DIRECCION_REGIONAL" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODDIRECREGIONAL" NUMBER(10,0) NOT NULL ENABLE, 
	"FECINGRESO" DATE, 
	"TIPODOCIDENTDIREC" VARCHAR2(6), 
	"NUMDOCIDENTDIREC" VARCHAR2(20), 
	"STSDIRECREGIONAL" VARCHAR2(10), 
	"FECSTS" DATE, 
	 CONSTRAINT "PK_DIRECCION_REGIONAL" PRIMARY KEY ("CODCIA", "CODDIRECREGIONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPODOCIDENTDIREC", "NUMDOCIDENTDIREC")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
