
  CREATE TABLE "SICAS_OC"."DIRECCION_REGIONAL_USR" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODDIRECREGIONAL" NUMBER(10,0) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"FECINGRESO" DATE, 
	"STSUSUARIO" VARCHAR2(10), 
	"FECSTS" DATE, 
	 CONSTRAINT "PK_DIRECCION_REGIONAL_USR" PRIMARY KEY ("CODCIA", "CODDIRECREGIONAL", "CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_DIREC_REGIONAL_USR" FOREIGN KEY ("CODCIA", "CODDIRECREGIONAL")
	  REFERENCES "SICAS_OC"."DIRECCION_REGIONAL" ("CODCIA", "CODDIRECREGIONAL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
