
  CREATE TABLE "SICAS_OC"."DIRECCIONES_PNJ" 
   (	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6) NOT NULL ENABLE, 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPO_DIRECCION" VARCHAR2(6) NOT NULL ENABLE, 
	"CORRELATIVO_DIRECCION" NUMBER(5,0) NOT NULL ENABLE, 
	"DIRECCION" VARCHAR2(250), 
	"CODPAIS" VARCHAR2(3) NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) NOT NULL ENABLE, 
	"CODMUNICIPIO" VARCHAR2(3) NOT NULL ENABLE, 
	"CODIGO_POSTAL" VARCHAR2(30) NOT NULL ENABLE, 
	"CODASENTAMIENTO" VARCHAR2(6) NOT NULL ENABLE, 
	"CODIGO_ZIP" VARCHAR2(10), 
	"DIRECCION_PRINCIPAL" VARCHAR2(1) NOT NULL ENABLE, 
	"NUMINTERIOR" VARCHAR2(20), 
	"NUMEXTERIOR" VARCHAR2(20), 
	 PRIMARY KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "CORRELATIVO_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CHECK ("DIRECCION" IS NOT NULL) ENABLE, 
	 FOREIGN KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
