
  CREATE TABLE "SICAS_OC"."DIRECCIONES_CLIENTE" 
   (	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"CORRELATIVO_DIRECCION" NUMBER(5,0) NOT NULL ENABLE, 
	"TIPO_DIRECCION" VARCHAR2(6), 
	"DIRECCION" VARCHAR2(150), 
	"CODPAIS" VARCHAR2(3), 
	"CODESTADO" VARCHAR2(3), 
	"CODCIUDAD" VARCHAR2(3), 
	"CODMUNICIPIO" VARCHAR2(3), 
	"CODIGOZIP" VARCHAR2(10), 
	"CODIGO_POSTAL" VARCHAR2(30), 
	"CODASENTAMIENTO" NUMBER(5,0), 
	 PRIMARY KEY ("CODCLIENTE", "CORRELATIVO_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODIGO_POSTAL", "CODASENTAMIENTO")
	  REFERENCES "SICAS_OC"."DETALLE_APARTADO" ("CODIGO_POSTAL", "CORRELATIVO") ENABLE, 
	 FOREIGN KEY ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO")
	  REFERENCES "SICAS_OC"."CORREGIMIENTO" ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO") ENABLE, 
	 FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "SICAS_OC"."CLIENTES" ("CODCLIENTE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
