
  CREATE TABLE "SICAS_OC"."DISTRITO" 
   (	"CODPAIS" VARCHAR2(3) CONSTRAINT "SYS_C007090" NOT NULL ENABLE, 
	"CODESTADO" VARCHAR2(3) CONSTRAINT "SYS_C007091" NOT NULL ENABLE, 
	"CODCIUDAD" VARCHAR2(3) CONSTRAINT "SYS_C007092" NOT NULL ENABLE, 
	"DESCCIUDAD" VARCHAR2(50) CONSTRAINT "SYS_C007093" NOT NULL ENABLE, 
	"CODDISTRITOALTERNO" VARCHAR2(3), 
	"CODZONAGEO" VARCHAR2(6), 
	"CVE_CNSF" VARCHAR2(15), 
	"DESC_CNSF" VARCHAR2(300), 
	 PRIMARY KEY ("CODPAIS", "CODESTADO", "CODCIUDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODPAIS", "CODESTADO")
	  REFERENCES "SICAS_OC"."PROVINCIA" ("CODPAIS", "CODESTADO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
