--
-- DISTRIBUCION_MASIVA_LOG  (Table) 
--
CREATE TABLE SICAS_OC.DISTRIBUCION_MASIVA_LOG
(
  CODCIA          NUMBER(14)                    NOT NULL,
  CODEMPRESA      NUMBER(14)                    NOT NULL,
  IDPOLIZA        NUMBER(14)                    NOT NULL,
  IDTRANSACCION   NUMBER(18)                    NOT NULL,
  NUMSECUENCIA    NUMBER                        NOT NULL,
  CODIGOLOG       VARCHAR2(20 BYTE),
  TEXTOLOG        CLOB,
  FECHALOG        DATE,
  CODUSUARIOPROC  VARCHAR2(30 BYTE)
)
LOB (TEXTOLOG) STORE AS (
  TABLESPACE  TS_SICASOC
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.DISTRIBUCION_MASIVA_LOG IS 'Información resultante de la distribución de transacciones por póliza para el Reaseguro'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.CODCIA IS 'Código de la Compañía'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.IDPOLIZA IS 'Identificador de la Póliza'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.IDTRANSACCION IS 'Identificador de la Transacción'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.NUMSECUENCIA IS 'Número Consecutivo'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.CODIGOLOG IS 'Código del Resultado'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.TEXTOLOG IS 'Texto del Resultado'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.FECHALOG IS 'Fecha del Resultado'
/

COMMENT ON COLUMN SICAS_OC.DISTRIBUCION_MASIVA_LOG.CODUSUARIOPROC IS 'Código del Usuario que Procesó'
/



--
-- DISTRIBUCION_MASIVA_LOG_PK  (Index) 
--
--  Dependencies: 
--   DISTRIBUCION_MASIVA_LOG (Table)
--
CREATE UNIQUE INDEX SICAS_OC.DISTRIBUCION_MASIVA_LOG_PK ON SICAS_OC.DISTRIBUCION_MASIVA_LOG
(CODCIA, CODEMPRESA, IDPOLIZA, IDTRANSACCION, NUMSECUENCIA)
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- DISTRIBUCION_MASIVA_LOG_TRG  (Trigger) 
--
--  Dependencies: 
--   DISTRIBUCION_MASIVA_LOG (Table)
--
CREATE OR REPLACE TRIGGER SICAS_OC.DISTRIBUCION_MASIVA_LOG_TRG
BEFORE INSERT
ON SICAS_OC.DISTRIBUCION_MASIVA_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column NUMSECUENCIA
  :new.NUMSECUENCIA := DISTRIBUCION_MASIVA_LOG_SEQ.nextval;
END DISTRIBUCION_MASIVA_LOG_TRG;
/


--
-- DISTRIBUCION_MASIVA_LOG  (Synonym) 
--
--  Dependencies: 
--   DISTRIBUCION_MASIVA_LOG (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM DISTRIBUCION_MASIVA_LOG FOR SICAS_OC.DISTRIBUCION_MASIVA_LOG
/


-- 
-- Non Foreign Key Constraints for Table DISTRIBUCION_MASIVA_LOG 
-- 
ALTER TABLE SICAS_OC.DISTRIBUCION_MASIVA_LOG ADD (
  CONSTRAINT DISTRIBUCION_MASIVA_LOG_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDPOLIZA, IDTRANSACCION, NUMSECUENCIA)
  USING INDEX SICAS_OC.DISTRIBUCION_MASIVA_LOG_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.DISTRIBUCION_MASIVA_LOG TO PUBLIC
/
