
  CREATE TABLE "SICAS_OC"."DM_SMS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"CODSMS" VARCHAR2(6) NOT NULL ENABLE, 
	"CODTIPODESSMS" VARCHAR2(6) NOT NULL ENABLE, 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0), 
	"COD_MONEDA" VARCHAR2(5), 
	"MONTO_FACTURA" NUMBER(18,2), 
	"FECEMI_FACTURA" DATE, 
	"FECVENC_FACTURA" DATE, 
	"DIAS_VENC" NUMBER(4,0), 
	"CODRANGO_MORA" VARCHAR2(6), 
	"FECNAC_CLIENTE" DATE, 
	"EMAIL_CLIENTE" VARCHAR2(50), 
	"IDPOLIZA" NUMBER(14,0), 
	"FECVENC_POLIZA" DATE, 
	"EMAIL_AGENTE" VARCHAR2(50), 
	"NUMPOLREF" VARCHAR2(30), 
	 FOREIGN KEY ("CODEMPRESA", "CODCIA", "CODSMS")
	  REFERENCES "SICAS_OC"."CATALOGO_SMS" ("CODEMPRESA", "CODCIA", "CODSMS") ENABLE, 
	 FOREIGN KEY ("CODCIA", "CODRANGO_MORA")
	  REFERENCES "SICAS_OC"."RANGO_MORA_CLIENTE" ("CODCIA", "CODRANGO_MORA") ENABLE, 
	 FOREIGN KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
	  REFERENCES "SICAS_OC"."AGENTES" ("COD_AGENTE", "CODCIA", "CODEMPRESA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
