CREATE TABLE SICAS_OC.DOCUMENTOS_JSON
   ( CODEMPRESA    NUMBER(14)   NOT NULL,
     CODCIA        NUMBER(14)   NOT NULL,
     IDCOTIZACION  NUMBER(14)   NOT NULL,
     JSON_DATA     CLOB CHECK ( JSON_DATA IS JSON )
   )
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SICAS_OC.DOCUMENTOS_JSON  IS 'Documentos JSON por Cotización';
COMMENT ON COLUMN SICAS_OC.DOCUMENTOS_JSON.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN SICAS_OC.DOCUMENTOS_JSON.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN SICAS_OC.DOCUMENTOS_JSON.IDCOTIZACION IS 'Identificador único de la cotización';
COMMENT ON COLUMN SICAS_OC.DOCUMENTOS_JSON.JSON_DATA IS 'Documento JSON';

--Crea la llave Primaria
CREATE UNIQUE INDEX SICAS_OC.DOCUMENTOS_JSON_PK ON SICAS_OC.DOCUMENTOS_JSON
( CODEMPRESA, CODCIA, IDCOTIZACION )
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

-- Crea el Sinónimo
CREATE OR REPLACE PUBLIC SYNONYM DOCUMENTOS_JSON FOR SICAS_OC.DOCUMENTOS_JSON;
/

-- Genera los permisos
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.DOCUMENTOS_JSON TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.DOCUMENTOS_JSON TO ROL_CONSULTA_SICAS;
