
  CREATE TABLE "SICAS_OC"."DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER(22,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	"TEXTO" VARCHAR2(1000), 
	"PATHIMAGEN" VARCHAR2(100), 
	"ESTADO" VARCHAR2(3), 
	"FECHA_ESTADO" DATE, 
	"PATHFIRMA" VARCHAR2(100), 
	"DESCFIRMA" VARCHAR2(300), 
	"FECHA_ANULACION" DATE, 
	 CONSTRAINT "PK_DOCUMENTO" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
