
  CREATE TABLE "SICAS_OC"."EJECUTIVO_COMERCIAL" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEJECUTIVO" NUMBER(10,0) NOT NULL ENABLE, 
	"FECINGRESO" DATE, 
	"TIPODOCIDENTEJEC" VARCHAR2(6), 
	"NUMDOCIDENTEJEC" VARCHAR2(20), 
	"STSEJECUTIVO" VARCHAR2(10), 
	"FECSTS" DATE, 
	 CONSTRAINT "PK_EJECUTIVO_COMERCIAL" PRIMARY KEY ("CODCIA", "CODEJECUTIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPODOCIDENTEJEC", "NUMDOCIDENTEJEC")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
