
  CREATE TABLE "SICAS_OC"."EMPLEADOS_FUNCIONARIOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPLEADOFUNC" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPODOCIDENTEMP" VARCHAR2(6), 
	"NUMDOCIDENTEMP" VARCHAR2(20), 
	"FECINGRESO" DATE, 
	"STSEMPLEADOFUNC" VARCHAR2(10), 
	"FECSTS" DATE, 
	"CODPUESTOASIGNADO" VARCHAR2(10), 
	"AREADEPARTAMENTO" VARCHAR2(50), 
	"CODCENTROCOSTO" VARCHAR2(10), 
	"FECHABAJA" DATE, 
	"CODMOTIVOBAJA" VARCHAR2(10), 
	 CONSTRAINT "PK_EMPLEADOS_FUNCIONARIOS" PRIMARY KEY ("CODCIA", "CODEMPLEADOFUNC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPODOCIDENTEMP", "NUMDOCIDENTEMP")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
