
  CREATE TABLE "SICAS_OC"."EMPRESAS" 
   (	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C007095" NOT NULL ENABLE, 
	"NOMCIA" VARCHAR2(200), 
	"DIRCIA" VARCHAR2(250), 
	"LICENCIA" VARCHAR2(20), 
	"TELCIA" VARCHAR2(30), 
	"FAXCIA" VARCHAR2(20), 
	"EMAIL" VARCHAR2(150), 
	"APARTADO" VARCHAR2(20), 
	"ZONACIA" VARCHAR2(20), 
	"STSCIA" VARCHAR2(3), 
	"FECSTS" DATE, 
	"TIPO_ID_TRIBUTARIA" VARCHAR2(5), 
	"NUM_TRIBUTARIO" VARCHAR2(18), 
	"COD_MONEDA" VARCHAR2(5), 
	"INDTIPOEMP" VARCHAR2(2), 
	"PATH_LOGO" VARCHAR2(100), 
	"PAGINA_WEB" VARCHAR2(100), 
	"CONTABILIDAD_AUTOMATICA" VARCHAR2(1), 
	"ENCABEZADO_PANTALLA" VARCHAR2(100), 
	"DIAS_RENOVACION" NUMBER(3,0), 
	"CODCLIENTE" NUMBER(14,0), 
	"REGIMENFISFACTELECT" VARCHAR2(6), 
	 PRIMARY KEY ("CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPO_ID_TRIBUTARIA")
	  REFERENCES "SICAS_OC"."IDENTIFICACION_TRIBUTARIA" ("TIPO_ID_TRIBUTARIA") ENABLE, 
	 FOREIGN KEY ("COD_MONEDA")
	  REFERENCES "SICAS_OC"."MONEDA" ("COD_MONEDA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
