
  CREATE TABLE "SICAS_OC"."ENCA_FAC_COBRAR" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDFACOBRAR" NUMBER NOT NULL ENABLE, 
	"CODGRUPO" VARCHAR2(8) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHAGEN" DATE NOT NULL ENABLE, 
	"STSPROV" VARCHAR2(3) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ENCA_FAC_COBRAR" PRIMARY KEY ("CODCIA", "IDFACOBRAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_ENCA_FAC_COBRAR_USU" FOREIGN KEY ("CODCIA", "CODGRUPO", "CODUSUARIO")
	  REFERENCES "SICAS_OC"."USUARIOS" ("CODCIA", "CODGRUPO", "CODUSUARIO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
