--JIBARRA_17-11-2022<ELIMINA EL SINONIMO EXISTENTE PARA LA TABLA>
DROP PUBLIC SYNONYM ENDOSO_SERVICIOS_WEB;

--JIBARRA_17-11-2022<ELIMINA LA TABLA>
DROP TABLE SICAS_OC.ENDOSO_SERVICIOS_WEB;

/

--JIBARRA_17-11-2022<SE CREA TABLA PARA LLEVAR EL CONTROL DE LAS ACTUALIZACIONES DE FECHA QUE REALICE EL USUARIO AL GENERAR EL ENDOSO CORRESPONDIENTE>
CREATE TABLE SICAS_OC.ENDOSO_SERVICIOS_WEB(CODCIA			NUMBER(14,0) 	NOT NULL	--ELEMENTO QUE SE CONSEDERA PARA CREAR LA LLAVE PRIMARIA, COMPANIA THONA SEGUROS
								,IDPOLIZA			NUMBER(14,0) 	NOT NULL	--ELEMENTO QUE SE CONSEDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DE LA POLIZA
								,IDETPOL			NUMBER(14,0) 	NOT NULL	--ELEMENTO QUE SE CONSEDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DEL DETALLE DE POLIZA
								,IDENDOSO			NUMBER(14,0)	NOT NULL	--IDENTIFICADOR DEL ENDOSO QUE SE ESTA CREADO, GENERANDO SU DETALLE
								,FECINIVIGP			DATE			NOT NULL	--FECHA DE INICIO DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION
								,FECFINVIGP			DATE 			NOT NULL	--FECHA DE FIN DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION
								,FECINIVIGD			DATE 			NOT NULL	--FECHA DE INICIO DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION
								,FECFINVIGD			DATE 			NOT NULL	--FECHA DE FIN DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION
								,IDENDOSOUPD		NUMBER(14,0)				--IDENTIFICADOR DEL ENDOSO QUE SE ACTUALIZA
								,FECINIVIGE		    DATE						--FECHA DE INICIO DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION
								,FECFINVIGE		    DATE						--FECHA DE FIN DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION
								,NEWFECHAINI		DATE						--VALOR DE LA FECHAINI QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION
								,NEWFECHAFIN		DATE						--VALOR DE LA FECHAFIN QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION
								,TIPO_DOC_UPD		VARCHAR2(50)				--TIPO DE DOCUMENTO ASOCIADO AL ENDOSO QUE SE CATUALIZA[NOTA_DE_CREDITO(NC), FACTURA(F)]
								,ID_DOC_UPD			NUMBER(14,0)				--IDENTIFICADOR DEL DOCUEMNTO QUE SE ACTUALIZA
								,FECINI_DOC			DATE						--FECHA DE INICIO DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION
								,FECFIN_DOC			DATE						--FECHA FIN DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION
								,NEWFECHAINIDOC		DATE						--VALOR DE LA FECHAINI QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION
								,NEWFECHAFINDOC		DATE						--VALOR DE LA FECHAFIN QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION
								,ENDOSO_EMITIDO		VARCHAR2(2)		NOT NULL	--VALOR DE CONTROL PARA ONSIDERAR REGISTROS EMITIDO [CON LA FECHAS ACTUALIZADAS [S-SI, N-NO]]
								,UPD_SERVICIOS_WEB	VARCHAR2(2)					--VALOR DE CONTROL PARA LAS ACTUALZIACIONES POR PARTE DE SERVICIOS WEB [S-SI, N-NO, NULL]
								,NOTA_SERVICIOS_WEB VARCHAR2(250)				--NOTA/COMETNARIOS ADICIONALES A LA ACTUALIZACION DE [UPD_SERVICIOS_WEB]
								,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	--CAMPO DE CONTRO/AUDITORIA, USUARIO QUE CREA EL REGISTRO
								,FECHA_ALTA			DATE			NOT NULL	--CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
								,USUARIO_MOD		VARCHAR2(50)	NOT NULL	--CAMPO DE CONTRO/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
								,FECHA_MOD			DATE			NOT NULL	--CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE ACTUALIZA EL REGISTRO
								) TABLESPACE TS_SICASOC;

/
--##
CREATE UNIQUE INDEX SICAS_OC.ENDOSO_SERVICIOS_WEB_IDX_1 ON SICAS_OC.ENDOSO_SERVICIOS_WEB (CODCIA, IDPOLIZA, IDETPOL, IDENDOSO) TABLESPACE IDX_SICASOC;								

/
--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.ENDOSO_SERVICIOS_WEB ADD CONSTRAINT PK_ENDOSO_SERVICIOS_WEB PRIMARY KEY (CODCIA, IDPOLIZA, IDETPOL, IDENDOSO) USING INDEX;
ALTER TABLE SICAS_OC.ENDOSO_SERVICIOS_WEB ADD CONSTRAINT FK_ENDOSO_SERVICIOS_WEB FOREIGN KEY (IDPOLIZA,IDENDOSO) REFERENCES SICAS_OC.ENDOSOS(IDPOLIZA,IDENDOSO) ON DELETE CASCADE;

/
--##GRANT´s
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX ON SICAS_OC.ENDOSO_SERVICIOS_WEB TO PUBLIC;

/
--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.CODCIA 				IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, COMPANIA THONA SEGUROS';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.IDPOLIZA 			IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DE LA POLIZA';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.IDETPOL 			IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DEL DETALLE DE POLIZA';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.IDENDOSO 			IS 'IDENTIFICADOR DEL ENDOSO QUE SE ESTA CREADO, GENERANDO SU DETALLE';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECINIVIGP 			IS 'FECHA DE INICIO DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECFINVIGP 			IS 'FECHA DE FIN DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECINIVIGD 			IS 'FECHA DE INICIO DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECFINVIGD 			IS 'FECHA DE FIN DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.IDENDOSOUPD			IS 'IDENTIFICADOR DEL ENDOSO QUE SE ACTUALIZA';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECINIVIGE 			IS 'FECHA DE INICIO DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECFINVIGE 			IS 'FECHA DE FIN DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.NEWFECHAINI 		IS 'VALOR DE LA FECHAINI QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.NEWFECHAFIN 		IS 'VALOR DE LA FECHAFIN QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.TIPO_DOC_UPD 		IS 'TIPO DE DOCUMENTO ASOCIADO AL ENDOSO QUE SE CATUALIZA[NOTA_DE_CREDITO(NCR), FACTURA(RECIBO)]';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.ID_DOC_UPD	 		IS 'IDENTIFICADOR DEL DOCUEMNTO QUE SE ACTUALIZA';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECINI_DOC 			IS 'FECHA DE INICIO DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECFIN_DOC 			IS 'FECHA FIN DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.NEWFECHAINIDOC 		IS 'VALOR DE LA FECHAINI QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.NEWFECHAFINDOC 		IS 'VALOR DE LA FECHAFIN QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.ENDOSO_EMITIDO 		IS 'VALOR DE CONTROL PARA ONSIDERAR REGISTROS EMITIDO [CON LA FECHAS ACTUALIZADAS [S-SI, N-NO]]';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.UPD_SERVICIOS_WEB	IS 'VALOR DE CONTROL PARA LAS ACTUALZIACIONES POR PARTE DE SERVICIOS WEB [S-SI, N-NO, NULL]';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.NOTA_SERVICIOS_WEB 	IS 'NOTA/COMETNARIOS ADICIONALES A LA ACTUALIZACION DE [UPD_SERVICIOS_WEB]';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.USUARIO_ALTA 		IS 'CAMPO DE CONTRO/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECHA_ALTA 			IS 'CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.USUARIO_MOD 		IS 'CAMPO DE CONTRO/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.ENDOSO_SERVICIOS_WEB.FECHA_MOD 			IS 'CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE ACTUALIZA EL REGISTRO';

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM ENDOSO_SERVICIOS_WEB FOR SICAS_OC.ENDOSO_SERVICIOS_WEB;
