
  CREATE TABLE "SICAS_OC"."ENDOSO_TXT_DET" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODENDOSO" VARCHAR2(20) NOT NULL ENABLE, 
	"TEXTO" LONG, 
	 PRIMARY KEY ("CODCIA", "CODENDOSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCIA", "CODENDOSO")
	  REFERENCES "SICAS_OC"."ENDOSO_TXT_ENC" ("CODCIA", "CODENDOSO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
