
  CREATE TABLE "SICAS_OC"."ENDOSO_SERVICIOS_WEB" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"IDENDOSO" NUMBER(14,0) NOT NULL ENABLE, 
	"FECINIVIGP" DATE NOT NULL ENABLE, 
	"FECFINVIGP" DATE NOT NULL ENABLE, 
	"FECINIVIGD" DATE NOT NULL ENABLE, 
	"FECFINVIGD" DATE NOT NULL ENABLE, 
	"IDENDOSOUPD" NUMBER(14,0), 
	"FECINIVIGE" DATE, 
	"FECFINVIGE" DATE, 
	"NEWFECHAINI" DATE, 
	"NEWFECHAFIN" DATE, 
	"TIPO_DOC_UPD" VARCHAR2(50 BYTE), 
	"ID_DOC_UPD" NUMBER(14,0), 
	"FECINI_DOC" DATE, 
	"FECFIN_DOC" DATE, 
	"NEWFECHAINIDOC" DATE, 
	"NEWFECHAFINDOC" DATE, 
	"ENDOSO_EMITIDO" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"UPD_SERVICIOS_WEB" VARCHAR2(2 BYTE), 
	"NOTA_SERVICIOS_WEB" VARCHAR2(250 BYTE), 
	"USUARIO_ALTA" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FECHA_ALTA" DATE NOT NULL ENABLE, 
	"USUARIO_MOD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FECHA_MOD" DATE NOT NULL ENABLE, 
	 CONSTRAINT "FK_ENDOSO_SERVICIOS_WEB" FOREIGN KEY ("IDPOLIZA", "IDENDOSO")
	  REFERENCES "SICAS_OC"."ENDOSOS" ("IDPOLIZA", "IDENDOSO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" ;
  CREATE UNIQUE INDEX "SICAS_OC"."ENDOSO_SERVICIOS_WEB_IDX_1" ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" ("CODCIA", "IDPOLIZA", "IDETPOL", "IDENDOSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" ;
ALTER TABLE "SICAS_OC"."ENDOSO_SERVICIOS_WEB" ADD CONSTRAINT "PK_ENDOSO_SERVICIOS_WEB" PRIMARY KEY ("CODCIA", "IDPOLIZA", "IDETPOL", "IDENDOSO")
  USING INDEX "SICAS_OC"."ENDOSO_SERVICIOS_WEB_IDX_1"  ENABLE;

   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."CODCIA" IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, COMPANIA THONA SEGUROS';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."IDPOLIZA" IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DE LA POLIZA';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."IDETPOL" IS 'ELEMENTO QUE SE CONSIDERA PARA CREAR LA LLAVE PRIMARIA, IDENTIFICADOR UNICO DEL DETALLE DE POLIZA';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."IDENDOSO" IS 'IDENTIFICADOR DEL ENDOSO QUE SE ESTA CREADO, GENERANDO SU DETALLE';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECINIVIGP" IS 'FECHA DE INICIO DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECFINVIGP" IS 'FECHA DE FIN DE VIGENCIA DE LA POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECINIVIGD" IS 'FECHA DE INICIO DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECFINVIGD" IS 'FECHA DE FIN DE VIGENCIA DEL DETALLE DE POLIZA, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."IDENDOSOUPD" IS 'IDENTIFICADOR DEL ENDOSO QUE SE ACTUALIZA';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECINIVIGE" IS 'FECHA DE INICIO DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECFINVIGE" IS 'FECHA DE FIN DE VIGENCIA DEL ENDOSO, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."NEWFECHAINI" IS 'VALOR DE LA FECHAINI QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."NEWFECHAFIN" IS 'VALOR DE LA FECHAFIN QUE SE APLICARA A LOS ELEMENTOS RESPECTO AL TIPO DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."TIPO_DOC_UPD" IS 'TIPO DE DOCUMENTO ASOCIADO AL ENDOSO QUE SE CATUALIZA[NOTA_DE_CREDITO(NCR), FACTURA(RECIBO)]';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."ID_DOC_UPD" IS 'IDENTIFICADOR DEL DOCUEMNTO QUE SE ACTUALIZA';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECINI_DOC" IS 'FECHA DE INICIO DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECFIN_DOC" IS 'FECHA FIN DEL DOCUMETO QUE SE ACTUALIZO, VALOR DE CONTROL DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."NEWFECHAINIDOC" IS 'VALOR DE LA FECHAINI QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."NEWFECHAFINDOC" IS 'VALOR DE LA FECHAFIN QUE SE APLICARA AL DOCUMENTO RESPECTO AL TIPO DE ACTUALIZACION';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."ENDOSO_EMITIDO" IS 'VALOR DE CONTROL PARA ONSIDERAR REGISTROS EMITIDO [CON LA FECHAS ACTUALIZADAS [S-SI, N-NO]]';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."UPD_SERVICIOS_WEB" IS 'VALOR DE CONTROL PARA LAS ACTUALZIACIONES POR PARTE DE SERVICIOS WEB [S-SI, N-NO, NULL]';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."NOTA_SERVICIOS_WEB" IS 'NOTA/COMETNARIOS ADICIONALES A LA ACTUALIZACION DE [UPD_SERVICIOS_WEB]';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."USUARIO_ALTA" IS 'CAMPO DE CONTRO/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECHA_ALTA" IS 'CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."USUARIO_MOD" IS 'CAMPO DE CONTRO/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
   COMMENT ON COLUMN "SICAS_OC"."ENDOSO_SERVICIOS_WEB"."FECHA_MOD" IS 'CAMPO DE CONTRO/AUDITORIA, FECHA EN QUE SE ACTUALIZA EL REGISTRO';


  GRANT ALTER ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
  GRANT DELETE ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
  GRANT INDEX ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
  GRANT INSERT ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
  GRANT SELECT ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
  GRANT UPDATE ON "SICAS_OC"."ENDOSO_SERVICIOS_WEB" TO PUBLIC;
