
  CREATE TABLE "SICAS_OC"."ENDOSOS" 
   (	"IDPOLIZA" NUMBER(14,0) CONSTRAINT "SYS_C007101" NOT NULL ENABLE, 
	"IDENDOSO" NUMBER(14,0) CONSTRAINT "SYS_C007102" NOT NULL ENABLE, 
	"TIPOENDOSO" VARCHAR2(6), 
	"NUMENDREF" VARCHAR2(30), 
	"FECINIVIG" DATE CONSTRAINT "SYS_C007103" NOT NULL ENABLE, 
	"FECFINVIG" DATE CONSTRAINT "SYS_C007104" NOT NULL ENABLE, 
	"FECSOLICITUD" DATE, 
	"FECEMISION" DATE, 
	"STSENDOSO" VARCHAR2(3), 
	"FECSTS" DATE CONSTRAINT "SYS_C007105" NOT NULL ENABLE, 
	"CODPLANPAGO" VARCHAR2(4), 
	"FECANUL" DATE, 
	"MOTIVANUL" VARCHAR2(6), 
	"SUMA_ASEG_LOCAL" NUMBER(18,2), 
	"SUMA_ASEG_MONEDA" NUMBER(18,2), 
	"PRIMA_NETA_LOCAL" NUMBER(18,2), 
	"DESCENDOSO" VARCHAR2(2000), 
	"PRIMA_NETA_MONEDA" NUMBER(18,2), 
	"PORCCOMIS" NUMBER(9,6), 
	"CODEMPRESA" NUMBER(14,0) CONSTRAINT "SYS_C007107" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C007108" NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0), 
	"NUM_BIEN" NUMBER(14,0), 
	"MOTIVO_ENDOSO" VARCHAR2(6), 
	"FECEXC" DATE, 
	"INDCALCDERECHOEMIS" VARCHAR2(1) DEFAULT 'N', 
	"PLDSTBLOQUEADA" VARCHAR2(2), 
	"PLDSTAPROBADA" VARCHAR2(2), 
	"PLDUSUARIOAPROB" VARCHAR2(15), 
	"MONTOAPORTEFONDO" NUMBER(18,2), 
	"CVE_MOTIVCANCFACT" VARCHAR2(30 CHAR), 
	"CODOBJETOIMP" VARCHAR2(10), 
	"CODUSOCFDI" VARCHAR2(10), 
	 PRIMARY KEY ("IDPOLIZA", "IDENDOSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODPLANPAGO", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."PLAN_DE_PAGOS" ("CODPLANPAGO", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
