
  CREATE TABLE "SICAS_OC"."ENTIDAD_FINANCIERA" 
   (	"CODCIA" NUMBER(14,0), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"CODENTIDAD" VARCHAR2(6), 
	"ESTADO" VARCHAR2(6), 
	"TIPOENTIDAD" VARCHAR2(6), 
	"FECHA_ESTADO" DATE, 
	"CODUSUARIO" VARCHAR2(15), 
	"CODBANCARIO" VARCHAR2(6), 
	"CODBCOMIZAR" NUMBER(5,0) DEFAULT 0, 
	 CONSTRAINT "ENTIDAD_FINANCIERA_PK" PRIMARY KEY ("CODCIA", "TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "CODENTIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "ENT_FINAN_PER_NAT_JURID_FK" FOREIGN KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
