
  CREATE TABLE "SICAS_OC"."EVALUA_QEQ" 
   (	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"COD_ASEG_CLI" NUMBER(14,0), 
	"NOMBRE" VARCHAR2(200), 
	"ESTA_EN_QEQ" VARCHAR2(10), 
	"LISTA" VARCHAR2(1000), 
	"TIPO_PERSONA" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
