
  CREATE TABLE "SICAS_OC"."EX_SABE_CATCLIEN_M" 
   (	"NUMERO_CLIENTE" NUMBER(9,0), 
	"TIPO_DE_PERSONA" VARCHAR2(10), 
	"RFC" VARCHAR2(13), 
	"FECHA_STATUS" VARCHAR2(8), 
	"NOMBRE_COMPLETO" VARCHAR2(180), 
	"PS_CV_PAIS" VARCHAR2(3), 
	"PAIS" VARCHAR2(30), 
	"EMAIL" VARCHAR2(60), 
	"CALLE_FISCAL" VARCHAR2(80), 
	"NUM_EXT_FISCAL" VARCHAR2(20), 
	"NUM_INT_FISCAL" VARCHAR2(20), 
	"COLONIA_FISCAL" VARCHAR2(100), 
	"POBLACION_FISCAL" VARCHAR2(60), 
	"CV_EDO" VARCHAR2(2), 
	"ESTADO_FISCAL" VARCHAR2(30), 
	"CP_FISCAL" VARCHAR2(6), 
	"CV_MUN_FISCAL" VARCHAR2(3), 
	"MUNICIPIO_FISCAL" VARCHAR2(30), 
	"TELEFONO1" VARCHAR2(20), 
	"TELEFONO2" VARCHAR2(20), 
	"TELEFONO3" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
