
  CREATE TABLE "SICAS_OC"."FACT_ELECT_PROD_SERV" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CLAVEPRODSERV" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCCLAVEPRODSERV" VARCHAR2(200), 
	"INDAPLICANEGOCIO" VARCHAR2(1) DEFAULT 'N', 
	"CLAVEUNIDAD" VARCHAR2(10), 
	"CODUSUARIO" VARCHAR2(30), 
	"FECULTMODIF" DATE, 
	 CONSTRAINT "PK_FACT_ELECT_PROD_SERV" PRIMARY KEY ("CODCIA", "CLAVEPRODSERV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_FACT_ELECT_PROD_SERV_EMP" FOREIGN KEY ("CODCIA")
	  REFERENCES "SICAS_OC"."EMPRESAS" ("CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
