DROP TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
/
--
-- FACTOR_NIVEL_HOSPITALARIO  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  IDTIPOSEG           VARCHAR2(6 BYTE)          NOT NULL,
  PLANCOB             VARCHAR2(15 BYTE)         NOT NULL,
  CODCOBERT           VARCHAR2(7 BYTE)          NOT NULL,
  CODENDOSO           VARCHAR2(10 BYTE)         NOT NULL,   
  INDINCLUIDO         VARCHAR2(1 BYTE)          NOT NULL,
  FACTOR              NUMBER(9,6)               NOT NULL
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO IS 'Factor para el Nivel Hospitalario'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODENDOSO IS 'Código de Endoso'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.INDINCLUIDO IS 'Indicador de Incluido'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.FACTOR IS 'Factor'
/

--
-- FACTOR_NIVEL_HOSPITALARIO_PK  (Index) 
--
--  Dependencies: 
--   FACTOR_NIVEL_HOSPITALARIO (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_NIVEL_HOSPITALARIO_PK ON SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, CODENDOSO)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- FACTOR_NIVEL_HOSPITALARIO  (Synonym) 
--
--  Dependencies: 
--   FACTOR_NIVEL_HOSPITALARIO (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_NIVEL_HOSPITALARIO FOR SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
/

-- 
-- Non Foreign Key Constraints for Table FACTOR_NIVEL_HOSPITALARIO 
-- 
ALTER TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO ADD (
  CONSTRAINT FACTOR_NIVEL_HOSPITALARIO_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, CODENDOSO)
  USING INDEX SICAS_OC.FACTOR_NIVEL_HOSPITALARIO_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_NIVEL_HOSPITALARIO TO PUBLIC
/