DROP TABLE FACT_ELECT_USO_CFDI CASCADE CONSTRAINTS;

CREATE TABLE FACT_ELECT_USO_CFDI
(CODCIA              NUMBER(14)      NOT NULL,
 CODUSOCFDI          VARCHAR2(10)    NOT NULL,
 DESCUSOCFDI         VARCHAR2(300)     NOT NULL,
 INDPERSFISICA       VARCHAR2(1),
 INDPERSMORAL        VARCHAR2(1),
 FECINIVIG           DATE,
 FECFINVIG           DATE,
 CODUSUARIO          VARCHAR2(30),
 FECMOD              DATE
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.CODCIA IS 'Código De La Compañía';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.CODUSOCFDI IS 'Código Uso del CFDI';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.DESCUSOCFDI IS 'Descripción del Uso de CFDI';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.INDPERSFISICA IS 'Indicador Aplica Persona Fïsica';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.INDPERSMORAL IS 'Indicador Aplica Persona Moral';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.FECINIVIG IS 'Fecha Incio de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.FECFINVIG IS 'Fecha Fin de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.CODUSUARIO IS 'Fecha Incio de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI.FECMOD IS 'Fecha Fin de Vigencia';

CREATE UNIQUE INDEX SICAS_OC.IDX_USO_CFDI ON SICAS_OC.FACT_ELECT_USO_CFDI
(CODCIA,CODUSOCFDI)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SICAS_OC.FACT_ELECT_USO_CFDI ADD (
  CONSTRAINT PK_USO_CFDI
  PRIMARY KEY
  (CODCIA,CODUSOCFDI)
  USING INDEX SICAS_OC.IDX_USO_CFDI
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACT_ELECT_USO_CFDI TO PUBLIC;

CREATE OR REPLACE PUBLIC SYNONYM FACT_ELECT_USO_CFDI FOR SICAS_OC.FACT_ELECT_USO_CFDI;
