
  CREATE TABLE "SICAS_OC"."FACT_ELECT_USO_CFDI_REG" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODUSOCFDI" VARCHAR2(10) NOT NULL ENABLE, 
	"IDREGFISSAT" NUMBER(5,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USO_CFDI_REG" PRIMARY KEY ("CODCIA", "CODUSOCFDI", "IDREGFISSAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_USO_CFDI_REG" FOREIGN KEY ("IDREGFISSAT")
	  REFERENCES "SICAS_OC"."CAT_REGIMEN_FISCAL" ("IDREGFISSAT") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
