DROP TABLE FACT_ELECT_OBJETO_IMPUESTO CASCADE CONSTRAINTS;

CREATE TABLE FACT_ELECT_OBJETO_IMPUESTO
(CODCIA              NUMBER(14)      NOT NULL,
 CODOBJETOIMP        VARCHAR2(10)    NOT NULL,
 DESCOBJETOIMP       VARCHAR2(300)   NOT NULL,
 FECINIVIG           DATE,
 FECFINVIG           DATE,
 CODUSUARIO          VARCHAR2(30),
 FECMOD              DATE
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.CODCIA IS 'Código De La Compañía';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.CODOBJETOIMP IS 'Código Objeto de Impuesto';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.DESCOBJETOIMP IS 'Descripción Objeto de Impuesto';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.FECINIVIG IS 'Fecha Incio de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.FECFINVIG IS 'Fecha Fin de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.CODUSUARIO IS 'Fecha Incio de Vigencia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO.FECMOD IS 'Fecha Fin de Vigencia';

CREATE UNIQUE INDEX SICAS_OC.IDX_OBJETO_IMP ON SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO
(CODCIA,CODOBJETOIMP)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO ADD (
  CONSTRAINT PK_OBJETO_IMP
  PRIMARY KEY
  (CODCIA,CODOBJETOIMP)
  USING INDEX SICAS_OC.IDX_OBJETO_IMP
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO TO PUBLIC;

CREATE OR REPLACE PUBLIC SYNONYM FACT_ELECT_OBJETO_IMPUESTO FOR SICAS_OC.FACT_ELECT_OBJETO_IMPUESTO;
