DROP TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
/
--
-- FACTOR_EQUIPOS_REPRESENTA  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  IDTIPOSEG           VARCHAR2(6 BYTE)          NOT NULL,
  PLANCOB             VARCHAR2(15 BYTE)         NOT NULL,
  CODPAQUETE          NUMBER(14)                NOT NULL,
  CODEQUIPO           VARCHAR2(10 BYTE)         NOT NULL,   
  INDINCLUIDO         VARCHAR2(1 BYTE)          NOT NULL,
  FACTOR              NUMBER(9,6)               NOT NULL,
  TEXTOFACTOR         VARCHAR2(4000 BYTE)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA IS 'Factor para los Equipos Representativos'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODPAQUETE IS 'Código del Paquete Comercial'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODEQUIPO IS 'Código del Equipo Representativo'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.INDINCLUIDO IS 'Indicador de Incluido'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.FACTOR IS 'Factor'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.TEXTOFACTOR IS 'Texto Especial del Factor'
/

--
-- FACTOR_EQUIPOS_REPRESENTA_PK  (Index) 
--
--  Dependencies: 
--   FACTOR_EQUIPOS_REPRESENTA (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_EQUIPOS_REPRESENTA_PK ON SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, CODEQUIPO)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- FACTOR_EQUIPOS_REPRESENTA  (Synonym) 
--
--  Dependencies: 
--   FACTOR_EQUIPOS_REPRESENTA (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_EQUIPOS_REPRESENTA FOR SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
/

-- 
-- Non Foreign Key Constraints for Table FACTOR_EQUIPOS_REPRESENTA 
-- 
ALTER TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA ADD (
  CONSTRAINT FACTOR_EQUIPOS_REPRESENTA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, CODEQUIPO)
  USING INDEX SICAS_OC.FACTOR_EQUIPOS_REPRESENTA_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_EQUIPOS_REPRESENTA TO PUBLIC
/