
  CREATE TABLE "SICAS_OC"."FACTURAS_RECLAMADAS" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDDETSIN" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"ID_CONSECUTIVO" NUMBER(3,0), 
	"NUM_COMPROBANTE" VARCHAR2(15), 
	"FOLIO_FISCAL" VARCHAR2(40), 
	"FEC_EMISION_COMPROB" DATE, 
	"RFC_PROVEEDOR" VARCHAR2(16), 
	"NOM_PROVEEDOR" VARCHAR2(100), 
	"TP_PROCEDIMIENTO" VARCHAR2(6), 
	"MONTO_RECLAMADO" NUMBER(18,2), 
	"MONTO_AUTORIZADO" NUMBER(18,2), 
	"TP_CONCEPTO_NO_CUBIERTO" VARCHAR2(6), 
	"OBSERVACIONES" VARCHAR2(300), 
	 CONSTRAINT "FACTURAS_RECLAMADAS_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDSINIESTRO", "IDDETSIN", "IDPOLIZA", "COD_ASEGURADO", "ID_CONSECUTIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
