
  CREATE TABLE "SICAS_OC"."FACT_ELECT_MOTIVO_CANCELA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CVEMOTIVCANCFACT" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCMOTIVOCANC" VARCHAR2(300) NOT NULL ENABLE, 
	"STSMOTIVCANC" VARCHAR2(3), 
	"FECSTSMOTIVCANC" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "P_MOTIV_CANC" PRIMARY KEY ("CODCIA", "CVEMOTIVCANCFACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
