
  CREATE TABLE "SICAS_OC"."FACT_ELECT_CAT_GPO_LINEA" 
   (	"CODCIA" NUMBER NOT NULL ENABLE, 
	"CODIDENTIFICADOR" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCIDENTIFICADOR" VARCHAR2(3000), 
	"VERSIONCFDI" VARCHAR2(5), 
	"CODUSUARIO" VARCHAR2(30), 
	"FECHALINEA" DATE, 
	 CONSTRAINT "P_CAT_IDENTIFICADOR" PRIMARY KEY ("CODCIA", "CODIDENTIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
