DROP TABLE SICAS_OC.FACTOR_GUA
/
--
-- FACTOR_GUA  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_GUA
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  IDTIPOSEG           VARCHAR2(6 BYTE)          NOT NULL,
  PLANCOB             VARCHAR2(15 BYTE)         NOT NULL,
  CODCOBERT           VARCHAR2(7 BYTE)          NOT NULL,
  NIVEL               VARCHAR2(8 BYTE)          NOT NULL,
  FACTOR              NUMBER(9,6)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.FACTOR_GUA IS 'Factor Para El Gasto Usual Acostumbrado'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.NIVEL IS 'Nivel'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.FACTOR IS 'Factor'
/

--
-- FACTOR_GUA_PK  (Index) 
--
--  Dependencies: 
--   FACTOR_GUA (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_GUA_PK ON SICAS_OC.FACTOR_GUA
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, NIVEL )
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- FACTOR_GUA  (Synonym) 
--
--  Dependencies: 
--   FACTOR_GUA (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_GUA FOR SICAS_OC.FACTOR_GUA
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_GUA 
-- 
ALTER TABLE SICAS_OC.FACTOR_GUA ADD (
  CONSTRAINT FACTOR_GUA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, NIVEL )
  USING INDEX SICAS_OC.FACTOR_GUA_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_GUA TO PUBLIC
/