DROP TABLE SICAS_OC.FACTOR_REGION CASCADE CONSTRAINTS;
/
--
-- FACTOR_REGION  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_REGION
(
  CODCIA       NUMBER(14)                        NOT NULL,
  CODEMPRESA   NUMBER(14)                        NOT NULL,
  IDTIPOSEG    VARCHAR2(6 BYTE)                  NOT NULL,
  PLANCOB      VARCHAR2(15 BYTE)                 NOT NULL,
  CODPAQUETE   NUMBER(14)                        NOT NULL,
  CODREGION    VARCHAR2(6 BYTE)                  NOT NULL,
  FACTOR       NUMBER(9,6),
  TEXTOFACTOR  VARCHAR2(4000)
)

TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.FACTOR_REGION IS 'Factor por Región'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODPAQUETE IS 'Código del Paquete Comercial'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODREGION IS 'Código de la Región'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.FACTOR IS 'Factor'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.TEXTOFACTOR IS 'Texto Para Factor de la Región'
/



--
-- FACTOR_REGION_PK  (Index) 
--
--  Dependencies: 
--   FACTOR_REGION (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_REGION_PK ON SICAS_OC.FACTOR_REGION
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, 
CODREGION)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- FACTOR_REGION  (Synonym) 
--
--  Dependencies: 
--   FACTOR_REGION (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_REGION FOR SICAS_OC.FACTOR_REGION
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_REGION 
-- 
ALTER TABLE SICAS_OC.FACTOR_REGION ADD (
  CONSTRAINT FACTOR_REGION_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, CODREGION)
  USING INDEX SICAS_OC.FACTOR_REGION_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_REGION TO PUBLIC
/