
  CREATE TABLE "SICAS_OC"."FACT_ELECT_CAT_CAMPOS_CFDI" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODIDENTIFICADOR" VARCHAR2(10) NOT NULL ENABLE, 
	"CODATRIBUTO" VARCHAR2(30) NOT NULL ENABLE, 
	"DESCATRIBUTO" VARCHAR2(4000), 
	"CODRUTINACALC" VARCHAR2(20), 
	 CONSTRAINT "P_ATRIBUTO" PRIMARY KEY ("CODCIA", "CODIDENTIFICADOR", "CODATRIBUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
