DROP TABLE FACT_ELECT_USO_CFDI_REG CASCADE CONSTRAINTS;

CREATE TABLE FACT_ELECT_USO_CFDI_REG
(CODCIA              NUMBER(14)      NOT NULL,
 CODUSOCFDI          VARCHAR2(10)    NOT NULL,
 IDREGFISSAT         NUMBER(5)       NOT NULL
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI_REG.CODCIA IS 'Código De La Compañía';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI_REG.CODUSOCFDI IS 'Código Uso del CFDI';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_USO_CFDI_REG.IDREGFISSAT IS 'Id Regimen Fiscal';


CREATE UNIQUE INDEX SICAS_OC.IDX_USO_CFDI_REG ON SICAS_OC.FACT_ELECT_USO_CFDI_REG
(CODCIA, CODUSOCFDI, IDREGFISSAT)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SICAS_OC.FACT_ELECT_USO_CFDI_REG ADD (
  CONSTRAINT PK_USO_CFDI_REG
  PRIMARY KEY
  (CODCIA, CODUSOCFDI, IDREGFISSAT)
  USING INDEX SICAS_OC.IDX_USO_CFDI_REG
  ENABLE VALIDATE);


ALTER TABLE FACT_ELECT_USO_CFDI_REG
ADD CONSTRAINT FK_USO_CFDI_REG
   FOREIGN KEY (IDREGFISSAT)
   REFERENCES CAT_REGIMEN_FISCAL (IDREGFISSAT); 
   

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACT_ELECT_USO_CFDI_REG TO PUBLIC;

CREATE OR REPLACE PUBLIC SYNONYM FACT_ELECT_USO_CFDI_REG FOR SICAS_OC.FACT_ELECT_USO_CFDI_REG;
