
  CREATE TABLE "SICAS_OC"."FACTOR_ZONA_GEOGRAFICA" 
   (	"CODZONAGEO" VARCHAR2(6) NOT NULL ENABLE, 
	"FECINIVIG" DATE, 
	"FECFINVIG" DATE, 
	"FACTORZONA" NUMBER(9,6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FACTOR_ZONA_GEOGRAFICA" PRIMARY KEY ("CODZONAGEO", "FECINIVIG", "FECFINVIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
