
  CREATE TABLE "SICAS_OC"."FACT_ELECT_OBJETO_IMPUESTO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODOBJETOIMP" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCOBJETOIMP" VARCHAR2(300) NOT NULL ENABLE, 
	"FECINIVIG" DATE, 
	"FECFINVIG" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	"FECMOD" DATE, 
	 CONSTRAINT "PK_OBJETO_IMP" PRIMARY KEY ("CODCIA", "CODOBJETOIMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
