DROP TABLE SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE
/
--
-- FACT_ELECT_DOCTOS_TIMBRE  (Table) 
--
CREATE TABLE SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE 
   ( CODCIA       NUMBER(14) NOT NULL, 
     CODEMPRESA   NUMBER(14) NOT NULL, 
     IDTIMBRE     NUMBER(14) NOT NULL, 
     IDFACTURA    NUMBER(14), 
     IDNCR        NUMBER(14), 
     CODPROCESO   VARCHAR2(6 BYTE) NOT NULL, 
     DOCTOXML     CLOB,
     DOCTOPDF     CLOB,
     DOCTOIMG     CLOB,
     NOMBARCHZIP  VARCHAR2(200),
     IDAGRUPAENV  NUMBER(14),
     IDENTREGADO  VARCHAR2(1) )
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE  IS 'Registro de los Documentos del Timbre de Facturación Electrónica';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.CODCIA IS 'Código De La Compañía';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.CODEMPRESA IS 'Código De La Empresa';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.IDTIMBRE IS 'Identificador Único De Timbre Fiscal';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.IDFACTURA IS 'Identificador De Factura';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.IDNCR IS 'Identificador De Nota De Crédito';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.CODPROCESO IS 'Código De Proceso Del Timbre, Valores de Lista (PROCFACELE)';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.DOCTOXML IS 'Contenido del Documento XML en Carácter';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.DOCTOPDF IS 'Contenido del Documento PDF en Base64';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.DOCTOIMG IS 'Contenido del Documento IMG en Base64';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.NOMBARCHZIP IS 'Nombre del Archivo ZIP que agrupa los archivos png, xml y pdf';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.IDAGRUPAENV IS 'Indicador del agrupador del envío';
COMMENT ON COLUMN SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE.IDENTREGADO IS 'Indicador de entregado S o N';

--
-- FACT_ELECT_DOCTOS_TIMBRE_PK  (Index) 
--
--  Dependencies: 
--   FACT_ELECT_DOCTOS_TIMBRE (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE_PK ON SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE
( CODCIA, CODEMPRESA, IDTIMBRE )
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX SICAS_OC.FACT_ELECT_DOC_TIM_IDX1 ON SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE (CODCIA, CODEMPRESA, IDFACTURA) 
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX SICAS_OC.FACT_ELECT_DOC_TIM_IDX2 ON SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE (CODCIA, CODEMPRESA, IDNCR) 
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

--
-- FACT_ELECT_DOCTOS_TIMBRE  (Synonym) 
--
--  Dependencies: 
--   FACT_ELECT_DOCTOS_TIMBRE (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FACT_ELECT_DOCTOS_TIMBRE FOR SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE;

-- 
-- Non Foreign Key Constraints for Table FACT_ELECT_DOCTOS_TIMBRE
-- 
ALTER TABLE SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE ADD (
  CONSTRAINT FACT_ELECT_DOCTOS_TIMBRE_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, IDTIMBRE )
  USING INDEX SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE_PK
  ENABLE VALIDATE);
  
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACT_ELECT_DOCTOS_TIMBRE TO PUBLIC;