
  CREATE TABLE "SICAS_OC"."FAI_TASAS_DE_IMPUESTOS" 
   (	"TIPOIMPUESTO" VARCHAR2(10) NOT NULL ENABLE, 
	"FECINIVIG" DATE NOT NULL ENABLE, 
	"FECFINVIG" DATE NOT NULL ENABLE, 
	"TASAIMPUESTO" NUMBER(20,6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FAI_TASAS_DE_IMPUESTOS" PRIMARY KEY ("TIPOIMPUESTO", "FECINIVIG", "FECFINVIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_FAI_TASAS_IMPUESTOS_TIPOS" FOREIGN KEY ("TIPOIMPUESTO")
	  REFERENCES "SICAS_OC"."FAI_TIPOS_DE_IMPUESTOS" ("TIPOIMPUESTO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
