
  CREATE TABLE "SICAS_OC"."FAI_PRECIOS_DIARIOS" 
   (	"TIPOPRECIO" VARCHAR2(10) NOT NULL ENABLE, 
	"FECPRECIO" DATE NOT NULL ENABLE, 
	"PRECIODIARIO" NUMBER(28,12) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FAI_PRECIOS_DIARIOS" PRIMARY KEY ("TIPOPRECIO", "FECPRECIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_FAI_PRECIOS_DIARIOS" FOREIGN KEY ("TIPOPRECIO")
	  REFERENCES "SICAS_OC"."FAI_PRECIOS" ("TIPOPRECIO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
