
  CREATE TABLE "SICAS_OC"."FAI_TIPOS_DE_INTERES" 
   (	"TIPOINTERES" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCTIPOINTERES" VARCHAR2(200) NOT NULL ENABLE, 
	"PERIODICIDAD" VARCHAR2(6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FAI_TIPOS_DE_INTERES" PRIMARY KEY ("TIPOINTERES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
