
  CREATE TABLE "SICAS_OC"."FAI_CARGOS_FONDOS_RANGOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPOFONDO" VARCHAR2(10) NOT NULL ENABLE, 
	"CODCARGO" VARCHAR2(10) NOT NULL ENABLE, 
	"FECINICARGO" DATE NOT NULL ENABLE, 
	"FECFINCARGO" DATE NOT NULL ENABLE, 
	"ANOINIRANGO" NUMBER(4,0) NOT NULL ENABLE, 
	"ANOFINRANGO" NUMBER(4,0) NOT NULL ENABLE, 
	"RANGOINI" NUMBER(28,2) NOT NULL ENABLE, 
	"RANGOFIN" NUMBER(28,2) NOT NULL ENABLE, 
	"PORCCARGO" NUMBER(12,6), 
	"MONTOCARGO" NUMBER(28,2), 
	"CODRUTINACALC" VARCHAR2(30), 
	 CONSTRAINT "PK_FAI_CARGOS_FONDOS_RANGOS" PRIMARY KEY ("CODCIA", "CODEMPRESA", "TIPOFONDO", "CODCARGO", "FECINICARGO", "FECFINCARGO", "ANOINIRANGO", "ANOFINRANGO", "RANGOINI", "RANGOFIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_FAI_CARGOS_FONDOS_RANGOS" FOREIGN KEY ("CODCIA", "CODEMPRESA", "TIPOFONDO", "CODCARGO")
	  REFERENCES "SICAS_OC"."FAI_CARGOS_FONDOS" ("CODCIA", "CODEMPRESA", "TIPOFONDO", "CODCARGO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
