
  CREATE TABLE "SICAS_OC"."FAI_ESQUEMA_COMIS_FONDO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"CODASEGURADO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDFONDO" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"INDPRINCIPAL" VARCHAR2(1) NOT NULL ENABLE, 
	"NIVELCOMISION" NUMBER(10,0), 
	"PLANCOMISION" VARCHAR2(6), 
	"CODINCENTIVO" VARCHAR2(10), 
	 CONSTRAINT "PK_FAI_ESQUEMA_COMIS_FONDO" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "CODASEGURADO", "IDFONDO", "COD_AGENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_INTER_COMIS_FONDOS" FOREIGN KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
	  REFERENCES "SICAS_OC"."AGENTES" ("COD_AGENTE", "CODCIA", "CODEMPRESA") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_FAI_ESQUEMA_COMIS_FONDO" FOREIGN KEY ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "CODASEGURADO", "IDFONDO")
	  REFERENCES "SICAS_OC"."FAI_FONDOS_DETALLE_POLIZA" ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "CODASEGURADO", "IDFONDO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
