
  CREATE TABLE "SICAS_OC"."FAI_SERVICIOS_PORTAL" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDCONSULTASERVICIO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODSERVICIO" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHACONSULTA" DATE NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30), 
	"XMLCONSULTA" "SYS"."XMLTYPE" , 
	 CONSTRAINT "PK_FAI_SERVICIOS_PORTAL" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDCONSULTASERVICIO", "CODSERVICIO", "FECHACONSULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 XMLTYPE COLUMN "XMLCONSULTA" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA 
