
  CREATE TABLE "SICAS_OC"."FECHA_CONTABLE_EQUIVALENTE" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"FECHAREAL" DATE NOT NULL ENABLE, 
	"FECHACONTABLE" DATE NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "PK_FECHA_CONTABLE_EQUIVALENTE" PRIMARY KEY ("CODCIA", "CODEMPRESA", "FECHAREAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_FECHA_CONT_EQUIV_EMP" FOREIGN KEY ("CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."EMPRESAS_DE_SEGUROS" ("CODEMPRESA", "CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
