
  CREATE TABLE "SICAS_OC"."FILIALES_CATEGORIAS" 
   (	"CODCATEGORIA" VARCHAR2(20) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODGRUPOEC" VARCHAR2(20) NOT NULL ENABLE, 
	"CODFILIAL" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(50), 
	"ESTADO" VARCHAR2(6), 
	 CONSTRAINT "PK_FILIALES_CATEGORIAS" PRIMARY KEY ("CODCIA", "CODGRUPOEC", "CODFILIAL", "CODCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_CATEGORIAS_FILIALES" FOREIGN KEY ("CODFILIAL", "CODCIA", "CODGRUPOEC")
	  REFERENCES "SICAS_OC"."FILIALES" ("CODFILIAL", "CODCIA", "CODGRUPOEC") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
