--DROP TABLE SICAS_OC.FILTRAR_POLIZAS_SESAS
--/

--
-- FILTRAR_POLIZAS_SESAS  (Table)
--
CREATE TABLE SICAS_OC.FILTRAR_POLIZAS_SESAS
(
  CODCIA         NUMBER(14)      NOT NULL,
  CODEMPRESA     NUMBER(14)      NOT NULL,
  PROCESOSESAS   VARCHAR2(100)   NOT NULL,
  SECUENCIA      NUMBER          NOT NULL,
  IDPOLIZA       NUMBER(14),
  OBSERVACION    VARCHAR2(4000),
  FECHACARGA     DATE,
  USUARIOCARGA   VARCHAR2(100)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.FILTRAR_POLIZAS_SESAS IS 'Pólizas a Filtrar para la Generación de las SESAS'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.CODCIA IS 'Código de Compañía'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.CODEMPRESA IS 'Código de Empresa'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.PROCESOSESAS IS 'Nombre del Archivo de SESAS a generar'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.SECUENCIA IS 'Número secuencial de la póliza a filtrar'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.IDPOLIZA IS 'No. de Póliza'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.OBSERVACION IS 'Observaciones de la carga'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.FECHACARGA IS 'Fecha en que se cargo la póliza'
/

COMMENT ON COLUMN SICAS_OC.FILTRAR_POLIZAS_SESAS.USUARIOCARGA IS 'Usuario que realizó la carga'
/

--
-- FILTRAR_POLIZAS_SESAS_PK  (Index) 
--
--  Dependencies: 
--   FILTRAR_POLIZAS_SESAS (Table)
--
CREATE UNIQUE INDEX SICAS_OC.FILTRAR_POLIZAS_SESAS_PK ON SICAS_OC.FILTRAR_POLIZAS_SESAS
( CODCIA, CODEMPRESA, PROCESOSESAS, SECUENCIA )
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


--
-- FILTRAR_POLIZAS_SESAS  (Synonym) 
--
--  Dependencies: 
--   FILTRAR_POLIZAS_SESAS (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM FILTRAR_POLIZAS_SESAS FOR SICAS_OC.FILTRAR_POLIZAS_SESAS
/


-- 
-- Non Foreign Key Constraints for Table FILTRAR_POLIZAS_SESAS 
-- 
ALTER TABLE SICAS_OC.FILTRAR_POLIZAS_SESAS ADD (
  CONSTRAINT FILTRAR_POLIZAS_SESAS_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, PROCESOSESAS, SECUENCIA )
  USING INDEX SICAS_OC.FILTRAR_POLIZAS_SESAS_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FILTRAR_POLIZAS_SESAS TO PUBLIC
/
