
  CREATE TABLE "SICAS_OC"."FONDOS_RETIRO" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDNEGOCIO" VARCHAR2(6), 
	"IDSINIESTRO" NUMBER(14,0), 
	"NOM_JUBILADO" VARCHAR2(300), 
	"ID_RFC" VARCHAR2(20), 
	"ID_EMPLEADO" VARCHAR2(20), 
	"FEC_PAGO_FINIQUITO" DATE, 
	"FEC_NOTIFICACION" DATE, 
	"FEC_BAJA" DATE, 
	"IMPTE_PAGO" NUMBER(18,2), 
	"USUARIO_REGISTRO" VARCHAR2(30), 
	"FECHAREGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
