
  CREATE TABLE "SICAS_OC"."FONDEO" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDDETSIN" NUMBER(14,0), 
	"NUM_APROBACION" NUMBER(14,0), 
	"BENEF" NUMBER(5,0), 
	"NUM_CHEQUE" NUMBER(14,0), 
	"NUM_REFERENCIA" VARCHAR2(40), 
	"IDTIPO_PAGO" VARCHAR2(6), 
	"FEC_PAGO_MOVTO" DATE, 
	"FEC_PAGO_REAL" DATE, 
	"ID_GRUPO_FONDEO" NUMBER(5,0), 
	"ST_FONDEO" VARCHAR2(6), 
	"FEC_FONDEO" DATE, 
	"USUARIO_FONDEO" VARCHAR2(30), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"ST_FINIQUITO" VARCHAR2(6), 
	"FEC_REGISTRO" DATE, 
	"USUARIO_REGISTRO" VARCHAR2(30), 
	"FEC_IMPRESION" DATE, 
	"USUARIO_IMPRESION" VARCHAR2(30), 
	"MOTIVO_RECHAZO" VARCHAR2(100), 
	"FEC_PAGO_PROGRAMADA" DATE, 
	"IDPROC" NUMBER(14,0), 
	"IDRAMO" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
