
  CREATE TABLE "SICAS_OC"."FORMAS_PAGO_AGENTES" 
   (	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(18,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(18,0) NOT NULL ENABLE, 
	"FORMPAGO" VARCHAR2(6) NOT NULL ENABLE, 
	"ENTFINAN" VARCHAR2(6) NOT NULL ENABLE, 
	"NUM_CUENTA" VARCHAR2(20) NOT NULL ENABLE, 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"INDPRINCIPAL" VARCHAR2(1) NOT NULL ENABLE, 
	 PRIMARY KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA", "FORMPAGO", "ENTFINAN", "NUM_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
	  REFERENCES "SICAS_OC"."AGENTES" ("COD_AGENTE", "CODCIA", "CODEMPRESA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
