
  CREATE TABLE "SICAS_OC"."FZ_GARANTIA" 
   (	"CODIGO" VARCHAR2(50) NOT NULL ENABLE, 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6) NOT NULL ENABLE, 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPOGARANTIA" VARCHAR2(6), 
	"MONTOLOCAL" NUMBER(18,2), 
	"MONTOMONEDA" NUMBER(18,2), 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"INICIO_VIGENCIA" DATE, 
	"FIN_VIGENCIA" DATE, 
	"DESCRIPCION" LONG NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(3), 
	"CODCONTRATO" VARCHAR2(50), 
	"FECSTS" DATE, 
	 PRIMARY KEY ("CODIGO", "TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
