
  CREATE TABLE "SICAS_OC"."FZ_PROYECTO" 
   (	"CODPROYECTO" VARCHAR2(50) NOT NULL ENABLE, 
	"CODBENEFICIARIOFZ" NUMBER(10,0) NOT NULL ENABLE, 
	"FECAPERTURACLICAS" DATE, 
	"OBJETO" LONG, 
	"MONTOOFERTADOLOCAL" NUMBER(18,2), 
	"MONTOOFERTADOMONEDA" NUMBER(18,2), 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(3), 
	 PRIMARY KEY ("CODPROYECTO", "COD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
