CREATE SEQUENCE SICAS_OC.SEQ_HIS_LISTAS_CNSF
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCYCLE
    ORDER;

CREATE TABLE SICAS_OC.HIS_LISTAS_CNSF(
    IDPROCESO       NUMBER ,    --1 REFIERE A LISTAS NEGRAS DE CNSF
    IDCONSEC        NUMBER  DEFAULT SICAS_OC.SEQ_HIS_LISTAS_CNSF.NEXTVAL,
    NOMBRE          VARCHAR2(1000),
    TIPOPERSONA     VARCHAR2(20),
    LISTAORIGEN     VARCHAR2(15),
    DESCRIPCION     VARCHAR2(4000),
    TIPOMOVIMIENTO  VARCHAR2(5),
    FECHAINSERT     DATE DEFAULT SYSDATE,
    USRINSERT       VARCHAR2(20) DEFAULT USER,
    FECHAUPDATE     DATE,
    USRUPDATE       VARCHAR2(20)
    );

CREATE UNIQUE INDEX SICAS_OC.IDX_HIS_LISTAS_CNSF_1 ON
    SICAS_OC.HIS_LISTAS_CNSF(IDPROCESO,IDCONSEC);

ALTER TABLE SICAS_OC.HIS_LISTAS_CNSF ADD(
    CONSTRAINT PK_HIS_LISTAS_CNSF
    PRIMARY KEY (IDPROCESO,IDCONSEC)
    USING INDEX SICAS_OC.IDX_HIS_LISTAS_CNSF_1);

GRANT SELECT,INSERT,DELETE,UPDATE ON SICAS_OC.HIS_LISTAS_CNSF TO ROL_MODIFICA_SICAS,ROL_CONSULTA_SICAS;

CREATE OR REPLACE PUBLIC SYNONYM SEQ_HIS_LISTAS_CNSF FOR SICAS_OC.SEQ_HIS_LISTAS_CNSF;

CREATE OR REPLACE PUBLIC SYNONYM HIS_LISTAS_CNSF FOR SICAS_OC.HIS_LISTAS_CNSF;