
  CREATE TABLE "SICAS_OC"."INFO_ALTCOM" 
   (	"ID_CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"NU_REMESA" VARCHAR2(30) NOT NULL ENABLE, 
	"ID_CREDITO_THONA" VARCHAR2(30) NOT NULL ENABLE, 
	"ID_POLIZA" VARCHAR2(10) NOT NULL ENABLE, 
	"ID_ENDOSO" NUMBER(7,0) NOT NULL ENABLE, 
	"ID_ASEGURADORA" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CREDITO" NUMBER(12,0) NOT NULL ENABLE, 
	"ID_TRABAJADOR" NUMBER(12,0) NOT NULL ENABLE, 
	"PATERNO" VARCHAR2(30), 
	"MATERNO" VARCHAR2(30), 
	"NOMBRE" VARCHAR2(30), 
	"SEGUNDO_NOMBRE" VARCHAR2(30), 
	"NOMBRE_COMPLETO" VARCHAR2(150), 
	"FE_NACIMIENTO" DATE, 
	"SEXO" VARCHAR2(1), 
	"RFC_TRABAJADOR" VARCHAR2(13), 
	"SALDO_INSOLUTO" NUMBER(15,2), 
	"FE_INICIO" DATE, 
	"PLAZO" NUMBER(5,0), 
	"TAZA_INTERES" NUMBER(11,7), 
	"TIPO_MOVIMIENTO" VARCHAR2(1), 
	"PRIMA" NUMBER(15,2), 
	"CUOTA" NUMBER(15,2), 
	"EMPRESA" VARCHAR2(150), 
	"ID_CENTRO_TRA" NUMBER(15,0), 
	"TIPO_SEG_SOCIAL" NUMBER(1,0), 
	"NUM_SEG_SOCIAL" VARCHAR2(11), 
	"PRODUCTO" NUMBER(10,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"TAZA_INTE_MENS" NUMBER(18,7), 
	"PAGO_MENS" NUMBER(18,7), 
	"FE_CARGA" DATE, 
	"ST_REGISTRO" VARCHAR2(5), 
	"CODUSUARIO" VARCHAR2(30), 
	"CODERRORCARGA" VARCHAR2(10), 
	"CREDITO_ORIGEN" NUMBER(12,0), 
	 CONSTRAINT "INFO_ALTCOM_PK" PRIMARY KEY ("ID_CODCIA", "NU_REMESA", "ID_CREDITO_THONA", "ID_POLIZA", "ID_ENDOSO", "ID_ASEGURADORA", "ID_CREDITO", "ID_TRABAJADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
