
  CREATE TABLE "SICAS_OC"."INFO_SINCOM" 
   (	"ID_CODCIA" NUMBER(14,0), 
	"NU_REMESA" VARCHAR2(30), 
	"ID_CREDITO_THONA" VARCHAR2(30), 
	"ID_POLIZA" VARCHAR2(10), 
	"ID_ENDOSO" NUMBER(7,0), 
	"ID_ASEGURADORA" NUMBER(10,0), 
	"ID_CREDITO" NUMBER(12,0), 
	"ID_TRABAJADOR" NUMBER(12,0), 
	"PATERNO" VARCHAR2(30), 
	"MATERNO" VARCHAR2(30), 
	"NOMBRE" VARCHAR2(30), 
	"SEGUNDO_NOMBRE" VARCHAR2(30), 
	"FE_NACIMIENTO" DATE, 
	"SEXO" VARCHAR2(1), 
	"RFC_TRABAJADOR" VARCHAR2(13), 
	"IMPORTE" NUMBER(15,2), 
	"EMPRESA" VARCHAR2(150), 
	"DOMICILIO_CT" VARCHAR2(250), 
	"TEL_PRINCIPAL" VARCHAR2(22), 
	"TEL_CEL" VARCHAR2(22), 
	"TIPO_SEG_SOCIAL" NUMBER(1,0), 
	"NUM_SEG_SOCIAL" VARCHAR2(11), 
	"SUCURSAL" VARCHAR2(4), 
	"PRODUCTO" NUMBER(10,0), 
	"COBERTURA" NUMBER(1,0), 
	"ID_ENVIO" NUMBER(10,0), 
	"REF_BANCA" VARCHAR2(25), 
	"FECHA_BAJA" DATE, 
	"SINIESTRO" VARCHAR2(100), 
	"FECHA_SINIESTRO" DATE, 
	"MENSUALIDAD" VARCHAR2(100), 
	"OBS_SINIESTRO" VARCHAR2(100), 
	"CVE_NO_PAGO" VARCHAR2(100), 
	"ENVIO_ACTA_DEF" VARCHAR2(100), 
	"ENVIO_DICTAMEN_INV" VARCHAR2(100), 
	"REF_BANCA_PAGO" VARCHAR2(25), 
	"FECHA_PAGO" DATE, 
	"FE_CARGA" DATE, 
	"ST_REGISTRO" VARCHAR2(5), 
	"CODUSUARIO" VARCHAR2(30), 
	"CODERRORCARGA" VARCHAR2(10), 
	"TIPOPROCESO" VARCHAR2(30), 
	"ID_ENVIO_PAGO" NUMBER(10,0), 
	"OBSERVACIONES_ADI" VARCHAR2(200), 
	"ERROR_INICIAL" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
