
  CREATE TABLE "SICAS_OC"."INSPECCION" 
   (	"NUM_INSPECCION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_VEHI" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"ENCARGADO" VARCHAR2(200), 
	"FECREQUI" DATE NOT NULL ENABLE, 
	"OBSERVACIONES" LONG, 
	"CODCIA" NUMBER(14,0), 
	 PRIMARY KEY ("NUM_INSPECCION", "IDETPOL", "NUM_VEHI", "IDPOLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
