
  CREATE TABLE "SICAS_OC"."LOG_TRANSACCION" 
   (	"ID_TRANSACCION" NUMBER(14,0) CONSTRAINT "SYS_C007130" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0), 
	"ID_REFERENCIA" VARCHAR2(50), 
	"FECHA_TRANSACCION" DATE, 
	"DIRECCION_IP" VARCHAR2(50), 
	"NUM_REFERENCIA" VARCHAR2(50), 
	"ORIGEN_TRANSACCION" VARCHAR2(150), 
	"DESC_MOVIMIENTO" VARCHAR2(1000), 
	"CODUSUARIO" VARCHAR2(30), 
	 PRIMARY KEY ("ID_TRANSACCION", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
