CREATE SEQUENCE SICAS_OC.SEQ_LOGERRSESAS
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    ORDER;
/

CREATE TABLE SICAS_OC.LOGERRORES_SESAS (
    CODCIA          NUMBER          NOT NULL,
    CODEMPRESA      NUMBER          NOT NULL,
    CODUSUARIO      VARCHAR2(30)    NOT NULL,
    CODREPORTE      VARCHAR2(30)    NOT NULL,
    IDSECUENCIA     NUMBER          DEFAULT SICAS_OC.SEQ_LOGERRSESAS.NEXTVAL,
    EPOLIZ       	VARCHAR2(100),
    ECERTI  		VARCHAR2(500),
    CODERR        	NUMBER,
    DESCER       	VARCHAR2(4000),
    FECREG   		DATE            DEFAULT SYSDATE,
    USUARIOREGISTRO VARCHAR2(30)    DEFAULT USER,
    FECHAINSERT     DATE        	DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

CREATE UNIQUE INDEX SICAS_OC.IX_LOGERRSESAS ON
    SICAS_OC.LOGERRORES_SESAS(CODCIA,CODEMPRESA,CODUSUARIO,CODREPORTE,IDSECUENCIA)
    TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.LOGERRORES_SESAS ADD(
    CONSTRAINT PK_LOGERRSESAS
    PRIMARY KEY (CODCIA,CODEMPRESA,CODUSUARIO,CODREPORTE,IDSECUENCIA)
    USING INDEX SICAS_OC.IX_LOGERRSESAS);
/

CREATE INDEX SICAS_OC.IX_LOGERRSESAPOLI ON
    SICAS_OC.LOGERRORES_SESAS(EPOLIZ,ECERTI)
    TABLESPACE IDX_SICASOC;
/

CREATE INDEX SICAS_OC.IX_LOGERRFECHASESA ON
    SICAS_OC.LOGERRORES_SESAS(FECREG)
    TABLESPACE IDX_SICASOC;
/

COMMENT ON TABLE SICAS_OC.LOGERRORES_SESAS IS 'Tabla de sesas que se registraron con error';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.CODUSUARIO IS 'Código del Usuario que Genera el Reporte';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.CODREPORTE IS 'Código del Reporte';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.IDSECUENCIA IS 'Consecutivo del registro unico';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.EPOLIZ IS 'Número de póliza que se registro con error';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.ECERTI IS 'Número del ECERTIicado que se registro con error';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.CODERR IS 'Codigo de error que se reporto';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.DESCER IS 'Descripción del error que se reporto';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.FECREG IS 'Fecha de registro';
COMMENT ON COLUMN SICAS_OC.LOGERRORES_SESAS.USUARIOREGISTRO IS 'Usuario con el que se registro el evento';


CREATE OR REPLACE PUBLIC SYNONYM SEQ_LOGERRSESAS FOR SICAS_OC.SEQ_LOGERRSESAS;
/

CREATE OR REPLACE PUBLIC SYNONYM LOGERRORES_SESAS FOR SICAS_OC.LOGERRORES_SESAS;
/

GRANT INSERT,UPDATE,DELETE,SELECT ON SICAS_OC.LOGERRORES_SESAS TO PUBLIC;
/
