
  CREATE TABLE "SICAS_OC"."MODELO" 
   (	"COD_MARCA" VARCHAR2(10) CONSTRAINT "SYS_C007135" NOT NULL ENABLE, 
	"COD_MODELO" VARCHAR2(10) CONSTRAINT "SYS_C007136" NOT NULL ENABLE, 
	"DESC_MODELO" VARCHAR2(100), 
	 PRIMARY KEY ("COD_MARCA", "COD_MODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("COD_MARCA")
	  REFERENCES "SICAS_OC"."MARCA" ("COD_MARCA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
