
  CREATE TABLE "SICAS_OC"."MONEDA" 
   (	"COD_MONEDA" VARCHAR2(5) CONSTRAINT "SYS_C007138" NOT NULL ENABLE, 
	"DESC_MONEDA" VARCHAR2(100), 
	"CODALTERNO" VARCHAR2(5), 
	"CODSISTCONT" VARCHAR2(5), 
	"CODFACTELECT" VARCHAR2(5), 
	"CVE_CNSF" VARCHAR2(15), 
	"DESC_CNSF" VARCHAR2(300), 
	 PRIMARY KEY ("COD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
