
  CREATE TABLE "SICAS_OC"."MONITOR" 
   (	"PROCESO" NUMBER(14,0), 
	"IDPROCMASIVO" NUMBER(14,0), 
	"PROGRAMA" VARCHAR2(100), 
	"PASO" NUMBER(10,2), 
	"TIEMPO" TIMESTAMP (6), 
	"FECHA" DATE, 
	"EXTRA" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
