
  CREATE TABLE "SICAS_OC"."NCR_FACTEXT" 
   (	"IDEFACTEXT" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDNCR" NUMBER(14,0) NOT NULL ENABLE, 
	"FECENTREGA" DATE, 
	"ESTADO" VARCHAR2(6), 
	"OBSERVACIONES" VARCHAR2(4000), 
	"UUID" VARCHAR2(40) DEFAULT 'eeeeeeee-0000-eeee-0000-eeeeee000000' NOT NULL ENABLE, 
	"INDPREVFIS" VARCHAR2(1) DEFAULT 'N', 
	 CONSTRAINT "PK_NCR_FACTEXT" PRIMARY KEY ("CODCIA", "IDEFACTEXT", "TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "IDNCR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_NCRFACTEXT_NOTACRED" FOREIGN KEY ("IDNCR", "CODCIA")
	  REFERENCES "SICAS_OC"."NOTAS_DE_CREDITO" ("IDNCR", "CODCIA") ENABLE, 
	 CONSTRAINT "FK_NCRFACTEXT_FACTEXT" FOREIGN KEY ("IDEFACTEXT", "TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "UUID")
	  REFERENCES "SICAS_OC"."FACTURA_EXTERNA" ("IDEFACTEXT", "TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "UUID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
