
  CREATE TABLE "SICAS_OC"."NIVELES_AUTORIZACION" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDEMPLEADO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODUSUARIOBD" VARCHAR2(30), 
	"IDEMPLEADOSUPERIOR" NUMBER(14,0), 
	"INDAUTORIZA" VARCHAR2(2) DEFAULT 'N', 
	"STSEMPLEADO" VARCHAR2(6), 
	"FECSTSEMPLEADO" DATE, 
	 CONSTRAINT "PK_NIVELES_AUTORIZACION" PRIMARY KEY ("CODCIA", "IDEMPLEADO", "CODUSUARIOBD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_NIVEL_USUARIO" FOREIGN KEY ("CODCIA")
	  REFERENCES "SICAS_OC"."EMPRESAS" ("CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
