
  CREATE TABLE "SICAS_OC"."NIVEL" 
   (	"CODNIVEL" NUMBER(10,0) CONSTRAINT "SYS_C0028103" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C0028102" NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(50), 
	"JERARQUIA" NUMBER(2,0), 
	"ESTADO" VARCHAR2(6), 
	"PREFIJOUSUARIOWEB" VARCHAR2(10), 
	 PRIMARY KEY ("CODCIA", "CODNIVEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCIA")
	  REFERENCES "SICAS_OC"."EMPRESAS" ("CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
