
  CREATE TABLE "SICAS_OC"."NIVELES_AUTORIZACION_GRUPO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDEMPLEADO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODGRUPO" VARCHAR2(8) NOT NULL ENABLE, 
	"MONTOMINIMOAUTORIZADO" NUMBER(28,2) NOT NULL ENABLE, 
	"MONTOMAXIMOAUTORIZADO" NUMBER(28,2) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30), 
	"FECCONFIGURADO" DATE, 
	 CONSTRAINT "PK_NIVELES_AUTORIZACION_GRUPO" PRIMARY KEY ("CODCIA", "CODGRUPO", "IDEMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_NIVEL_GRUPO_AUTORIZA" FOREIGN KEY ("CODGRUPO", "CODCIA")
	  REFERENCES "SICAS_OC"."GRUPOS_DE_USUARIOS" ("CODGRUPO", "CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
