
  CREATE TABLE "SICAS_OC"."NOMINA_COMISIONES" 
   (	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(18,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(18,0) NOT NULL ENABLE, 
	"NOMINA_PAGO" VARCHAR2(20) NOT NULL ENABLE, 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"STSNOMPAGO" VARCHAR2(3) NOT NULL ENABLE, 
	"FECSTS" DATE NOT NULL ENABLE, 
	"INGRESOS" NUMBER(18,2) NOT NULL ENABLE, 
	"DEDUCCIONES" NUMBER(18,2), 
	"LIQUIDO" NUMBER(18,2) NOT NULL ENABLE, 
	"FORMPAGO" VARCHAR2(6), 
	"ENTFINAN" VARCHAR2(6), 
	"NUM_CUENTA" VARCHAR2(20), 
	"NUM_DOCPAGO" VARCHAR2(20), 
	"FEC_PAGO" DATE, 
	 PRIMARY KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA", "NOMINA_PAGO", "COD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
	  REFERENCES "SICAS_OC"."AGENTES" ("COD_AGENTE", "CODCIA", "CODEMPRESA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
