
  CREATE TABLE "SICAS_OC"."NOTAS_DE_CREDITO" 
   (	"IDNCR" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"CODCLIENTE" NUMBER(14,0), 
	"NUMNCR" VARCHAR2(30), 
	"FECDEVOL" DATE NOT NULL ENABLE, 
	"MONTO_NCR_LOCAL" NUMBER(18,2) NOT NULL ENABLE, 
	"MONTO_NCR_MONEDA" NUMBER(18,2), 
	"STSNCR" VARCHAR2(3), 
	"FECSTS" DATE, 
	"FECANUL" DATE, 
	"MOTIVANUL" VARCHAR2(6), 
	"IDENDOSO" NUMBER(14,0), 
	"MTOCOMISI_LOCAL" NUMBER(18,2), 
	"MTOCOMISI_MONEDA" NUMBER(18,2), 
	"COMISPAGADA_LOCAL" NUMBER(18,2), 
	"COMISPAGADA_MONEDA" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6), 
	"CODTIPODOC" VARCHAR2(30), 
	"COD_AGENTE" NUMBER(18,0), 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"SALDO_NCR_LOCAL" NUMBER(18,2), 
	"SALDO_NCR_MONEDA" NUMBER(18,2), 
	"IDTRANSACCION" NUMBER(18,0), 
	"IDNCRPOL" NUMBER(14,0), 
	"IDNOMINA" NUMBER(14,0), 
	"CODMONEDA" VARCHAR2(5), 
	"CTALIQUIDADORA" VARCHAR2(6), 
	"IDTRANSACCIONANU" NUMBER(14,0), 
	"IDTRANSACAPLIC" NUMBER(14,0), 
	"INDFACTELECTRONICA" VARCHAR2(1) DEFAULT 'N', 
	"FECENVFACTELEC" DATE, 
	"CODUSUARIOENVFACT" VARCHAR2(30), 
	"FOLIOFACTELEC" VARCHAR2(30), 
	"FECENVFACTELECANU" DATE, 
	"CODUSUARIOENVFACTANU" VARCHAR2(30), 
	"LOGPROCESOFACTELEC" VARCHAR2(4000), 
	"IDTRANSACREVAPLIC" NUMBER(14,0), 
	"NUMPRESTAMO" NUMBER(14,0), 
	"FECFINVIG" DATE, 
	"CODPLANPAGO" VARCHAR2(4), 
	"IDNCRREHAB" NUMBER(14,0), 
	"ID_AÑO_POLIZA" NUMBER(4,0), 
	"CVE_MOTIVCANCFACT" VARCHAR2(30), 
	 CONSTRAINT "PK_NOTA_CRED" PRIMARY KEY ("IDNCR", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("IDNCRPOL", "IDPOLIZA", "CODCIA")
	  REFERENCES "SICAS_OC"."NOTAS_DE_CREDITO_POLIZA" ("IDNCRPOL", "IDPOLIZA", "CODCIA") ENABLE, 
	 FOREIGN KEY ("IDPOLIZA", "IDETPOL", "CODCIA")
	  REFERENCES "SICAS_OC"."DETALLE_POLIZA" ("IDPOLIZA", "IDETPOL", "CODCIA") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
