
  CREATE TABLE "SICAS_OC"."NOTAS_DE_CREDITO_POLIZA" 
   (	"IDNCRPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"NUMNCR" VARCHAR2(30), 
	"FECDEVOL" DATE NOT NULL ENABLE, 
	"MONTO_NCR_LOCAL" NUMBER(18,2), 
	"MONTO_NCR_MONEDA" NUMBER(18,2), 
	"STSNCR" VARCHAR2(3), 
	"FECSTS" DATE, 
	"FECANUL" DATE, 
	"MOTIVANUL" VARCHAR2(6), 
	"IDENDOSO" NUMBER(14,0), 
	"MTOCOMISI_LOCAL" NUMBER(18,2), 
	"MTOCOMISI_MONEDA" NUMBER(18,2), 
	"COMISPAGADA_LOCAL" NUMBER(18,2), 
	"COMISPAGADA_MONEDA" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6), 
	"CODTIPODOC" NUMBER(10,0), 
	"COD_AGENTE" NUMBER(18,0), 
	 PRIMARY KEY ("IDNCRPOL", "IDPOLIZA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
