CREATE TABLE SICAS_OC.OCUPACION_SESAS (
    CODREPORTE          VARCHAR2(30)    NOT NULL,
    CLAVESESA           VARCHAR2(10),
    ACTIVIDAD           VARCHAR2(500),
    CODACTIVIDAD        VARCHAR2(35),
    DESCRIPCION         VARCHAR2(500),
    FECREG              DATE            DEFAULT SYSDATE,
    USUARIOREGISTRO     VARCHAR2(30)    DEFAULT USER,
    FECHAINSERT         DATE            DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

CREATE UNIQUE INDEX SICAS_OC.IX_OCUPASESAS ON
    SICAS_OC.OCUPACION_SESAS(CODREPORTE,CODACTIVIDAD,CLAVESESA)
    TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.OCUPACION_SESAS ADD(
    CONSTRAINT PK_OCUPASESAS
    PRIMARY KEY (CODREPORTE,CODACTIVIDAD,CLAVESESA)
    USING INDEX SICAS_OC.IX_OCUPASESAS);
/


COMMENT ON TABLE SICAS_OC.OCUPACION_SESAS IS 'Tabla de sesas que almacena las ocupaciones para sesas de AP';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.CODREPORTE IS 'Codigo del Reporte';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.CODACTIVIDAD IS 'CLAVE DE LA ACTIVIDAD REGISTRADA EN PERSONA NATURAL JURIDICA';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.CLAVESESA IS 'CLAVE A RETORNAR EN LA SESAS';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.DESCRIPCION IS 'DESCRIPCION DEL CATALOGO';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.FECREG IS 'Fecha de registro';
COMMENT ON COLUMN SICAS_OC.OCUPACION_SESAS.USUARIOREGISTRO IS 'Usuario con el que se registro el evento';


CREATE OR REPLACE PUBLIC SYNONYM SEQ_OCUPASESAS FOR SICAS_OC.SEQ_OCUPASESAS;
/

CREATE OR REPLACE PUBLIC SYNONYM OCUPACION_SESAS FOR SICAS_OC.OCUPACION_SESAS;
/

GRANT INSERT,UPDATE,DELETE,SELECT ON SICAS_OC.OCUPACION_SESAS TO PUBLIC;
/
