
  CREATE TABLE "SICAS_OC"."OPERACION_CONTABLE" 
   (	"IDEOPECONTABLE" NUMBER(14,0) NOT NULL ENABLE, 
	"NOMBREOPECONTABLE" VARCHAR2(100) NOT NULL ENABLE, 
	"STSOPECONTABLE" VARCHAR2(3) NOT NULL ENABLE, 
	"FECSTS" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("IDEOPECONTABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
