
  CREATE TABLE "SICAS_OC"."PAGOS" 
   (	"IDRECIBO" NUMBER(18,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_RECIBO_REF" VARCHAR2(20), 
	"FECHA" DATE, 
	"OPERADO" VARCHAR2(30), 
	"MONTO" NUMBER(18,2), 
	"TASA_CAMBIO" NUMBER(18,6), 
	"MONEDA" VARCHAR2(6) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDTRANSACCION" NUMBER(18,0), 
	"FORMPAGO" VARCHAR2(6), 
	"NUMDOC" VARCHAR2(30), 
	"IDTRANSACCIONANU" NUMBER(14,0), 
	"FECANULACION" DATE, 
	 CONSTRAINT "PK_PAGOS_FACT" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDRECIBO", "IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "UK_RECIBO" UNIQUE ("IDRECIBO", "IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
