
  CREATE TABLE "SICAS_OC"."PAGOS_POR_OTROS_CONCEPTOS" 
   (	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETSIN" NUMBER(14,0) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(6), 
	"MONTO_PAGO_LOCAL" NUMBER(18,2), 
	"MONTO_PAGO_MONEDA" NUMBER(18,2), 
	"MONTO_RESERVADO_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVADO_MONEDA" NUMBER(18,2), 
	"STSPAGO" VARCHAR2(3), 
	 PRIMARY KEY ("IDSINIESTRO", "IDPOLIZA", "IDDETSIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
