
  CREATE TABLE "SICAS_OC"."PAGOS_FACTURA" 
   (	"NUM_PAGO" NUMBER(18,0) NOT NULL ENABLE, 
	"NUM_REF_PAGO" VARCHAR2(20), 
	"FECHA_PAGO" DATE, 
	"FECHA_ANUL" DATE, 
	"STS_PAG" VARCHAR2(20), 
	"OPERADO" VARCHAR2(10), 
	"CAMPO1" VARCHAR2(30), 
	"CAMPO2" VARCHAR2(30), 
	"CAMPO3" VARCHAR2(30), 
	 PRIMARY KEY ("NUM_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
