
  CREATE TABLE "SICAS_OC"."PAGO_COTIZACION" 
   (	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"NUM_COTIZACION" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCPTO" VARCHAR2(6), 
	"MONTO_CONCEPTO_LOCAL" NUMBER(18,2), 
	"MONTO_CONCEPTO_MONEDA" NUMBER(18,2), 
	"NOPAGO" NUMBER(2,0), 
	"FECHAPAGO" DATE, 
	 FOREIGN KEY ("NUM_COTIZACION", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."COTIZACION" ("NUM_COTIZACION", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
