
  CREATE TABLE "SICAS_OC"."PAGOS_MASIVOS_CUENTAS_AGENTES" 
   (	"CUENTA_CLABE" VARCHAR2(20) NOT NULL ENABLE, 
	"CUENTA_BANCARIA" VARCHAR2(16) NOT NULL ENABLE, 
	"CODENTIDADFINAN" VARCHAR2(3) NOT NULL ENABLE, 
	"ID_TPO_CTA" VARCHAR2(4) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(6), 
	"RFC" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMBRE_BENEFICIARIO" VARCHAR2(250) NOT NULL ENABLE, 
	"ALIAS_DE_LA_CUENTA" VARCHAR2(18), 
	"EMAIL" VARCHAR2(80), 
	"IMPORTE_MAXIMO_A_PAGAR" NUMBER(15,4), 
	"AGENTE" NUMBER(4,0), 
	"CUENTA_PREFERENTE" VARCHAR2(1), 
	"CAMPO1" NUMBER(12,4), 
	"CAMPO2" VARCHAR2(100), 
	"CAMPO3" DATE, 
	"CAMPO4" DATE, 
	 CONSTRAINT "PK_PAGMASIV" PRIMARY KEY ("CUENTA_CLABE", "CUENTA_BANCARIA", "RFC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
