
  CREATE TABLE "SICAS_OC"."PAGO_DETALLE" 
   (	"IDRECIBO" NUMBER(18,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCPTO" VARCHAR2(6) NOT NULL ENABLE, 
	"MONTO" NUMBER(18,2), 
	"IDTRANSACCION" NUMBER(18,0), 
	 PRIMARY KEY ("IDRECIBO", "IDFACTURA", "CODCPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_PAGO_IDRECIBO" FOREIGN KEY ("IDRECIBO", "IDFACTURA")
	  REFERENCES "SICAS_OC"."PAGOS" ("IDRECIBO", "IDFACTURA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
