
  CREATE TABLE "SICAS_OC"."PAGOS_REFERENCIADOS_REC" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPROCESO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETPAGOREF" NUMBER(14,0) NOT NULL ENABLE, 
	"REFERENCIA" VARCHAR2(20) NOT NULL ENABLE, 
	"FECHA_DEPOSITO" DATE, 
	"FORMA_PAGO" VARCHAR2(6), 
	"NUMERO_CIE" NUMBER(10,0), 
	"CONCEPTO" VARCHAR2(100), 
	"MONTO" NUMBER(18,2), 
	"INDCONCILIADO" VARCHAR2(1), 
	"INDAPLICADO" VARCHAR2(1), 
	"INDDUPLICADO" VARCHAR2(1), 
	 CONSTRAINT "PK_PAG_REF_REC" PRIMARY KEY ("CODCIA", "IDPROCESO", "IDDETPAGOREF", "REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
