
  CREATE TABLE "SICAS_OC"."PAQUETE_COMERCIAL" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDTIPOSEG" VARCHAR2(6 CHAR), 
	"PLANCOB" VARCHAR2(15 CHAR), 
	"CODPAQUETE" NUMBER(14,0) DEFAULT 0, 
	"DESCPAQUETE" VARCHAR2(250 CHAR), 
	"CODUSUARIO" VARCHAR2(30 CHAR) DEFAULT USER, 
	"FECHAMODIF" DATE DEFAULT SYSDATE, 
	"DOCUMENTO" BLOB DEFAULT EMPTY_BLOB(), 
	 CONSTRAINT "PAQUETE_COMERCIAL_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "DESCPAQUETE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("DOCUMENTO") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
