
  CREATE TABLE "SICAS_OC"."PARAMETROS_COBRO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CORRELATIVO" NUMBER(3,0) NOT NULL ENABLE, 
	"RANGO_INICIAL" NUMBER(10,0) NOT NULL ENABLE, 
	"RANGO_FINAL" NUMBER(10,0) NOT NULL ENABLE, 
	"BANCO" VARCHAR2(50) NOT NULL ENABLE, 
	"CONVENIO" VARCHAR2(50), 
	"REFERENCIA" VARCHAR2(50), 
	"NOMBRE_CONCEPTO" VARCHAR2(50), 
	"MONEDA" VARCHAR2(5), 
	 CONSTRAINT "PK_CON_COM" PRIMARY KEY ("CODCIA", "CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
