
  CREATE TABLE "SICAS_OC"."PARAMETROS_EMISION" 
   (	"PAEM_CD_PRODUCTO" NUMBER(6,0) NOT NULL ENABLE, 
	"PAEM_DES_PRODUCTO" VARCHAR2(100) NOT NULL ENABLE, 
	"PAEM_ID_PRODUCTO" NUMBER(6,0) NOT NULL ENABLE, 
	"PAEM_FE_ALTA" DATE NOT NULL ENABLE, 
	"PAEM_FLAG" NUMBER(3,0) NOT NULL ENABLE, 
	"PAEM_USUARIO" VARCHAR2(20) NOT NULL ENABLE, 
	"PAME_DS_NUMERADOR" VARCHAR2(100) NOT NULL ENABLE, 
	"PAEM_AUX1" VARCHAR2(200), 
	"PAEM_AUX2" VARCHAR2(200), 
	"PAEM_AUX3" DATE, 
	"PAEM_AUX4" DATE, 
	"PAEM_AUX5" NUMBER(13,2), 
	"PAEM_AUX6" NUMBER(13,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
