
  CREATE TABLE "SICAS_OC"."PARAMETROS_ENUM_SIN" 
   (	"PAEN_CD_SIN" NUMBER(6,0) NOT NULL ENABLE, 
	"PAEN_ID_SIN" NUMBER(6,0) NOT NULL ENABLE, 
	"PAEN_CONT_INI" NUMBER(9,0) NOT NULL ENABLE, 
	"PAEN_CONT_FIN" NUMBER(9,0) NOT NULL ENABLE, 
	"PAEN_FE_INI" DATE, 
	"PAEN_FE_FIN" DATE, 
	"PAEN_AUX1" VARCHAR2(200), 
	"PAEN_AUX2" VARCHAR2(200), 
	"PAEN_AUX3" DATE, 
	"PAEN_AUX4" DATE, 
	"PAEN_AUX5" NUMBER(13,2), 
	"PAEN_AUX6" NUMBER(13,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
