
  CREATE TABLE "SICAS_OC"."PASO_ASEGURADOS" 
   (	"ASEGURADO" NUMBER(12,0), 
	"SUMAASEG" NUMBER(12,2), 
	"CODCIA" NUMBER(2,0), 
	"IDPOLIZA" NUMBER(6,0), 
	"IDETPOL" NUMBER(3,0), 
	"CODCOBERT" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
