CREATE TABLE SICAS_OC.PERIODOS_POR_COBERTURA
(
    IDTIPOSEG         VARCHAR2(6 BYTE),
    PLANCOB           VARCHAR2(15 BYTE),
    CODCOBERT         VARCHAR2(6 BYTE),
    PERIODO_CARENCIA        NUMBER(12),
    PERIODO_ESPERA      NUMBER(12)
);
/

CREATE UNIQUE INDEX SICAS_OC.IDX_PERIODOS_POR_COBERTURA ON
    SICAS_OC.PERIODOS_POR_COBERTURA(IDTIPOSEG,PLANCOB,CODCOBERT);
/

ALTER TABLE SICAS_OC.PERIODOS_POR_COBERTURA ADD(
    CONSTRAINT PK_PERIODOS_POR_COBERTURA
    PRIMARY KEY (IDTIPOSEG,PLANCOB,CODCOBERT)
    USING INDEX SICAS_OC.IDX_PERIODOS_POR_COBERTURA);
/

GRANT SELECT,INSERT,DELETE,UPDATE ON SICAS_OC.PERIODOS_POR_COBERTURA TO ROL_MODIFICA_SICAS,ROL_CONSULTA_SICAS;
/

CREATE OR REPLACE PUBLIC SYNONYM PERIODOS_POR_COBERTURA FOR SICAS_OC.PERIODOS_POR_COBERTURA;
/


--Llenado de la tabla con todos los planes configurados
DECLARE

vIDTIPOSEG  VARCHAR2(100);
vPLANCOB    VARCHAR2(100);
vCODCOBERT  VARCHAR2(100);

CURSOR C1 IS
SELECT IDTIPOSEG, PLANCOB, CODCOBERT FROM COBERTURAS_DE_SEGUROS
WHERE IDTIPOSEG='GMPR2C'
ORDER BY 3;

BEGIN

OPEN C1;
  LOOP
    fetch C1 into vIDTIPOSEG, vPLANCOB, vCODCOBERT;
    exit when C1%notfound;

    INSERT INTO SICAS_OC.PERIODOS_POR_COBERTURA VALUES(vIDTIPOSEG, vPLANCOB, vCODCOBERT, 0,0);

  END LOOP;
  CLOSE C1;

  COMMIT;
END;

--Actualización de los periodos de acuerdo al layout

UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C1';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C2';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C3';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C4';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C5';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C6';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M1C7';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=0 WHERE CODCOBERT='M2C8';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=0 WHERE CODCOBERT='M2C9';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=0 WHERE CODCOBERT='M2C10';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M2C11';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M3C12';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M3C13';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M3C14';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M3C15';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M4C16';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M4C17';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =10, PERIODO_ESPERA=10 WHERE CODCOBERT='M4C18';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M4C19';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M4C20';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M4C21';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M4C22';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M4C23';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M5C24';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M5C25';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M5C26';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M5C27';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M5C28';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =24, PERIODO_ESPERA=24 WHERE CODCOBERT='M5C29';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C30';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C31';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C32';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C33';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C34';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C35';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C36';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C37';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C38';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C39';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C40';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M6C41';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C42';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C43';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C44';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C45';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C46';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C47';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=3 WHERE CODCOBERT='M7C48';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C49';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C50';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C51';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C52';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C53';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C54';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M7C55';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =9, PERIODO_ESPERA=9 WHERE CODCOBERT='M7C56';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=0 WHERE CODCOBERT='M7C57';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =9, PERIODO_ESPERA=9 WHERE CODCOBERT='M7C58';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =9, PERIODO_ESPERA=9 WHERE CODCOBERT='M7C59';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =9, PERIODO_ESPERA=9 WHERE CODCOBERT='M7C60';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M7C61';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M7C62';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =0, PERIODO_ESPERA=0 WHERE CODCOBERT='M8C63';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M8C64';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M8C65';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C66';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C67';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=0 WHERE CODCOBERT='M9C68';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C69';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=0 WHERE CODCOBERT='M9C70';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =1, PERIODO_ESPERA=3 WHERE CODCOBERT='M9C71';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C72';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M9C73';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M9C74';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C75';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M9C76';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C77';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M9C78';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C79';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C80';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C81';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C82';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C83';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C84';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =12, PERIODO_ESPERA=12 WHERE CODCOBERT='M9C85';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=0 WHERE CODCOBERT='M9C86';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M9C87';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=6 WHERE CODCOBERT='M9C88';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=0 WHERE CODCOBERT='M9C89';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =6, PERIODO_ESPERA=0 WHERE CODCOBERT='M9C90';
UPDATE SICAS_OC.PERIODOS_POR_COBERTURA SET PERIODO_CARENCIA =3, PERIODO_ESPERA=3 WHERE CODCOBERT='M9C91';

COMMIT;

--Query final de Jasper 

SELECT CBA.CODCIA, CBA.COD_ASEGURADO, CBA.CODEMPRESA, CBA.IDPOLIZA, CBA.IDETPOL, CBA.CODCOBERT, CBA.PLANCOB, CBA.IDTIPOSEG, 
TO_CHAR(CBA.SUMAASEG_MONEDA,'999,999,999,999.99') SUMAASEG_MONEDA,
CBA.SUMAASEG_LOCAL,
CBA.PRIMA_MONEDA, CBA.PRIMA_LOCAL, DEDUCIBLE_LOCAL,
OC_COBERTURAS_DE_SEGUROS.DESCRIPCION_COBERTURA(CBA.CODCIA, CBA.CODEMPRESA, CBA.IDTIPOSEG, CBA.PLANCOB, CBA.CODCOBERT) NOMBRECOBERTURA, ORDENIMPRESION,
PC.PERIODO_CARENCIA, PC.PERIODO_ESPERA
FROM COBERT_ACT_ASEG CBA
INNER JOIN COBERTURAS_DE_SEGUROS CS ON CS.CODCOBERT = CBA.CODCOBERT
INNER JOIN SICAS_OC.PERIODOS_POR_COBERTURA PC ON CBA.CODCOBERT = PC.CODCOBERT AND CBA.PLANCOB = PC.PLANCOB AND CBA.IDTIPOSEG = PC.IDTIPOSEG
AND CS.PLANCOB = CBA.PLANCOB
AND CS.IDTIPOSEG = CBA.IDTIPOSEG
AND CS.CODEMPRESA = CBA.CODEMPRESA
AND CS.CODCIA = CBA.CODCIA
AND CBA.CODCIA = 1
AND CBA.IDPOLIZA = $P{IDPOLIZA} 
AND CBA.IDETPOL = $P{IDETPOL} 
AND CBA.COD_ASEGURADO = $P{COD_ASEGURADO} 
UNION
SELECT CBA.CODCIA, CBA.COD_ASEGURADO, CBA.CODEMPRESA, CBA.IDPOLIZA, CBA.IDETPOL, CBA.CODCOBERT, CBA.PLANCOB, CBA.IDTIPOSEG, 
TO_CHAR(CBA.SUMAASEG_MONEDA,'999,999,999,999.99') SUMAASEG_MONEDA,
CBA.SUMAASEG_LOCAL,
CBA.PRIMA_MONEDA, CBA.PRIMA_LOCAL, DEDUCIBLE_LOCAL,
OC_COBERTURAS_DE_SEGUROS.DESCRIPCION_COBERTURA(CBA.CODCIA, CBA.CODEMPRESA, CBA.IDTIPOSEG, CBA.PLANCOB, CBA.CODCOBERT) NOMBRECOBERTURA, ORDENIMPRESION,
PC.PERIODO_CARENCIA, PC.PERIODO_ESPERA
FROM COBERT_ACT CBA 
INNER JOIN COBERTURAS_DE_SEGUROS CS ON CS.CODCOBERT = CBA.CODCOBERT
INNER JOIN SICAS_OC.PERIODOS_POR_COBERTURA PC ON CBA.CODCOBERT = PC.CODCOBERT AND CBA.PLANCOB = PC.PLANCOB AND CBA.IDTIPOSEG = PC.IDTIPOSEG
AND CS.PLANCOB = CBA.PLANCOB
AND CS.IDTIPOSEG = CBA.IDTIPOSEG
AND CS.CODEMPRESA = CBA.CODEMPRESA
AND CS.CODCIA = CBA.CODCIA
AND CBA.CODCIA = 1
AND CBA.IDPOLIZA = $P{IDPOLIZA} 
AND CBA.IDETPOL = $P{IDETPOL} 
AND CBA.COD_ASEGURADO = $P{COD_ASEGURADO} 
ORDER BY ORDENIMPRESION
;