
  CREATE TABLE "SICAS_OC"."PERSONAS_YOS" 
   (	"TIPO_DOC_IDENTIFICACION" VARCHAR2(30), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(30), 
	"NUM_CONSECUTIVO_YO" NUMBER(14,0), 
	"NOMBRE_COMERCIAL" VARCHAR2(100), 
	"DIRECCION_CALLE" VARCHAR2(100), 
	"NUM_EXTERIOR" VARCHAR2(5), 
	"NUM_INTERIOR" VARCHAR2(5), 
	"CODIGO_POSTAL" VARCHAR2(6), 
	"CODCOLONIA" VARCHAR2(6), 
	"CODESTADO" VARCHAR2(3), 
	"CODCIUDAD" VARCHAR2(3), 
	"CODMUNICIPIO" VARCHAR2(3), 
	"CODPAIS" VARCHAR2(3), 
	"TELEFONO" VARCHAR2(10), 
	"EMAIL" VARCHAR2(50), 
	 CONSTRAINT "PERSONAS_YOS_PK" PRIMARY KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "NUM_CONSECUTIVO_YO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
