
  CREATE TABLE "SICAS_OC"."PERSONAS_IDUNICOPERSONA" 
   (	"IDUNICOPERSONA" VARCHAR2(20), 
	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"TIPO_ID_TRIBUTARIA" VARCHAR2(6), 
	"NUM_TRIBUTARIO" VARCHAR2(20), 
	"CURP" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
