
  CREATE TABLE "SICAS_OC"."PLAN_DE_PAGOS" 
   (	"CODPLANPAGO" VARCHAR2(4) CONSTRAINT "SYS_C007172" NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) CONSTRAINT "SYS_C007174" NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C007175" NOT NULL ENABLE, 
	"DESCPLAN" VARCHAR2(100), 
	"NUMPAGOS" NUMBER(3,0) CONSTRAINT "SYS_C007173" NOT NULL ENABLE, 
	"FRECPAGOS" NUMBER(3,0), 
	"PORCINICIAL" NUMBER(9,6), 
	"STSPLAN" VARCHAR2(3), 
	"FECSTS" DATE, 
	"TIPOPAGO" VARCHAR2(2), 
	"INDPORCINIDINAMICO" VARCHAR2(1), 
	 CONSTRAINT "CK_TIPOPAGO" CHECK (tipopago in ('CO','CR')) ENABLE, 
	 PRIMARY KEY ("CODPLANPAGO", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."EMPRESAS_DE_SEGUROS" ("CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
