
  CREATE TABLE "SICAS_OC"."PLAN_COBERTURAS" 
   (	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"PLANCOB" VARCHAR2(15) NOT NULL ENABLE, 
	"DESC_PLAN" VARCHAR2(200) NOT NULL ENABLE, 
	"ULTMODPLAN" DATE, 
	"ESTADO_PLAN" VARCHAR2(6), 
	"CODUSUARIO" VARCHAR2(30), 
	"TIPPLANCOB" VARCHAR2(1), 
	"CODMONEDA" VARCHAR2(6), 
	"CODTIPOPLAN" VARCHAR2(6), 
	"COD_AGENTE" NUMBER(18,0), 
	"DIASRETROACTIVOS" NUMBER(15,0), 
	"MODALIDAD" VARCHAR2(6), 
	"PLANPOLIZA" VARCHAR2(6), 
	"INDISPUTABILIDAD" NUMBER(3,0), 
	"CODTEMPORALIDAD" VARCHAR2(6), 
	"INDAPLICASAMI" VARCHAR2(1), 
	"COMMINIMA" NUMBER(28,2), 
	"COMMAXIMA" NUMBER(28,2), 
	"PORCGTOADMIN" NUMBER(9,6), 
	"PORCGTOADQUI" NUMBER(9,6), 
	"PORCUTILIDAD" NUMBER(9,6), 
	"DIASRETROREN" NUMBER(15,0), 
	"DURACIONPLAN" NUMBER(5,0) DEFAULT 1, 
	"PORCDESCUENTO" NUMBER(9,6), 
	"PORCEXTRAPRIMA" NUMBER(9,6), 
	"MONTOEXTRAPRIMA" NUMBER(18,2), 
	"FACTORAJUSTE" NUMBER(9,6), 
	"MONTODEDUCIBLE" NUMBER(18,2), 
	"FACTFORMULADEDUC" NUMBER(12,8), 
	"PREFIJOPOL" VARCHAR2(6), 
	"DIASEXTRASCANCEL" NUMBER(5,0) DEFAULT 0, 
	"DIASSINPAGOFONDOS" NUMBER(5,0) DEFAULT 0, 
	"ID_LARGO_PLAZO" VARCHAR2(2) DEFAULT 'N', 
	"SUMA_ASEG_MAX" NUMBER(18,2), 
	 PRIMARY KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA", "PLANCOB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_PLAN_COBERTURAS_AGENTES" FOREIGN KEY ("COD_AGENTE", "CODCIA", "CODEMPRESA")
	  REFERENCES "SICAS_OC"."AGENTES" ("COD_AGENTE", "CODCIA", "CODEMPRESA") DISABLE, 
	 CONSTRAINT "FK_PLANES_TIPOS_SEGUROS" FOREIGN KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."TIPOS_DE_SEGUROS" ("IDTIPOSEG", "CODEMPRESA", "CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
