
  CREATE TABLE "SICAS_OC"."PLD_REP_OPERACIONES" 
   (	"CODCIA" NUMBER(14,0), 
	"IDOPERACION" NUMBER(20,0), 
	"CODTIPOREPORTE" VARCHAR2(6), 
	"ID_PERIODO" VARCHAR2(15), 
	"FOLIO" VARCHAR2(15), 
	"COD_ORGANO_SUPER" VARCHAR2(15), 
	"ID_OBLIGADO" VARCHAR2(15), 
	"ID_LOCALIDAD" VARCHAR2(15), 
	"ID_SUCURSAL" VARCHAR2(15), 
	"ID_TIP_OPERACION" VARCHAR2(15), 
	"COD_INSTRU_MONEDA" VARCHAR2(15), 
	"NUMPOLUNICO" VARCHAR2(30), 
	"NUMCUENTABANCARIA" VARCHAR2(30), 
	"ID_OPE_IMSS" VARCHAR2(30), 
	"MONTO" NUMBER(20,2), 
	"COD_MONEDA" VARCHAR2(15), 
	"FEC_OPERACION" DATE, 
	"COD_NACIONALIDAD" VARCHAR2(15), 
	"TIPO_PERSONA" VARCHAR2(6), 
	"RAZONSOCIAL" VARCHAR2(300), 
	"NOMBRE_REPORTADA" VARCHAR2(200), 
	"APE_PATERNO_REPORTADA" VARCHAR2(50), 
	"APE_MATERNO_REPORTADA" VARCHAR2(50), 
	"NUM_TRIBUTARIO" VARCHAR2(20), 
	"CURP" VARCHAR2(30), 
	"FECNACIMIENTO" VARCHAR2(200), 
	"DIRECRES" VARCHAR2(500), 
	"CODPAIS" VARCHAR2(3), 
	"CODESTADO" VARCHAR2(3), 
	"CODCIUDAD" VARCHAR2(3), 
	"CODMUNICIPIO" VARCHAR2(3), 
	"CODIGO_POSTAL" VARCHAR2(30), 
	"CODIGO_COLONIA" VARCHAR2(6), 
	"TELRES" VARCHAR2(30), 
	"CODACTIVIDAD" VARCHAR2(10), 
	"NOM_AGE_APO" VARCHAR2(200), 
	"APE_PATERNO_AGE_APO" VARCHAR2(50), 
	"APE_MATERNO_AGE_APO" VARCHAR2(50), 
	"NUM_TRIBUTARIO_AGE_APO" VARCHAR2(20), 
	"CURP_AGE_APO" VARCHAR2(30), 
	"NUM_CONSECUTIVO" VARCHAR2(15), 
	"CVE_OBLIGADO" VARCHAR2(15), 
	"NOM_TITULAR" VARCHAR2(200), 
	"APE_PATERNO_TITULAR" VARCHAR2(50), 
	"APE_MATERNO_TITULAR" VARCHAR2(50), 
	"DESCRIPCION_DENUNCIA" VARCHAR2(4000), 
	"RAZONES" VARCHAR2(4000), 
	"CODUSUARIO_ALTA" VARCHAR2(30) DEFAULT USER, 
	"FEC_ALTA" DATE DEFAULT TRUNC(SYSDATE), 
	 CONSTRAINT "PK_PLD_REP_OPERACIONES" PRIMARY KEY ("IDOPERACION", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
