
  CREATE TABLE "SICAS_OC"."POLFACTMENSUAL" 
   (	"CODCIA" NUMBER(3,0) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(10,0) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(10,0) NOT NULL ENABLE, 
	"FECINICIOVIG" DATE, 
	"FECFINVIG" DATE, 
	 PRIMARY KEY ("CODCIA", "IDPOLIZA", "IDFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
