
  CREATE TABLE "SICAS_OC"."POR_AUTORIZAR_SAT" 
   (	"CODCIA" NUMBER(14,0), 
	"ID_RFC" VARCHAR2(30), 
	"NOM_CONTRIB" VARCHAR2(500), 
	"SIT_CONTRIB" VARCHAR2(50), 
	"STATUS_REGISTRO" VARCHAR2(6), 
	"USUARIO_PROCESA" VARCHAR2(30), 
	"FECHA_AUTORIZACION" DATE, 
	"OBSERVACIONES" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
