
  CREATE TABLE "SICAS_OC"."PRIMAS_DEPOSITO" 
   (	"IDPRIMADEPOSITO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"FECHA" DATE, 
	"MONTO_LOCAL" NUMBER(18,2), 
	"MONTO_MONEDA" NUMBER(18,2), 
	"COSTO_TOTAL_POLIZA_MONEDA" NUMBER(18,2), 
	"SALDO_MONEDA" NUMBER(18,2), 
	"SALDO_LOCAL" NUMBER(18,2), 
	"OBSERVACIONES" LONG, 
	"ESTADO" VARCHAR2(6), 
	"NUMERO_RECIBO_REFERENCIA" VARCHAR2(30), 
	"COD_MONEDA" VARCHAR2(5), 
	"TASACAMBIO" NUMBER(11,6), 
	"COSTO_TOTAL_POLIZA_LOCAL" NUMBER(18,2), 
	"FECSTS" DATE, 
	"IDTRANSACEMIT" NUMBER(18,0), 
	"IDTRANSACAPLIC" NUMBER(18,0), 
	"IDTRANSACANUL" NUMBER(18,0), 
	"CTALIQUIDADORA" VARCHAR2(6), 
	"IDPOLIZA" NUMBER(14,0) DEFAULT 0, 
	"IDETPOL" NUMBER(14,0) DEFAULT 0, 
	 CONSTRAINT "PK_PRIMAS_DEPOSITO" PRIMARY KEY ("IDPRIMADEPOSITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
