
  CREATE TABLE "SICAS_OC"."PROCESOS_MASIVOS_SEGUIMIENTO" 
   (	"IDPROCMASIVO" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CRGA_COD_PROCESO" VARCHAR2(6), 
	"CRGA_DESCPROCESO" VARCHAR2(80), 
	"CRGA_NOM_ARCHIVO" VARCHAR2(200), 
	"CRGA_REGDATOSPROC" VARCHAR2(4000), 
	"CRGA_STS" VARCHAR2(6), 
	"CRGA_USUARIO" VARCHAR2(50), 
	"CRGA_TERMINAL" VARCHAR2(50), 
	"CRGA_FECHA" DATE, 
	"CRGA_FECHACOMP" DATE, 
	"ERR_IDLOGPROCESO" NUMBER(14,0), 
	"ERR_TXTERROR" VARCHAR2(4000), 
	"ERR_USUARIO" VARCHAR2(50), 
	"ERR_TERMINAL" VARCHAR2(50), 
	"ERR_FECHA" DATE, 
	"ERR_FECHACOMP" DATE, 
	"EMI_IDTIPOSEG" VARCHAR2(6), 
	"EMI_PLANCOB" VARCHAR2(15), 
	"EMI_TIPOPROCESO" VARCHAR2(30), 
	"EMI_STSREGPROCESO" VARCHAR2(6), 
	"EMI_REGDATOSPROC" VARCHAR2(4000), 
	"EMI_USUARIO" VARCHAR2(50), 
	"EMI_TERMINAL" VARCHAR2(50), 
	"EMI_FECHA" DATE, 
	"EMI_FECHACOMP" DATE, 
	"IDPOLIZA" NUMBER(14,0), 
	"IDTRANSACCION" NUMBER(18,0), 
	"NUM_APROBACION" NUMBER(14,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"MONTOIVA" NUMBER(28,2), 
	"MONTOPAGAR" NUMBER(28,2), 
	"MONTOISR" NUMBER(28,2), 
	"CODCOBERT" VARCHAR2(6), 
	"NUMMOD" NUMBER(2,0), 
	"TIPO" VARCHAR2(20), 
	"NUMFACTURA" VARCHAR2(45), 
	"ARCHIVO_LOGEM" VARCHAR2(200), 
	"INDPOLCOL" VARCHAR2(12), 
	"NUM_ASISTENCIA" VARCHAR2(25), 
	"RFC_HOSPITAL" VARCHAR2(32), 
	"RFC_ASISTENCIADORA" VARCHAR2(32), 
	"POLCONTA_GG" VARCHAR2(20), 
	"FECHA_PAGO" DATE, 
	"IMPORT_PAGO" NUMBER(18,2), 
	"ARCHIVO_GG" VARCHAR2(100), 
	"PGOGG_USUARIO" VARCHAR2(50), 
	"PGOGG_TERMINAL" VARCHAR2(50), 
	"PGOGG_FECHA" DATE, 
	"PGOGG_FECHACOMP" DATE, 
	"OBSERVACION_GG" VARCHAR2(100), 
	"INDFONDOSINI" VARCHAR2(1) DEFAULT 'N', 
	"FOND_USUARIO" VARCHAR2(50), 
	"FOND_TERMINAL" VARCHAR2(50), 
	"FOND_FEC" DATE, 
	"FOND_RFC" VARCHAR2(21), 
	 CONSTRAINT "PK_PROCESOS_MASIVOS_SEG" PRIMARY KEY ("IDPROCMASIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
