
  CREATE TABLE "SICAS_OC"."PROC_DET" 
   (	"ID_PROCESO" NUMBER(5,0), 
	"ST_PROCESO" NUMBER(5,0), 
	"TP_TRANSACC" VARCHAR2(20), 
	"IDTRANSACCION" NUMBER(18,0), 
	"IDPROCESO_T" NUMBER(10,0), 
	"FECHATRANSACCION" DATE, 
	"CORRELATIVO_DT" NUMBER(10,0), 
	"CODSUBPROCESO_DT" VARCHAR2(6), 
	"OBJETO_DT" VARCHAR2(35), 
	"ID_POLIZA_V1_DT" VARCHAR2(20), 
	"ID_DETPOLV2_DT" VARCHAR2(20), 
	"ID_ENDOSO_V3_DT" VARCHAR2(20), 
	"ID_IDNCR_V4_DT" VARCHAR2(20), 
	"MTOLOCAL_DT" NUMBER(18,6), 
	"NUMCOMPROB" NUMBER(28,0), 
	"TIPOCOMPROB" VARCHAR2(10), 
	"FECCOMPROB" DATE, 
	"STSCOMPROB" VARCHAR2(10), 
	"FECSTS_COMP" DATE, 
	"TOTALDEBITOS_COMP" NUMBER(28,2), 
	"TOTALCREDITOS_COMP" NUMBER(28,2), 
	"TOTALDIFCOMP_COMP" NUMBER(28,2), 
	"FECENVIOSC_COMP" DATE, 
	"NUMCOMPROBSC_COMP" NUMBER(28,0), 
	"REG_FE_CARGA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
