
  CREATE TABLE "SICAS_OC"."PROCESO_AUTORIZACION" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPROCESO" VARCHAR2(6) NOT NULL ENABLE, 
	"DESCPROCAUTORIZA" VARCHAR2(100) NOT NULL ENABLE, 
	"INDTIPOSEG" VARCHAR2(1) DEFAULT 'N', 
	"FECHAALTAPROC" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	"INDNIVELJERARQUICO" VARCHAR2(1), 
	 CONSTRAINT "PK_PROCESO_AUTORIZACION" PRIMARY KEY ("CODCIA", "CODPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
