
  CREATE TABLE "SICAS_OC"."PROC_TAREA" 
   (	"IDPROCESO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROINI" VARCHAR2(6) NOT NULL ENABLE, 
	"PROFIN" VARCHAR2(6) NOT NULL ENABLE, 
	"INDPROCESO" VARCHAR2(1) NOT NULL ENABLE, 
	"TIPOPROCESO" VARCHAR2(6), 
	"DESCRIPCION_PROCESO" VARCHAR2(200), 
	"TIEMPO" NUMBER(4,2), 
	"PARAMETRO_TIEMPO" VARCHAR2(6), 
	"ESTADO" VARCHAR2(6), 
	"INDFECEQUIV" VARCHAR2(1), 
	 CONSTRAINT "PK_PROC_TAREA" PRIMARY KEY ("IDPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
