
  CREATE TABLE "SICAS_OC"."PROCESOS_CONTABLES" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPROCESO" VARCHAR2(6) NOT NULL ENABLE, 
	"NOMPROCESO" VARCHAR2(100), 
	"TIPOCOMPROB" VARCHAR2(6), 
	"TIPOCOMPREV" VARCHAR2(6), 
	"CODUSUARIO" VARCHAR2(30), 
	"FECULTCAMBIO" DATE, 
	"TIPODIARIO" VARCHAR2(6), 
	 CONSTRAINT "PK_PROCESOS_CONTABLES" PRIMARY KEY ("CODCIA", "CODPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
