
  CREATE TABLE "SICAS_OC"."PROVEEDORES_SERVICIOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPROVEEDOR" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPOSERVICIO" VARCHAR2(6) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROV_SERVICIOS" PRIMARY KEY ("CODCIA", "CODPROVEEDOR", "TIPOSERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_PROV_SERVICIOS" FOREIGN KEY ("CODCIA", "CODPROVEEDOR")
	  REFERENCES "SICAS_OC"."PROVEEDORES_DATOS_PART" ("CODCIA", "CODPROVEEDOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
