
  CREATE TABLE "SICAS_OC"."PROVEEDORES_DATOS_PART" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPROVEEDOR" NUMBER(14,0) NOT NULL ENABLE, 
	"NROCONTRATO" VARCHAR2(30), 
	"LICENCIASANITARIA" VARCHAR2(30), 
	"TIEMPOPAGO" NUMBER(3,0), 
	"CLASIFICACION" VARCHAR2(5), 
	"PCTDESCUENTO" NUMBER(3,0), 
	"TIPODESCUENTO" VARCHAR2(6), 
	"FECHAALTA" DATE, 
	"OBSERVACIONES" VARCHAR2(2000), 
	 CONSTRAINT "PK_PROV_DAT_PART" PRIMARY KEY ("CODCIA", "CODPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_PROV_DAT_PART" FOREIGN KEY ("CODCIA", "CODPROVEEDOR")
	  REFERENCES "SICAS_OC"."PROVEEDORES" ("CODCIA", "CODPROVEEDOR") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
