
  CREATE TABLE "SICAS_OC"."PROVEEDORES_LOG" 
   (	"IDPROCESO" NUMBER(14,0), 
	"TIPO_ARCHIVO" VARCHAR2(20), 
	"CONSECUTIVO" NUMBER(10,0), 
	"ID_RFC" VARCHAR2(30), 
	"CODIGO_ERROR" VARCHAR2(20), 
	"TXTERROR" VARCHAR2(200), 
	"FECHA_LOG" DATE, 
	"COD_USUARIO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
