
  CREATE TABLE "SICAS_OC"."PROVEEDORES" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODPROVEEDOR" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPOPROVEEDOR" VARCHAR2(10), 
	"FECINGRESO" DATE, 
	"TIPODOCIDENTPROV" VARCHAR2(6), 
	"NUMDOCIDENTPROV" VARCHAR2(20), 
	"STSPROVEEDOR" VARCHAR2(10), 
	"FECSTS" DATE, 
	"CLASEPROVEEDOR" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROVEEDORES" PRIMARY KEY ("CODCIA", "CODPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPODOCIDENTPROV", "NUMDOCIDENTPROV")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
