
  CREATE TABLE "SICAS_OC"."PROVEEDOR_SAT_EVALUADO" 
   (	"CODCIA" NUMBER(14,0), 
	"CONSECUTIVO" NUMBER(10,0), 
	"ID_RFC" VARCHAR2(30), 
	"FECHA_EVALUACION" DATE, 
	"NOM_CONTRIB" VARCHAR2(500), 
	"SIT_CONTRIB" VARCHAR2(500), 
	"OFI_PRESUNCION_1" VARCHAR2(500), 
	"PUB_SAT_PRESUNTOS" VARCHAR2(500), 
	"OFI_PRESUNCION_2" VARCHAR2(500), 
	"PUB_DOF_PRESUNTOS" VARCHAR2(500), 
	"PUB_SAT_DESVIRTUADOS" VARCHAR2(500), 
	"OFI_CONTRIB_DESVIRTUADOS" VARCHAR2(500), 
	"PUB_DOF_DESVIRTUADOS" VARCHAR2(500), 
	"OFI_DEFINITIVOS" VARCHAR2(500), 
	"PUB_SAT_DEFINITIVOS" VARCHAR2(500), 
	"PUB_DOF_DEFINITIVOS" VARCHAR2(500), 
	"OFI_SENTECIA_FAV" VARCHAR2(500), 
	"PUB_SAT_SENTENCIA_FAV" VARCHAR2(500), 
	"OFI_DOF_SENTENCIA_FAV" VARCHAR2(500), 
	"PUB_DOF_SENTENCIA_FAV" VARCHAR2(500), 
	"ENCONTRADO_EN" VARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
