
  CREATE TABLE "SICAS_OC"."RANGO_MORA_CLIENTE" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODRANGO_MORA" VARCHAR2(6) NOT NULL ENABLE, 
	"DIAS_DE" NUMBER(3,0) NOT NULL ENABLE, 
	"DIAS_A" NUMBER(3,0) NOT NULL ENABLE, 
	"DESCRANGO" VARCHAR2(50) NOT NULL ENABLE, 
	"ORDEN_IMPRESION" NUMBER(3,0), 
	 PRIMARY KEY ("CODCIA", "CODRANGO_MORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
