
  CREATE TABLE "SICAS_OC"."REA_DISTRIB_AUTO_HIST_BK" 
   (	"IDPOLIZA" NUMBER(14,0), 
	"NUMPOLUNICO" VARCHAR2(30), 
	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"PLANCOB" VARCHAR2(15), 
	"IDTRANSACCION" NUMBER(18,0) NOT NULL ENABLE, 
	"OBJETO" VARCHAR2(35), 
	"IDPROCESO" NUMBER(10,0) NOT NULL ENABLE, 
	"FECHATRANSACCION" DATE, 
	"TIPO_RIESGO" VARCHAR2(10), 
	"CODESQUEMA" VARCHAR2(20), 
	"PROCESADO" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
