
  CREATE TABLE "SICAS_OC"."REA_LIQUIDACION_REASEG_DET" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDLIQUIDACION" NUMBER(14,0) NOT NULL ENABLE, 
	"IDDETLIQREASEG" NUMBER(10,0) NOT NULL ENABLE, 
	"CODCPTOLIQUIDA" VARCHAR2(6) NOT NULL ENABLE, 
	"TOTCPTOLIQUIDA" NUMBER(32,6), 
	"DESCMOVIMIENTO" VARCHAR2(2000), 
	 CONSTRAINT "PK_REA_LIQUIDACION_REASEG_DET" PRIMARY KEY ("CODCIA", "IDLIQUIDACION", "IDDETLIQREASEG", "CODCPTOLIQUIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_REA_LIQUIDACION_REASEG_DET" FOREIGN KEY ("CODCIA", "IDLIQUIDACION", "IDDETLIQREASEG")
	  REFERENCES "SICAS_OC"."REA_LIQUIDACION_REASEG" ("CODCIA", "IDLIQUIDACION", "IDDETLIQREASEG") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
