
  CREATE TABLE "SICAS_OC"."REA_ESQUEMAS_FACT_CREDITOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODESQUEMA" VARCHAR2(10) NOT NULL ENABLE, 
	"FECINICREDITO" DATE NOT NULL ENABLE, 
	"FECFINCREDITO" DATE NOT NULL ENABLE, 
	"FACTORCREDITOS" NUMBER(18,9), 
	"PERIODOVARIABLE" NUMBER(5,0), 
	"INDPERIODOVARREASEG" VARCHAR2(1) DEFAULT 'N', 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "PK_REA_ESQUEMAS_FACT_CREDITOS" PRIMARY KEY ("CODCIA", "CODESQUEMA", "FECINICREDITO", "FECFINCREDITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_ESQUEMAS_FACT_CRED" FOREIGN KEY ("CODCIA", "CODESQUEMA")
	  REFERENCES "SICAS_OC"."REA_ESQUEMAS" ("CODCIA", "CODESQUEMA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
