
  CREATE TABLE "SICAS_OC"."REA_ESQUEMAS_POLIZAS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODESQUEMA" VARCHAR2(10) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"PRIMASDIRECTAS" NUMBER(28,2), 
	"FACTORREASEG" NUMBER(18,9), 
	"PRIMASCEDIDAS" NUMBER(32,6), 
	"TOTALPRIMASREASEG" NUMBER(32,6), 
	"FACTORCESION" NUMBER(18,9), 
	"FECINGRESO" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	 CONSTRAINT "PK_REA_ESQUEMAS_POLIZAS" PRIMARY KEY ("CODCIA", "CODESQUEMA", "IDPOLIZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_ESQUEMAS_POLIZAS" FOREIGN KEY ("CODCIA", "CODESQUEMA")
	  REFERENCES "SICAS_OC"."REA_ESQUEMAS" ("CODCIA", "CODESQUEMA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
