
  CREATE TABLE "SICAS_OC"."REA_ESQUEMAS_POLIZA_COBERT" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODESQUEMA" VARCHAR2(10) NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6), 
	"INDCESIONPRIMAS" VARCHAR2(1), 
	"INDRECUPERASINI" VARCHAR2(1), 
	 CONSTRAINT "PK_REA_ESQUEMAS_POLIZA_COBERT" PRIMARY KEY ("CODCIA", "CODESQUEMA", "IDPOLIZA", "CODCOBERT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_ESQUEMAS_POLIZAS_COBERT" FOREIGN KEY ("CODCIA", "CODESQUEMA", "IDPOLIZA")
	  REFERENCES "SICAS_OC"."REA_ESQUEMAS_POLIZAS" ("CODCIA", "CODESQUEMA", "IDPOLIZA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
