
  CREATE TABLE "SICAS_OC"."REA_EMPRESAS_CONTACTOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESAGREMIO" VARCHAR2(10) NOT NULL ENABLE, 
	"IDCONTACTO" NUMBER(5,0) NOT NULL ENABLE, 
	"NOMCONTACTO" VARCHAR2(200), 
	"PUESTOCONTACTO" VARCHAR2(100), 
	"NOMDEPARTAMENTO" VARCHAR2(100), 
	"TELCONTACTO" VARCHAR2(50), 
	"FAXCONTACTO" VARCHAR2(50), 
	"EMAILCONTACTO" VARCHAR2(200), 
	 CONSTRAINT "PK_REA_EMPRESAS_CONTACTOS" PRIMARY KEY ("CODCIA", "CODEMPRESAGREMIO", "IDCONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_REA_EMPRESAS_CONTACTOS" FOREIGN KEY ("CODCIA", "CODEMPRESAGREMIO")
	  REFERENCES "SICAS_OC"."REA_EMPRESAS_GREMIO" ("CODCIA", "CODEMPRESAGREMIO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
