
  CREATE TABLE "SICAS_OC"."REGISTRO_TIPSEG_AUTORIDAD" 
   (	"IDTIPOSEG" VARCHAR2(6) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"NUMREGISTRO" NUMBER(6,0) NOT NULL ENABLE, 
	"FECREGISTRO" DATE, 
	"NUMAUTORTIPSEG" VARCHAR2(200), 
	"FECINGRESO" DATE, 
	"OBSERVACIONES" VARCHAR2(300), 
	"CODUSUARIO" VARCHAR2(30), 
	"DS_ARCH_CONGEN" VARCHAR2(200), 
	"STREGISTRO" VARCHAR2(6), 
	"FEC_SUSPENCION" DATE, 
	"CONDICIONESGENERALES" BLOB DEFAULT EMPTY_BLOB(), 
	 PRIMARY KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA", "NUMREGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("IDTIPOSEG", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."TIPOS_DE_SEGUROS" ("IDTIPOSEG", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("CONDICIONESGENERALES") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
