
  CREATE TABLE "SICAS_OC"."REGLA_SA_COBER" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"CODCOBERT" VARCHAR2(6), 
	"TEXTO" VARCHAR2(200), 
	"STREGLA" VARCHAR2(6), 
	"USUARIO" VARCHAR2(10), 
	"FECHA_ULT_MOVTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
