
  CREATE TABLE "SICAS_OC"."RELACION_PNJ" 
   (	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6) NOT NULL ENABLE, 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_RELACION" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPO_RELACION" VARCHAR2(6), 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHA_HORA" DATE NOT NULL ENABLE, 
	"CONTACTO" VARCHAR2(200), 
	"MOTIVO" VARCHAR2(6), 
	"DESCRIPCION" LONG, 
	 PRIMARY KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "ID_RELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
