
  CREATE TABLE "SICAS_OC"."RELACION_CLIENTE" 
   (	"CODCLIENTE" NUMBER(14,0) CONSTRAINT "SYS_C0033662" NOT NULL ENABLE, 
	"ID_RELACION" NUMBER(14,0) CONSTRAINT "SYS_C0033663" NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) CONSTRAINT "SYS_C0033664" NOT NULL ENABLE, 
	"TIPO_RELACION" VARCHAR2(6), 
	"FECHA_HORA" DATE, 
	"CONTACTO" VARCHAR2(200), 
	"MOTIVO" VARCHAR2(6), 
	"IDTIPOSEG" VARCHAR2(6), 
	"DESCRIPCION" LONG, 
	"NOMARCH" VARCHAR2(200), 
	 PRIMARY KEY ("CODCLIENTE", "ID_RELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
