
  CREATE TABLE "SICAS_OC"."RENO_ERROR" 
   (	"ID_CODCIA" NUMBER(14,0), 
	"NU_REMESA" VARCHAR2(30), 
	"ID_POLIZA" NUMBER(14,0), 
	"ID_DETPOL" NUMBER(14,0), 
	"FE_PROCESO" DATE, 
	"USUARIO_PROCESO" VARCHAR2(10), 
	"ID_ERROR" VARCHAR2(5), 
	"DS_ERROR" VARCHAR2(3000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
