
  CREATE TABLE "SICAS_OC"."REP_LEGAL_PNJ" 
   (	"TIPO_DOC_IDENTIFICACION" VARCHAR2(6), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"TIPO_DOC_REP_LEGAL" VARCHAR2(6), 
	"NUM_DOC_REP_LEGAL" VARCHAR2(20), 
	"CORRELATIVO" NUMBER(5,0) NOT NULL ENABLE, 
	"FECHAINICIO" DATE, 
	"FECHAFINAL" DATE, 
	"ESTADO" VARCHAR2(6), 
	"CODUSUARIO_ALTA" VARCHAR2(30) DEFAULT USER, 
	"FEC_ALTA" DATE DEFAULT TRUNC(SYSDATE), 
	 CONSTRAINT "PK_REPLEGAL" PRIMARY KEY ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION", "TIPO_DOC_REP_LEGAL", "NUM_DOC_REP_LEGAL", "CORRELATIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_REP_LEGAL_REP_LEGAL" FOREIGN KEY ("TIPO_DOC_REP_LEGAL", "NUM_DOC_REP_LEGAL")
	  REFERENCES "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("TIPO_DOC_IDENTIFICACION", "NUM_DOC_IDENTIFICACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
