
  CREATE TABLE "SICAS_OC"."REPCARTERA" 
   (	"POLIZA" VARCHAR2(30), 
	"CONSECUTIVO" NUMBER(14,0), 
	"AGRUPADOR" VARCHAR2(6), 
	"RAMO" VARCHAR2(50), 
	"CONTRATANTE" VARCHAR2(200), 
	"INICIO_VIG" DATE, 
	"FIN_VIG" DATE, 
	"PLAN_PAGO" VARCHAR2(50), 
	"NUM_SUBGRUPOS" NUMBER(8,0), 
	"STATUS" VARCHAR2(50), 
	"FECHA_STATUS" DATE, 
	"PRIMA_NETA" NUMBER(18,2), 
	"DERECHO_POLIZA" NUMBER(18,2), 
	"RECARGO" NUMBER(18,2), 
	"IVA" NUMBER(18,2), 
	"PRIMA_TOTAL" NUMBER(18,2), 
	"PRIMA_BASE" NUMBER(18,2), 
	"PRIMA_PAGADA" NUMBER(18,2), 
	"CODIGO_AGENTE" NUMBER(8,0), 
	"NOMBRE_AGENTE" VARCHAR2(100), 
	"PORCENTAJE_AGENTE" NUMBER(10,6), 
	"CANTIDAD_AGENTE" NUMBER(18,2), 
	"CODIGO_PROMOTOR" NUMBER(8,0), 
	"NOMBRE_PROMOTOR" VARCHAR2(100), 
	"PORCENTAJE_PROMOTOR" NUMBER(10,6), 
	"MONTO_PROMOTOR" NUMBER(18,2), 
	"CODIGO_DIRECCION" NUMBER(8,0), 
	"NOMBRE_DIRECCION" VARCHAR2(100), 
	"PORCENTAJE_DIRECCION" NUMBER(10,6), 
	"MONTO_DIRECCION" NUMBER(18,2), 
	"FECHA_REPORTE" DATE DEFAULT trunc(sysdate), 
	"RFC" VARCHAR2(45)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
