
  CREATE TABLE "SICAS_OC"."REPORTE_FORMATO" 
   (	"IDREPORTEFORMATO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDREPORTE" NUMBER(14,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(2000), 
	"FORMATO" VARCHAR2(9), 
	"PRINCIPAL" VARCHAR2(1), 
	 CONSTRAINT "CHK_PRINCIPAL_FORMATO" CHECK (PRINCIPAL IN ('S','N')
) ENABLE, 
	 CONSTRAINT "PK_REPORTEFORMATO" PRIMARY KEY ("IDREPORTEFORMATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
