
  CREATE TABLE "SICAS_OC"."REPORTE_RECIBOS_360" 
   (	"RECIBO" NUMBER(14,0), 
	"POLIZA" VARCHAR2(30), 
	"NOMBRE_CONTRATANTE" VARCHAR2(302), 
	"PERIODICIDAD_PAGO" VARCHAR2(100), 
	"ORIGEN_RECIBO" CHAR(8), 
	"SUBGRUPO" NUMBER(14,0), 
	"ENDOSO" NUMBER(14,0), 
	"VENCIMIENTO" DATE, 
	"DIAS_DE_VENCIDO" NUMBER, 
	"ANTIGUEDAD" VARCHAR2(12), 
	"PRIMA_NETA" NUMBER, 
	"PRIMA_TOTAL" NUMBER, 
	"ID_AGENTE" NUMBER(18,0), 
	"NOMBRE_AGENTE" VARCHAR2(4000), 
	"COMISION_PORC_AG" NUMBER(9,6), 
	"COMISION_AG" NUMBER, 
	"ID_PROMOTOR" NUMBER(18,0), 
	"NOMBRE_PROMOTOR" VARCHAR2(4000), 
	"COMISION_PORC_PRO" NUMBER(9,6), 
	"COMISION_PRO" NUMBER, 
	"ID_DIRREG" NUMBER(18,0), 
	"NOMBRE_DIRECCION" VARCHAR2(4000), 
	"COMISION_PORC_DR" NUMBER(9,6), 
	"COMISION_DR" NUMBER, 
	"STATUS" VARCHAR2(401), 
	"RAMO" VARCHAR2(4000), 
	"SI_SINIESTRO" VARCHAR2(13), 
	"MONTO_RESERVA_PENDIENTE" NUMBER, 
	"MONTO_PAGADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
