
  CREATE TABLE "SICAS_OC"."REQUISITOS" 
   (	"CODREQUISITO" VARCHAR2(6) CONSTRAINT "SYS_C0033783" NOT NULL ENABLE, 
	"INDOBLIG" VARCHAR2(1) CONSTRAINT "SYS_C0033784" NOT NULL ENABLE, 
	"DESCREQUISITO" VARCHAR2(200), 
	"STSREQUISITO" VARCHAR2(3), 
	"FECSTS" DATE, 
	"USOREQUISITO" VARCHAR2(1), 
	"INDCOBERT" VARCHAR2(1), 
	"INDPLANCOB" VARCHAR2(1), 
	 PRIMARY KEY ("CODREQUISITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "SYS_C0033786" CHECK (IndOblig IN ('S','N') ) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
