
  CREATE TABLE "SICAS_OC"."REQUISITOS_ENC_POLIZA" 
   (	"IDPOLIZA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODREQUISITO" VARCHAR2(6) NOT NULL ENABLE, 
	"FECSOLICITREQ" DATE, 
	"FECENTREGAREQ" DATE, 
	"OBSERVACIONES" VARCHAR2(2000), 
	"CODCIA" NUMBER(14,0), 
	 CONSTRAINT "PK_REQ_ENC_POLIZA" PRIMARY KEY ("IDPOLIZA", "CODREQUISITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
