DROP TABLE SICAS_OC.REQUISITOS_COBERTURAS;
/

DROP SYNONYM REQUISITOS_COBERTURAS;
/

CREATE TABLE SICAS_OC.REQUISITOS_COBERTURAS(  --MANTREQC
    CODCIA              NUMBER          NOT NULL,
    CODEMPRESA          NUMBER          NOT NULL,
    IDTIPOSEG           VARCHAR2(6)     NOT NULL,
    PLANCOB             VARCHAR2(15)    NOT NULL,
    CODCOBERT           VARCHAR2(6)     NOT NULL,
    CODREQUISITO        VARCHAR2(6)     NOT NULL,
    REQUERIDO           VARCHAR2(1)     DEFAULT 'N',
    ORDENEXPEDIENTE     NUMBER          DEFAULT 1,
    ORDENPDF            NUMBER          DEFAULT 1,
    CANTIDAD            NUMBER          DEFAULT 1,
    USRINSERT           VARCHAR2(20)    DEFAULT USER,
    FECHAINSERT         DATE            DEFAULT SYSDATE,
    USRMODIF            VARCHAR2(20)    DEFAULT USER,
    FECHAMODIF          DATE            DEFAULT SYSDATE
)TABLESPACE TS_SICASOC;
/

CREATE UNIQUE INDEX SICAS_OC.IX_REQSCOBERT  ON
    SICAS_OC.REQUISITOS_COBERTURAS(CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODREQUISITO)
TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.REQUISITOS_COBERTURAS ADD
    CONSTRAINT PK_REQSCOBERT 
    PRIMARY KEY (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODREQUISITO)
    USING INDEX SICAS_OC.IX_REQSCOBERT;
/

ALTER TABLE SICAS_OC.REQUISITOS_COBERTURAS ADD
    CONSTRAINT FK_REQSCOBERT1
    FOREIGN KEY (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT)
    REFERENCES SICAS_OC.COBERTURAS_DE_SEGUROS (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT);
/

ALTER TABLE SICAS_OC.REQUISITOS_COBERTURAS ADD
    CONSTRAINT FK_REQSCOBERT2
    FOREIGN KEY (CODREQUISITO)
    REFERENCES SICAS_OC.REQUISITOS (CODREQUISITO);
/

COMMENT ON TABLE SICAS_OC.REQUISITOS_COBERTURAS IS 'Tabla de requisitos para levantar un siniestro por cobertura';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.CODCIA IS 'Codigo de la Compania';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.CODEMPRESA IS 'Codigo de la Empresa';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.IDTIPOSEG IS 'Clave de tipo de seguro';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.PLANCOB IS 'Plan cobertura del idtiposeg';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.CODCOBERT IS 'Clave de la cobertura del siniestro';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.CODREQUISITO IS 'Codigo del requisito de la tabla requisitos';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.REQUERIDO IS 'Valor si es requerido o so, 1 para Si y 0 para No';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.ORDENEXPEDIENTE IS 'Orden de requisitos con forme al expediente';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.CANTIDAD IS 'Cantidad máxima de archivos para el requisito en cuestion';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.USRINSERT IS 'Usuario que inserto el registro';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.FECHAINSERT IS 'Fecha de insercion del registro';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.USRMODIF IS 'Ultimo Usuario que modifico el registro';
COMMENT ON COLUMN SICAS_OC.REQUISITOS_COBERTURAS.FECHAMODIF IS 'Ultima fecha de modificacion';

CREATE OR REPLACE PUBLIC SYNONYM REQUISITOS_COBERTURAS FOR SICAS_OC.REQUISITOS_COBERTURAS;
/

GRANT INSERT, DELETE, UPDATE,SELECT ON SICAS_OC.REQUISITOS_COBERTURAS TO PUBLIC,ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.REQUISITOS_COBERTURAS TO PUBLIC,ROL_CONSULTA_SICAS;
/
