DROP TABLE SICAS_OC.REQUISITOS ;
/

DROP SYNONYM REQUISITOS;
/

CREATE TABLE SICAS_OC.REQUISITOS (
    CODREQUISITO VARCHAR2(6), 
	INDOBLIG VARCHAR2(1), 
	DESCREQUISITO VARCHAR2(4000), 
	STSREQUISITO VARCHAR2(3), 
	FECSTS DATE, 
	USOREQUISITO VARCHAR2(1), 
	INDCOBERT VARCHAR2(1), 
	INDPLANCOB VARCHAR2(1), 
	TAMANIOBYTES NUMBER DEFAULT 1, 
	FORMATOS VARCHAR2(50) DEFAULT 'JPG,PDF,PNG', 
	CLAVEOCR VARCHAR2(50), 
	TOOLTIP VARCHAR2(4000), 
	NOMARCHIVO VARCHAR2(4000)
) TABLESPACE TS_SICASOC ;
   
CREATE INDEX SICAS_OC.REQUISITOS_IDX_1 
    ON SICAS_OC.REQUISITOS (CODREQUISITO, INDOBLIG) 
TABLESPACE IDX_SICASOC ;
  
ALTER TABLE SICAS_OC.REQUISITOS ADD 
    PRIMARY KEY (CODREQUISITO)
USING INDEX SICAS_OC.REQUISITOS_IDX_1 ;

COMMENT ON COLUMN SICAS_OC.REQUISITOS.CODREQUISITO IS 'Codigo del Requisito';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.INDOBLIG IS 'Indicador si es obligatorio';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.DESCREQUISITO IS 'Descripcion del requisito, sin caracteres especiales';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.STSREQUISITO IS 'Estado del Requisito';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.FECSTS IS 'Fecha del Status';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.USOREQUISITO IS 'Uso de Requisito en Emision, Siniestros o Ambas';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.INDCOBERT IS 'Indicador de Coberturas';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.INDPLANCOB IS 'Indicador para Planes de Coberturas';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.TAMANIOBYTES IS 'Tamanio maximo por archivo ens';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.FORMATOS IS 'Formatos validos para subir archivos';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.CLAVEOCR IS 'Clave OCR del requisito';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.TOOLTIP IS 'Tooltip a mostrar em la plataforma de agentes, sin caracteres especiales';
COMMENT ON COLUMN SICAS_OC.REQUISITOS.NOMARCHIVO IS 'Nombre del archivo';
COMMENT ON TABLE SICAS_OC.REQUISITOS  IS 'Requisitos para Emitir Polizas o Siniestros';

CREATE OR REPLACE PUBLIC SYNONYM REQUISITOS FOR SICAS_OC.REQUISITOS_COBERTURAS;
/

GRANT INSERT, DELETE, UPDATE,SELECT ON SICAS_OC.REQUISITOS TO PUBLIC,ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.REQUISITOS TO PUBLIC,ROL_CONSULTA_SICAS;
/

