
  CREATE TABLE "SICAS_OC"."RESERVAS_TECNICAS_RES" 
   (	"IDRESERVA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDRESUMEN" NUMBER(10,0) NOT NULL ENABLE, 
	"CODCPTORVA" VARCHAR2(6) NOT NULL ENABLE, 
	"MTOCOBBASICA" NUMBER(28,2), 
	"MTOCOBADICIONALES" NUMBER(28,2), 
	"MTOTOTALCOB" NUMBER(28,2), 
	 CONSTRAINT "PK_RESERVAS_TECNICAS_RES" PRIMARY KEY ("IDRESERVA", "IDRESUMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_RESERVAS_TECNICAS_RES" FOREIGN KEY ("IDRESERVA")
	  REFERENCES "SICAS_OC"."RESERVAS_TECNICAS" ("IDRESERVA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
