
  CREATE TABLE "SICAS_OC"."RESERVA_BKP" 
   (	"CODCIA" NUMBER(14,0), 
	"ID_PROCESO" NUMBER(3,0), 
	"ID_RAMO" VARCHAR2(6), 
	"ID_IND_O_COL" VARCHAR2(6), 
	"ID_MONEDA" VARCHAR2(6), 
	"ID_POLIZA" NUMBER(14,0), 
	"FE_INIVIG" DATE, 
	"FE_FINVIG" DATE, 
	"NUMPOLUNICO" VARCHAR2(30), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"COD_CLIENTE" NUMBER(14,0), 
	"TIPO_SEGURO" VARCHAR2(6), 
	"ID_SINIESTRO" NUMBER(14,0), 
	"NUMSINIREF" VARCHAR2(30), 
	"FE_NOTIFICACION" DATE, 
	"FE_OCURRIDO" DATE, 
	"AÑO_MOVIMIENTO" NUMBER(4,0), 
	"MES_MOVIMIENTO" NUMBER(2,0), 
	"ID_COBERTURA" VARCHAR2(6), 
	"RESERVA_ANTERIOR" NUMBER(18,2), 
	"ESTIMACION_INICIAL" NUMBER(18,2), 
	"AJUSTES_MAS" NUMBER(18,2), 
	"AJUSTES_MENOS" NUMBER(18,2), 
	"PAGOS" NUMBER(18,2), 
	"DESPAGOS" NUMBER(18,2), 
	"RESERVA_FINAL" NUMBER(18,2), 
	"ID_ORIGEN" VARCHAR2(6), 
	"ID_VALIDACION" VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
