
  CREATE TABLE "SICAS_OC"."RESERVAS_TECNICAS_GAAS" 
   (	"IDRESERVA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDTRIMESTRE" NUMBER(6,0) NOT NULL ENABLE, 
	"PRIMANETATRIM" NUMBER(28,2), 
	"CONSTRESERVA" NUMBER(28,6), 
	"RRCVIDAIND" NUMBER(28,6), 
	"RVAACUMTRIM" NUMBER(28,6), 
	"LIMSUPRESERVA" NUMBER(28,6), 
	"RVATOTTRIMESTRE" NUMBER(28,6), 
	"PRIMACEDIDA" NUMBER(28,2), 
	"FACTORCEDIDA" NUMBER(28,6), 
	"RVAREASEGCEDIDO" NUMBER(28,6), 
	 CONSTRAINT "PK_TARESERVAS_TECNICAS_GAAS" PRIMARY KEY ("IDRESERVA", "IDTRIMESTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_RESERVAS_TECNICAS_GAAS" FOREIGN KEY ("IDRESERVA")
	  REFERENCES "SICAS_OC"."RESERVAS_TECNICAS" ("IDRESERVA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
