
  CREATE TABLE "SICAS_OC"."RESERVA_DET_BKP" 
   (	"CODCIA" NUMBER(14,0), 
	"ID_SINIESTRO" NUMBER(14,0), 
	"ID_POLIZA" NUMBER(14,0), 
	"ID_COBERTURA" VARCHAR2(6), 
	"TIPO_MOVIMIENTO" VARCHAR2(6), 
	"IMPTE_MOVIMIENTO" NUMBER(18,2), 
	"FE_MOVTO" DATE, 
	"AÑO_MOVIMIENTO" NUMBER(4,0), 
	"MES_MOVIMIENTO" NUMBER(2,0), 
	"TRANSACCION" NUMBER(18,0), 
	"NMOD" NUMBER(3,0), 
	"PROCESO" NUMBER(10,0), 
	"SUBPROCESO" VARCHAR2(6), 
	"SIGNO" VARCHAR2(1), 
	"ID_ORIGEN" VARCHAR2(6), 
	"ID_VALIDACION" VARCHAR2(6), 
	"ID_PROCESO" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
