
  CREATE TABLE "SICAS_OC"."RW_SERVER_QUEUE" 
   (	"JOB_QUEUE" VARCHAR2(30), 
	"JOB_ID" NUMBER, 
	"JOB_TYPE" VARCHAR2(30), 
	"JOB_NAME" VARCHAR2(4000), 
	"STATUS_CODE" NUMBER, 
	"STATUS_MESSAGE" VARCHAR2(4000), 
	"COMMAND_LINE" VARCHAR2(4000), 
	"OWNER" VARCHAR2(30), 
	"DESTYPE" VARCHAR2(80), 
	"DESNAME" VARCHAR2(4000), 
	"SERVER" VARCHAR2(80), 
	"QUEUED" DATE, 
	"STARTED" DATE, 
	"FINISHED" DATE, 
	"RUN_ELAPSE" NUMBER, 
	"TOTAL_ELAPSE" NUMBER, 
	"LAST_RUN" DATE, 
	"NEXT_RUN" DATE, 
	"REPEAT_INTERVAL" NUMBER, 
	"REPEAT_PATTERN" NUMBER, 
	"CACHE_KEY" VARCHAR2(4000), 
	"CACHE_HIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
