
  CREATE TABLE "SICAS_OC"."SAI_CAT_GENERAL" 
   (	"CAGE_CD_CATALOGO" NUMBER(4,0) NOT NULL ENABLE, 
	"CAGE_CD_CLAVE_SEG" NUMBER(4,0) NOT NULL ENABLE, 
	"CAGE_CD_CLAVE_TER" NUMBER(20,0) NOT NULL ENABLE, 
	"CAGE_NOM_CATALOGO" VARCHAR2(40), 
	"CAGE_ID_CONCEP_NUM" NUMBER(3,0), 
	"CAGE_ID_CONCEP_ALF" VARCHAR2(3), 
	"CAGE_NOM_CONCEP" VARCHAR2(30), 
	"CAGE_VALOR_CORTO" VARCHAR2(10), 
	"CAGE_VALOR_LARGO" VARCHAR2(300), 
	"CAGE_CD_ESTATUS" VARCHAR2(3), 
	"CAGE_FE_REG" DATE, 
	"CAGE_CVE_REG" NUMBER(16,2), 
	"CAGE_NOM_REG" VARCHAR2(200), 
	"CAGE_PORC_CESION_UR" NUMBER(10,6), 
	"CAGE_PORC_COLTEC_UR" NUMBER(10,6), 
	 CONSTRAINT "SAI_CAG_PK" PRIMARY KEY ("CAGE_CD_CATALOGO", "CAGE_CD_CLAVE_SEG", "CAGE_CD_CLAVE_TER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
