
  CREATE TABLE "SICAS_OC"."SALDOS_COMISIONES_MES" 
   (	"CD_CIA" NUMBER(14,0), 
	"CD_AGENTE" NUMBER(18,0), 
	"CD_TIPO_RAMO" VARCHAR2(6), 
	"FE_INI_SALDO" DATE, 
	"FE_FIN_SALDO" DATE, 
	"FE_PROC_SALDO" DATE, 
	"CD_MONEDA" VARCHAR2(5), 
	"MT_SALDO_INICIAL" NUMBER(18,2), 
	"MT_COMISION_MES" NUMBER(18,2), 
	"MT_IVA_MES" NUMBER(18,2), 
	"MT_IVARET_MES" NUMBER(18,2), 
	"MT_ISR_MES" NUMBER(18,2), 
	"MT_ISRRET_MES" NUMBER(18,2), 
	"MT_ENCONTRA_MES" NUMBER(18,2), 
	"MT_AFAVOR_MES" NUMBER(18,2), 
	"MT_SALDO_FINAL" NUMBER(18,2), 
	"DS_OBSERVACIONES" VARCHAR2(300), 
	 CONSTRAINT "SALDOS_COMIS_MES_PK" PRIMARY KEY ("CD_CIA", "CD_AGENTE", "CD_TIPO_RAMO", "FE_INI_SALDO", "CD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
