
  CREATE TABLE "SICAS_OC"."SALDOS_COMISIONES_DETALLE" 
   (	"CD_CIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CD_TIPO_RAMO" VARCHAR2(6) NOT NULL ENABLE, 
	"FE_INI_SALDO" DATE NOT NULL ENABLE, 
	"FE_FIN_SALDO" DATE NOT NULL ENABLE, 
	"FE_PROCESO_SALDO" DATE NOT NULL ENABLE, 
	"FE_GENERACION" DATE NOT NULL ENABLE, 
	"CD_NIVEL" NUMBER(19,0) NOT NULL ENABLE, 
	"ID_POLIZA" NUMBER(14,0), 
	"ID_ENDOSO" NUMBER(14,0), 
	"ID_RECIBO" VARCHAR2(20), 
	"CD_MONEDA" VARCHAR2(5), 
	"MT_PRIMA_COM" NUMBER(18,2), 
	"MT_COMISION" NUMBER(18,2), 
	"MT_IVA" NUMBER(18,2), 
	"MT_IVARET" NUMBER(18,2), 
	"MT_ISR" NUMBER(18,2), 
	"MT_ISRRET" NUMBER(18,2), 
	"MT_SUBTOTAL" NUMBER(18,2), 
	"MT_ENCONTRA" NUMBER(18,2), 
	"MT_AFAVOR" NUMBER(18,2), 
	"ID_COMISION" NUMBER(14,0), 
	"ST_COMISION" VARCHAR2(6), 
	"PO_COM_DIST" NUMBER(9,6), 
	"PO_COM_PROP" NUMBER(9,6), 
	"MT_PMA" NUMBER(18,2), 
	"MT_PMAFACTURA" NUMBER(18,2), 
	"FE_PAGO" DATE, 
	 CONSTRAINT "SALDOS_DETALLE_PK" PRIMARY KEY ("CD_CIA", "CD_AGENTE", "CD_TIPO_RAMO", "ID_POLIZA", "ID_ENDOSO", "ID_RECIBO", "ID_COMISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
