
  CREATE TABLE "SICAS_OC"."SALDOS_COMISIONES" 
   (	"CD_CIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"CD_TIPO_RAMO" VARCHAR2(30), 
	"FE_INI_SALDO" DATE, 
	"FE_FIN_SALDO" DATE, 
	"FE_PROC_SALDO" DATE, 
	"CD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"MT_SALDO_INICIAL" NUMBER(18,2), 
	"MT_COM_TOT" NUMBER(18,2), 
	"MT_IVA_TOT" NUMBER(18,2), 
	"MT_IVARET_TOT" NUMBER(18,2), 
	"MT_ISR_TOT" NUMBER(18,2), 
	"MT_ISRRET_TOT" NUMBER(18,2), 
	"MT_SUBTOTAL_TOT" NUMBER(18,2), 
	"MT_ENCONTRA_TOT" NUMBER(18,2), 
	"MT_AFAVOR_TOT" NUMBER(18,2), 
	"MT_SALDO_FINAL" NUMBER(18,2), 
	"DS_OBSERVACION" VARCHAR2(300), 
	 CONSTRAINT "SALDOS_COMISIONES_PK" PRIMARY KEY ("CD_CIA", "CD_AGENTE", "CD_TIPO_RAMO", "FE_INI_SALDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
