
  CREATE TABLE "SICAS_OC"."SALDOS_COMISIONES_MES_3" 
   (	"CODCIA" NUMBER(14,0), 
	"COD_AGENTE" NUMBER(18,0), 
	"COD_TIPO_RAMO" VARCHAR2(6), 
	"FEC_INI_SALDO" DATE, 
	"FEC_FIN_SALDO" DATE, 
	"FEC_PROC_SALDO" DATE, 
	"COD_MONEDA" VARCHAR2(5), 
	"MONTO_SALDO_INICIAL" NUMBER(18,2), 
	"MONTO_COMISION_MES" NUMBER(18,2), 
	"MONTO_IVA_MES" NUMBER(18,2), 
	"MONTO_IVARET_MES" NUMBER(18,2), 
	"MONTO_ISR_MES" NUMBER(18,2), 
	"MONTO_ISRRET_MES" NUMBER(18,2), 
	"MONTO_ENCONTRA_MES" NUMBER(18,2), 
	"MONTO_AFAVOR_MES" NUMBER(18,2), 
	"MONTO_SALDO_FINAL" NUMBER(18,2), 
	"DESC_OBSERVACIONES" VARCHAR2(300), 
	 CONSTRAINT "SALDOS_COMIS_MES3_PK" PRIMARY KEY ("CODCIA", "COD_AGENTE", "COD_TIPO_RAMO", "FEC_INI_SALDO", "COD_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
