
  CREATE TABLE "SICAS_OC"."SC$LICENCIA" 
   (	"NUM_LICENCIA" VARCHAR2(28) NOT NULL ENABLE, 
	"EMPRESA" VARCHAR2(50) NOT NULL ENABLE, 
	"NUM_ACTIVACION" VARCHAR2(28) NOT NULL ENABLE, 
	"FECACTIVACION" DATE NOT NULL ENABLE, 
	"PASSWORD_LICENCIA" VARCHAR2(10) NOT NULL ENABLE, 
	"USUARIO_INSTALACION" VARCHAR2(50) NOT NULL ENABLE, 
	"TABLESPACE_INSTALACION" VARCHAR2(50) NOT NULL ENABLE, 
	"STSLIC" VARCHAR2(3), 
	"FECSTS" DATE, 
	 PRIMARY KEY ("NUM_LICENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
