
  CREATE TABLE "SICAS_OC"."SC$VIGENCIA_LICENCIA" 
   (	"NUM_LICENCIA" VARCHAR2(28) NOT NULL ENABLE, 
	"MODSC" VARCHAR2(6) NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"FECINIVIG" DATE NOT NULL ENABLE, 
	"FECFINVIG" DATE NOT NULL ENABLE, 
	"NOTIFICACION_VENCIMIENTO" VARCHAR2(1) NOT NULL ENABLE, 
	 PRIMARY KEY ("NUM_LICENCIA", "MODSC", "CODCIA", "FECINIVIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("NUM_LICENCIA", "MODSC", "CODCIA")
	  REFERENCES "SICAS_OC"."SC$CONFIGURACION_LICENCIA" ("NUM_LICENCIA", "MODSC", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
