
  CREATE TABLE "SICAS_OC"."SEGUIMIENTO_SINIESTRO" 
   (	"IDNUMSEGUI" NUMBER(14,0) CONSTRAINT "SYS_C0033774" NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) CONSTRAINT "SYS_C0033775" NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(14,0) CONSTRAINT "SYS_C0033776" NOT NULL ENABLE, 
	"FECSEGUI" DATE, 
	"TELSEG" VARCHAR2(30), 
	"CONTACTO" VARCHAR2(200), 
	"STSSEGUI" VARCHAR2(3), 
	"FECSTS" DATE, 
	"OBSERVACIONES" LONG, 
	 PRIMARY KEY ("IDNUMSEGUI", "IDPOLIZA", "IDSINIESTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
