
  CREATE TABLE "SICAS_OC"."SEGUIMIENTO_PRIMA_DEPOSITO" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDPRIMADEPOSITO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDSEGUIMIENTO" NUMBER(14,0) NOT NULL ENABLE, 
	"FECSEGUIMIENTO" DATE, 
	"TIPOSEGUIMIENTO" VARCHAR2(6), 
	"STSSEGUIMIENTO" VARCHAR2(6), 
	"FECHASTS" DATE, 
	"CODUSUARIO" VARCHAR2(30), 
	"OBSERVACIONES" LONG, 
	 CONSTRAINT "PK_SEGUIMIENTO_PRIMA_DEPOSITO" PRIMARY KEY ("CODCIA", "IDPRIMADEPOSITO", "IDSEGUIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_SEGUIMIENTO_PRIMA_DEPOSITO" FOREIGN KEY ("IDPRIMADEPOSITO")
	  REFERENCES "SICAS_OC"."PRIMAS_DEPOSITO" ("IDPRIMADEPOSITO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
