
  CREATE TABLE "SICAS_OC"."SEPARA_NOMBRES" 
   (	"IDREGISTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"NOMBRECOMPLETO" VARCHAR2(300) NOT NULL ENABLE, 
	"NOMBRESOLO" VARCHAR2(200), 
	"APELLIDO_PATERNO" VARCHAR2(50), 
	"APELLIDO_MATERNO" VARCHAR2(50), 
	 PRIMARY KEY ("IDREGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
