CREATE SEQUENCE SICAS_OC.SESAS_DATGEN_SEQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  CACHE 20
  NOORDER
/

CREATE TABLE SICAS_OC.SESAS_DATGEN
(
  CODCIA            NUMBER(14)    NOT NULL,
  CODEMPRESA        NUMBER(14)    NOT NULL,
  CODREPORTE        VARCHAR2(30)  NOT NULL,
  CODUSUARIO        VARCHAR2(30)  NOT NULL,
  IDSECUENCIA       NUMBER    ,--    NOT NULL,
  NUMPOLIZA         VARCHAR2(30)  NOT NULL,
  NUMCERTIFICADO    VARCHAR2(20)  NOT NULL,
  TIPOSEGURO        VARCHAR2(1),
  MONEDA            VARCHAR2(2),
  ENTIDADASEGURADO  VARCHAR2(2),
  FECINIVIG         DATE,
  FECFINVIG         DATE,
  FECALTCERT        DATE,
  FECBAJCERT        DATE,
  FECNACIM          DATE,
  FECEMISION        DATE,
  SEXO              VARCHAR2(1),
  STATUSCERT        VARCHAR2(1),
  FORMAVTA          VARCHAR2(2),
  SUBTIPOSEG        VARCHAR2(1),
  TIPODIVIDENDO     VARCHAR2(1),
  ANIOPOLIZA        NUMBER(2),
  OCUPACION         VARCHAR2(3),
  TIPORIESGO        VARCHAR2(1),
  NUMASEGPOL        NUMBER(9),
  PLANPOLIZA        VARCHAR2(2),
  MODALIDADPOLIZA   VARCHAR2(2),
  FORMAPAGO         VARCHAR2(1),
  PLAZOPAGOPRIMA    NUMBER(2),
  COASEGURO         VARCHAR2(1),
  EMISION           VARCHAR2(1),
  CANTCERTIFICADOS  NUMBER(8),
  PRIMACEDIDA       NUMBER(18,2),
  COMISIONDIRECTA   NUMBER(18,2),
  SDOFONINV         NUMBER(23,2),
  SDOFONADM         NUMBER(23,2),
  MONTODIVIDENDO    NUMBER(23,2),
  MONTORESCATE      NUMBER(18,2),
  MODASUMASEG       VARCHAR2(1),
  IDPOLIZA          NUMBER(14),
  IDETPOL           NUMBER(14),
  CODASEGURADO      NUMBER(14),
  TIPODETALLE       VARCHAR2(3),
  FECHAINSERT       DATE       DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

COMMENT ON TABLE SICAS_OC.SESAS_DATGEN IS 'Información de Datos Generales para los reportes de SESAS';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CODREPORTE IS 'Código del Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CODUSUARIO IS 'Código del Usuario que Genera el Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.IDSECUENCIA IS 'Identificador Secuencial del Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.NUMPOLIZA IS 'Número de Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.NUMCERTIFICADO IS 'Número de Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.TIPOSEGURO IS 'Tipo de Seguro';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.MONEDA IS 'Moneda';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.ENTIDADASEGURADO IS 'Entidad del Asegurado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECINIVIG IS 'Fecha de Inicio de Vigencia';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECFINVIG IS 'Fecha de Fin de Vigencia';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECALTCERT IS 'Fecha de Alta del Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECBAJCERT IS 'Fecha de Baja del Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECNACIM IS 'Fecha de Nacimiento';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FECEMISION IS 'Fecha de Emisión';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.SEXO IS 'Sexo';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.STATUSCERT IS 'Estatus del Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FORMAVTA IS 'Forma de Venta';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.SUBTIPOSEG IS 'Subtipo de Seguro';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.TIPODIVIDENDO IS 'Tipo de Dividendo';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.ANIOPOLIZA IS 'Año Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.OCUPACION IS 'Ocupación/Giro Económico';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.TIPORIESGO IS 'Tipo de Riesgo';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.NUMASEGPOL IS 'Número de Asegurados Póliza Concentrada';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.PLANPOLIZA IS 'Plan de la Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.MODALIDADPOLIZA IS 'Modalidad de la Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.FORMAPAGO IS 'Forma de Pago';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.PLAZOPAGOPRIMA IS 'Plazo de Pago de Prima';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.COASEGURO IS 'Coaseguro';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.EMISION IS 'Emisión';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CANTCERTIFICADOS IS 'Número de Certificados';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.PRIMACEDIDA IS 'Prima Cedida';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.COMISIONDIRECTA IS 'Comisión Directa';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.SDOFONINV IS 'Saldo del Fondo de Inversión';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.SDOFONADM IS 'Saldo del Fondo de Administración';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.MONTODIVIDENDO IS 'Monto de Dividendo';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.MONTORESCATE IS 'Monto de Rescate';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.MODASUMASEG IS 'Modalidad de Suma Asegurada';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.IDPOLIZA IS 'Identificador de la Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.IDETPOL IS 'Identificador del Detalle de la Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.CODASEGURADO IS 'Código del Asegurado';
COMMENT ON COLUMN SICAS_OC.SESAS_DATGEN.TIPODETALLE IS 'Tipo de Detalle';


CREATE UNIQUE INDEX SICAS_OC.SESAS_DATGEN_PK ON SICAS_OC.SESAS_DATGEN
( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO )
LOGGING
TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.SESAS_DATGEN ADD (
  CONSTRAINT SESAS_DATGEN_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO )
  USING INDEX SICAS_OC.SESAS_DATGEN_PK);
/

CREATE OR REPLACE PUBLIC SYNONYM SESAS_DATGEN FOR SICAS_OC.SESAS_DATGEN;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.SESAS_DATGEN TO PUBLIC;
/