CREATE SEQUENCE SICAS_OC.SEQ_SESAASEGMODELO
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    ORDER;
/

CREATE TABLE SICAS_OC.SESA_ASEGMODELO (
    CODCIA          NUMBER          NOT NULL,
    CODEMPRESA      NUMBER          NOT NULL,
    COD_ASEGURADO   VARCHAR2(30)    NOT NULL,
    USUARIOREGISTRO VARCHAR2(30)    DEFAULT USER,
    FECHAINSERT     DATE        DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

CREATE UNIQUE INDEX SICAS_OC.IX_SESAASEGMODELO ON
    SICAS_OC.SESA_ASEGMODELO(CODCIA,CODEMPRESA,COD_ASEGURADO)
    TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.SESA_ASEGMODELO ADD(
    CONSTRAINT PK_SESAASEGMODELO
    PRIMARY KEY (CODCIA,CODEMPRESA,COD_ASEGURADO)
    USING INDEX SICAS_OC.IX_SESAASEGMODELO);
/

COMMENT ON TABLE SICAS_OC.SESA_ASEGMODELO IS 'Tabla de sesas que contiene  los c�digos de asegurado correctos';
COMMENT ON COLUMN SICAS_OC.SESA_ASEGMODELO.CODCIA IS 'Codigo de la Compañía';
COMMENT ON COLUMN SICAS_OC.SESA_ASEGMODELO.CODEMPRESA IS 'Codigo de la Empresa';
COMMENT ON COLUMN SICAS_OC.SESA_ASEGMODELO.COD_ASEGURADO IS 'Codigo del Asegurado modelo valido para sesas.';
COMMENT ON COLUMN SICAS_OC.SESA_ASEGMODELO.USUARIOREGISTRO IS 'Usuario con el que se registro el evento';


CREATE OR REPLACE PUBLIC SYNONYM SEQ_SESAASEGMODELO FOR SICAS_OC.SEQ_SESAASEGMODELO;
/

CREATE OR REPLACE PUBLIC SYNONYM SESA_ASEGMODELO FOR SICAS_OC.SESA_ASEGMODELO;
/

GRANT INSERT,UPDATE,DELETE,SELECT ON SICAS_OC.SESA_ASEGMODELO TO PUBLIC;
/
