--
-- SESAS_DATGEN_TRG  (Trigger) 
--
--  Dependencies: 
--   SESAS_DATGEN (Table)
--
CREATE OR REPLACE TRIGGER SICAS_OC.SESAS_DATGEN_TRG
BEFORE INSERT
ON SICAS_OC.SESAS_DATGEN
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDSECUENCIA
  :new.IDSECUENCIA := SICAS_OC.SESAS_DATGEN_SEQ.nextval;
END SESAS_DATGEN_TRG;
/