CREATE TABLE SICAS_OC.SESAS_EMISION
(
  CODCIA          NUMBER(14)    NOT NULL,
  CODEMPRESA      NUMBER(14)    NOT NULL,
  CODREPORTE      VARCHAR2(30)  NOT NULL,
  CODUSUARIO      VARCHAR2(30)  NOT NULL,
  NUMPOLIZA       VARCHAR2(30)  NOT NULL,
  NUMCERTIFICADO  VARCHAR2(20)  NOT NULL,
  COBERTURA       VARCHAR2(2)   NOT NULL,
  TIPOSUMASEG     VARCHAR2(1) ,
  PERIODOESPERA   NUMBER(2) ,
  SUMAASEGURADA   NUMBER(23,2) ,
  PRIMAEMITIDA    NUMBER(18,2) ,
  PRIMADEVENGADA  NUMBER(18,2) ,
  NUMDIASRENTA    NUMBER(3) ,
  TIPOEXTRAPRIMA  VARCHAR2(1) ,
  ORDENSESAS      NUMBER(5),
  FECHAINSERT        DATE       DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

COMMENT ON TABLE SICAS_OC.SESAS_EMISION IS 'Información de Emisión para los reportes de SESAS';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.CODREPORTE IS 'Código del Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.CODUSUARIO IS 'Código del Usuario que Genera el Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.NUMPOLIZA IS 'Número de Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.NUMCERTIFICADO IS 'Número de Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.COBERTURA IS 'Cobertura';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.TIPOSUMASEG IS 'Tipo de Suma Asegurada';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.PERIODOESPERA IS 'Periodo de Espera';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.SUMAASEGURADA IS 'Suma Asegurada';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.PRIMAEMITIDA IS 'Prima Emitida';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.PRIMADEVENGADA IS 'Prima Devengada';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.NUMDIASRENTA IS 'Número de Días de Renta';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.TIPOEXTRAPRIMA IS 'Tipo de Extra Prima';
COMMENT ON COLUMN SICAS_OC.SESAS_EMISION.ORDENSESAS IS 'Orden Interno para las Coberturas';
/

CREATE UNIQUE INDEX SICAS_OC.SESAS_EMISION_PK ON SICAS_OC.SESAS_EMISION
( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO, COBERTURA )
LOGGING
TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.SESAS_EMISION ADD (
  CONSTRAINT SESAS_EMISION_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO, COBERTURA )
  USING INDEX SICAS_OC.SESAS_EMISION_PK);
/

CREATE OR REPLACE PUBLIC SYNONYM SESAS_EMISION FOR SICAS_OC.SESAS_EMISION;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.SESAS_EMISION TO PUBLIC;
/