DROP TABLE SICAS_OC.SESAS_SINIESTROS;
/

CREATE TABLE SICAS_OC.SESAS_SINIESTROS
(
  CODCIA             NUMBER(14)    NOT NULL,
  CODEMPRESA         NUMBER(14)    NOT NULL,
  CODREPORTE         VARCHAR2(30)  NOT NULL,
  CODUSUARIO         VARCHAR2(30)  NOT NULL,
  NUMPOLIZA          VARCHAR2(30)  NOT NULL,
  NUMCERTIFICADO     VARCHAR2(20)  NOT NULL,
  NUMSINIESTRO       VARCHAR2(20)  NOT NULL,
  COBERTURA          VARCHAR2(2)    NOT NULL,
  NUMRECLAMACION     VARCHAR2(20) ,
  FECOCUSIN          DATE ,
  FECREPREC          DATE ,
  FECCONSIN          DATE ,
  FECPAGSIN          DATE ,
  STATUSRECLAMACION  VARCHAR2(1) ,
  ENTOCUSIN          VARCHAR2(2) ,
  MONTORECLAMADO     NUMBER(23,2) ,
  CAUSASINIESTRO     VARCHAR2(4) ,
  MONTODEDUCIBLE     NUMBER(18,2) ,
  MONTOCOASEGURO     NUMBER(18,2) ,
  MONTOPAGSIN        NUMBER(18,2) ,
  MONTORECREA        NUMBER(18,2) ,
  MONTODIVIDENDO     NUMBER(18,2) ,
  TIPMOVREC          VARCHAR2(1) ,
  MONTOVENCIMIENTO   NUMBER(18,2) ,
  MONTORESCATE       NUMBER(18,2) ,
  TIPOGASTO          VARCHAR2(2) ,
  PERIODOESPERA      NUMBER(2) ,
  TIPOPAGO           VARCHAR2(1) ,
  SEXO               VARCHAR2(1) ,
  FECNACIM           DATE ,
  ORDENSESAS         NUMBER(5),
  FECHAINSERT        DATE       DEFAULT SYSDATE
) TABLESPACE TS_SICASOC;
/

COMMENT ON TABLE SICAS_OC.SESAS_SINIESTROS IS 'Información de Siniestros para los reportes de SESAS';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.CODREPORTE IS 'Código del Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.CODUSUARIO IS 'Código del Usuario que Genera el Reporte';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.NUMPOLIZA IS 'Número de Póliza';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.NUMCERTIFICADO IS 'Número de Certificado';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.NUMSINIESTRO IS 'Número de Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.COBERTURA IS 'Cobertura Afectada';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.NUMRECLAMACION IS 'Número de Reclamación';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.FECOCUSIN IS 'Fecha de Ocurrencia del Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.FECREPREC IS 'Fecha de Reporte de Reclamación/Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.FECCONSIN IS 'Fecha de Contabilización del Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.FECPAGSIN IS 'Fecha de Pago del Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.STATUSRECLAMACION IS 'Estatus de la Reclamación/Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.ENTOCUSIN IS 'Entidad de Ocurrencia del Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTORECLAMADO IS 'Monto Reclamación';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.CAUSASINIESTRO IS 'Causa de Siniestro o Reclamación';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTODEDUCIBLE IS 'Monto de Deducible';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTOCOASEGURO IS 'Monto de Coaseguro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTOPAGSIN IS 'Monto Pagado del Siniestro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTORECREA IS 'Monto Recuperado de Reaseguro';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTODIVIDENDO IS 'Monto de Dividendo';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.TIPMOVREC IS 'Tipo de Movimiento de Reclamación';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTOVENCIMIENTO IS 'Monto de Vencimiento';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.MONTORESCATE IS 'Monto de Rescate';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.TIPOGASTO IS 'Tipo de Gasto';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.PERIODOESPERA IS 'Periodo de Espera';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.TIPOPAGO IS 'Tipo de Pago';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.SEXO IS 'Sexo';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.FECNACIM IS 'Fecha de Nacimiento';
COMMENT ON COLUMN SICAS_OC.SESAS_SINIESTROS.ORDENSESAS IS 'Orden Interno para las Coberturas';


CREATE UNIQUE INDEX SICAS_OC.SESAS_SINIESTROS_PK ON SICAS_OC.SESAS_SINIESTROS
( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO, NUMSINIESTRO, COBERTURA )
TABLESPACE IDX_SICASOC;
/

ALTER TABLE SICAS_OC.SESAS_SINIESTROS ADD (
  CONSTRAINT SESAS_SINIESTROS_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, NUMPOLIZA, NUMCERTIFICADO, NUMSINIESTRO, COBERTURA )
  USING INDEX SICAS_OC.SESAS_SINIESTROS_PK);
/

CREATE OR REPLACE PUBLIC SYNONYM SESAS_SINIESTROS FOR SICAS_OC.SESAS_SINIESTROS;
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.SESAS_SINIESTROS TO PUBLIC;
/