
  CREATE TABLE "SICAS_OC"."SINIESTRO" 
   (	"IDSINIESTRO" NUMBER(14,0) CONSTRAINT "SYS_C007201" NOT NULL ENABLE, 
	"IDPOLIZA" NUMBER(14,0) CONSTRAINT "SYS_C007200" NOT NULL ENABLE, 
	"NUMSINIREF" VARCHAR2(30), 
	"TIPO_SINIESTRO" VARCHAR2(6), 
	"FEC_OCURRENCIA" DATE, 
	"FEC_NOTIFICACION" DATE, 
	"STS_SINIESTRO" VARCHAR2(3), 
	"FECSTS" DATE, 
	"FECANUL" DATE, 
	"MOTIV_ANUL" VARCHAR2(6), 
	"DESC_SINIESTRO" VARCHAR2(4000), 
	"MONTO_RESERVA_LOCAL" NUMBER(18,2), 
	"MONTO_RESERVA_MONEDA" NUMBER(18,2), 
	"MONTO_PAGO_LOCAL" NUMBER(18,2), 
	"MONTO_PAGO_MONEDA" NUMBER(18,2), 
	"COD_MONEDA" VARCHAR2(5), 
	"IDETPOL" NUMBER(14,0), 
	"NUM_BIEN" NUMBER(14,0), 
	"MONTO_INDEMINZACION" NUMBER(18,2), 
	"DEDUCIBLE" NUMBER(18,2), 
	"TIPO_INDEMNIZACION" VARCHAR2(6), 
	"AJUSTADOR" VARCHAR2(6), 
	"CODCIA" NUMBER(14,0) DEFAULT 1, 
	"MOTIVO_DE_SINIESTRO" VARCHAR2(6), 
	"CODEMPRESA" NUMBER(14,0) DEFAULT 1, 
	"NUMSINNOM" VARCHAR2(20), 
	"NUMSEMANA" NUMBER(2,0) DEFAULT 0, 
	"CODPAISOCURR" VARCHAR2(3), 
	"CODPROVOCURR" VARCHAR2(3), 
	"CODPROVEEDOR" NUMBER(10,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"IDAUTORIZACION" NUMBER(14,0), 
	"IDCOLEINDI" VARCHAR2(6), 
	"IDTPORIGEN" VARCHAR2(6) DEFAULT 'NORMAL', 
	"CODUSUARIO" VARCHAR2(30) DEFAULT USER, 
	"FECREGISTRO" DATE DEFAULT TRUNC(SYSDATE), 
	"SUBMOTIVO_SINIESTRO" VARCHAR2(6), 
	"IDAUTORIZACION_FLUJO" VARCHAR2(6), 
	"USUARIO_AUTORIZA_FLUJO" VARCHAR2(30), 
	"FEAUTORIZACION_FLUJO" DATE, 
	"CODRIESGOREA" VARCHAR2(6), 
	"IDCONTRIBUTORIO" VARCHAR2(6), 
	"EMPRESA_LABORA" VARCHAR2(300), 
	"IDCREDITO" VARCHAR2(30), 
	"RFC_ASEGURADO" VARCHAR2(20), 
	"TP_ASEGURADO" VARCHAR2(6), 
	"CODMUNICIPIO" VARCHAR2(3), 
	"NOM_MEDICO_CERTIFICA" VARCHAR2(300), 
	"ID_CEDULA_MEDICA" VARCHAR2(20), 
	 CONSTRAINT "SINIESTRO_PK" PRIMARY KEY ("IDSINIESTRO", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
