
  CREATE TABLE "SICAS_OC"."SOLICITUD_COBERTURAS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDSOLICITUD" NUMBER(14,0) NOT NULL ENABLE, 
	"IDETSOL" NUMBER(18,2) NOT NULL ENABLE, 
	"CODCOBERT" VARCHAR2(6) NOT NULL ENABLE, 
	"SUMAASEG_LOCAL" NUMBER(18,2), 
	"SUMAASEG_MONEDA" NUMBER(18,2), 
	"TASA" NUMBER(18,6), 
	"PRIMA_MONEDA" NUMBER(18,2), 
	"PRIMA_LOCAL" NUMBER(18,2), 
	"DEDUCIBLE_LOCAL" NUMBER(14,2), 
	"DEDUCIBLE_MONEDA" NUMBER(14,2), 
	 PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDSOLICITUD", "IDETSOL", "CODCOBERT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCIA", "CODEMPRESA", "IDSOLICITUD", "IDETSOL")
	  REFERENCES "SICAS_OC"."SOLICITUD_DETALLE" ("CODCIA", "CODEMPRESA", "IDSOLICITUD", "IDETSOL") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
