
  CREATE TABLE "SICAS_OC"."SUB_PROCESO" 
   (	"IDPROCESO" NUMBER(10,0) NOT NULL ENABLE, 
	"CODSUBPROCESO" VARCHAR2(6) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	"STSSUBPROC" VARCHAR2(3), 
	"INDGENCONTABILIDAD" VARCHAR2(1), 
	"CODPROCESOCONT" VARCHAR2(6), 
	"INDTAREA" VARCHAR2(1), 
	"PARAMETRO_TIEMPO" VARCHAR2(6), 
	"TIEMPO" NUMBER(4,2), 
	"CODPROCESO" VARCHAR2(6), 
	"INDFECEQUIV" VARCHAR2(1), 
	 PRIMARY KEY ("IDPROCESO", "CODSUBPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
