
  CREATE TABLE "SICAS_OC"."SUBESPECIALIDAD_MEDICA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODESPECIALIDAD" VARCHAR2(10) NOT NULL ENABLE, 
	"CODSUBESPECIALIDAD" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCSUBESPECIALIDAD" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "PK_SUBESPECIALIDAD_MEDICA" PRIMARY KEY ("CODCIA", "CODESPECIALIDAD", "CODSUBESPECIALIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_SUBESPECIALIDAD_MEDICA" FOREIGN KEY ("CODCIA", "CODESPECIALIDAD")
	  REFERENCES "SICAS_OC"."ESPECIALIDAD_MEDICA" ("CODCIA", "CODESPECIALIDAD") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
