
  CREATE TABLE "SICAS_OC"."T_EDOSCTA_ARRASTRE" 
   (	"COD_AGENTE" NUMBER(18,0), 
	"FECHA_DESDE" DATE, 
	"FECHA_HASTA" DATE, 
	"NIVEL_AGENTE" VARCHAR2(50), 
	"DESCRIPCION_RAMO" VARCHAR2(200), 
	"CODNIVEL" NUMBER(10,0), 
	"NUMPOLUNICO" VARCHAR2(30), 
	"FEC_GENERACION" DATE, 
	"IDPOLIZA" NUMBER(14,0), 
	"IDENDOSO" VARCHAR2(14), 
	"NOMCLIENTE" VARCHAR2(350), 
	"RECIBO" VARCHAR2(16), 
	"MONEDA" VARCHAR2(5), 
	"PRIMA_COMISINABLE_LOCAL" NUMBER(18,2), 
	"MONTO_COMISION" NUMBER(18,2), 
	"COMI_MONEDA" NUMBER(18,2), 
	"STT_COMISION" VARCHAR2(6), 
	"STATUS_PAGOF" VARCHAR2(6), 
	"PAGADO" NUMBER(18,2), 
	"POR_PAGAR" NUMBER(18,2), 
	"MTOIVA" NUMBER(18,2), 
	"MTOIVARET" NUMBER(18,2), 
	"MTOISR" NUMBER(18,2), 
	"MTOISRRET" NUMBER(18,2), 
	"SUBTOTAL" NUMBER(18,2), 
	"CASE_COMISION" NUMBER(18,2), 
	"CASE_MTOIVA" NUMBER(18,2), 
	"CASE_MTOIVARET" NUMBER(18,2), 
	"CASE_MTOISR" NUMBER(18,2), 
	"CASE_MTOISRRET" NUMBER(18,2), 
	"POR_PAGAR_SHOWON" NUMBER(18,2), 
	"POR_PAGAR_COMISION" NUMBER(18,2), 
	"POR_PAGAR_MTOIVA" NUMBER(18,2), 
	"POR_PAGAR_MTOIVARET" NUMBER(18,2), 
	"POR_PAGAR_MTOISR" NUMBER(18,2), 
	"CASE_MTOPRIMAFACTURA" NUMBER(18,2), 
	"EN_CONTRA" NUMBER(18,2), 
	"CODTIPOPLAN" VARCHAR2(6), 
	"A_FAVOR" NUMBER(18,2), 
	"IDCOMISION" NUMBER(14,0), 
	"NOMBRE_AGENTE" VARCHAR2(150), 
	"DIRECRES" VARCHAR2(150), 
	"NUM_TRIBUTARIO" VARCHAR2(20), 
	"NUMCEDULA" VARCHAR2(30), 
	"FECVENCIMIENTO" DATE, 
	"TIPO_PERSONA" VARCHAR2(20), 
	"NUM_DOC_IDENTIFICACION" VARCHAR2(20), 
	"POR_COM_DISTRIBUIDA" NUMBER(9,6), 
	"PORC_COM_PROPORCIONAL" NUMBER(9,6), 
	"PRIMA_NETA" NUMBER(18,2), 
	"MTOPRIMAFACTURA" NUMBER(18,2), 
	"NOMINA_COM" NUMBER(14,0), 
	"FECHA_PAGO" DATE, 
	 CONSTRAINT "SALDOS_ARRASTRE_PK" PRIMARY KEY ("COD_AGENTE", "FECHA_DESDE", "FECHA_HASTA", "IDCOMISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
