
  CREATE TABLE "SICAS_OC"."T_EDO_CTA_FONDOS" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"CODASEGURADO" NUMBER(14,0), 
	"TPREPORTE" NUMBER(2,0), 
	"ORDEN" NUMBER(5,0), 
	"NOM_CONCEPTO" VARCHAR2(200), 
	"IMPTE_CARGO" NUMBER(28,6), 
	"IMPTE_ABONO" NUMBER(28,6), 
	"IMPTE_SALDO" NUMBER(28,6), 
	"IDFONDO" NUMBER(14,0), 
	"IDMOVIMIENTO" NUMBER(14,0), 
	"CODCPTOMOV" VARCHAR2(10), 
	"TIPOFONDO" VARCHAR2(10), 
	"FEMOVTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
