
  CREATE TABLE "SICAS_OC"."T_OC_DETALLE_COMISION_VIFLEX" 
   (	"COD_AGENTE" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"NUMDOCTO" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"COD_MONEDA" VARCHAR2(5), 
	"COMISION_LOCAL" NUMBER(18,2), 
	"COMISION_MONEDA" NUMBER(18,2), 
	"TIPORAMO" VARCHAR2(3), 
	 CONSTRAINT "DETALLE_COMISION_VIFLEX_PK" PRIMARY KEY ("COD_AGENTE", "IDPOLIZA", "NUMDOCTO", "IDETPOL", "TIPORAMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
