
  CREATE TABLE "SICAS_OC"."T_SALDOS_COMISIONES_ANIOMES" 
   (	"CODCIA" NUMBER(14,0), 
	"COD_AGENTE" NUMBER(18,0), 
	"FE_INI_SALDO" DATE, 
	"COD_MONEDA" VARCHAR2(5), 
	"MONTO_SALDO_FINAL" NUMBER(18,2), 
	 CONSTRAINT "SALDOS_COMIS_ANIOMES_PK" PRIMARY KEY ("CODCIA", "COD_AGENTE", "COD_MONEDA", "FE_INI_SALDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
