CREATE TABLE SICAS_OC.TA_CARGALYTPLD(
                CODCIA  	NUMBER,
                CODEMPRESA  NUMBER,
                IDREGISTRO  NUMBER,
                ESTATUS 	VARCHAR2(4000),
                FECINSERT   DATE DEFAULT SYSDATE,
                USRINSERT   VARCHAR2(20) DEFAULT USER);
/

CREATE UNIQUE INDEX SICAS_OC.IDX_TA_CARGALYTPLD_1 ON
    SICAS_OC.TA_CARGALYTPLD(CODCIA,CODEMPRESA,IDREGISTRO,USRINSERT);
    
ALTER TABLE SICAS_OC.TA_CARGALYTPLD ADD (
    CONSTRAINT PK_TA_CARGALYTPLD 
    PRIMARY KEY (CODCIA,CODEMPRESA,IDREGISTRO,USRINSERT)
    USING INDEX SICAS_OC.IDX_TA_CARGALYTPLD_1);

CREATE OR REPLACE PUBLIC SYNONYM TA_CARGALYTPLD FOR TA_CARGALYTPLD;

GRANT SELECT,INSERT,UPDATE,DELETE ON SICAS_OC.TA_CARGALYTPLD TO PUBLIC;
/
