
  CREATE TABLE "SICAS_OC"."TAB_VALORES_GARANTIZADOS" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"IDETPOL" NUMBER(14,0), 
	"IDENDOSO" NUMBER(14,0), 
	"COD_ASEGURADO" NUMBER(14,0), 
	"CODCOBERT" VARCHAR2(6), 
	"ANIOPOLIZA" NUMBER(3,0), 
	"ANIO" NUMBER(3,0), 
	"EDAD" NUMBER(3,0), 
	"COD_MONEDA" VARCHAR2(5 CHAR), 
	"PRIMA_ANUAL_LOCAL" NUMBER(18,2), 
	"PRIMA_ANUAL_MONEDA" NUMBER(18,2), 
	"SUMA_ASEGURADA_LOCAL" NUMBER(18,2), 
	"SUMA_ASEGURADA_MONEDA" NUMBER(18,2), 
	"VALOR_RESCATE_LOCAL" NUMBER(18,2), 
	"VALOR_RESCATE_MONEDA" NUMBER(18,2), 
	"SEGURO_SALDADO_LOCAL" NUMBER(18,2), 
	"SEGURO_SALDADO_MONEDA" NUMBER(18,2), 
	"PRORROGADO_ANIOS" NUMBER(3,0), 
	"PRORROGADO_DIAS" NUMBER(15,6), 
	"EFECTIVO_FINAL_LOCAL" NUMBER(18,2), 
	"EFECTIVO_FINAL_MONEDA" NUMBER(18,2), 
	"USUARIO_MODIFICO" VARCHAR2(30 CHAR) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_TAB_VALORES_GARANTIZADOS" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "IDENDOSO", "COD_ASEGURADO", "CODCOBERT", "ANIOPOLIZA", "ANIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
