
  CREATE TABLE "SICAS_OC"."TABLA_SMS" 
   (	"IDTABLA_SMS" NUMBER(22,0), 
	"PARA" VARCHAR2(8), 
	"DE" VARCHAR2(8), 
	"MENSAJE" VARCHAR2(200), 
	"ENNREC" VARCHAR2(1), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
