
  CREATE TABLE "SICAS_OC"."TASAS_CAMBIO_FACTURAS" 
   (	"FECHA_HORA_CAMBIO" DATE NOT NULL ENABLE, 
	"COD_MONEDA" VARCHAR2(5) NOT NULL ENABLE, 
	"IDFACTURA" NUMBER(14,0) NOT NULL ENABLE, 
	"TASA_CAMBIO_EMISION" NUMBER(28,10), 
	"TASA_CAMBIO_COBRO" NUMBER(28,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
