
  CREATE TABLE "SICAS_OC"."TELEFONOS_CLIENTE" 
   (	"CODCLIENTE" NUMBER(14,0) NOT NULL ENABLE, 
	"CORRELATIVO_CONTACTO" NUMBER(5,0) NOT NULL ENABLE, 
	"NUM_TELEFONO" VARCHAR2(15), 
	"TIPO_TELEFONO" VARCHAR2(3), 
	"EXT_TELEFONO" VARCHAR2(10), 
	 PRIMARY KEY ("CODCLIENTE", "CORRELATIVO_CONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "SICAS_OC"."CLIENTES" ("CODCLIENTE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
