
  CREATE TABLE "SICAS_OC"."TEMP_DETALLE_COMISION" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDCOMISION" NUMBER(14,0) NOT NULL ENABLE, 
	"CODCONCEPTO" VARCHAR2(6) NOT NULL ENABLE, 
	"MONTO_MON_LOCAL" NUMBER(14,2), 
	"MONTO_MON_EXTRANJERA" NUMBER(14,2), 
	"ESTADO" VARCHAR2(6), 
	"ORIGEN" VARCHAR2(1) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
