-- Create table
DROP PUBLIC SYNONYM TEMP_RECIBOS_PROV;
DROP TABLE SICAS_OC.TEMP_RECIBOS_PROV;

CREATE TABLE SICAS_OC.TEMP_RECIBOS_PROV
(
  IDCONSECUTIVO      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IDPOLIZA           NUMBER(14) not null,
  IDETPOL            NUMBER(14),
  IDFACTURAORIG      NUMBER(14),
  IDFACTURAINI       NUMBER(14),
  IDNCRINICIAL       NUMBER(14),
  IDFACTURA1         NUMBER(14),
  IDFACTURA2         NUMBER(14),
  IDNCR1             NUMBER(14)
)
tablespace TS_SICASOC
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
/
-- Add comments to the columns 
comment on column TEMP_RECIBOS_PROV.IDCONSECUTIVO
  is 'Es el numero consecutivo del registro';
comment on column TEMP_RECIBOS_PROV.IDPOLIZA
  is 'Identificador de Poliza';
comment on column TEMP_RECIBOS_PROV.IDETPOL
  is 'Identificador de Certificado';
comment on column TEMP_RECIBOS_PROV.IDFACTURAORIG
  is 'Identificador de Recibo Original';
comment on column TEMP_RECIBOS_PROV.IDFACTURAINI
  is 'Identificador de Recibo Provicional inicial';
comment on column TEMP_RECIBOS_PROV.IDNCRINICIAL
  is 'Identificador de Nota de Credito Provicional Inicial';
comment on column TEMP_RECIBOS_PROV.IDFACTURA1
  is 'Identificador de Recibo original Rehabilitado';
comment on column TEMP_RECIBOS_PROV.IDFACTURA2
  is 'Identificador de Recibo Provicional Rehabilitado';
comment on column TEMP_RECIBOS_PROV.IDNCR1
  is 'Identificador de Nota de Credito Provicional Rehabilitado';
/
-- Create/Recreate indexes 
create index IDX_TEMP_RECIBOS_PROV_1 on TEMP_RECIBOS_PROV (IDCONSECUTIVO, IDPOLIZA, IDETPOL)
  tablespace TS_SICASOC
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
/
 CREATE PUBLIC SYNONYM TEMP_RECIBOS_PROV FOR TEMP_RECIBOS_PROV;

/
-- Grant/Revoke object privileges 
grant select on SICAS_OC.TEMP_RECIBOS_PROV to ROL_CONSULTA_SICAS;
grant select, insert, update, delete, alter on SICAS_OC.TEMP_RECIBOS_PROV to ROL_MODIFICA_SICAS;

