
  CREATE TABLE "SICAS_OC"."TEMP_PARA_FACTURAR" 
   (	"UUID" VARCHAR2(50), 
	"TOTAL" NUMBER(28,2), 
	"TIPO" VARCHAR2(10), 
	"IDRECIBONCR" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
