--
-- TEMP_ARCHIVOS_THONA  (Table) 
--
CREATE TABLE SICAS_OC.TEMP_ARCHIVOS_THONA
(
  CODCIA      NUMBER(14)                        NOT NULL,
  CODEMPRESA  NUMBER(14)                        NOT NULL,
  CODREPORTE  VARCHAR2(30 BYTE)                 NOT NULL,
  CODUSUARIO  VARCHAR2(30 BYTE)                 NOT NULL,
  ARCHIVO     BLOB                              DEFAULT EMPTY_BLOB()
)
LOB (ARCHIVO) STORE AS (
  TABLESPACE  TS_SICASOC
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  PCTVERSION  10
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          1M
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.TEMP_ARCHIVOS_THONA IS 'Registro Temporal de Archivos THONA'
/

COMMENT ON COLUMN SICAS_OC.TEMP_ARCHIVOS_THONA.CODCIA IS 'Código de la Compañía'
/

COMMENT ON COLUMN SICAS_OC.TEMP_ARCHIVOS_THONA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.TEMP_ARCHIVOS_THONA.CODREPORTE IS 'Código del Reporte'
/

COMMENT ON COLUMN SICAS_OC.TEMP_ARCHIVOS_THONA.CODUSUARIO IS 'Código del Usuario que Genera el Reporte'
/

COMMENT ON COLUMN SICAS_OC.TEMP_ARCHIVOS_THONA.ARCHIVO IS 'Archivo Generado'
/



--
-- TEMP_ARCHIVOS_THONA_PK  (Index) 
--
--  Dependencies: 
--   TEMP_ARCHIVOS_THONA (Table)
--
CREATE UNIQUE INDEX SICAS_OC.TEMP_ARCHIVOS_THONA_PK ON SICAS_OC.TEMP_ARCHIVOS_THONA
(CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO)
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table TEMP_ARCHIVOS_THONA 
-- 
ALTER TABLE SICAS_OC.TEMP_ARCHIVOS_THONA ADD (
  CONSTRAINT TEMP_ARCHIVOS_THONA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO)
  USING INDEX SICAS_OC.TEMP_ARCHIVOS_THONA_PK
  ENABLE VALIDATE)
/

CREATE OR REPLACE PUBLIC SYNONYM TEMP_ARCHIVOS_THONA FOR SICAS_OC.TEMP_ARCHIVOS_THONA;
/

GRANT DELETE, UPDATE, SELECT, INSERT ON SICAS_OC.TEMP_ARCHIVOS_THONA TO PUBLIC;
/