
  CREATE TABLE "SICAS_OC"."TEMP_POLIZAS_SESAS" 
   (	"IDPOLIZA" NUMBER(14,0), 
	"STSPOLIZA" VARCHAR2(3), 
	"TIPOADMINISTRACION" VARCHAR2(6), 
	"IDTIPOSEG" VARCHAR2(6), 
	"PLANCOB" VARCHAR2(15), 
	"FECINIVIG" DATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
