--
-- TEMP_REPORTES_THONA  (Table) 
--
CREATE TABLE SICAS_OC.TEMP_REPORTES_THONA
(
  CODCIA       NUMBER(14)                       NOT NULL,
  CODEMPRESA   NUMBER(14)                       NOT NULL,
  CODREPORTE   VARCHAR2(30 BYTE)                NOT NULL,
  CODUSUARIO   VARCHAR2(30 BYTE)                NOT NULL,
  IDSECUENCIA  NUMBER                           NOT NULL,
  LINEA        VARCHAR2(4000 BYTE)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE SICAS_OC.TEMP_REPORTES_THONA IS 'Registro Temporal de Reportes THONA'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.CODCIA IS 'Código de la Compañía'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.CODREPORTE IS 'Código del Reporte'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.CODUSUARIO IS 'Código del Usuario que Genera el Reporte'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.IDSECUENCIA IS 'Identificador Secuencial del Reporte'
/

COMMENT ON COLUMN SICAS_OC.TEMP_REPORTES_THONA.LINEA IS 'Datos por Línea del Reporte'
/

--
-- TEMP_REPORTES_THONA_PK  (Index) 
--
--  Dependencies: 
--   TEMP_REPORTES_THONA (Table)
--
CREATE UNIQUE INDEX SICAS_OC.TEMP_REPORTES_THONA_PK ON SICAS_OC.TEMP_REPORTES_THONA
(CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, IDSECUENCIA)
LOGGING
TABLESPACE TS_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

--
-- TEMP_REPORTES_THONA_TRG  (Trigger) 
--
--  Dependencies: 
--   TEMP_REPORTES_THONA (Table)
--
CREATE OR REPLACE TRIGGER SICAS_OC.TEMP_REPORTES_THONA_TRG
BEFORE INSERT
ON SICAS_OC.TEMP_REPORTES_THONA
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDSECUENCIA
  :new.IDSECUENCIA := SICAS_OC.TEMP_REPORTES_THONA_SEQ.nextval;
END TEMP_REPORTES_THONA_TRG;
/

-- 
-- Non Foreign Key Constraints for Table TEMP_REPORTES_THONA 
-- 
ALTER TABLE SICAS_OC.TEMP_REPORTES_THONA ADD (
  CONSTRAINT TEMP_REPORTES_THONA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODREPORTE, CODUSUARIO, IDSECUENCIA)
  USING INDEX SICAS_OC.TEMP_REPORTES_THONA_PK
  ENABLE VALIDATE)
/

CREATE OR REPLACE PUBLIC SYNONYM TEMP_REPORTES_THONA FOR SICAS_OC.TEMP_REPORTES_THONA;
/

GRANT DELETE, UPDATE, SELECT, INSERT ON SICAS_OC.TEMP_REPORTES_THONA TO PUBLIC;
/