
  CREATE TABLE "SICAS_OC"."TEMP_SESAS_COMPVIGRP2" 
   (	"SECUENCIA" NUMBER, 
	"POLIZA" VARCHAR2(30), 
	"CERTI" VARCHAR2(23), 
	"MONEDA" VARCHAR2(1), 
	"INI_VIG" VARCHAR2(8), 
	"FIN_VIG" VARCHAR2(8), 
	"FECHA_ALTA" VARCHAR2(8), 
	"FECHA_BAJA" VARCHAR2(8), 
	"FECHA_NAC" VARCHAR2(8), 
	"SEXO" VARCHAR2(1), 
	"FORMA_VTA" VARCHAR2(6), 
	"ANIOPOLIZA" NUMBER, 
	"TIPODIVIDENDO" VARCHAR2(1), 
	"MONTODIVIDENDO" NUMBER, 
	"POLCONCENTRADA" NUMBER, 
	"CODPAIS" VARCHAR2(3), 
	"CODESTADO" VARCHAR2(3), 
	"IDPOLIZA" NUMBER(14,0), 
	"STSPOLIZA" VARCHAR2(3), 
	"FECINIVIG" DATE NOT NULL ENABLE, 
	"FECFINVIGPOL" DATE NOT NULL ENABLE, 
	"IDTIPOSEG" VARCHAR2(6), 
	"IDETPOL" NUMBER(14,0) NOT NULL ENABLE, 
	"STSDETALLE" VARCHAR2(6), 
	"FECFINVIG" DATE, 
	"INDASEGMODELO" VARCHAR2(1), 
	"CANTASEGMODELO" NUMBER, 
	"COD_ASEGURADO" NUMBER(14,0) NOT NULL ENABLE, 
	"TIPODETALLE" CHAR(3), 
	"EMISION" NUMBER, 
	"PLAZOPAGOPRIMAS" NUMBER, 
	"PLANPOLIZA" VARCHAR2(6), 
	"PLANCOB" VARCHAR2(15), 
	"IDENDOSO" NUMBER(14,0), 
	 PRIMARY KEY ("SECUENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
