
  CREATE TABLE "SICAS_OC"."TEMP_ARCHIVOS_THONA" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODREPORTE" VARCHAR2(30) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"ARCHIVO" BLOB DEFAULT EMPTY_BLOB(), 
	"FECHA" DATE DEFAULT SYSDATE, 
	"ID_ENVIO" NUMBER DEFAULT 0, 
	 CONSTRAINT "TEMP_ARCHIVOS_THONA_PK" PRIMARY KEY ("CODCIA", "CODEMPRESA", "CODREPORTE", "CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("ARCHIVO") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
