
  CREATE TABLE "SICAS_OC"."TEMP_MIZAR_SICAS" 
   (	"FOLIO" VARCHAR2(30), 
	"SERIESAT" VARCHAR2(10), 
	"STATUSSAT" VARCHAR2(10), 
	"UUID" VARCHAR2(50), 
	"RFCASOCIADO" VARCHAR2(20), 
	"ASOCIADO" VARCHAR2(300), 
	"CONCEPTOSIMPORTE" VARCHAR2(30), 
	"PRIMANETA" NUMBER(28,2), 
	"IVA" NUMBER(28,2), 
	"TOTAL" NUMBER(28,2), 
	"VERSIONFACT" VARCHAR2(10), 
	"MOTIVOCANCELACION" VARCHAR2(10), 
	"CADENACONCEPTOS" VARCHAR2(1000), 
	"TIPO" VARCHAR2(10), 
	"FECHAEMISION" DATE, 
	"FECHACANCELACION" DATE, 
	"IDRECIBONCR" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"RFCCONTRATANTE" VARCHAR2(20), 
	"TIPOSICAS" VARCHAR2(10), 
	"FECHAEMIFACTNCR" DATE, 
	"STATUS" VARCHAR2(10), 
	"FOLIOFACTELECT" VARCHAR2(30), 
	"PRIMANETASICAS" NUMBER(28,2), 
	"IVASICAS" NUMBER(28,2), 
	"TOTALSICAS" NUMBER(28,2), 
	"FECHACANCELSICAS" DATE, 
	"MOTIVOCANCELSICAS" VARCHAR2(10), 
	"FECHAPAGOSICAS" DATE, 
	"TIMBREENFACTELECT" NUMBER(14,0), 
	"UUIDENFACTELECT" VARCHAR2(2), 
	"SERIEFOLIOENFACTELECT" VARCHAR2(2), 
	"RECIBONCRENFACTELECT" VARCHAR2(2), 
	"UUIDCANCELADOENFACTELECT" VARCHAR2(2), 
	"RECIBONCRANULENFACTELECT" VARCHAR2(2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
