
  CREATE TABLE "SICAS_OC"."TEMP_HISTORICO_MARGE_AGRUP" 
   (	"CONSECUTIVO" NUMBER(38,0), 
	"SUFIJO" VARCHAR2(26), 
	"AÑO_DE_EMISIÓN" VARCHAR2(26), 
	"AÑO_VENCIMIENTO" VARCHAR2(26), 
	"MES_DE_VENCIMIENTO" VARCHAR2(26), 
	"LLAVE" VARCHAR2(26), 
	"AGENTE_ETIQUETA" NUMBER(38,0), 
	"NOMBRE_DEL_AGENTE_ETIQUETA" VARCHAR2(250), 
	"AGENTE" NUMBER(38,0), 
	"NOMBRE_DEL_AGENTE" VARCHAR2(250), 
	"NOMBRE_AGENTE_1_LICITACIONES" VARCHAR2(250), 
	"PROMOTOR" VARCHAR2(30), 
	"NOMBRE_PROMOTOR" VARCHAR2(250), 
	"NO_DR" VARCHAR2(30), 
	"IDENTIFICACIÓN_SUSCRIPCIÓN" VARCHAR2(26), 
	"LINEA_COMERCIAL" VARCHAR2(250), 
	"LINEA_COMERCIAL_1" VARCHAR2(26), 
	"LINEA_DE_NEGOCIO1" VARCHAR2(26), 
	"UNIDAD_DE_NEGOCIO" VARCHAR2(26), 
	"GERENTE_COMERCIAL" VARCHAR2(250), 
	"NO" VARCHAR2(50), 
	"NO_DE_PÓLIZA" VARCHAR2(30), 
	"TIPO_DE_VIGENCIA" VARCHAR2(26), 
	"NO_REFERENCIA" VARCHAR2(30), 
	"CONTRATANTE" VARCHAR2(250), 
	"TIPO_DE_NEGOCIO" VARCHAR2(26), 
	"AGENTE2" NUMBER(38,0), 
	"MONEDA" VARCHAR2(26), 
	"TIPO_SEGURO" VARCHAR2(26), 
	"PLAN_COBERTURAS" VARCHAR2(26), 
	"CÓDIGO_SUBRAMO" NUMBER(38,0), 
	"DESCRIPCIÓN_SUBRAMO" VARCHAR2(128), 
	"RAMO" VARCHAR2(26), 
	"INICIO_VIG_PÓLIZA" DATE, 
	"FIN_VIG_PÓLIZA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
