--
-- TEMP_SESAS_COMPVIGRP1  (Table) 
--
CREATE TABLE SICAS_OC.TEMP_SESAS_COMPVIGRP1
(
  SECUENCIA        NUMBER,
  POLIZA           VARCHAR2(30 BYTE),
  CERTI            VARCHAR2(23 BYTE),
  MONEDA           VARCHAR2(1 BYTE),
  INI_VIG          VARCHAR2(8 BYTE),
  FIN_VIG          VARCHAR2(8 BYTE),
  FECHA_ALTA       VARCHAR2(8 BYTE),
  FECHA_BAJA       VARCHAR2(8 BYTE),
  FECHA_NAC        VARCHAR2(8 BYTE),
  SEXO             VARCHAR2(1 BYTE),
  FORMA_VTA        VARCHAR2(6 BYTE),
  ANIOPOLIZA       NUMBER,
  TIPODIVIDENDO    VARCHAR2(1 BYTE),
  MONTODIVIDENDO   NUMBER,
  POLCONCENTRADA   NUMBER,
  CODPAIS          VARCHAR2(3 BYTE),
  CODESTADO        VARCHAR2(3 BYTE),
  IDPOLIZA         NUMBER(14),
  STSPOLIZA        VARCHAR2(3 BYTE),
  FECINIVIG        DATE                         NOT NULL,
  FECFINVIGPOL     DATE                         NOT NULL,
  IDTIPOSEG        VARCHAR2(6 BYTE),
  IDETPOL          NUMBER(14)                   NOT NULL,
  STSDETALLE       VARCHAR2(6 BYTE),
  FECFINVIG        DATE,
  INDASEGMODELO    VARCHAR2(1 BYTE),
  CANTASEGMODELO   NUMBER,
  COD_ASEGURADO    NUMBER(14)                   NOT NULL,
  TIPODETALLE      CHAR(3 BYTE),
  EMISION          NUMBER,
  PLAZOPAGOPRIMAS  NUMBER,
  PLANPOLIZA       VARCHAR2(6 BYTE),
  PLANCOB          VARCHAR2(15 BYTE)
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

CREATE OR REPLACE PUBLIC SYNONYM TEMP_SESAS_COMPVIGRP1 FOR SICAS_OC.TEMP_SESAS_COMPVIGRP1
/

-- 
-- Non Foreign Key Constraints for Table TEMP_SESAS_COMPVIGRP1 
-- 
ALTER TABLE SICAS_OC.TEMP_SESAS_COMPVIGRP1 ADD (
  PRIMARY KEY
  (SECUENCIA)
  USING INDEX
    TABLESPACE TS_SICASOC
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.TEMP_SESAS_COMPVIGRP1 TO PUBLIC
/
