
  CREATE TABLE "SICAS_OC"."TEMP_CASTIGA_COMISIONES" 
   (	"TIPO_DOCUMENTO" VARCHAR2(6), 
	"NUM_DOCUMENTO" NUMBER(18,0), 
	"ESTATUS_DOCUMENTO" VARCHAR2(5), 
	"IDPOLIZA" NUMBER(14,0), 
	"COD_AGENTE" NUMBER(18,0), 
	"IDCOMISION" NUMBER(14,0), 
	"ESTATUS_COMISION" VARCHAR2(5), 
	"FEC_GENERACION" DATE, 
	"FEC_ESTADO" DATE, 
	"FEC_PROCESO" DATE, 
	"APLICADO" VARCHAR2(1), 
	"CAMPO_GENERAL" VARCHAR2(20), 
	 CONSTRAINT "CASTIGA_COMIS_PK" PRIMARY KEY ("TIPO_DOCUMENTO", "NUM_DOCUMENTO", "IDPOLIZA", "COD_AGENTE", "IDCOMISION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
