
  CREATE TABLE "SICAS_OC"."TEXTO_COBERTURA" 
   (	"CODCIA" NUMBER(14,0), 
	"CODEMPRESA" NUMBER(14,0), 
	"IDTIPOSEG" VARCHAR2(6), 
	"PLANCOB" VARCHAR2(15), 
	"CODCOBERT" VARCHAR2(6), 
	"CORRTEXTO" NUMBER(14,0), 
	"TEXTO" VARCHAR2(4000), 
	"ESTADO" VARCHAR2(6), 
	"FECHAVIGENTEDESDE" DATE, 
	 CONSTRAINT "PK_TEXTOCOB" PRIMARY KEY ("CODCIA", "CODEMPRESA", "IDTIPOSEG", "PLANCOB", "CODCOBERT", "CORRTEXTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "RF_TEXTCOB_DETPOL" FOREIGN KEY ("IDTIPOSEG", "PLANCOB", "CODCOBERT", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."COBERTURAS_DE_SEGUROS" ("IDTIPOSEG", "PLANCOB", "CODCOBERT", "CODEMPRESA", "CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
