
  CREATE TABLE "SICAS_OC"."TIPOS_ESTANDARES_SERVICIO" 
   (	"CODCIA" NUMBER, 
	"CODEMPRESA" NUMBER, 
	"CODFLUJO" VARCHAR2(5), 
	"IDTIPOSEG" VARCHAR2(6), 
	"PLANCOB" VARCHAR2(15), 
	"CODTRAMITE" VARCHAR2(5), 
	"CODSOLICITUD" VARCHAR2(100), 
	"NUMDIASATN" NUMBER DEFAULT 0, 
	"INDDIAS" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
