
  CREATE TABLE "SICAS_OC"."TIPO_DE_DOCUMENTO" 
   (	"IDEOPECONTABLE" NUMBER(14,0) NOT NULL ENABLE, 
	"CODTIPODOC" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCTIPODOC" VARCHAR2(100) NOT NULL ENABLE, 
	"CODCLASE" VARCHAR2(3) NOT NULL ENABLE, 
	"SUGERIDO" VARCHAR2(1), 
	 CONSTRAINT "PK_TIPO_DE_DOCUMENTO" PRIMARY KEY ("CODTIPODOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
