
  CREATE TABLE "SICAS_OC"."TIPO_AGENTE" 
   (	"CODTIPO" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(50), 
	"FECHAESTADO" DATE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(6), 
	 CONSTRAINT "PK_TIPOS_AGENTES" PRIMARY KEY ("CODCIA", "CODTIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
