
  CREATE TABLE "SICAS_OC"."TMP_COMISIONES_TOTALES_CTRL" 
   (	"IDLOTE" NUMBER NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"FECHA_DESDE" DATE, 
	"FECHA_HASTA" DATE, 
	"MONEDA" VARCHAR2(5), 
	"USUARIO" VARCHAR2(30) DEFAULT USER, 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "TMP_COMISIONES_TOTALES_CTRL_PK" PRIMARY KEY ("IDLOTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
