
  CREATE TABLE "SICAS_OC"."TMP_COMISIONES_TOTALES" 
   (	"IDLOTE" NUMBER NOT NULL ENABLE, 
	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"COD_AGENTE" NUMBER(18,0) NOT NULL ENABLE, 
	"IDCOMISION" NUMBER(14,0) NOT NULL ENABLE, 
	"CODMONEDA" VARCHAR2(10), 
	"MTOCOMISI" NUMBER, 
	"MTOIVA" NUMBER, 
	"MTOIVARET" NUMBER, 
	"MTOISR" NUMBER, 
	"MTOISRRET" NUMBER, 
	"SUBTOTAL" NUMBER, 
	 CONSTRAINT "TMP_COMISIONES_TOTALES_PK" PRIMARY KEY ("IDLOTE", "CODCIA", "COD_AGENTE", "IDCOMISION", "CODMONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC"  ENABLE, 
	 CONSTRAINT "TMP_COMISIONES_TOTALES_R01" FOREIGN KEY ("IDLOTE")
	  REFERENCES "SICAS_OC"."TMP_COMISIONES_TOTALES_CTRL" ("IDLOTE") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
