
  CREATE TABLE "SICAS_OC"."TRANSACAPROB" 
   (	"TRANIDTRANSACCION" NUMBER(18,0), 
	"FECHATRANSACCION" DATE, 
	"APROBDTRANSACCION" NUMBER(18,0), 
	"IDSINIESTRO" NUMBER(14,0), 
	"IDPOLIZA" NUMBER(14,0), 
	"NUM_APROBACION" NUMBER(14,0), 
	"STSAPROBACION" VARCHAR2(3), 
	"IDTRANSACCIONANUL" VARCHAR2(18), 
	"INDV_COLECT" VARCHAR2(12), 
	 CONSTRAINT "TRANSACAPROB_PK" PRIMARY KEY ("TRANIDTRANSACCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
