
  CREATE TABLE "SICAS_OC"."TRIANGULOS_SINIESTROS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDTRIANGULO" NUMBER(14,0) NOT NULL ENABLE, 
	"IDSINIESTRO" NUMBER(14,0) NOT NULL ENABLE, 
	"FECOCURR" DATE, 
	"FECNOTIF" DATE, 
	"MTOSINIESTRO" NUMBER(28,2), 
	 CONSTRAINT "PK_TRIANGULOS_SINIESTROS" PRIMARY KEY ("CODCIA", "IDTRIANGULO", "IDSINIESTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_TRIANGULOS_SINIESTROS" FOREIGN KEY ("CODCIA", "IDTRIANGULO")
	  REFERENCES "SICAS_OC"."TRIANGULOS" ("CODCIA", "IDTRIANGULO") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
