
  CREATE TABLE "SICAS_OC"."USUARIOS" 
   (	"CODCIA" NUMBER(14,0) CONSTRAINT "SYS_C0033732" NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) CONSTRAINT "SYS_C0033729" NOT NULL ENABLE, 
	"NOMUSUARIO" VARCHAR2(50) CONSTRAINT "SYS_C0033730" NOT NULL ENABLE, 
	"SUPERVISOR" VARCHAR2(1), 
	"CODGRUPO" VARCHAR2(8) CONSTRAINT "SYS_C0033731" NOT NULL ENABLE, 
	"COD_AGENTE" VARCHAR2(10), 
	"SOLO_LECTURA" VARCHAR2(1), 
	"EMAIL" VARCHAR2(80), 
	"INDREVISAPRECIOS" VARCHAR2(1), 
	 PRIMARY KEY ("CODCIA", "CODGRUPO", "CODUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "SYS_C0033734" CHECK (Supervisor IN ('S','N')   ) ENABLE, 
	 FOREIGN KEY ("CODGRUPO", "CODCIA")
	  REFERENCES "SICAS_OC"."GRUPOS_DE_USUARIOS" ("CODGRUPO", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
