
  CREATE TABLE "SICAS_OC"."USUARIO_HORARIO" 
   (	"IDCODIGO" NUMBER(14,0) NOT NULL ENABLE, 
	"DIA" VARCHAR2(10) NOT NULL ENABLE, 
	"HORA_INGRESO" DATE NOT NULL ENABLE, 
	"HORA_EGRESO" DATE NOT NULL ENABLE, 
	"IDUSUARIOHORARIO" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USUARIOHORARIO" PRIMARY KEY ("IDUSUARIOHORARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_USUARIOHORARIO_USUA" FOREIGN KEY ("IDCODIGO")
	  REFERENCES "SICAS_OC"."USUARIO_CONFG" ("IDCODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
