
  CREATE TABLE "SICAS_OC"."USUARIO_CONVERSA" 
   (	"IDCODIGO" NUMBER(14,0), 
	"IDCODIGODESTINO" NUMBER(14,0), 
	"IDSESSION" NUMBER(22,0), 
	"IDSESSIONDESTINO" NUMBER(22,0), 
	"LINEA" NUMBER(22,0), 
	"HORA" DATE, 
	"IDUSUARIOCONVERSA" VARCHAR2(30), 
	 CONSTRAINT "PK_USUARIOCONVERSA" PRIMARY KEY ("IDUSUARIOCONVERSA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "FK_USUARIOCONVERSA_USUARIO" FOREIGN KEY ("IDCODIGO")
	  REFERENCES "SICAS_OC"."USUARIO_CONFG" ("IDCODIGO") ENABLE, 
	 CONSTRAINT "FK_USUARIOCONVERSA_USUA" FOREIGN KEY ("IDCODIGODESTINO")
	  REFERENCES "SICAS_OC"."USUARIO_CONFG" ("IDCODIGO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
