
  CREATE TABLE "SICAS_OC"."VALORES_DE_LISTAS" 
   (	"CODLISTA" VARCHAR2(10) CONSTRAINT "SYS_C007232" NOT NULL ENABLE, 
	"CODVALOR" VARCHAR2(6) CONSTRAINT "SYS_C007233" NOT NULL ENABLE, 
	"DESCVALLST" VARCHAR2(200) CONSTRAINT "SYS_C007234" NOT NULL ENABLE, 
	"CVE_CNSF" VARCHAR2(15), 
	"DESC_CNSF" VARCHAR2(300), 
	 PRIMARY KEY ("CODLISTA", "CODVALOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("CODLISTA")
	  REFERENCES "SICAS_OC"."TIPO_DE_LISTA" ("CODLISTA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
