
  CREATE TABLE "SICAS_OC"."VERSION" 
   (	"COD_MARCA" VARCHAR2(10) CONSTRAINT "SYS_C007236" NOT NULL ENABLE, 
	"COD_VERSION" VARCHAR2(10) CONSTRAINT "SYS_C007237" NOT NULL ENABLE, 
	"COD_MODELO" VARCHAR2(10) CONSTRAINT "SYS_C007238" NOT NULL ENABLE, 
	"DESC_VERSION" VARCHAR2(100), 
	"DESC_MOTOR" VARCHAR2(17), 
	"DESC_TRANSMISION" VARCHAR2(6), 
	"COD_DESTINADO" VARCHAR2(6), 
	"NUM_PUESTO" VARCHAR2(6), 
	"TIPO_VEH" VARCHAR2(6), 
	"CLASE_VEH" VARCHAR2(6), 
	"CAP_TONELAJE" VARCHAR2(6) CONSTRAINT "SYS_C007239" NOT NULL ENABLE, 
	"NUM_CILINDROS" VARCHAR2(6) CONSTRAINT "SYS_C007240" NOT NULL ENABLE, 
	"NUM_PUERTAS" VARCHAR2(6) CONSTRAINT "SYS_C007241" NOT NULL ENABLE, 
	"TIPO_INYECCION" VARCHAR2(6) CONSTRAINT "SYS_C007242" NOT NULL ENABLE, 
	"TIPO_FRENOS" VARCHAR2(6) CONSTRAINT "SYS_C007243" NOT NULL ENABLE, 
	"TIPO_AIREACO" VARCHAR2(6) CONSTRAINT "SYS_C007244" NOT NULL ENABLE, 
	"TIPO_VIDRIO" VARCHAR2(6) CONSTRAINT "SYS_C007245" NOT NULL ENABLE, 
	"TIPO_TAPICERIA" VARCHAR2(6) CONSTRAINT "SYS_C007246" NOT NULL ENABLE, 
	"TIPO_SONIDO" VARCHAR2(6) CONSTRAINT "SYS_C007247" NOT NULL ENABLE, 
	"TIPO_TECHO" VARCHAR2(6) CONSTRAINT "SYS_C007248" NOT NULL ENABLE, 
	"TIPO_AIR_BAGS" VARCHAR2(6) CONSTRAINT "SYS_C007249" NOT NULL ENABLE, 
	"COD_CLASIF" VARCHAR2(6) CONSTRAINT "SYS_C007250" NOT NULL ENABLE, 
	"OCUP_VEH" VARCHAR2(6) CONSTRAINT "SYS_C007251" NOT NULL ENABLE, 
	"CAPACIDAD_CARGA" NUMBER(6,2) CONSTRAINT "SYS_C007252" NOT NULL ENABLE, 
	"CAP_CARGA" VARCHAR2(6), 
	 PRIMARY KEY ("COD_MARCA", "COD_VERSION", "COD_MODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 FOREIGN KEY ("COD_MARCA", "COD_MODELO")
	  REFERENCES "SICAS_OC"."MODELO" ("COD_MARCA", "COD_MODELO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
