
  CREATE TABLE "SICAS_OC"."WEB_SERVICES" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDWEB" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(2000 CHAR), 
	"USUARIO" VARCHAR2(30 CHAR), 
	"PASSWORD" VARCHAR2(50 CHAR), 
	"URL" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"METODO" VARCHAR2(200 CHAR), 
	"ESPACIONOMBRE" VARCHAR2(200 CHAR), 
	"IDEWEBXMLENVIO" NUMBER(10,0), 
	"IDEWEBXMLRESP" NUMBER(10,0), 
	"STSWEB" VARCHAR2(6) DEFAULT 'CONFIG' NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) DEFAULT user NOT NULL ENABLE, 
	"FECULTMODIF" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "WEB_SERVICES_PK" PRIMARY KEY ("IDWEB", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "WEB_SERVICES_R01" FOREIGN KEY ("IDEWEBXMLENVIO", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."WEB_SERVICES_XML" ("IDWEBXML", "CODEMPRESA", "CODCIA") ENABLE, 
	 CONSTRAINT "WEB_SERVICES_R02" FOREIGN KEY ("IDEWEBXMLRESP", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."WEB_SERVICES_XML" ("IDWEBXML", "CODEMPRESA", "CODCIA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
