
  CREATE TABLE "SICAS_OC"."WEB_SERVICES_XML_NODOS" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDWEBXML" NUMBER(10,0) NOT NULL ENABLE, 
	"IDWEBXMLNODO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"TIPODATO" VARCHAR2(100 CHAR), 
	"LONGITUD" NUMBER(10,0), 
	"VALORDEFAULT" VARCHAR2(4000 CHAR), 
	"ORDEN" NUMBER(5,0), 
	"CODUSUARIO" VARCHAR2(30) DEFAULT user NOT NULL ENABLE, 
	"FECULTMODIF" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"NIVEL" NUMBER(5,0) DEFAULT 1, 
	 CONSTRAINT "WEB_SERVICES_XML_NODOS_PK" PRIMARY KEY ("IDWEBXMLNODO", "IDWEBXML", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE, 
	 CONSTRAINT "WEB_SERVICES_XML_NODOS_R01" FOREIGN KEY ("IDWEBXML", "CODEMPRESA", "CODCIA")
	  REFERENCES "SICAS_OC"."WEB_SERVICES_XML" ("IDWEBXML", "CODEMPRESA", "CODCIA") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
