
  CREATE TABLE "SICAS_OC"."WEB_SERVICES_XML" 
   (	"CODCIA" NUMBER(14,0) NOT NULL ENABLE, 
	"CODEMPRESA" NUMBER(14,0) NOT NULL ENABLE, 
	"IDWEBXML" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(2000 CHAR), 
	"ESPACIONOMBRE" VARCHAR2(400 CHAR), 
	"ESENVIO" CHAR(1 CHAR), 
	"STSWSX" VARCHAR2(6) DEFAULT 'CONFIG' NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(30) DEFAULT user NOT NULL ENABLE, 
	"FECULTMODIF" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"SQLQUERY" CLOB, 
	"DATOSXML" CHAR(1 CHAR) DEFAULT 'S', 
	 CONSTRAINT "WEB_SERVICES_XML_PK" PRIMARY KEY ("IDWEBXML", "CODEMPRESA", "CODCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
 LOB ("SQLQUERY") STORE AS BASICFILE (
  TABLESPACE "TS_SICASOC" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
