--
-- GT_BONOS_AGENTES_POLIZAS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   BONOS_AGENTES_POLIZAS (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.GT_BONOS_AGENTES_POLIZAS AS

PROCEDURE COPIAR (nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER, nIdBonoVentasDest NUMBER);

FUNCTION EXISTEN_REGISTROS(nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER) RETURN VARCHAR2; 

PROCEDURE ELIMINAR(nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER);

END GT_BONOS_AGENTES_POLIZAS;
/

--
-- GT_BONOS_AGENTES_POLIZAS  (Package Body) 
--
--  Dependencies: 
--   GT_BONOS_AGENTES_POLIZAS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.GT_BONOS_AGENTES_POLIZAS AS

PROCEDURE COPIAR (nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER, nIdBonoVentasDest NUMBER) IS
CURSOR AGT_Q IS
   SELECT IdPoliza
     FROM BONOS_AGENTES_POLIZAS
    WHERE CodCia       = nCodCia
      AND CodEmpresa   = nCodEmpresa
      AND IdBonoVentas = nIdBonoVentas;
BEGIN
   FOR W IN AGT_Q LOOP
      INSERT INTO BONOS_AGENTES_POLIZAS
            (CodCia, CodEmpresa, IdBonoVentas, IdPoliza)
      VALUES(nCodCia, nCodEmpresa, nIdBonoVentasDest, W.IdPoliza);
   END LOOP;
END COPIAR;

FUNCTION EXISTEN_REGISTROS(nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER) RETURN VARCHAR2 IS
cExiste     VARCHAR2(1);
BEGIN
   BEGIN
      SELECT 'S'
        INTO cExiste
        FROM BONOS_AGENTES_POLIZAS
       WHERE CodCia       = nCodCia
         AND CodEmpresa   = nCodEmpresa
         AND IdBonoVentas = nIdBonoVentas;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cExiste := 'N';
      WHEN TOO_MANY_ROWS THEN
         cExiste := 'S';
   END;
   RETURN(cExiste);
END EXISTEN_REGISTROS;

PROCEDURE ELIMINAR(nCodCia NUMBER, nCodEmpresa NUMBER, nIdBonoVentas NUMBER) IS
BEGIN
   DELETE BONOS_AGENTES_POLIZAS
    WHERE CodCia       = nCodCia
      AND CodEmpresa   = nCodEmpresa
      AND IdBonoVentas = nIdBonoVentas;
END ELIMINAR;

END GT_BONOS_AGENTES_POLIZAS;
/

--
-- GT_BONOS_AGENTES_POLIZAS  (Synonym) 
--
--  Dependencies: 
--   GT_BONOS_AGENTES_POLIZAS (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM GT_BONOS_AGENTES_POLIZAS FOR SICAS_OC.GT_BONOS_AGENTES_POLIZAS
/


GRANT EXECUTE, DEBUG ON SICAS_OC.GT_BONOS_AGENTES_POLIZAS TO PUBLIC
/
