--
-- GT_CATEGORIAS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   CATEGORIAS (Table)
--   CATEGORIAS (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.GT_CATEGORIAS IS

  PROCEDURE INSERTAR
    (
     in_CODCIA         IN CATEGORIAS.CODCIA%TYPE
    ,in_CODEMPRESA     IN CATEGORIAS.CODEMPRESA%TYPE
    ,in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE
    ,in_CODCATEGO      IN CATEGORIAS.CODCATEGO%TYPE
    ,in_DESCCATEGO     IN CATEGORIAS.DESCCATEGO%TYPE
    );

  PROCEDURE ACTUALIZAR
    (
     in_CODCIA         IN CATEGORIAS.CODCIA%TYPE
    ,in_CODEMPRESA     IN CATEGORIAS.CODEMPRESA%TYPE
    ,in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE
    ,in_CODCATEGO      IN CATEGORIAS.CODCATEGO%TYPE
    ,in_DESCCATEGO     IN CATEGORIAS.DESCCATEGO%TYPE
    );
    
   FUNCTION CONSULTA_DESCRIP(in_CODCIA IN CATEGORIAS.CODCIA%TYPE,in_CODEMPRESA IN CATEGORIAS.CODEMPRESA%TYPE,in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE,in_CODCATEGO IN CATEGORIAS.CODCATEGO%TYPE ) RETURN VARCHAR2;

END GT_CATEGORIAS;
/

--
-- GT_CATEGORIAS  (Package Body) 
--
--  Dependencies: 
--   GT_CATEGORIAS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.GT_CATEGORIAS IS

    PROCEDURE INSERTAR
    (
         in_CODCIA         IN CATEGORIAS.CODCIA%TYPE
        ,in_CODEMPRESA     IN CATEGORIAS.CODEMPRESA%TYPE
        ,in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE
        ,in_CODCATEGO      IN CATEGORIAS.CODCATEGO%TYPE
        ,in_DESCCATEGO     IN CATEGORIAS.DESCCATEGO%TYPE
    ) IS
    BEGIN
        INSERT INTO CATEGORIAS
          (
           CODCIA
          ,CODEMPRESA
          ,CODTIPONEGOCIO
          ,CODCATEGO
          ,DESCCATEGO
          )
        VALUES
          (
           in_CODCIA
          ,in_CODEMPRESA
          ,in_CODTIPONEGOCIO
          ,in_CODCATEGO
          ,in_DESCCATEGO
          );
    END INSERTAR;

    PROCEDURE ACTUALIZAR
    (
         in_CODCIA         IN CATEGORIAS.CODCIA%TYPE
        ,in_CODEMPRESA     IN CATEGORIAS.CODEMPRESA%TYPE
        ,in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE
        ,in_CODCATEGO      IN CATEGORIAS.CODCATEGO%TYPE
        ,in_DESCCATEGO     IN CATEGORIAS.DESCCATEGO%TYPE
        ) IS
    BEGIN
        UPDATE CATEGORIAS
        SET 
            DESCCATEGO       = in_DESCCATEGO
           ,CODUSUARIO       = USER
           ,FECHAMODIF       = SYSDATE
        WHERE
            CODCIA           = in_CODCIA
        AND CODEMPRESA       = in_CODEMPRESA
        AND CODTIPONEGOCIO   = in_CODTIPONEGOCIO
        AND CODCATEGO        = in_CODCATEGO;
    END ACTUALIZAR;
    --
    FUNCTION CONSULTA_DESCRIP(in_CODCIA IN CATEGORIAS.CODCIA%TYPE,
                              in_CODEMPRESA IN CATEGORIAS.CODEMPRESA%TYPE,
                              in_CODTIPONEGOCIO IN CATEGORIAS.CODTIPONEGOCIO%TYPE,
                              in_CODCATEGO IN CATEGORIAS.CODCATEGO%TYPE ) RETURN VARCHAR2 IS
        DESCCATEGO VARCHAR2(200);
    BEGIN
        SELECT C.DESCCATEGO
          INTO DESCCATEGO 
          FROM CATEGORIAS C
         WHERE C.CODCIA         =   in_CODCIA
           AND C.CODEMPRESA     =   in_CODEMPRESA
           AND C.CODTIPONEGOCIO =   in_CODTIPONEGOCIO
           AND C.CODCATEGO      =   in_CODCATEGO;            
        RETURN DESCCATEGO;    
    EXCEPTION WHEN OTHERS THEN           
        RETURN 'SIN DEFINICIÓN';
    END CONSULTA_DESCRIP;
    --
END GT_CATEGORIAS;
/

--
-- GT_CATEGORIAS  (Synonym) 
--
--  Dependencies: 
--   GT_CATEGORIAS (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM GT_CATEGORIAS FOR SICAS_OC.GT_CATEGORIAS
/


GRANT EXECUTE ON SICAS_OC.GT_CATEGORIAS TO PUBLIC
/
