CREATE OR REPLACE PACKAGE          GT_DETALLE_TABLERO_COMPROB IS

  PROCEDURE INSERTAR
    (
     in_CODCIA      IN DETALLE_TABLERO_COMPROB.CODCIA%TYPE
    ,in_IDPROC      IN DETALLE_TABLERO_COMPROB.IDPROC%TYPE
    ,in_IDPROCDET   IN DETALLE_TABLERO_COMPROB.IDPROCDET%TYPE
    ,in_NUMCOMPROB  IN DETALLE_TABLERO_COMPROB.NUMCOMPROB%TYPE
    ,in_CUENTA  IN DETALLE_TABLERO_COMPROB.CUENTA%TYPE
    ,in_NIVAUX      IN DETALLE_TABLERO_COMPROB.NIVAUX%TYPE
    );

END GT_DETALLE_TABLERO_COMPROB;
/

CREATE OR REPLACE PACKAGE BODY          GT_DETALLE_TABLERO_COMPROB IS

  PROCEDURE INSERTAR
    (
     in_CODCIA      IN DETALLE_TABLERO_COMPROB.CODCIA%TYPE
    ,in_IDPROC      IN DETALLE_TABLERO_COMPROB.IDPROC%TYPE
    ,in_IDPROCDET   IN DETALLE_TABLERO_COMPROB.IDPROCDET%TYPE
    ,in_NUMCOMPROB  IN DETALLE_TABLERO_COMPROB.NUMCOMPROB%TYPE
    ,in_CUENTA      IN DETALLE_TABLERO_COMPROB.CUENTA%TYPE
    ,in_NIVAUX      IN DETALLE_TABLERO_COMPROB.NIVAUX%TYPE
    ) IS
    nSwLocalizado  NUMBER := 0;
  BEGIN
    
    INSERT INTO DETALLE_TABLERO_COMPROB
      (
       CODCIA
      ,IDPROC
      ,IDPROCDET
      ,NUMCOMPROB
      ,CUENTA
      ,NIVAUX
      ,CODUSUARIO
      ,FECULTMODIF
      )
    VALUES
      (
       in_CODCIA
      ,in_IDPROC
      ,in_IDPROCDET
      ,in_NUMCOMPROB
      ,in_CUENTA
      ,in_NIVAUX
      ,user
      ,sysdate
      );
  END insertar;

END GT_DETALLE_TABLERO_COMPROB;
