CREATE OR REPLACE PACKAGE          GT_OFICINAS IS

    PROCEDURE INSERTAR (pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE,pDESCOFICINA   IN OFICINAS.DESCOFICINA%TYPE,pDIRECCION     IN OFICINAS.DIRECCION%TYPE,pTELEFONO      IN OFICINAS.TELEFONO%TYPE);

    PROCEDURE ACTUALIZAR (pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE,pDESCOFICINA   IN OFICINAS.DESCOFICINA%TYPE,pDIRECCION     IN OFICINAS.DIRECCION%TYPE,pTELEFONO      IN OFICINAS.TELEFONO%TYPE,pSTSOFICINA    IN OFICINAS.STSOFICINA%TYPE);

    PROCEDURE SUSPENDER    (     pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE    );
    --
    FUNCTION CONSULTA (pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE, pOPCION VARCHAR2 := 'DESCRIPCION') RETURN VARCHAR2;
    --
    PROCEDURE REG_CONSULTA( RECORDSET OUT SYS_REFCURSOR);
     
END GT_OFICINAS;
/

CREATE OR REPLACE PACKAGE BODY          GT_OFICINAS IS

    PROCEDURE INSERTAR
    (
     pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE
    ,pDESCOFICINA   IN OFICINAS.DESCOFICINA%TYPE
    ,pDIRECCION     IN OFICINAS.DIRECCION%TYPE
    ,pTELEFONO      IN OFICINAS.TELEFONO%TYPE
    ) IS
    BEGIN
    INSERT INTO OFICINAS
      (
       CODOFICINA
      ,DESCOFICINA
      ,DIRECCION
      ,TELEFONO
      )
    VALUES
      (
       pCODOFICINA
      ,pDESCOFICINA
      ,pDIRECCION
      ,pTELEFONO
      );
    END INSERTAR;

    PROCEDURE ACTUALIZAR
    (
     pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE
    ,pDESCOFICINA   IN OFICINAS.DESCOFICINA%TYPE
    ,pDIRECCION     IN OFICINAS.DIRECCION%TYPE
    ,pTELEFONO      IN OFICINAS.TELEFONO%TYPE
    ,pSTSOFICINA    IN OFICINAS.STSOFICINA%TYPE
    ) IS
    BEGIN
    UPDATE OFICINAS
    SET 
        DESCOFICINA   = pDESCOFICINA
       ,DIRECCION     = pDIRECCION
       ,TELEFONO      = pTELEFONO
       ,STSOFICINA    = pSTSOFICINA
       ,CODUSUARIOMOD = user
       ,FECMODIF      = sysdate
    WHERE
        CODOFICINA    = pCODOFICINA;
    END ACTUALIZAR;

    PROCEDURE SUSPENDER
    (
     pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE
    ) IS
    BEGIN
    UPDATE OFICINAS
    SET 
        STSOFICINA    = 'SUSPENDIDO'
       ,CODUSUARIOMOD = user
       ,FECMODIF      = sysdate
    WHERE
        CODOFICINA    = pCODOFICINA;
    END SUSPENDER;
    --
    FUNCTION CONSULTA ( pCODOFICINA    IN OFICINAS.CODOFICINA%TYPE, pOPCION VARCHAR2 := 'DESCRIPCION') RETURN VARCHAR2 IS    
        CURSOR Q_OFICINA IS
        SELECT 
                CASE WHEN UPPER(pOPCION) = 'DESCRIPCION' THEN O.DESCOFICINA ELSE
                CASE WHEN UPPER(pOPCION) = 'DIRECCION' THEN O.DIRECCION ELSE
                CASE WHEN UPPER(pOPCION) = 'TELEFONO' THEN O.TELEFONO ELSE                 
                CASE WHEN UPPER(pOPCION) = 'ESTATUS' THEN O.STSOFICINA END END END END  OPCION                 
          FROM OFICINAS  O
         WHERE O.CODOFICINA =  pCODOFICINA;
    --         
        R_OFICINA Q_OFICINA%ROWTYPE;
            
    BEGIN
         OPEN Q_OFICINA;
         FETCH Q_OFICINA INTO R_OFICINA;
         CLOSE Q_OFICINA;
         RETURN R_OFICINA.OPCION;
    EXCEPTION WHEN OTHERS THEN
        RETURN 'NO LOCALIZADO';          
    END CONSULTA;
    --
    PROCEDURE REG_CONSULTA( RECORDSET OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN RECORDSET FOR        
          SELECT O.CODOFICINA, 
                 O.DESCOFICINA,
                 O.STSOFICINA
          FROM OFICINAS  O
          WHERE O.STSOFICINA = 'ACTIVO'
          ORDER BY DESCOFICINA;
    END;
    --  
END GT_OFICINAS;
