CREATE OR REPLACE PACKAGE SICAS_OC.GT_PAQUETE_COMERCIAL IS
    --
    PROCEDURE INSERTA
        (
         in_CODCIA      IN PAQUETE_COMERCIAL.CODCIA%TYPE
        ,in_CODEMPRESA  IN PAQUETE_COMERCIAL.CODEMPRESA%TYPE
        ,in_IDTIPOSEG   IN PAQUETE_COMERCIAL.IDTIPOSEG%TYPE
        ,in_PLANCOB     IN PAQUETE_COMERCIAL.PLANCOB%TYPE
        ,in_CODPAQUETE  IN PAQUETE_COMERCIAL.CODPAQUETE%TYPE
        ,in_DESCPAQUETE IN PAQUETE_COMERCIAL.DESCPAQUETE%TYPE
        );
    --  
    FUNCTION COTIZACIONES_NUMREG(SQLTEXT VARCHAR2) RETURN NUMBER; 
    --
    FUNCTION DOCUMENTO(nCodCia NUMBER, nCodEmpresa NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2, nCodPaquete NUMBER) RETURN BLOB;
    --
    FUNCTION DESCRIPCION_PAQUETE(nCodCia NUMBER, nCodEmpresa NUMBER, nCodPaquete NUMBER) RETURN VARCHAR2;
    --
END GT_PAQUETE_COMERCIAL;
/

CREATE OR REPLACE PACKAGE BODY SICAS_OC.GT_PAQUETE_COMERCIAL IS

  PROCEDURE INSERTA
    (
     in_CODCIA      IN PAQUETE_COMERCIAL.CODCIA%TYPE
    ,in_CODEMPRESA  IN PAQUETE_COMERCIAL.CODEMPRESA%TYPE
    ,in_IDTIPOSEG   IN PAQUETE_COMERCIAL.IDTIPOSEG%TYPE
    ,in_PLANCOB     IN PAQUETE_COMERCIAL.PLANCOB%TYPE
    ,in_CODPAQUETE  IN PAQUETE_COMERCIAL.CODPAQUETE%TYPE
    ,in_DESCPAQUETE IN PAQUETE_COMERCIAL.DESCPAQUETE%TYPE
    ) IS
    
    nCODPAQUETE number;
    
  BEGIN
  
    SELECT NVL(max(CODPAQUETE), 0) + NVL(in_CODPAQUETE, 1)
      INTO nCODPAQUETE
      FROM PAQUETE_COMERCIAL P
     WHERE P.CODCIA     = in_CODCIA
       AND P.CODEMPRESA = in_CODEMPRESA
       AND NVL(in_CODPAQUETE,0) = 0;
  
    INSERT INTO PAQUETE_COMERCIAL
      (
       CODCIA
      ,CODEMPRESA
      ,IDTIPOSEG
      ,PLANCOB
      ,CODPAQUETE
      ,DESCPAQUETE
      )
    VALUES
      (
       in_CODCIA
      ,in_CODEMPRESA
      ,in_IDTIPOSEG
      ,in_PLANCOB
      ,nCODPAQUETE
      ,in_DESCPAQUETE
      );
  END INSERTA;

    FUNCTION COTIZACIONES_NUMREG(SQLTEXT VARCHAR2) RETURN NUMBER IS
        NUMROWS number;
    BEGIN
        EXECUTE IMMEDIATE SQLTEXT INTO NUMROWS;
        RETURN NUMROWS;
    END;
    --
   FUNCTION DOCUMENTO(nCodCia NUMBER, nCodEmpresa NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2, nCodPaquete NUMBER) RETURN BLOB AS
     bDocumento PAQUETE_COMERCIAL.Documento%TYPE;
   BEGIN   
      BEGIN
         SELECT Documento --IdTipoSeg,FecRegistro,NumAutorTipSeg,Ds_Arch_Congen,StRegistro,Fec_Suspencion
           INTO bDocumento
           FROM PAQUETE_COMERCIAL
          WHERE CodCia        = nCodCia
            AND CodEmpresa    = nCodEmpresa
            AND IdTipoSeg     = cIdTipoSeg
            AND PLANCOB       = cPlanCob
            --AND UPPER(DESCPAQUETE)   = UPPER(cDescPaquete);
            AND CodPaquete    = nCodPaquete;
      EXCEPTION
         WHEN OTHERS THEN
            bDocumento := EMPTY_BLOB();
      END;
      RETURN bDocumento;
   END DOCUMENTO;
   --
   FUNCTION DESCRIPCION_PAQUETE(nCodCia NUMBER, nCodEmpresa NUMBER, nCodPaquete NUMBER) RETURN VARCHAR2 AS   
        cDESCPAQUETE VARCHAR2(250); 
   BEGIN
        BEGIN
         SELECT DESCPAQUETE --IdTipoSeg,FecRegistro,NumAutorTipSeg,Ds_Arch_Congen,StRegistro,Fec_Suspencion
           INTO cDESCPAQUETE
           FROM PAQUETE_COMERCIAL
          WHERE CodCia        = nCodCia
            AND CodEmpresa    = nCodEmpresa
            AND CodPaquete    = nCodPaquete;
      EXCEPTION
         WHEN OTHERS THEN
            cDESCPAQUETE := null;
      END;
      --
      RETURN cDESCPAQUETE;
      --
   END DESCRIPCION_PAQUETE;     
   --
END GT_PAQUETE_COMERCIAL;
/

--
-- GT_PAQUETE_COMERCIAL  (Synonym) 
--
--  Dependencies: 
--   GT_PAQUETE_COMERCIAL (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM GT_PAQUETE_COMERCIAL FOR SICAS_OC.GT_PAQUETE_COMERCIAL
/


GRANT EXECUTE ON SICAS_OC.GT_PAQUETE_COMERCIAL TO PUBLIC
/
