--
-- GT_PAQUETE_COMERCIAL  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   PAQUETE_COMERCIAL (Table)
--   PAQUETE_COMERCIAL (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.GT_PAQUETE_COMERCIAL IS

      PROCEDURE INSERTA
        (
         in_CODCIA      IN PAQUETE_COMERCIAL.CODCIA%TYPE
        ,in_CODEMPRESA  IN PAQUETE_COMERCIAL.CODEMPRESA%TYPE
        ,in_IDTIPOSEG   IN PAQUETE_COMERCIAL.IDTIPOSEG%TYPE
        ,in_PLANCOB     IN PAQUETE_COMERCIAL.PLANCOB%TYPE
        ,in_CODPAQUETE  IN PAQUETE_COMERCIAL.CODPAQUETE%TYPE
        ,in_DESCPAQUETE IN PAQUETE_COMERCIAL.DESCPAQUETE%TYPE
        );
    --  
    FUNCTION COTIZACIONES_NUMREG(SQLTEXT VARCHAR2) RETURN NUMBER; 
    --
    FUNCTION DOCUMENTO(nCodCia NUMBER, nCodEmpresa NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2, nCodPaquete NUMBER) RETURN BLOB;
    --
END GT_PAQUETE_COMERCIAL;
/

--
-- GT_PAQUETE_COMERCIAL  (Package Body) 
--
--  Dependencies: 
--   GT_PAQUETE_COMERCIAL (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.GT_PAQUETE_COMERCIAL IS

  PROCEDURE INSERTA
    (
     in_CODCIA      IN PAQUETE_COMERCIAL.CODCIA%TYPE
    ,in_CODEMPRESA  IN PAQUETE_COMERCIAL.CODEMPRESA%TYPE
    ,in_IDTIPOSEG   IN PAQUETE_COMERCIAL.IDTIPOSEG%TYPE
    ,in_PLANCOB     IN PAQUETE_COMERCIAL.PLANCOB%TYPE
    ,in_CODPAQUETE  IN PAQUETE_COMERCIAL.CODPAQUETE%TYPE
    ,in_DESCPAQUETE IN PAQUETE_COMERCIAL.DESCPAQUETE%TYPE
    ) IS
  BEGIN
    INSERT INTO PAQUETE_COMERCIAL
      (
       CODCIA
      ,CODEMPRESA
      ,IDTIPOSEG
      ,PLANCOB
      ,CODPAQUETE
      ,DESCPAQUETE
      )
    VALUES
      (
       in_CODCIA
      ,in_CODEMPRESA
      ,in_IDTIPOSEG
      ,in_PLANCOB
      ,in_CODPAQUETE
      ,in_DESCPAQUETE
      );
  END INSERTA;

    FUNCTION COTIZACIONES_NUMREG(SQLTEXT VARCHAR2) RETURN NUMBER IS
        NUMROWS number;
    BEGIN
        EXECUTE IMMEDIATE SQLTEXT INTO NUMROWS;
        RETURN NUMROWS;
    END;
    --
   FUNCTION DOCUMENTO(nCodCia NUMBER, nCodEmpresa NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2, nCodPaquete NUMBER) RETURN BLOB AS
     bDocumento PAQUETE_COMERCIAL.Documento%TYPE;
   BEGIN   
      BEGIN
         SELECT Documento --IdTipoSeg,FecRegistro,NumAutorTipSeg,Ds_Arch_Congen,StRegistro,Fec_Suspencion
           INTO bDocumento
           FROM PAQUETE_COMERCIAL
          WHERE CodCia        = nCodCia
            AND CodEmpresa    = nCodEmpresa
            AND IdTipoSeg     = cIdTipoSeg
            AND PLANCOB       = cPlanCob
            --AND UPPER(DESCPAQUETE)   = UPPER(cDescPaquete);
            AND CodPaquete    = nCodPaquete;
      EXCEPTION
         WHEN OTHERS THEN
            bDocumento := EMPTY_BLOB();
      END;
      RETURN bDocumento;
   END DOCUMENTO;
    --    
END GT_PAQUETE_COMERCIAL;
/

--
-- GT_PAQUETE_COMERCIAL  (Synonym) 
--
--  Dependencies: 
--   GT_PAQUETE_COMERCIAL (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM GT_PAQUETE_COMERCIAL FOR SICAS_OC.GT_PAQUETE_COMERCIAL
/


GRANT EXECUTE ON SICAS_OC.GT_PAQUETE_COMERCIAL TO PUBLIC
/
