CREATE OR REPLACE PACKAGE GT_REA_GRUPO_COBERT_TARIFAS IS

  FUNCTION DESCRIPCION_GRUPO(nCodCia NUMBER, cCodGrupoCobert VARCHAR2) RETURN VARCHAR2;

END GT_REA_GRUPO_COBERT_TARIFAS;
/

CREATE OR REPLACE PACKAGE BODY GT_REA_GRUPO_COBERT_TARIFAS IS

FUNCTION DESCRIPCION_GRUPO(nCodCia NUMBER, cCodGrupoCobert VARCHAR2) RETURN VARCHAR2 IS
cDescGrupoCobert       REA_GRUPO_COBERT_TARIFAS.DescGrupoCobert%TYPE;
BEGIN
   BEGIN
      SELECT DescGrupoCobert
        INTO cDescGrupoCobert
        FROM REA_GRUPO_COBERT_TARIFAS
       WHERE CodCia           = nCodCia
         AND CodGrupoCobert   = cCodGrupoCobert;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescGrupoCobert := 'Grupo NO Existe';
   END;
   RETURN(cDescGrupoCobert);
END DESCRIPCION_GRUPO;

END GT_REA_GRUPO_COBERT_TARIFAS;
