CREATE OR REPLACE PACKAGE GT_REA_CONTINENTES IS

  FUNCTION NOMBRE_CONTINENTE(cCodContinente VARCHAR2) RETURN VARCHAR2;

END GT_REA_CONTINENTES;
/

CREATE OR REPLACE PACKAGE BODY GT_REA_CONTINENTES IS

FUNCTION NOMBRE_CONTINENTE(cCodContinente VARCHAR2) RETURN VARCHAR2 IS
cNomContinente       REA_CONTINENTES.NomContinente%TYPE;
BEGIN
   BEGIN
      SELECT NomContinente
        INTO cNomContinente
        FROM REA_CONTINENTES
       WHERE CodContinente = cCodContinente;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cNomContinente := 'Continente - NO EXISTE';
   END;
   RETURN(cNomContinente);
END NOMBRE_CONTINENTE;

END GT_REA_CONTINENTES;
