CREATE OR REPLACE PACKAGE OC_APLICACIONES IS

  FUNCTION NOMBRE_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2;
  FUNCTION TIPO_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2;

END OC_APLICACIONES;
/

CREATE OR REPLACE PACKAGE BODY OC_APLICACIONES IS

FUNCTION NOMBRE_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2 IS
cDescAplica    APLICACIONES.DescAplica%TYPE;
BEGIN
   BEGIN
      SELECT DescAplica
        INTO cDescAplica
        FROM APLICACIONES
       WHERE CodAplica  = cCodAplica;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescAplica  := 'APLICACION NO EXISTE';
   END;
   RETURN(cDescAplica);
END NOMBRE_APLICACION;

FUNCTION TIPO_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2 IS
cTipoAplic    APLICACIONES.TipoAplic%TYPE;
BEGIN
   BEGIN
      SELECT TipoAplic
        INTO cTipoAplic
        FROM APLICACIONES
       WHERE CodAplica  = cCodAplica;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cTipoAplic  := NULL;
   END;
   RETURN(cTipoAplic);
END TIPO_APLICACION;

END OC_APLICACIONES;
