CREATE OR REPLACE PACKAGE OC_APLICACIONES_AYUDA IS

  FUNCTION NUMERO_AYUDA(cCodAplica VARCHAR2) RETURN NUMBER;

  FUNCTION DOCUMENTO_VIDEO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2;
  FUNCTION FORMATO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2;

END OC_APLICACIONES_AYUDA;
/

CREATE OR REPLACE PACKAGE BODY OC_APLICACIONES_AYUDA IS

FUNCTION NUMERO_AYUDA(cCodAplica VARCHAR2) RETURN NUMBER IS
nIdDocVideoAyuda    APLICACIONES_AYUDA.IdDocVideoAyuda%TYPE;
BEGIN
   SELECT NVL(MAX(IdDocVideoAyuda),0) + 1
     INTO nIdDocVideoAyuda
     FROM APLICACIONES_AYUDA
    WHERE CodAplica  = cCodAplica;

   RETURN(nIdDocVideoAyuda);
END NUMERO_AYUDA;


FUNCTION DOCUMENTO_VIDEO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2 IS
cNombreDocumVideo    APLICACIONES_AYUDA.NombreDocumVideo%TYPE;
BEGIN
   BEGIN
      SELECT NombreDocumVideo
        INTO cNombreDocumVideo
        FROM APLICACIONES_AYUDA
       WHERE CodAplica       = cCodAplica
         AND IdDocVideoAyuda = nIdDocVideoAyuda;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cNombreDocumVideo  := NULL;
   END;
   RETURN(cNombreDocumVideo);
END DOCUMENTO_VIDEO_AYUDA;

FUNCTION FORMATO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2 IS
cFormato    APLICACIONES_AYUDA.Formato%TYPE;
BEGIN
   BEGIN
      SELECT Formato
        INTO cFormato
        FROM APLICACIONES_AYUDA
       WHERE CodAplica       = cCodAplica
         AND IdDocVideoAyuda = nIdDocVideoAyuda;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cFormato  := NULL;
   END;
   RETURN(cFormato);
END FORMATO_AYUDA;

END OC_APLICACIONES_AYUDA;
