--
-- OC_ADMON_ACTIVI_RELEVANTES  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   ADMON_ACTIVI_RELEVANTES (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_ADMON_ACTIVI_RELEVANTES AS

  PROCEDURE ELIMINAR(nCodCia NUMBER, nIdProceso NUMBER, nIdPoliza NUMBER, nIdetPoliza NUMBER);

END OC_ADMON_ACTIVI_RELEVANTES;
/

--
-- OC_ADMON_ACTIVI_RELEVANTES  (Package Body) 
--
--  Dependencies: 
--   OC_ADMON_ACTIVI_RELEVANTES (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_ADMON_ACTIVI_RELEVANTES AS

PROCEDURE ELIMINAR(nCodCia NUMBER, nIdProceso NUMBER, nIdPoliza NUMBER, nIdetPoliza NUMBER) IS
BEGIN
   DELETE ADMON_ACTIVI_RELEVANTES
    WHERE CODCIA        = nCodCia
      AND ID_PROCESO    = nIdProceso
      AND IDPOLIZA      = nIdPoliza
      AND IDETPOL	= nIdetPoliza;
END ELIMINAR;

END OC_ADMON_ACTIVI_RELEVANTES ;
/
