--
-- OC_ADMON_ACTIVI_FONDOS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   ADMON_ACTIVI_FONDOS (Table)
--   OC_ADMON_ACTIVI_FONDOS_H (Package)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_ADMON_ACTIVI_FONDOS IS

PROCEDURE INSERTA(P_CODCIA    NUMBER    ,
      P_CODEMPRESA    NUMBER    ,
      P_IDTIPOSEG    VARCHAR2  ,
      P_IDPOLIZA    NUMBER    ,
      P_IDETPOL    NUMBER    ,
      P_NUMSECUENCIA NUMBER,      
      P_CODASEGURADO  NUMBER    ,
      P_NOMBREASEGURADO         VARCHAR2,
      P_FORMPAGO    VARCHAR2  ,
      P_FECEVALUACION  DATE    ,
      P_NUMAPORTPLANFE  NUMBER    ,
      P_NUMAPORTCRITOK  NUMBER    ,
      P_NUMAPORTREALFE  NUMBER    ,
      P_IMPTEPLANAPORFE  NUMBER    ,
      P_IMPTEAPORCRITOK  NUMBER    ,
      P_IMPTEACUMAPORFE  NUMBER    ,
      P_NUMRETICRITOK  NUMBER    ,
      P_NUMRETREALFE  NUMBER    ,
      P_RESULTADOEVAL  VARCHAR2  ,
      P_STATUSREVISION  VARCHAR2  ,
      P_OBSERVACIONES  VARCHAR2  ,
      P_FECHAREVISION  DATE    ,
      P_USUARIOREVISA  VARCHAR2
                  );

END OC_ADMON_ACTIVI_FONDOS;
/

--
-- OC_ADMON_ACTIVI_FONDOS  (Package Body) 
--
--  Dependencies: 
--   OC_ADMON_ACTIVI_FONDOS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_ADMON_ACTIVI_FONDOS IS
--

PROCEDURE INSERTA(P_CODCIA    NUMBER    ,
      P_CODEMPRESA    NUMBER    ,
      P_IDTIPOSEG    VARCHAR2  ,
      P_IDPOLIZA    NUMBER    ,
      P_IDETPOL    NUMBER    ,      
      P_NUMSECUENCIA NUMBER,
      P_CODASEGURADO  NUMBER    ,
      P_NOMBREASEGURADO         VARCHAR2,
      P_FORMPAGO    VARCHAR2  ,
      P_FECEVALUACION  DATE    ,
      P_NUMAPORTPLANFE  NUMBER    ,
      P_NUMAPORTCRITOK  NUMBER    ,
      P_NUMAPORTREALFE  NUMBER    ,
      P_IMPTEPLANAPORFE  NUMBER    ,
      P_IMPTEAPORCRITOK  NUMBER    ,
      P_IMPTEACUMAPORFE  NUMBER    ,
      P_NUMRETICRITOK  NUMBER    ,
      P_NUMRETREALFE  NUMBER    ,
      P_RESULTADOEVAL  VARCHAR2  ,
      P_STATUSREVISION  VARCHAR2  ,
      P_OBSERVACIONES  VARCHAR2  ,
      P_FECHAREVISION  DATE    ,
      P_USUARIOREVISA  VARCHAR2
                 ) IS
--
BEGIN
  --
  --INSERTA ADMON_ACTIVI_FONDOS
  --
  INSERT INTO ADMON_ACTIVI_FONDOS
    (CODCIA,     CODEMPRESA,      IDTIPOSEG,       IDPOLIZA,      IDETPOL, NUMSECUENCIA,
     CODASEGURADO,  NOMBREASEGURADO, FORMPAGO,      FECEVALUACION,       NUMAPORTPLANFE,
     NUMAPORTCRITOK,   NUMAPORTREALFE,    IMPTEPLANAPORFE, IMPTEAPORCRITOK,   IMPTEACUMAPORFE,
     NUMRETICRITOK,   NUMRETREALFE,      RESULTADOEVAL,   STATUSREVISION,    OBSERVACIONES,
     FECHAREVISION,   USUARIOREVISA)
    VALUES
    (P_CODCIA,     P_CODEMPRESA,      P_IDTIPOSEG,       P_IDPOLIZA,    P_IDETPOL, P_NUMSECUENCIA ,
     P_CODASEGURADO,  P_NOMBREASEGURADO, P_FORMPAGO,      P_FECEVALUACION,    P_NUMAPORTPLANFE,
     P_NUMAPORTCRITOK,  P_NUMAPORTREALFE,  P_IMPTEPLANAPORFE, P_IMPTEAPORCRITOK, P_IMPTEACUMAPORFE,
     P_NUMRETICRITOK,   P_NUMRETREALFE,    P_RESULTADOEVAL,   P_STATUSREVISION,  P_OBSERVACIONES,
     P_FECHAREVISION,   P_USUARIOREVISA);
  --
     COMMIT;

     OC_ADMON_ACTIVI_FONDOS_H.INSERTA(P_CODCIA       ,
      P_CODEMPRESA       ,
      P_IDTIPOSEG      ,
      P_IDPOLIZA      ,
      P_IDETPOL       ,
      P_NUMSECUENCIA ,
      P_CODASEGURADO      ,
      P_NOMBREASEGURADO   ,
      P_FORMPAGO     ,
      P_FECEVALUACION     ,
      P_NUMAPORTPLANFE      ,
      P_NUMAPORTCRITOK      ,
      P_NUMAPORTREALFE     ,
      P_IMPTEPLANAPORFE      ,
      P_IMPTEAPORCRITOK      ,
      P_IMPTEACUMAPORFE      ,
      P_NUMRETICRITOK     ,
      P_NUMRETREALFE      ,
      P_RESULTADOEVAL    ,
      P_STATUSREVISION    ,
      P_OBSERVACIONES    ,
      P_FECHAREVISION      ,
      P_USUARIOREVISA  
                 );
END INSERTA;
--

END OC_ADMON_ACTIVI_FONDOS;
/
