--
-- OC_APLICACIONES  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   APLICACIONES (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_APLICACIONES IS

  FUNCTION NOMBRE_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2;
  FUNCTION TIPO_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2;

END OC_APLICACIONES;
/

--
-- OC_APLICACIONES  (Package Body) 
--
--  Dependencies: 
--   OC_APLICACIONES (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_APLICACIONES IS

FUNCTION NOMBRE_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2 IS
cDescAplica    APLICACIONES.DescAplica%TYPE;
BEGIN
   BEGIN
      SELECT DescAplica
        INTO cDescAplica
        FROM APLICACIONES
       WHERE CodAplica  = cCodAplica;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescAplica  := 'APLICACION NO EXISTE';
   END;
   RETURN(cDescAplica);
END NOMBRE_APLICACION;

FUNCTION TIPO_APLICACION(cCodAplica VARCHAR2) RETURN VARCHAR2 IS
cTipoAplic    APLICACIONES.TipoAplic%TYPE;
BEGIN
   BEGIN
      SELECT TipoAplic
        INTO cTipoAplic
        FROM APLICACIONES
       WHERE CodAplica  = cCodAplica;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cTipoAplic  := NULL;
   END;
   RETURN(cTipoAplic);
END TIPO_APLICACION;

END OC_APLICACIONES;
/

--
-- OC_APLICACIONES  (Synonym) 
--
--  Dependencies: 
--   OC_APLICACIONES (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_APLICACIONES FOR SICAS_OC.OC_APLICACIONES
/


GRANT EXECUTE, DEBUG ON SICAS_OC.OC_APLICACIONES TO PUBLIC
/
