CREATE OR REPLACE PACKAGE          OC_ADMON_RIESGO_SINIESTROS_H IS

PROCEDURE INSERTA(
      P_CODCIA    	NUMBER    ,
      P_CODEMPRESA    	NUMBER    ,
      P_ID_PROCESO    	NUMBER  ,
      P_IDPOLIZA      	NUMBER    ,
      P_STSPOLIZA     	VARCHAR2   ,
      P_CODCLIENTE    	NUMBER,
      P_NUMSINIESTRO  	NUMBER    ,
      P_ORIGEN        	VARCHAR2,
      P_TIPO_DOC_IDENTIFICACION	VARCHAR2,
      P_NUM_DOC_IDENTIFICACION	VARCHAR2,
      P_NOMBRE_BENEFICIARIO	VARCHAR2,
      P_ST_RESOLUCION	VARCHAR2,
      P_FE_ESTATUS	DATE ,
      P_TP_RESOLUCION	VARCHAR2,
      P_OBSERVACIONES	VARCHAR2,
      P_FECHA_PROCESO  	DATE    ,
      P_USUARIO  	VARCHAR2
                  );

END OC_ADMON_RIESGO_SINIESTROS_H;
/

CREATE OR REPLACE PACKAGE BODY          OC_ADMON_RIESGO_SINIESTROS_H IS
--

PROCEDURE INSERTA(
      P_CODCIA    	NUMBER ,
      P_CODEMPRESA    	NUMBER ,
      P_ID_PROCESO    	NUMBER ,
      P_IDPOLIZA      	NUMBER ,
      P_STSPOLIZA     	VARCHAR2 ,
      P_CODCLIENTE    	NUMBER ,
      P_NUMSINIESTRO  	NUMBER ,
      P_ORIGEN        	VARCHAR2 ,
      P_TIPO_DOC_IDENTIFICACION	VARCHAR2,
      P_NUM_DOC_IDENTIFICACION	VARCHAR2,
      P_NOMBRE_BENEFICIARIO	VARCHAR2,
      P_ST_RESOLUCION	VARCHAR2,
      P_FE_ESTATUS	DATE ,
      P_TP_RESOLUCION	VARCHAR2,
      P_OBSERVACIONES	VARCHAR2,
      P_FECHA_PROCESO  	DATE    ,
      P_USUARIO  	VARCHAR2
                 ) IS
--
BEGIN
  --
  --INSERTA ADMON_RIESGO_SINIESTROS
  --
  INSERT INTO ADMON_RIESGO_SINIESTROS_H
    (  CODCIA  ,
       CODEMPRESA  ,
       ID_PROCESO  ,
       IDPOLIZA  ,
       STSPOLIZA ,
       CODCLIENTE ,
       NUMSINIESTRO ,
       ORIGEN ,
       TIPO_DOC_IDENTIFICACION,
       NUM_DOC_IDENTIFICACION,
       NOMBRE_BENEFICIARIO,
       ST_RESOLUCION,
       FE_ESTATUS,
       TP_RESOLUCION,
       OBSERVACIONES,
       FECHA_PROCESO ,
       USUARIO )
    VALUES
    ( P_CODCIA  ,
      P_CODEMPRESA ,
      P_ID_PROCESO ,
      P_IDPOLIZA  ,
      P_STSPOLIZA ,
      P_CODCLIENTE ,
      P_NUMSINIESTRO ,
      P_ORIGEN  ,
      P_TIPO_DOC_IDENTIFICACION	,
      P_NUM_DOC_IDENTIFICACION	,
      P_NOMBRE_BENEFICIARIO	,
      P_ST_RESOLUCION	,
      P_FE_ESTATUS	,
      P_TP_RESOLUCION	,
      P_OBSERVACIONES	,
      P_FECHA_PROCESO  ,
      P_USUARIO );
  --
     COMMIT;
     
END INSERTA;
--

END OC_ADMON_RIESGO_SINIESTROS_H;
