--
-- OC_APLICACIONES_AYUDA  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   APLICACIONES_AYUDA (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_APLICACIONES_AYUDA IS

  FUNCTION NUMERO_AYUDA(cCodAplica VARCHAR2) RETURN NUMBER;

  FUNCTION DOCUMENTO_VIDEO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2;
  FUNCTION FORMATO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2;

END OC_APLICACIONES_AYUDA;
/

--
-- OC_APLICACIONES_AYUDA  (Package Body) 
--
--  Dependencies: 
--   OC_APLICACIONES_AYUDA (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_APLICACIONES_AYUDA IS

FUNCTION NUMERO_AYUDA(cCodAplica VARCHAR2) RETURN NUMBER IS
nIdDocVideoAyuda    APLICACIONES_AYUDA.IdDocVideoAyuda%TYPE;
BEGIN
   SELECT NVL(MAX(IdDocVideoAyuda),0) + 1
     INTO nIdDocVideoAyuda
     FROM APLICACIONES_AYUDA
    WHERE CodAplica  = cCodAplica;

   RETURN(nIdDocVideoAyuda);
END NUMERO_AYUDA;


FUNCTION DOCUMENTO_VIDEO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2 IS
cNombreDocumVideo    APLICACIONES_AYUDA.NombreDocumVideo%TYPE;
BEGIN
   BEGIN
      SELECT NombreDocumVideo
        INTO cNombreDocumVideo
        FROM APLICACIONES_AYUDA
       WHERE CodAplica       = cCodAplica
         AND IdDocVideoAyuda = nIdDocVideoAyuda;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cNombreDocumVideo  := NULL;
   END;
   RETURN(cNombreDocumVideo);
END DOCUMENTO_VIDEO_AYUDA;

FUNCTION FORMATO_AYUDA(cCodAplica VARCHAR2, nIdDocVideoAyuda NUMBER) RETURN VARCHAR2 IS
cFormato    APLICACIONES_AYUDA.Formato%TYPE;
BEGIN
   BEGIN
      SELECT Formato
        INTO cFormato
        FROM APLICACIONES_AYUDA
       WHERE CodAplica       = cCodAplica
         AND IdDocVideoAyuda = nIdDocVideoAyuda;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cFormato  := NULL;
   END;
   RETURN(cFormato);
END FORMATO_AYUDA;

END OC_APLICACIONES_AYUDA;
/

--
-- OC_APLICACIONES_AYUDA  (Synonym) 
--
--  Dependencies: 
--   OC_APLICACIONES_AYUDA (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_APLICACIONES_AYUDA FOR SICAS_OC.OC_APLICACIONES_AYUDA
/


GRANT EXECUTE, DEBUG ON SICAS_OC.OC_APLICACIONES_AYUDA TO PUBLIC
/
