--
-- OC_CFG_ENDOSOS_SV  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_STANDARD (Package)
--   CFG_ENDOSOS_SV (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_CFG_ENDOSOS_SV IS

  FUNCTION DESCRIPCION_ENDOSO(nCorrConf NUMBER) RETURN VARCHAR2;

  FUNCTION FORMA_ENDOSO(nCorrConf NUMBER) RETURN VARCHAR2;

  FUNCTION NUMERO_CORRELATIVO RETURN NUMBER;

END OC_CFG_ENDOSOS_SV;
/

--
-- OC_CFG_ENDOSOS_SV  (Package Body) 
--
--  Dependencies: 
--   OC_CFG_ENDOSOS_SV (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_CFG_ENDOSOS_SV IS

FUNCTION DESCRIPCION_ENDOSO(nCorrConf NUMBER) RETURN VARCHAR2 IS
cDescripcion   CFG_ENDOSOS_SV.Descripcion%TYPE;
BEGIN
   BEGIN
      SELECT Descripcion
        INTO cDescripcion
        FROM CFG_ENDOSOS_SV
       WHERE CorrConf  = nCorrConf;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         RAISE_APPLICATION_ERROR(-20225,'NO Existe Configuración de Endoso Sin Valor No. '|| nCorrConf);
      WHEN TOO_MANY_ROWS THEN
         RAISE_APPLICATION_ERROR(-20225,'Existen Varios Registros de Endoso Sin Valor No. '|| nCorrConf);
   END;
   RETURN(cDescripcion);
END DESCRIPCION_ENDOSO;

FUNCTION FORMA_ENDOSO(nCorrConf NUMBER) RETURN VARCHAR2 IS
cForma   CFG_ENDOSOS_SV.Forma%TYPE;
BEGIN
   BEGIN
      SELECT Forma
        INTO cForma
        FROM CFG_ENDOSOS_SV
       WHERE CorrConf  = nCorrConf;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         RAISE_APPLICATION_ERROR(-20225,'NO Existe Configuración de Endoso Sin Valor No. '|| nCorrConf);
      WHEN TOO_MANY_ROWS THEN
         RAISE_APPLICATION_ERROR(-20225,'Existen Varios Registros de Endoso Sin Valor No. '|| nCorrConf);
   END;
   RETURN(cForma);
END FORMA_ENDOSO;

FUNCTION NUMERO_CORRELATIVO RETURN NUMBER IS
nCorrConf   CFG_ENDOSOS_SV.CorrConf%TYPE;
BEGIN
   BEGIN
      SELECT NVL(MAX(CorrConf),0)
        INTO nCorrConf
        FROM CFG_ENDOSOS_SV;
   END;
   RETURN(nCorrConf);
END NUMERO_CORRELATIVO;

END OC_CFG_ENDOSOS_SV;
/
