CREATE OR REPLACE PACKAGE OC_CLIENTE_ASEG IS

  PROCEDURE INSERTA(nCodCliente NUMBER, nCod_Asegurado NUMBER);

END OC_CLIENTE_ASEG;
/

CREATE OR REPLACE PACKAGE BODY OC_CLIENTE_ASEG IS

PROCEDURE INSERTA(nCodCliente NUMBER, nCod_Asegurado NUMBER) IS
BEGIN
   BEGIN
      INSERT INTO CLIENTE_ASEG
            (CodCliente, Cod_Asegurado)
      VALUES(nCodCliente, nCod_Asegurado);
   EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN
         NULL;
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20225,'Error al Insertar CLIENTE_ASEG '||SQLERRM);
   END;
END INSERTA;

END OC_CLIENTE_ASEG;
