CREATE OR REPLACE PACKAGE OC_CPTOS_TRANSAC_SINIESTROS IS

  FUNCTION CONCEPTO_TRANSACCION(nCodCia NUMBER, cCodTransac VARCHAR, cIndTipoCobert VARCHAR2) RETURN VARCHAR2;

END OC_CPTOS_TRANSAC_SINIESTROS;
/

CREATE OR REPLACE PACKAGE BODY OC_CPTOS_TRANSAC_SINIESTROS IS

FUNCTION CONCEPTO_TRANSACCION(nCodCia NUMBER, cCodTransac VARCHAR, cIndTipoCobert VARCHAR2) RETURN VARCHAR2 IS
cCodCptoTransac    CPTOS_TRANSAC_SINIESTROS.CodCptoTransac%TYPE;
BEGIN
   BEGIN
      SELECT CodCptoTransac
        INTO cCodCptoTransac
        FROM CPTOS_TRANSAC_SINIESTROS
       WHERE CodCia         = nCodCia
         AND CodTransac     = cCodTransac
                        AND IndTipoCobert IN (cIndTipoCobert, 'TO');
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         RAISE_APPLICATION_ERROR(-20225,'NO Existe Concepto Configurado para Transaccion '||TRIM(cCodTransac));
   END;
   RETURN(cCodCptoTransac);
END CONCEPTO_TRANSACCION;

END OC_CPTOS_TRANSAC_SINIESTROS;
