CREATE OR REPLACE PACKAGE OC_CAT_CEDULAS_TIPOS_SEGUROS IS

PROCEDURE INSERTA(
      P_CODEMPRESA      NUMBER ,
      P_CODCIA          NUMBER ,      
      P_TIPO_CEDULA     VARCHAR2,
      P_IDTIPOSEG       VARCHAR2,
      P_STSREGISTRO     VARCHAR2,
      P_FECHASTATUS     DATE 
                   );

END OC_CAT_CEDULAS_TIPOS_SEGUROS;
/

CREATE OR REPLACE PACKAGE BODY OC_CAT_CEDULAS_TIPOS_SEGUROS IS


PROCEDURE INSERTA(
      P_CODEMPRESA      NUMBER ,
      P_CODCIA          NUMBER ,      
      P_TIPO_CEDULA     VARCHAR2,
      P_IDTIPOSEG       VARCHAR2,
      P_STSREGISTRO     VARCHAR2,
      P_FECHASTATUS     DATE 
                 ) IS
--
BEGIN
  --
  --INSERTA ADMON_RIESGO_SINIESTROS
  --
  INSERT INTO CATALOGO_CEDULAS_TIPOS_SEGUROS
    (  CODEMPRESA  ,
       CODCIA  ,       
       TIPO_CEDULA  ,
       IDTIPOSEG  ,
       STSREGISTRO ,
       FECHASTATUS )
    VALUES
    ( P_CODEMPRESA  ,
      P_CODCIA  ,       
      P_TIPO_CEDULA  ,
      P_IDTIPOSEG  ,
      P_STSREGISTRO ,
      P_FECHASTATUS );
  --
     COMMIT;

END INSERTA;
--

END OC_CAT_CEDULAS_TIPOS_SEGUROS;
