CREATE OR REPLACE PACKAGE OC_CAT_REGIMEN_FISCAL AS

    FUNCTION FUN_NOMBRE_REGFIS (nIdRegimen NUMBER)  RETURN VARCHAR2;
    FUNCTION FUN_PROCENTAJEISR (nIdRegimen NUMBER)  RETURN VARCHAR2;
    FUNCTION FUN_NIVELCTA3      (nIdRegimen NUMBER)  RETURN VARCHAR2;


END OC_CAT_REGIMEN_FISCAL;

/

CREATE OR REPLACE PACKAGE BODY OC_CAT_REGIMEN_FISCAL IS

    FUNCTION FUN_NOMBRE_REGFIS ( nIdRegimen NUMBER) RETURN VARCHAR2 IS
        cNomRegFis      CAT_REGIMEN_FISCAL.DescTipoRegimen%TYPE;
    BEGIN

         SELECT DescTipoRegimen
           INTO cNomRegFis
           FROM CAT_REGIMEN_FISCAL C
          WHERE IdRegFisSAT = nIdRegimen;
       --
       RETURN ( cNomRegFis );

    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END FUN_NOMBRE_REGFIS;
    --
    FUNCTION FUN_PROCENTAJEISR ( nIdRegimen NUMBER) RETURN VARCHAR2 IS
        cPORCCONCEPTO      CAT_REGIMEN_FISCAL.PORCCONCEPTO%TYPE;
    BEGIN

         SELECT PORCCONCEPTO
           INTO cPORCCONCEPTO
           FROM CAT_REGIMEN_FISCAL C
          WHERE IdRegFisSAT = nIdRegimen;
       --
       RETURN ( cPORCCONCEPTO );

    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END FUN_PROCENTAJEISR;
    --
    FUNCTION FUN_NIVELCTA3 ( nIdRegimen NUMBER) RETURN VARCHAR2 IS
        cNIVELCTA3      CAT_REGIMEN_FISCAL.NIVELCTA3%TYPE;
    BEGIN

         SELECT NIVELCTA3
           INTO CNIVELCTA3
           FROM CAT_REGIMEN_FISCAL C
          WHERE IdRegFisSAT = nIdRegimen;
       --
       RETURN ( cNIVELCTA3 );

    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END FUN_NIVELCTA3;
    --

END OC_CAT_REGIMEN_FISCAL;
