--
-- OC_DIRECCION_REGIONAL_TIPOSEG  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DIRECCION_REGIONAL_TIPOSEG (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_DIRECCION_REGIONAL_TIPOSEG IS

  PROCEDURE ACTIVAR_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2);
  PROCEDURE SUSPENDER_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2);

END OC_DIRECCION_REGIONAL_TIPOSEG;
/

--
-- OC_DIRECCION_REGIONAL_TIPOSEG  (Package Body) 
--
--  Dependencies: 
--   OC_DIRECCION_REGIONAL_TIPOSEG (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_DIRECCION_REGIONAL_TIPOSEG IS

PROCEDURE ACTIVAR_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2) IS
BEGIN
   UPDATE DIRECCION_REGIONAL_TIPOSEG
      SET StsIdTipoSeg  = 'ACTIV',
          FecSts        = TRUNC(SYSDATE)
    WHERE CodCia           = nCodCia
      AND CodDirecRegional = nCodDirecRegional
      AND IdTipoSeg        = cIdTipoSeg
      AND PlanCob          = cPlanCob;
END ACTIVAR_TIPOSEG_PLAN;

PROCEDURE SUSPENDER_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2) IS
BEGIN
   UPDATE DIRECCION_REGIONAL_TIPOSEG
      SET StsIdTipoSeg  = 'SUSPEN',
          FecSts        = TRUNC(SYSDATE)
    WHERE CodCia           = nCodCia
      AND CodDirecRegional = nCodDirecRegional
      AND IdTipoSeg        = cIdTipoSeg
      AND PlanCob          = cPlanCob;
END SUSPENDER_TIPOSEG_PLAN;

END OC_DIRECCION_REGIONAL_TIPOSEG;
/

--
-- OC_DIRECCION_REGIONAL_TIPOSEG  (Synonym) 
--
--  Dependencies: 
--   OC_DIRECCION_REGIONAL_TIPOSEG (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_DIRECCION_REGIONAL_TIPOSEG FOR SICAS_OC.OC_DIRECCION_REGIONAL_TIPOSEG
/


GRANT EXECUTE ON SICAS_OC.OC_DIRECCION_REGIONAL_TIPOSEG TO PUBLIC
/
