--
-- OC_DDL_OBJETOS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_STANDARD (Package)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_DDL_OBJETOS IS
cMsgResp varchar2(4000);
PROCEDURE EJECUTAR_SQL (pSql IN VARCHAR2);
FUNCTION EJECUTAR_QUERY (pSql IN VARCHAR2) RETURN VARCHAR2;
FUNCTION EJECUTAR_FUNCTION (pSql IN VARCHAR2) RETURN VARCHAR2;
END;
/

--
-- OC_DDL_OBJETOS  (Package Body) 
--
--  Dependencies: 
--   OC_DDL_OBJETOS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_DDL_OBJETOS IS
--
PROCEDURE EJECUTAR_SQL( pSql IN VARCHAR2) IS
varfechini   timestamp   := systimestamp;
BEGIN
  EXECUTE IMMEDIATE pSql;
EXCEPTION WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20201,'E001 AL EJECUTAR SENTENCIA '||SQLERRM||'-->'||PSQL);
END EJECUTAR_SQL;
--
FUNCTION EJECUTAR_QUERY (pSql IN VARCHAR2) RETURN VARCHAR2 IS
cValorCampo   VARCHAR2(1000);
BEGIN
  EXECUTE IMMEDIATE pSql INTO cValorCampo;
  RETURN(cValorCampo);
EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN(0);
         WHEN TOO_MANY_ROWS THEN
  RETURN('1');
          WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20201,'E001 AL EJECUTAR SENTENCIA '||SQLERRM||'-->'||PSQL);
END EJECUTAR_QUERY;
--
FUNCTION EJECUTAR_FUNCTION (pSql IN VARCHAR2) RETURN VARCHAR2 IS
cValorCampo   VARCHAR2(4000);
cQuery        VARCHAR2(4000);
BEGIN
  cQuery := 'BEGIN :this := '||pSql||' END;';
  EXECUTE IMMEDIATE cQuery USING IN OUT cValorCampo;
  RETURN(cValorCampo);
EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN(0);
          WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20201,'E001 AL EJECUTAR SENTENCIA '||SQLERRM||'-->'||PSQL);
END EJECUTAR_FUNCTION;
--
END;
/

--
-- OC_DDL_OBJETOS  (Synonym) 
--
--  Dependencies: 
--   OC_DDL_OBJETOS (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_DDL_OBJETOS FOR SICAS_OC.OC_DDL_OBJETOS
/


GRANT EXECUTE ON SICAS_OC.OC_DDL_OBJETOS TO PUBLIC
/
