CREATE OR REPLACE PACKAGE OC_DIRECCION_REGIONAL_TIPOSEG IS

  PROCEDURE ACTIVAR_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2);
  PROCEDURE SUSPENDER_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2);

END OC_DIRECCION_REGIONAL_TIPOSEG;
/

CREATE OR REPLACE PACKAGE BODY OC_DIRECCION_REGIONAL_TIPOSEG IS

PROCEDURE ACTIVAR_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2) IS
BEGIN
   UPDATE DIRECCION_REGIONAL_TIPOSEG
      SET StsIdTipoSeg  = 'ACTIV',
          FecSts        = TRUNC(SYSDATE)
    WHERE CodCia           = nCodCia
      AND CodDirecRegional = nCodDirecRegional
      AND IdTipoSeg        = cIdTipoSeg
      AND PlanCob          = cPlanCob;
END ACTIVAR_TIPOSEG_PLAN;

PROCEDURE SUSPENDER_TIPOSEG_PLAN(nCodCia NUMBER, nCodDirecRegional NUMBER, cIdTipoSeg VARCHAR2, cPlanCob VARCHAR2) IS
BEGIN
   UPDATE DIRECCION_REGIONAL_TIPOSEG
      SET StsIdTipoSeg  = 'SUSPEN',
          FecSts        = TRUNC(SYSDATE)
    WHERE CodCia           = nCodCia
      AND CodDirecRegional = nCodDirecRegional
      AND IdTipoSeg        = cIdTipoSeg
      AND PlanCob          = cPlanCob;
END SUSPENDER_TIPOSEG_PLAN;

END OC_DIRECCION_REGIONAL_TIPOSEG;
