CREATE OR REPLACE PACKAGE SICAS_OC.OC_ENDOSO_ESPECIAL IS
/***********************************************************************************/
/* PAQUETE PARA LA CREACIÓN DE ENDOSOS ESPECIALES SIN VALOR PARA MODIFICACIONES DE */
/* DATOS                                                                           */
/* FECHA CREACION : 19/12/2023                                                     */
/* CREO :           MARIA DE LA LUZ JIMENEZ SILVA                                  */
/***********************************************************************************/

    PROCEDURE INSERTA_ENDOSO_ESPECIAL(NIDPOLIZA   NUMBER, nIDetPol  NUMBER,   CUSUARIO VARCHAR2, CTERMINAL VARCHAR2,
                                      CTIPOENDOSO VARCHAR2, NVALORANT VARCHAR2, NVALORNUE VARCHAR2,NVALORANT2 VARCHAR2 DEFAULT NULL,
                                      NVALORNUE2 VARCHAR2 DEFAULT NULL,       PERROR OUT NUMBER , PDESCERROR OUT VARCHAR2        );

    PROCEDURE INSERTA_ENDOSO_SEGUIMIENTO(NIDPOLIZA NUMBER, nIdEndoso NUMBER, nIDetPol NUMBER, NNUMENDREF VARCHAR2,CUSUARIO VARCHAR2, CTERMINAL VARCHAR2);

    PROCEDURE INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA NUMBER, nIdEndoso NUMBER, nIDetPol NUMBER, NCORRELATIVO NUMBER,NCAMPO VARCHAR2, NVALOR_ANTERIOR VARCHAR2, NVALOR_ACTUAL VARCHAR2, NTABLA VARCHAR2, NCAMPOREF VARCHAR2);

    FUNCTION OBTENER_CORRELATIVO (nIdPoliza NUMBER )RETURN NUMBER;

END OC_ENDOSO_ESPECIAL;
/
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_ENDOSO_ESPECIAL IS

  PROCEDURE INSERTA_ENDOSO_ESPECIAL(NIDPOLIZA NUMBER, nIDetPol NUMBER,CUSUARIO VARCHAR2, CTERMINAL VARCHAR2, CTIPOENDOSO VARCHAR2, NVALORANT VARCHAR2, NVALORNUE VARCHAR2,NVALORANT2 VARCHAR2 DEFAULT NULL, NVALORNUE2 VARCHAR2 DEFAULT NULL,
            PERROR OUT NUMBER , PDESCERROR OUT VARCHAR2)  IS -- Este es para hacer modificaciones especiales y generar el endoso

    nIdEndoso    NUMBER(5);
    CDESCENDOSO  VARCHAR2(1000);
    NNUMENDREF   VARCHAR2(20);
    NCORRELATIVO NUMBER;
    NERROR       NUMBER         := 0;
    NDESCERROR   VARCHAR2(1000) := NULL;

    eERROR       EXCEPTION;

    dFecIniVig		DATE;
    dFecFinVig		DATE;

    BEGIN
     PERROR     := 0;
     PDESCERROR := NULL;
    nIdEndoso  := OC_ENDOSO.CREAR(NIDPOLIZA);
    NNUMENDREF := 'END-'||nIdPoliza||'-'|| nIdendoso;

    --036 Cambio de Uso de CFDI
    --IF NTIPOENDOSO = 036 THEN
    --Se actualiza el valor en las tablas DETALLE_POLIZA y POLIZAS
    BEGIN

      UPDATE DETALLE_POLIZA D SET D.CODOBJETOIMP = NVL(NVALORNUE2, D.CODOBJETOIMP),
      D.CODUSOCFDI   = NVL(NVALORNUE, D.CODUSOCFDI )
      WHERE IDPOLIZA = NIDPOLIZA;

    EXCEPTION
      WHEN OTHERS THEN
        NERROR     := 2000;
        NDESCERROR := NDESCERROR||' ERRROR ACTUALIZANDO EL DETALLE_POLIZA';
        RAISE eERROR;
    END;

    BEGIN
      UPDATE POLIZAS SET  CODOBJETOIMP = NVL(NVALORNUE2,CODOBJETOIMP),
      CODUSOCFDI   = NVL(NVALORNUE,CODUSOCFDI)
      WHERE  IDPOLIZA = NIDPOLIZA;
    EXCEPTION
      WHEN OTHERS THEN
        NERROR     := 2000;
        NDESCERROR := NDESCERROR||' ERRROR ACTUALIZANDO LA POLIZAS ';
        RAISE eERROR;
    END;

    CDESCENDOSO:='SE CREO ENDOSO SIN VALOR PARA EL CAMBIO DE USO DE CFDI EL DIA,'|| SYSTIMESTAMP ||'POR EL USUARIO, '|| CUSUARIO ||', EN LA TERMINAL - '||CTERMINAL;

    --SE CREA EL ENDOSO
    -- SE OBTIENE LA VIGENCIA DEL ENDOSO EN BASE A LA VIGENCIA DE LA PÓLIZA --MLJS 09/04/2024
     SELECT FecIniVig, FecFinVig
       INTO dFecIniVig, dFecFinVig
       FROM POLIZAS
      WHERE IdPoliza = NIDPOLIZA;

    Insert into ENDOSOS (IDPOLIZA,IDENDOSO    ,TIPOENDOSO,NUMENDREF,FECINIVIG,FECFINVIG,   FECSOLICITUD,  FECEMISION,     STSENDOSO,FECSTS        ,
                         CODPLANPAGO,FECANUL  ,MOTIVANUL,SUMA_ASEG_LOCAL,SUMA_ASEG_MONEDA,PRIMA_NETA_LOCAL,DESCENDOSO   ,PRIMA_NETA_MONEDA,
                         PORCCOMIS,CODEMPRESA ,CODCIA,IDETPOL,NUM_BIEN,MOTIVO_ENDOSO ,FECEXC,INDCALCDERECHOEMIS,PLDSTBLOQUEADA,PLDSTAPROBADA,PLDUSUARIOAPROB,MONTOAPORTEFONDO,CVE_MOTIVCANCFACT,CODOBJETOIMP,CODUSOCFDI)
    values              (NIDPOLIZA  ,nIdEndoso,'ESV'    ,NNUMENDREF,dFecIniVig,dFecFinVig,TRUNC(SYSDATE) ,TRUNC(SYSDATE),'EMI'     ,TRUNC(SYSDATE),
                         null       ,null     ,null     ,0              ,0               ,0               ,CDESCENDOSO  ,0        ,
                         0        , 1         ,1      ,nIDetPol,null  ,CTIPOENDOSO   ,NULL,'N',null,null,null,null,null,NVALORNUE2,NVALORNUE);

   -- END IF;

    -- SE INSERTA LA DESCRIPCIÓN DEL ENDOSO
    OC_ENDOSO_TEXTO.INSERTA(NIDPOLIZA, nIdEndoso, CDESCENDOSO);

    -- SE REGISTRA EL USUARIO Y LA FECHA DE MODIFICACIÓN
    OC_ENDOSO_ESPECIAL.INSERTA_ENDOSO_SEGUIMIENTO(NIDPOLIZA, nIdEndoso, nIDetPol, NNUMENDREF, CUSUARIO, CTERMINAL);

    -- SE REGISTRA EL CAMBIO DEL VALOR EN EL DATO
    IF NVALORNUE IS NOT NULL THEN
       NCORRELATIVO := OC_ENDOSO_ESPECIAL.OBTENER_CORRELATIVO(NIDPOLIZA);
       OC_ENDOSO_ESPECIAL.INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA, nIdEndoso, nIDetPol, NCORRELATIVO, 'CODOBJETOIMP', NVALORANT, NVALORNUE,'DETALLE_POLIZA', 'Código de Objeto de Impuesto');
       OC_ENDOSO_ESPECIAL.INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA, nIdEndoso, nIDetPol, NCORRELATIVO, 'CODOBJETOIMP', NVALORANT, NVALORNUE,'IDPOLIZA', 'Código de Objeto de Impuesto');
    END IF;
    IF NVALORNUE2 IS NOT NULL THEN
       NCORRELATIVO := OC_ENDOSO_ESPECIAL.OBTENER_CORRELATIVO(NIDPOLIZA);
       OC_ENDOSO_ESPECIAL.INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA, nIdEndoso, nIDetPol, NCORRELATIVO, 'CODUSOCFDI', NVALORANT2, NVALORNUE2,'DETALLE_POLIZA', 'Código de Uso de CFDI');
       OC_ENDOSO_ESPECIAL.INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA, nIdEndoso, nIDetPol, NCORRELATIVO, 'CODUSOCFDI', NVALORANT2, NVALORNUE2,'IDPOLIZA', 'Código de Uso de CFDI');
    END IF;

    IF NERROR = 0 THEN
      COMMIT;
    END IF;

  EXCEPTION
    WHEN  eERROR THEN
      PERROR     := NERROR;
      PDESCERROR := NDESCERROR;

  END INSERTA_ENDOSO_ESPECIAL;

  PROCEDURE INSERTA_ENDOSO_SEGUIMIENTO(NIDPOLIZA NUMBER, nIdEndoso NUMBER, nIDetPol NUMBER, NNUMENDREF VARCHAR2,CUSUARIO VARCHAR2, CTERMINAL VARCHAR2) IS -- Este es para insertar el usuario y la fecha de la modificación
  BEGIN

  Insert into ENDOSOS_SEGUIMIENTO (IDPOLIZA,IDENDOSO,TIPOENDOSO,NUMENDREF,STSENDOSO,FECSTS,IDETPOL,USUARIO,TERMINAL,FECH_ALTA)
  values (NIDPOLIZA,nIdEndoso,'ESV',NNUMENDREF,'EMI',TRUNC(SYSDATE),nIDetPol,CUSUARIO,CTERMINAL,TRUNC(SYSDATE));

  END INSERTA_ENDOSO_SEGUIMIENTO;

  PROCEDURE INSERTA_DETALLE_ENDOSO_SV(NIDPOLIZA NUMBER, nIdEndoso NUMBER, nIDetPol NUMBER, NCORRELATIVO NUMBER,NCAMPO VARCHAR2, NVALOR_ANTERIOR VARCHAR2, NVALOR_ACTUAL VARCHAR2, NTABLA VARCHAR2, NCAMPOREF VARCHAR2) IS -- Este es para insertar el valor anterior y nuevo

  BEGIN

    Insert into DETALLE_ENDOSO_SV (IDPOLIZA,IDETPOL,CORRELATIVO,CAMPO,VALOR_ANTERIOR,VALOR_ACTUAL,TABLA,IDENDOSO,CAMPOREF,TIPO_CAMBIO)
    values (NIDPOLIZA,nIDetPol,NCORRELATIVO,NCAMPO,NVALOR_ANTERIOR,NVALOR_ACTUAL,NTABLA,nIdEndoso,NCAMPOREF,'M');

  END INSERTA_DETALLE_ENDOSO_SV;

  FUNCTION OBTENER_CORRELATIVO (nIdPoliza NUMBER )RETURN NUMBER IS -- Para obtener el consecutivo de los datos modificados durante el Endoso
  NCORRELATIVO NUMBER;
  BEGIN
     BEGIN
        SELECT NVL(MAX(CORRELATIVO),0) + 1
          INTO NCORRELATIVO
          FROM DETALLE_ENDOSO_SV
         WHERE IdPoliza = nIdPoliza;
     END;
     RETURN(NCORRELATIVO);
  END OBTENER_CORRELATIVO ;

END OC_ENDOSO_ESPECIAL;
/
CREATE OR REPLACE PUBLIC SYNONYM OC_ENDOSO_ESPECIAL FOR SICAS_OC.OC_ENDOSO_ESPECIAL;
/

GRANT EXECUTE ON SICAS_OC.OC_ENDOSO_ESPECIAL TO PUBLIC;
/
