--
-- OC_EMPRESAS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_STANDARD (Package)
--   EMPRESAS (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.oc_empresas IS

FUNCTION NOMBRE_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION MONEDA_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION IDENTIFICACION_TRIBUTARIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION TIPO_IDENTIFICACION_TRIBUTARIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION DIRECCION_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION TELEFONO_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION EMAIL_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION SITIO_WEB(nCodCia NUMBER) RETURN VARCHAR2;
FUNCTION REGIMEN_FISCAL_FECT_ELECT(nCodCia NUMBER) RETURN VARCHAR2;

END OC_EMPRESAS;
/

--
-- OC_EMPRESAS  (Package Body) 
--
--  Dependencies: 
--   OC_EMPRESAS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.oc_empresas IS

FUNCTION NOMBRE_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cNomCia   EMPRESAS.NomCia%TYPE;
BEGIN
   SELECT NomCia
     INTO cNomCia
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   RETURN(cNomCia);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      cNomCia := 'COMPAÑIA - NO EXISTE!!!';
      RETURN(cNomCia);
END NOMBRE_COMPANIA;

FUNCTION MONEDA_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cCod_Moneda     EMPRESAS.Cod_Moneda%TYPE;
BEGIN
   SELECT Cod_Moneda
     INTO cCod_Moneda
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   RETURN(cCod_Moneda);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20200,'Compañía '|| nCodCia || ' NO Existe');
END MONEDA_COMPANIA;

FUNCTION IDENTIFICACION_TRIBUTARIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cNum_Tributario     EMPRESAS.Num_Tributario%TYPE;
BEGIN
   SELECT Num_Tributario
     INTO cNum_Tributario
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   IF cNum_Tributario IS NULL THEN
      RAISE_APPLICATION_ERROR(-20200,'Compañía '|| nCodCia || ' NO Tiene Registrada su Identificación Tributaria');
   ELSE   
      RETURN(cNum_Tributario);
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20200,'Compañía '|| nCodCia || ' NO Existe');
END IDENTIFICACION_TRIBUTARIA;

FUNCTION TIPO_IDENTIFICACION_TRIBUTARIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cTipo_Id_Tributaria     EMPRESAS.Tipo_Id_Tributaria%TYPE;
BEGIN
   SELECT Tipo_Id_Tributaria
     INTO cTipo_Id_Tributaria
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   IF cTipo_Id_Tributaria IS NULL THEN
      RAISE_APPLICATION_ERROR(-20200,'Compañía '|| nCodCia || ' NO Tiene Registrada su Tipo de Identificación Tributaria');
   ELSE   
      RETURN(cTipo_Id_Tributaria);
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20200,'Compañía '|| nCodCia || ' NO Existe');
END TIPO_IDENTIFICACION_TRIBUTARIA;

FUNCTION DIRECCION_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cDirCia   EMPRESAS.DirCia%TYPE;
BEGIN
   SELECT DirCia
     INTO cDirCia
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   RETURN(cDirCia);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      cDirCia := 'DIRECCION COMPAÑIA - NO EXISTE';
      RETURN(cDirCia);
END DIRECCION_COMPANIA;

FUNCTION TELEFONO_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cTelCia   EMPRESAS.TelCia%TYPE;
BEGIN
   SELECT TelCia
     INTO cTelCia
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   RETURN(cTelCia);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      cTelCia := 'TELEFONO CIA - NO EXISTE';
      RETURN(cTelCia);
END TELEFONO_COMPANIA;

FUNCTION EMAIL_COMPANIA(nCodCia NUMBER) RETURN VARCHAR2 IS
cEmail   EMPRESAS.Email%TYPE;
BEGIN
   SELECT Email
     INTO cEmail
     FROM EMPRESAS
    WHERE CodCia = nCodCia;
   RETURN(cEmail);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      cEmail := 'EMAIL CIA - NO EXISTE';
      RETURN(cEmail);
END EMAIL_COMPANIA;

FUNCTION SITIO_WEB(nCodCia NUMBER) RETURN VARCHAR2 IS
cPaginaWeb  EMPRESAS.Pagina_Web%TYPE;
cNomCia     EMPRESAS.NomCia%TYPE;
BEGIN
   SELECT NVL(Pagina_Web,'SIN PAGINA WEB')
     INTO cPaginaWeb
     FROM EMPRESAS
    WHERE CodCia     = nCodCia;
   RETURN(cPaginaWeb);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      cNomCia := 'EMPRESA - NO EXISTE!!!';
      RETURN(cNomCia);
END SITIO_WEB;

FUNCTION REGIMEN_FISCAL_FECT_ELECT(nCodCia NUMBER) RETURN VARCHAR2 IS
cRegimenFisFactElect EMPRESAS.RegimenFisFactElect%TYPE;
BEGIN
    SELECT NVL(RegimenFisFactElect,'SINREG')
      INTO cRegimenFisFactElect
      FROM EMPRESAS
     WHERE CodCia = nCodCia;
    RETURN(cRegimenFisFactElect);
EXCEPTION 
    WHEN NO_DATA_FOUND THEN
        cRegimenFisFactElect := '000';
        RETURN(cRegimenFisFactElect);
END REGIMEN_FISCAL_FECT_ELECT;

END OC_EMPRESAS;
/
