CREATE OR REPLACE PACKAGE OC_FACT_ELECT_MOTIVO_CANCELA AS
FUNCTION DESCRIPCION(nCodCia NUMBER,cCveMotivCancFact VARCHAR2) RETURN VARCHAR2;
PROCEDURE ACTUALIZA_ESTATUS(nCodCia NUMBER,cCveMotivCancFact VARCHAR2, cStsIni VARCHAR2, cStsFin VARCHAR2);
END OC_FACT_ELECT_MOTIVO_CANCELA;
/
CREATE OR REPLACE PACKAGE BODY OC_FACT_ELECT_MOTIVO_CANCELA AS
FUNCTION DESCRIPCION(nCodCia NUMBER,cCveMotivCancFact VARCHAR2) RETURN VARCHAR2 IS
cDescMotivoCanc FACT_ELECT_MOTIVO_CANCELA.DescMotivoCanc%TYPE;
BEGIN
   BEGIN
      SELECT NVL(DescMotivoCanc,'NO EXISTE')
        INTO cDescMotivoCanc
        FROM FACT_ELECT_MOTIVO_CANCELA
       WHERE CodCia           = nCodCia
         AND CveMotivCancFact = cCveMotivCancFact;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN 
         cDescMotivoCanc := 'NO EXISTE';
   END; 
   RETURN cDescMotivoCanc;
END;
PROCEDURE ACTUALIZA_ESTATUS(nCodCia NUMBER, cCveMotivCancFact VARCHAR2, cStsIni VARCHAR2, cStsFin VARCHAR2) IS
BEGIN
   UPDATE FACT_ELECT_MOTIVO_CANCELA
      SET StsMotivCanc     = cStsFin,
          FecStsMotivCanc  = TRUNC(SYSDATE),
          CodUsuario       = USER
    WHERE CodCia           = nCodCia
      AND CveMotivCancFact = cCveMotivCancFact
      AND StsMotivCanc     = cStsIni;
END;   
END OC_FACT_ELECT_MOTIVO_CANCELA;
/
CREATE OR REPLACE PUBLIC SYNONYM OC_FACT_ELECT_MOTIVO_CANCELA FOR SICAS_OC.OC_FACT_ELECT_MOTIVO_CANCELA;
/
GRANT EXECUTE ON OC_FACT_ELECT_MOTIVO_CANCELA TO PUBLIC;