--
-- OC_FACT_ELECT_PROD_SERV  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   FACT_ELECT_PROD_SERV (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_FACT_ELECT_PROD_SERV IS

  FUNCTION DESCRIPCION_CLAVE(nCodCia NUMBER, cClaveProdServ VARCHAR2) RETURN VARCHAR2;

END OC_FACT_ELECT_PROD_SERV;
/

--
-- OC_FACT_ELECT_PROD_SERV  (Package Body) 
--
--  Dependencies: 
--   OC_FACT_ELECT_PROD_SERV (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_FACT_ELECT_PROD_SERV IS

FUNCTION DESCRIPCION_CLAVE(nCodCia NUMBER, cClaveProdServ VARCHAR2) RETURN VARCHAR2 IS
cDescClaveProdServ   FACT_ELECT_PROD_SERV.DescClaveProdServ%TYPE;
BEGIN
   BEGIN
      SELECT DescClaveProdServ
        INTO cDescClaveProdServ
        FROM FACT_ELECT_PROD_SERV
       WHERE CodCia        = nCodCia
         AND ClaveProdServ = cClaveProdServ;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescClaveProdServ := ' NO EXISTE';
   END;
   RETURN(cDescClaveProdServ);
END DESCRIPCION_CLAVE;

END OC_FACT_ELECT_PROD_SERV;
/

--
-- OC_FACT_ELECT_PROD_SERV  (Synonym) 
--
--  Dependencies: 
--   OC_FACT_ELECT_PROD_SERV (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_FACT_ELECT_PROD_SERV FOR SICAS_OC.OC_FACT_ELECT_PROD_SERV
/


GRANT EXECUTE ON SICAS_OC.OC_FACT_ELECT_PROD_SERV TO PUBLIC
/
