CREATE OR REPLACE PACKAGE OC_FACT_ELECT_PROD_SERV IS

  FUNCTION DESCRIPCION_CLAVE(nCodCia NUMBER, cClaveProdServ VARCHAR2) RETURN VARCHAR2;

END OC_FACT_ELECT_PROD_SERV;
/

CREATE OR REPLACE PACKAGE BODY OC_FACT_ELECT_PROD_SERV IS

FUNCTION DESCRIPCION_CLAVE(nCodCia NUMBER, cClaveProdServ VARCHAR2) RETURN VARCHAR2 IS
cDescClaveProdServ   FACT_ELECT_PROD_SERV.DescClaveProdServ%TYPE;
BEGIN
   BEGIN
      SELECT DescClaveProdServ
        INTO cDescClaveProdServ
        FROM FACT_ELECT_PROD_SERV
       WHERE CodCia        = nCodCia
         AND ClaveProdServ = cClaveProdServ;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescClaveProdServ := ' NO EXISTE';
   END;
   RETURN(cDescClaveProdServ);
END DESCRIPCION_CLAVE;

END OC_FACT_ELECT_PROD_SERV;
