CREATE OR REPLACE PACKAGE OC_FACTURAS_RECLAMADAS IS
--
-- CREACION     05/10/2021
-- BITACORA DE CAMBIOS 
--
PROCEDURE INSERTA_REGISTROS(nCODCIA        NUMBER,
               nCODEMPRESA      NUMBER,
               nIDSINIESTRO        NUMBER,
               nIDDETSIN        NUMBER,
               nIDPOLIZA        NUMBER,
               nCOD_ASEGURADO      NUMBER,
               nID_CONSECUTIVO      NUMBER,
               cNUM_COMPROBANTE      VARCHAR2,
               cFOLIO_FISCAL      VARCHAR2,
               dFEC_EMISION_COMPROB    DATE,
               cRFC_PROVEEDOR      VARCHAR2,
               cNOM_PROVEEDOR      VARCHAR2,
               cTP_PROCEDIMIENTO      VARCHAR2,
               nMONTO_RECLAMADO      NUMBER,
               nMONTO_AUTORIZADO      NUMBER,
               cTP_CONCEPTO_NO_CUBIERTO    VARCHAR2,
               cOBSERVACIONES      VARCHAR2) ;

--
PROCEDURE BORRA_MOVIMIENTO(nCODCIA        NUMBER,
               nCODEMPRESA      NUMBER,
               nIDSINIESTRO        NUMBER,
               nIDDETSIN        NUMBER,
               nIDPOLIZA        NUMBER,
               nCOD_ASEGURADO      NUMBER,
               nID_CONSECUTIVO      NUMBER );

END OC_FACTURAS_RECLAMADAS;

/

CREATE OR REPLACE PACKAGE BODY OC_FACTURAS_RECLAMADAS IS
--
PROCEDURE INSERTA_REGISTROS(nCODCIA        NUMBER,
               nCODEMPRESA      NUMBER,
               nIDSINIESTRO        NUMBER,
               nIDDETSIN        NUMBER,
               nIDPOLIZA        NUMBER,
               nCOD_ASEGURADO      NUMBER,
               nID_CONSECUTIVO      NUMBER,
               cNUM_COMPROBANTE      VARCHAR2,
               cFOLIO_FISCAL      VARCHAR2,
               dFEC_EMISION_COMPROB    DATE,
               cRFC_PROVEEDOR      VARCHAR2,
               cNOM_PROVEEDOR      VARCHAR2,
               cTP_PROCEDIMIENTO      VARCHAR2,
               nMONTO_RECLAMADO      NUMBER,
               nMONTO_AUTORIZADO      NUMBER,
               cTP_CONCEPTO_NO_CUBIERTO    VARCHAR2,
               cOBSERVACIONES      VARCHAR2)  IS
BEGIN

       INSERT INTO FACTURAS_RECLAMADAS (CODCIA, CODEMPRESA, IDSINIESTRO, IDDETSIN, IDPOLIZA, COD_ASEGURADO, ID_CONSECUTIVO,
                             NUM_COMPROBANTE, FOLIO_FISCAL, FEC_EMISION_COMPROB, RFC_PROVEEDOR, NOM_PROVEEDOR,
                        TP_PROCEDIMIENTO, MONTO_RECLAMADO, MONTO_AUTORIZADO, TP_CONCEPTO_NO_CUBIERTO, OBSERVACIONES)
       VALUES(nCODCIA, nCODEMPRESA, nIDSINIESTRO, nIDDETSIN, nIDPOLIZA, nCOD_ASEGURADO, nID_CONSECUTIVO, cNUM_COMPROBANTE,
       cFOLIO_FISCAL, dFEC_EMISION_COMPROB, cRFC_PROVEEDOR, cNOM_PROVEEDOR, cTP_PROCEDIMIENTO, nMONTO_RECLAMADO,
                     nMONTO_AUTORIZADO, cTP_CONCEPTO_NO_CUBIERTO, cOBSERVACIONES  );


END INSERTA_REGISTROS;
--
PROCEDURE BORRA_MOVIMIENTO(nCODCIA        NUMBER,
               nCODEMPRESA      NUMBER,
               nIDSINIESTRO        NUMBER,
               nIDDETSIN        NUMBER,
               nIDPOLIZA        NUMBER,
               nCOD_ASEGURADO      NUMBER,
               nID_CONSECUTIVO      NUMBER ) IS
--
BEGIN
  --
  DELETE FACTURAS_RECLAMADAS
    WHERE CODCIA        = nCODCIA
      AND CODEMPRESA    = nCODEMPRESA
      AND CODEMPRESA    = nCODEMPRESA
      AND IDSINIESTRO    = nIDSINIESTRO
      AND IDDETSIN    = nIDDETSIN
      AND IDPOLIZA        = nIDPOLIZA
      AND COD_ASEGURADO    = nCOD_ASEGURADO
      AND ID_CONSECUTIVO    = nID_CONSECUTIVO  ;
  --
END BORRA_MOVIMIENTO;
--
END OC_FACTURAS_RECLAMADAS;
