--
-- OC_GRUPOS_DE_USUARIOS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_STANDARD (Package)
--   USUARIOS (Table)
--   GRUPOS_DE_USUARIOS (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_GRUPOS_DE_USUARIOS IS 
  FUNCTION INDICADOR_CONSULTA(cUsuario VARCHAR2) RETURN VARCHAR2;
  FUNCTION DESCRIPCION_GRUPO(nCodCia NUMBER, cCodGrupo VARCHAR2) RETURN VARCHAR2;
END OC_GRUPOS_DE_USUARIOS;
/

--
-- OC_GRUPOS_DE_USUARIOS  (Package Body) 
--
--  Dependencies: 
--   OC_GRUPOS_DE_USUARIOS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_GRUPOS_DE_USUARIOS IS
FUNCTION INDICADOR_CONSULTA(cUsuario VARCHAR2 ) RETURN  VARCHAR2 IS
nIndConsulta   GRUPOS_DE_USUARIOS.IndConsulta%TYPE;
BEGIN
   SELECT IndConsulta
     INTO nIndConsulta
     FROM USUARIOS US, GRUPOS_DE_USUARIOS GDU
    WHERE US.CODCIA = GDU.CODCIA 
      AND US.CODGRUPO = GDU.CODGRUPO 
      AND CODUSUARIO  = cUsuario;
   RETURN(nIndConsulta);       
EXCEPTION
   WHEN NO_DATA_FOUND THEN       
      nIndConsulta := 'N';
      RETURN(nIndConsulta);
END INDICADOR_CONSULTA;

FUNCTION DESCRIPCION_GRUPO(nCodCia NUMBER, cCodGrupo VARCHAR2) RETURN VARCHAR2 IS
cDescGrupo        GRUPOS_DE_USUARIOS.DescGrupo%TYPE;
BEGIN
   BEGIN
      SELECT DescGrupo
        INTO cDescGrupo
        FROM GRUPOS_DE_USUARIOS
       WHERE CodCia     = nCodCia
         AND CodGrupo   = cCodGrupo;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescGrupo  := 'NO EXISTE';
      WHEN TOO_MANY_ROWS THEN
         RAISE_APPLICATION_ERROR(-20225,'Error en Configuración del Grupo de Usuario ' || cCodGrupo ||' - Existe en Varios Registros');
   END;
   RETURN(cDescGrupo);
END DESCRIPCION_GRUPO;

END OC_GRUPOS_DE_USUARIOS;
/

--
-- OC_GRUPOS_DE_USUARIOS  (Synonym) 
--
--  Dependencies: 
--   OC_GRUPOS_DE_USUARIOS (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM OC_GRUPOS_DE_USUARIOS FOR SICAS_OC.OC_GRUPOS_DE_USUARIOS
/


GRANT EXECUTE ON SICAS_OC.OC_GRUPOS_DE_USUARIOS TO PUBLIC
/
