CREATE OR REPLACE PACKAGE OC_LOG_CONF_FACT_ELECT IS
  PROCEDURE INSERTA(nCodCia LOG_CONF_FACT_ELECT.CODCIA%TYPE, 
                    cNombTabla LOG_CONF_FACT_ELECT.NOMBRETABLA%TYPE,  
					cNombCampo LOG_CONF_FACT_ELECT.NOMBRECAMPO%TYPE, 
					cValorOld LOG_CONF_FACT_ELECT.VALORCAMPOANT%TYPE, 
					cValorNew LOG_CONF_FACT_ELECT.VALORCAMPOUPD%TYPE, 
					cTipoAccion LOG_CONF_FACT_ELECT.ACCION%TYPE);
END;
/

CREATE OR REPLACE PACKAGE BODY OC_LOG_CONF_FACT_ELECT IS
PROCEDURE INSERTA(nCodCia LOG_CONF_FACT_ELECT.CODCIA%TYPE, 
                  cNombTabla LOG_CONF_FACT_ELECT.NOMBRETABLA%TYPE,  
					cNombCampo LOG_CONF_FACT_ELECT.NOMBRECAMPO%TYPE, 
					cValorOld LOG_CONF_FACT_ELECT.VALORCAMPOANT%TYPE, 
					cValorNew LOG_CONF_FACT_ELECT.VALORCAMPOUPD%TYPE, 
					cTipoAccion LOG_CONF_FACT_ELECT.ACCION%TYPE) IS
nMaxTransaccion     LOG_CONF_FACT_ELECT.IDCTRLOG%TYPE;
cUsuario            LOG_CONF_FACT_ELECT.USUARIOMOD%TYPE;


  BEGIN

		SELECT SQ_LOGCONFFACT.NEXTVAL
		   INTO nMaxTransaccion
		   FROM DUAL;
		   
		SELECT USER
		   INTO cUsuario
		   FROM DUAL;
		     
		   
		  
		    INSERT INTO LOG_CONF_FACT_ELECT
            (IDCTRLOG, CodCia, NOMBRETABLA, NOMBRECAMPO, VALORCAMPOANT, VALORCAMPOUPD, ACCION, USUARIOMOD, FECMODIFICACION)
            VALUES(nMaxtransaccion, nCodCia, cNombTabla, cNombCampo, cValorOld, cValorNew, cTipoAccion, cUsuario, SYSDATE);
		   
		   

  END INSERTA;

END OC_LOG_CONF_FACT_ELECT
/

CREATE OR REPLACE PUBLIC SYNONYM OC_LOG_CONF_FACT_ELECT FOR SICAS_OC.OC_LOG_CONF_FACT_ELECT
/

GRANT EXECUTE ON SICAS_OC.OC_LOG_CONF_FACT_ELECT TO PUBLIC
/
