CREATE OR REPLACE PACKAGE OC_PLD_LISTAS_CNSF IS
--
-- BITACORA DE CAMBIO
-- CREACION DE PROGRAMA            JICO 20221201  
--  07(03/2023 
--

FUNCTION ES_LISTA_CNSF(cTipoDocIdentEmp VARCHAR2, cNumDocIdentEmp VARCHAR2) RETURN VARCHAR2;

END OC_PLD_LISTAS_CNSF;
/
CREATE OR REPLACE PACKAGE BODY OC_PLD_LISTAS_CNSF IS

FUNCTION ES_LISTA_CNSF(cTipoDocIdentEmp VARCHAR2, cNumDocIdentEmp VARCHAR2) RETURN VARCHAR2 IS
cESLISTACNSF   VARCHAR2(1);
W_NOMBRE         ADMON_RIESGO.NOMBRE%TYPE;
BEGIN
  --
  W_NOMBRE := TRIM(OC_PERSONA_NATURAL_JURIDICA.NOMBRE_COMPLETO(cTipoDocIdentEmp, cNumDocIdentEmp));
  --
  BEGIN
    SELECT 'S'
      INTO cESLISTACNSF
      FROM PLD_LISTAS_CNSF L 
     WHERE ((L.NOMBRE_1 = W_NOMBRE)
        OR  (L.NOMBRE_2 = W_NOMBRE)
        OR  (L.NOMBRE_3 = W_NOMBRE)
        OR  (L.NOMBRE_4 = W_NOMBRE)
        OR  (L.NOMBRE_5 = W_NOMBRE)
        OR  (L.ALIAS_1  = W_NOMBRE)
        OR  (L.ALIAS_2  = W_NOMBRE)
        OR  (L.ALIAS_3  = W_NOMBRE)
        OR  (L.ALIAS_4  = W_NOMBRE)
        OR  (L.ALIAS_5  = W_NOMBRE)
        OR  (L.ALIAS_6  = W_NOMBRE)
        OR  (L.ALIAS_7  = W_NOMBRE)
        OR  (L.ALIAS_8  = W_NOMBRE)
        OR  (L.ALIAS_9  = W_NOMBRE)
        OR  (L.ALIAS_10 = W_NOMBRE)
           ) 
        --
        AND L.TP_MOVIMIENTO != 'BAJA';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
         cESLISTACNSF := 'N';
    WHEN TOO_MANY_ROWS THEN
         cESLISTACNSF := 'S';
  END;
  --
  RETURN(cESLISTACNSF);
  --
END ES_LISTA_CNSF;

END OC_PLD_LISTAS_CNSF;
/

CREATE OR REPLACE PUBLIC SYNONYM OC_PLD_LISTAS_CNSF FOR SICAS_OC.OC_PLD_LISTAS_CNSF
;

GRANT EXECUTE ON SICAS_OC.OC_PLD_LISTAS_CNSF TO PUBLIC
;

/
