CREATE OR REPLACE PACKAGE OC_PAIS IS
--
-- MODIFICACIONES  
-- 07/03/2023 Se agrega funcion BUSCA_DESC_CNSF Y ES_PAIS_ALTO_RIESGO JICO                                                                          |
-- 
FUNCTION NOMBRE_PAIS(cCodPais VARCHAR2) RETURN VARCHAR2;
  
FUNCTION CODIGO_ALTERNATIVO(cCodPais VARCHAR2) RETURN VARCHAR2;

FUNCTION BUSCA_CLAVE_CNSF(cCodPais VARCHAR2) RETURN VARCHAR2;

FUNCTION ES_PAIS_ALTO_RIESGO(CCODPAIS VARCHAR2) RETURN VARCHAR2;

END OC_PAIS;
 
 
 
 
 
 
/
CREATE OR REPLACE PACKAGE BODY OC_PAIS IS

FUNCTION NOMBRE_PAIS(cCodPais VARCHAR2) RETURN VARCHAR2 IS
cDescPais    PAIS.DescPais%TYPE;
BEGIN
   BEGIN
      SELECT DescPais
        INTO cDescPais
        FROM PAIS
       WHERE CodPais   = cCodPais;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cDescPais  := 'PAIS NO EXISTE';
   END;
   RETURN(cDescPais);
END NOMBRE_PAIS;

FUNCTION CODIGO_ALTERNATIVO(cCodPais VARCHAR2) RETURN VARCHAR2 IS
cCodPaisAlterno    PAIS.CodPaisAlterno%TYPE;
BEGIN
   BEGIN
      SELECT CodPaisAlterno
        INTO cCodPaisAlterno
        FROM PAIS
       WHERE CodPais   = cCodPais;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cCodPaisAlterno  := NULL;
   END;
   RETURN(cCodPaisAlterno);
END CODIGO_ALTERNATIVO;

FUNCTION BUSCA_CLAVE_CNSF(cCodPais VARCHAR2) RETURN VARCHAR2 IS
cCLAVE_CNSF    PAIS.CVE_CNSF%TYPE;
BEGIN
   BEGIN
      SELECT A.CVE_CNSF
        INTO cCLAVE_CNSF
        FROM PAIS A
       WHERE CodPais   = cCodPais;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         cCLAVE_CNSF := NULL;
   END;
   RETURN(cCLAVE_CNSF);
END BUSCA_CLAVE_CNSF;


FUNCTION ES_PAIS_ALTO_RIESGO(CCODPAIS VARCHAR2) RETURN VARCHAR2 IS
CES_PAIS_ALTORIESGO     VARCHAR2(1);
BEGIN
   BEGIN
      SELECT 'S'
        INTO CES_PAIS_ALTORIESGO
        FROM PAIS P
       WHERE P.CODPAIS    = CCODPAIS
         AND P.TIPORIESGO = 'ALTO';
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         CES_PAIS_ALTORIESGO := 'N';
      WHEN TOO_MANY_ROWS THEN
         CES_PAIS_ALTORIESGO := 'S';
   END;
   
   RETURN(CES_PAIS_ALTORIESGO);
END ES_PAIS_ALTO_RIESGO;

END OC_PAIS;
/
