--
-- OC_PAGO_DETALLE  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   PAGO_DETALLE (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.OC_PAGO_DETALLE AS
    FUNCTION MTO_PAGO_CONCEPTO_FACTURA(nIdFactura NUMBER,cCodConcepto VARCHAR2) RETURN NUMBER;
    FUNCTION MTO_PAGO_TOTAL_FACTURA(nIdFactura NUMBER) RETURN NUMBER;
    FUNCTION MTO_PAGO_CONCEPTO_RECIBO(nIdRecibo NUMBER,cCodConcepto VARCHAR2) RETURN NUMBER;
    FUNCTION MTO_PAGO_TOTAL_RECIBO(nIdRecibo NUMBER) RETURN NUMBER;
END OC_PAGO_DETALLE;
/

--
-- OC_PAGO_DETALLE  (Package Body) 
--
--  Dependencies: 
--   OC_PAGO_DETALLE (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.OC_PAGO_DETALLE AS
    FUNCTION MTO_PAGO_CONCEPTO_FACTURA(nIdFactura NUMBER,cCodConcepto VARCHAR2) RETURN NUMBER IS
        nMonto PAGO_DETALLE.Monto%TYPE;
    BEGIN
        SELECT SUM(Monto)
          INTO nMonto
          FROM PAGO_DETALLE
         WHERE IdFactura = nIdFactura
           AND CodCpto   = cCodConcepto;
        RETURN nMonto;
    END MTO_PAGO_CONCEPTO_FACTURA;
    FUNCTION MTO_PAGO_TOTAL_FACTURA(nIdFactura NUMBER) RETURN NUMBER IS
        nMonto PAGO_DETALLE.Monto%TYPE;
    BEGIN
        SELECT SUM(Monto)
          INTO nMonto
          FROM PAGO_DETALLE
         WHERE IdFactura = nIdFactura;
        RETURN nMonto;
    END MTO_PAGO_TOTAL_FACTURA;
    FUNCTION MTO_PAGO_CONCEPTO_RECIBO(nIdRecibo NUMBER,cCodConcepto VARCHAR2) RETURN NUMBER IS
        nMonto PAGO_DETALLE.Monto%TYPE;
    BEGIN
        SELECT SUM(Monto)
          INTO nMonto
          FROM PAGO_DETALLE
         WHERE IdRecibo = nIdRecibo
           AND CodCpto  = cCodConcepto;
        RETURN nMonto;
    END MTO_PAGO_CONCEPTO_RECIBO;
    FUNCTION MTO_PAGO_TOTAL_RECIBO(nIdRecibo NUMBER) RETURN NUMBER IS
        nMonto PAGO_DETALLE.Monto%TYPE;
    BEGIN
        SELECT SUM(Monto)
          INTO nMonto
          FROM PAGO_DETALLE
         WHERE IdRecibo = nIdRecibo;
        RETURN nMonto;
    END MTO_PAGO_TOTAL_RECIBO;
END OC_PAGO_DETALLE;
/
