CREATE OR REPLACE PACKAGE OC_PLD_REP_OPERACIONES IS
--
-- BITACORA DE CAMBIO
-- ALTA   JICO 20221206


FUNCTION ID_OPERACIONES RETURN NUMBER;

FUNCTION DESCRIPCION_MONEDA(cCodMoneda VARCHAR2) RETURN VARCHAR2;

END OC_PLD_REP_OPERACIONES;
/
CREATE OR REPLACE PACKAGE BODY OC_PLD_REP_OPERACIONES IS
--
-- BITACORA DE CAMBIO
-- ALTA   JICO 20221114


FUNCTION ID_OPERACIONES RETURN NUMBER IS
NIDOPERACION PLD_REP_OPERACIONES.IDOPERACION%TYPE;
BEGIN
  BEGIN
    SELECT SQ_PLD_OPERACIONES.NEXTVAL
      INTO NIDOPERACION
      FROM DUAL;
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
         RAISE_APPLICATION_ERROR(-20225,'YA Existe la Secuencia  para Operaciones ');
  END;
  --
  RETURN(NIDOPERACION);
  --
END ID_OPERACIONES;

FUNCTION DESCRIPCION_MONEDA(cCodMoneda VARCHAR2) RETURN VARCHAR2 IS
cDesc_Moneda   MONEDA.Desc_Moneda%TYPE;
BEGIN
   BEGIN
      SELECT Desc_Moneda
        INTO cDesc_Moneda
        FROM MONEDA
       WHERE Cod_Moneda = cCodMoneda;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
           cDesc_Moneda := 'Invalida';
   END;
   RETURN(cDesc_Moneda);
END DESCRIPCION_MONEDA;

END OC_PLD_REP_OPERACIONES;
/
