CREATE OR REPLACE PACKAGE OC_REP_LEGAL_PNJ IS
--
-- BITACORA DE CAMBIO
-- ALTA   JICO 20221114

FUNCTION ES_REPRESENTANTE_LEGAL(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2) RETURN VARCHAR2;

FUNCTION ES_REPRESENTANTE_VIGENTE(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2, dFECHA IN DATE) RETURN VARCHAR2;

FUNCTION PARTICIPA_EN_POLIZAS(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2) RETURN VARCHAR2;

END OC_REP_LEGAL_PNJ;
/
CREATE OR REPLACE PACKAGE BODY OC_REP_LEGAL_PNJ IS
--
-- BITACORA DE CAMBIO
-- ALTA   JICO 20221114

FUNCTION ES_REPRESENTANTE_LEGAL(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2) RETURN VARCHAR2 IS
cEXISTE VARCHAR2(1);
BEGIN
  BEGIN
    SELECT 'S'
      INTO cEXISTE
      FROM REP_LEGAL_PNJ R
     WHERE R.TIPO_DOC_REP_LEGAL = cTIPO_DOC_REP_LEGAL
       AND R.NUM_DOC_REP_LEGAL  = cNUM_DOC_REP_LEGAL;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
         cEXISTE := 'N';
    WHEN TOO_MANY_ROWS THEN
         cEXISTE := 'S';
  END;
  --
  RETURN cEXISTE;
  --
END ES_REPRESENTANTE_LEGAL;

FUNCTION ES_REPRESENTANTE_VIGENTE(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2, dFECHA IN DATE) RETURN VARCHAR2 IS
cVIGENTE VARCHAR2(1);
BEGIN
  BEGIN
    SELECT 'S'
      INTO cVIGENTE
      FROM REP_LEGAL_PNJ R
     WHERE R.TIPO_DOC_REP_LEGAL = cTIPO_DOC_REP_LEGAL
       AND R.NUM_DOC_REP_LEGAL  = cNUM_DOC_REP_LEGAL
       AND R.FECHAINICIO        <= dFECHA
       AND R.FECHAFINAL         >= dFECHA
       AND R.ESTADO             = 'ACT' ;
  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
         cVIGENTE := 'N';
    WHEN TOO_MANY_ROWS THEN
         cVIGENTE := 'S';
  END;
  --
  RETURN cVIGENTE;
  --
END ES_REPRESENTANTE_VIGENTE;

FUNCTION PARTICIPA_EN_POLIZAS(cTIPO_DOC_REP_LEGAL IN VARCHAR2, cNUM_DOC_REP_LEGAL IN VARCHAR2) RETURN VARCHAR2 IS
cTIENE_POLIZAS VARCHAR2(1);
--
W_CLIENTE                NUMBER(10) := 0;
W_ASEGURADO_SUBGRUPO     NUMBER(10) := 0;
W_ASEGURADO_CERTIFICADO  NUMBER(10) := 0;
W_TIENE_POLIZAS          NUMBER(10) := 0;
--
BEGIN
  --
  SELECT COUNT(*)
    INTO W_CLIENTE
    FROM CLIENTES C,
         POLIZAS P
   WHERE C.TIPO_DOC_IDENTIFICACION = cTIPO_DOC_REP_LEGAL
     AND C.NUM_DOC_IDENTIFICACION  = cNUM_DOC_REP_LEGAL
     --
     AND P.CODCLIENTE = C.CODCLIENTE;
  --
  SELECT COUNT(*)
    INTO W_ASEGURADO_SUBGRUPO
    FROM ASEGURADO A,
         DETALLE_POLIZA DP
   WHERE A.TIPO_DOC_IDENTIFICACION = cTIPO_DOC_REP_LEGAL
     AND A.NUM_DOC_IDENTIFICACION  = cNUM_DOC_REP_LEGAL
     --
     AND DP.COD_ASEGURADO = A.COD_ASEGURADO;
  --
  SELECT COUNT(*)
    INTO W_ASEGURADO_CERTIFICADO  
    FROM ASEGURADO A,
         ASEGURADO_CERTIFICADO AC
   WHERE A.TIPO_DOC_IDENTIFICACION = cTIPO_DOC_REP_LEGAL
     AND A.NUM_DOC_IDENTIFICACION  = cNUM_DOC_REP_LEGAL
     --
     AND AC.COD_ASEGURADO = A.COD_ASEGURADO;
  -- 
  W_TIENE_POLIZAS := W_CLIENTE + W_ASEGURADO_SUBGRUPO + W_ASEGURADO_CERTIFICADO; 
  --
  IF W_TIENE_POLIZAS = 0 THEN
     cTIENE_POLIZAS := 'N';
  ELSE
     cTIENE_POLIZAS := 'S';
  END IF;
  --
  RETURN cTIENE_POLIZAS;
  --
END PARTICIPA_EN_POLIZAS;

END OC_REP_LEGAL_PNJ;
/
