CREATE OR REPLACE PACKAGE TH_BIT_DESBLOQUEOS_SAT IS

PROCEDURE INSERTA(P_CODCIA		NUMBER 		,
		  P_ID_RFC		VARCHAR2	,		
		  P_NOM_CONTRIB		VARCHAR2	,		
		  P_SIT_CONTRIB		VARCHAR2	,		
		  P_STATUS_REGISTRO	VARCHAR2	,	
		  P_USUARIO_AUTORIZA	VARCHAR2	,
		  P_FECHA_AUTORIZACION	DATE		,
		  P_OBSERVACIONES	VARCHAR2
                  );

END TH_BIT_DESBLOQUEOS_SAT;
/

CREATE OR REPLACE PACKAGE BODY TH_BIT_DESBLOQUEOS_SAT  IS
--

PROCEDURE INSERTA(P_CODCIA		NUMBER	,
		  P_ID_RFC		VARCHAR2 ,		
		  P_NOM_CONTRIB		VARCHAR2 ,		
		  P_SIT_CONTRIB		VARCHAR2 ,		
		  P_STATUS_REGISTRO 	VARCHAR2 ,	
		  P_USUARIO_AUTORIZA 	VARCHAR2 ,
		  P_FECHA_AUTORIZACION	DATE ,
		  P_OBSERVACIONES	VARCHAR2
                 ) IS
--
BEGIN
  --
  --INSERTA BIT_AUTORIZA_DESBLOQUEOS_SAT 
  --
  INSERT INTO BIT_AUTORIZA_DESBLOQUEOS_SAT 
    (CODCIA ,
     ID_RFC ,		
     NOM_CONTRIB ,		
     SIT_CONTRIB ,		
     STATUS_REGISTRO ,	
     USUARIO_AUTORIZA ,
     FECHA_AUTORIZACION ,
     OBSERVACIONES)
    VALUES
    	(P_CODCIA ,
         P_ID_RFC ,		
	 P_NOM_CONTRIB ,		
	 P_SIT_CONTRIB ,		
	 P_STATUS_REGISTRO ,	
	 P_USUARIO_AUTORIZA ,
	 P_FECHA_AUTORIZACION ,
	 P_OBSERVACIONES);
  --
     COMMIT;

END INSERTA;
--

END TH_BIT_DESBLOQUEOS_SAT;
