--
-- TH_CLAUSULAS  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_OUTPUT (Synonym)
--   POLIZAS (Table)
--   CLAUSULAS_POLIZA (Table)
--   EXTRAE_CLAUSULA_POL (Function)
--
CREATE OR REPLACE PACKAGE SICAS_OC.TH_CLAUSULAS IS

FUNCTION COPIA_CLAUSULAS(P_IDPOLIZA_ORI  IN  NUMBER,
                         P_IDPOLIZA_DEST IN  NUMBER,
                         MENSAJE         OUT VARCHAR2) RETURN NUMBER;

END TH_CLAUSULAS;
/

--
-- TH_CLAUSULAS  (Package Body) 
--
--  Dependencies: 
--   TH_CLAUSULAS (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.TH_CLAUSULAS IS
--
-- CREADO 27/10/2016
-- ACTUALIZACIONES 
-- 20161208  SE AGREGA EL BORRADO ANTES DE LA INSERCION    BORRA JICO
W_IDPOLIZA_ORI    POLIZAS.IDPOLIZA%TYPE;  
W_IDPOLIZA_DEST   POLIZAS.IDPOLIZA%TYPE;
W_FECINIVIG       POLIZAS.FECINIVIG%TYPE;
W_FECFINVIG       POLIZAS.FECFINVIG%TYPE;
W_CODCIA          NUMBER;
--
MENSAJE                    VARCHAR2(2000);
--
CURSOR CLAUSULA IS
  SELECT CODCIA,
         IDPOLIZA,
         COD_CLAUSULA,
         TIPO_CLAUSULA,
         SUBSTR(EXTRAE_CLAUSULA_POL(ROWID),1,3998) TEXTO,
         INICIO_VIGENCIA,
         FIN_VIGENCIA,
         ESTADO
    FROM CLAUSULAS_POLIZA CP
   WHERE CP.CODCIA   = W_CODCIA
     AND CP.IDPOLIZA = W_IDPOLIZA_ORI
  ;
--
--
--
FUNCTION COPIA_CLAUSULAS(P_IDPOLIZA_ORI  IN  NUMBER,
                         P_IDPOLIZA_DEST IN  NUMBER,
                         MENSAJE  OUT VARCHAR2) RETURN NUMBER IS
--
BEGIN
  --
  W_CODCIA        := 1;
  W_IDPOLIZA_ORI  := P_IDPOLIZA_ORI;
  W_IDPOLIZA_DEST := P_IDPOLIZA_DEST;
  --
  DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS'));
  --
  BEGIN
    SELECT P.FECINIVIG,
           P.FECFINVIG
      INTO W_FECINIVIG,
           W_FECFINVIG
      FROM POLIZAS P
     WHERE P.IDPOLIZA = W_IDPOLIZA_ORI;
  EXCEPTION
    WHEN OTHERS THEN
         NULL;
  END;
  --
  DELETE CLAUSULAS_POLIZA A           --BORRA
  WHERE A.CODCIA   = W_CODCIA         --BORRA
    AND A.IDPOLIZA = W_IDPOLIZA_DEST  --BORRA
  ;
  --
  FOR C IN CLAUSULA LOOP 
      --
      INSERT INTO CLAUSULAS_POLIZA 
       (CODCIA,
        IDPOLIZA,
        COD_CLAUSULA,
        TIPO_CLAUSULA,
        TEXTO,
        INICIO_VIGENCIA,
        FIN_VIGENCIA,
        ESTADO
       )
      VALUES
       (C.CODCIA,
        W_IDPOLIZA_DEST,
        C.COD_CLAUSULA,
        C.TIPO_CLAUSULA,
        C.TEXTO,
        W_FECINIVIG,
        W_FECFINVIG,
        'EMI'
       );
      --
  END LOOP;
  --
  RETURN W_IDPOLIZA_DEST;
  --
EXCEPTION
 WHEN OTHERS THEN
      MENSAJE := 'ERROR AL COPIAR LA CLAUSULA : '||W_IDPOLIZA_ORI;    
      RETURN 0;  
END;

END TH_CLAUSULAS;
/

--
-- TH_CLAUSULAS  (Synonym) 
--
--  Dependencies: 
--   TH_CLAUSULAS (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM TH_CLAUSULAS FOR SICAS_OC.TH_CLAUSULAS
/


GRANT EXECUTE ON SICAS_OC.TH_CLAUSULAS TO PUBLIC
/
