--
-- TH_POR_AUTORIZAR_SAT  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   POR_AUTORIZAR_SAT (Table)
--
CREATE OR REPLACE PACKAGE SICAS_OC.TH_POR_AUTORIZAR_SAT IS

PROCEDURE INSERTA(P_CODCIA		NUMBER 		,
		  P_ID_RFC		VARCHAR2	,		
		  P_NOM_CONTRIB		VARCHAR2	,		
		  P_SIT_CONTRIB		VARCHAR2	,		
		  P_STATUS_REGISTRO	VARCHAR2	,	
		  P_USUARIO_PROCESA	VARCHAR2	,
		  P_FECHA_AUTORIZACION	DATE		,
		  P_OBSERVACIONES	VARCHAR2
                  );

END TH_POR_AUTORIZAR_SAT;
/

--
-- TH_POR_AUTORIZAR_SAT  (Package Body) 
--
--  Dependencies: 
--   TH_POR_AUTORIZAR_SAT (Package)
--
CREATE OR REPLACE PACKAGE BODY SICAS_OC.TH_POR_AUTORIZAR_SAT  IS
--

PROCEDURE INSERTA(P_CODCIA		NUMBER	,
		  P_ID_RFC		VARCHAR2 ,		
		  P_NOM_CONTRIB		VARCHAR2 ,		
		  P_SIT_CONTRIB		VARCHAR2 ,		
		  P_STATUS_REGISTRO 	VARCHAR2 ,	
		  P_USUARIO_PROCESA 	VARCHAR2 ,
		  P_FECHA_AUTORIZACION	DATE ,
		  P_OBSERVACIONES	VARCHAR2
                 ) IS
--
BEGIN
  --
  --INSERTA POR_AUTORIZAR_SAT  
  --
  INSERT INTO POR_AUTORIZAR_SAT 
    (CODCIA ,
     ID_RFC ,		
     NOM_CONTRIB ,		
     SIT_CONTRIB ,		
     STATUS_REGISTRO ,	
     USUARIO_PROCESA ,
     FECHA_AUTORIZACION ,
     OBSERVACIONES)
    VALUES
    	(P_CODCIA ,
         P_ID_RFC ,		
	 P_NOM_CONTRIB ,		
	 P_SIT_CONTRIB ,		
	 P_STATUS_REGISTRO ,	
	 P_USUARIO_PROCESA ,
	 P_FECHA_AUTORIZACION ,
	 P_OBSERVACIONES);
  --
     COMMIT;

END INSERTA;
--

END TH_POR_AUTORIZAR_SAT;
/

--
-- TH_POR_AUTORIZAR_SAT  (Synonym) 
--
--  Dependencies: 
--   TH_POR_AUTORIZAR_SAT (Package)
--
CREATE OR REPLACE PUBLIC SYNONYM TH_POR_AUTORIZAR_SAT FOR SICAS_OC.TH_POR_AUTORIZAR_SAT
/


GRANT EXECUTE ON SICAS_OC.TH_POR_AUTORIZAR_SAT TO PUBLIC
/
