DROP TABLE THONAPI.ASEGURADOS_SIGO_TMP;

CREATE TABLE THONAPI.ASEGURADOS_SIGO_TMP
   ( CODCIA           NUMBER(14)  NOT NULL,
     CODEMPRESA       NUMBER(14)  NOT NULL,
     IDPOLIZA         NUMBER(14)  NOT NULL,
     IDETPOL          NUMBER(14)  NOT NULL,
     IDASEG           NUMBER(14)  NOT NULL,
     NOMBRE           VARCHAR2(200),
     APELLIDOPATERNO  VARCHAR2(200),
     APELLIDOMATERNO  VARCHAR2(200),
     GENERO           VARCHAR2(1),
     FECNACIMIENTO    DATE,
     SALARIOMENSUAL   NUMBER(28,2),
     VECESSALARIO     NUMBER(10),
     SUMASEGFIJA      NUMBER(28,2),
     RFC              VARCHAR2(20)
   )
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE THONAPI.ASEGURADOS_SIGO_TMP  IS 'Documentos JSON por Cotización';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.CODCIA IS 'Código de la Compañía';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.CODEMPRESA IS 'Código de la Empresa';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.IDPOLIZA IS 'Identificador único de la póliza';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.IDETPOL IS 'Identificador único del detalle/certificado de la póliza';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.IDASEG IS 'Identificador/Secuencia única del Asegurado';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.NOMBRE IS 'Nombre del Asegurado';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.APELLIDOPATERNO IS 'Apellido Paterno del Asegurado';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.APELLIDOMATERNO IS 'Apellido Materno del Asegurado';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.GENERO IS 'Genero/Sexo del Asegurado';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.FECNACIMIENTO IS 'Fecha de Nacimiento';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.SALARIOMENSUAL IS 'Salario Mensual';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.VECESSALARIO IS 'Veces Salario';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.SUMASEGFIJA IS 'Suma Asegurada Fija';
COMMENT ON COLUMN THONAPI.ASEGURADOS_SIGO_TMP.RFC IS 'Registro Federal de Contribuyentes';

--Crea la llave Primaria
CREATE UNIQUE INDEX THONAPI.ASEGURADOS_SIGO_TMP_PK ON THONAPI.ASEGURADOS_SIGO_TMP
( CODCIA, CODEMPRESA, IDPOLIZA, IDETPOL, IDASEG )
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

-- Crea el Sinónimo
CREATE OR REPLACE PUBLIC SYNONYM ASEGURADOS_SIGO_TMP FOR THONAPI.ASEGURADOS_SIGO_TMP;
/

-- 
ALTER TABLE THONAPI.ASEGURADOS_SIGO_TMP ADD (
  CONSTRAINT ASEGURADOS_SIGO_TMP_PK
  PRIMARY KEY
  ( CODCIA, CODEMPRESA, IDPOLIZA, IDETPOL, IDASEG )
  USING INDEX THONAPI.ASEGURADOS_SIGO_TMP_PK
  ENABLE VALIDATE)
/

-- Genera los permisos
GRANT DELETE, INSERT, SELECT, UPDATE ON THONAPI.ASEGURADOS_SIGO_TMP TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON THONAPI.ASEGURADOS_SIGO_TMP TO ROL_MODIFICA_SICAS;
GRANT SELECT ON THONAPI.ASEGURADOS_SIGO_TMP TO ROL_CONSULTA_SICAS;
