CREATE INDEX ADMON_RIESGO_SIN_H_IDX_1 ON ADMON_RIESGO_SINIESTROS_H
   (TIPO_DOC_IDENTIFICACION,NUM_DOC_IDENTIFICACION) ;
CREATE INDEX ADMON_RIESGO_SIN_H_IDX_2 ON ADMON_RIESGO_SINIESTROS_H
   (IDPOLIZA) ;
/