CREATE INDEX SICAS_OC.ADMON_RIESGO_SINIESTROS_IDX_1 ON SICAS_OC.ADMON_RIESGO_SINIESTROS
   (TIPO_DOC_IDENTIFICACION,NUM_DOC_IDENTIFICACION) ;
CREATE INDEX SICAS_OC.ADMON_RIESGO_SINIESTROS_IDX_2 ON SICAS_OC.ADMON_RIESGO_SINIESTROS
   (IDPOLIZA) ;
/