CREATE INDEX SICAS_OC.ASEGURADO_CERTIFICADO_IDX_2 ON SICAS_OC.ASEGURADO_CERTIFICADO 
   (IDPOLIZA) 
COMPRESS;
/
CREATE INDEX SICAS_OC.ASEGURADO_CERTIFICADO_IDX_3 ON SICAS_OC.ASEGURADO_CERTIFICADO
   (IDPOLIZA, IDETPOL) 
COMPRESS;
/