
  CREATE UNIQUE INDEX "SICAS_OC"."COMISION_TIPSEG_LARPLA_PK" ON "SICAS_OC"."COMISION_TIPSEG_LARPLA" ("CODCIA", "CODEMPRESA", "IDTIPOSEG", "ID_AÑO", "ST_COMISION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
