
  CREATE UNIQUE INDEX "SICAS_OC"."COTIZADOR_COBERT_WEB_PK" ON "SICAS_OC"."COTIZADOR_COBERT_WEB" ("CODCIA", "CODEMPRESA", "CODCOTIZADOR", "IDTIPOSEG", "PLANCOB", "CODGPOCOBERTWEB", "CODCOBERTWEB", "IDCOTIZACION", "IDETCOTIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
