CREATE INDEX SICAS_OC.DETALLE_POLIZA_IDX_2 ON SICAS_OC.DETALLE_POLIZA 
   (IDETPOL, IDPOLIZA)
COMPRESS;
/
CREATE INDEX SICAS_OC.DETALLE_POLIZA_IDX_3 ON SICAS_OC.DETALLE_POLIZA
   (FECFINVIG) 
COMPRESS;
/