CREATE INDEX SICAS_OC.DETALLE_TRANSACCION_IDX_3 ON SICAS_OC.DETALLE_TRANSACCION
(CODSUBPROCESO, TO_NUMBER(VALOR1))
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
