
  CREATE INDEX "SICAS_OC"."IDX_PNJ_NOMBRE_APELLIDOS" ON "SICAS_OC"."PERSONA_NATURAL_JURIDICA" ("NOMBRE", "APELLIDO_PATERNO", "APELLIDO_MATERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
