CREATE INDEX SICAS_OC.FAI_CONCENTRADORA_FONDO_IDX_1 ON SICAS_OC.FAI_CONCENTRADORA_FONDO 
   (IDFACTURA) 
COMPRESS;
/
CREATE INDEX SICAS_OC.FAI_CONCENTRADORA_FONDO_IDX_2 ON SICAS_OC.FAI_CONCENTRADORA_FONDO
   (IDPOLIZA) 
COMPRESS;
/
CREATE INDEX SICAS_OC.FAI_CONCENTRADORA_FONDO_IDX_3 ON SICAS_OC.FAI_CONCENTRADORA_FONDO 
   (IDTRANSACCIONANU) 
COMPRESS;
/
CREATE INDEX SICAS_OC.FAI_CONCENTRADORA_FONDO_IDX_4 ON SICAS_OC.FAI_CONCENTRADORA_FONDO 
   (IDTRANSACCION) 
COMPRESS;
/