
  CREATE INDEX "SICAS_OC"."IN_DX1_INFO_SINCOM" ON "SICAS_OC"."INFO_SINCOM" ("ID_CODCIA", "ID_POLIZA", "ID_CREDITO", "ID_TRABAJADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
