CREATE INDEX SICAS_OC.IX_PLD_EMPLEADO ON
    SICAS_OC.EMPLEADOS_FUNCIONARIOS(NUMDOCIDENTEMP,CODCIA,TIPODOCIDENTEMP,TO_NUMBER(CODEMPLEADOFUNC));
    
CREATE INDEX SICAS_OC.IX_PLD_ASEG ON
    SICAS_OC.ASEGURADO(NUM_DOC_IDENTIFICACION,TIPO_DOC_IDENTIFICACION,COD_ASEGURADO);
    
CREATE INDEX SICAS_OC.IX_PLD_BENEF ON
    SICAS_OC.BENEFICIARIO(COD_ASEGURADO);
    
CREATE INDEX SICAS_OC.IX_PLD_PNJ ON
    SICAS_OC.PERSONA_NATURAL_JURIDICA(NVL(NUM_TRIBUTARIO,NUM_DOC_IDENTIFICACION),TIPO_DOC_IDENTIFICACION);
    
CREATE INDEX SICAS_OC.IX_PLD_BENEFSIN ON
    SICAS_OC.BENEF_SIN(NUM_DOC_TRIBUTARIO,TIPO_ID_TRIBUTARIO,CODCIA,CODEMPRESA,BENEF);
    
CREATE INDEX SICAS_OC.IX_PLD_PROVEEDOR ON
    SICAS_OC.PROVEEDORES(NUMDOCIDENTPROV,CODCIA,TIPODOCIDENTPROV,CODPROVEEDOR);
    