CREATE INDEX SICAS_OC.IX_SESASOPTIM1 ON
    SICAS_OC.PLAN_COBERTURAS(CODTIPOPLAN,CODEMPRESA,CODCIA)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM14 ON
    SICAS_OC.PLAN_COBERTURAS(IDTIPOSEG,CODTIPOPLAN,CODEMPRESA,CODCIA)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_OPTSESAS ON
    SICAS_OC.PLAN_COBERTURAS(IDTIPOSEG,CODTIPOPLAN,CODCIA)
TABLESPACE IDX_SICASOC;

/******************************************************************************/

CREATE INDEX SICAS_OC.IX_SESASOPTIM6 ON
    SICAS_OC.COMISIONES(IDPOLIZA,IDFACTURA,IDCOMISION)
TABLESPACE IDX_SICASOC;


CREATE INDEX SICAS_OC.IX_SESASOPTIM7 ON
    SICAS_OC.COMISIONES(IDPOLIZA,IDNCR,IDCOMISION)
TABLESPACE IDX_SICASOC;

/******************************************************************************/

CREATE INDEX SICAS_OC.IX_SESASOPTIM9 ON
    SICAS_OC.DETALLE_POLIZA(CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM16 ON
    SICAS_OC.DETALLE_POLIZA(STSDETALLE,CODCIA,CODEMPRESA,FECANUL)
TABLESPACE IDX_SICASOC;

/******************************************************************************/

CREATE INDEX SICAS_OC.IX_SESASOPTIM15 ON
    SICAS_OC.COBERTURAS(IDETPOL,IDPOLIZA)
TABLESPACE IDX_SICASOC;
    
CREATE INDEX SICAS_OC.IX_OPTSESAS3 ON
    SICAS_OC.COBERTURAS( IDPOLIZA, IDETPOL, IDTIPOSEG)
TABLESPACE IDX_SICASOC;

/******************************************************************************/

CREATE INDEX SICAS_OC.IX_OPTSESAS4 ON
    SICAS_OC.SESAS_DATGEN(NUMPOLIZA)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_OPTSESAS5 ON
    SICAS_OC.SESAS_DATGEN(NUMCERTIFICADO)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_OPTSESAS6 ON
    SICAS_OC.SESAS_DATGEN(CODCIA,CODEMPRESA,CODREPORTE,CODUSUARIO,NUMPOLIZA)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IDX$$_11A80001 ON
    SICAS_OC.SESAS_DATGEN(CODREPORTE,CODCIA,CODEMPRESA,CODUSUARIO,IDPOLIZA,IDETPOL)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IXDDATGENSESA ON
    SICAS_OC.SESAS_DATGEN(CODCIA,CODEMPRESA,CODREPORTE,CODUSUARIO)
TABLESPACE IDX_SICASOC;

/******************************************************************************/

CREATE INDEX SICAS_OC.IX_SESASOPTIM2 ON
    SICAS_OC.SINIESTRO(IDPOLIZA,TO_CHAR(FEC_OCURRENCIA,'YYYY'))
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM3 ON
    SICAS_OC.COBERT_ACT_ASEG(COD_ASEGURADO)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM4 ON
    SICAS_OC.FACTURAS(IDPOLIZA,CODCIA,IDFACTURA,STSFACT)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM5 ON
    SICAS_OC.DETALLE_COMISION(IDCOMISION)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM8 ON
    SICAS_OC.NOTAS_DE_CREDITO(IDPOLIZA,CODCIA,IDTRANSACCION,IDNCR,STSNCR)
TABLESPACE IDX_SICASOC;
    
CREATE INDEX SICAS_OC.IX_SESASOPTIM10 ON
    SICAS_OC.PERSONA_NATURAL_JURIDICA(NUM_DOC_IDENTIFICACION)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM11 ON
    SICAS_OC.POLIZAS(CODCIA,CODEMPRESA,FECANUL)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM12 ON
    SICAS_OC.COBERTURAS_DE_SEGUROS(PLANCOB,IDTIPOSEG)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IX_SESASOPTIM17 ON 
    SICAS_OC.AGENTES(COD_AGENTE)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IXEMISIONSESA ON
    SICAS_OC.SESAS_EMISION(CODCIA,CODEMPRESA,CODREPORTE,CODUSUARIO)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.IXDSINISESA ON
    SICAS_OC.SESAS_SINIESTROS(CODCIA,CODEMPRESA,CODREPORTE,CODUSUARIO)
TABLESPACE IDX_SICASOC;

CREATE INDEX SICAS_OC.FILTRAR_POLIZAS_SESAS_IDX1 ON
    SICAS_OC.FILTRAR_POLIZAS_SESAS(CODCIA, CODEMPRESA, PROCESOSESAS, UsuarioCarga,OBSERVACION)
TABLESPACE IDX_SICASOC;
           
CREATE INDEX SICAS_OC.IX_OPTSESAS2 ON
    SICAS_OC.COBERTURA_ASEG( IDPOLIZA, IDETPOL, IDTIPOSEG)
TABLESPACE IDX_SICASOC;
    
/******************************************************************************/
	
ANALYZE TABLE SESAS_DATGEN COMPUTE STATISTICS;
ANALYZE TABLE SESAS_EMISION COMPUTE STATISTICS;
ANALYZE TABLE SESAS_SINIESTROS COMPUTE STATISTICS;
ANALYZE TABLE LOGERRORES_SESAS COMPUTE STATISTICS;

/******************************************************************************/