
  CREATE UNIQUE INDEX "SICAS_OC"."PK_COLONIA" ON "SICAS_OC"."COLONIA" ("CODPAIS", "CODESTADO", "CODCIUDAD", "CODMUNICIPIO", "CODIGO_POSTAL", "CODIGO_COLONIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
