
  CREATE UNIQUE INDEX "SICAS_OC"."PK_CAT_RESPUESTA_DOMICI" ON "SICAS_OC"."CAT_RESPUESTA_DOMICI" ("CODCIA", "CODENTIDAD", "CORRELATIVO", "CODRESPUESTA", "DESCRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
