
  CREATE UNIQUE INDEX "SICAS_OC"."PK_EAD_CONTROL_ASEG_COBERT" ON "SICAS_OC"."EAD_CONTROL_ASEG_COBERT" ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "CODASEGURADO", "IDENDOSO", "NUMDECLARACION", "CODCOBERT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
