
  CREATE UNIQUE INDEX "SICAS_OC"."PK_FAI_CARGOS_FONDOS_RANGOS" ON "SICAS_OC"."FAI_CARGOS_FONDOS_RANGOS" ("CODCIA", "CODEMPRESA", "TIPOFONDO", "CODCARGO", "FECINICARGO", "FECFINCARGO", "ANOINIRANGO", "ANOFINRANGO", "RANGOINI", "RANGOFIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
