
  CREATE UNIQUE INDEX "SICAS_OC"."PK_REA_DISTRIBUCION_PAGO_FACUL" ON "SICAS_OC"."REA_DISTRIBUCION_PAGO_FACUL" ("CODCIA", "IDDISTRIBREA", "NUMDISTRIB", "CODEMPRESAGREMIO", "CODINTERREASEG", "NUMPAGOFACULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
