
  CREATE UNIQUE INDEX "SICAS_OC"."PK_TEMP_CARGA_SUMAS_PRIMAS" ON "SICAS_OC"."TEMP_CARGA_SUMAS_PRIMAS" ("CODCIA", "CODEMPRESA", "IDPOLIZA", "IDETPOL", "COD_ASEGURADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
