
  CREATE UNIQUE INDEX "SICAS_OC"."PK_VALGAR_COB_SEX_EDAD_RIESG" ON "SICAS_OC"."VALGAR_COB_SEX_EDAD_RIESG" ("CODCIA", "CODEMPRESA", "IDTIPOSEG", "PLANCOB", "CODCOBERT", "EDADINITARIFA", "EDADFINTARIFA", "ANIOPOL", "SEXOTARIFA", "RIESGOTARIFA", "FACTORRESCATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
