
  CREATE UNIQUE INDEX "SICAS_OC"."SALDOS_COMIS_MES3_PK" ON "SICAS_OC"."SALDOS_COMISIONES_MES_3" ("CODCIA", "COD_AGENTE", "COD_TIPO_RAMO", "FEC_INI_SALDO", "COD_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SICASOC" 
