
  CREATE UNIQUE INDEX "SICAS_OC"."SYS_C0021388" ON "SICAS_OC"."RAMO_OPERACION_CONTABLE" ("CODEMPRESA", "CODCIA", "IDEOPECONTABLE", "CODPLANPAGO", "CODCPTO", "IDECUENTA", "IDETIPOSEG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IDX_SICASOC" 
