--
-- DETALLE_FILIAL  (View) 
--
--  Dependencies: 
--   P (Synonym)
--   POLIZAS (Table)
--   FACTURAS (Table)
--   DETALLE_POLIZA (Table)
--
CREATE OR REPLACE FORCE VIEW SICAS_OC.DETALLE_FILIAL
(IDTIPOSEG, CODFILIAL, SUMA_ASEG_LOCAL, PRIMA_LOCAL, CODCIA, 
 CODEMPRESA, IDPOLIZA, IDFACTURA, NUMCUOTA)
AS 
(
SELECT D.IDTIPOSEG IDTIPOSEG,P.CodFilial CodFilial, SUM (D.SUMA_ASEG_LOCAL) SUMA_ASEG_LOCAL,F.MONTO_FACT_LOCAL PRIMA_LOCAL,
P.CodCia, P.CodEmpresa,P.IdPoliza,F.IdFactura ,F.NumCuota
  FROM DETALLE_POLIZA D, POLIZAS P, FACTURAS F
  WHERE D.IdPoliza     = P.IdPoliza
    AND P.CODFILIAL IS NOT NULL
    AND P.IdPoliza = F.IdPoliza
 GROUP BY D.IDTIPOSEG, P.CodFilial,P.CodCia, P.CodEmpresa,p.IdPoliza,F.IdFactura,F.NumCuota,F.MONTO_FACT_LOCAL

)
/
