CREATE OR REPLACE VIEW GET_BENEF_SIN (IDPOLIZA, IDSINIESTRO, BENEF, NOMBRE_BENEFICIARIO, TIPO_PAGO, BANCO,CUENTA_CLAVE,ENT_FINANCIERA,	
                                       CUENTA_BANCARIA,	TELEFONO,	NUM_IDENTIFICACION,	COD_CONVENIO,	
                                       EMAIL,	NUM_DOC_TRIBUTARIO, TP_IDENTIFICACION,	TIPO_IDENTIFICACION
) AS
SELECT BES.IDPOLIZA
      ,BES.IDSINIESTRO
      ,BES.BENEF
      ,BES.NOMBRE ||'  '|| BES.APELLIDO_PATERNO ||'  ' || BES.APELLIDO_MATERNO NOMBRE_BENEFICIARIO
      ,CASE
          WHEN BES.IDTIPO_PAGO IS NOT NULL THEN
              OC_VALORES_DE_LISTAS.BUSCA_LVALOR('PAGOBENEF',BES.IDTIPO_PAGO)
          ELSE
              NULL
      END TIPO_PAGO
      ,CASE
         WHEN BES.ENT_FINANCIERA IS NOT NULL THEN
            OC_ENTIDAD_FINANCIERA.NOMBRE_COMERCIAL(BES.CODCIA,BES.ENT_FINANCIERA)
         ELSE
            NULL
      END BANCO
      ,BES.CUENTA_CLAVE
      ,BES.ENT_FINANCIERA
      ,BES.NUMCUENTABANCARIA CUENTA_BANCARIA
      ,BES.TELEFONO
      ,BES.NUM_IDENTIFICACION
      ,BES.COD_CONVENIO
      ,BES.EMAIL
      ,BES.NUM_DOC_TRIBUTARIO
      ,BES.TP_IDENTIFICACION
      ,CASE
         WHEN BES.TP_IDENTIFICACION IS NOT NULL THEN
            DECODE(OC_VALORES_DE_LISTAS.BUSCA_LVALOR('TDOCIDEN',BES.TP_IDENTIFICACION),'Invalida','',
                  OC_VALORES_DE_LISTAS.BUSCA_LVALOR('TDOCIDEN',BES.TP_IDENTIFICACION)) 
         ELSE
            NULL
      END TIPO_IDENTIFICACION
   FROM BENEF_SIN BES
   WHERE 1 = 1
        ORDER BY 1,2 
   