 CREATE OR REPLACE VIEW GET_MONTO_PAGO (CODCIA,	CODEMPRESA,	IDPOLIZA,	IDSINIESTRO,	IDTRANSACCION,	NUM_APROBACION, BENEF,	IDDETSIN,	
                                       STSAPROBACION,	FECHA_TRANSACCION, USUARIO_GENERO, MONTO_PAGO, COD_PAGO, CodCptoTransac

) AS
 
SELECT /*+ PARALLEL */
       A.CODCIA
       ,A.CODEMPRESA
       ,A.IDPOLIZA
       ,A.IDSINIESTRO
       ,A.IDTRANSACCION
       ,A.NUM_APROBACION
       ,A.BENEF
       ,A.IDDETSIN
       ,A.STSAPROBACION
       ,TO_CHAR(T.FECHATRANSACCION,'DD/MM/YYYY') FECHA_TRANSACCION
       ,T.USUARIOGENERO USUARIO_GENERO
    ,--SUM(DECODE(CTS.SIGNO,'-',( (DA.MONTO_MONEDA)*-1),DA.MONTO_MONEDA)) MONTO_PAGO
    CASE 
       
         WHEN CTS.SIGNO = '-' THEN 
            SUM(DA.MONTO_MONEDA) * -1 
        WHEN A.STSAPROBACION  = 'ANU' THEN 
            SUM(DA.MONTO_MONEDA) * -1 
         ELSE 
            SUM(DA.MONTO_MONEDA) 
      END MONTO_RESERVA
       ,DA.Cod_Pago
       ,DA.CodCptoTransac
  FROM TRANSACCION T
       ,APROBACIONES A
       ,DETALLE_APROBACION DA
       ,Config_Transac_Siniestros TS
       ,config_transac_siniestros  CTS
 WHERE T.IDPROCESO			= 6 
   AND   CTS.CODTRANSAC = DA.CODTRANSAC
   AND CTS.CODCIA =DA.CODCIA
   AND A.CODCIA            = T.CODCIA
   AND A.CODEMPRESA        = T.CODEMPRESA
   AND A.IDTRANSACCION     = T.IDTRANSACCION
   AND A.STSAPROBACION    in( 'PAG','ANU')
   AND A.CODCIA   			= DA.CODCIA
   AND A.CODEMPRESA        = DA.CODEMPRESA
   AND A.IDSINIESTRO       = DA.IDSINIESTRO
   AND A.NUM_APROBACION    = DA.NUM_APROBACION
   AND DA.CodCia           = TS.CodCia
   AND DA.CodTransac       = TS.CodTransac
        AND   CTS.CODTRANSAC = DA.CODTRANSAC
   AND CTS.CODCIA =DA.CODCIA
 
   AND TS.StsTransac       = 'ACTIVA'
   AND TS.CodCia           = CTS.CodCia
   AND TS.CodTransac       = CTS.CodTransac
 
 GROUP BY A.CODCIA
       ,A.CODEMPRESA
       ,A.IDTRANSACCION
       ,A.IDPOLIZA
       ,A.IDSINIESTRO
       ,A.BENEF
       ,A.IDDETSIN
       ,A.NUM_APROBACION
       ,A.STSAPROBACION
       ,TO_CHAR(T.FECHATRANSACCION,'DD/MM/YYYY')
       ,T.USUARIOGENERO
       ,DA.Cod_Pago
       ,DA.CodCptoTransac
       ,CTS.SIGNO
 ORDER BY 3,4,8
 ;