--
-- NUMNUTRA  (View) 
--
--  Dependencies: 
--   POLIZAS (Table)
--   PERSONA_NATURAL_JURIDICA (Table)
--   ASEGURADO (Table)
--   ASEGURADO_CERTIFICADO (Table)
--
CREATE OR REPLACE FORCE VIEW SICAS_OC.NUMNUTRA
(POLIZA_UNICA, POLIZA, CODIGO_ASEGURADO, NUMERO_TRABAJADOR, NOMBRE, 
 APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_IDENTIFICACION, NUM_IDENTIFICACION)
AS 
SELECT  D.NUMPOLUNICO             POLIZA_UNICA,
        A.IDPOLIZA                POLIZA,
        A.COD_ASEGURADO           CODIGO_ASEGURADO,
        A.CAMPO3                  NUMERO_TRABAJADOR,
        C.NOMBRE                  NOMBRE,
        C.APELLIDO_PATERNO        APELLIDO_PATERNO,
        C.APELLIDO_MATERNO        APELLIDO_MATERNO,
        C.TIPO_DOC_IDENTIFICACION TIPO_IDENTIFICACION,
        C.NUM_DOC_IDENTIFICACION  NUM_IDENTIFICACION
FROM ASEGURADO_CERTIFICADO    A
    ,ASEGURADO                B
    ,PERSONA_NATURAL_JURIDICA C
    ,POLIZAS                  D
WHERE A.CAMPO3 IS NOT NULL
--
AND B.COD_ASEGURADO  = A.COD_ASEGURADO
--
AND C.TIPO_DOC_IDENTIFICACION = B.TIPO_DOC_IDENTIFICACION
AND C.NUM_DOC_IDENTIFICACION  = B.NUM_DOC_IDENTIFICACION
--
AND D.IDPOLIZA = A.IDPOLIZA
AND D.CODCIA   = 1
ORDER BY 1,4
/


--
-- NUMNUTRA  (Synonym) 
--
--  Dependencies: 
--   NUMNUTRA (View)
--
CREATE OR REPLACE PUBLIC SYNONYM NUMNUTRA FOR SICAS_OC.NUMNUTRA
/


GRANT SELECT ON SICAS_OC.NUMNUTRA TO PUBLIC
/
