--
-- VW_CALENDARIO_ALERTAS  (View) 
--
--  Dependencies: 
--   REA_CORREO_ALERTAS (Table)
--   REA_ESQUEMAS (Table)
--   REA_ESQUEMAS_CALENDARIO (Table)
--   REA_ESQUEMAS_EMPRESAS (Table)
--   GT_REA_EMPRESAS_GREMIO (Package)
--
CREATE OR REPLACE FORCE VIEW SICAS_OC.VW_CALENDARIO_ALERTAS
(CODCIA, CODESQUEMA, DESCESQUEMA, IDESQCONTRATO, IDCAPACONTRATO, 
 CODEMPRESAGREMIO, DESCEMPRESAGREMIO, CODINTERREASEG, IDCALENDARIO, IDALERTA, 
 EVENTO, FECHABASE, TIPO, DIAS, FECHAALERTA, 
 REPETIR, CORREOS)
AS 
SELECT CAL.CODCIA,
          CAL.CODESQUEMA,
          ESQ.DESCESQUEMA,
          CAL.IDESQCONTRATO,
          CAL.IDCAPACONTRATO,
          CAL.CODEMPRESAGREMIO,
          GT_REA_EMPRESAS_GREMIO.NOMBRE_EMPRESA (CAL.CODCIA,
                                                 CAL.CODEMPRESAGREMIO)
             DESCEMPRESAGREMIO,
          CAL.CODINTERREASEG,
          CAL.IDCALENDARIO,
          ALR.IDALERTA,
          'EDOCTA' EVENTO,
          CAL.FECENVIOESTADOCTA FECHABASE,
          ALR.TIPO,
          ALR.DIAS,
          DECODE (ALR.TIPO,
                  'ANTES', CAL.FECENVIOESTADOCTA - ALR.DIAS,
                  CAL.FECENVIOESTADOCTA + ALR.DIAS)
             FECHAALERTA,
          ALR.REPETICION REPETIR,
          ALR.CORREOS
     FROM REA_ESQUEMAS_CALENDARIO CAL,
          REA_CORREO_ALERTAS ALR,
          REA_ESQUEMAS ESQ
    WHERE     CAL.CODCIA = ALR.CODCIA
          AND CAL.CODESQUEMA = ALR.CODESQUEMA
          AND CAL.IDESQCONTRATO = ALR.IDESQCONTRATO
          AND CAL.IDCAPACONTRATO = ALR.IDCAPACONTRATO
          AND CAL.CODEMPRESAGREMIO = ALR.CODEMPRESAGREMIO
          AND CAL.CODINTERREASEG = ALR.CODINTERREASEG
          AND CAL.IDCALENDARIO = ALR.IDCALENDARIO
          AND ALR.CODESQUEMA = ESQ.CODESQUEMA
          AND ALR.CODCIA = ESQ.CODCIA
          AND ALR.STSCORREOALRT = 'ACTIVO'
          AND ALR.CODEMPRESAGREMIO <> '00001'
          AND ALR.CODEMPRESAGREMIO IN (SELECT CODEMPRESAGREMIO
                                         FROM REA_ESQUEMAS_EMPRESAS
                                        WHERE STSESQEMPRESA = 'ACTIVO')
          AND CAL.FECREALENTREGA IS NULL
          AND NVL(CAL.INDESTCTAENTREG,'N') <> 'S'
   UNION
   SELECT CAL.CODCIA,
          CAL.CODESQUEMA,
          ESQ.DESCESQUEMA,
          CAL.IDESQCONTRATO,
          CAL.IDCAPACONTRATO,
          CAL.CODEMPRESAGREMIO,
          GT_REA_EMPRESAS_GREMIO.NOMBRE_EMPRESA (CAL.CODCIA,
                                                 CAL.CODEMPRESAGREMIO)
             DESCEMPRESAGREMIO,
          CAL.CODINTERREASEG,
          CAL.IDCALENDARIO,
          ALR.IDALERTA,
          'FECHAPAGO' EVENTO,
          CAL.FECHAPAGO FECHABASE,
          ALR.TIPO,
          ALR.DIAS,
          DECODE (ALR.TIPO,
                  'ANTES', CAL.FECHAPAGO - ALR.DIAS,
                  CAL.FECHAPAGO + ALR.DIAS)
             FECHAALERTA,
          ALR.REPETICION REPETIR,
          ALR.CORREOS
     FROM REA_ESQUEMAS_CALENDARIO CAL,
          REA_CORREO_ALERTAS ALR,
          REA_ESQUEMAS ESQ
    WHERE     CAL.CODCIA = ALR.CODCIA
          AND CAL.CODESQUEMA = ALR.CODESQUEMA
          AND CAL.IDESQCONTRATO = ALR.IDESQCONTRATO
          AND CAL.IDCAPACONTRATO = ALR.IDCAPACONTRATO
          AND CAL.CODEMPRESAGREMIO = ALR.CODEMPRESAGREMIO
          AND CAL.CODINTERREASEG = ALR.CODINTERREASEG
          AND CAL.IDCALENDARIO = ALR.IDCALENDARIO
          AND ALR.CODESQUEMA = ESQ.CODESQUEMA
          AND ALR.CODCIA = ESQ.CODCIA
          AND ALR.STSCORREOALRT = 'ACTIVO'
          AND ALR.CODEMPRESAGREMIO <> '00001'
          AND ALR.CODEMPRESAGREMIO IN (SELECT CODEMPRESAGREMIO
                                         FROM REA_ESQUEMAS_EMPRESAS
                                        WHERE STSESQEMPRESA = 'ACTIVO')
          AND CAL.FECREALENTREGA IS NULL
          AND NVL(CAL.INDESTCTAENTREG,'N') <> 'S'
/


GRANT SELECT ON SICAS_OC.VW_CALENDARIO_ALERTAS TO PUBLIC
/
