
  CREATE OR REPLACE FORCE VIEW "SICAS_OC"."VW_INDICADOR_POLIZA" ("POL_CODCIA", "POL_CODEMPRESA", "POL_IDCOTIZACION", "POL_IDTIPOSEG", "POL_CODRAMO", "POL_RAMO", "POL_PLANCOB", "POL_CODSUBRAMO", "POL_SUBRAMO", "POL_IDPOLIZA", "POL_NUMRENOV", "POL_CODGRUPOEC", "POL_CONTRA_REA", "POL_CLIENTE", "POL_NUMDET", "POL_NUMPOLUNICO", "POL_STSPOLIZA", "POL_FECSTATUS", "POL_FECEMISION", "POL_FECINIVIG", "POL_FECFINVIG", "POL_FECRENOVACION", "POL_FECANUL", "POL_CODAGENTE", "POL_AGENTE", "POL_CODPROMOTOR", "POL_PROMOTOR", "POL_CODDR", "POL_DR", "POL_CODPLANPAGO", "POL_CODCANALFORMAVENTA", "POL_CANALFORMAVENTA", "POL_CODAGRUPADOR", "POL_AGRUPADOR", "POL_CODTIPONEGOCIO", "POL_TIPONEGOCIO", "POL_CODCATEGO", "POL_CATEGORIA", "POL_CODFUENTERECURSOS", "POL_FUENTERECURSOS", "POL_CODOFICINA", "POL_OFICINA", "POL_GIRONEGOCIO", "POL_ESCONTRIBUTORIO", "POL_PORCENCONTRIBUTORIO", "POL_PLATAFOMA_WEB", "POL_CODPAQCOMERCIAL", "POL_COD_MONEDA", "POL_SUMA_ASEG_LOCAL", "POL_SUMA_ASEG_MONEDA", "POL_PRIMA_LOCAL", "POL_PRIMA_MONEDA") AS 
  (
 SELECT 
        POL.CODCIA                    POL_CODCIA,
        POL.CODEMPRESA                POL_CODEMPRESA,
        POL.NUM_COTIZACION            POL_IDCOTIZACION,
        DET.IDTIPOSEG                 POL_IDTIPOSEG,
        TIP.CODTIPOPLAN               POL_CODRAMO,
        RAM.DESCVALLST                POL_RAMO,
        DET.PLANCOB                   POL_PLANCOB,
        PLA.CODTIPOPLAN               POL_CODSUBRAMO,
        SUB.DESCVALLST                POL_SUBRAMO,
        POL.IDPOLIZA                  POL_IDPOLIZA,
        POL.NUMRENOV                  POL_NUMRENOV,
        POL.CODGRUPOEC                POL_CODGRUPOEC,
        RES.DESCESQUEMA               POL_CONTRA_REA,
        TRIM(PER.NOMBRE || ' ' || PER.APELLIDO_PATERNO || ' ' || PER.APELLIDO_MATERNO)  POL_CLIENTE,
        COUNT(DET.IDETPOL)            POL_NUMDET,
        POL.NUMPOLUNICO               POL_NUMPOLUNICO,
        POL.STSPOLIZA                 POL_STSPOLIZA,
        POL.FECSTS                    POL_FECSTATUS,
        POL.FECEMISION                POL_FECEMISION,
        POL.FECINIVIG                 POL_FECINIVIG,
        POL.FECFINVIG                 POL_FECFINVIG,
        POL.FECRENOVACION             POL_FECRENOVACION,     
        POL.FECANUL                   POL_FECANUL,
        --
        NVL(POL.COD_AGENTE, AGP.COD_AGENTE)     POL_CODAGENTE,
        TRIM(PAG.NOMBRE || ' ' || PAG.APELLIDO_PATERNO || ' ' || PAG.APELLIDO_MATERNO)   POL_AGENTE,
        --
        PRO.COD_AGENTE_DISTR                    POL_CODPROMOTOR,
        TRIM(PAA.NOMBRE || ' ' || PAA.APELLIDO_PATERNO || ' ' || PAA.APELLIDO_MATERNO)   POL_PROMOTOR,
        --
        PDR.COD_AGENTE_DISTR                    POL_CODDR,
        TRIM(PAR.NOMBRE || ' ' || PAR.APELLIDO_PATERNO || ' ' || PAR.APELLIDO_MATERNO)   POL_DR,
        --
        POL.CODPLANPAGO               POL_CODPLANPAGO,
        POL.FORMAVENTA                POL_CODCANALFORMAVENTA,
        CAN.DESCVALLST                POL_CANALFORMAVENTA,
        NVL(POL.CODAGRUPADOR, '0000') POL_CODAGRUPADOR,
        AGR.DESCVALLST                POL_AGRUPADOR,
        --
        POL.CODTIPONEGOCIO            POL_CODTIPONEGOCIO,
        NEG.DESCVALLST                                                  POL_TIPONEGOCIO,
        --
        POL.CODCATEGO                                                   POL_CODCATEGO,
        CGO.DESCCATEGO                                                  POL_CATEGORIA,
        --
        POL.FUENTERECURSOSPRIMA                                         POL_CODFUENTERECURSOS,
        FTE.DESCVALLST                                                  POL_FUENTERECURSOS,
        --
        POL.CODOFICINA                                                  POL_CODOFICINA,
        OFI.DESCOFICINA                                                 POL_OFICINA,
        --
        UPPER(TXT.DESCGIRONEGOCIO)                                      POL_GIRONEGOCIO, 
        DECODE(NVL(POL.PORCENCONTRIBUTORIO, 0), 0, 'N', 'S')            POL_ESCONTRIBUTORIO,
        NVL(POL.PORCENCONTRIBUTORIO, 0)                                 POL_PORCENCONTRIBUTORIO,       
        NVL((SELECT 'S' FROM COTIZACIONES C WHERE C.CODEMPRESA = POL.CODEMPRESA AND C.CODCIA = POL.CODCIA AND C.IDCOTIZACION = POL.NUM_COTIZACION AND NVL(NVL(C.INDCOTIZACIONWEB, C.INDCOTIZACIONBASEWEB), 'N') = 'S'), 'N')  POL_PLATAFOMA_WEB,  
        POL.CODPAQCOMERCIAL                                             POL_CODPAQCOMERCIAL,
        POL.COD_MONEDA                                                  POL_COD_MONEDA,
        SUM(DET.SUMA_ASEG_LOCAL)                                        POL_SUMA_ASEG_LOCAL,
        SUM(DET.SUMA_ASEG_MONEDA)                                       POL_SUMA_ASEG_MONEDA,
        SUM(DET.PRIMA_LOCAL)                                            POL_PRIMA_LOCAL,
        SUM(DET.PRIMA_MONEDA)                                           POL_PRIMA_MONEDA        
  FROM POLIZAS    POL       INNER JOIN DETALLE_POLIZA           DET ON DET.CODCIA = POL.CODCIA    AND DET.CODEMPRESA = POL.CODEMPRESA AND DET.IDPOLIZA = POL.IDPOLIZA
                            LEFT JOIN VALORES_DE_LISTAS         FTE ON FTE.CODLISTA = 'TIPNEGO'   AND FTE.CODVALOR   = POL.FUENTERECURSOSPRIMA 
                            LEFT JOIN VALORES_DE_LISTAS         NEG ON NEG.CODLISTA = 'FUENTEREC' AND NEG.CODVALOR   = POL.CODTIPONEGOCIO
                            LEFT JOIN CATEGORIAS                CGO ON CGO.CODCIA   = POL.CODCIA  AND CGO.CODEMPRESA = POL.CODEMPRESA AND CGO.CODTIPONEGOCIO = POL.CODTIPONEGOCIO AND CGO.CODCATEGO = POL.CODCATEGO
                            LEFT JOIN OFICINAS                  OFI ON OFI.CODOFICINA = POL.CODOFICINA
                            LEFT JOIN POLIZAS_TEXTO_COTIZACION  TXT ON TXT.CODCIA = POL.CODCIA    AND TXT.CODEMPRESA = POL.CODEMPRESA AND TXT.IDPOLIZA = POL.IDPOLIZA                            
                            LEFT JOIN TIPOS_DE_SEGUROS          TIP ON TIP.CODCIA   = POL.CODCIA  AND TIP.CODEMPRESA = POL.CODEMPRESA AND TIP.IDTIPOSEG= DET.IDTIPOSEG
                            LEFT JOIN VALORES_DE_LISTAS         RAM ON RAM.CODLISTA = 'CODRAMOS'  AND RAM.CODVALOR   = TIP.CODTIPOPLAN
                            LEFT JOIN PLAN_COBERTURAS           PLA ON PLA.CODCIA   = POL.CODCIA  AND PLA.CODEMPRESA = POL.CODEMPRESA AND PLA.IDTIPOSEG= DET.IDTIPOSEG  AND PLA.PLANCOB = DET.PLANCOB                          
                            LEFT JOIN VALORES_DE_LISTAS         SUB ON SUB.CODLISTA = 'SUBRAMOS'  AND SUB.CODVALOR   = PLA.CODTIPOPLAN
                            LEFT JOIN CLIENTES                  CLI ON CLI.CODCLIENTE = POL.CODCLIENTE
                            LEFT JOIN PERSONA_NATURAL_JURIDICA  PER ON PER.TIPO_DOC_IDENTIFICACION  = CLI.TIPO_DOC_IDENTIFICACION     AND PER.NUM_DOC_IDENTIFICACION = CLI.NUM_DOC_IDENTIFICACION
                            LEFT JOIN VALORES_DE_LISTAS         CAN ON CAN.CODLISTA = 'FORMVENT'  AND CAN.CODVALOR   = POL.FORMAVENTA
                            LEFT JOIN VALORES_DE_LISTAS         AGR ON AGR.CODLISTA = 'AGRUPA'    AND AGR.CODVALOR   = NVL(POL.CODAGRUPADOR, '0000')
                            LEFT JOIN REA_ESQUEMAS_POLIZAS      RPO ON RPO.CODCIA = POL.CODCIA    AND RPO.IDPOLIZA   = POL.IDPOLIZA
                            LEFT JOIN REA_ESQUEMAS              RES ON RES.CODCIA = RPO.CODCIA    AND RES.CODESQUEMA = RPO.CODESQUEMA
                            --
                            LEFT JOIN AGENTE_POLIZA             AGP ON AGP.CODCIA   = POL.CODCIA  AND AGP.IDPOLIZA   = POL.IDPOLIZA AND AGP.IND_PRINCIPAL = 'S'
                            LEFT JOIN AGENTES                   AGE ON AGE.CODCIA   = POL.CODCIA  AND AGE.CODEMPRESA = POL.CODEMPRESA AND AGE.COD_AGENTE = NVL(POL.COD_AGENTE, AGP.COD_AGENTE) 
                            LEFT JOIN PERSONA_NATURAL_JURIDICA  PAG ON PAG.TIPO_DOC_IDENTIFICACION = AGE.TIPO_DOC_IDENTIFICACION AND PAG.NUM_DOC_IDENTIFICACION = AGE.NUM_DOC_IDENTIFICACION
                            --
                            LEFT JOIN AGENTES_DISTRIBUCION_COMISION PRO ON PRO.CODCIA = POL.CODCIA AND PRO.IDPOLIZA = POL.IDPOLIZA AND PRO.IDETPOL = 1 AND PRO.CODNIVEL = 2
                            LEFT JOIN AGENTES                   PRA ON PRA.CODCIA   = POL.CODCIA  AND PRA.CODEMPRESA = POL.CODEMPRESA AND PRA.COD_AGENTE = PRO.COD_AGENTE_DISTR
                            LEFT JOIN PERSONA_NATURAL_JURIDICA  PAA ON PAA.TIPO_DOC_IDENTIFICACION = PRA.TIPO_DOC_IDENTIFICACION AND PAA.NUM_DOC_IDENTIFICACION = PRA.NUM_DOC_IDENTIFICACION
                            --
                            LEFT JOIN AGENTES_DISTRIBUCION_COMISION PDR ON PDR.CODCIA = POL.CODCIA AND PDR.IDPOLIZA = POL.IDPOLIZA AND PDR.IDETPOL = 1 AND PDR.CODNIVEL = 1
                            LEFT JOIN AGENTES                   PRD ON PRD.CODCIA   = POL.CODCIA  AND PRD.CODEMPRESA = POL.CODEMPRESA AND PRD.COD_AGENTE = PDR.COD_AGENTE_DISTR
                            LEFT JOIN PERSONA_NATURAL_JURIDICA  PAR ON PAR.TIPO_DOC_IDENTIFICACION = PRD.TIPO_DOC_IDENTIFICACION AND PAR.NUM_DOC_IDENTIFICACION = PRD.NUM_DOC_IDENTIFICACION
WHERE DET.IDTIPOSEG IS NOT NULL
--  AND POL.IDPOLIZA = 8869
GROUP BY  
        POL.CODCIA                    ,
        POL.CODEMPRESA                ,
        POL.NUM_COTIZACION            ,
        DET.IDTIPOSEG                 ,
        TIP.CODTIPOPLAN               ,
        RAM.DESCVALLST                ,
        DET.PLANCOB                   ,
        PLA.CODTIPOPLAN               ,
        SUB.DESCVALLST                ,
        POL.IDPOLIZA                  ,        
        POL.NUMRENOV                  ,
        POL.CODGRUPOEC                ,
        RES.DESCESQUEMA               ,
        TRIM(PER.NOMBRE || ' ' || PER.APELLIDO_PATERNO || ' ' || PER.APELLIDO_MATERNO),
        POL.NUMPOLUNICO               ,
        POL.STSPOLIZA                 ,
        POL.FECSTS                    ,
        POL.FECEMISION                ,
        POL.FECINIVIG                 ,
        POL.FECFINVIG                 ,
        POL.FECRENOVACION             ,     
        POL.FECANUL                   ,
        POL.COD_MONEDA                ,
        NVL(POL.COD_AGENTE, AGP.COD_AGENTE),                               
        TRIM(PAG.NOMBRE || ' ' || PAG.APELLIDO_PATERNO || ' ' || PAG.APELLIDO_MATERNO),
        PRO.COD_AGENTE_DISTR,
        TRIM(PAA.NOMBRE || ' ' || PAA.APELLIDO_PATERNO || ' ' || PAA.APELLIDO_MATERNO),
        --
        PDR.COD_AGENTE_DISTR,
        TRIM(PAR.NOMBRE || ' ' || PAR.APELLIDO_PATERNO || ' ' || PAR.APELLIDO_MATERNO),
        --        
        POL.CODPLANPAGO               ,
        POL.FORMAVENTA                ,
        CAN.DESCVALLST                ,
        POL.CODAGRUPADOR              ,
        AGR.DESCVALLST                ,
        --
        POL.CODTIPONEGOCIO            ,
        NEG.DESCVALLST                ,
        --
        POL.CODCATEGO                 ,
        CGO.DESCCATEGO                ,
        --
        POL.FUENTERECURSOSPRIMA       ,
        FTE.DESCVALLST                ,
        --
        POL.CODOFICINA                ,
        OFI.DESCOFICINA               ,
        --
        UPPER(TXT.DESCGIRONEGOCIO)    , 
        NVL(POL.PORCENCONTRIBUTORIO, 0),
        POL.CODPAQCOMERCIAL)
