--
-- VW_REPMENFIS_GRAL  (View) 
--
--  Dependencies: 
--   REPMENFIS (Table)
--
CREATE OR REPLACE FORCE VIEW SICAS_OC.VW_REPMENFIS_GRAL
(COD_CIA, PERIODO, MES, CONSECUTIVO_ALTA, ST_REGISTRO, 
 FE_CARGA, CODUSUARIO)
AS 
(SELECT COD_CIA, PERIODO, MES, CONSECUTIVO_ALTA,  ST_REGISTRO, FE_CARGA, CODUSUARIO
FROM REPMENFIS
GROUP BY COD_CIA, PERIODO, MES, CONSECUTIVO_ALTA,  ST_REGISTRO, FE_CARGA, CODUSUARIO)
/


--
-- VW_REPMENFIS_GRAL  (Synonym) 
--
--  Dependencies: 
--   VW_REPMENFIS_GRAL (View)
--
CREATE OR REPLACE PUBLIC SYNONYM VW_REPMENFIS_GRAL FOR SICAS_OC.VW_REPMENFIS_GRAL
/


GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.VW_REPMENFIS_GRAL TO PUBLIC
/
