--JIBARRA_04-ENE-2023 <ARCHIVO DE CONTROL DE CREACION DE LA TABLA SICAS_OC.PAGINAS_FAVORITOS_APPX PARA EL REQUERIMIENTO DE CONTROL DE ACCESOS EN APEX, NUEVO SISTEMA DE SICAS>
--##SE ELIMINAN EL SINONIMO Y LA TABLA
DROP PUBLIC SYNONYM PAGINAS_FAVORITOS_APPX;

DROP TABLE SICAS_OC.PAGINAS_FAVORITOS_APPX CASCADE CONSTRAINTS;

/
--##SE CREA LA TABLA SICAS_OC.PAGINAS_FAVORITOS_APPX
CREATE TABLE SICAS_OC.PAGINAS_FAVORITOS_APPX(CODCIA         	NUMBER          NOT NULL        --CODIGO DE COMPANIA
											--**,CODGRUPO       	VARCHAR2(20)    NOT NULL        --CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS
											,CODUSUARIO			VARCHAR2(20)    NOT NULL        --CODIGO CON EL QUE SE IDENTIFICA EL USUARIO
											,IDAPLICACION      	NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION
											,IDPAGINA      		NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA PAGINA DE LA APLICACION
											,FLAG_ACCESO		VARCHAR2(2)		NOT NULL		--BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA PAGINA DE LA APLICACION [S (SI), N (NO)]
											,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO
											,FECHA_ALTA			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
											,USUARIO_MOD		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
											,FECHA_MOD			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO
											)TABLESPACE TS_SICASOC;

/
--##SE CREA INDICE UNICO PARA LA TABLA
CREATE UNIQUE INDEX SICAS_OC.PAGINAS_FAVORITOS_APPX_IDX1 ON SICAS_OC.PAGINAS_FAVORITOS_APPX (CODCIA, CODUSUARIO, IDAPLICACION, IDPAGINA) TABLESPACE IDX_SICASOC;

--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.PAGINAS_FAVORITOS_APPX ADD CONSTRAINT PK_PAGINAS_FAVORITOS_APPX PRIMARY KEY (CODCIA, CODUSUARIO, IDAPLICACION, IDPAGINA) USING INDEX;
ALTER TABLE SICAS_OC.PAGINAS_FAVORITOS_APPX ADD CONSTRAINT FK_PAGINAS_FAVORITOS_APPX FOREIGN KEY (CODCIA, CODUSUARIO) REFERENCES SICAS_OC.USUARIOS_APPX(CODCIA, CODUSUARIO) ON DELETE CASCADE;


--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.CODCIA 				IS 'CODIGO DE COMPANIA';
--**COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.CODGRUPO 				IS 'CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_ESP_APPX.CODUSUARIO 		IS 'CODIGO CON EL QUE SE IDENTIFICA EL USUARIO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.IDAPLICACION 			IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.IDPAGINA 				IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA PAGINA DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.FLAG_ACCESO 			IS 'BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA PAGINA DE LA APLICACION [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.USUARIO_ALTA 			IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.FECHA_ALTA 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.USUARIO_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_FAVORITOS_APPX.FECHA_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO';

/
--##GRANT´s
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.PAGINAS_FAVORITOS_APPX TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM PAGINAS_FAVORITOS_APPX FOR SICAS_OC.PAGINAS_FAVORITOS_APPX;
