--JIBARRA_04-ENE-2023 <ARCHIVO DE CONTROL DE CREACION DE LA TABLA SICAS_OC.APLICACIONES_ACCESO_APPX PARA EL REQUERIMIENTO DE CONTROL DE ACCESOS EN APEX, NUEVO SISTEMA DE SICAS>
--##SE ELIMINAN EL SINONIMO Y LA TABLA
DROP PUBLIC SYNONYM APLICACIONES_ACCESO_APPX;

DROP TABLE SICAS_OC.APLICACIONES_ACCESO_APPX CASCADE CONSTRAINTS;

/
--##SE CREA LA TABLA SICAS_OC.APLICACIONES_ACCESO_APPX
CREATE TABLE SICAS_OC.APLICACIONES_ACCESO_APPX(CODCIA         	NUMBER          NOT NULL        --CODIGO DE COMPANIA
										,CODGRUPO       	VARCHAR2(20)    NOT NULL        --CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS
										,CODUSUARIO			VARCHAR2(20)            		--CODIGO CON EL QUE SE IDENTIFICA EL USUARIO, SI ES NULL AFECTA A TODO EL GRUPO, SI ES NOT NULL ES ACCESO ESPECIAL
										--**,WORKSPACE			VARCHAR2(20)    NOT NULL        --ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION
										,IDAPLICACION      	NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION
										,FLAG_ACCESO		VARCHAR2(2)		NOT NULL		--BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA APLICACION [S (SI), N (NO)]
										,FLAG_ACCESO_ESP	VARCHAR2(2)		NOT NULL		--BANDERA QUE DETERMINA SI SE CONSIDERA UN ACCESO ESPECIAL [S (SI), N (NO)]
										,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO
										,FECHA_ALTA			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
										,USUARIO_MOD		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
										,FECHA_MOD			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO
										)TABLESPACE TS_SICASOC;

/
--##SE CREA INDICE UNICO PARA LA TABLA
CREATE UNIQUE INDEX SICAS_OC.APLICACIONES_ACCESO_APPX_IDX1 ON SICAS_OC.APLICACIONES_ACCESO_APPX (CODCIA, CODGRUPO, IDAPLICACION) TABLESPACE IDX_SICASOC;

--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.APLICACIONES_ACCESO_APPX ADD CONSTRAINT PK_APLICACIONES_ACCESO_APPX PRIMARY KEY (CODCIA, CODGRUPO, IDAPLICACION) USING INDEX;
ALTER TABLE SICAS_OC.APLICACIONES_ACCESO_APPX ADD CONSTRAINT FK_APLICACIONES_ACCESO_APPX FOREIGN KEY (CODCIA, CODGRUPO) REFERENCES SICAS_OC.GRUPOS_DE_USUARIOS_APPX(CODCIA, CODGRUPO) ON DELETE CASCADE;
--**ALTER TABLE SICAS_OC.APLICACIONES_ACCESO_APPX ADD CONSTRAINT FK2_APLICACIONES_ACCESO_ESP_APPX FOREIGN KEY (CODCIA, IDAPLICACION) REFERENCES SICAS_OC.APLICACIONES_APPX(CODCIA, IDAPLICACION) ON DELETE CASCADE;

--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.CODCIA 				IS 'CODIGO DE COMPANIA';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.CODGRUPO 			IS 'CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.CODUSUARIO 			IS 'CODIGO CON EL QUE SE IDENTIFICA EL USUARIO, SI ES NULL AFECTA A TODO EL GRUPO, SI ES NOT NULL ES ACCESO ESPECIAL';
--**COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.WORKSPACE 			IS 'ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.IDAPLICACION 		IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.FLAG_ACCESO 		IS 'BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA APLICACION [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.FLAG_ACCESO_ESP 	IS 'BANDERA QUE DETERMINA SI SE CONSIDERA UN ACCESO ESPECIAL [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.USUARIO_ALTA 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.FECHA_ALTA 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.USUARIO_MOD 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_APPX.FECHA_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO';

/
--##GRANT´s
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.APLICACIONES_ACCESO_APPX TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM APLICACIONES_ACCESO_APPX FOR SICAS_OC.APLICACIONES_ACCESO_APPX;
