--JIBARRA_04-ENE-2023 <ARCHIVO DE CONTROL DE CREACION DE LA TABLA SICAS_OC.USUARIOS_APPX PARA EL REQUERIMIENTO DE CONTROL DE ACCESOS EN APEX, NUEVO SISTEMA DE SICAS>
--##SE ELIMINAN EL SINONIMO Y LA TABLA
DROP PUBLIC SYNONYM USUARIOS_APPX;

DROP TABLE SICAS_OC.USUARIOS_APPX CASCADE CONSTRAINTS;

/
--##SE CREA LA TABLA SICAS_OC.USUARIOS_APPX
CREATE TABLE SICAS_OC.USUARIOS_APPX(CODCIA         	NUMBER          NOT NULL        --CODIGO DE COMPANIA
								,CODGRUPO       	VARCHAR2(20)    NOT NULL        --CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS
								,CODUSUARIO			VARCHAR2(20)    NOT NULL        --CODIGO DE CON EL QUE SE IDENTIFICA EL USUARIO
								,NOMUSUARIO      	VARCHAR2(100)   NOT NULL        --NOMBRE COMPLETO DEL USUARIO
								,EMAILUSUARIO		VARCHAR2(50)	NOT NULL		--CORREO ASOCIADO AL USUARIO
								,FLAG_SUPERVISOR   	VARCHAR2(2)     NOT NULL     	--BANDERA QUE INDICA SI EL USUARIO ES SUPERVISOR [S (SI), N (NO)]
								,FLAG_ACTIVO   		VARCHAR2(2)     NOT NULL     	--BANDERA QUE INDICA SI EL USUARIO ESTA ACTIVO [S (SI), N (NO)]
								,FECHA_BAJA			DATE							--FECHA EN LA QUE SE INDICA LA BAJA DEL USUARIO
								,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO
								,FECHA_ALTA			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
								,USUARIO_MOD		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
								,FECHA_MOD			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO
								)TABLESPACE TS_SICASOC;

/
--##SE CREA INDICE UNICO PARA LA TABLA
CREATE UNIQUE INDEX SICAS_OC.USUARIOS_APPX_IDX1 ON SICAS_OC.USUARIOS_APPX (CODCIA, CODUSUARIO) TABLESPACE IDX_SICASOC;

--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.USUARIOS_APPX ADD CONSTRAINT PK_USUARIOS_APPX PRIMARY KEY (CODCIA, CODUSUARIO) USING INDEX;
ALTER TABLE SICAS_OC.USUARIOS_APPX ADD CONSTRAINT FK_USUARIOS_APPX FOREIGN KEY (CODCIA, CODGRUPO) REFERENCES SICAS_OC.GRUPOS_DE_USUARIOS_APPX(CODCIA, CODGRUPO) ON DELETE CASCADE;

--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.CODCIA 			IS 'CODIGO DE COMPANIA';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.CODGRUPO 			IS 'CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.CODUSUARIO 		IS 'CODIGO DE CON EL QUE SE IDENTIFICA EL USUARIO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.NOMUSUARIO 		IS 'NOMBRE COMPLETO DEL USUARIO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.EMAILUSUARIO 		IS 'CORREO ASOCIADO AL USUARIO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.FLAG_SUPERVISOR	IS 'BANDERA QUE INDICA SI EL USUARIO ES SUPERVISOR [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.FLAG_ACTIVO 		IS 'BANDERA QUE INDICA SI EL USUARIO ESTA ACTIVO [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.FECHA_BAJA 		IS 'FECHA EN LA QUE SE INDICA LA BAJA DEL USUARIO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.USUARIO_ALTA 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.FECHA_ALTA 		IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.USUARIO_MOD 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.USUARIOS_APPX.FECHA_MOD 		IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO';

/
--##GRANT´s
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.USUARIOS_APPX TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM USUARIOS_APPX FOR SICAS_OC.USUARIOS_APPX;

/
--##INSERT para considerar la informacion de control de la aplciacion de acceso
INSERT INTO SICAS_OC.USUARIOS_APPX (CODCIA,CODGRUPO,CODUSUARIO,NOMUSUARIO,EMAILUSUARIO,FLAG_SUPERVISOR,FLAG_ACTIVO,FECHA_BAJA,USUARIO_ALTA,FECHA_ALTA,USUARIO_MOD,FECHA_MOD)
SELECT U.CODCIA
    ,U.CODGRUPO
    ,U.CODUSUARIO
    ,U.NOMUSUARIO
    ,NVL(U.EMAIL,'noEmail@thonaseguros.mx') EMAIL
    ,U.SUPERVISOR
    ,'S' FLAG_ACTIVO
    ,NULL FECHA_BAJA
    ,USER USUARIO_ALTA
    ,TRUNC(SYSDATE) FECHA_ALTA
    ,USER USUARIO_MOD
    ,TRUNC(SYSDATE) FECHA_MOD
FROM SICAS_OC.USUARIOS U
;

/

COMMIT;