--JIBARRA_04-ENE-2023 <ARCHIVO DE CONTROL DE CREACION DE LA TABLA SICAS_OC.PAGINAS_ACCESO_APPX PARA EL REQUERIMIENTO DE CONTROL DE ACCESOS EN APEX, NUEVO SISTEMA DE SICAS>
--##SE ELIMINAN EL SINONIMO Y LA TABLA
DROP PUBLIC SYNONYM PAGINAS_ACCESO_APPX;

DROP TABLE SICAS_OC.PAGINAS_ACCESO_APPX CASCADE CONSTRAINTS;

/
--##SE CREA LA TABLA SICAS_OC.PAGINAS_ACCESO_APPX
CREATE TABLE SICAS_OC.PAGINAS_ACCESO_APPX(CODCIA         	NUMBER          NOT NULL        --CODIGO DE COMPANIA
											,CODGRUPO       	VARCHAR2(20)    NOT NULL        --CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS
											--**,WORKSPACE			VARCHAR2(20)    NOT NULL        --ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION
											,CODUSUARIO			VARCHAR2(20)    NOT NULL        --CODIGO CON EL QUE SE IDENTIFICA EL USUARIO
											,IDAPLICACION      	NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION
											,IDPAGINA      		NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA PAGINA DE LA APLICACION
											,ORDER_ENTRY		NUMBER			NOT NULL		--IDENTIFICADOR NUMERICO PARA EL ORDEN DEL MENU, AQUELLOS QUE SE REPIDEN CORRESPONDEN A SUBMENUS
											,NIVEL				NUMBER			NOT NULL		--IDENTIFICADOR DEL NIVEL PARA CREAR EL MENU Y/O SUBMENU
											,FLAG_ACCESO		VARCHAR2(2)		NOT NULL		--BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA PAGINA DE LA APLICACION [S (SI), N (NO)]
											,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO
											,FECHA_ALTA			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
											,USUARIO_MOD		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
											,FECHA_MOD			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO
											)TABLESPACE TS_SICASOC;

/
--##SE CREA INDICE UNICO PARA LA TABLA
CREATE UNIQUE INDEX SICAS_OC.PAGINAS_ACCESO_APPX_IDX1 ON SICAS_OC.PAGINAS_ACCESO_APPX (CODCIA, CODUSUARIO, IDAPLICACION, IDPAGINA, ORDER_ENTRY, NIVEL) TABLESPACE IDX_SICASOC;

--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.PAGINAS_ACCESO_APPX ADD CONSTRAINT PK_PAGINAS_ACCESO_APPX PRIMARY KEY (CODCIA, CODUSUARIO, IDAPLICACION, IDPAGINA, ORDER_ENTRY, NIVEL) USING INDEX;
ALTER TABLE SICAS_OC.PAGINAS_ACCESO_APPX ADD CONSTRAINT FK_PAGINAS_ACCESO_APPX FOREIGN KEY (CODCIA, CODGRUPO, IDAPLICACION) REFERENCES SICAS_OC.APLICACIONES_ACCESO_APPX(CODCIA, CODGRUPO, IDAPLICACION) ON DELETE CASCADE;


--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.CODCIA 				IS 'CODIGO DE COMPANIA';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.CODGRUPO 			IS 'CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS';
--**COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.WORKSPACE 			IS 'ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_ACCESO_ESP_APPX.CODUSUARIO 		IS 'CODIGO CON EL QUE SE IDENTIFICA EL USUARIO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.IDAPLICACION 		IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.IDPAGINA 			IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA PAGINA DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.PAGINAS_APLICACION_APPX.ORDER_ENTRY 			IS 'IDENTIFICADOR NUMERICO PARA EL ORDEN DEL MENU, AQUELLOS QUE SE REPIDEN CORRESPONDEN A SUBMENUS';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.FLAG_ACCESO 			IS 'BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA PAGINA DE LA APLICACION [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.USUARIO_ALTA 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.FECHA_ALTA 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.USUARIO_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.PAGINAS_ACCESO_APPX.FECHA_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO';

/
--##GRANT´s
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.PAGINAS_ACCESO_APPX TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM PAGINAS_ACCESO_APPX FOR SICAS_OC.PAGINAS_ACCESO_APPX;
