--JIBARRA_04-ENE-2023 <ARCHIVO DE CONTROL DE CREACION DE LA TABLA SICAS_OC.APLICACIONES_APPX PARA EL REQUERIMIENTO DE CONTROL DE ACCESOS EN APEX, NUEVO SISTEMA DE SICAS>
--##SE ELIMINAN EL SINONIMO Y LA TABLA
DROP PUBLIC SYNONYM APLICACIONES_APPX;

DROP TABLE SICAS_OC.APLICACIONES_APPX CASCADE CONSTRAINTS;

/
--##SE CREA LA TABLA SICAS_OC.APLICACIONES_APPX
CREATE TABLE SICAS_OC.APLICACIONES_APPX(CODCIA         	NUMBER          NOT NULL        --CODIGO DE COMPANIA
										--**,CODGRUPO       	VARCHAR2(20)    NOT NULL        --CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS
										,WORKSPACE			VARCHAR2(20)    NOT NULL        --ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION
										,IDAPLICACION      	NUMBER   		NOT NULL        --IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION
										,NOMBRE_APLICACION	VARCHAR2(100)	NOT NULL		--NOMBRE DESCRIPTIVO DE LA APLICACION 
										,LINK_HOME  		VARCHAR2(50)    NOT NULL     	--URL/REFERENCIA DE ACCESO A SU PAGINA DE INICIO/HOME DE LA APLICACION
										,LOGO_HOME   		VARCHAR2(50)    NOT NULL     	--NOMBRE/IDENTIFICADOR DEL LOGO/IMAGEN QUE PERMITE IDENTIFICAR A LA APLICACION
										,FLAG_VISIBLE		VARCHAR2(2)		NOT NULL		--BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA APLICACION [S (SI), N (NO)]
										,USUARIO_ALTA		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO
										,FECHA_ALTA			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO
										,USUARIO_MOD		VARCHAR2(50)	NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO
										,FECHA_MOD			DATE			NOT NULL	    --CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO
										)TABLESPACE TS_SICASOC;

/
--##SE CREA INDICE UNICO PARA LA TABLA
CREATE UNIQUE INDEX SICAS_OC.APLICACIONES_APPX_IDX1 ON SICAS_OC.APLICACIONES_APPX (CODCIA, IDAPLICACION) TABLESPACE IDX_SICASOC;

--##ALTER TABLE DE PRIMARY KEY AND FOREIGN KEY
ALTER TABLE SICAS_OC.APLICACIONES_APPX ADD CONSTRAINT PK_APLICACIONES_APPX PRIMARY KEY (CODCIA, IDAPLICACION) USING INDEX;
--**ALTER TABLE SICAS_OC.APLICACIONES_APPX ADD CONSTRAINT FK_APLICACIONES_APPX FOREIGN KEY (CODCIA, CODGRUPO) REFERENCES SICAS_OC.GRUPOS_DE_USUARIOS_APPX(CODCIA, CODGRUPO) ON DELETE CASCADE;


--##COMENTARIOS DESCRIPTIVOS DE LAS COLUMNAS
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.CODCIA 				IS 'CODIGO DE COMPANIA';
--**COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.CODGRUPO 			IS 'CODIGO DE GRUPO QUE ORGANIZA A LOS USUARIOS';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.WORKSPACE 			IS 'ESPACIO DE TRABAJO EN EL QUE SE UBICA LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.IDAPLICACION 		IS 'IDENTIFICADOR NUMERICO Y UNICO DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.NOMBRE_APLICACION 	IS 'NOMBRE DESCRIPTIVO DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.LINK_HOME			IS 'URL/REFERENCIA DE ACCESO A SU PAGINA DE INICIO/HOME DE LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.LOGO_HOME 			IS 'NOMBRE/IDENTIFICADOR DEL LOGO/IMAGEN QUE PERMITE IDENTIFICAR A LA APLICACION';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.FLAG_VISIBLE 		IS 'BANDERA QUE DETERMINA SI ESTA PERMITIDO EL ACCESO A LA APLICACION [S (SI), N (NO)]';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.USUARIO_ALTA 		IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.FECHA_ALTA 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE CREA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.USUARIO_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, USUARIO QUE MODIFICA EL REGISTRO';
COMMENT ON COLUMN SICAS_OC.APLICACIONES_APPX.FECHA_MOD 			IS 'CAMPO DE CONTROL/AUDITORIA, FECHA EN QUE SE MODIFICA EL REGISTRO';

/
--##GRANT´s
GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.APLICACIONES_APPX TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM APLICACIONES_APPX FOR SICAS_OC.APLICACIONES_APPX;
