--DROP TABLE FACT_ELECT_MOTIVO_CANCELA CASCADE CONSTRAINT;

CREATE TABLE FACT_ELECT_MOTIVO_CANCELA 
(   CodCia              NUMBER(14)     NOT NULL,
    CveMotivCancFact    VARCHAR2(30)   NOT NULL,
    DescMotivoCanc      VARCHAR2(300)  NOT NULL,
    StsMotivCanc        VARCHAR2(3),
    FecStsMotivCanc     DATE,
    CodUsuario          VARCHAR2(30)
)
TABLESPACE TS_SICASOC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.CodCia IS 'Código Compañia';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.CveMotivCancFact IS 'Código De Cancelacion';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.DescMotivoCanc IS 'Descripción Motivo de Cancelación';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.StsMotivCanc IS 'Esttus Motivo Cancelación';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.FecStsMotivCanc IS 'Fecha de Estatus';

COMMENT ON COLUMN SICAS_OC.FACT_ELECT_MOTIVO_CANCELA.CodUsuario IS 'Código de Usuario';




CREATE UNIQUE INDEX SICAS_OC.P_MOTIV_CANC ON SICAS_OC.FACT_ELECT_MOTIVO_CANCELA
(CodCia, CveMotivCancFact)
LOGGING
TABLESPACE IDX_SICASOC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SICAS_OC.FACT_ELECT_MOTIVO_CANCELA ADD (
  CONSTRAINT P_MOTIV_CANC
  PRIMARY KEY
  (CodCia, CveMotivCancFact)
  USING INDEX SICAS_OC.P_MOTIV_CANC
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACT_ELECT_MOTIVO_CANCELA TO PUBLIC;

CREATE OR REPLACE PUBLIC SYNONYM FACT_ELECT_MOTIVO_CANCELA FOR SICAS_OC.FACT_ELECT_MOTIVO_CANCELA;
