INSERT INTO TIPO_DE_LISTA T (T.CODLISTA, T.DESCLISTA, T.TIPO_LISTA) VALUES ('CVEFACTELE','CLAVE PARA FACTURA ELECTRONICA SEGUN RAMO','SYS');
/
INSERT INTO VALORES_DE_LISTAS T (T.CODLISTA, T.CODVALOR, T.DESCVALLST) VALUES ('CVEFACTELE','010','84131601');
/        
INSERT INTO VALORES_DE_LISTAS T (T.CODLISTA, T.CODVALOR, T.DESCVALLST) VALUES ('CVEFACTELE','020','84131602');
/        
INSERT INTO VALORES_DE_LISTAS T (T.CODLISTA, T.CODVALOR, T.DESCVALLST) VALUES ('CVEFACTELE','030','84131603');
/        
insert into VALORES_DE_LISTAS (CODLISTA, CODVALOR, DESCVALLST) values ('UENXTIPSEG', 'PPAQ1', '01111011001001001');

COMMIT;
