UPDATE COTIZACIONES A
SET    A.CODPAQUETE = ( SELECT B.CODPAQUETE
                        FROM   PAQUETE_COMERCIAL B
                        WHERE  B.DESCPAQUETE = A.CODPAQCOMERCIAL)
WHERE  A.CODPAQCOMERCIAL IS NOT NULL
/
COMMIT
/
