--
-- AGRUPA_DOCTOS_SEQ  (Sequence) 
--
CREATE SEQUENCE SICAS_OC.AGRUPA_DOCTOS_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  CYCLE
  CACHE 20
  NOORDER
/

CREATE OR REPLACE PUBLIC SYNONYM AGRUPA_DOCTOS_SEQ FOR SICAS_OC.AGRUPA_DOCTOS_SEQ
/

GRANT SELECT ON SICAS_OC.AGRUPA_DOCTOS_SEQ TO PUBLIC
/
