ALTER TABLE SICAS_OC.DETALLE_POLIZA ADD
   ( RIESGOTARIFA     VARCHAR2(2),
     HORASVIG         NUMBER(5,0),
     DIASVIG          NUMBER(5,0),
     FACTORAJUSTE     NUMBER(9,6),
     FACTFORMULADEDUC NUMBER(12,8)
   );

COMMENT ON COLUMN SICAS_OC.DETALLE_POLIZA.RIESGOTARIFA IS 'Riesgo para Tarifa';
COMMENT ON COLUMN SICAS_OC.DETALLE_POLIZA.HORASVIG IS 'Horas Cubiertas en Vigencia';
COMMENT ON COLUMN SICAS_OC.DETALLE_POLIZA.DIASVIG IS 'Días Cubiertos en Vigencia';
COMMENT ON COLUMN SICAS_OC.DETALLE_POLIZA.FACTORAJUSTE IS 'Factor de Ajuste';
COMMENT ON COLUMN SICAS_OC.DETALLE_POLIZA.FACTFORMULADEDUC IS 'Factor de Fórmula de Deducible Default del Cotizador';