ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_ASEG 
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_ASEG.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'

/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_ASEG
ADD (MONTODIARIO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_ASEG.MONTODIARIO IS 'Monto Diario de la cobertura'
/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_ASEG  
ADD (DIAS_CAL        NUMBER(5))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_ASEG.DIAS_CAL IS 'Dias para calcular la suma asegurada'