ALTER TABLE SICAS_OC.PLAN_COBERTURAS ADD
   ( INDPRIMIN  VARCHAR2(1),
     MTOPRIMIN  NUMBER(18,2)
   );

COMMENT ON COLUMN SICAS_OC.PLAN_COBERTURAS.INDPRIMIN IS 'Indicador de si Aplica Regla de Prima Anual Mínima S/N';
COMMENT ON COLUMN SICAS_OC.PLAN_COBERTURAS.MTOPRIMIN IS 'Monto de Prima Anual Mínima';
