ALTER TABLE SICAS_OC.COBERT_ACT 
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COBERT_ACT.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'
/
ALTER TABLE SICAS_OC.COBERT_ACT
ADD (MONTODIARIO        NUMBER(18,2))
/
COMMENT ON COLUMN COBERT_ACT.MONTODIARIO IS 'Monto Diario de la cobertura'
/
ALTER TABLE SICAS_OC.COBERT_ACT  
ADD (DIAS_CAL        NUMBER(5))
/
COMMENT ON COLUMN COBERT_ACT.DIAS_CAL IS 'Dias para calcular la suma asegurada'