ALTER TABLE SICAS_OC.COTIZACIONES
 ADD (STSACTUALIZA  VARCHAR2(6))
/

ALTER TABLE SICAS_OC.COTIZACIONES
 ADD (USUARIOACTUALIZA  VARCHAR2(30))
/

ALTER TABLE SICAS_OC.COTIZACIONES
 ADD (FECHAACTUALIZA  DATE)
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES.STSACTUALIZA IS 'Estatus de la Solicitud de Actualización de Vigencias de la Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES.USUARIOACTUALIZA IS 'Usuario que Solicitó/Actualizó la Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES.FECHAACTUALIZA IS 'Fecha en que se Solicitó/Actualizó la Cotización'
/