ALTER TABLE SICAS_OC.COTIZACIONES_COBERTURAS  
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERTURAS.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'
/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERTURAS  
ADD (MONTODIARIO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERTURAS.MONTODIARIO IS 'Monto Diario de la cobertura'

ALTER TABLE SICAS_OC.COTIZACIONES_COBERTURAS  
ADD (DIAS_CAL        NUMBER(5))
/
COMMENT ON COLUMN COTIZACIONES_COBERTURAS.DIAS_CAL IS 'Dias para calcular la suma asegurada'