ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_MASTER  
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_MASTER.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'

/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_MASTER
ADD (MONTODIARIO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_MASTER.MONTODIARIO IS 'Monto Diario de la cobertura'
/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_MASTER  
ADD (DIAS_CAL        NUMBER(5))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_MASTER.DIAS_CAL IS 'Dias para calcular la suma asegurada'