ALTER TABLE SICAS_OC.TEMP_SESAS_COMPAPCOL1 ADD IdEndoso NUMBER(14,0);
ALTER TABLE SICAS_OC.TEMP_SESAS_COMPAPCOL2 ADD IdEndoso NUMBER(14,0);
ALTER TABLE SICAS_OC.TEMP_SESAS_COMPVIGRP1 ADD IdEndoso NUMBER(14,0);
ALTER TABLE SICAS_OC.TEMP_SESAS_COMPVIGRP2 ADD IdEndoso NUMBER(14,0);
