ALTER TABLE SICAS_OC.PLAN_DE_PAGOS ADD
   ( INDPRIMIN  VARCHAR2(1),
     MTOPRIMIN  NUMBER(18,2)
   );

COMMENT ON COLUMN SICAS_OC.PLAN_DE_PAGOS.INDPRIMIN IS 'Indicador de si Aplica Regla de Prima Anual Mínima S/N';
COMMENT ON COLUMN SICAS_OC.PLAN_DE_PAGOS.MTOPRIMIN IS 'Monto de Prima Anual Mínima';
