ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'

/
ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (RIESGOTARIFA VARCHAR2(2))
/
COMMENT ON COLUMN COTIZACIONES.RIESGOTARIFA IS 'Riesgo del Asegurado para Tarifa';

/
ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (TIPNEGO_WEB VARCHAR2(10))
/
COMMENT ON COLUMN COTIZACIONES.TIPNEGO_WEB IS 'Tipo de Negocio desde Web';

/
ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (RIES_LABOR VARCHAR2(1))
/
COMMENT ON COLUMN COTIZACIONES.RIES_LABOR IS 'Tipo de Riesgo a cubrir Laboral';

/
ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (RIES_24365 VARCHAR2(1))
/
COMMENT ON COLUMN COTIZACIONES.RIES_24365 IS 'Tipo de Riesgo a cubrir 24/365';

/
ALTER TABLE SICAS_OC.COTIZACIONES  
ADD (RIES_TRASLA VARCHAR2(1))
/
COMMENT ON COLUMN COTIZACIONES.RIES_TRASLA IS 'Tipo de Riesgo a cubrir de Traslado';