ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_WEB_TEMP  
ADD (FRANQUICIAINGRESADO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_WEB_TEMP.FRANQUICIAINGRESADO IS 'Monto de Franquicia de la Cotización'
/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_WEB_TEMP  
ADD (MONTODIARIO        NUMBER(18,2))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_WEB_TEMP.MONTODIARIO IS 'Monto Diario de la cobertura'

ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_WEB_TEMP  
ADD (DIAS_CAL        NUMBER(5))
/
COMMENT ON COLUMN COTIZACIONES_COBERT_WEB_TEMP.DIAS_CAL IS 'Dias para calcular la suma asegurada'