--COLOCA DEFAULT
ALTER TABLE SINIESTRO
MODIFY
(
NUMSEMANA	NUMBER(2) DEFAULT 0,
IDTPORIGEN  VARCHAR2(6)  DEFAULT 'NORMAL',
CODUSUARIO  VARCHAR2(30) DEFAULT USER,
FECREGISTRO DATE  DEFAULT TRUNC(SYSDATE)
)
;

ALTER TABLE DATOS_PART_SINIESTROS
MODIFY
(
CODEMPRESA	NUMBER(14) DEFAULT 1
)
;

ALTER TABLE OBSERVACION_SINIESTRO
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1
)
;

ALTER TABLE DETALLE_SINIESTRO_ASEG
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE DETALLE_SINIESTRO
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE DETALLE_APROBACION
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE DETALLE_APROBACION_ASEG
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE APROBACIONES
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE APROBACION_ASEG
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS'
)
;

ALTER TABLE BENEF_SIN_PAGOS
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1
)
;

ALTER TABLE BENEF_SIN
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1
)
;

ALTER TABLE COBERTURA_SINIESTRO_ASEG
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS',
IDTPRESERVA NUMBER(5) DEFAULT 1
)
;

ALTER TABLE COBERTURA_SINIESTRO
MODIFY
(
CODCIA	    NUMBER(14) DEFAULT 1,
CODEMPRESA	NUMBER(14) DEFAULT 1,
COD_MONEDA  VARCHAR2(5)  DEFAULT 'PS',
IDTPRESERVA NUMBER(5) DEFAULT 1
)
;