ALTER TABLE PLANTILLAS_CONTABLES 
ADD 
(
IDREGFISSAT NUMBER(5),
IDREGPLANTILLA_SUST NUMBER(10)
);
/
ALTER TABLE PLANTILLAS_CONTABLES ADD CONSTRAINT FK_CAT_REG_FISCAL_PLANT_CONT FOREIGN KEY   (IDREGFISSAT) REFERENCES   CAT_REGIMEN_FISCAL   (IDREGFISSAT)
ENABLE VALIDATE;
/
COMMENT ON COLUMN PLANTILLAS_CONTABLES.IDREGFISSAT IS 'Identificador de tipo de registro fiscal ante el SAT';
COMMENT ON COLUMN PLANTILLAS_CONTABLES.IDREGPLANTILLA_SUST IS 'Identifica el registro que sustituye de la plantilla por el tipo de IDREGFISSAT';
/
