DROP PUBLIC SYNONYM FECHASDEVIGENCIA;

DROP TYPE SICAS_OC.FECHASDEVIGENCIA FORCE;

--JIBARRA_13-12-2022 <SE CREA UN OBJETO QUE PERMITA RETORNAR UN DESCRIPTIVO DE QUE TIPO SE OBTIENE [tipo [POLIZA, CERTIFICADO, ETC]] LAS FECHAS DE VIGENCIA Y EL VALOR DE LAS MISMAS
--						FECHA INICIAL [fechaIniVig] Y FECHA FINAL [fechaFinVig] DE VIGENCIA.>
CREATE OR REPLACE TYPE SICAS_OC.FECHASDEVIGENCIA AS OBJECT (tipo VARCHAR2(100), fechaIniVig DATE, fechaFinVig DATE);

/
--GRANT´s
GRANT EXECUTE ON SICAS_OC.FECHASDEVIGENCIA TO PUBLIC;

/
--##SINONIMO
CREATE OR REPLACE PUBLIC SYNONYM FECHASDEVIGENCIA FOR SICAS_OC.FECHASDEVIGENCIA;
