ALTER TABLE sicas_oc.cotizaciones ADD (CODTIPONEGOCIO VARCHAR2(100 CHAR));
COMMENT ON COLUMN sicas_oc.cotizaciones.CODTIPONEGOCIO IS 'Código tipo de negocio';
/
ALTER TABLE sicas_oc.cotizaciones ADD (CODPAQCOMERCIAL VARCHAR2(250 CHAR));
COMMENT ON COLUMN sicas_oc.cotizaciones.CODPAQCOMERCIAL IS 'Código paquete comercial';
/
ALTER TABLE sicas_oc.cotizaciones ADD (CODOFICINA VARCHAR2(8 CHAR));
COMMENT ON COLUMN sicas_oc.cotizaciones.CODOFICINA IS 'Código de oficina comercial';
/
ALTER TABLE sicas_oc.cotizaciones ADD (CODUSUARIOMOD VARCHAR2(30 CHAR) DEFAULT USER);
COMMENT ON COLUMN sicas_oc.cotizaciones.CODUSUARIOMOD IS 'Código de usuario que modifica el registro';
/
ALTER TABLE sicas_oc.cotizaciones ADD (FECULTIMAMOD date DEFAULT SYSDATE);
COMMENT ON COLUMN sicas_oc.cotizaciones.FECULTIMAMOD IS 'fecha de ultima modificación del registro';
/
ALTER TABLE sicas_oc.cotizaciones ADD (CODCATEGO VARCHAR2(100 CHAR));
COMMENT ON COLUMN sicas_oc.cotizaciones.CODCATEGO IS 'Código de catégoria';
/
CREATE INDEX SICAS_OC.IDX_COTIZACIONES_CODPAQCOMERCI ON SICAS_OC.COTIZACIONES
(CODCIA, CODEMPRESA, CODPAQCOMERCIAL)
LOGGING
NOPARALLEL
/
CREATE INDEX SICAS_OC.IDX_COTIZACIONES_CODTIPONEGOC ON SICAS_OC.COTIZACIONES
(CODCIA, CODEMPRESA, CODTIPONEGOCIO)
LOGGING
NOPARALLEL
/

