DROP TABLE TIPOS_ESTANDARES_SERVICIO CASCADE CONSTRAINTS
/

--
-- TIPOS_ESTANDARES_SERVICIO  (Table) 
--
CREATE TABLE TIPOS_ESTANDARES_SERVICIO
(
  CODCIA        NUMBER,
  CODEMPRESA    NUMBER,
  CODFLUJO      VARCHAR2(5 BYTE),
  IDTIPOSEG     VARCHAR2(6 BYTE),
  PLANCOB       VARCHAR2(15 BYTE),
  CODTRAMITE    VARCHAR2(5 BYTE),
  CODSOLICITUD  VARCHAR2(100 BYTE),
  NUMDIASATN    NUMBER                          DEFAULT 0,
  INDDIAS       VARCHAR2(1 BYTE)
)
/


--
-- TIPOS_ESTANDARES_SERVICIO_PK  (Index) 
--
CREATE UNIQUE INDEX TIPOS_ESTANDARES_SERVICIO_PK ON TIPOS_ESTANDARES_SERVICIO
(CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
CODTRAMITE, CODSOLICITUD)
/


--
-- TIPOS_ESTANDARES_SERVICIO  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM TIPOS_ESTANDARES_SERVICIO FOR TIPOS_ESTANDARES_SERVICIO
/


GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TIPOS_ESTANDARES_SERVICIO TO PUBLIC
/

Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP-N', 'DEVUELTO', 30, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP-N', 'COMPLEMENTARIA', 30, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP-N', 'INICIAL', 30, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP-N', 'ACLARACION', 30, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, '1', '654654', '654', 
    '65446', '654654', 654, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, '1', 'VIFLEX', 'MAESTRO', 
    'tipo', 'ii', 15, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'VD', 'COMPLEMENTARIA', 6, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'F', NULL, NULL, 
    'F1', 'INICIAL', 2, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'GM', 'INICIAL', 5, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'C', NULL, NULL, 
    'NE', 'INICIAL', 20, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'VD', 'INICIAL', 10, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'MT', 'INICIAR', 10, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP', 'ACLARACIÓN', 5, 'H');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    '%', 'INICIAR', 10, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', 'ESTACA', 'ESTRELLA ESC A', 
    'AP', 'ACLARACIÓN', 10, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', NULL, NULL, 
    'AP', 'COMPLEMENTARIA', 1, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', 'PREMEX', 'PAQUETE 03', 
    'VD', 'INICIAL', 5, 'N');
Insert into TIPOS_ESTANDARES_SERVICIO
   (CODCIA, CODEMPRESA, CODFLUJO, IDTIPOSEG, PLANCOB, 
    CODTRAMITE, CODSOLICITUD, NUMDIASATN, INDDIAS)
 Values
   (1, 1, 'S', 'GM0001', 'GMM00001', 
    'GM', 'INICIAL', 3, 'H');
COMMIT;

/