ALTER TABLE FACTOR_GUA ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_GUA ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_GUA.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_GUA.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE FACTOR_ESCALA_PO ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_ESCALA_PO ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_ESCALA_PO.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_ESCALA_PO.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE FACTOR_NIVEL_HOSPITALARIO ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_NIVEL_HOSPITALARIO ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_NIVEL_HOSPITALARIO.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_NIVEL_HOSPITALARIO.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE FACTOR_PADEC_ESPECIAL ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_PADEC_ESPECIAL ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_PADEC_ESPECIAL.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_PADEC_ESPECIAL.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE CLAUSULAS_FACTORES ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE CLAUSULAS_FACTORES ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN CLAUSULAS_FACTORES.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN CLAUSULAS_FACTORES.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE FACTOR_EQUIPOS_REPRESENTA ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_EQUIPOS_REPRESENTA ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_EQUIPOS_REPRESENTA.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_EQUIPOS_REPRESENTA.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE FACTOR_REGION ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE FACTOR_REGION ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN FACTOR_REGION.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN FACTOR_REGION.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE COTIZADOR_GPO_COBERT_WEB ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE COTIZADOR_GPO_COBERT_WEB ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN COTIZADOR_GPO_COBERT_WEB.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN COTIZADOR_GPO_COBERT_WEB.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE COTIZADOR_COBERT_WEB ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE COTIZADOR_COBERT_WEB ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN COTIZADOR_COBERT_WEB.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN COTIZADOR_COBERT_WEB.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE COTIZACIONES_GPO_COBERT_WEB ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE COTIZACIONES_GPO_COBERT_WEB ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN COTIZACIONES_GPO_COBERT_WEB.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN COTIZACIONES_GPO_COBERT_WEB.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE COTIZACIONES_COBERT_WEB ADD (ACTUALIZO_USUARIO VARCHAR2(30 CHAR) DEFAULT USER);
/
ALTER TABLE COTIZACIONES_COBERT_WEB ADD (ACTUALIZO_FECHA DATE DEFAULT sysdate);
/
COMMENT ON COLUMN COTIZACIONES_COBERT_WEB.ACTUALIZO_FECHA IS 'Fecha en que se incrementa o se alteró el registro';
/
COMMENT ON COLUMN COTIZACIONES_COBERT_WEB.ACTUALIZO_USUARIO IS 'Usuario que incrementa o altera el registro';
/
ALTER TABLE COTIZADOR_COBERT_WEB DROP CONSTRAINT COTIZADOR_COBERT_WEB_PK
/
ALTER TABLE COTIZADOR_COBERT_WEB ADD CONSTRAINT COTIZADOR_COBERT_WE_PK PRIMARY KEY (CODCOBERTWEB, CODGPOCOBERTWEB, PLANCOB, IDTIPOSEG, CODCOTIZADOR, CODEMPRESA, CODCIA)  ENABLE  VALIDATE
/
CREATE INDEX COT_GPO_COB_WEB_IDX ON COTIZACIONES_GPO_COBERT_WEB
(CODCIA, CODEMPRESA, IDCOTIZACION)
TABLESPACE IDX_SICASOC
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/





