ALTER TABLE CRITERIOS_VAL_SINI
 DROP PRIMARY KEY CASCADE
/

DROP TABLE CRITERIOS_VAL_SINI CASCADE CONSTRAINTS
/

--
-- CRITERIOS_VAL_SINI  (Table) 
--
CREATE TABLE CRITERIOS_VAL_SINI
(
  IDVALCRITERIO     NUMBER(14)                  NOT NULL,
  IDCRITERIO        NUMBER(14)                  NOT NULL,
  VALOR             VARCHAR2(50 BYTE)           NOT NULL,
  DESCRIPCION       VARCHAR2(300 BYTE),
  IDROL             NUMBER(14)                  NOT NULL,
  STSVALCRITERIO    VARCHAR2(3 BYTE)            NOT NULL,
  CODCIA            NUMBER(14)                  NOT NULL,
  CODEMPRESA        NUMBER(14)                  NOT NULL,
  FECINIVIG         DATE,
  FECFINVIG         DATE,
  FECREGISTRO       DATE                        NOT NULL,
  USERREGISTRO      VARCHAR2(30 BYTE)           NOT NULL,
  FECULTACTUALIZA   DATE,
  USERULTACTUALIZA  VARCHAR2(30 BYTE)
)
/

COMMENT ON TABLE CRITERIOS_VAL_SINI IS 'Valores de Criterios para Rol validos para el Siniestro'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.IDVALCRITERIO IS 'Identificador unico del Valor del Criterio'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.IDCRITERIO IS 'Identificador unico del Criterio'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.VALOR IS 'Valor del Criterio'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.DESCRIPCION IS 'Descripcion del Valor del Criterio'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.STSVALCRITERIO IS 'Estado del Valor del Criterio Activo (ACT), Inactivo (INA)'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.CODCIA IS 'Codigo de Compañia'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.CODEMPRESA IS 'Codigo de Empresa'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.FECINIVIG IS 'Fecha de Inicio de Vigencia'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.FECFINVIG IS 'Fecha de Fin de Vigencia'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.FECREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.USERREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.FECULTACTUALIZA IS 'Fecha de ultima actualizacion del registro'
/

COMMENT ON COLUMN CRITERIOS_VAL_SINI.USERULTACTUALIZA IS 'Usuario que actualizo por ultima ve el registro'
/



--
-- PK_CRITERIOS_VAL_SINI  (Index) 
--
CREATE UNIQUE INDEX PK_CRITERIOS_VAL_SINI ON CRITERIOS_VAL_SINI
(IDVALCRITERIO, IDCRITERIO, VALOR)
/


--
-- CRITERIOS_VAL_SINI  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CRITERIOS_VAL_SINI FOR CRITERIOS_VAL_SINI
/


-- 
-- Non Foreign Key Constraints for Table CRITERIOS_VAL_SINI 
-- 
ALTER TABLE CRITERIOS_VAL_SINI ADD (
  CONSTRAINT PK_CRITERIOS_VAL_SINI
  PRIMARY KEY
  (IDVALCRITERIO, IDCRITERIO, VALOR)
  USING INDEX PK_CRITERIOS_VAL_SINI
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table CRITERIOS_VAL_SINI 
-- 
ALTER TABLE CRITERIOS_VAL_SINI ADD (
  CONSTRAINT FK_CRITVALSINI 
  FOREIGN KEY (IDCRITERIO) 
  REFERENCES CRITERIOS_SINI (IDCRITERIO)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON CRITERIOS_VAL_SINI TO PUBLIC
/

Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (42, 42, '%', NULL, 42, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('06/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (122, 1, '1058', 'DAFI', 122, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('07/11/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, '1055', 'UNAM', 5, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('03/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (3, 1, '1058', 'FEMEXFUT AMATEUR', 5, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (4, 2, '8777776', 'TELEVISORA DEL YAQUI', 5, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (5, 2, '8777676', 'TELEVISION DEL PACIFICO', 5, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (7, 3, '38478', 'TELEVISA SA DE CV', 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (8, 3, '40749', 'TELEVISA TALENTO', 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (9, 3, '39667', 'TELEVISA CORPORACION', 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (10, 3, '39741', 'TELEVISA PRODUCCIONES', 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (13, 4, 'APCO19', NULL, 1, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (14, 4, 'APIN19', NULL, 1, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (15, 4, 'BMIVIDA', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (16, 4, 'ESTACA', NULL, 1, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (17, 4, 'GMINDI', NULL, 3, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (18, 4, 'GM0001', NULL, 3, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (19, 4, 'GMINDC', NULL, 3, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (20, 4, 'PPAQI', NULL, 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (21, 4, 'PPAQC', NULL, 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (22, 4, 'PPAQ1', NULL, 4, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (23, 4, 'VG2017', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (24, 4, 'VIFLEX', NULL, 6, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (25, 4, 'VIDXN', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (26, 4, 'VGD17', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (27, 4, 'VI2019', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (28, 4, 'VG2020', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
Insert into CRITERIOS_VAL_SINI
   (IDVALCRITERIO, IDCRITERIO, VALOR, DESCRIPCION, IDROL, 
    STSVALCRITERIO, CODCIA, CODEMPRESA, FECINIVIG, FECFINVIG, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (29, 4, 'VITULM', NULL, 2, 
    'ACT', 1, 1, NULL, NULL, 
    TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', NULL, NULL);
COMMIT;
