ALTER TABLE SICAS_OC.FACTOR_GUA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_GUA CASCADE CONSTRAINTS
/

--
-- FACTOR_GUA  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_GUA
(
  CODCIA      NUMBER(14)                        NOT NULL,
  CODEMPRESA  NUMBER(14)                        NOT NULL,
  IDTIPOSEG   VARCHAR2(6 CHAR)                  NOT NULL,
  PLANCOB     VARCHAR2(15 CHAR)                 NOT NULL,
  CODCOBERT   VARCHAR2(7 CHAR)                  NOT NULL,
  NIVEL       VARCHAR2(8 CHAR)                  NOT NULL,
  FACTOR      NUMBER(9,6),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE
)
/

COMMENT ON TABLE SICAS_OC.FACTOR_GUA IS 'Factor Para El Gasto Usual Acostumbrado'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.NIVEL IS 'Nivel'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_GUA.FACTOR IS 'Factor'
/



--
-- FACTOR_GUA_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_GUA_PK ON SICAS_OC.FACTOR_GUA
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, 
NIVEL)
/


--
-- FACTOR_GUA  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_GUA FOR SICAS_OC.FACTOR_GUA
/


--
-- FACTOR_GUA  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_GUA FOR SICAS_OC.FACTOR_GUA
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_GUA 
-- 
ALTER TABLE SICAS_OC.FACTOR_GUA ADD (
  CONSTRAINT FACTOR_GUA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, NIVEL)
  USING INDEX SICAS_OC.FACTOR_GUA_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_GUA TO PUBLIC
/
ALTER TABLE SICAS_OC.FACTOR_ESCALA_PO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_ESCALA_PO CASCADE CONSTRAINTS
/

--
-- FACTOR_ESCALA_PO  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_ESCALA_PO
(
  CODCIA      NUMBER(14)                        NOT NULL,
  CODEMPRESA  NUMBER(14)                        NOT NULL,
  IDTIPOSEG   VARCHAR2(6 CHAR)                  NOT NULL,
  PLANCOB     VARCHAR2(15 CHAR)                 NOT NULL,
  CODCOBERT   VARCHAR2(7 CHAR)                  NOT NULL,
  ESCALA      VARCHAR2(1 CHAR)                  NOT NULL,
  FACTOR      NUMBER(9,7),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE
)
/

COMMENT ON TABLE SICAS_OC.FACTOR_ESCALA_PO IS 'Factor Para El Gasto Usual Acostumbrado'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.ESCALA IS 'Escala de Perdida Orgánica'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_ESCALA_PO.FACTOR IS 'Factor'
/



--
-- FACTOR_ESCALA_PO_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_ESCALA_PO_PK ON SICAS_OC.FACTOR_ESCALA_PO
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, 
ESCALA)
/


--
-- FACTOR_ESCALA_PO  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_ESCALA_PO FOR SICAS_OC.FACTOR_ESCALA_PO
/


--
-- FACTOR_ESCALA_PO  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_ESCALA_PO FOR SICAS_OC.FACTOR_ESCALA_PO
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_ESCALA_PO 
-- 
ALTER TABLE SICAS_OC.FACTOR_ESCALA_PO ADD (
  CONSTRAINT FACTOR_ESCALA_PO_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, ESCALA)
  USING INDEX SICAS_OC.FACTOR_ESCALA_PO_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_ESCALA_PO TO PUBLIC
/
ALTER TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO CASCADE CONSTRAINTS
/

--
-- FACTOR_NIVEL_HOSPITALARIO  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
(
  CODCIA       NUMBER(14)                       NOT NULL,
  CODEMPRESA   NUMBER(14)                       NOT NULL,
  IDTIPOSEG    VARCHAR2(6 CHAR)                 NOT NULL,
  PLANCOB      VARCHAR2(15 CHAR)                NOT NULL,
  CODCOBERT    VARCHAR2(7 CHAR)                 NOT NULL,
  CODENDOSO    VARCHAR2(10 CHAR)                NOT NULL,
  INDINCLUIDO  VARCHAR2(1 CHAR)                 NOT NULL,
  FACTOR       NUMBER(9,6)                      NOT NULL,
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO IS 'Factor para el Nivel Hospitalario'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.CODENDOSO IS 'Código de Endoso'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.INDINCLUIDO IS 'Indicador de Incluido'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_NIVEL_HOSPITALARIO.FACTOR IS 'Factor'
/



--
-- FACTOR_NIVEL_HOSPITALARIO_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_NIVEL_HOSPITALARIO_PK ON SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, 
CODENDOSO)
/


--
-- FACTOR_NIVEL_HOSPITALARIO  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_NIVEL_HOSPITALARIO FOR SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
/


--
-- FACTOR_NIVEL_HOSPITALARIO  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_NIVEL_HOSPITALARIO FOR SICAS_OC.FACTOR_NIVEL_HOSPITALARIO
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_NIVEL_HOSPITALARIO 
-- 
ALTER TABLE SICAS_OC.FACTOR_NIVEL_HOSPITALARIO ADD (
  CONSTRAINT FACTOR_NIVEL_HOSPITALARIO_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, CODENDOSO)
  USING INDEX SICAS_OC.FACTOR_NIVEL_HOSPITALARIO_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_NIVEL_HOSPITALARIO TO PUBLIC
/
ALTER TABLE SICAS_OC.FACTOR_PADEC_ESPECIAL
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_PADEC_ESPECIAL CASCADE CONSTRAINTS
/

--
-- FACTOR_PADEC_ESPECIAL  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_PADEC_ESPECIAL
(
  CODCIA       NUMBER(14)                       NOT NULL,
  CODEMPRESA   NUMBER(14)                       NOT NULL,
  IDTIPOSEG    VARCHAR2(6 CHAR)                 NOT NULL,
  PLANCOB      VARCHAR2(15 CHAR)                NOT NULL,
  CODCOBERT    VARCHAR2(7 CHAR)                 NOT NULL,
  CODENDOSO    VARCHAR2(10 CHAR)                NOT NULL,
  INDINCLUIDO  VARCHAR2(1 CHAR)                 NOT NULL,
  FACTOR       NUMBER(9,6)                      NOT NULL,
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.FACTOR_PADEC_ESPECIAL IS 'Factor para los Padecimientos Especiales'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.CODCOBERT IS 'Código de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.CODENDOSO IS 'Código de Endoso'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.INDINCLUIDO IS 'Indicador de Incluido'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_PADEC_ESPECIAL.FACTOR IS 'Factor'
/



--
-- FACTOR_PADEC_ESPECIAL_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_PADEC_ESPECIAL_PK ON SICAS_OC.FACTOR_PADEC_ESPECIAL
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, 
CODENDOSO)
/


--
-- FACTOR_PADEC_ESPECIAL  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_PADEC_ESPECIAL FOR SICAS_OC.FACTOR_PADEC_ESPECIAL
/


--
-- FACTOR_PADEC_ESPECIAL  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_PADEC_ESPECIAL FOR SICAS_OC.FACTOR_PADEC_ESPECIAL
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_PADEC_ESPECIAL 
-- 
ALTER TABLE SICAS_OC.FACTOR_PADEC_ESPECIAL ADD (
  CONSTRAINT FACTOR_PADEC_ESPECIAL_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODCOBERT, CODENDOSO)
  USING INDEX SICAS_OC.FACTOR_PADEC_ESPECIAL_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_PADEC_ESPECIAL TO PUBLIC
/
ALTER TABLE SICAS_OC.CLAUSULAS_FACTORES
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.CLAUSULAS_FACTORES CASCADE CONSTRAINTS
/

--
-- CLAUSULAS_FACTORES  (Table) 
--
CREATE TABLE SICAS_OC.CLAUSULAS_FACTORES
(
  TIPOFACTOR    VARCHAR2(6 CHAR)                NOT NULL,
  CODFACTOR     VARCHAR2(8 CHAR)                NOT NULL,
  CODCLAUSULA   VARCHAR2(6 CHAR)                NOT NULL,
  INDPRINCIPAL  VARCHAR2(1 CHAR)                NOT NULL,
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.CLAUSULAS_FACTORES IS 'Clausulas para los diferentes Tipos de Factores'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.TIPOFACTOR IS 'Tipo de Factor'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.CODFACTOR IS 'Código del Factor'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.CODCLAUSULA IS 'Código de la Clausula'
/

COMMENT ON COLUMN SICAS_OC.CLAUSULAS_FACTORES.INDPRINCIPAL IS 'Indicador de si es Clausula Principal'
/



--
-- CLAUSULAS_FACTORES_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.CLAUSULAS_FACTORES_PK ON SICAS_OC.CLAUSULAS_FACTORES
(TIPOFACTOR, CODFACTOR, CODCLAUSULA)
/


--
-- CLAUSULAS_FACTORES  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CLAUSULAS_FACTORES FOR SICAS_OC.CLAUSULAS_FACTORES
/


--
-- CLAUSULAS_FACTORES  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.CLAUSULAS_FACTORES FOR SICAS_OC.CLAUSULAS_FACTORES
/


-- 
-- Non Foreign Key Constraints for Table CLAUSULAS_FACTORES 
-- 
ALTER TABLE SICAS_OC.CLAUSULAS_FACTORES ADD (
  CONSTRAINT CLAUSULAS_FACTORES_PK
  PRIMARY KEY
  (TIPOFACTOR, CODFACTOR, CODCLAUSULA)
  USING INDEX SICAS_OC.CLAUSULAS_FACTORES_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.CLAUSULAS_FACTORES TO PUBLIC
/
ALTER TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA CASCADE CONSTRAINTS
/

--
-- FACTOR_EQUIPOS_REPRESENTA  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
(
  CODCIA       NUMBER(14)                       NOT NULL,
  CODEMPRESA   NUMBER(14)                       NOT NULL,
  IDTIPOSEG    VARCHAR2(6 CHAR)                 NOT NULL,
  PLANCOB      VARCHAR2(15 CHAR)                NOT NULL,
  CODPAQUETE   NUMBER(14)                       NOT NULL,
  CODEQUIPO    VARCHAR2(10 CHAR)                NOT NULL,
  INDINCLUIDO  VARCHAR2(1 CHAR)                 NOT NULL,
  FACTOR       NUMBER(9,6)                      NOT NULL,
  TEXTOFACTOR  VARCHAR2(4000 CHAR),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA IS 'Factor para los Equipos Representativos'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODPAQUETE IS 'Código del Paquete Comercial'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.CODEQUIPO IS 'Código del Equipo Representativo'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.INDINCLUIDO IS 'Indicador de Incluido'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.FACTOR IS 'Factor'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_EQUIPOS_REPRESENTA.TEXTOFACTOR IS 'Texto especial del factor'
/



--
-- FACTOR_EQUIPOS_REPRESENTA_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_EQUIPOS_REPRESENTA_PK ON SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, 
CODEQUIPO)
/


--
-- FACTOR_EQUIPOS_REPRESENTA  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_EQUIPOS_REPRESENTA FOR SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
/


--
-- FACTOR_EQUIPOS_REPRESENTA  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_EQUIPOS_REPRESENTA FOR SICAS_OC.FACTOR_EQUIPOS_REPRESENTA
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_EQUIPOS_REPRESENTA 
-- 
ALTER TABLE SICAS_OC.FACTOR_EQUIPOS_REPRESENTA ADD (
  CONSTRAINT FACTOR_EQUIPOS_REPRESENTA_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, CODEQUIPO)
  USING INDEX SICAS_OC.FACTOR_EQUIPOS_REPRESENTA_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_EQUIPOS_REPRESENTA TO PUBLIC
/
ALTER TABLE SICAS_OC.FACTOR_REGION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.FACTOR_REGION CASCADE CONSTRAINTS
/

--
-- FACTOR_REGION  (Table) 
--
CREATE TABLE SICAS_OC.FACTOR_REGION
(
  CODCIA       NUMBER(14)                       NOT NULL,
  CODEMPRESA   NUMBER(14)                       NOT NULL,
  IDTIPOSEG    VARCHAR2(6 CHAR)                 NOT NULL,
  PLANCOB      VARCHAR2(15 CHAR)                NOT NULL,
  CODPAQUETE   NUMBER(14)                       NOT NULL,
  CODREGION    VARCHAR2(6 CHAR)                 NOT NULL,
  FACTOR       NUMBER(9,6),
  TEXTOFACTOR  VARCHAR2(4000 CHAR),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.FACTOR_REGION IS 'Factor por Región'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODPAQUETE IS 'Código del Paquete Comercial'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.CODREGION IS 'Código de la Región'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.FACTOR IS 'Factor'
/

COMMENT ON COLUMN SICAS_OC.FACTOR_REGION.TEXTOFACTOR IS 'Texto Para Factor de la Región'
/



--
-- FACTOR_REGION_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.FACTOR_REGION_PK ON SICAS_OC.FACTOR_REGION
(CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, 
CODREGION)
/


--
-- FACTOR_REGION  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FACTOR_REGION FOR SICAS_OC.FACTOR_REGION
/


--
-- FACTOR_REGION  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.FACTOR_REGION FOR SICAS_OC.FACTOR_REGION
/


-- 
-- Non Foreign Key Constraints for Table FACTOR_REGION 
-- 
ALTER TABLE SICAS_OC.FACTOR_REGION ADD (
  CONSTRAINT FACTOR_REGION_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDTIPOSEG, PLANCOB, CODPAQUETE, CODREGION)
  USING INDEX SICAS_OC.FACTOR_REGION_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.FACTOR_REGION TO PUBLIC
/
ALTER TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB CASCADE CONSTRAINTS
/

--
-- COTIZADOR_GPO_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB
(
  CODCIA           NUMBER(14)                   NOT NULL,
  CODEMPRESA       NUMBER(14)                   NOT NULL,
  CODCOTIZADOR     VARCHAR2(30 CHAR)            NOT NULL,
  IDTIPOSEG        VARCHAR2(6 CHAR)             NOT NULL,
  PLANCOB          VARCHAR2(15 CHAR)            NOT NULL,
  CODGPOCOBERTWEB  VARCHAR2(6 CHAR)             NOT NULL,
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB IS 'Cotizador Grupo Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODCOTIZADOR IS 'Código del Cotizador'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_GPO_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/



--
-- COTIZADOR_GPO_COBERT_WEB_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.COTIZADOR_GPO_COBERT_WEB_PK ON SICAS_OC.COTIZADOR_GPO_COBERT_WEB
(CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, 
CODGPOCOBERTWEB)
/


--
-- COTIZADOR_GPO_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZADOR_GPO_COBERT_WEB FOR SICAS_OC.COTIZADOR_GPO_COBERT_WEB
/


--
-- COTIZADOR_GPO_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.COTIZADOR_GPO_COBERT_WEB FOR SICAS_OC.COTIZADOR_GPO_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZADOR_GPO_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_GPO_COBERT_WEB ADD (
  CONSTRAINT COTIZADOR_GPO_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, CODGPOCOBERTWEB)
  USING INDEX SICAS_OC.COTIZADOR_GPO_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZADOR_GPO_COBERT_WEB TO PUBLIC
/
ALTER TABLE SICAS_OC.COTIZADOR_COBERT_WEB
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.COTIZADOR_COBERT_WEB CASCADE CONSTRAINTS
/

--
-- COTIZADOR_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZADOR_COBERT_WEB
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  CODCOTIZADOR        VARCHAR2(30 CHAR)         NOT NULL,
  IDTIPOSEG           VARCHAR2(6 CHAR)          NOT NULL,
  PLANCOB             VARCHAR2(15 CHAR)         NOT NULL,
  CODGPOCOBERTWEB     VARCHAR2(6 CHAR)          NOT NULL,
  CODCOBERTWEB        VARCHAR2(6 CHAR)          NOT NULL,
  IDCOTIZACION        NUMBER(14)                NOT NULL,
  IDETCOTIZACION      NUMBER(14)                NOT NULL,
  SUMAASEGCOBLOCAL    NUMBER(28,2),
  SUMAASEGCOBMONEDA   NUMBER(28,2),
  TASA                NUMBER(18,6),
  PRIMACOBLOCAL       NUMBER(28,2),
  PRIMACOBMONEDA      NUMBER(28,2),
  DEDUCIBLECOBLOCAL   NUMBER(28,2),
  DEDUCIBLECOBMONEDA  NUMBER(28,2),
  SALARIOMENSUAL      NUMBER(28,2),
  VECESSALARIO        NUMBER(10),
  SUMAASEGCALCULADA   NUMBER(28,2),
  EDAD_MINIMA         NUMBER(3),
  EDAD_MAXIMA         NUMBER(3),
  EDAD_EXCLUSION      NUMBER(3),
  SUMAASEG_MINIMA     NUMBER(28,2),
  SUMAASEG_MAXIMA     NUMBER(28,2),
  PORCEXTRAPRIMADET   NUMBER(9,6),
  MONTOEXTRAPRIMADET  NUMBER(18,2),
  SUMAINGRESADA       NUMBER(28,2),
  ORDENIMPRESION      NUMBER(4),
  DEDUCIBLEINGRESADO  NUMBER(28,2),
  CUOTAPROMEDIO       NUMBER(18,6),
  PRIMAPROMEDIO       NUMBER(28,2),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.COTIZADOR_COBERT_WEB IS 'Cotizador Grupo Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCOTIZADOR IS 'Código del Cotizador'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDTIPOSEG IS 'Identificador del Tipo de Seguro'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PLANCOB IS 'Identificador del Plan de Coberturas'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CODCOBERTWEB IS 'Código de Cobertura Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDCOTIZACION IS 'No. de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.IDETCOTIZACION IS 'No. de Detalle de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCOBLOCAL IS 'Suma Asegurada Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCOBMONEDA IS 'Suma Asegurada Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.TASA IS 'Tasa de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMACOBLOCAL IS 'Prima Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMACOBMONEDA IS 'Prima Moneta de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLECOBLOCAL IS 'Deducible Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLECOBMONEDA IS 'Deducible Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SALARIOMENSUAL IS 'Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.VECESSALARIO IS 'Veces de Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEGCALCULADA IS 'Suma Asegurada Calculada'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_MINIMA IS 'Edad Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_MAXIMA IS 'Edad Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.EDAD_EXCLUSION IS 'Edad Exclusion de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEG_MINIMA IS 'Suma Asegurada Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAASEG_MAXIMA IS 'Suma Asegurada Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PORCEXTRAPRIMADET IS 'Porcentaje de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.MONTOEXTRAPRIMADET IS 'Monto de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.SUMAINGRESADA IS 'Suma Asegurada Ingresada por Usuario'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.ORDENIMPRESION IS 'Orden de Impresión de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.DEDUCIBLEINGRESADO IS 'Deducible Ingresado para Tarifa'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.CUOTAPROMEDIO IS 'Cuota Promedio de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZADOR_COBERT_WEB.PRIMAPROMEDIO IS 'Prima Promedio de Cobertura'
/



--
-- COTIZADOR_COBERT_WEB_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.COTIZADOR_COBERT_WEB_PK ON SICAS_OC.COTIZADOR_COBERT_WEB
(CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, 
CODGPOCOBERTWEB, CODCOBERTWEB, IDCOTIZACION, IDETCOTIZACION)
/


--
-- COTIZADOR_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZADOR_COBERT_WEB FOR SICAS_OC.COTIZADOR_COBERT_WEB
/


--
-- COTIZADOR_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.COTIZADOR_COBERT_WEB FOR SICAS_OC.COTIZADOR_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZADOR_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZADOR_COBERT_WEB ADD (
  CONSTRAINT COTIZADOR_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODCOTIZADOR, IDTIPOSEG, PLANCOB, CODGPOCOBERTWEB, CODCOBERTWEB, IDCOTIZACION, IDETCOTIZACION)
  USING INDEX SICAS_OC.COTIZADOR_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZADOR_COBERT_WEB TO PUBLIC
/
ALTER TABLE SICAS_OC.COTIZACIONES_GPO_COBERT_WEB
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.COTIZACIONES_GPO_COBERT_WEB CASCADE CONSTRAINTS
/

--
-- COTIZACIONES_GPO_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZACIONES_GPO_COBERT_WEB
(
  CODCIA           NUMBER(14)                   NOT NULL,
  CODEMPRESA       NUMBER(14)                   NOT NULL,
  IDCOTIZACION     NUMBER(14)                   NOT NULL,
  CODGPOCOBERTWEB  VARCHAR2(6 CHAR)             NOT NULL,
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE

)
/

COMMENT ON TABLE SICAS_OC.COTIZACIONES_GPO_COBERT_WEB IS 'Cotizaciones Grupo Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_GPO_COBERT_WEB.CODCIA IS 'Código de la Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_GPO_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_GPO_COBERT_WEB.IDCOTIZACION IS 'No. de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_GPO_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/



--
-- COTIZACIONES_GPO_COBERT_WEB_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.COTIZACIONES_GPO_COBERT_WEB_PK ON SICAS_OC.COTIZACIONES_GPO_COBERT_WEB
(CODCIA, CODEMPRESA, IDCOTIZACION, CODGPOCOBERTWEB)
/


--
-- COTIZACIONES_GPO_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZACIONES_GPO_COBERT_WEB FOR SICAS_OC.COTIZACIONES_GPO_COBERT_WEB
/


--
-- COTIZACIONES_GPO_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.COTIZACIONES_GPO_COBERT_WEB FOR SICAS_OC.COTIZACIONES_GPO_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZACIONES_GPO_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZACIONES_GPO_COBERT_WEB ADD (
  CONSTRAINT COTIZACIONES_GPO_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDCOTIZACION, CODGPOCOBERTWEB)
  USING INDEX SICAS_OC.COTIZACIONES_GPO_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZACIONES_GPO_COBERT_WEB TO PUBLIC
/
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_WEB
 DROP PRIMARY KEY CASCADE
/

DROP TABLE SICAS_OC.COTIZACIONES_COBERT_WEB CASCADE CONSTRAINTS
/

--
-- COTIZACIONES_COBERT_WEB  (Table) 
--
CREATE TABLE SICAS_OC.COTIZACIONES_COBERT_WEB
(
  CODCIA              NUMBER(14)                NOT NULL,
  CODEMPRESA          NUMBER(14)                NOT NULL,
  IDCOTIZACION        NUMBER(14)                NOT NULL,
  IDETCOTIZACION      NUMBER(14)                NOT NULL,
  CODGPOCOBERTWEB     VARCHAR2(6 CHAR)          NOT NULL,
  CODCOBERTWEB        VARCHAR2(6 CHAR)          NOT NULL,
  SUMAASEGCOBLOCAL    NUMBER(28,2),
  SUMAASEGCOBMONEDA   NUMBER(28,2),
  TASA                NUMBER(18,6),
  PRIMACOBLOCAL       NUMBER(28,2),
  PRIMACOBMONEDA      NUMBER(28,2),
  DEDUCIBLECOBLOCAL   NUMBER(28,2),
  DEDUCIBLECOBMONEDA  NUMBER(28,2),
  SALARIOMENSUAL      NUMBER(28,2),
  VECESSALARIO        NUMBER(10),
  SUMAASEGCALCULADA   NUMBER(28,2),
  EDAD_MINIMA         NUMBER(3),
  EDAD_MAXIMA         NUMBER(3),
  EDAD_EXCLUSION      NUMBER(3),
  SUMAASEG_MINIMA     NUMBER(28,2),
  SUMAASEG_MAXIMA     NUMBER(28,2),
  PORCEXTRAPRIMADET   NUMBER(9,6),
  MONTOEXTRAPRIMADET  NUMBER(18,2),
  SUMAINGRESADA       NUMBER(28,2),
  ORDENIMPRESION      NUMBER(4),
  DEDUCIBLEINGRESADO  NUMBER(28,2),
  CUOTAPROMEDIO       NUMBER(18,6),
  PRIMAPROMEDIO       NUMBER(28,2),
  ACTUALIZO_USUARIO VARCHAR2(30) DEFAULT USER,
  ACTUALIZO_FECHA   DATE DEFAULT SYSDATE
)
/

COMMENT ON TABLE SICAS_OC.COTIZACIONES_COBERT_WEB IS 'Cotizaciones Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.CODCIA IS 'Código del Compañía'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.CODEMPRESA IS 'Código de la Empresa'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.IDCOTIZACION IS 'No. de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.IDETCOTIZACION IS 'No. de Detalle de Cotización'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.CODGPOCOBERTWEB IS 'Código del Grupo de Coberturas Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.CODCOBERTWEB IS 'Código de Cobertura Web'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAASEGCOBLOCAL IS 'Suma Asegurada Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAASEGCOBMONEDA IS 'Suma Asegurada Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.TASA IS 'Tasa de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.PRIMACOBLOCAL IS 'Prima Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.PRIMACOBMONEDA IS 'Prima Moneta de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.DEDUCIBLECOBLOCAL IS 'Deducible Local de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.DEDUCIBLECOBMONEDA IS 'Deducible Moneda de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SALARIOMENSUAL IS 'Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.VECESSALARIO IS 'Veces de Salario de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAASEGCALCULADA IS 'Suma Asegurada Calculada'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.EDAD_MINIMA IS 'Edad Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.EDAD_MAXIMA IS 'Edad Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.EDAD_EXCLUSION IS 'Edad Exclusion de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAASEG_MINIMA IS 'Suma Asegurada Mínima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAASEG_MAXIMA IS 'Suma Asegurada Máxima de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.PORCEXTRAPRIMADET IS 'Porcentaje de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.MONTOEXTRAPRIMADET IS 'Monto de ExtraPrima para Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.SUMAINGRESADA IS 'Suma Asegurada Ingresada por Usuario'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.ORDENIMPRESION IS 'Orden de Impresión de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.DEDUCIBLEINGRESADO IS 'Deducible Ingresado para Tarifa'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.CUOTAPROMEDIO IS 'Cuota Promedio de Cobertura'
/

COMMENT ON COLUMN SICAS_OC.COTIZACIONES_COBERT_WEB.PRIMAPROMEDIO IS 'Prima Promedio de Cobertura'
/



--
-- COTIZACIONES_COBERT_WEB_PK  (Index) 
--
CREATE UNIQUE INDEX SICAS_OC.COTIZACIONES_COBERT_WEB_PK ON SICAS_OC.COTIZACIONES_COBERT_WEB
(CODCIA, CODEMPRESA, IDCOTIZACION, IDETCOTIZACION, CODGPOCOBERTWEB, 
CODCOBERTWEB)
/


--
-- COTIZACIONES_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM COTIZACIONES_COBERT_WEB FOR SICAS_OC.COTIZACIONES_COBERT_WEB
/


--
-- COTIZACIONES_COBERT_WEB  (Synonym) 
--
CREATE OR REPLACE SYNONYM THONAPI.COTIZACIONES_COBERT_WEB FOR SICAS_OC.COTIZACIONES_COBERT_WEB
/


-- 
-- Non Foreign Key Constraints for Table COTIZACIONES_COBERT_WEB 
-- 
ALTER TABLE SICAS_OC.COTIZACIONES_COBERT_WEB ADD (
  CONSTRAINT COTIZACIONES_COBERT_WEB_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDCOTIZACION, IDETCOTIZACION, CODGPOCOBERTWEB, CODCOBERTWEB)
  USING INDEX SICAS_OC.COTIZACIONES_COBERT_WEB_PK
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON SICAS_OC.COTIZACIONES_COBERT_WEB TO PUBLIC
/

