CREATE INDEX SICAS_OC.DETALLE_FACTURAS_IDX_2 ON SICAS_OC.DETALLE_FACTURAS
(IDFACTURA)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.CATALOGO_DE_CONCEPTOS_IDX_2 ON SICAS_OC.CATALOGO_DE_CONCEPTOS
(CODCIA, CODCONCEPTO, INDCPTOFONDO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.CATALOGO_DE_CONCEPTOS_IDX_3 ON SICAS_OC.CATALOGO_DE_CONCEPTOS
(CODCIA, CODCONCEPTO, INDCPTOPRIMAS)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.DETALLE_TRANSACCION_IDX_4 ON SICAS_OC.DETALLE_TRANSACCION
(CODCIA, CODEMPRESA, IDTRANSACCION, OBJETO, CODSUBPROCESO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.FACTURAS_IDX_POLSTAT ON SICAS_OC.FACTURAS
(IDPOLIZA, STSFACT)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
ALTER TABLE SICAS_OC.TEMP_ARCHIVOS_THONA
ADD (FECHA DATE DEFAULT SYSDATE);
/
CREATE INDEX SICAS_OC.CTRL_PROC_AUTOMATIC_INDX ON SICAS_OC.CONTROL_PROCESOS_AUTOMATICOS
(ID_ENVIO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
GRANT SELECT, ALTER ON SICAS_OC.SQ_CONTROL_PROCESOS_AUTOMATI TO "PUBLIC";
/
CREATE PUBLIC SYNONYM SQ_CONTROL_PROCESOS_AUTOMATI FOR SICAS_OC.SQ_CONTROL_PROCESOS_AUTOMATI;
/
ALTER TABLE SICAS_OC.T_REPORTES_AUTOMATICOS
ADD (ID_ENVIO NUMBER);
/
CREATE INDEX SICAS_OC.T_REPORTES_AUTOMATICOS_IDX2 ON SICAS_OC.T_REPORTES_AUTOMATICOS
(CODCIA, CODEMPRESA, ID_ENVIO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.TEMP_ARCHIVOS_THONA_IDX2 ON SICAS_OC.TEMP_ARCHIVOS_THONA
(CODCIA, CODEMPRESA, ID_ENVIO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
ALTER TABLE SICAS_OC.T_REPORTES_AUTOMATICOS ADD 
CONSTRAINT T_REPORTES_AUTOMATICOS_PK
 PRIMARY KEY (CODCIA, CODEMPRESA, ID_ENVIO, NOMBRE_REPORTE, FECHA_PROCESO, NUMERO_REGISTRO)
 ENABLE
 VALIDATE
/ 
CREATE INDEX SICAS_OC.TRANSACCION_IDX1 ON SICAS_OC.TRANSACCION
(CODCIA, CODEMPRESA, FECHATRANSACCION, IDPROCESO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.FACTURAS_1 ON SICAS_OC.FACTURAS
(CODCIA, IDPOLIZA, IDTRANSACCION)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.FACTURAS_DXP_IDX ON SICAS_OC.FACTURAS
(CODCIA, STSFACT, INDCONTABILIZADA, IDTRANSACCION, IDTRANSACCONTAB)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
