ALTER TABLE SICAS_OC.TIPOS_DE_SEGUROS ADD (INDMULTIRAMO CHAR(1 CHAR) CHECK (INDMULTIRAMO in ('S', 'N', NULL)));
/
COMMENT ON COLUMN SICAS_OC.TIPOS_DE_SEGUROS.INDMULTIRAMO IS 'Indicador si este tipo de seguro es multiramo';
/
