ALTER TABLE FACT_ELECT_DETALLE_TIMBRE ADD (SAT_CODRESPUESTAOPC VARCHAR2(100));
ALTER TABLE FACT_ELECT_DETALLE_TIMBRE ADD (SAT_DESRESPUESTAOPC VARCHAR2(300 CHAR));
ALTER TABLE FACT_ELECT_DETALLE_TIMBRE ADD (SAT_FECRESPUESTAOPC DATE);
/
COMMENT ON COLUMN FACT_ELECT_DETALLE_TIMBRE.SAT_CODRESPUESTAOPC IS 'Codigo del estatus respuesta SAT segun envío de la CVE_MOTIVCANCFAC';
COMMENT ON COLUMN FACT_ELECT_DETALLE_TIMBRE.SAT_DESRESPUESTAOPC IS 'Descripción del estatus respuesta SAT segun envío de la CVE_MOTIVCANCFAC';
COMMENT ON COLUMN FACT_ELECT_DETALLE_TIMBRE.SAT_FECRESPUESTAOPC IS 'Fecha del estatus respuesta SAT segun envío de la CVE_MOTIVCANCFAC';
/
CREATE INDEX IDX_SAT_CODRESPUESTAOPC ON FACT_ELECT_DETALLE_TIMBRE
(SAT_CODRESPUESTAOPC)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX IDX_SAT_FECRESPUESTAOPC ON FACT_ELECT_DETALLE_TIMBRE
(SAT_FECRESPUESTAOPC)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX IDX_UUIDCANCELADO ON FACT_ELECT_DETALLE_TIMBRE
(UUIDCANCELADO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX IDX_UUIDRELACIONADO ON FACT_ELECT_DETALLE_TIMBRE
(UUIDRELACIONADO)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX IDX_UUID ON FACT_ELECT_DETALLE_TIMBRE
(UUID)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/

