ALTER TABLE TIPOS_SOLICITUD DROP PRIMARY KEY CASCADE
/
DROP TABLE TIPOS_SOLICITUD CASCADE CONSTRAINTS
/
CREATE TABLE TIPOS_SOLICITUD
(
  CODCIA       NUMBER,
  CODEMPRESA   NUMBER,
  CODFLUJO     VARCHAR2(5 BYTE),
  CODTRAMITE   VARCHAR2(5 BYTE),
  CODSOLICITUD VARCHAR2(100 BYTE)
)
/
CREATE UNIQUE INDEX TIPOS_SOLICITUD_PK ON TIPOS_SOLICITUD
(CODCIA, CODEMPRESA, CODFLUJO, CODTRAMITE, CODSOLICITUD)
/
CREATE OR REPLACE PUBLIC SYNONYM TIPOS_SOLICITUD FOR TIPOS_SOLICITUD
/
ALTER TABLE TIPOS_SOLICITUD ADD (
  CONSTRAINT TIPOS_SOLICITUD_PK
  PRIMARY KEY (CODCIA, CODEMPRESA, CODFLUJO, CODTRAMITE, CODSOLICITUD)
  USING INDEX TIPOS_SOLICITUD_PK
  ENABLE VALIDATE)
/  
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON TIPOS_SOLICITUD TO PUBLIC
/
