ALTER TABLE CRITERIOS_SINI
 DROP PRIMARY KEY CASCADE
/

DROP TABLE CRITERIOS_SINI CASCADE CONSTRAINTS
/

--
-- CRITERIOS_SINI  (Table) 
--
CREATE TABLE CRITERIOS_SINI
(
  IDCRITERIO        NUMBER(14)                  NOT NULL,
  DESCCRITERIO      VARCHAR2(50 BYTE)           NOT NULL,
  ORDEN             NUMBER(5)                   NOT NULL,
  STSCRITERIO       VARCHAR2(3 BYTE)            NOT NULL,
  CODCIA            NUMBER(14)                  NOT NULL,
  CODEMPRESA        NUMBER(14)                  NOT NULL,
  FECINIVIG         DATE,
  FECFINVIG         DATE,
  FECREGISTRO       DATE                        NOT NULL,
  USERREGISTRO      VARCHAR2(30 BYTE)           NOT NULL,
  FECULTACTUALIZA   DATE,
  USERULTACTUALIZA  VARCHAR2(30 BYTE)
)
/

COMMENT ON TABLE CRITERIOS_SINI IS 'Criterios para Rol validos para el Siniestro'
/

COMMENT ON COLUMN CRITERIOS_SINI.IDCRITERIO IS 'Identificador unico del Criterio'
/

COMMENT ON COLUMN CRITERIOS_SINI.DESCCRITERIO IS 'Descripcion del Criterio'
/

COMMENT ON COLUMN CRITERIOS_SINI.ORDEN IS 'Numero de Orden o Prioridad del Criterio'
/

COMMENT ON COLUMN CRITERIOS_SINI.STSCRITERIO IS 'Estado del Criterio Activo (ACT), Inactivo (INA)'
/

COMMENT ON COLUMN CRITERIOS_SINI.CODCIA IS 'Codigo de Compañia'
/

COMMENT ON COLUMN CRITERIOS_SINI.CODEMPRESA IS 'Codigo de Empresa'
/

COMMENT ON COLUMN CRITERIOS_SINI.FECINIVIG IS 'Fecha de Inicio de Vigencia'
/

COMMENT ON COLUMN CRITERIOS_SINI.FECFINVIG IS 'Fecha de Fin de Vigencia'
/

COMMENT ON COLUMN CRITERIOS_SINI.FECREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN CRITERIOS_SINI.USERREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN CRITERIOS_SINI.FECULTACTUALIZA IS 'Fecha de ultima actualizacion del registro'
/

COMMENT ON COLUMN CRITERIOS_SINI.USERULTACTUALIZA IS 'Usuario que actualizo por ultima ve el registro'
/



--
-- IDX_CRITERIO_SINI  (Index) 
--
CREATE UNIQUE INDEX IDX_CRITERIO_SINI ON CRITERIOS_SINI
(IDCRITERIO, DESCCRITERIO)
/


--
-- PK_CRITERIOS_SINI  (Index) 
--
CREATE UNIQUE INDEX PK_CRITERIOS_SINI ON CRITERIOS_SINI
(IDCRITERIO)
/


--
-- CRITERIOS_SINI  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM CRITERIOS_SINI FOR CRITERIOS_SINI
/


-- 
-- Non Foreign Key Constraints for Table CRITERIOS_SINI 
-- 
ALTER TABLE CRITERIOS_SINI ADD (
  CONSTRAINT PK_CRITERIOS_SINI
  PRIMARY KEY
  (IDCRITERIO)
  USING INDEX PK_CRITERIOS_SINI
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON CRITERIOS_SINI TO PUBLIC
/

Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (42, 'Otro criterio', 6, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('06/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 'Agrupador', 1, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    TO_DATE('03/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (2, 'Contratante', 2, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (3, 'Póliza', 3, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (4, 'Tipo de Seguro', 5, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into CRITERIOS_SINI
   (IDCRITERIO, DESCCRITERIO, ORDEN, STSCRITERIO, CODCIA, 
    CODEMPRESA, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (5, 'Agente', 4, 'ACT', 1, 
    1, NULL, NULL, TO_DATE('03/22/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
COMMIT;
