CREATE INDEX SICAS_OC.IDX_FACTURAS_FECSTATUS ON SICAS_OC.FACTURAS
(FECSTS, STSFACT)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.IDX_FACTURAS_FECPAGO ON SICAS_OC.FACTURAS
(FECPAGO, STSFACT)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
CREATE INDEX SICAS_OC.IDX_FACTURAS_IndFactFEC ON SICAS_OC.FACTURAS
(FECSTS, INDFACTELECTRONICA)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
