ALTER TABLE DIAS_ATENCION_SINI
 DROP PRIMARY KEY CASCADE
/

DROP TABLE DIAS_ATENCION_SINI CASCADE CONSTRAINTS
/

--
-- DIAS_ATENCION_SINI  (Table) 
--
CREATE TABLE DIAS_ATENCION_SINI
(
  CODCIA            NUMBER(14)                  NOT NULL,
  CODEMPRESA        NUMBER(14)                  NOT NULL,
  IDPOLIZA          NUMBER(14)                  NOT NULL,
  CODFLUJO          VARCHAR2(5 BYTE),
  CODTRAMITE        VARCHAR2(5 BYTE),
  CODSOLICITUD      VARCHAR2(100 BYTE),
  NUMDIASATN        NUMBER(14),
  INDDIAS           VARCHAR2(1 BYTE)            NOT NULL,
  IDDIASATN         NUMBER(14)                  NOT NULL,
  NUMPOLUNICO       VARCHAR2(30 BYTE),
  CODAGRUPADOR      VARCHAR2(6 BYTE),
  CODCLIENTE        NUMBER(14)                  NOT NULL,
  NOMCLIENTE        VARCHAR2(300 BYTE),
  CODAGENTE         VARCHAR2(10 BYTE),
  OBSERVACIONES     VARCHAR2(2000 BYTE),
  STSATENCION       VARCHAR2(3 BYTE)            NOT NULL,
  FECINIVIG         DATE,
  FECFINVIG         DATE,
  FECREGISTRO       DATE                        NOT NULL,
  USERREGISTRO      VARCHAR2(30 BYTE)           NOT NULL,
  FECULTACTUALIZA   DATE,
  USERULTACTUALIZA  VARCHAR2(30 BYTE)
)
/

COMMENT ON TABLE DIAS_ATENCION_SINI IS 'Numero de dias de atencion garantizadospara atender el Siniestro'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODCIA IS 'Codigo de Compañia'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODEMPRESA IS 'Codigo de Empresa'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.IDPOLIZA IS 'Numero de Poliza al que aplican los dias de garantia'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODSOLICITUD IS 'Tipo de Siniestro'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.NUMDIASATN IS 'Numero de dias compromiso de atencion garantizada del Siniestro'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.INDDIAS IS 'Indicador del tipo de dias Habiles (H), Naturales (N)'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.IDDIASATN IS 'Identificador unico de dias de atencion'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.NUMPOLUNICO IS 'Numero de Poliza Unico'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODAGRUPADOR IS 'Codigo del Agrupador'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODCLIENTE IS 'Codigo del Cliente contratante'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.NOMCLIENTE IS 'Nombre del Cliente contratante'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.CODAGENTE IS 'Codigo del Agente'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.OBSERVACIONES IS 'Consecutivo de la Poliza'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.STSATENCION IS 'Estado de los dias de Atencion Activo (ACT), Caducado (CAD)'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.FECINIVIG IS 'Fecha de Inicio de Vigencia'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.FECFINVIG IS 'Fecha de Fin de Vigencia'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.FECREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.USERREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.FECULTACTUALIZA IS 'Fecha de ultima actualizacion del registro'
/

COMMENT ON COLUMN DIAS_ATENCION_SINI.USERULTACTUALIZA IS 'Usuario que actualizo por ultima ve el registro'
/



--
-- PK_DIAS_ATN_SINI  (Index) 
--
CREATE UNIQUE INDEX PK_DIAS_ATN_SINI ON DIAS_ATENCION_SINI
(CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
CODSOLICITUD)
/


--
-- DIAS_ATENCION_SINI  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM DIAS_ATENCION_SINI FOR DIAS_ATENCION_SINI
/


-- 
-- Non Foreign Key Constraints for Table DIAS_ATENCION_SINI 
-- 
ALTER TABLE DIAS_ATENCION_SINI ADD (
  CONSTRAINT PK_DIAS_ATN_SINI
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, CODSOLICITUD)
  USING INDEX PK_DIAS_ATN_SINI
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON DIAS_ATENCION_SINI TO PUBLIC
/

Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25699, 'S', 'AP', 
    'INICIAL', 12, 'H', 59, 'AG-25699-00', 
    '1000', 538446, 'ALIMENTO PARA TODOS, IAP', '212', NULL, 
    'ACT', TO_DATE('01/03/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/04/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/10/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25701, 'S', 'AP', 
    'INICIAL', 12, 'H', 60, 'AG-22479-00', 
    '1000', 3150316, 'CONSEJO DE PROMOCION TURISTICA DE MEXICO, S.A. DE C.V.', '918', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/10/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25710, 'S', 'AP', 
    'INICIAL', 12, 'H', 77, 'VG-22447-01', 
    '1000', 3117765, 'FERROCARRIL DEL ISTMO DE TEHUANTEPEC, S.A. DE C.V.', '99', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/28/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/10/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25735, 'S', 'AP', 
    'INICIAL', 12, 'H', 78, 'MONF01-00', 
    '1000', 3775186, 'MONTOLIN MEXICO, S.A. DE C.V.', '351', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/10/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 32421, 'S', 'AP', 
    'INICIAL', 7, 'H', 79, '32421-00', 
    '1000', 7297973, 'MEDDISOFT S.A.P.I. DE C.V.', '3278', NULL, 
    'ACT', TO_DATE('07/13/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/13/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 32861, 'S', 'AP', 
    'INICIAL', 10, 'H', 80, '27240-01', 
    '1060', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('08/05/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/05/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 32862, 'S', 'AP', 
    'INICIAL', 10, 'H', 81, '27241-01', 
    '1060', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('08/05/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/05/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33016, 'S', 'AP', 
    'INICIAL', 10, 'H', 82, '33016-00', 
    '1060', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('08/05/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/05/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33173, 'S', 'AP', 
    'INICIAL', 7, 'H', 83, '33173-00', 
    '1000', 7297973, 'MEDDISOFT S.A.P.I. DE C.V.', '3278', NULL, 
    'ACT', TO_DATE('08/25/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/25/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33237, 'S', 'AP', 
    'INICIAL', 10, 'H', 84, 'AG-27128-01', 
    '1059', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('07/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33239, 'S', 'AP', 
    'INICIAL', 10, 'H', 85, 'VG-27129-01', 
    '1059', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('07/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/21/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33412, 'S', 'AP', 
    'INICIAL', 7, 'H', 86, '33412-00', 
    '1000', 7297973, 'MEDDISOFT S.A.P.I. DE C.V.', '3278', NULL, 
    'ACT', TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33602, 'S', 'AP', 
    'INICIAL', 10, 'H', 87, '33602-00', 
    '1061', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33674, 'S', 'AP', 
    'INICIAL', 10, 'H', 88, '33674-00', 
    '1062', 95, 'FEDERACION MEXICANA DE FUTBOL ASOCIACION, A.C.', '3119', NULL, 
    'ACT', TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/10/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 36014, 'S', 'AP', 
    'INICIAL', 7, 'H', 89, '36014-00', 
    '1000', 7297973, 'MEDDISOFT S.A.P.I. DE C.V.', '3278', NULL, 
    'ACT', TO_DATE('02/22/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/22/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 38668, 'S', 'AP', 
    'INICIAL', 7, 'H', 90, '38668-00', 
    '1000', 7297973, 'MEDDISOFT S.A.P.I. DE C.V.', '3278', NULL, 
    'ACT', TO_DATE('04/09/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/09/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25859, 'S', 'AP', 
    'INICIAL', 90, 'H', 121, '14065-02', 
    '1001', 4523061, 'ASOC DE PADRES DE FAM. URBANA 185 VENUSTIANO LLAMAS QUEVEDO T/M 14EPR0127E', '280', NULL, 
    'ACT', TO_DATE('01/23/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/19/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/29/2022 13:22:32', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25660, 'S', 'AP', 
    'INICIAL', 10, 'N', 101, '6343-08', 
    '1000', 719575, 'UNIVERSIDAD POLITECNICA METROPOLITANA DE HIDALGO', '155', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/31/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/22/2022 11:38:10', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    TO_DATE('03/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25703, 'S', 'AP', 
    'INICIAL', 8, 'H', 102, 'VG-23144-01', 
    '1000', 3613393, 'COMISION NACIONAL BANCARIA Y DE VALORES', '99', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/15/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/22/2022 11:38:10', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25706, 'S', 'AP', 
    'INICIAL', 30, 'H', 91, 'VG-22502-01', 
    '1000', 3117765, 'FERROCARRIL DEL ISTMO DE TEHUANTEPEC, S.A. DE C.V.', '99', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/28/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 15:08:37', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 25694, 'S', 'AP', 
    'INICIAL', 5, 'N', 92, '17466-03', 
    '1064', 553, 'COLEGIO DE BACHILLERES DE CHIAPAS', '99', NULL, 
    'ACT', TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/15/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/17/2022 15:15:58', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 41691, 'S', 'AP', 
    'INICIAL', 22, 'H', 141, '41691-01', 
    '1000', 8845303, 'MARIANA DE LEON GONZALEZ', '179', NULL, 
    'ACT', TO_DATE('04/20/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/20/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/28/2022 15:29:23', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    NULL, NULL);
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 41625, 'F', 'F1', 
    'INICIAL', 7, 'N', 164, '41625-00', 
    '1000', 8845303, 'MARIANA DE LEON GONZALEZ', '179', NULL, 
    'ACT', TO_DATE('02/03/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/03/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/04/2022 15:32:32', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    TO_DATE('07/04/2022 15:32:32', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 33455, 'S', 'VD', 
    'INICIAL', 10, 'N', 166, '33227-00', 
    '1000', 7349595, 'TESORERIA MUNICIPAL DE TORREÓN', '3028', NULL, 
    'ACT', TO_DATE('08/30/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/06/2022 16:07:55', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    TO_DATE('07/06/2022 16:07:55', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into DIAS_ATENCION_SINI
   (CODCIA, CODEMPRESA, IDPOLIZA, CODFLUJO, CODTRAMITE, 
    CODSOLICITUD, NUMDIASATN, INDDIAS, IDDIASATN, NUMPOLUNICO, 
    CODAGRUPADOR, CODCLIENTE, NOMCLIENTE, CODAGENTE, OBSERVACIONES, 
    STSATENCION, FECINIVIG, FECFINVIG, FECREGISTRO, USERREGISTRO, 
    FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 41675, 'S', 'VD', 
    'COMPLEMENTARIA', 9, 'N', 165, '41675-00', 
    '1000', 8845303, 'MARIANA DE LEON GONZALEZ', '179', NULL, 
    'ACT', TO_DATE('03/26/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/26/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/04/2022 16:16:18', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', 
    TO_DATE('07/04/2022 16:16:18', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
COMMIT;
/