ALTER TABLE TIPOS_TRAMITE
 DROP PRIMARY KEY CASCADE
/

DROP TABLE TIPOS_TRAMITE CASCADE CONSTRAINTS
/

--
-- TIPOS_TRAMITE  (Table) 
--
CREATE TABLE TIPOS_TRAMITE
(
  IDTRAMITE         NUMBER(14)                  NOT NULL,
  IDFLUJO           NUMBER(14)                  NOT NULL,
  CODCIA            NUMBER(14)                  NOT NULL,
  CODEMPRESA        NUMBER(14)                  NOT NULL,
  CODFLUJO          VARCHAR2(5 BYTE)            NOT NULL,
  CODTRAMITE        VARCHAR2(5 BYTE)            NOT NULL,
  NOMTRAMITE        VARCHAR2(300 BYTE),
  STSTIPTRAM        VARCHAR2(5 BYTE)            NOT NULL,
  NUMDIASATN        NUMBER                      DEFAULT 0,
  INDDIAS           VARCHAR2(1 BYTE),
  FECREGISTRO       DATE                        NOT NULL,
  USERREGISTRO      VARCHAR2(30 BYTE)           NOT NULL,
  FECULTACTUALIZA   DATE,
  USERULTACTUALIZA  VARCHAR2(30 BYTE)
)
/

COMMENT ON TABLE TIPOS_TRAMITE IS 'Tipos de Tramite validos para Flujos de Operacion'
/

COMMENT ON COLUMN TIPOS_TRAMITE.IDTRAMITE IS 'Identificador del Tramite'
/

COMMENT ON COLUMN TIPOS_TRAMITE.CODCIA IS 'Codigo de Compañia'
/

COMMENT ON COLUMN TIPOS_TRAMITE.CODEMPRESA IS 'Codigo de Empresa'
/

COMMENT ON COLUMN TIPOS_TRAMITE.CODFLUJO IS 'Abreviatura que identifica al Flujo'
/

COMMENT ON COLUMN TIPOS_TRAMITE.CODTRAMITE IS 'Abreviatura que identifica al Tipo de Tramite o Ramo'
/

COMMENT ON COLUMN TIPOS_TRAMITE.NOMTRAMITE IS 'Nombre del Tramite o Ramo'
/

COMMENT ON COLUMN TIPOS_TRAMITE.STSTIPTRAM IS 'Estado del Tipo de Tramite ACT Activo, INA Inactivo'
/

COMMENT ON COLUMN TIPOS_TRAMITE.NUMDIASATN IS 'Nuúmero de dias para atención'
/

COMMENT ON COLUMN TIPOS_TRAMITE.INDDIAS IS 'Inicador sin son días Naturales o días Hábiles'
/

COMMENT ON COLUMN TIPOS_TRAMITE.FECREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN TIPOS_TRAMITE.USERREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN TIPOS_TRAMITE.FECULTACTUALIZA IS 'Fecha de ultima actualizacion del registro'
/

COMMENT ON COLUMN TIPOS_TRAMITE.USERULTACTUALIZA IS 'Usuario que actualizo por ultima ve el registro'
/



--
-- TIPOS_TRAMITE_PK  (Index) 
--
CREATE UNIQUE INDEX TIPOS_TRAMITE_PK ON TIPOS_TRAMITE
(CODCIA, CODEMPRESA, CODFLUJO, CODTRAMITE)
/


--
-- TIPOS_TRAMITE  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM TIPOS_TRAMITE FOR TIPOS_TRAMITE
/


-- 
-- Non Foreign Key Constraints for Table TIPOS_TRAMITE 
-- 
ALTER TABLE TIPOS_TRAMITE ADD (
  CONSTRAINT TIPOS_TRAMITE_PK
  PRIMARY KEY
  (CODCIA, CODEMPRESA, CODFLUJO, CODTRAMITE)
  USING INDEX TIPOS_TRAMITE_PK
  ENABLE VALIDATE)
/

-- 
-- Foreign Key Constraints for Table TIPOS_TRAMITE 
-- 
ALTER TABLE TIPOS_TRAMITE ADD (
  CONSTRAINT FK_TIPO_TRAMITE 
  FOREIGN KEY (CODCIA, CODEMPRESA, CODFLUJO) 
  REFERENCES FLUJOS_OPERACION (CODCIA,CODEMPRESA,CODFLUJO)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE ON TIPOS_TRAMITE TO PUBLIC
/

Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (328, 1, 1, 1, 'S', 
    'AP-N', 'Accidentes Personales', 'ACT', 30, 'H', 
    TO_DATE('10/05/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ', TO_DATE('10/05/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (122, 82, 1, 1, 'F', 
    'F1', 'Otro Tramite', 'ACT', 5, 'H', 
    TO_DATE('06/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 1, 'S', 
    'AP', 'Accidentes Personales', 'INA', 30, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('10/05/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (2, 1, 1, 1, 'S', 
    'GM', 'Gastos Medicos', 'ACT', 0, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('09/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (3, 1, 1, 1, 'S', 
    'VD', 'Vida', 'ACT', 25, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('09/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (4, 1, 1, 1, 'S', 
    'MT', 'Multiramo', 'INA', 8, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('09/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'IPEREZ');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (5, 2, 1, 1, 'C', 
    'AP', 'Accidentes Personales', 'ACT', 0, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (6, 2, 1, 1, 'C', 
    'CL', 'Cuentas por Licitaciones', 'ACT', 0, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (7, 2, 1, 1, 'C', 
    'DN', 'Descuento por Nómina', 'ACT', 1, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (8, 2, 1, 1, 'C', 
    'NE', 'Negocio Especial', 'ACT', 10, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (9, 2, 1, 1, 'C', 
    'VG', 'Vida Grupo', 'ACT', 1, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (10, 2, 1, 1, 'C', 
    'VI', 'Vida Individual', 'ACT', 1, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (11, 3, 1, 1, 'E', 
    'AP', 'Accidentes Personales', 'ACT', 1, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (12, 3, 1, 1, 'E', 
    'GM', 'Gastos Medicos Mayores', 'ACT', 2, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (13, 3, 1, 1, 'E', 
    'MD', 'Modificación', 'ACT', 3, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (14, 3, 1, 1, 'E', 
    'VD', 'Vida', 'ACT', 4, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (15, 4, 1, 1, 'B', 
    'AP', 'Aplicación de Pagos', 'ACT', 4, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (16, 4, 1, 1, 'B', 
    'DV', 'Devoluciones', 'ACT', 8, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (17, 4, 1, 1, 'B', 
    'FE', 'Fact. Texto / Cond. Especiales', 'ACT', 6, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (18, 4, 1, 1, 'B', 
    'OT', 'Otro', 'ACT', 5, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (19, 4, 1, 1, 'B', 
    'FR', 'Reexpedición de Facturas', 'ACT', 4, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (20, 5, 1, 1, 'A', 
    'AD', 'Actualización de Documentos', 'ACT', 14, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (21, 5, 1, 1, 'A', 
    'AA', 'Alta Agente Promotor', 'ACT', 3, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (22, 5, 1, 1, 'A', 
    'EF', 'Envío de Facturas Fiscales', 'ACT', 3, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (23, 5, 1, 1, 'A', 
    'PC', 'Pago de Comisiones', 'ACT', 4, 'H', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
Insert into TIPOS_TRAMITE
   (IDTRAMITE, IDFLUJO, CODCIA, CODEMPRESA, CODFLUJO, 
    CODTRAMITE, NOMTRAMITE, STSTIPTRAM, NUMDIASATN, INDDIAS, 
    FECREGISTRO, USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (24, 5, 1, 1, 'A', 
    'RA', 'Reasignar Agente/Cartera', 'ACT', 5, 'N', 
    TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC', TO_DATE('06/30/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'SICAS_OC');
COMMIT;
/