ALTER TABLE FLUJOS_FOLIOS
 DROP PRIMARY KEY CASCADE
/

DROP TABLE FLUJOS_FOLIOS CASCADE CONSTRAINTS
/

--
-- FLUJOS_FOLIOS  (Table) 
--
CREATE TABLE FLUJOS_FOLIOS
(
  CODCIA            NUMBER(1)                   NOT NULL,
  CODEMPRESA        NUMBER(1)                   NOT NULL,
  IDFLUJO           NUMBER(14)                  NOT NULL,
  CODFLUJO          VARCHAR2(6 BYTE)            NOT NULL,
  IDTRAMITE         NUMBER(14)                  NOT NULL,
  CODTRAMITE        VARCHAR2(5 BYTE)            NOT NULL,
  CONSECFOLIO       VARCHAR2(30 BYTE),
  FECINIVIG         DATE,
  FECFINVIG         DATE,
  FECREGISTRO       DATE                        NOT NULL,
  USERREGISTRO      VARCHAR2(30 BYTE)           NOT NULL,
  FECULTACTUALIZA   DATE,
  USERULTACTUALIZA  VARCHAR2(30 BYTE)
)
/

COMMENT ON TABLE FLUJOS_FOLIOS IS 'Folios por tipo de Flujo y Trámite de operacion'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.CODCIA IS 'Codigo de Compañia'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.CODEMPRESA IS 'Codigo de Empresa'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.IDFLUJO IS 'Identificador del Flujo de Operacion'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.CODFLUJO IS 'Codigo del Flujo de Operacion'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.IDTRAMITE IS 'Identificdor del Tipo de Trámite o Ramo'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.CODTRAMITE IS 'Codigo del Tipo de Trámite o Ramo'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.CONSECFOLIO IS 'Consecutivo del Folio '
/

COMMENT ON COLUMN FLUJOS_FOLIOS.FECINIVIG IS 'Fecha de Inicio de Vigencia'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.FECFINVIG IS 'Fecha de Fin de Vigencia'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.FECREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.USERREGISTRO IS 'Fecha de registro o alta del Usuario en esta tabla'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.FECULTACTUALIZA IS 'Fecha de ultima actualizacion del registro'
/

COMMENT ON COLUMN FLUJOS_FOLIOS.USERULTACTUALIZA IS 'Usuario que actualizo por ultima ve el registro'
/



--
-- PK_FLUJO_FOLIOS  (Index) 
--
CREATE UNIQUE INDEX PK_FLUJO_FOLIOS ON FLUJOS_FOLIOS
(CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
CODTRAMITE, FECINIVIG, FECFINVIG)
/


--
-- FLUJOS_FOLIOS  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM FLUJOS_FOLIOS FOR FLUJOS_FOLIOS
/


-- 
-- Non Foreign Key Constraints for Table FLUJOS_FOLIOS 
-- 
ALTER TABLE FLUJOS_FOLIOS ADD (
  CONSTRAINT PK_FLUJO_FOLIOS
  PRIMARY KEY
  (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, CODTRAMITE, FECINIVIG, FECFINVIG)
  USING INDEX PK_FLUJO_FOLIOS
  ENABLE VALIDATE)
/

GRANT DELETE, INSERT, SELECT, UPDATE ON FLUJOS_FOLIOS TO PUBLIC
/

Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 3, 
    'VD', '172', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/24/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'THONAPI', TO_DATE('10/06/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'THONAPI');
Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 328, 
    'AP-N', '1', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('10/05/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'THONAPI', NULL, NULL);
Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 1, 
    'AP', '295', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SICAS_OC', TO_DATE('09/09/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'THONAPI');
Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 2, 
    'GM', '215', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SICAS_OC', TO_DATE('10/07/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'THONAPI');
Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 4, 
    'MT', '16', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/23/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'SICAS_OC', TO_DATE('06/27/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'THONAPI');
Insert into FLUJOS_FOLIOS
   (CODCIA, CODEMPRESA, IDFLUJO, CODFLUJO, IDTRAMITE, 
    CODTRAMITE, CONSECFOLIO, FECINIVIG, FECFINVIG, FECREGISTRO, 
    USERREGISTRO, FECULTACTUALIZA, USERULTACTUALIZA)
 Values
   (1, 1, 1, 'S', 1, 
    'AP-N', '2', TO_DATE('01/01/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'THONAPI', TO_DATE('09/29/2022 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'THONAPI');
COMMIT;
