CREATE INDEX FACT_ELECT_REPORTE_PORTAL_IDX ON SICAS_OC.FACT_ELECT_REPORTE_PORTAL
(CODCIA, RFC, IDPOLIZA, IDETPOL)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
