REM INSERTING into FACTOR_PADEC_ESPECIAL
SET DEFINE OFF;
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','PAD001','S',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','PAD002','N',1.15);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','PAD001','S',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','PAD002','N',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','PAD001','S',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','PAD002','N',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','PAD001','S',1);
Insert into FACTOR_PADEC_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','PAD002','N',1.15);
commit;
