REM INSERTING into ENTREGAS_CNSF_PLANTILLA
SET DEFINE OFF;
--
--Datos Generales Accidentes Personales Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','MONEDA',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','ENTASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','INIVIG',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FINVIG',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FECALT',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FECBAJ',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FECNAC',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FECEMI',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','SEXO',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','STSCER',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','FORVTA',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','SUBSEG',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','TIPDIV',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','ANOPOL',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','OCUPAC',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','TIPRIE',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','NUMASE',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','PRICED',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','COMDIR',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPC','SESADATAPC','MTODIV',23,'S');
--
--Emisión Accidentes Personales Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','PERESP',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','SUMASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','PRIEMI',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','PRIDEV',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','NUMDIA',8,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPC','SESAEMIAPC','ORDSES',9,'S');
--

--Siniestros Accidentes Personales Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','NUMREC',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','STSSIN',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','ENTOCU',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','COBERT',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','FECNAC',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','SEXO',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','CAUSIN',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','TIPMOV',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MTOREC',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MTODED',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MTOCOA',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MTOPAG',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MTOREA',20,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','ORDSES',21,'S');
--
--Datos Generales Accidentes Personales Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','MONEDA',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','ENTASE',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','INIVIG',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FINVIG',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FECALT',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FECBAJ',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FECNAC',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FECEMI',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','SEXO',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','STSCER',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','FORVTA',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','SUBSEG',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','TIPDIV',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','ANOPOL',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','OCUPAC',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','TIPRIE',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','PRICED',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','COMDIR',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATAPI','SESADATAPI','MTODIV',21,'S');
--
--Emisión Accidentes Personales Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','PERESP',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','SUMASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','PRIEMI',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','PRIDEV',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','NUMDIA',8,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIAPI','SESAEMIAPI','ORDSES',9,'S');
--

--Siniestros Accidentes Personales Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','NUMREC',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','STSSIN',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','ENTOCU',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','COBERT',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','CAUSIN',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','TIPMOV',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MTOREC',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MTODED',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MTOCOA',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MTOPAG',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MTOREA',18,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','ORDSES',19,'S');
--
--Datos Generales Gastos Médicos Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','MONEDA',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','ENTASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','INIVIG',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FINVIG',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FECALT',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FECBAJ',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FECNAC',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FECEMI',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','SEXO',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','STSCER',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','FORVTA',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','SUBSEG',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','ANOPOL',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','MODSUM',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','COASEG',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','TIPDIV',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','MTODIV',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','PRICED',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMC','SESADATGMC','COMDIR',22,'S');
--
--Emisión Gastos Médicos Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','SUMASE',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','PRIEMI',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','PRIDEV',6,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMC','SESAEMIGMC','ORDSES',7,'S');
--

--Siniestros Gastos Médicos Colectivo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','NUMREC',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','STSSIN',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','ENTOCU',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','TIPGAS',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','PERESP',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','CAUSIN',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','TIPPAG',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','SEXO',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','FECNAC',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MTOREC',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MTODED',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MTOCOA',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MTOPAG',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MTOREA',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','TIPMOV',22,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','ORDSES',23,'S');
--
--Datos Generales Gastos Médicos Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','MONEDA',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','ENTASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','INIVIG',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FINVIG',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FECALT',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FECBAJ',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FECNAC',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FECEMI',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','SEXO',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','STSCER',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','FORVTA',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','SUBSEG',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','ANOPOL',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','MODSUM',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','COASEG',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','PRICED',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATGMI','SESADATGMI','COMDIR',20,'S');
--
--Emisión Gastos Médicos Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','SUMASE',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','PRIEMI',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','PRIDEV',6,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIGMI','SESAEMIGMI','ORDSES',7,'S');
--

--Siniestros Gastos Médicos Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','NUMREC',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','STSSIN',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','ENTOCU',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','TIPGAS',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','PERESP',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','CAUSIN',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','TIPPAG',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','SEXO',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','FECNAC',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MTOREC',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MTODED',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MTOCOA',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MTOPAG',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MTOREA',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','TIPMOV',22,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','ORDSES',23,'S');
--
--Datos Generales Vida Grupo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','PLANPO',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','MODPOL',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','MONEDA',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','ENTASE',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','INIVIG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FINVIG',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FECALT',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FECBAJ',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FECNAC',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FECEMI',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','SEXO',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FORVTA',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','STSCER',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','TIPDIV',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','FORPAG',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','PLAPAG',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','COASEG',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','EMISIO',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','NUMCER',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','PRICED',23,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','COMDIR',24,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','SLFOIN',25,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','SLFOAD',26,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','MTODIV',27,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVIG','SESADATVIG','MTORES',28,'S');
--
--Emisión Vida Grupo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','TIPSUM',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','SUMASE',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','PRIEMI',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','PERESP',7,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVIG','SESAEMIVIG','ORDSES',8,'S');
--

--Siniestros Vida Grupo
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','COBERT',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','ENTOCU',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','STSSIN',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','CAUSIN',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','SEXO',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','FECNAC',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTOREC',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTOVEN',15,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTORES',14,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTODIV',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTOPAG',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','MTOREA',17,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVIG','SESASINVIG','ORDSES',18,'S');
--
--Datos Generales Vida Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','PLANPO',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','MODPOL',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','MONEDA',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','ENTASE',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','INIVIG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FINVIG',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FECALT',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FECBAJ',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FECNAC',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FECEMI',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','SEXO',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FORVTA',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','STSCER',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','TIPDIV',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','FORPAG',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','PLAPAG',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','COASEG',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','EMISIO',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','PRICED',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','COMDIR',23,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','SLFOIN',24,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','SLFOAD',25,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','MTODIV',26,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESADATVII','SESADATVII','MTORES',27,'S');
--
--Emisión Vida Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','COBERT',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','TIPSUM',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','TIPEXT',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','SUMASE',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','PRIEMI',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','PERESP',8,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVII','SESAEMIVII','ORDSES',9,'S');
--
--Siniestros Vida Individual
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','CERTIF',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','NUMSIN',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','COBERT',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','FECOCU',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','FECREP',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','FECCON',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','FECPAG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','ENTOCU',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','STSSIN',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','CAUSIN',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','MTOREC',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','MTOVEN',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','MTOPAG',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','MTOREA',15,'S');
--Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINVII','SESASINVII','ORDSES',16,'S');
--
--Emisión Vida Grupo Fonacot
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','POLIZA',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','CERTI',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','TIPSEG',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','MODALI',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PLANPO',5,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','MONEDA',6,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','ENTCTE',7,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','INIVIG',8,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','FINVIG',9,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','FECALT',10,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','FECBAJ',11,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','FECNAC',12,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SEXO',13,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','FORVTA',14,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','POLSTS',15,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','CERSTS',16,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PDOESP',17,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN1',18,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN2',19,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN3',20,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN4',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN6',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN8',23,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SABEN9',24,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM1',25,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM2',26,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM3',27,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM4',28,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM5',29,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM6',30,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM7',31,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM8',32,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PMAEM9',33,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SLFOAD',34,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','MTOVEN',35,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','MTORES',36,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','TIPDIV',37,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','MTODIV',38,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SUBSEG',39,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','EMISIO',40,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','ANOPOL',41,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','INICOB',42,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SADOTA',43,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PRIDOT',44,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PLAPAG',45,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','TIRGAS',46,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','SLFOIN',47,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','POLCON',48,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','ASEPOC',49,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAEMIVG-FONACOT','SESAEMIVGF','PCOMA',50,'S');
--
--LOG DE ERRORES

Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAERROR','SESAERROR','EPOLIZ',1,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAERROR','SESAERROR','ECERTI',2,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAERROR','SESAERROR','CODERR',3,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAERROR','SESAERROR','DESCER',4,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESAERROR','SESAERROR','FECREG',4,'S');
COMMIT;