REM INSERTING into TIPO_DE_LISTA
SET DEFINE OFF;
--
--Relación Contratante
Insert into TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('RELCONTR','RELACION CONTRATANTES','USR');
--
--Detalle de Relaciones
Insert into VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('RELCONTR','PATEMP','Patrón-Empleado');
Insert into VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('RELCONTR','ASOASO','Asociación-Asociado');
Insert into VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('RELCONTR','EMPCLI','Empresa-Cliente');
Insert into VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('RELCONTR','ESCALU','Escuela-Alumnos');
