REM INSERTING into FACTOR_REGION
SET DEFINE OFF;
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26470,'REG001',1,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26470,'REG002',2.9105,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26470,'REG003',1.643478,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26470,'REG004',1.643478,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26471,'REG001',1,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26471,'REG002',2.9105,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26471,'REG003',1.643478,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26471,'REG004',1.643478,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26472,'REG001',1,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26472,'REG002',2.9105,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26472,'REG003',1.643478,null);
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',26472,'REG004',1.643478,null);
/*Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6708,'REG001',1,'Texto REG001');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6708,'REG002',2.9105,'Texto REG002');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6708,'REG003',1.643478,'Texto REG003');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6708,'REG004',1.643478,'Texto REG004');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6709,'REG001',1,'Texto REG001');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6709,'REG002',2.9105,'Texto REG002');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6709,'REG003',1.643478,'Texto REG003');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6709,'REG004',1.643478,'Texto REG004');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6710,'REG001',1,'Texto REG001');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6710,'REG002',2.9105,'Texto REG002');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6710,'REG003',1.643478,'Texto REG003');
Insert into FACTOR_REGION (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODPAQUETE,CODREGION,FACTOR,TEXTOFACTOR) values (1,1,'ESTACA','MAESTRO',6710,'REG004',1.643478,'Texto REG004');*/
commit;
