REM INSERTING into FACTOR_GUA
SET DEFINE OFF;
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','GUA 100%',1);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','GUA 125%',1.12);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','GUA 150%',1.2);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','GUA 200%',1.3);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','GUA 100%',1);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','GUA 125%',1.12);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','GUA 150%',1.2);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','GUA 200%',1.3);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','GUA 100%',1);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','GUA 125%',1.12);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','GUA 150%',1.2);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','GUA 200%',1.3);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','GUA 100%',1);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','GUA 125%',1.12);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','GUA 150%',1.2);
Insert into FACTOR_GUA (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,NIVEL,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','GUA 200%',1.3);
commit;
