INSERT INTO SICAS_OC.TIPO_DE_LISTA
VALUES ('REGIONFACT', 'REGIONES PARA APLICACION DE FACTORES', 'USR');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('REGIONFACT', 'REG001', 'REGION: RESTO DE LA REPUBLICA');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('REGIONFACT', 'REG002', 'REGION: COAHUILA');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('REGIONFACT', 'REG003', 'REGION: PUEBLA');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('REGIONFACT', 'REG004', 'REGION: TLAXCALA');
/
COMMIT;
/
