REM INSERTING into TIPO_DE_LISTA
SET DEFINE OFF;
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATAPC','SESAS DE DATOS GENERALES APC','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIAPC','SESAS DE EMISION AP COLECTIVO','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINAPC','SESAS DE SINIESTROS AP COLECTIVO','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATAPI','SESAS DE DATOS GENERALES API','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIAPI','SESAS DE EMISION AP INDIVIDUAL','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINAPI','SESAS DE SINIESTROS AP INDIVIDUAL','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATGMC','SESAS DE DATOS GENERALES GMC','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIGMC','SESAS DE EMISION GM COLECTIVO','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINGMC','SESAS DE SINIESTROS GM COLECTIVO','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATGMI','SESAS DE DATOS GENERALES GMI','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIGMI','SESAS DE EMISION GM INDIVIDUAL','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINGMI','SESAS DE SINIESTROS GM INDIVIDUAL','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATVIG','SESAS DE DATOS GENERALES VIG','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIVIG','SESAS DE EMISION VIDA GRUPO','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINVIG','SESAS DE SINIESTROS VIDA GRUPO','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEDATVII','SESAS DE DATOS GENERALES VII','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIVII','SESAS DE EMISION VIDA INDIVIDUAL','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESINVII','SESAS DE SINIESTROS VIDA INDIVIDUAL','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEMIVGF','SESAS DE EMISION VG INFONACOT','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SEEQUCAM','SESAS EQUIVALENCIA CAMPOS','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS239','COBERTURAS SESAS RAMOS 011 Y 012','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS92','COBERTURAS SESAS RAMOS 031 Y 033','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS255','COBERTURAS SESAS RAMOS 034 Y 036','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS237','PLAN DE POLIZA CON CATALOGO 237','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS240','TIPO DE SEGURO CON CATALOGO 240','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS250','TIPO DE SEGURO CON CATALOGO 250','USR');
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS254','TIPO DE SEGURO CON CATALOGO 254','USR');
--
Insert into SICAS_OC.TIPO_DE_LISTA (CODLISTA,DESCLISTA,TIPO_LISTA) values ('SESAS258','TIPO DE PAGO PARA GMM CATALOGO 258','USR');
--
COMMIT;