REM INSERTING into CLAUSULAS_FACTORES
SET DEFINE OFF;
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('NIVHOS','NIV001','NIV001','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('NIVHOS','NIV002','NIV002','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('PADESP','PAD001','PAD001','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('PADESP','PAD002','PAD002','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('GUA','GUA 100%','GUA001','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('GUA','GUA 125%','GUA002','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('GUA','GUA 150%','GUA003','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('GUA','GUA 200%','GUA004','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('EQUREP','EQU001','EQU001','S');
Insert into CLAUSULAS_FACTORES (TIPOFACTOR,CODFACTOR,CODCLAUSULA,INDPRINCIPAL) values ('EQUREP','EQU002','EQU002','S');
commit;
