INSERT INTO VALORES_DE_LISTAS
                (CODLISTA, CODVALOR,DESCVALLST, CVE_CNSF, DESC_CNSF)
         VALUES ('MTOENDAU', '032', 'ENDOSO A DECLARACION POR INCREMENTO', NULL, NULL);
/
INSERT INTO VALORES_DE_LISTAS
                (CODLISTA, CODVALOR,DESCVALLST, CVE_CNSF, DESC_CNSF)
         VALUES ('MTOENDAU', '033', 'ENDOSO A DECLARACION POR DECREMENTO', NULL, NULL);
		 
/