/*ACTUALIZACIÓN DE ACTIVIDADES ECONOMICAS DE ALTO RIESGO*/

    UPDATE SICAS_OC.ACTIVIDADES_ECONOMICAS 
    SET TIPORIESGO='ALTO' 
    WHERE CODACTIVIDAD IN (
    'ADCENCON','ADMUEB','ADACC','ADQVEHI','AGEAUTO',
    'ADMINCOMER','AHORRPRES','AHORROPR','ALQUIMUEBL',
    'ALQOF','ALQDEOTROS','AUTOM','AUTOTRANS','AUTTRA',
    'AUTFORACAR','AUTFORMATE','CAAHO','CAJPRES','PREYEMP',
    'COMERINMUE','COMROPA','COMERMADES','COMGAS','CONSTRUCC',
    'CONSTRUC','CONSNAV','CONSTVIVIE','OBRPES','CONST',
    'CONCAAU','FINANCRED','DESC','DINVALORE','ECOT',
    'AHORRO','FABPARTAUT','FABREFAUT','FABJOYERIA',
    'INDUSMINER','INMO','JUEGAZAR','MAQPARTEAE','MINCOB',
    'PRESPETROD','PRODENJOYE','RENDEP','SEGUPRI','SERVMAR',
    'FERROCARRI','SERFER','INMOBILIA','ALQUIOFICI','ALQOFCO',
    'AUTOMO','AUTT','ALQOFIC','CONS INMUE','AUTOFORMAT',
    'CONINCO','DINY VAL','SEGUPRIVA'
    );

COMMIT;

/*ACTUALIZACIÓN DE PAISES DE ALTO RIESGO*/

UPDATE SICAS_OC.PAIS
SET TIPORIESGO = 'ALTO'
WHERE CODPAIS IN (047,100,165);

UPDATE SICAS_OC.PAIS
SET TIPORIESGO = 'BAJO'
WHERE CODPAIS NOT IN (047,100,165);

COMMIT;

UPDATE SICAS_OC.DISTRITO
SET TIPORIESGO='ALTO'
WHERE CODESTADO IN ('024','025','029','032','008');

UPDATE SICAS_OC.PROVINCIA
SET TIPORIESGO='ALTO'
WHERE CODESTADO IN ('024','025','029','032','008');

COMMIT;

INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES('EMAILOPPRE','OFICIH','oficialcumplimiento2@thonaseguros.mx,lreynoso@thonaseguros.mx',NULL,NULL);
COMMIT;

INSERT INTO SICAS_OC.PARAMETROS_GLOBALES VALUES (1,'PLI','00:00:00','Hora de inicio en la que puede ejecutarse el proceso historico');
        INSERT INTO SICAS_OC.PARAMETROS_GLOBALES VALUES (1,'PLF','23:59:59','Hora de Finalizacion en la que debe detenerse el proceso historico');
COMMIT;

INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('JOSE DE JESUS ESTRADA GUTIERREZ','','COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO DE JALISCO','01-2024','OFAC','24 HRS','SE REPORTÓ A JOSE DE JESUS ESTRADA GUTIERREZ, CONTRATANTE:COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO DE JALISCO, ENERO 2024, POR COINCIDENCIA EN OFAC, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('MOISES GONZALEZ ANGUIANO','','CAJA POPULAR ATEMAJAC SC DE AP DE RL DE CV','02-2024','OFAC','24 HRS','SE REPORTÓ A MOISES GONZALEZ ANGUIANO, CONTRATANTE:CAJA POPULAR ATEMAJAC SC DE AP DE RL DE CV, FEBRERO 2024, POR COINCIDENCIA EN OFAC, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('ABDHIEL JOSUE GARCIA VELAZCO','','FEDERACION MEXICANA DE FUTBOL ASOCIACION AC','03-2024','OFAC','24 HRS','SE REPORTÓ A ABDHIEL JOSUE GARCIA VELAZCO, CONTRATANTE:FEDERACION MEXICANA DE FUTBOL ASOCIACION AC, MARZO 2024, POR COINCIDENCIA EN LPB, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('MAYRA GISEL GONZALEZ CORDERO','','OMNIA GUADALAJARA SA DE CV','03-2024','OFAC','24 HRS','SE REPORTÓ A MAYRA GISEL GONZALEZ CORDERO, CONTRATANTE:OMNIA GUADALAJARA SA DE CV, MARZO 2024, POR COINCIDENCIA EN LPB, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('JULIO ANTONIO CANO PERAZA','39472','GOBIERNO DEL ESTADO LIBRE Y SOBERNO DE Q ROO','08-2024','OFAC','24 HRS','SE REPORTÓ A JULIO ANTONIO CANO PERAZA, QUIEN PARTICIPA EN LA PÓLIZA 39472, CONTRATANTE:GOBIERNO DEL ESTADO LIBRE Y SOBERNO DE Q ROO, AGOSTO 2024, POR COINCIDENCIA EN LPB, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('TERESA GARCIA RAMIREZ','36123','VIGUA SERVICIOS PATRIMONIALES SA DE CV','08-2024','OFAC','24 HRS','SE REPORTÓ A TERESA GARCIA RAMIREZ, QUIEN PARTICIPA EN LA PÓLIZA 36123, CONTRATANTE:VIGUA SERVICIOS PATRIMONIALES SA DE CV, AGOSTO 2024, POR COINCIDENCIA EN LPB, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('GONZALO RANGEL CORTEZ','36123','VIGUA SERVICIOS PATRIMONIALES SA DE CV','08-2024','OFAC','24 HRS','SE REPORTÓ A GONZALO RANGEL CORTEZ, QUIEN PARTICIPA EN LA PÓLIZA 36123, CONTRATANTE:VIGUA SERVICIOS PATRIMONIALES SA DE CV, AGOSTO 2024, POR COINCIDENCIA EN LPB, SE EMITIÓ REPORTE 24 HRS');
INSERT INTO SICAS_OC.COMITECOMCTRL (NOMBRE,POLIZA,CONTRATANTE,MES,LISTA,OPERACION,COMENTARIO) VALUES ('MAYRA GISEL GONZALEZ CORDERO','33075','OMNIA GUADALAJARA SA DE CV','09-2024','OFAC','INUSUAL','EN EL COMITÉ DE OCTUBRE 2024 SE DECIDIÓ REPORTAR AMAYRA GISEL GONZALEZ CORDERO, QUIEN PARTICIPA EN LA PÓLIZA 33075, CONTRATANTE:OMNIA GUADALAJARA SA DE CV, SEPTIEMBRE 2024, POR COINCIDENCIA EN OFAC, SE EMITIÓ REPORTE INUSUAL');

COMMIT;

INSERT INTO SICAS_OC.valores_de_listas VALUES ('CATSTRIE','REPO','REPORTADO',NULL,NULL);
INSERT INTO SICAS_OC.valores_de_listas VALUES ('CATSTRIE','NORE','NO REPORTADO',NULL,NULL);

COMMIT;