---CAMBIAR LONGITUD DE COLUMNA A 10 EN TABLA VALORES DE LISTA

alter table SICAS_OC.VALORES_DE_LISTAS
  modify CODVALOR VARCHAR2(10);
  /


---INSERTS DE PANTILLAS PARA GENERACION DE ARCHIVO TXT EN SESAS.
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,21,'MOTMENDEDN','N','NUMBER',146,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,22,'MONTACUMN','N','NUMBER',146,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,23,'MONTOTALN','N','NUMBER',146,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,24,'R3N','N','NUMBER',146,15,0,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,25,'NUMRECN','N','VARCHAR2',61,20,0,null,null,null,null,null,null);

Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,21,'MOTMENDEDN','N','NUMBER',122,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,22,'MONTACUMN','N','NUMBER',122,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,23,'MONTOTALN','N','NUMBER',122,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,24,'R3N','N','NUMBER',122,15,0,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,25,'NUMRECN','N','VARCHAR2',61,20,0,null,null,null,null,null,null);

Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,25,'MOTMENDEDN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,26,'MONTACUMN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,27,'MONTOTALN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,28,'R3N','N','NUMBER',139,15,0,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,29,'NUMRECN','N','VARCHAR2',66,20,0,null,null,null,null,null,null);

Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,25,'MOTMENDEDN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,26,'MONTACUMN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,27,'MONTOTALN','N','NUMBER',139,15,2,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,28,'R3N','N','NUMBER',139,15,0,null,null,null,null,null,null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_CAMPOS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,ORDENCAMPO,NOMCAMPO,INDCLAVEPRIMARIA,TIPOCAMPO,POSINICAMPO,LONGITUDCAMPO,NUMDECIMALES,VALORDEFAULT,SQLVALIDACION,SQLVALORCAMPO,INDDATOPART,ORDENDATOPART,INDASEG) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,29,'NUMRECN','N','VARCHAR2',66,20,0,null,null,null,null,null,null);

Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MOTMENDEDN',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MONTACUMN',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','MONTOTALN',23,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','R3N',24,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPC','SESASINAPC','NUMRECN',25,'S');

Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MOTMENDEDN',21,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MONTACUMN',22,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','MONTOTALN',23,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','R3N',24,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINAPI','SESASINAPI','NUMRECN',25,'S');

Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MOTMENDEDN',25,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MONTACUMN',26,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','MONTOTALN',27,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','R3N',28,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMC','SESASINGMC','NUMRECN',29,'S');

Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MOTMENDEDN',25,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MONTACUMN',26,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','MONTOTALN',27,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','R3N',28,'S');
Insert into SICAS_OC.ENTREGAS_CNSF_PLANTILLA (CODCIA,CODEMPRESA,CODENTREGA,CODPLANTILLA,CAMPO,ORDEN,INDAPLICA) values (1,1,'SESASINGMI','SESASINGMI','NUMRECN',29,'S');

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MOTMENDEDN','Monto menos deducible');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MONTACUMN','Monto acumulado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MONTOTALN','Monto Total');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','R3N','R3N auxiliar si es mayor');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','NUMRECN','Num Reclamacion');

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MOTMENDEDN','MONT RECL MENOS DEDU');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MONTACUMN','Monto Acumulado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MONTOTALN','Monto Total');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','R3N','Auxiliar');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','NUMRECN','Num Reclamacion');

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MOTMENDEDN','MONT RECL MENOS DEDU');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MONTACUMN','Monto Acumulado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MONTOTALN','Monto Total');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','R3N','Auxiliar');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','NUMRECN','Num Reclamacion');

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MOTMENDEDN','MONT RECL MENOS DEDU');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MONTACUMN','SUMA ACUMULADA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MONTOTALN','MONTO TOTAL');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','R3N','AUXILIAR');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','NUMRECN','NUM RECLAMACION');

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MOTMENDEDN','MOMENDED');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MONTACUMN','MONTSUM');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MONTOTALN','MONTOTAL');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','R3N','R3');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMRECN','NUM_REC');
