REM INSERTING into VALORES_DE_LISTAS
SET DEFINE OFF;
--
--Datos Generales Accidentes Personales Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','SUBSEG','Subtipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','ANOPOL','Año Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','OCUPAC','Ocupación o Giro Económico');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','TIPRIE','Tipo de Riesgo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','NUMASE','Número de Asegurados Póliza Concentrada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','COMDIR','Comisión Directa (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPC','MTODIV','Monto de Dividendo (Con Dos Decimales)');
--
--Emisión Accidentes Personales Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','PERESP','Periodo de Espera');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','PRIDEV','Prima Devengada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','NUMDIA','Número de Días de Renta');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPC','ORDSES','Orden Interno para las Coberturas');
--
--Siniestros Accidentes Personales Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','NUMREC','Número de Reclamación Derivado del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','STSSIN','Estatus de la Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','COBERT','Cobertura Afectada que da Origen al Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','FECNAC','Fecha de Nacimiento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','SEXO','Sexo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','TIPMOV','Tipo de Movimiento de Reclamación I = Inicial, C = Complemento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MTODED','Monto de Deducible (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MTOCOA','Monto de Coaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MTOPAG','Monto Pagado del Siniestro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','MTOREA','Monto Recuperado de Reaseguro (Con Dos Decimales)');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPC','ORDSES','Orden Interno para las Coberturas');
--
--Datos Generales Accidentes Personales Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','SUBSEG','Subtipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','ANOPOL','Año Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','OCUPAC','Ocupación o Giro Económico');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','TIPRIE','Tipo de Riesgo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','COMDIR','Comisión Directa (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATAPI','MTODIV','Monto de Dividendo (Con Dos Decimales)');
--
--Emisión Accidentes Personales Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','PERESP','Periodo de Espera');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','PRIDEV','Prima Devengada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','NUMDIA','Número de Días de Renta');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIAPI','ORDSES','Orden Interno para las Coberturas');
--

--Siniestros Accidentes Personales Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','NUMREC','Número de Reclamación Derivado del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','STSSIN','Estatus de la Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','COBERT','Cobertura Afectada que da Origen al Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','TIPMOV','Tipo de Movimiento de Reclamación I = Inicial, C = Complemento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MTODED','Monto de Deducible (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MTOCOA','Monto de Coaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MTOPAG','Monto Pagado del Siniestro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','MTOREA','Monto Recuperado de Reaseguro (Con Dos Decimales)');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINAPI','ORDSES','Orden Interno para las Coberturas');
--
--Datos Generales Gastos Médicos Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','SUBSEG','Subtipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','ANOPOL','Año Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','MODSUM','Modalidad de Suma Asegurada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','COASEG','Coaseguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','MTODIV','Monto de Dividendo (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMC','COMDIR','Comisión Directa (Con Dos Decimales)');
--
--Emisión Gastos Médicos Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','PRIDEV','Prima Devengada (Con Dos Decimales)');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMC','ORDSES','Orden Interno para las Coberturas');
--
--Siniestros Gastos Médicos Colectivo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','NUMREC','Número de Reclamación Derivado del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','STSSIN','Estatus de la Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','TIPGAS','Tipo de Gasto');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','PERESP','Periodo de Espera');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','TIPPAG','Tipo de Pago');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MTODED','Monto de Deducible (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MTOCOA','Monto de Coaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MTOPAG','Monto Pagado del Siniestro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','MTOREA','Monto Recuperado de Reaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','TIPMOV','Tipo de Movimiento de Reclamación I = Inicial, C = Complemento');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMC','ORDSES','Orden Interno para las Coberturas');
--
--Datos Generales Gastos Médicos Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','SUBSEG','Subtipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','ANOPOL','Año Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','MODSUM','Modalidad de Suma Asegurada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','COASEG','Coaseguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATGMI','COMDIR','Comisión Directa (Con Dos Decimales)');
--
--Emisión Gastos Médicos Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','PRIDEV','Prima Devengada (Con Dos Decimales)');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIGMI','ORDSES','Orden Interno para las Coberturas');
--

--Siniestros Accidentes Personales Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','NUMREC','Número de Reclamación Derivado del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','STSSIN','Estatus de la Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','TIPGAS','Tipo de Gasto');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','PERESP','Periodo de Espera');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','TIPPAG','Tipo de Pago');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MTODED','Monto de Deducible (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MTOCOA','Monto de Coaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MTOPAG','Monto Pagado del Siniestro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','MTOREA','Monto Recuperado de Reaseguro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','TIPMOV','Tipo de Movimiento de Reclamación I = Inicial, C = Complemento');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINGMI','ORDSES','Orden Interno para las Coberturas');
--
--Datos Generales Vida Grupo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','PLANPO','Plan de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','MODPOL','Modalidad de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','FORPAG','Forma de Pago');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','PLAPAG','Plazo de Pago de Primas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','COASEG','Coaseguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','EMISIO','Emisión');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','NUMCER','Número de Certificados');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','COMDIR','Comisión Directa (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','SLFOIN','Saldo del fondo de Inversión (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','SLFOAD','Saldo Fondo en Administración (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','MTODIV','Monto de Dividendo (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVIG','MTORES','Monto de Rescate (Con Dos Decimales)');
--
--Emisión Vida Grupo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','TIPSUM','Tipo de Suma Asegurada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','PERESP','Periodo de Espera');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVIG','ORDSES','Orden Interno para las Coberturas');
--

--Siniestros Vida Grupo
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','STSSIN','Estatus del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTOVEN','Monto de Vencimiento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTORES','Monto de Rescate');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTODIV','Monto de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTOPAG','Monto Pagado del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','MTOREA','Monto Recuperado de Reaseguro');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVIG','ORDSES','Orden Interno para las Coberturas');
--
--Datos Generales Vida Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','PLANPO','Plan de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','MODPOL','Modalidad de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','ENTASE','Entidad del Asegurado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FECEMI','Fecha de Emisión AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','STSCER','Estatus del Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','FORPAG','Forma de Pago');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','PLAPAG','Plazo de Pago de Primas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','COASEG','Coaseguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','EMISIO','Emisión');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','PRICED','Prima Cedida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','COMDIR','Comisión Directa (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','SLFOIN','Saldo del fondo de Inversión (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','SLFOAD','Saldo Fondo en Administración (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','MTODIV','Monto de Dividendo (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEDATVII','MTORES','Monto de Rescate (Con Dos Decimales)');
--
--Emisión Vida Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','TIPSUM','Tipo de Suma Asegurada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','TIPEXT','Tipo de Extraprima');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','SUMASE','Suma Asegurada (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','PRIEMI','Prima Emitida (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','PERESP','Periodo de Espera');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVII','ORDSES','Orden Interno para las Coberturas');
--
--Siniestros Vida Individual
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','CERTIF','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','NUMSIN','Número de Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','COBERT','Cobertura');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','FECOCU','Fecha de Ocurrencia del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','FECREP','Fecha de Reporte del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','FECCON','Fecha de Contabilización del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','FECPAG','Fecha de Pago del Siniestro AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','ENTOCU','Entidad de Ocurrencia del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','STSSIN','Estatus del Siniestro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','CAUSIN','Causa del Siniestro o Reclamación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','MTOREC','Monto de la Reclamación (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','MTOVEN','Monto de Vencimiento (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','MTOPAG','Monto Pagado del Siniestro (Con Dos Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','MTOREA','Monto Recuperado de Reaseguro (Con Dos Decimales)');
--Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESINVII','ORDSES','Orden Interno para las Coberturas');
--
--Emisión Vida Grupo Fonacot
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','POLIZA','Número de Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','CERTI','Número de Certificado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','TIPSEG','Tipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','MODALI','Modalidad de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PLANPO','Plan de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','MONEDA','Moneda');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','ENTCTE','Entidad del Contratante');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','INIVIG','Fecha de Inicio de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','FINVIG','Fecha de Fin de Vigencia de la Póliza AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','FECALT','Fecha de Alta del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','FECBAJ','Fecha de Baja del Certificado AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','FECNAC','Fecha de Nacimiento AAAAMMDD');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SEXO','Sexo: F = Femenino y M = Masculino');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','FORVTA','Forma de Venta');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','POLSTS','Estatus de Póliza (Estatus)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','CERSTS','Estatus de Certificado (Estatus) Debe Ser Igual al Estatus de la Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PDOESP','Periodo de Espera "No Existe Periodo de Espera Valor = 0"');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN1','S.A. Alcanzada Beneficio 1 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN2','S.A. Alcanzada Beneficio 2 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN3','S.A. Alcanzada Beneficio 3 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN4','S.A. Alcanzada Beneficio 4 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN6','S.A. Alcanzada Beneficio 6 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN8','S.A. Alcanzada Beneficio 8 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SABEN9','S.A. Alcanzada Beneficio 9 (Sin Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM1','Prima Emitida Beneficio 1 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM2','Prima Emitida Beneficio 2 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM3','Prima Emitida Beneficio 3 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM4','Prima Emitida Beneficio 4 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM5','Prima Emitida Beneficio 5 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM6','Prima Emitida Beneficio 6 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM7','Prima Emitida Beneficio 7 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM8','Prima Emitida Beneficio 8 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PMAEM9','Prima Emitida Beneficio 9 (Con 2 Decimales)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SLFOAD','Saldo Fondo en Administración');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','MTOVEN','Monto de Vencimiento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','MTORES','Monto de Rescate');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','TIPDIV','Tipo de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','MTODIV','Monto de Dividendo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SUBSEG','Subtipo de Seguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','EMISIO','Emisión');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','ANOPOL','Año Póliza');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','INICOB','Inicio de cobertura 1 = Diferida y 2 = No Diferida');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SADOTA','S.A. Alcanzada de Dotales a Corto Plazo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PRIDOT','Prima Emitida de Dotales a Corto Plazo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PLAPAG','Plazo de Pago de Primas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','TIRGAS','Tipo de Riesgo Asociado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','SLFOIN','Saldo del fondo de Inversión');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','POLCON','Póliza Concentrada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','ASEPOC','Número de Asegurados Póliza Concentrada');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEMIVGF','PCOMA','Punto y Coma (;) para Cerrar el Registro');
--
--Equivalencia de Campos de Datos Generales
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','POLIZA','NUMPOLIZA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','CERTIF','NUMCERTIFICADO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPSEG','TIPOSEGURO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PLANPO','PLANPOLIZA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MODPOL','MODALIDADPOLIZA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MONEDA','MONEDA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','ENTASE','ENTIDADASEGURADO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','INIVIG','FECINIVIG');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FINVIG','FECFINVIG');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECALT','FECALTCERT');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECBAJ','FECBAJCERT');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECNAC','FECNACIM');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECEMI','FECEMISION');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','SEXO'  ,'SEXO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FORVTA','FORMAVTA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','STSCER','STATUSCERT');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPDIV','TIPODIVIDENDO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FORPAG','FORMAPAGO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PLAPAG','PLAZOPAGOPRIMA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','COASEG','COASEGURO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','EMISIO','EMISION');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMCER','CANTCERTIFICADOS');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PRICED','PRIMACEDIDA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','COMDIR','COMISIONDIRECTA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','SLFOIN','SDOFONINV');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','SLFOAD','SDOFONADM');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTODIV','MONTODIVIDENDO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTORES','MONTORESCATE');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','SUBSEG','SUBTIPOSEG');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','ANOPOL','ANIOPOLIZA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','OCUPAC','OCUPACION');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPRIE','TIPORIESGO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMASE','NUMASEGPOL');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MODSUM','MODASUMASEG');
--
--Equivalencia de Campos de Emisión
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','COBERT','COBERTURA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPSUM','TIPOSUMASEG');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PERESP','PERIODOESPERA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','SUMASE','SUMAASEGURADA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PRIEMI','PRIMAEMITIDA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','ORDSES','ORDENSESAS');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','PRIDEV','PRIMADEVENGADA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMDIA','NUMDIASRENTA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPEXT','TIPOEXTRAPRIMA');
--
DELETE FROM SICAS_OC.VALORES_DE_LISTAS WHERE CODLISTA = 'SESINVII'  AND CODVALOR = 'ORDSES'
--Equivalencia de Campos de Siniestros
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMSIN','NUMSINIESTRO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','NUMREC','NUMRECLAMACION');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECOCU','FECOCUSIN');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECREP','FECREPREC');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECCON','FECCONSIN');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECPAG','FECPAGSIN');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','STSSIN','STATUSRECLAMACION');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','ENTOCU','ENTOCUSIN');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTOREC','MONTORECLAMADO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','CAUSIN','CAUSASINIESTRO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTODED','MONTODEDUCIBLE');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTOCOA','MONTOCOASEGURO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTOPAG','MONTOPAGSIN');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTOREA','MONTORECREA');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPMOV','TIPMOVREC');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','MTOVEN','MONTOVENCIMIENTO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPGAS','TIPOGASTO');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','TIPPAG','TIPOPAGO');
--
--Equivalencia de Campos de Log de Errores
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','EPOLIZ','EPOLIZ');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','ECERTI','ECERTI');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','CODERR','CODERR');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','DESCER','DESCER');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SEEQUCAM','FECREG','FECREG');

/*NUEVAS COBERTURAS PARA SESAS*/
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','01','Fallecimiento');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','02','Pérdidas Orgánicas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','03','Muerte accidental (Doble indemnización)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','04','Muerte colectiva (Triple indemnización)');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','05','Invalidez total y permanente');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','06','Gastos funerarios');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','07','Desempleo/ Incapacidad temporal');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','08','Asistencias');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','09','Sobrevivencia');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','10','Exención de pago de prima');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','11','Ahorro / Inversión');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','12','Dotales corto plazo');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','13','Enfermedades graves');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','14','Devolución de prima');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','15','Apoyo por hospitalización');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','16','Indemnización accidentes personales');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','17','Intervención quirúrgica');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS239','99','Otros');
--
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','01','Muerte Accidental');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','02','Pérdidas Orgánicas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','03','Indemnización Diaria por Incapacidad Total o Parcial');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','04','Reembolso de Gastos Médicos Mayores');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','05','Invalidez total y permanente');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','06','Gastos funerarios');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','07','Renta diaria por hospitalización');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','08','Asistencias');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','09','Indemnización enfermedades graves');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','10','Beneficio de recuperación');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','11','Indemnización rotura de huesos');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS92','99','Otras coberturas');
--
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','01','Gastos medicos en el territorio nacional');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','02','Gastos médicos en el extranjero');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','03','Emergencia médica en el extranjero');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','04','Maternidad');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','05','Gastos médicos dentales');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','06','Gastos médicos salud visual');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','07','Renta diaria por hospitalización');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','08','Indemnización por incapacidad');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','09','Muerte accidental');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','10','Gastos funerarios');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','11','Exención de deducible');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','12','Enfermedades graves');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','13','Servicios de asistencia');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS255','99','Otro');
--

/*PLAN DE POLIZA*/
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','01','Temporal');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','02','Vitalicio');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','05','Rentas');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','08','Otros');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','09','Dotal Mixto');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','10','Dotal Puro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS237','11','Seguro de separación');
--
/*TIPOS DE SEGURO*/

INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS254','1','GM Plan Limitado: Planes en donde se excluye a los hospitales de mayor costo.');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS254','2','GM Plan Amplio: Planes que incluyen todos los hospitales, principalmente los de mayor costo');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS254','3','GM Plan Internacional: Planes con cobertura completa Nacional y en el extranjero, incluyendo los hospitales de mayor costo');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS254','4','GM Indemnizatorios: Planes en donde se paga una indemnización o monto fijo en caso de accidente o enfermedad o renta diaria por hospitalización.');

INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS240','G','Seguro de Grupo, otorgado al trabajador por medio de una relación laboral');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS240','C','Seguro de Grupo, distinto de relación laboral');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS240','I','Individual');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS240','F','Familiar');

INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','1','Escolares');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','2','Viajero');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','3','Excursiones');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','4','Trabajadores');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','5','Actividades deportivas');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','6','Servicios bancarios');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS250','9','Otro');

DELETE FROM VALORES_DE_LISTAS WHERE CODLISTA = 'SESAS83';
COMMIT;

Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS83','1','Microseguro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS83','3','Producto Básico estandarizado');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS83','4','Otro');
Insert into SICAS_OC.VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) values ('SESAS83','5','Indemnizatorio');

COMMIT;


INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS258','1','Seguro indemnizatorio');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS258','2','Pago directo');
INSERT INTO VALORES_DE_LISTAS (CODLISTA,CODVALOR,DESCVALLST) VALUES ('SESAS258','3','Reembolso');

COMMIT;