REM INSERTING into SICAS_OC.CONFIG_PLANTILLAS_TABLAS
SET DEFINE OFF;
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATAPC','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIAPC','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINAPC','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATAPI','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIAPI','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINAPI','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATGMC','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIGMC','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINGMC','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATGMI','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIGMI','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINGMI','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATVIG','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIVIG','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINVIG','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESADATVII','SESAS_DATGEN'    ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIVII','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESASINVII','SESAS_SINIESTROS',1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAEMIVGF','SESAS_EMISION'   ,1,'NA',null,null,'SELECT',null);
--
Insert into SICAS_OC.CONFIG_PLANTILLAS_TABLAS (CODCIA,CODEMPRESA,CODPLANTILLA,NOMTABLA,ORDENPROCESO,TIPOTABLA,WHERETABLA,ORDENCAMPOS,TIPOACCION,CODRUTINA) values (1,1,'SESAERROR','LOGERRORES_SESAS'   ,1,'NA',null,null,'SELECT',null);

COMMIT;