REM INSERTING into COTIZACIONES_GPO_COBERT_WEB
SET DEFINE OFF;
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'BAS');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'CAN');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'EXC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'FUN');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'GRE');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'INV');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'MAA');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'MCA');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26466,'QUI');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26470,'GMAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26470,'MUAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26470,'POAB');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26471,'GMAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26471,'MUAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26471,'POAB');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26472,'GMAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26472,'MUAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26472,'POAB');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26473,'GMAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26473,'MUAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26473,'POAB');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26474,'GMAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26474,'MUAC');
Insert into COTIZACIONES_GPO_COBERT_WEB (CODCIA,CODEMPRESA,IDCOTIZACION,CODGPOCOBERTWEB) values (1,1,26474,'POAB');
commit;


