UPDATE SICAS_OC.APLICACIONES
SET DESCAPLICA ='Administracion de Operaciones Inusuales'
WHERE CODAPLICA = 'ADMOACTI'
;

INSERT INTO SICAS_OC.APLICACIONES VALUES ('DENUPLD','Denuncia Anónima PLD','F');
INSERT INTO SICAS_OC.APLICACIONES VALUES ('ADMLISTN','Administración de Listas Negras','F');
INSERT INTO SICAS_OC.APLICACIONES VALUES ('CRUCEPLD','Cruce Histórico PLD','F');

INSERT INTO SICAS_OC.APLICACIONES VALUES ('REPOPERA','Registro de Operaciones CNSF','F');

INSERT INTO SICAS_OC.APLICACIONES VALUES ('MANTLISN','Administración de Listas Negras','F');
INSERT INTO SICAS_OC.APLICACIONES VALUES ('CONSUPOL','Consulta de Polizas Por Cliente','F');

COMMIT;

INSERT INTO SICAS_OC.TIPO_DE_LISTA VALUES ('CATORAC1','Nuevas reglas para Operaciones Inusuales','USR');
INSERT INTO SICAS_OC.TIPO_DE_LISTA VALUES ('CATORAC2','Nuevas reglas para Operaciones Relevantes','USR');

COMMIT;

INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC1','REGLA1','Periodicidad de pago',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC1','REGLA2','Incremento en monto de prima',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC1','REGLA3','Cambio forma de pago',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC1','REGLA4','Cancelación de póliza anticipada',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC1','REGLA5','Monitor PLD',NULL,NULL);

INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC2','REGLA1','Aprobación efectivo ',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATORAC2','REGLA2','Operación relevante',NULL,NULL);

UPDATE SICAS_OC.VALORES_DE_LISTAS
SET DESCVALLST = 'GRUPO DE ACCION FINANCIERA INTERNACIONAL'
WHERE CODLISTA = 'LISTAO'
    AND CODVALOR = 'GAFI';
    
COMMIT;


INSERT INTO SICAS_OC.TIPO_DE_LISTA VALUES ('STSPLDES','NUEVO CATÁLOGO ESTATUS PLD EMISION Y SINIESTROS','USR');
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('STSPLDES','PEND','PENDIENTE',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('STSPLDES','APRO','APROBADA',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('STSPLDES','RECH','RECHAZADO',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('STSPLDES','OPIN','OPERACION INUSUAL',NULL,NULL);

INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATRESOL','PEP','PEP',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATRESOL','LPB','LPB',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATRESOL','CEL','COINCIDENCIA EN LISTAS',NULL,NULL);
INSERT INTO SICAS_OC.VALORES_DE_LISTAS VALUES ('CATRESOL','CCC','CCC',NULL,NULL);

UPDATE SICAS_OC.VALORES_DE_LISTAS
SET DESCVALLST = 'SIN COINCIDENCIA'
WHERE CODLISTA = 'CATRESOL'
    AND CODVALOR = 'HOMONI';
COMMIT;

 UPDATE SICAS_OC.VALORES_DE_LISTAS
 SET DESCVALLST = 'FISICA'
 WHERE CODLISTA = 'TIPPCN'
    AND CODVALOR = 'FISICA';
    
 UPDATE SICAS_OC.VALORES_DE_LISTAS
 SET DESCVALLST = 'MORAL'
 WHERE CODLISTA = 'TIPPCN'
    AND CODVALOR = 'MORAL';
    
    COMMIT;