REM INSERTING into FACTOR_DEPORTE_ESPECIAL
SET DEFINE OFF;
Insert into FACTOR_DEPORTE_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,DEPORTE,RIESGO,FACTOR) values (1,1,'APCO19','TURISMO1_DF','GMACC','FUTAME','E',24.705287);
Insert into FACTOR_DEPORTE_ESPECIAL (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,DEPORTE,RIESGO,FACTOR) values (1,1,'APCO19','TURISMO1_DF','GMACC','FUTSOC','D',21.056493);
commit;
