REM INSERTING into FACTOR_ESCALA_PO
SET DEFINE OFF;
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'APCO19','TURISMO1','POA','A',2.730233);
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'APCO19','TURISMO1','POB','B',3.16707);
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'APCO19','TURISMO2','POA','A',2.908291);
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'APCO19','TURISMO2','POB','B',3.373619);
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'ESTACA','MAESTRO','POA','A',1.771885);
Insert into FACTOR_ESCALA_PO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,ESCALA,FACTOR) values (1,1,'ESTACA','MAESTRO','POB','B',1.895917);
commit;
