REM INSERTING into FACTOR_NIVEL_HOSPITALARIO
SET DEFINE OFF;
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','NIV001','S',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APIN19','MAESTRO','GMACC','NIV002','N',1.3);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','NIV001','S',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO1','GMACC','NIV002','N',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','NIV001','S',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'APCO19','TURISMO2','GMACC','NIV002','N',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','NIV001','S',1);
Insert into FACTOR_NIVEL_HOSPITALARIO (CODCIA,CODEMPRESA,IDTIPOSEG,PLANCOB,CODCOBERT,CODENDOSO,INDINCLUIDO,FACTOR) values (1,1,'ESTACA','MAESTRO','GMACC','NIV002','N',1.3);
commit;
