
-----INSERTA USUARIO QUE PUEDE MODIFICAR NUMERO DE RECLAMACION.

INSERT INTO SICAS_OC.PARAMETROS_GLOBALES(CODCIA,CODIGO,DESCRIPCION,FUNCIONPARAM) VALUES (1,056,'SICAS_OC,RMALDONADO','Usuario que puede modificar');
COMMIT;

