INSERT INTO SICAS_OC.TIPO_DE_LISTA
VALUES ('GPOCOBWEB', 'AGRUPADOR DE COBERTURAS WEB', 'USR');
--/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('GPOCOBWEB', 'FALLEC', 'FALLECIMIENTO POR CUALQUIER CAUSA');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('GPOCOBWEB', 'GFUN', 'GASTOS FUNERARIOS');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('GPOCOBWEB', 'MUA', 'MUERTE ACCIDENTAL');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('GPOCOBWEB', 'EXPP', 'EXENCION PAGO PRIMAS');
/
INSERT INTO SICAS_OC.VALORES_DE_LISTAS
VALUES ('GPOCOBWEB', 'GRAVEN', 'GRAVES ENFERMEDADES');
/
COMMIT;
/