CREATE INDEX SICAS_OC.REA_DISTRIBUCION_IDX_4 ON SICAS_OC.REA_DISTRIBUCION
(CODCIA, IDPOLIZA, IDTRANSACCION)
LOGGING
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
