
ALTER TABLE AGENTES
ADD
(
INDEXCLUIRHONORARIO	VARCHAR2(1) DEFAULT 'N',
CLAVE_PORTAL		VARCHAR2(10),
PASSWORD_PORTAL	VARCHAR2(25)
)
/
COMMENT ON COLUMN AGENTES.INDEXCLUIRHONORARIO IS 'Identifica si Agente se excluye de pago de honorarios';
COMMENT ON COLUMN AGENTES.CLAVE_PORTAL IS 'Clave del Agente en el portal';
COMMENT ON COLUMN AGENTES.PASSWORD_PORTAL IS 'Password del Agente en el portal';
/
