CREATE SEQUENCE SICAS_OC.SEQ_CTRLMAIL_NOTIF
  MINVALUE 1 
  NOMAXVALUE 
  INCREMENT BY 1 
  START WITH  1 
  NOCYCLE 
  ORDER;
/

CREATE OR REPLACE PUBLIC SYNONYM SEQ_CTRLMAIL_NOTIF FOR SICAS_OC.SEQ_CTRLMAIL_NOTIF;
/

GRANT SELECT ON SICAS_OC.SEQ_CTRLMAIL_NOTIF TO PUBLIC;