----------------- SYNONYM ------------------
CREATE OR REPLACE PUBLIC SYNONYM ESTIMADOS_SINIESTROS
  FOR ESTIMADOS_SINIESTROS;      
  
CREATE OR REPLACE PUBLIC SYNONYM APROBACIONES_ANULADAS
  FOR APROBACIONES_ANULADAS;   

CREATE OR REPLACE PUBLIC SYNONYM APROBACIONES_PAGADAS
  FOR APROBACIONES_PAGADAS;


----------------- GRANTS ------------------
GRANT EXECUTE ON ESTIMADOS_SINIESTROS  TO PUBLIC;

GRANT EXECUTE ON APROBACIONES_ANULADAS TO PUBLIC;

GRANT EXECUTE ON APROBACIONES_PAGADAS  TO PUBLIC;