CREATE SEQUENCE SQ_FACT_ELECT_DOCUMENTO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
CREATE OR REPLACE PUBLIC SYNONYM  SQ_FACT_ELECT_DOCUMENTO FOR SICAS_OC.SQ_FACT_ELECT_DOCUMENTO;
/
GRANT SELECT ON SQ_FACT_ELECT_DOCUMENTO TO PUBLIC;