DROP PUBLIC SYNONYM PROVEEDORES_SAT_DESVIRTUADOS

-- Crea el Sinónimo
-- =============================
CREATE or replace PUBLIC SYNONYM PROVEEDORES_SAT_DESVIRTUADOS FOR PROVEEDORES_SAT_DESVIRTUADOS;
/
