--------------------------------------------------------------
-- INSERT A LA TABLA DE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS
--
-- Descripción:
-- Este script crea los permisos por grupo en la tabla SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS para el aplicativo de archivos polizas.
-- Para todos los grupos excepto EMISION y SUPERVIS, se inserta solo el campo CODGRUPO,
-- ya que los demás campos tienen valor por defecto 'N'.
-- Para los grupos EMISION y SUPERVIS se otorgan todos los permisos explícitamente ('S').
--------------------------------------------------------------

-- Grupos con acceso completo.
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS 
(CODGRUPO, METRICAS, REPOSITORIO, GESTION_USUARIOS, EDICION_ARCHIVOS, ELIMINAR_ARCHIVOS, PAPELERIA_RECICLAJE, HIST_CAMBIOS, CARGA_ARCHIVOS, ACCESO_APLICATIVO)
VALUES ('EMISION','S','S','S','S','S','S','S','S','S');

INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS 
(CODGRUPO, METRICAS, REPOSITORIO, GESTION_USUARIOS, EDICION_ARCHIVOS, ELIMINAR_ARCHIVOS, PAPELERIA_RECICLAJE, HIST_CAMBIOS, CARGA_ARCHIVOS, ACCESO_APLICATIVO)
VALUES ('SUPERVIS','S','S','S','S','S','S','S','S','S');


-- Grupos sin acceso por default.
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('ADMRIESG');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('ASISTCON');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('ASISTENC');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('AUDITO');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('CONPRSAT');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('CONQEQ');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('CONSUL');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('DIRFINAN');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('DIRGRAL');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('DIRREGIO');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('DIRSECLI');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('DSERVCLI');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('EMIFAC');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('EMISSPC');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('EXTERNO');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('FINANZAS');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('GOBDAT');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('IMPLANT');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('IMPLEMEN');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('INACT');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('REASEGUR');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('RECHUMAN');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('RIESGOS');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SERVASEG');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SERVGENE');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINANAAP');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINANAVD');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINASCON');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINASIST');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINCONSU');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINCONTA');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINDICTA');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINPEREX');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINSUPAP');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINSUPDI');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINSUPER');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SINSUPVD');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('SUSCRIP');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('TECCOMOD');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('TECCONSU');
INSERT INTO SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) VALUES ('TECNICA');

COMMIT;
/