--------------------------------------------------------------------------------
                    --TABLA PARA PERMISOS_ARCHIVOS_POLIZAS--
--------------------------------------------------------------------------------
DROP PUBLIC SYNONYM PERMISOS_ARCHIVOS_POLIZAS;

CREATE TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (
    "CODGRUPO"              VARCHAR2(10),                           -- Código del grupo de usuarios
    "CREATED"               DATE DEFAULT SYSDATE,                   -- Fecha de creación del registro
    "CREATED_BY"            VARCHAR2(50) DEFAULT USER,              -- Usuario que creó el registro
    "UPDATED"               DATE DEFAULT SYSDATE,                   -- Fecha de última actualización del registro
    "UPDATED_BY"            VARCHAR2(50) DEFAULT USER,              -- Usuario que actualizó por última vez
    "METRICAS"              CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para acceder a métricas (S/N)
    "REPOSITORIO"           CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para ver el repositorio de archivos (S/N)
    "GESTION_USUARIOS"      CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para acceder a la gestionar permisos de usuarios (S/N)
    "EDICION_ARCHIVOS"      CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para editar archivos (S/N)
    "ELIMINAR_ARCHIVOS"     CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para eliminar archivos (S/N)
    "PAPELERIA_RECICLAJE"   CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para acceder a la papelera de reciclaje (S/N)
    "HIST_CAMBIOS"          CHAR(1) DEFAULT 'N' NOT NULL ENABLE,    -- Permiso para ver el historial de cambios (S/N)
    "CARGA_ARCHIVOS"        CHAR(1) DEFAULT 'N',                    -- Permiso para cargar archivos (S/N)
    "ACCESO_APLICATIVO"     CHAR(1) DEFAULT 'N' NOT NULL ENABLE     -- Permiso para ingresar al aplicativo (S/N)
) TABLESPACE TS_SICASOC;


--ÍNDICES
CREATE UNIQUE INDEX SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS_INDX ON SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS (CODGRUPO) TABLESPACE IDX_SICASOC;
/

--PRIMARY KEY
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT PK_PERMISOS_ARCHIVOS_POLIZAS PRIMARY KEY (CODGRUPO) USING INDEX;
/

--CHECK CONSTRAINTS
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_METRICAS CHECK (METRICAS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_REPOSITORIO CHECK (REPOSITORIO IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_GESTION_USUARIOS CHECK (GESTION_USUARIOS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_EDICION_ARCHIVOS CHECK (EDICION_ARCHIVOS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_ELIMINAR_ARCHIVOS CHECK (ELIMINAR_ARCHIVOS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_PAPELERIA_RECICLAJE CHECK (PAPELERIA_RECICLAJE IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_HIST_CAMBIOS CHECK (HIST_CAMBIOS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_CARGA_ARCHIVOS CHECK (CARGA_ARCHIVOS IN ('S', 'N')) ENABLE;
ALTER TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS ADD CONSTRAINT CHK_ACCESO_APLICATIVO CHECK (ACCESO_APLICATIVO IN ('S', 'N')) ENABLE;
/

--GRANT
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS TO ROL_MODIFICA_SICAS;
GRANT SELECT ON SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS TO ROL_CONSULTA_SICAS;
/

--SINÓNIMO
CREATE OR REPLACE PUBLIC SYNONYM PERMISOS_ARCHIVOS_POLIZAS FOR SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS;

--COMENTARIOS DESCRIPTIVOS
COMMENT ON TABLE SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS                     IS 'Tabla que define los permisos de acceso y acciones para cada grupo de usuarios en el módulo de archivos de pólizas';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.CODGRUPO           IS 'Código del grupo de usuarios';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.CREATED            IS 'Fecha de creación del registro';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.CREATED_BY         IS 'Usuario que creó el registro';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.UPDATED            IS 'Fecha de última actualización del registro';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.UPDATED_BY         IS 'Usuario que actualizó por última vez';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.METRICAS           IS 'Permiso para acceder a métricas (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.REPOSITORIO        IS 'Permiso para ver el repositorio de archivos (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.GESTION_USUARIOS   IS 'Permiso para gestionar usuarios (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.EDICION_ARCHIVOS   IS 'Permiso para editar archivos (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.ELIMINAR_ARCHIVOS  IS 'Permiso para eliminar archivos (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.PAPELERIA_RECICLAJE IS 'Permiso para acceder a la papelera de reciclaje (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.HIST_CAMBIOS       IS 'Permiso para ver el historial de cambios (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.CARGA_ARCHIVOS     IS 'Permiso para cargar archivos (S/N)';
COMMENT ON COLUMN SICAS_OC.PERMISOS_ARCHIVOS_POLIZAS.ACCESO_APLICATIVO  IS 'Permiso para ingresar al aplicativo (S/N)';